[TeamsAppIcon] Add icon relationships to teamsAppDefinition and teamsAppIcon entity type
microsoftgraph/microsoft-graph-docs pull request #12188
Opened 2021-04-01 18:27 UTC by jessiechan27

2021-04-01 19:51 UTC, opbld34 commented
Docs Build status updates of commit _[e171b7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e171b7c12e5311ebb2b37af815b1f7268d884c34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104011950375544-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=745s4wNKPAc7tP2qZGjlb5j4W0iAPhqmWpUx%2BrMOJAs%3D&st=2021-04-01T19%3A46%3A47Z&se=2021-05-02T19%3A51%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 20:30 UTC, opbld31 commented
Docs Build status updates of commit _[bab4879](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bab4879e521d6bf4845b93512b5bd3303116f544)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104012029215097-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MewaIxbki9e5gaFYUdj1HVjB3b2qP6FryWZKm7lmPzw%3D&st=2021-04-01T20%3A25%3A39Z&se=2021-05-02T20%3A30%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 09:33 UTC, AkJo commented on api-reference/beta/resources/teamsappdefinition.md
> +|:------------------- |:-------- |:------------------------------------------------------ |
FYI, you dont really to make this spacing change...

2021-04-02 09:36 UTC, AkJo commented on api-reference/beta/resources/teamsappdefinition.md
> +| colorIcon      |[teamsAppIcon](teamsappicon.md) | The URL indicating where the color icon can be found.       |
The colorIcon is not a url. It is a entity containing multiple items, one of which is the url. Rephrase this accordingly.


The color version of the Teams app's icon.
The outline version of the Teams app's icon.

2021-04-02 09:38 UTC, AkJo commented on api-reference/beta/resources/teamsappicon.md
> +| webUrl        | string                      | The publicly-accessible URL where the app icon can be found.                            |
The web url that can be used for downloading the image.

2021-04-02 09:42 UTC, AkJo commented on api-reference/beta/resources/teamsappdefinition.md
You need to have pages for the following APIs:

teamsappicon-get.md
/appCatalogs/teamsApps/{teams-app-id}/appDefinitions/{appDefinition-id}/outlineIcon/hostedContent/$value
/appCatalogs/teamsApps/{teams-app-id}/appDefinitions/{appDefinition-id}/colorIcon/hostedContent/$value

You should crossreference these as methods inside teamsAppDefinition.md

Add an entry in the ToC for Get app icons that should point to this teamsappicon-get.md

2021-04-02 15:16 UTC, jessiechan27 commented on api-reference/beta/resources/teamsappdefinition.md
> +| colorIcon      |[teamsAppIcon](teamsappicon.md) | The URL indicating where the color icon can be found.       |
ok! I was just following what was written in this proposal: 
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/7385?_a=files

Does that mean the proposal doesn't always match the correct definition?

2021-04-02 15:23 UTC, jessiechan27 commented on api-reference/beta/resources/teamsappicon.md
> +| webUrl        | string                      | The publicly-accessible URL where the app icon can be found.                            |
same question as above

2021-04-02 15:31 UTC, opbld30 commented
Docs Build status updates of commit _[4b68714](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b68714cffa241aa3b468b71c56174444e8c13cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104021529231540-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XiMjJK4HaIxb4OKDXBw0c2uGbiR%2BEEqUR0bk2q5KRXw%3D&st=2021-04-02T15%3A26%3A31Z&se=2021-05-03T15%3A31%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 18:13 UTC, subray2014 commented on api-reference/beta/api/teamsappicon-get.md
> +**Get icon in color version**
Would it be better to name this:
"Get color icon of a teams app definition"

2021-04-06 18:14 UTC, subray2014 commented on api-reference/beta/api/teamsappicon-get.md
> +**Get icon in outline version**
Same comment here:
Would it be better to name this:
"Get outline icon of a teams app definition"

2021-04-06 18:17 UTC, subray2014 commented on api-reference/beta/api/teamsappicon-get.md
> +## Examples
We would want at least 4 examples:
1. Color icon where web url is public cdn.
2. Color icon where web url is teams hosted content.
3. Outline icon where web url is public cdn.
4. Outline icon where web url is teams hosted content.

You have 3 of these right now.
The example on expansion of hosted content is probably not needed since you already have a separate page for icon hosted content.

2021-04-06 18:48 UTC, opbld33 commented
Docs Build status updates of commit _[cc60a86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc60a86ef5a0f00a9c890de5234f1cf5e765e643)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8111347c)
[api-reference/beta/api/teamsappicon-get-hostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get-hostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get-hostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-8111347c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061847096137-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=56YqR4Fnvr9IrHRn4q1MQg5PwMcBaqeJZkJ1o4sBFyM%3D&st=2021-04-06T18%3A43%3A29Z&se=2021-05-07T18%3A48%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 18:50 UTC, subray2014 commented on api-reference/beta/api/teamsappicon-get-hostedcontent.md
> +**Get hosted content bytes in app icon for an image**
Would this sound better:
Get the raw value of hosted content (the image) in a Teams App icon.

2021-04-06 18:50 UTC, subray2014 commented on api-reference/beta/api/teamsappicon-get-hostedcontent.md
> +## Optional query parameters
There are two kinds of requests in this. 1 for hosted content which does support $select and the other for $value which doesnt.
I would suggest splitting these two requests into different sections for clarity.

2021-04-06 19:23 UTC, opbld30 commented
Docs Build status updates of commit _[ebf8fcb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebf8fcbcb9421166c18a869f4d2b5ae8303aef01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2bc39912)
[api-reference/beta/api/teamsappicon-get-hostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get-hostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get-hostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-2bc39912"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061921520544-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B0T4sV8gX9zxzUxCudBP2D6CASqF2PwuMba00k5FEHg%3D&st=2021-04-06T19%3A18%3A08Z&se=2021-05-07T19%3A23%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 19:24 UTC, jessiechan27 commented on api-reference/beta/api/teamsappicon-get-hostedcontent.md
> +**Get hosted content bytes in app icon for an image**
hmm I think so too. I was following the existing "Get chatMessageHostedContent" page:
https://docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta

I'll change it for that page as well

2021-04-06 19:29 UTC, opbld31 commented
Docs Build status updates of commit _[107b3d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/107b3d27c061d26be74b70455422058025de41b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-498a392e)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get-hostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get-hostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get-hostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-498a392e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061927422035-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u5Q3igVDHw%2BiwnThTdGwzOT9OxsPxTpAN6WcUHaNO6k%3D&st=2021-04-06T19%3A24%3A00Z&se=2021-05-07T19%3A29%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 19:34 UTC, opbld34 commented
Docs Build status updates of commit _[4f0f5c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f0f5c97f65bce48ae2f380e6e193f53905ae812)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1aa8ae4d)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get-hostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get-hostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get-hostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-1aa8ae4d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061933083706-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lUb43vDoKSkNSl6zsw4ZlOwDTtwZe0Qs0X0lB2uirsk%3D&st=2021-04-06T19%3A29%3A26Z&se=2021-05-07T19%3A34%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 19:46 UTC, opbld31 commented
Docs Build status updates of commit _[088d833](https://github.com/microsoftgraph/microsoft-graph-docs/commits/088d8334f35a1ebf65849e4a985e62fb03623c53)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9d474801)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get-hostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get-hostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get-hostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-9d474801"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061944518556-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wNe6NGXTsuQjkDqYHJAP9jXPAZ6VXj2AQ5YHabkZ7GU%3D&st=2021-04-06T19%3A41%3A20Z&se=2021-05-07T19%3A46%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 19:57 UTC, opbld34 commented
Docs Build status updates of commit _[4d1e8c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d1e8c33db30209fcdfce8b1a15808c132cd7362)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-549f4d2a)
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get-hostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get-hostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get-hostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-549f4d2a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061955498616-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hmajRdjwOxCa4GIHj4ojI1dj8B1cYqGsq9GrD6b1OC4%3D&st=2021-04-06T19%3A52%3A18Z&se=2021-05-07T19%3A57%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 19:58 UTC, jessiechan27 commented on api-reference/beta/api/teamsappicon-get-hostedcontent.md
> +## Optional query parameters
I changed it to match the "Get chatMessageHostedContent" API page by removing the $value API from HTTP Request section but keeping it in the Examples. I also added a note in the example to say that $value doesn't support any query parameters. Hope that works.

2021-04-07 16:36 UTC, subray2014 commented on api-reference/beta/api/teamsappicon-get.md
> +### Example 4: Get outline icon of a public Teams app.
I think the term we use for apps published by msft is "Store" apps. Confirm with Anand.

2021-04-07 16:37 UTC, subray2014 approved these changes

2021-04-09 17:03 UTC, opbld31 commented
Docs Build status updates of commit _[090048d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/090048dc24a09845f38c4f8b48253a440f596e54)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a9247ef2)

<a id="a9247ef2"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104091702375525-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i8tb7psGMVYPRFG0ZI%2B18CCvYsH9V8HBhvsomJ86RRk%3D&st=2021-04-09T16%3A58%3A02Z&se=2021-05-10T17%3A03%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-09 17:10 UTC, opbld31 commented
Docs Build status updates of commit _[b7add24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7add24fb13a386f8c94ff48fa901d55b205cb71)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9141c266)

<a id="9141c266"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104091709125860-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vjxYb%2Bcm1VF4XgZo9aOJAtHVewt9VXfwek02xxpCV%2BU%3D&st=2021-04-09T17%3A05%3A32Z&se=2021-05-10T17%3A10%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 19:17 UTC, opbld34 commented
Docs Build status updates of commit _[b76016e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b76016e20dc2c53d294614e458c53320bb9e8ad0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f72a0f2b)

<a id="f72a0f2b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104121917413131-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UCzExGyw%2FASq2vhXeizqnBQ3nGmvzeYqo6aXIeJY2K0%3D&st=2021-04-12T19%3A12%3A58Z&se=2021-05-13T19%3A17%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 19:19 UTC, AkJo approved these changes

2021-04-12 19:19 UTC, opbld32 commented
Docs Build status updates of commit _[3a3c622](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a3c622bca0742fc4f4588bbc027812540912fb8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-342220ee)

<a id="342220ee"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104121919348842-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y7gaOpmctx7jY0P900Fh7Zwj%2FCF43f9kaRHQMfu%2Fi2Y%3D&st=2021-04-12T19%3A14%3A55Z&se=2021-05-13T19%3A19%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-13 02:25 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get-hostedcontent.md
> +title: "Get hostedContent in a Teams app icon"
This topic should be teamworkhostedcontent-get. The H1 and title would then be "Get teamworkHostedContent".

2021-04-13 02:27 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get-hostedcontent.md
> +### Example 1: Get the bytes of the hosted content of the color icon of a Teams App.
Don't include ending punctuation in headings; delete the period here.

2021-04-13 02:28 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get.md
> +title: "Get teamsAppIcon of a TeamsApp"
The title and H1 should just be "Get teamsAppIcon".

2021-04-13 02:31 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get.md
> +### Example 1: Get color icon of a Teams app which is a 'custom' app.
Global: We shouldn't have formatting like the apostrophes around words for emphasis. You can simplify this heading as "Get color icon of a custom Teams app". Please apply the same pattern to the following H3 headings as well.

2021-04-13 02:32 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get.md
> +The following example shows the response for an organizational app. *Note:* Accessing the actual [image of the custom app's icon](teamsappicon-get-hostedcontent.md) requires a Microsoft Graph token t
Actually format the Note as a Note. Start on a new line and precede with a ">" character. Make the word Note bold, not italics.

2021-04-13 02:33 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get.md
> +The following example shows the response for an organizational app. *Note:* Accessing the actual [image of the custom app's icon](teamsappicon-get-hostedcontent.md) requires a Microsoft Graph token t
Apply the same note formatting here.

2021-04-13 02:35 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get-hostedcontent.md
> +---
Global: Delete this extra line that was left behind I assume from copying an existing operation topic and removing the snippets?

2021-04-13 02:36 UTC, Lauragra commented on api-reference/beta/resources/teamsappdefinition.md
> +| teamsAppId          | string   | The id from the Teams App manifest.                    |
Global: Teams App should be Teams app in all cases (no reason to capitalize the word app).

2021-04-13 02:37 UTC, Lauragra commented on api-reference/beta/resources/teamsappdefinition.md
> +| id                  | string   | A unique id (not the teams appid).                     |
Global: When you refer to the abbreviation for identifier in text, it's ID (all caps).

2021-04-13 02:38 UTC, Lauragra commented on api-reference/beta/resources/teamsappicon.md
> +| [Get icon of app](../api/teamsappicon-get.md)     | [teamsAppIcon](teamsappicon.md)                   | Get an icon associated with a specific version of a Teams app. |
The link text can just be Get icon and Get hosted content.

2021-04-13 02:39 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: App Icon
Lowercase the word Icon. Use the shortened operation names for the TOC entries - Get icon, Get hosted content.

2021-04-13 02:40 UTC, Lauragra commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the [teamsAppIcon](https://docs.microsoft.com/en-us/graph/api/resources/teamsAppIcon?view=graph-rest-beta) resource type.",
Mention the GET operations in the changelog as well?

2021-04-13 02:43 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: App Icon
Also, the TOC entries are currently under App catalog; should they be under the App node?

2021-04-13 02:43 UTC, Lauragra requested changes
Please address comments and fix the merge conflicts before we merge.

2021-04-14 05:28 UTC, AkJo commented on api-reference/beta/api/teamsappicon-get.md
> +### Example 1: Get color icon of a Teams app which is a 'custom' app.
The apostrophe is not exactly for emphasis but to draw attention to the special connotation of the term 'custom' here. It has very specific semantics in the MS Teams domain.

2021-04-14 05:29 UTC, AkJo commented on api-reference/beta/api/teamsappicon-get.md
> +### Example 1: Get color icon of a Teams app which is a 'custom' app.
Another option would be to italicize it instead. Please suggest if that would be better.

2021-04-14 05:57 UTC, opbld33 commented
Docs Build status updates of commit _[f3070de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3070de653f4736c4a71c9d71de5801eb1261707)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b4556a31)

<a id="b4556a31"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104140556570357-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c%2BUMVJ%2B6jRQOFkKJjK3t2vknvqvt3rFSK9VlaSL%2F%2F08%3D&st=2021-04-14T05%3A52%3A15Z&se=2021-05-15T05%3A57%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 06:02 UTC, opbld30 commented
Docs Build status updates of commit _[2536f4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2536f4efc1813d32beeeaa0044b73133d4f508ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappicon-get-hostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get-hostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get-hostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12188) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104140600316138-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GPSILnAr7FqSoo9vyYqsHk9s82L8h3sFFyJpfAQSfLs%3D&st=2021-04-14T05%3A56%3A59Z&se=2021-05-15T06%3A01%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 06:19 UTC, opbld32 commented
Docs Build status updates of commit _[a14e638](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a14e63875903523200bb8c54d5494d8545afa305)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamworkhostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamworkhostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkhostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12188) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104140617464395-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pZyyWzKg02InFAg4q0ZnrVrOA3g94dpZ0mYgMgcaDNk%3D&st=2021-04-14T06%3A14%3A04Z&se=2021-05-15T06%3A19%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 16:29 UTC, Lauragra commented on api-reference/beta/api/teamsappicon-get.md
> +### Example 1: Get color icon of a Teams app which is a 'custom' app.
Can we use tic marks? If not then I guess italics would be better than the apostrophes.

2021-04-16 05:54 UTC, opbld30 commented
Docs Build status updates of commit _[e464c52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e464c52ab77df63d2da6c28a9b6369ec6ba25d20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamworkhostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamworkhostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkhostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12188) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104160552282024-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pe1i%2FZF2ubWvzRjgpLSyVtxQFdzBB4nVz4TLEueevT4%3D&st=2021-04-16T05%3A49%3A47Z&se=2021-05-17T05%3A54%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:57 UTC, opbld34 commented
Docs Build status updates of commit _[e542ce6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e542ce6d09f30110b80f0e13696c48cf55809fed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamworkhostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamworkhostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkhostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12188) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170156098220-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cUfWIHwSXNBKHgQJGFztKGi9jf%2FkC4TxAxCdRjDYB2I%3D&st=2021-04-17T01%3A52%3A23Z&se=2021-05-18T01%3A57%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:58 UTC, Lauragra approved these changes

2021-04-17 01:58 UTC, opbld32 commented
Docs Build status updates of commit _[e542ce6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e542ce6d09f30110b80f0e13696c48cf55809fed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamworkhostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamworkhostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkhostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12188) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170156196970-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BLQ3rYCM5ZMrvirYfGbFtAC6S9q6i4Q205IsK3TxDcs%3D&st=2021-04-17T01%3A53%3A44Z&se=2021-05-18T01%3A58%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 02:00 UTC, opbld32 commented
Docs Build status updates of commit _[71c9c05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71c9c05d4a5b61c79ecfc2512d55e0ac4f39f0ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamworkhostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamworkhostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkhostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12188) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170157331102-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2SZmYv4UNrwXBWvf7tXYt5U1Fx1tkURISlC33DauP1U%3D&st=2021-04-17T01%3A55%3A06Z&se=2021-05-18T02%3A00%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 02:01 UTC, opbld33 commented
Docs Build status updates of commit _[2575618](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25756181d7919e3ad1d71b2e642113cdd2491cf3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamsappicon-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/api/teamworkhostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/api/teamworkhostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkhostedcontent-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamsappicon.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamsappicon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappicon?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/resources/teamworkhostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/resources/teamworkhostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkhostedcontent?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&branch=pr-en-us-12188) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12188) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/app-icons/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170159271205-12188%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ri09Jpsi7VQ6PovezREcxCp41yK1fTWLJx1cmRMO1k0%3D&st=2021-04-17T01%3A56%3A24Z&se=2021-05-18T02%3A01%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 02:02 UTC, merged