Adds information about caching in MGT components
microsoftgraph/microsoft-graph-docs pull request #12227
Opened 2021-04-07 11:38 UTC by waldekmastykarz

Adds information about caching in components. Closes https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/964

2021-04-07 11:40 UTC, opbld34 commented
Docs Build status updates of commit _[280439d](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/280439da4ce610d78b02c71cc0abc429c5a8e08a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12227) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12227) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12227) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12227) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12227) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12227) |
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12227) |
[concepts/toolkit/components/teams-channel-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/teams-channel-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/teams-channel-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12227) |
[concepts/toolkit/customize-components/cache.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/customize-components/cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/cache?branch=pr-en-us-12227) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104071138350733-12227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n7MJNwSl9FVbC4L4OsK2mRQK8N3RzT%2BovVRamRfN0Bw%3D&st=2021-04-07T11%3A35%3A08Z&se=2021-05-08T11%3A40%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 02:59 UTC, nmetulev requested changes
Awesome, this makes it so much more clear

Left few suggestions,
* I changed `IndexedDB` to `Object store` in the tables
* Added a line after each table to point to the caching docs for more details

2021-04-08 02:59 UTC, nmetulev commented on concepts/toolkit/components/get.md
> +`response`|Complete response retrieved from Microsoft Graph for the query specified in the `resource` property of `mgt-get`|
Should we also add a little about when the components cache the data and a link to more info about caching?

Ex:
```suggestion
## Cache

To enable and configure the cache, use the `cacheEnabled` and `cacheInvalidationPeriod` properties. By default, the `mgt-get` component does not cache any responses.

|Object store|Cached data|Remarks|
|-----------|-----------|-------|
|`response`|Complete response retrieved from Microsoft Graph for the query specified in the `resource` property of `mgt-get`|

See [Caching](../customize-components/cache.md) for more details.
```

2021-04-08 02:59 UTC, nmetulev commented on concepts/toolkit/components/people-picker.md
> +
```suggestion
## Cache

|Object store|Cached data|Remarks|
|---------|-----------|-------|
|`groups`|List of groups|Used when `type` is set to `PersonType.group`|
|`people`|List of people|Used when `type` is set to `PersonType.person` or `PersonType.any`|
|`users`|List of users|Used when `groupId` specified|

See [Caching](../customize-components/cache.md) for more details on how to configure the cache.
```

2021-04-08 02:59 UTC, nmetulev commented on concepts/toolkit/customize-components/cache.md
> +The data for each entity is stored in a separate IndexedDB. You can view the cache on the developer panel. On the **Application** tab, in the **Storage** pane, go to the **IndexedDB** tab.
```suggestion
Databases created by mgt for caching are prefixed with `mgt-`. The data for each entity is stored in a separate object store. To inspect the cache, use the **Application** tab in the developer panel (F12 tools) - under the **Storage** section, click on the **IndexedDB** tab. 
```

2021-04-08 02:59 UTC, nmetulev commented on concepts/toolkit/components/people.md
> +
```suggestion
## Cache

|Object store|Cached data|Remarks|
|---------|-----------|-------|
|`people`|Information about people matching the query|Used when `resource` specified|
|`users`|Information about users matching the query|Used when `groupId`, `userIds`, `peopleQueries` or no properties specified|
|`presence`|Presence for the specified set of people|Used when `showPresence` set to `true`|

> [!NOTE]
> By default, the `mgt-people` component uses the [`mgt-person`](./person.md) component to display information about people. The `mgt-person` component automatically downloads and caches the photo for each person.

See [Caching](../customize-components/cache.md) for more details on how to configure the cache.
```

2021-04-08 02:59 UTC, nmetulev commented on concepts/toolkit/components/person-card.md
> +`users`|Person's user information|Used when `userId` is specified or the `personQuery` is set to `me`
```suggestion
## Cache

> [!IMPORTANT]
> The `mgt-person-card` component retrieves the basic person data from the parent `mgt-person` component without calling Microsoft Graph. When `mgt-person-card` is used separately, it will retrieve the necessary data itself and cache it. The data displayed in card's sections is retrieved separately and is not cached.

|Object store|Cached data|Remarks|
|---------|-----------|-------|
|`people`|Person's information|Used when `personQuery` is specified and its value is different than `me`|
|`photos`|Person's photo|
|`presence`|Person's presence|Used, when `showPresence` is set to `true`|
|`users`|Person's user information|Used when `userId` is specified or the `personQuery` is set to `me`|

See [Caching](../customize-components/cache.md) for more details on how to configure the cache.

```

2021-04-08 02:59 UTC, nmetulev commented on concepts/toolkit/components/person.md
> +
```suggestion
## Cache

|Object store|Cached data|Remarks|
|---------|-----------|-------|
|`photos`|Person's photo|Used, when `avatarType` is set to `photo` and `fetchImage` is set to `true`|
|`presence`|Person's presence|Used, when `showPresence` is set to `true`|
|`users`|Person's user information|

See [Caching](../customize-components/cache.md) for more details on how to configure the cache.

```

2021-04-08 06:31 UTC, waldekmastykarz commented on concepts/toolkit/components/get.md
> +`response`|Complete response retrieved from Microsoft Graph for the query specified in the `resource` property of `mgt-get`|
Ah missed that! I thought `mgt-get` cache was enabled by default like it is for other components. Good catch!

2021-04-08 06:43 UTC, opbld32 commented
Docs Build status updates of commit _[371b41e](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/371b41ef694d9fd122d3d7c5e150321f250bc961)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12227) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12227) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12227) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12227) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12227) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12227) |
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12227) |
[concepts/toolkit/components/teams-channel-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/teams-channel-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/teams-channel-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12227) |
[concepts/toolkit/customize-components/cache.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/customize-components/cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/cache?branch=pr-en-us-12227) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104080631487877-12227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vPZMdsHcYRKHZkXbWiiZ4qwwdc%2Fu1KgBs1clj3QhnRM%3D&st=2021-04-08T06%3A38%3A20Z&se=2021-05-09T06%3A43%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 06:45 UTC, opbld34 commented
Docs Build status updates of commit _[371b41e](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/371b41ef694d9fd122d3d7c5e150321f250bc961)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12227) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12227) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12227) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12227) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12227) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12227) |
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12227) |
[concepts/toolkit/components/teams-channel-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/teams-channel-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/teams-channel-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12227) |
[concepts/toolkit/customize-components/cache.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/customize-components/cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/cache?branch=pr-en-us-12227) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104080631385278-12227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wMYsUAfgVfWxlr2se%2BRFf9Sx4BW2jJqyOktmxIHdKL0%3D&st=2021-04-08T06%3A40%3A39Z&se=2021-05-09T06%3A45%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 06:45 UTC, opbld31 commented
Docs Build status updates of commit _[4b1a671](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/4b1a6715dd575ce3b377cdab7ea89ab8ec16ddfd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-84b6579d)

<a id="84b6579d"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104080632053794-12227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CCSdEEplkzMAD5ytmB5Gh%2F5wVynZhr9leKAi2PYqHf0%3D&st=2021-04-08T06%3A40%3A52Z&se=2021-05-09T06%3A45%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 06:48 UTC, opbld30 commented
Docs Build status updates of commit _[8f01649](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/8f01649ebb57b08800e5025264c6b8725454ea14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12227) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12227) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12227) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12227) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12227) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12227) |
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12227) |
[concepts/toolkit/components/teams-channel-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/teams-channel-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/teams-channel-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12227) |
[concepts/toolkit/customize-components/cache.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/customize-components/cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/cache?branch=pr-en-us-12227) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104080631555229-12227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LnhL3GcnqI1fT34Sqsq4QQKD7MamY0xB8ba5XpMb0S4%3D&st=2021-04-08T06%3A43%3A12Z&se=2021-05-09T06%3A48%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 06:50 UTC, opbld33 commented
Docs Build status updates of commit _[7c0ac4c](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/7c0ac4cad08334489e2a84d79dc73cb9400b4585)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12227) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12227) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12227) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12227) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12227) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12227) |
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12227) |
[concepts/toolkit/components/teams-channel-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/teams-channel-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/teams-channel-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12227) |
[concepts/toolkit/customize-components/cache.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/customize-components/cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/cache?branch=pr-en-us-12227) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104080632120785-12227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZRGlUFiDVKgbImjKJBM9P%2BlQJuOGaN3kaR5YFhEr08c%3D&st=2021-04-08T06%3A45%3A41Z&se=2021-05-09T06%3A50%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 15:30 UTC, nmetulev approved these changes
Looks great.

@elisenyang, do you mind doing a quick review as well?

2021-04-27 20:52 UTC, elisenyang reviewed
Some of the tables show "IndexedDB" as the column name while others show "Object Store". Is this intentional or should it be consistent between all pages?

2021-05-04 12:21 UTC, waldekmastykarz commented
@nmetulev Elise and I synced and all seems to be ready for merge

2021-05-07 03:25 UTC, opbld31 commented
Docs Build status updates of commit _[af0effe](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/af0effe56e204a665e53ed0fa22734f7bfe20d8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12227) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12227) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12227) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12227) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12227) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12227) |
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12227) |
[concepts/toolkit/components/teams-channel-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/teams-channel-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/teams-channel-picker?branch=pr-en-us-12227) |
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12227) |
[concepts/toolkit/customize-components/cache.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-cache/concepts/toolkit/customize-components/cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/cache?branch=pr-en-us-12227) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105070324123944-12227%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H2XfaJyuTdbXCZLHBVaF5M7fM7xUjkHRbGbB32ntlho%3D&st=2021-05-07T03%3A20%3A39Z&se=2021-06-07T03%3A25%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-07 03:26 UTC, Lauragra approved these changes

2021-05-07 03:27 UTC, merged