Add Windows Update for Business deployment service
microsoftgraph/microsoft-graph-docs pull request #12220
Opened 2021-04-07 00:15 UTC by Alice-at-Microsoft

2021-04-07 00:17 UTC, opbld34 commented
Docs Build status updates of commit _[363b987](https://github.com/microsoftgraph/microsoft-graph-docs/commits/363b9870d200aa8ae00b164c6dc783b18a8d07bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bbf16fd7)
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-bbf16fd7)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-bbf16fd7)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-bbf16fd7)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-bbf16fd7)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-0 [...]

2021-04-10 02:06 UTC, opbld30 commented
Docs Build status updates of commit _[9b29705](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b29705794ba0ecfb83f475269486f64978438cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-0733bfa7)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-0733bfa7)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-0733bfa7)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-0733bfa7)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-0733bfa7)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-0733bfa7)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-10 02:36 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +![WUfB: ds overview](images/windowsupdates-wufbds.png)
The following comments are for the image specified in line 20 windowsupdates-wufbds.png:
Assuming "MDM", "WUfB", "DS" are not well-known, official acronyms, please either expand them or add a key in the image to define these acronyms.
Please use sentence case for "Windows Updates" -> "Windows updates".

2021-04-10 03:38 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +
In the following paragraphs, notice that I try to simplify sentence structure to convey the similar message to customers. Please see the principles of Microsoft Voice: 
Cloud style guide: https://styleguides.azurewebsites.net/StyleGuide/Read?id=2696&topicid=25356
Microsoft writing style guide: https://styleguides.azurewebsites.net/StyleGuide/Read?id=2700&topicid=28361

2021-04-10 04:20 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +The deployment service simplifies the process of reviewing, approving, scheduling, and deploying content throughout a diverse device ecosystem. The service's catalog of software updates provides an a
Line 38:
What is an "approval tailored view"? I am assuming that means a view tailored for approval.

2021-04-10 04:30 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +
Line 40:
"... have been chosen" - this is an example of vagueness when using passive voice - who is doing the choosing? (I'm assuming the administrator, or, the audience reading this.)
In general, where possible, use the perspective of second person singular, "you", or start a sentence with a verb (infinitive without to), e.g., "once you have chosen the desired updates, schedule deployments to start, or deploy over..."

2021-04-10 04:37 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +* [Software updates with the Windows Update for Business deployment service](windowsupdates-software-updates.md)
Link text for lines 43 to 45:
Because we write for scanning, this topic starts with putting the focus in the Windows Update for Business deployment service, and the name itself is long (6 words), I am going to remove the service name from the link text in these links.

2021-04-10 04:42 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +* [Manage monitoring rules for a deployment using the Windows Update for Business deployment service](windowsupdates-manage-monitoring-rules.md)
Line 61:
We don't do a bullet list if there's only a single bullet item.

2021-04-10 05:06 UTC, opbld32 commented
Docs Build status updates of commit _[555368a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/555368a93d05b576d5e3326a568abe7a0d8e4b0b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-4db12976)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-4db12976)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-4db12976)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-4db12976)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-4db12976)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-4db12976)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-10 05:08 UTC, opbld31 commented
Docs Build status updates of commit _[578f5b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/578f5b52e5aa1b1f9f7065b956fa0e50d9b26604)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-3bf299ff)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-3bf299ff)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-3bf299ff)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-3bf299ff)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-3bf299ff)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-3bf299ff)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-10 07:18 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +Deployments initiated by the service automatically benefit from [safeguard holds](https://docs.microsoft.com/en-us/windows/deployment/update/safeguard-holds) which prevent devices affected by quality
Line 56:
You have a warning for the link in this line. In general, for http links, make sure to remove the segment in the URL that specifies the locale/language, i.e., /en-us in this case.

2021-04-10 07:28 UTC, angelgolfer-ms reviewed
FYI I made some edits in the windowsupdates-concept-overview.md topic to follow the Microsoft Voice principles. I tried to convey similar ideas with fewer words and simpler sentence structures. Please take a look at the diff in this commit (https://github.com/microsoftgraph/microsoft-graph-docs/pull/12220/commits/555368a93d05b576d5e3326a568abe7a0d8e4b0b). Please let me know if you have any comments or questions about these updates.

I'll probably not spend as much time editing the rest of the topics for Microsoft Voice, trusting that you can apply the same principles to them, especially the conceptual topics. :-)

2021-04-13 03:53 UTC, opbld30 commented
Docs Build status updates of commit _[58d6918](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58d69181ba12a9486c570915effa8019c8c94504)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-5e83ec5c)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-5e83ec5c)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-5e83ec5c)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-5e83ec5c)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-5e83ec5c)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-5e83ec5c)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-13 07:17 UTC, angelgolfer-ms commented on concepts/windowsupdates-software-updates.md
> +Once you identify a desired version, you can assign it as content to a deployment using a [featureUpdateReference](/graph/api/resources/windowsupdates-featureupdatereference) and specifying the `vers
Line 69 and GLOBAL:
Please make sure to style property names as bold, not by enclosing them with tick marks. 
(Use tick marks for programmability terms which are not part of the Graph API, for example, the OData query parameter `$select`.)
I'm making this fix directly in the PR, but please check and correct other instances, and apply such from now on.

2021-04-13 07:20 UTC, angelgolfer-ms commented on concepts/windowsupdates-software-updates.md
> +There are two high-level categories of Windows 10 updates: feature updates and quality updates. Quality updates are further classified as security and non-security. The deployment service currently s
Line 18 and GLOBAL:
Please don't use possessive ('s) on the deployment service, as it's never alive.
For this instance, I rephrased the sentence: 
"Driver management is currently excluded from the quality updates of the deployment service."

2021-04-13 07:39 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Feature update catalog entry
FYI I put lines 9483-9484 to go after 9485-9488.

2021-04-13 07:43 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Expedited quality update reference
@Alice-at-Microsoft , what is the reason that we don't want to include qualityUpdateReference in the TOC, before line 9502-9503? Not all quality updates are expedited, so in those case, is qualityUpdateReference  used?

2021-04-13 07:48 UTC, opbld30 commented
Docs Build status updates of commit _[d9d2d60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9d2d602581e3e44ccfc3f6f6f961fa478db5dda)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-502f0188)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-502f0188)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-502f0188)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-502f0188)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-502f0188)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-502f0188)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-14 01:37 UTC, opbld30 commented
Docs Build status updates of commit _[fb7621c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb7621c5d603680cbe634b717bae7079b013f792)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-2723b6a1)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-2723b6a1)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-2723b6a1)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-2723b6a1)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-2723b6a1)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-2723b6a1)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-14 02:00 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-catalog-list-entries.md
> +Get the list of entries from a [catalog](../resources/windowsupdates-catalog.md).
Line 15:
It would be more informative to introduce the data type of "entries" in the summary description.
It also seems like at this point, this operation doesn't return all the catelogEntry resources in a catalog, and returns only those of the featureUpdateCatalogEntry or qualityUpdateCatalog type?
If that's the case, this info needs to be there too.
For example:

"Get a list of catalogEntry resources (provide link) in a catalog (provide link).
(new paragraph - summary description should be a single sentence in its own paragraph, summarizing the purpose of the operation)
Currently, this operation returns entries of the featureUpdateCatalogEntry or qualityUpdateCatalog type (provide links)."

2021-04-14 02:03 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-catalog-list-entries.md
> +To use a query parameter on a property that is not inherited from [catalogEntry](../resources/windowsupdates-catalogentry.md), include the full resource type for the property. For example, to filter
Line 39:
Please remove the ellipses at the end. I think the context is clear that this is just about the filtering, and is not a complete query.

2021-04-14 02:18 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-catalogentry.md
> +All catalog entries exist as one of the following derived types: [featureUpdateCatalogEntry](../resources/windowsupdates-featureupdatecatalogentry.md) and [qualityUpdateCatalogEntry](../resources/win
Line 18:
Is this statement true?
Or is it true that there are other types like driverUpdateCatalogEntry that exist in a catalog, but currently the list operation doesn't return entries of that type?
I'm asking that only because the CSDL you provided has driverUpdateCatalogEntry as one of the 3 types inheriting from softwareUpdateCatelogEntry which is derived from catalogEntry.
If the statement is true, then that's good.
Otherwise if later on the list operation will include entries of the driverUpdateCatalogEntry type, then perhaps you can  instead say:
"**catalogEntry** is the base type from which [featureUpdateCatalogEntry](../resources/windowsupdates-featureupdatecatalogentry.md) and [qualityUpdateCatalogEntry](../resources/windowsupdates-qualityupdatecatalogentry.md) inherit."

BTW I hesitate to say "... is the base type for..." because their base type is actually softwareUpdateCatelogEntry. I think "inherit" still makes sense; "derive" is ok.

2021-04-14 02:25 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-catalogentry.md
> +|deployableUntilDateTime|DateTimeOffset|The date on which the content was or will no longer be available to deploy using the service. Read-only.|
Line 23:
I think it's ok to use present tense "...is no longer available for deployment using the service".

FYI in general, we try to stick to present tense in docs. The use of present tense is based on the perspective that, this IS presently how an API behaves. We do so even when we state two actions one occurring after the other, like "After the sun rises, the children get up." Both the first and second phrases keep the present tense.

2021-04-14 02:46 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-catalogentry.md
> +|releaseDateTime|DateTimeOffset|The date on which the content was or will be released. Read-only.|
Line 26:
Use present tense, "... is released".

2021-04-14 03:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-catalogentry.md
> +|deployableUntilDateTime|DateTimeOffset|The date on which the content was or will no longer be available to deploy using the service. Read-only.|
BTW, please make the similar updates to the description of the same property inherited in the softwareUpdateCatalogEntry, featureUpdateCatalogEntry, and qualityUpdateCatalog topics.
I won't be commenting in those topics about this ;-)

2021-04-14 03:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-catalogentry.md
> +|releaseDateTime|DateTimeOffset|The date on which the content was or will be released. Read-only.|
Please make the similar updates to the description of the same property inherited in the softwareUpdateCatalogEntry, featureUpdateCatalogEntry, and qualityUpdateCatalog topics.

2021-04-14 03:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
> +
Please add as a separate paragraph after line 16.
I think it would be helpful to pull in a sentence from your other [Windows docs](https://docs.microsoft.com/en-us/windows/deployment/update/waas-quick-start) to explain feature updates. I was wondering myself what I know that differentiates a feature update from a quality update. 

"As the name suggests, feature updates add new features to Windows 10, delivered in bite-sized chunks compared to the previous practice of Windows releases every 3-5 years."

2021-04-14 03:37 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-qualityupdatecatalogentry.md
> +
After line 16, as a separate paragraph, I think it would be helpful to provide a bit more info what a quality update is.
You can say,
"Quality updates include security updates and non-security updates, such as {give an example}."
I think that would help customers better identify their prior knowledge or experience with how we're explaining the API, and help with their learning.

2021-04-14 03:47 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +When you deploy an update to a device, Windows Update will offer the specified update to the device if it has not yet taken the update. For example, if you deploy a feature update (e.g. version 20H2)
Line 14:
Can we replace the verb in "... if it has not yet taken the update", and say "... if it has not yet received the update"?

2021-04-14 03:51 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +When you deploy an update to a device, Windows Update will offer the specified update to the device if it has not yet taken the update. For example, if you deploy a feature update (e.g. version 20H2)
Line 14:
Please rephrase:
"For example, if you deploy a feature update (e.g. version 20H2), the device will move to the specified version if it is enrolled in feature update management and currently on an older version of Windows 10. "
As:
"For example, if you deploy a feature update (e.g. version 20H2) to a device that is enrolled in feature update management and currently on an older version of Windows 10, the specified version installs on the device."
Please replace the verb "install" if it's actually not accurate.

2021-04-14 03:53 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +When you deploy an update to a device, Windows Update will offer the specified update to the device if it has not yet taken the update. For example, if you deploy a feature update (e.g. version 20H2)
Like I explained in another part of this PR, please use present tense and not future tense. Present tense denotes this is the behavior.

2021-04-14 04:04 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +
Line 16:
"Today, the deployment service supports deployments of Windows 10 feature updates."
Based on the title of this topic, I would expect this topic to cover deploying both feature and quality updates, unless you're saying in this release, you don't support the latter, but doesn't seem like it's true based on the windowsupdates-deploy-expedited-update.md topic.

Can you clarify and correct this sentence, or correct the topic title and TOC title, if you want this topic for deploying only feature updates?

If it turns out that you intend to focus on deploying feature updates in this topic, then please put the "see-also" as a level 2 "See also" section at the end of the topic.

2021-04-14 04:19 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md
> +Update the members and exclusions collections of a deployment audience.
Line 15:
Please add a link to deploymentAudience.
In general, please try to surface links to related types (e.g., type of binding parameter of a method, or return type of an operation or method) in the summary description. The generator tool doesn't do a good job in respect, but typically the generated description is also lacking in context and explains only the syntax as defined in the CSDL, so the author's enhancement would be an improvement.

2021-04-14 04:24 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +Devices are automatically registered with the service when added to the members or exclusions collections of a deployment audience (i.e. an azureADDevice object is automatically created if it does no
Line 155:
Please add a link to azureADDevice.
Please remember - in general, on first reference in a topic, every resource or method name in the Graph API should have a link to the corresponding topic.

2021-04-14 04:29 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +A deployment specifies content to deploy, how and when to deploy the content, and the targeted devices. When a deployment is created, a deployment audience is automatically created as a relationship.
Line 65:
Please add a link to deploymentAudience.md. I believe this is the first reference in this topic?
I think in a conceptual topic where the focus is explaining how APIs are designed to work together, in a case like this where the words that form the resource name "deploymentAudience" can also be used in natural language to explain the behavior, it's ok to keep the link text as "deployment audience". There is some flexibility with link text. 
(But when in doubt, then err on the side of using the exact API or resource name as link text.)

2021-04-14 04:30 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +After a deployment is created, you can assign devices to the deployment audience. Devices can be assigned directly, or via updatable asset groups. Once the deployment audience is successfully updated
Line 153:
Please add a link to "updatable asset group" to link to updatableAssetGroup.md.

2021-04-14 07:56 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +Deployments move through the following lifecycle states:
Line 51:
"... move through states as described in the following table."
Per Microsoft Writing Style Guide, the lead-in sentence to a table should not end with a colon.

2021-04-14 08:05 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +| Paused    | The deployment is paused and prevented from offering the update to devices until it is unpaused.  |
Lines 55-57, the State column:
For these state values, I'd suggest using camel case and reflecting the actual enum values, and styling them as such by enclosing them in tick marks. That is: `scheduled`, `offering`, `paused`.

2021-04-14 08:18 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +Deployments are the foundation of the Windows Update for Business deployment service. Through a deployment you can target a set of devices to receive specific content from Windows Update, such as a [
I have an overall comment for this topic - as we progress deeper into how the APIs work, we can make the corresponding resource names more obvious to help learning. I can see using natural language without involving resource names makes smoother reading. I'll comment inline below how we can walk that line.

2021-04-14 08:27 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +1. Content: The update available to deploy from the catalog.
Line 16:
"... deploy from the catalog. This is represented by the **content** property of a deployment (link to deployment resource topic).
Line 17:
"... receive content. This is an **audience** relationship of the deploymentAudience (link to deploymentAudience) type."
Line 18:
"... delivered to devices. This is represented by the **settings** property of the deploymentSettings (link) type."
Line 19:
"... its lifecycle. This is represented by the **state** property of the deploymentState (link) type."

2021-04-14 08:30 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +
Line 23:
Use active voice as much as possible:
"Because content and audience are key to the definition of a deployment, assign them at the time of creation. You cannot change content and audience assignments later, however, you can change device membership within an audience."

2021-04-14 08:32 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +Rollout settings govern how the content is deployed over time to devices in the deployment audience. Rollout settings can be configured for deployments of feature updates.
Line 31:
Please just use "Rollout settings" as link text to the topic for rolloutSettings.

2021-04-14 08:33 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +You can use monitoring settings to configure alerts and automated actions to take based on update signals from devices. Monitoring settings can be configured for deployments of feature updates.
Line 37:
Similarly, just use "monitoring settings" as link text to the topic for monitoringSettings.

2021-04-14 08:33 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +
Line 43:
Please just use "user experience settings" as link text to the topic for userExperienceSettings.

2021-04-14 08:35 UTC, angelgolfer-ms commented on concepts/windowsupdates-deployments.md
> +
Lines 71 and 73:
Please style the 3 property names as bold, not enclosing them in tick marks.

2021-04-14 23:19 UTC, Alice-at-Microsoft commented on api-reference/beta/toc.yml
> +          - name: Expedited quality update reference
The deployment service doesn't support deploying (regular non-expedited) quality updates at this time, so I didn't include it. Is that okay?

2021-04-14 23:20 UTC, Alice-at-Microsoft commented on api-reference/beta/resources/windowsupdates-catalogentry.md
> +All catalog entries exist as one of the following derived types: [featureUpdateCatalogEntry](../resources/windowsupdates-featureupdatecatalogentry.md) and [qualityUpdateCatalogEntry](../resources/win
Yes, that statement is true today (no support for driver updates--the updated CSDL should reflect that).

2021-04-14 23:43 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-deploy-update.md
> +
The deployment service supports two scenarios: deploying feature updates and deploying expedited quality updates. We split it into the more generic "deploy an update" and "deploy an expedited update" to better frame future support for other content types. Do you recommend making the topics more specific for now and then changing them back to more general in the future?

2021-04-15 06:20 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +
Assuming you mean in this release: the service supports deploying (1) feature updates, (2) expedited quality updates. Later on, the service will support deploying other updates such as (3) quality updates but not in an expedited way (if that is actually a type of update that is ever supported).
Then I would suggest documenting exactly what is currently supported. 
In windowsupdates-deploy-update.md, the following sentence:
"Today, the deployment service supports deployments of Windows 10 feature updates. "
and step 1 are indeed setting this topic up to apply to only deployments of feature updates, and preclude deployments of quality updates. Is that your intention now and in the foreseeable future?
If that's the case, I'd suggest:
(a) Use the TOC title: "Deploy a feature update"
(b) Use the topic title: "Deploy a feature update using the Windows Update for Business deployment service"
(c) The topic currently starts with a general statement for all types of deployments. I'd suggest you add a couple more sentences to the first paragraph. Something to the effect of:
"With the Windows Update for Business deployment service, you can deploy Windows updates to sets of devices in an Azure AD tenant. Today, the deployment service supports deployments of Windows 10 feature updates and expedited quality updates. This topic focuses on deployments of feature updates. For information about deploying expedited quality updates, see {link to the windowsupdates-deploy-expedited-update.md topic}."

2021-04-15 06:46 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-expedited-update.md
> +Today, the deployment service supports expedited deployments of Windows 10 quality updates. Deploying an expedited quality update helps achieve compliance against a specific security update, as speci
I am curious if there's a reason why the content in line 20 doesn't appear as part of the first paragraph; doing so would quickly put into focus that this topic is about expedited _quality_ updates, not just any expedited update (if there is expedited feature updates, ever).
Is it that in the future, you plan to add to this topic deploying expedited feature update, such that the content in lines 14-18 will still apply?
Regardless, for this release, an expedited update is an expedited quality update. I'd still suggest moving line 20 to the first paragraph, and tightening the two sentences. For example:

"The Windows Update for Business deployment service supports expedited deployment of Windows 10 quality  updates to sets of devices in an Azure AD tenant in case an emergency arises. The service lets you quickly deploy an update to achieve compliance against a specific security update, as specified by date. This topic focuses on deploying expedited quality updates. For information on deploying feature updates, see {link to windowsupdates-deploy-update.md}."

2021-04-15 06:47 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-update.md
> +
My suggestions for the other topic (windowsupdates-deploy-expedited-update.md) are here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/12220/files#r613798124

2021-04-15 06:50 UTC, angelgolfer-ms commented on concepts/windowsupdates-deploy-expedited-update.md
> +Today, the deployment service supports expedited deployments of Windows 10 quality updates. Deploying an expedited quality update helps achieve compliance against a specific security update, as speci
I also suggest:
(a) Keeping the TOC title "Deploy an expedited update" (Doing "Deploy an expedited quality update" is too long and would wrap around which we avoid.)
(b) Using the topic title:
"Deploy an expedited quality update using the Windows Update for Business deployment service"

2021-04-15 07:20 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-deployablecontent.md
> +Represents content that is deployable by the service.
Line 16 and GLOBAL:
I think it would be helpful to at least add a sentence like: "This is an abstract type."
This would help explain why this topic (and most other abstract type topics) is sparsely documented, and sets up the expectations that it's ok, and its usefulness gets augmented by types that inherit from it.

I think we talked about adding the derived types, something like:
"This is an abstract type inherited by {link to resource A}, {link to resource B},..."

 The only thing I can think of that makes that a disadvantage is over time, when we add more derived types, the abstract type topic may get stale as new derived types don't get added to that sentence.

2021-04-15 08:35 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-expeditedqualityupdatereference.md
> +|classification|qualityUpdateClassification|Specifies the classification of the referenced content. Default value is `security`. Inherited from [qualityUpdateReference](../resources/windowsupdates-qu
Line 26 and GLOBAL:
Where have you documented enums defined in your subnamespace?
I am expecting a file by the name of enums-{subnamespace name}.md, but don't seem to see it in your PR. This is according to this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103159/Enums-in-subnamespaces

I am hoping to find how you're documenting an enum like qualityUpdateClassification. I have noticed your CSDL seems to define more than what your PR is releasing, BTW 8-|.

2021-04-16 00:24 UTC, opbld30 commented
Docs Build status updates of commit _[d95041d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d95041d39e2b2c744e10ae28bdebddd1ee242254)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-bc7553eb)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-bc7553eb)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-bc7553eb)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-bc7553eb)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-bc7553eb)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-bc7553eb)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-16 02:54 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Delete updatable asset
FYI, I moved list operation (9521-9522) above the get operation (9519-9520). The typical order is list, create, get, update, delete.

2021-04-16 02:57 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableasset-list.md
> +To use a query parameter on a property that is not inherited from [updatableAsset](../resources/windowsupdates-updatableasset.md), include the full resource type for the property. For example, to sel
Line 41:
FYI I rephrased the sentence about applying $select on the errors property with the appropriate sentence structure and formatting.

2021-04-16 03:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-updatableassetgroup.md
> +
Line 16:
I changed that to say "A group of devices that can receive updates."
If that's not correct, please update.
I did so that the description is more informative - what's an "asset"? what does "updatable" mean?

2021-04-16 03:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-updatableassetgroup.md
> +An [azureADDevice](../resources/windowsupdates-azureADDevice.md) can be a member; an updatableAssetGroup cannot be a member.
Line 18:
FYI I have rephrased this to say "Members are of the [azureADDevice](../resources/windowsupdates-azureADDevice.md) resource type. An **updatableAssetGroup** resource cannot be a member of another **updatableAssetGroup**."

2021-04-16 03:27 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Expedited quality update reference
Ok, yes, I got that impression subsequently. Let's leave it as is right now.

2021-04-16 03:28 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            - name: Create updatable asset group
Under the updatableAssetGroup resource node:
FYI I rearranged the order a bit to follow the convention for CRUD operations - list, create, get, update (not supported here), delete. Then followed by any actions or functions.

2021-04-16 03:38 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            - name: Delete updatable asset group
FYI I also moved "List members" to before "Add members", instead of leaving it at the end.
First, we generally put a "list" operation before a create/add operation.
Second, technically this is using a GET operation and the members nav property of updatableAssetGroup, and is not a function.

2021-04-16 03:44 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-list-members.md
> +
After line 15 as a separate paragraph, is it correct to say the following? 

This operation references the **members** navigation property of an **updatableAssetGroup" resource. To reference the navigation property that is not inherited from [updatableAsset](../resources/windowsupdates-updatableasset.md), include the full resource type for the property in the query URL, i.e., `.../microsoft.graph.windowsUpdates.updatableAssetGroup/members`."

If it is, please add that sentence in a separate paragraph. I was a little intrigued by the syntax why referencing a nav property (members) on an updatableAssetGroup requires the segment /microsoft.graph.windowsUpdates.updatableAssetGroup/, preceding members, when we already identified a specific updatableAssetGroup.

2021-04-16 03:50 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md
> +An [azureADDevice](../resources/windowsupdates-azureaddevice.md) can be added as a member; an [updatableAssetGroup](../resources/windowsupdates-updatableassetgroup.md) cannot be added as a member.
Line 17:
FYI I rephrased this to use active voice. It's more user friendly, stating the task they can do, rather than passive voice which is more about "rules". That's part of the principles of Microsoft Voice.

2021-04-16 03:53 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md
> +An [azureADDevice](../resources/windowsupdates-azureaddevice.md) can be added as a member; an [updatableAssetGroup](../resources/windowsupdates-updatableassetgroup.md) cannot be added as a member.
I also moved the link to updatableAssetGroup to the first sentence in line 15.
In general, the summary description should contain links to the significant API or resource names, in this case, the binding parameter (or parent type).

2021-04-16 03:57 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md
> +If successful, this action returns a `202 Accepted` response code.
Line 61:
I think this should include the default sentence "It does not return anything in the response body.".

2021-04-16 03:57 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md
> +If successful, this action returns a `202 Accepted` response code.
I added that sentence in this topic, but if there are other similar topics, please add that sentence for clarity.

2021-04-16 03:58 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md
> +<!-- {
I also deleted line 89 as there's no response body.

2021-04-16 03:59 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md
> +
Line 15:
I added a link to the updatableAssetGroup resource, as this is the first reference, and it's the parent resource for the method.

2021-04-16 04:00 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md
> +|memberEntityType|String|The full type of the updatable assets. Possible values are: `#microsoft.graph.windowsUpdates.azureADDevice`.|
Both lines 49 and 50:
Should refer to "updatable assets" by their resource name, for clarity.

2021-04-16 04:11 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-removemembers.md
> +
FYI I applied similar updates to clarify exact resource names, linking to them on first reference, as I commented in the parallel topics for addmembers and addmembersbyid.

2021-04-16 04:15 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            - name: Delete updatable asset group
FYI I added to the TOC addmembersbyid and removemembersid as well, because in general we try to expose all actions and functions.

2021-04-16 04:23 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-azureaddevice-list.md
> +
FYI after line 15, I added a sentence:
"This operation filters on the full resource type, `microsoft.graph.windowsUpdates.azureADDevice`, which inherits from [updatableAsset](../resources/windowsupdates-updatableasset.md)."

Please update if it's not correct. I feel it's worth pointing out this is not the typical get collection operation (which we call "list").

2021-04-16 04:37 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            - name: Get Azure AD device
Under the node for azuredevice, FYI I reordered the operations and methods as indicated in other contexts, and added the 2 enroll and unenroll methods by ID.

2021-04-16 04:41 UTC, opbld30 commented
Docs Build status updates of commit _[98ab4f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98ab4f5c263d9b1d9935de0aedab80f405403da6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-97480f83)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-97480f83)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-97480f83)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-97480f83)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-97480f83)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-97480f83)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-16 06:30 UTC, opbld31 commented
Docs Build status updates of commit _[e57ae84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e57ae84d44f26448efea6b9c69cad6cd142b919a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-462ccd3c)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-462ccd3c)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-462ccd3c)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-462ccd3c)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-462ccd3c)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-12220) | [Details](#user-content-a46d7d876f80d17c571e10a97f1ac07c-462ccd3c)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/a [...]

2021-04-16 06:41 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-deployment.md
> +
Is the updateSettings action in scope for this release? It's not in this Methods table, and there's no file for it either. Please confirm.
That action is defined in the CSDL:
			<Action Name="updateSettings" IsBound="true">
				<Parameter Name="bindingParameter" Type="microsoft.graph.windowsUpdates.deployment"/>
				<Parameter Name="settings" Type="microsoft.graph.windowsUpdates.deploymentSettings"/>
			</Action>

2021-04-16 07:19 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
> +|displayName|String|	The display name of the content. Read-only. Inherited from [catalogEntry](../resources/windowsupdates-catalogentry.md)|
Line 26 and GLOBAL:
Can you please do a search for "Inherited from" that exists in a Description column in a table, and make sure each such sentence ends with a period?

2021-04-16 07:31 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        items:
I think there are a few things we can add:
(1) Create a new API overview topic. This topic should give a high level description of the APIs you offer, and their use cases. Every workload should have an API overview, even though some partners are slow in getting that together. More info: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103154/Conceptual-topics?anchor=but%2C-what%27s-the-difference-between-a-service-overview-vs-an-api-overview-in-the-reference-section%3F
(2) Document the admin and windows entities which are defined in your CSDL.
You don't have to expose the admin and windows entities in the TOC. But it would be helpful to mention that "customers can access your APIs off  /admin/windows/updates; for more information, see the admin, windows, and updates entities" and link to them.
(3) Before the Catalog node in the TOC, add a node for the updates entity. It seems to me that is actually the "main" entity for the APIs you're exposing in this release, from which a customer can access the deployments, updatableAssets, and catalog relationships to connect to the rest of the API set? Is that the case?

So the first 2 levels of the TOC for your API in the reference section would look like:

Operating system updates (preview)
Overview
  Updates
  Catalog
  Deployment
        Deployment audience
  Updatable asset

2021-04-16 07:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-rolloutsettings.md
> +|:---|:---|:---|
In this table and in general:
Please style names of properties defined in your resources with bold, not tick marks.
(There are a few other topics that do this, and they are not consistent.)

2021-04-16 08:50 UTC, angelgolfer-ms commented on concepts/windowsupdates-schedule-deployment.md
> +
Above paragraph - please style the property names as bold, not tick marks.

2021-04-16 08:55 UTC, angelgolfer-ms commented on concepts/windowsupdates-schedule-deployment.md
> +In this example, a new deployment is configured so that a new set of devices is offered the update every week (`durationBetweenOffers` set to seven days), starting on July 1, 2021. All devices will b
Above line 88:
I suggest creating a level 3 section header and provide a title for the example, to make it easier to discover and scan.
Something like:
"Example: Stage a deployment at intervals between start and end dates"

2021-04-16 08:56 UTC, angelgolfer-ms commented on concepts/windowsupdates-schedule-deployment.md
> +In this example, a new deployment is configured so that a new set of devices is offered the update every week (`durationBetweenOffers` set to seven days), starting on July 1, 2021. All devices will b
Note that you should bump down the existing level 3 headers ("Request" and Response") to level 4.

2021-04-16 08:58 UTC, angelgolfer-ms commented on concepts/windowsupdates-schedule-deployment.md
> +
Above line 156:
I suggest adding another level 3 header, such as:
"Example: Stage a deployment at fixed intervals for a specified number of devices in each offer

2021-04-16 09:04 UTC, angelgolfer-ms commented on concepts/windowsupdates-manage-monitoring-rules.md
> +For deployments initiated by the deployment service, you can use monitoring rules configure alerts and automated actions based on deployment signals.
Line 12:
Use singular "monitoring rule", and add word "to", as in "... you can use a monitoring rule to configure alerts and automated actions..."

Add a link to "monitoring rule" to link to the monitoringRule resource topic.
After all this is to describe how to use our APIs, so conceptual content should also relate to API elements where appropriate.

2021-04-16 09:05 UTC, angelgolfer-ms commented on concepts/windowsupdates-manage-monitoring-rules.md
> +
Please rewrite line 99 as a level 3 section title, like "Example: Resume deployment by removing a monitoring rule".

2021-04-16 09:06 UTC, angelgolfer-ms commented on concepts/windowsupdates-manage-monitoring-rules.md
> +
Bump down the existing level 3 headings to level 4 ("Request" and "Response").

2021-04-16 09:07 UTC, angelgolfer-ms commented on concepts/windowsupdates-manage-monitoring-rules.md
> +
Add a level 3 heading that summarizes the first sentence in line 158. For example:
"Example: Resume deployment by adjusting the threshold of a monitoring rule"

2021-04-16 09:11 UTC, angelgolfer-ms requested changes
@Alice-at-Microsoft , I think I have taken a look at all the topics in this PR. In the interest of time to reduce iterations of reviews, I went ahead and made a few updates directly in your PR. In each of these cases, I tried to add a comment in the PR as well, so that you're aware of my fixes and the respective reasons.
Feel free to also take a look at my commits up to this point.
Please let me know if you have questions.

BTW, please contact lauragra for the value of ms.prod you should use, and a few of the errors somehow reported in the few docfx.json files.

2021-04-16 09:14 UTC, opbld30 commented
Docs Build status updates of commit _[f7ab4cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7ab4cdb2d5a4043f02e2b9c456495c017a513fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-9d7791472832342ece57ad6ed003b768-47ae0572)
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-56e00c7a79e1ba6581719cf9171c0710-47ae0572)
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-1a8524b6ef93174d9a72fd0f5a6b095d-47ae0572)
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-83cf6f930a234673ce043b4fd744655c-47ae0572)
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-47ae0572)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-47ae0572)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-47ae0572)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-47ae0572)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-47ae0572)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/g [...]

2021-04-16 17:36 UTC, Alice-at-Microsoft commented on api-reference/beta/resources/windowsupdates-expeditedqualityupdatereference.md
> +|classification|qualityUpdateClassification|Specifies the classification of the referenced content. Default value is `security`. Inherited from [qualityUpdateReference](../resources/windowsupdates-qu
We are missing an enums file--will add.

The deployed CSDL should match the PR. I will share the most recent CSDL with you.

2021-04-16 17:40 UTC, Alice-at-Microsoft commented on api-reference/beta/api/windowsupdates-updatableassetgroup-list-members.md
> +
Right, it's because we're accessing the updatableAssetGroup from an updatableAsset collection, and members is not inherited from updatableAsset. Will clarify!

2021-04-16 17:50 UTC, Alice-at-Microsoft commented on api-reference/beta/resources/windowsupdates-featureupdatecatalogentry.md
> +|displayName|String|	The display name of the content. Read-only. Inherited from [catalogEntry](../resources/windowsupdates-catalogentry.md)|
Yup! Will also include in bugs for stub generator.

2021-04-16 18:03 UTC, Alice-at-Microsoft commented on api-reference/beta/toc.yml
> +        items:
Thanks! 1 and 2 make sense to me. For 3, it's true that all other APIs are accessed through the updates entity. However, the updates entity itself does not have any methods and cannot be accessed on its own. I think of it more like a prefix than an entity (even though it is technically an entity). Given this context, do you still recommend putting Updates into the TOC?

2021-04-16 21:09 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        items:
I can see the same too about how the updates entity is defined - the updates entity is skeletal other than the 3 nav properties. However it serves more like a "root" with the 3 nav properties that cover other parts of the API set.
The existing pattern and organization for other workloads starts their TOC with an entity that has other features built around it. 
Let's try sticking the updates entity as the first entity after the API overview topic, see how the TOC experience is like, and make changes if necessary?

2021-04-16 21:11 UTC, Alice-at-Microsoft commented on api-reference/beta/toc.yml
> +        items:
Sounds good. We'll try that.

2021-04-20 00:34 UTC, opbld32 commented
Docs Build status updates of commit _[83eea2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83eea2f55e76b0ad62d1eb6b80d237710548ad9e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-6d3f2d28)
[concepts/windowsupdates-deploy-expedited-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-expedited-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-expedited-update?branch=pr-en-us-12220) | [Details](#user-content-abfde833684d8b33688cf2abc0863784-6d3f2d28)
[concepts/windowsupdates-deploy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-deploy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-deploy-update?branch=pr-en-us-12220) | [Details](#user-content-092f17528556d857a56e1c682ce4fef4-6d3f2d28)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-6d3f2d28)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-6d3f2d28)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft [...]

2021-04-20 19:08 UTC, opbld32 commented
Docs Build status updates of commit _[c414ec1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c414ec1209791efc304861c7623f8ef4cd640a33)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-dd9ec95f)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-dd9ec95f)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-21 14:06 UTC, opbld32 commented
Docs Build status updates of commit _[40ae563](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40ae563e08c74f023f368007b1a1d4434258bc98)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-2cc6425c)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-2cc6425c)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-2cc6425c)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatable [...]

2021-04-21 14:21 UTC, cinglis-msft commented on api-reference/beta/api/windowsupdates-catalog-list-entries.md
> +Get the list of entries from a [catalog](../resources/windowsupdates-catalog.md).
Followed your recommended format. Made them into links. Removed later links for the given types (eg featureUpdateCatalogEntry), instead boldening them.

2021-04-21 14:22 UTC, cinglis-msft commented on api-reference/beta/api/windowsupdates-catalog-list-entries.md
> +To use a query parameter on a property that is not inherited from [catalogEntry](../resources/windowsupdates-catalogentry.md), include the full resource type for the property. For example, to filter
Done.

2021-04-21 14:34 UTC, opbld33 commented
Docs Build status updates of commit _[49a52e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49a52e66d0a7f27bdb71985c6ecbd0ade0a6cbd3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-d2483c7e)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-d2483c7e)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-d2483c7e)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatable [...]

2021-04-21 19:23 UTC, opbld33 commented
Docs Build status updates of commit _[7216065](https://github.com/microsoftgraph/microsoft-graph-docs/commits/721606532a7b662b8631bfa350704702923023bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-2755a34c)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-2755a34c)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-2755a34c)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatable [...]

2021-04-21 19:35 UTC, opbld31 commented
Docs Build status updates of commit _[5ef8bcb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ef8bcba9f15a4850001a81b9d02dfbb1bda3e4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-95cb7eab)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-95cb7eab)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-95cb7eab)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatable [...]

2021-04-21 22:27 UTC, aarononeal commented on api-reference/beta/api/windowsupdates-updatableassetgroup-list-members.md
> +
The phrasing wasn't exactly correct and also the path order was reversed. The derived type comes after the property in the URL, not before.

I added the following text and also corrected the sample.

> This operation references the members navigation property of an [updatableAssetGroup](../resources/windowsupdates-updatableassetgroup.md) resource and returns a collection of [updatableAsset](../resources/windowsupdates-updatableasset.md) resources. To reference a more specific derived type, include the full resource type in the query URL, i.e., `.../members/microsoft.graph.windowsUpdates.updatableAssetGroup`.

2021-04-21 22:53 UTC, aarononeal commented on concepts/windowsupdates-deploy-update.md
> +
Making those changes. However, line 16 seems important as it lets them know they will stop receiving automatic feature updates unless they configure a deployment or policy in the service. We want to avoid sediment that would occur if folks enroll and think things keep working like they used to.

2021-04-22 00:37 UTC, opbld32 commented
Docs Build status updates of commit _[874fa55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/874fa552211f4aa569707d1207ecd5644397a504)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-589b0581)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-589b0581)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-589b0581)
[api-reference/beta/resources/windowsupdates-admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-admin.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-admin?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-0918e31e1de779eaa399f93e59a8fddc-589b0581)
[api-reference/beta/resources/windowsupdates-updates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-updates.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-updates?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-75b779af44d734b2bb050a24638d934e-589b0581)
[api-reference/beta/resources/windowsupdates-windows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-windows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-windows?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-43268588947e50299595e35812154e33-589b0581)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-be [...]

2021-04-22 01:07 UTC, opbld32 commented
Docs Build status updates of commit _[218b080](https://github.com/microsoftgraph/microsoft-graph-docs/commits/218b0807a6b60bbd0b402c532eccb1e258bd1bf5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-02330f0f)
[concepts/windowsupdates-manage-monitoring-rules.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-manage-monitoring-rules.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-manage-monitoring-rules?branch=pr-en-us-12220) | [Details](#user-content-4cc2e9e58ec7e86ef07123811af6958f-02330f0f)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-02330f0f)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-02330f0f)
[api-reference/beta/resources/windowsupdates-admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-admin.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-admin?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-0918e31e1de779eaa399f93e59a8fddc-02330f0f)
[api-reference/beta/resources/windowsupdates-updates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-updates.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-updates?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-75b779af44d734b2bb050a24638d934e-02330f0f)
[api-reference/beta/resources/windowsupdates-windows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-windows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-windows?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-43268588947e50299595e35812154e33-02330f0f)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentau [...]

2021-04-22 01:12 UTC, opbld32 commented
Docs Build status updates of commit _[c0c9c6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0c9c6f69576cb3fa9deeb9844b0cac197849a60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-2a70f555)
[concepts/windowsupdates-manage-monitoring-rules.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-manage-monitoring-rules.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-manage-monitoring-rules?branch=pr-en-us-12220) | [Details](#user-content-4cc2e9e58ec7e86ef07123811af6958f-2a70f555)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-2a70f555)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-2a70f555)
[api-reference/beta/resources/windowsupdates-admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-admin.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-admin?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-0918e31e1de779eaa399f93e59a8fddc-2a70f555)
[api-reference/beta/resources/windowsupdates-updates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-updates.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-updates?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-75b779af44d734b2bb050a24638d934e-2a70f555)
[api-reference/beta/resources/windowsupdates-windows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-windows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-windows?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-43268588947e50299595e35812154e33-2a70f555)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentau [...]

2021-04-22 01:19 UTC, opbld34 commented
Docs Build status updates of commit _[e3d3df3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3d3df3475e964e2538f070e8dcd6011e4c99f0e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/windowsupdates-enroll.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-enroll.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-enroll?branch=pr-en-us-12220) | [Details](#user-content-10bf995fb2d36c19296c9f81867f0b55-f8c46319)
[concepts/windowsupdates-manage-monitoring-rules.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-manage-monitoring-rules.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-manage-monitoring-rules?branch=pr-en-us-12220) | [Details](#user-content-4cc2e9e58ec7e86ef07123811af6958f-f8c46319)
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-f8c46319)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-f8c46319)
[api-reference/beta/resources/windowsupdates-admin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-admin.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-admin?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-0918e31e1de779eaa399f93e59a8fddc-f8c46319)
[api-reference/beta/resources/windowsupdates-updates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-updates.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-updates?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-75b779af44d734b2bb050a24638d934e-f8c46319)
[api-reference/beta/resources/windowsupdates-windows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/resources/windowsupdates-windows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/windowsupdates-windows?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) | [Details](#user-content-43268588947e50299595e35812154e33-f8c46319)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentau [...]

2021-04-22 01:23 UTC, opbld31 commented
Docs Build status updates of commit _[54b3a52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54b3a525597d3a7f02e424b961b02172aca1fe68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-1a28ac76)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-1a28ac76)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 01:53 UTC, opbld31 commented
Docs Build status updates of commit _[aad5090](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aad509067b8a7a1e80aec3b136c14681d4746c6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-d3c6257d)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-d3c6257d)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 02:01 UTC, opbld30 commented
Docs Build status updates of commit _[c5882d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5882d60b6066362347b5efae1c9a62fb7fe1833)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-2ad6025b)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-2ad6025b)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 03:58 UTC, opbld30 commented
Docs Build status updates of commit _[e88edee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e88edee566368699d5f3fb807c65571b13930796)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-2c94e092)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-2c94e092)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 04:11 UTC, opbld30 commented
Docs Build status updates of commit _[2039e7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2039e7daebc60962800aec14aa96141a1c06107c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-27c8725d)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-27c8725d)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 04:37 UTC, opbld31 commented
Docs Build status updates of commit _[4095e8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4095e8a26fd4381dbc44ee244ecd402cf06f9ff0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-12564f27)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-12564f27)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 05:29 UTC, opbld31 commented
Docs Build status updates of commit _[beb8be5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/beb8be5e88f67c0d82a284d15ef4f4df4a6cfac0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-3eabab3d)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-3eabab3d)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 06:54 UTC, opbld32 commented
Docs Build status updates of commit _[e864f8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e864f8dde13cb0c175a1b723a1331133779638b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-7770fce5)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-7770fce5)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 07:34 UTC, opbld34 commented
Docs Build status updates of commit _[7d910c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d910c7be64700553c99c179651c59ddd052daff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-03128936)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-03128936)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) [...]

2021-04-22 18:54 UTC, opbld31 commented
Docs Build status updates of commit _[a782051](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a782051e3634cab9d7e83a05a2a414225714d7d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-ddd11819)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-ddd11819)
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-ddd11819)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/bet [...]

2021-04-22 22:49 UTC, opbld32 commented
Docs Build status updates of commit _[65d7f69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65d7f69eee072ac28bfeaaefb8d7e4b7962e904b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 02:45 UTC, opbld30 commented
Docs Build status updates of commit _[97b7bd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97b7bd78a24d5d768b726f8c78a5b90c2a9f04d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-6d3dd564)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-6d3dd564)
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-6d3dd564)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/bet [...]

2021-04-23 02:54 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +Today, the deployment service supports managing Windows 10 feature updates and expediting Windows 10 security updates. To learn more about the deployment service, please see [Overview of the deployme
Line 20:
Should we delete or comment out the second sentence?
Is it supposed to point to the API overview we talked about today, that will take a few more days to complete after initial publishing?

2021-04-23 03:00 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +* Be Azure AD joined or Hybrid AD joined
Line 31:
I changed this to "joined to Azure AD or Hybrid AD" to make it clearer for localization.
If you confirm that there are phrases like "Azure AD-joined" commonly used in the industry, then yes, please rephrase again and add the hyphens as follow:
"Be Azure AD-joined or Hybrid AD-joined".

2021-04-23 03:50 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-concept-overview.md
> +* Be Azure AD joined or Hybrid AD joined
Yes, it's a common phrase, but without the hyphen: https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-azure-ad-join

2021-04-23 03:52 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-concept-overview.md
> +Today, the deployment service supports managing Windows 10 feature updates and expediting Windows 10 security updates. To learn more about the deployment service, please see [Overview of the deployme
We were planning on adding a link to other documentation we will have in the Windows doc set. Does that work? I can add the link in before we publish.

2021-04-23 05:59 UTC, angelgolfer-ms commented on concepts/windowsupdates-software-updates.md
> +
Line 18:
I know I rephrased these two sentences in my last review. The sentences are still very clunky. FYI I have further rewritten them to reduce extra words (per Microsoft Voice). Please take a look below and let me know if I neglected any nuance I am not aware of.

"The service currently deploys only feature updates and _security_ quality updates. The service currently does not deploy quality updates that manage drivers."

2021-04-23 06:42 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-deployment-create.md
> +# Create deployment
Filename:
Likely I didn't pay attention to the filename last time.
For both the "create" and "list" topics for the deployment resource, the filenames are not consistent with the rest of the Graph docs, based on your CSDL and the syntax of these two operations.
The "create" topic filename should be update-post-deployments.md.
The "list" topic filename should be update-list-deployments.md.

Please see the filenaming topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

Did the generator generate these filenames?
If so, we need to report them as bugs :-|

2021-04-23 06:48 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableasset-list.md
> +# List updatableAssets
Filename:
This filename should be windowsupdates-updates-list-updatableAssets.md.
The pattern is {subnamespace-name}-{parententityname}-list-{navigationpropertyname}.md.

See CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

2021-04-23 07:57 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-azureaddevice-list.md
> +# List azureADDevices
Filename and topic title:
The current filename (windowsupdates-azureaddevice-list.md) is not consistent with other "list" operation files in the repo. The general pattern is {subnamespace-name}-{parententityname}-list-{navigationpropertyname}.md.

Also - overlooked in the first pass with the 70 new files - technically this syntax is just applying a query parameter $filter on the response from a list updatableAssets operation. In other API sets, this kind of syntax (applying a query parameter to a list operation) wouldn't even get its own separate topic, but would be documented as one use case of the list updatableAssets operation, with a syntax line and an example showing the use of the query parameter.

But since you already created this separate topic, and I think its existence as listed in the TOC as a separate topic would help educate customers better, let's just proceed to keep this as a separate topic. (Which begs the question - did the generator generate this topic as we see it now, with this filename and topic title?)

Alright, back to the filename, now that we're creating a topic somewhat manually - because the syntax before the query parameter does include the segments of a parent entity (updates) and its nav property (updatableAssets) which is the base type for azureADDevice, but, we're not supposed to pluralize a resource name by simply adding an 's' to form the term "azureADDevices", I suggest naming the file by appending the derived type to the end of the filename?
That is, {subnamespace-name}-{parententityname}-list-{navigationpropertyname}-{derivedentityname}.md
windowsupdates-updates-list-updatableassets-azureaddevice.md

As for the topic title, as mentioned, we're not supposed to just add an 's' to a resource name to form a new term, if that term is not defined in the CSDL. For clarity, I would suggest "List azureADDevice resources".

2021-04-23 08:05 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-list.md
> +# List updatableAssetGroups
Filename and topic title:
Similar to the comments for the topic for "list Azure AD devices", I am suggesting the using the filename of the pattern {subnamespace-name}-{parententityname}-list-{navigationpropertyname}-{derivedentityname}.md. 
That is:
windowsupdates-updates-list-updatableassets-updatableassetgroup.md

As for the topic title, as mentioned, we're not supposed to just add an 's' to a resource name to form a new term, if that term is not defined in the CSDL. For clarity, I would suggest and changed the topic title to "List updatableAssetGroup resources".

Please do a search and replace when you rename the file, and anywhere the topic title is used. I updated the Method column of the Methods table in the parent resource topic.

2021-04-23 08:05 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-azureaddevice-list.md
> +# List azureADDevices
Please do a search and replace when you rename the file, and anywhere the topic title is used. I updated the Method column of the Methods table in the parent resource topic.

2021-04-23 08:12 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-create.md
> +# Create updatableAssetGroup
Filename:
The current filename windowsupdates-updatableassetgroup-create.md is quite far off from the filenaming guideline, which in general is {subnamespace-name}-{parententityname}-post-{navigationpropertyname}.md

Based on the syntax and the CSDL, and similar to what we're doing to the "list updatable asset groups" topic, I suggest the filename:
windowsupdates-updates-post-updatableassets-updatableassetgroup.md

Please do a search and replace when you rename this file to avoid breaking existing links to this topic.

2021-04-23 08:29 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-updatableassetgroup-list-members.md
> +List the members of an updatable asset group.
Line 15:
FYI I added a sentence to clarify the type of these members, which is azureADDevice.
I searched the topic in its current state and we haven't explicitly stated the data type of the members. (The updatableAssetGroup resource topic does, fortunately, but we shouldn't expect customers to always correlate with the parent resource topic. Many customers just dip into the docs and quickly go back to their code; they typically don't spend a lot of time in the docs.)

2021-04-23 08:52 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Expedited quality update reference
Lines 9500-9503:
I still find it a little odd to have these two deployable content types coming after a list of operations, under a resource (deployment) the name of which doesn't intuitively reveal any correlation to an "xxx update reference". 

Usually under a parent resource node, there's a list of methods. Related resources (such as significant types derived from the parent resource) would come before the list of methods, not after. In this case, these xxxupdateReference types are related to but not derived from the deployment resource either.

FYI I inserted a parent node under the deployment node, for the 2 xxxupdateReference types. The extra node is named "Deployable content". BTW I intentionally left out the actual deployableContent resource under the node, because it's just an abstract complex type with no properties.

2021-04-23 09:01 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-deploymentaudience.md
> +The set of assets to which a deployment can apply.
Line 16:
I replaced "assets" by the actual type name with a link to it.
"The set of [updatableAsset](../resources/windowsupdates-updatableasset.md) resources..."

In general, in an API or resource topic, the summary description should include the names of any pertinent resources, and since they're usually first references in the topic, include links to them as well.

2021-04-23 09:24 UTC, opbld31 commented
Docs Build status updates of commit _[076cc3c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/076cc3ceb2cfec38f0a9c15b032a587b95cf2262)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/docfx.json) | :warning:Warning | | [Details](#user-content-dc08a42aabb6d45f19bca283e994adce-df782834)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-df782834)
[concepts/windowsupdates-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/concepts/windowsupdates-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/windowsupdates-concept-overview?branch=pr-en-us-12220) | [Details](#user-content-4034f41341083acc879ab7d207e57da3-df782834)
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/bet [...]

2021-04-23 09:36 UTC, angelgolfer-ms requested changes
Hi @Alice-at-Microsoft , I made some more fixes in the PR directly mainly for clarity or consistency. Feel free to look at the comments I left for your info, and also the commits I did tonight, in case you'd like to know what I changed exactly.
There are a few files that have filenames not following the general file naming guidelines for "list" and "create" operations. I made comments for those files; please follow up on renaming the files, and update any links that could be pointing to the old filenames. Please let me know if you have questions about the filename patterns.

Also, please confirm if the generator actually generated those unconventional filenames.

I still need perhaps another 1-2 hours to go over the remaining topics I haven't looked at tonight. I can look at them noon-2pm on Friday 4/23, if that works for you/ the other authors. Please send me a message on Teams if you're like to rearrange that time.

Thanks!

2021-04-23 20:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-deploymentaudience.md
> +|exclusions|[microsoft.graph.windowsUpdates.updatableAsset](../resources/windowsupdates-updatableasset.md) collection|Specifies the assets to exclude from the audience. Takes precedence over members.
Line 34:
Here, can you elaborate what "Takes precedence over members." actually means?

That sentence as is made me _imagine_ what happens if:
(a) An "update members and exclusions" includes the same asset in the addMembers and addExclusions parameters. Does this sentence imply addExclusions takes precedence over addMembers, and the asset would be included in the exclusions nav property collection but not the members nav property collection?
(b) "list members" and "list exclusions" should never show the same asset in their responses?

If (a) or (b) is what actually happens, then it would be good to elaborate in those API topics as well. Letting customers guess is usually not as helpful.

2021-04-23 21:33 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-updatableasseterror.md
> +All updatable asset errors exist as one of the following derived types: [azureADDeviceRegistrationError](../resources/windowsupdates-azureaddeviceregistrationerror.md).
Line 18:
For now, since all updatableAssetError resources are always the derived type azureADDeviceRegistrationError, I'm going to rephrase lines 16-20 as:

"An abstract type that represents an error which prevents the deployment service from enrolling an [azureADDevice](../resources/windowsupdates-azureaddevice.md) in update management, or deploying content to the device. 

All updatable asset errors are of the derived type, [azureADDeviceRegistrationError](../resources/windowsupdates-azureaddeviceregistrationerror.md)."

The current sentence sounds robotic, which is against the Microsoft Voice principle.
If/when in the future you add more possible types, then you can please rephrase the sentence again.

2021-04-23 21:44 UTC, opbld33 commented
Docs Build status updates of commit _[5dca1d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dca1d2652b8e25650c0f99867471ba2ba115b1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-u [...]

2021-04-23 21:45 UTC, opbld31 commented
Docs Build status updates of commit _[c0fae38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0fae38bf2d01ae382cda0a7d8668a8e5863c461)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-u [...]

2021-04-23 22:37 UTC, angelgolfer-ms requested changes
Hi @Alice-at-Microsoft , I looked at the few remaining topics today and wrapped up my second pass. I think I left one more comment actionable by you/your peer authors. Please feel free to update the PR directly now.

2021-04-26 18:09 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-software-updates.md
> +
I'm updating to "The service currently does not deploy driver updates" to keep it simple. Does that work?

2021-04-26 18:12 UTC, Alice-at-Microsoft commented on api-reference/beta/api/windowsupdates-updatableasset-list.md
> +# List updatableAssets
@angelgolfer-ms Similarly, should List azureADDevices and List upatableAssetGroups follow this pattern?

2021-04-26 20:25 UTC, Alice-at-Microsoft commented on api-reference/beta/resources/windowsupdates-deploymentaudience.md
> +|exclusions|[microsoft.graph.windowsUpdates.updatableAsset](../resources/windowsupdates-updatableasset.md) collection|Specifies the assets to exclude from the audience. Takes precedence over members.
@angelgolfer-ms An updatable asset can be in both members and exclusions at the same time. The statement was supposed to clarify that if a device is in exclusions, that device will be excluded even if it's in members (directly as an azureADDevice or as part of an updatableAssetGroup).

What do you think about removing that sentence completely? Is the above behavior clear as-is? (i.e. deployment audience is populated by members minus exclusions.)

Adding the following sentence to the update audience actions: "The same updatableAsset {link} object can be in both the members and exclusions collections."

2021-04-26 20:30 UTC, opbld32 commented
Docs Build status updates of commit _[9592bb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9592bb3809d39abe14af15146f7277e9956d0e55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-create?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-list?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-u [...]

2021-04-26 23:14 UTC, opbld31 commented
Docs Build status updates of commit _[7f341ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f341ab8397c477f16e496dc69d7cd88e55959a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-26 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[5c53de1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c53de100a7a29e1e7a98128a7063a499d9dd741)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-26 23:50 UTC, opbld32 commented
Docs Build status updates of commit _[ed8f574](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed8f574425bf1f0e9d4a0f0d38439e8f868c7cad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 04:20 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md
> +An [updatableAsset](../resources/windowsupdates-updatableasset.md) can be included in both the members and exclusions collections.
Line 19: 
Based on line 34 in windowsupdates-deploymentaudience.md where you added:
"If an **updatableAsset** belongs to both **members** and **exclusions**, a deployment will not apply to it."

Seems to be appropriate to complete the idea in line 19 here and say:
"If the same **updatableAsset** resource is included in the **exclusions** and **members** relationships, deployment will not apply to it."

I think it's correct, so in the interest of time, I am going ahead to make the idea more complete. Please let me know if this shouldn't be though.

2021-04-27 04:41 UTC, angelgolfer-ms commented on api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md
> +
Line 19:
Making similar update to clarify what happens:
"If the same updatableAsset resource gets included in the exclusions and members relationships, deployment will not apply to it."

2021-04-27 04:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/windowsupdates-deploymentaudience.md
> +|exclusions|[microsoft.graph.windowsUpdates.updatableAsset](../resources/windowsupdates-updatableasset.md) collection|Specifies the assets to exclude from the audience. If an **updatableAsset** belon
Line 34:
I'm moving this new sentence up to the top of this topic. By convention, we place info that's generally helpful for understanding an API set in that location of the parent resource topic, to make the info more noticeable.

2021-04-27 04:47 UTC, opbld34 commented
Docs Build status updates of commit _[748cf56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/748cf56ee72b34aa910a4149dd26a88bbcc969c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 04:49 UTC, opbld32 commented
Docs Build status updates of commit _[835fc1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/835fc1e377c938e13c3075a36772cc788d32839f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 05:55 UTC, opbld32 commented
Docs Build status updates of commit _[60a54c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60a54c9089c89573a001655095799ab8e249bd9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 08:21 UTC, angelgolfer-ms commented on concepts/windowsupdates-concept-overview.md
> +* Be Azure AD joined or Hybrid AD joined
Since the non-hyphenated version is all over the place on the internet, and I am not sure if at some point that form marketing officially prescribe that use, we can use the non-hyphenated version.
Technically/ grammatically, there should be a hyphen :-)
(Section titled "Hyphen in a Compound Expression With a Noun and Past Participle" on  [Grammarly](https://www.grammarly.com/blog/hyphen/).)

2021-04-27 08:43 UTC, angelgolfer-ms commented on concepts/windowsupdates-software-updates.md
> +
Are driver updates one type of non-security quality updates, and there are other types?
Or are all non-security quality updates driver updates?
I guess the first question is yes.
Assuming that's the case, that's the part I felt is disjoint - we talk about feature updates, quality updates, security quality updates in the first 2 sentences. Then in the third sentence we reference "driver updates". Where does driver updates fit in? It's a piece of fact ok. But if the first sentence is to serve as topic sentence for that paragraph, then the third sentence is standing on its own, seemingly unrelated.

How about:
"... The service currently does not deploy non-security quality updates, including driver updates."

2021-04-27 09:02 UTC, opbld30 commented
Docs Build status updates of commit _[ccb674f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccb674faa2ddfe2a3373da1d7335c3add55f5313)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 09:06 UTC, angelgolfer-ms approved these changes
There is one last issue I'm responding to your suggestion, [here](https://github.com/microsoftgraph/microsoft-graph-docs/pull/12220/files/c0fae38bf2d01ae382cda0a7d8668a8e5863c461..60a54c9089c89573a001655095799ab8e249bd9c#r620993437).
I don't have other requests at this point. I'm approving this PR as I'll be in a few meetings tomorrow first part of the day, and I can let you finish up and proceed with the protocol to publish (step 8 in this [topic](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103181/Content-workflow)).

Thank you for the timely follow-ups!

2021-04-27 16:23 UTC, opbld30 commented
Docs Build status updates of commit _[61cfc94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61cfc942fd86fae570fed1ab0295f52266a766d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 16:23 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-software-updates.md
> +
I realize that the confusion comes from the fact that the deployment service has different taxonomy from where customers might be starting from. I updated to clarify the deployment service taxonomy. Hopefully that makes the last two sentences more clear.

2021-04-27 16:44 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-concept-overview.md
> +* Be Azure AD joined or Hybrid AD joined
Yep, I'm all for proper hyphenation :)

2021-04-27 16:52 UTC, opbld34 commented
Docs Build status updates of commit _[c145ffe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c145ffe617a3709dc3a8f2a505938db5750dd412)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 17:22 UTC, opbld31 commented
Docs Build status updates of commit _[ef0981f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef0981fed135dcbeb9ef03418d764db6cb6ceb86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 20:09 UTC, angelgolfer-ms commented on concepts/windowsupdates-software-updates.md
> +
Oh so you mean, the first sentence is one taxonomy, the second sentence (deployment service catalog) refers to another taxonomy. 
The phrase you added to the second sentence says how driver updates _don't_ belong to the second taxonomy:
"...and driver updates are excluded from the definition of quality updates"

So do driver updates belong to the first taxonomy?
If it belongs to the first taxonomy, we can include a mention there (as quality updates?)
If it doesn't belong to either taxonomy, we should still include a mention in the first, more general sentence that introduces what there are in consideration. We start with "there are...", so ca we make a clarification there?

Even if we say driver updates aren't even a type of Windows updates:
"There are two main categories of Windows 10 updates - feature updates, quality updates; in addition, there are driver updates."

2021-04-27 20:18 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-software-updates.md
> +
@angelgolfer-ms Right, the first sentence is the taxonomy that IT admins may be more familiar with (see the definition of quality updates here: https://docs.microsoft.com/en-us/windows/deployment/update/waas-quick-start). The second sentence tries to translate the first taxonomy into the second, deployment service taxonomy. Then the last sentence describes what is supported relative to the deployment service taxonomy.

2021-04-27 20:20 UTC, Alice-at-Microsoft commented on concepts/windowsupdates-software-updates.md
> +
"There are two high-level categories of Windows 10 updates: feature updates and quality updates, with the definition of quality updates typically including security updates, critical updates, servicing stack updates, and driver updates. In the deployment service catalog, quality updates are classified as security and non-security, and driver updates are excluded from the definition of quality updates."

2021-04-27 20:34 UTC, opbld33 commented
Docs Build status updates of commit _[fa7acd4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa7acd458ef0d6b292868e3dad2ea30c187c6b94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 21:30 UTC, opbld31 commented
Docs Build status updates of commit _[21e4fa3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21e4fa38e0d1a0120b7a471c8ebb21d614a612d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 23:40 UTC, opbld30 commented
Docs Build status updates of commit _[737de4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/737de4cb6740b053bff70fd39a35a2fe76caaafc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-27 23:45 UTC, opbld33 commented
Docs Build status updates of commit _[b29b06b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b29b06b00f5c7bdb212a666e88c30fb305dedb48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-28 01:11 UTC, opbld30 commented
Docs Build status updates of commit _[3e59db3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e59db333f9d752a4fdf1a6dc1b1cf37d16802e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-28 01:23 UTC, opbld32 commented
Docs Build status updates of commit _[135ada0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/135ada00c1000ed0656676844f965afe09ffbde1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/windowsupdates-azureaddevice-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-azureaddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-azureaddevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-azureaddevice-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-catalog-list-entries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-catalog-list-entries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-catalog-list-entries?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deployment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deployment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deployment-update?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-exclusions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-exclusions?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudience.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudience?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-deploymentaudience-updateaudiencebyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-updateaudiencebyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-delete?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-enrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-enrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-get?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassets?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableasset-unenrollassetsbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableasset-unenrollassetsbyid?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/windowsupdates-updatableassetgroup-addmembers?view=graph-rest-beta&branch=pr-en-us-12220) (graph-rest-beta) |
[api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-06-altang-wufb-deployment-service/api-reference/beta/api/windowsupdates-updatableassetgroup-addmembersbyid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ap [...]

2021-04-28 01:25 UTC, merged