[CloudPC]Add CloudPC RBAC APIs
microsoftgraph/microsoft-graph-docs pull request #12237
Opened 2021-04-08 08:10 UTC by AshleyYangSZ

2021-04-08 08:14 UTC, opbld32 commented
Docs Build status updates of commit _[e953ea1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e953ea1b7b72ea0c42f934b15d01d23aaa58c34f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-71cd9d44)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-4492e0304c315f015cc937726fd57ced-71cd9d44)
[api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f2387f1cbab642ed1560948ba6b130ed-71cd9d44)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-71cd9d44)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-33cafde8709db6981c77bd10f95e17a2-71cd9d44)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-be0a600903274916b4f3b90d5c424c65-71cd9d44)
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-2576209ab0d55312f2ea88cd319c7da6-71cd9d44)
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7bf8f9abf1c82b93a18d507fb15b9c7c-71cd9d44)
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a5d9f32609434ca8924d1ba58dd2df5d-71cd9d44)
[api-reference/beta/resources/cloudpc-rbac-rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-rolemanagement.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f94431bbe74eb26821b041f0d85dedea-71cd9d44)
[api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b820db235aa9f6e5f105380f22ff03f-71cd9d44)

<a id="7e7253f75c611e5f0360fcaac688711c-71cd9d44"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 16, Column 48**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpr-rbac-unifiedroleassignmentmultiple.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````

<a id="4492e0304c315f015cc937726fd57ced-71cd9d44"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md)
 - **Line 99, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update unifiedRoleAssignmentMultiple - Microsoft Graph beta' is duplicated in: 'beta/api/cloudpc-unifiedroleassignmentmultiple-update.md(2,8), beta/api/unifiedroleassignmentmultiple-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-update.md(10,1), beta/api/unifiedroleassignmentmultiple- [...]

2021-04-08 09:21 UTC, opbld30 commented
Docs Build status updates of commit _[29c59b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29c59b41d688417bab241ac9b3f45fce00ab33de)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-28a084d9)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-28a084d9)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-28a084d9"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="7e7253f75c611e5f0360fcaac688711c-28a084d9"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104080917439805-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MfYO%2Bcx8RVa9d2YO%2F%2FseYDwKn%2B2Hf3wMSMtle%2FHAybw%3D&st=2021-04-08T09%3A15%3A58Z&se=2021-05-09T09%3A20%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master [...]

2021-04-09 07:57 UTC, opbld30 commented
Docs Build status updates of commit _[6101c5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6101c5f8eef1861722fff8ff3ebf253c7dc35d23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9b816e29)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-9b816e29)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-9b816e29"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="7e7253f75c611e5f0360fcaac688711c-9b816e29"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104090756095597-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gb35Y%2FU1gXpxZIslonooAMNCOfKHZG1LLr91%2BqOzEQY%3D&st=2021-04-09T07%3A52%3A27Z&se=2021-05-10T07%3A57%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to [...]

2021-04-13 18:38 UTC, abhijeetsinha commented on api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md
> +# cloudpc unifiedRoleDefinition resource type
@AshleyYangSZ  - This file is not needed. Refer to our existing documentation for resource type - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta. 
cc: @rolyon

2021-04-13 18:39 UTC, abhijeetsinha commented on api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md
> +# cloudpc unifiedRoleAssignmentMultiple resource type
@AshleyYangSZ -  This file is not needed. Refer to our existing documentation for resource type wherever needed - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta
cc: @rolyon

2021-04-13 18:40 UTC, abhijeetsinha commented on api-reference/beta/resources/cloudpc-rbac-rolemanagement.md
> +# cloudpc roleManagement resource type
@AshleyYangSZ - Again, this file is not needed. Refer to existing documentation - https://docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta. 
I can add a blurb about CloudPC in original documentation when you are in beta. 
cc: @rolyon

2021-04-13 18:41 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +Get a list of [unifiedRoleDefinition](../resources/cloudpc-rbac-unifiedroledefinition.md) objects for the cloud pc provider.
@AshleyYangSZ - UnifiedRoleDefinition link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta

2021-04-13 18:42 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +If successful, this method returns a `200 OK` response code and a collection of [unifiedRoleDefinition](../resources/cloudpc-rbac-unifiedroledefinition.md) objects in the response body.
@AshleyYangSZ - UnifiedRoleDefinition link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta

2021-04-13 18:43 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md
> +Get a list of [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object.
@AshleyYangSZ -  UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:43 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md
> +If successful, this method returns a `200 OK` response code and a collection of [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) objects in the response bod
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:44 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md
> +Update an existing [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:44 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md
> +If successful, this method returns a `200 OK` response code and an updated [unifiedAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentMultiple.md) object in the response body.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:45 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md
> +Create a new [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object. Use this object to create role assignments.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:45 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md
> +In the request body, supply a JSON representation of [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:45 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md
> +If successful, this method returns a `201 Created` response code and a new [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object in the response body.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:46 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md
> +    "principalIds": ["f8ca5a85-489a-49a0-b555-0a6d81e56f0d", "c1518aa9-4da5-4c84-a902-a31404023890"]
@AshleyYangSZ - scope is missing.

2021-04-13 18:46 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md
> +Retrieve the properties and relationships of a [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:46 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md
> +If successful, this method returns a `200 OK` response code and the requested [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object in the response body.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:47 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md
> +Delete a [unifiedRoleAssignmentMultiple](../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) object.
@AshleyYangSZ - UnifiedRoleAssignmentMultiple link should be to original doc here - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta

2021-04-13 18:48 UTC, abhijeetsinha commented on api-reference/beta/api/cloudpc-unifiedroledefinition-get.md
> +Retrieve the properties and relationships of a cloud pc [unifiedRoleDefinition](../resources/cloudpc-rbac-unifiedRoleDefinition.md) object.
@AshleyYangSZ - UnifiedRoleDefinition link should be to the original doc - https://docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta

2021-05-08 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[d2f300e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2f300e4d020cf0e1843defc7f8b3d818731f726)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-4132ed93)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-4132ed93)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/cloudpc-rbac-unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc-rbac-unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-4132ed93"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-4132ed93"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105080302002121-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f1RmkjUsxp%2BsbFYZgzkas2pVVMGvWvrZY23uJTr74u0%3D&st=2021-05-08T02%3A59%3A03Z&se=2021- [...]

2021-05-08 06:25 UTC, opbld32 commented
Docs Build status updates of commit _[7b8b6e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b8b6e8530b7b34b99352895f846d86189f45209)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-33cafde8709db6981c77bd10f95e17a2-a8b90bd5)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-a8b90bd5)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-be0a600903274916b4f3b90d5c424c65-a8b90bd5)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-4492e0304c315f015cc937726fd57ced-a8b90bd5)
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-2576209ab0d55312f2ea88cd319c7da6-a8b90bd5)
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7bf8f9abf1c82b93a18d507fb15b9c7c-a8b90bd5)
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a5d9f32609434ca8924d1ba58dd2df5d-a8b90bd5)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a8b90bd5)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-a8b90bd5)
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="33cafde8709db6981c77bd10f95e17a2-a8b90bd5"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md)
 - **Line 16, Column 10**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 10**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 16, Column 10**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="7e7253f75c611e5f0360fcaac688711c-a8b90bd5"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 16, Column 48**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 53, Column 79**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````
 - **Line 16, Column 48**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com [...]

2021-05-08 06:54 UTC, opbld31 commented
Docs Build status updates of commit _[0f9d8c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f9d8c706c9c24f5e4a5238ccdf63f82fa28dab4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-c1990f03)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c1990f03)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-c1990f03)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-c1990f03"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="0817dce4456c16725d5333633847d38f-c1990f03"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 9496, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-c1990f03"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105080653326364-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ro8uSoKIvwQh5z73JxOF0Usv%2F%2FBbnqqtsLX4t%2FoRG6g%3D&st=2021-05-08T06%3A49%3A52Z&se=2021-06-08T06%3A54%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like [...]

2021-05-08 07:00 UTC, opbld30 commented
Docs Build status updates of commit _[dcb7a39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcb7a3909f165f0cb481a710a5dcb911020a98a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-33f8433d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-33f8433d)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-33f8433d)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-33f8433d"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="0817dce4456c16725d5333633847d38f-33f8433d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 9496, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-33f8433d"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105080659244906-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gk0Ak7JDhwQZWxv7Ub3fG3MLh8ullS9C%2FuURdtStnC8%3D&st=2021-05-08T06%3A55%3A42Z&se=2021-06-08T07%3A00%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like Git [...]

2021-05-08 07:10 UTC, opbld34 commented
Docs Build status updates of commit _[82d45c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82d45c70fe8933e501014ff29d1d012298ff8ee8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-09ef7448)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-09ef7448)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-09ef7448)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-09ef7448"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="0817dce4456c16725d5333633847d38f-09ef7448"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 9496, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-09ef7448"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105080709174973-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q4jcTXQS4z4kMrqF0n6Prk6nj58YSK%2F8rnAPCGK%2BgrE%3D&st=2021-05-08T07%3A05%3A35Z&se=2021-06-08T07%3A10%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like G [...]

2021-05-18 13:35 UTC, opbld30 commented
Docs Build status updates of commit _[0793cd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0793cd534f10c8f359bf38e6e653d7f82f0b45eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-04192f96)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-04192f96)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-04192f96)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-04192f96"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="0817dce4456c16725d5333633847d38f-04192f96"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 9496, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-04192f96"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105181333365724-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OKgDqPfhjzmU4qLoMwQh8DaaoLxW3502PNPWiFn5fmM%3D&st=2021-05-18T13%3A30%3A25Z&se=2021-06-18T13%3A35%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitH [...]

2021-05-18 16:03 UTC, opbld31 commented
Docs Build status updates of commit _[3fd69c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fd69c547054c7f2fc97c1cf84be3b0f7ae74ee0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-b535765f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b535765f)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-b535765f)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-b535765f"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="0817dce4456c16725d5333633847d38f-b535765f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 9496, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-b535765f"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105181602421758-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y9UNw9ahnumRRcRqzocknvtPvK%2BG%2F6X7ca7N2R6%2BnZA%3D&st=2021-05-18T15%3A58%3A58Z&se=2021-06-18T16%3A03%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies lik [...]

2021-05-21 05:07 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            href: resources/cloudpc-rbac-unifiedroleassignmentmultiple.md
Line 9496:
@AshleyYangSZ , should this be linking to unifiedroleassignmentmultiple.md, based on the names of the files you specify in lines 9501, 9503, 9505, 9507?

Right now this is a broken link.

2021-05-21 05:08 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Role assignment
Line 9495:
Should this say "Role assignment multiple", and not "role assignment", if you're attempting to link to the resource topic unifiedRoleAssignmentMultiple?

2021-05-21 05:15 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          href: resources/rolemanagement.md
@AshleyYangSZ , this comment is for the file rolemanagement.md.
According to your api.md file, roleManagement gets a new nav property called cloudPC.
Can you update rolemanagement.md please?

2021-05-21 05:42 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +
Filename: 
Based on the following definitions in your api.md file and the existing definition for rbacApplicationMultiple, I think the filename should be rbacapplicationmultiple-list-roledefinitions.md.

```
<EntityType Name="roleManagement" ags:AddressUrl="https://fakeEndpoint.net" ags:IsMaster="false" ags:AddressContainsEntitySetSegment="true" ags:IsSharedEntity="true" >
    <Property Name="id" Type="Edm.String" Nullable="false" />
    <NavigationProperty Name="cloudPC" Type="microsoft.graph.rbacApplicationMultiple" ContainsTarget="true" ags:AddressUrl="https://cpc-web-auth-beta-westus.azurewebsites.net/api/auth/odata/roleManagement/cloudPC"/>
</EntityType>


<EntityType Name="rbacApplicationMultiple" BaseType="graph.entity">
<NavigationProperty Name="resourceNamespaces" Type="Collection(graph.unifiedRbacResourceNamespace)" ContainsTarget="true"/>
<NavigationProperty Name="roleAssignments" Type="Collection(graph.unifiedRoleAssignmentMultiple)" ContainsTarget="true"/>
<NavigationProperty Name="roleDefinitions" Type="Collection(graph.unifiedRoleDefinition)" ContainsTarget="true"/>
</EntityType>
```

2021-05-21 05:45 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +
Also, because there are multiple workloads sharing the role management API, it wouldn't be appropriate to prefix the related resource and API files with "cloudpc".

2021-05-21 05:56 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +
Line 16:
For the description, I can suggest something like:
"Get a list of unifiedRoleDefinition (keep link) objects for Microsoft 365 RBAC providers that are of the rbacApplicationMultiple (provide link) type, and that support multiple principals and multiple scopes in a single role assignment.
The cloud PC provider is an example of such providers."

2021-05-21 06:05 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +# List cloudpc unifiedRoleDefinitions
Line 10:
The topic title should say "List roleDefinitions".
Please see the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title
The topic title pattern for "list: operations is "List {nav property name}".

2021-05-21 06:07 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +```http
Line 35:
Because you're customizing the syntax for cloudPc, please add a sentence before line 32 to call that out.
Something like:
"To list role definitions for a cloud PC provider:"

2021-05-21 06:12 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +# List cloudpc unifiedRoleDefinitions
Since you're creating a "list" roleDefinition operation topic for providers of the type rbacApplicationMultiple, please also update the existing rbacapplicationmultiple.md topic and update its Methods table.
Currently in that Methods table, "List roleDefinitions" is linking to the file for rbacApplication, and that isn't appropriate (https://docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta).

2021-05-21 06:16 UTC, opbld30 commented
Docs Build status updates of commit _[4211b39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4211b39c699c34be3754b90a2e96058f6d428449)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-685c7e63)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-685c7e63)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-685c7e63)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-685c7e63"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="0817dce4456c16725d5333633847d38f-685c7e63"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 9496, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-685c7e63"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105210613423287-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TvAcUy8OfdbvoRgpvLqmNlxRNg1lr25aCZpL%2FOVtiLg%3D&st=2021-05-21T06%3A11%3A05Z&se=2021-06-21T06%3A16%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like Gi [...]

2021-05-21 06:17 UTC, opbld31 commented
Docs Build status updates of commit _[8516f12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8516f12462b6ce5640e4de741773164608d30373)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-c0fc7a4d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c0fc7a4d)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-c0fc7a4d)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-c0fc7a4d"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

<a id="0817dce4456c16725d5333633847d38f-c0fc7a4d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml)
 - **Line 9496, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/cloudpc-rbac-unifiedroleassignmentmultiple.md'.`````

<a id="1b355d45e548fd68d24ac961f1a24e58-c0fc7a4d"></a>
### [api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of a unifiedRoleAssignmentMultiple object.' is duplicated in 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(3,14)', 'beta/api/unifiedroleassignmentmultiple-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105210614039672-12237%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PAAIu%2BsZtGBtaZQrR4MXgeCfbhBULi9SaXKmXnRA6iA%3D&st=2021-05-21T06%3A12%3A27Z&se=2021-06-21T06%3A17%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like Gi [...]

2021-05-21 19:36 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +
That being said, at an API design level, @abhijeetsinha confirmed offline that the "unified" term in "unifiedRoleDefinition" is meant to unify the roleDefinition schema (hence -> unifiedRoleDefinition) making that the  same for both rbacApplication and rbacApplicationMultiple, while leaving role assignment schema to vary for these provider types.
I think from the developer experience perspective, keeping the syntax for the two provider types in the same "list" operation topic for unifiedRoleDefinitions makes it clearer how Graph lets different resources share APIs.

So at the filename level, we'll use the existing file rbacappliation-list-roledefinitions.md.

2021-05-22 02:57 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +
FYI @AshleyYangSZ , I updated rbacapplication-list-roledefinitions.md to incorporate the content for a cloud PC provider. Please take a look at that topic, please check each section, and do the similar for the GET operation topic (unifiedroledefinition-get.md).

After you integrate cloud PC-specific content to unifiedroledefinition-get.md, you can delete your copies of cloudpcrbacappliation-list-roledefinitions.md and cloudpc-unifiedroledefinition-get.md.

2021-05-22 02:59 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md
> +
Oh as for the TOC, for the "list" operation, I already updated the TOC to link to rbacappliation-list-roledefinitions.md.

After you update unifiedroledefinition-get.md with the cloud PC content, please also update the TOC to have the "GET" operation link to unifiedroledefinition-get.md.

2021-05-22 03:00 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpc-unifiedroledefinition-get.md
Line 9494:
After you update unifiedroledefinition-get.md with the cloud PC content, please also update the TOC to have the "GET" operation link to unifiedroledefinition-get.md.

2021-05-22 03:28 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Role assignment
FYI I changed line 9495 to "Role assignment multiple".

2021-05-22 03:29 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            href: resources/cloudpc-rbac-unifiedroleassignmentmultiple.md
FYI I changed line 9496 to link to unifiedroleassignmentmultiple.md.

2021-05-22 03:31 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            items:
Lines 9498-9507:
I think since you're sharing the resource unifiedRoleAssignmentMultiple with other rbacApplicationMultiple providers, then you should be sharing the CRUD operations too, and not create cloud PC-specific topics for the CRUD operations.

2021-05-22 03:51 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpcrbacapplication-list-roleassignments.md
Line 9499:
@AshleyYangSZ , @abhijeetsinha ,
FYI this should link to a file named rbacapplicationmultiple-list-roleassignments.md. I'm going to rename the existing file unifiedroleassignmentmultiple-list.md as  rbacapplicationmultiple-list-roleassignments.md.

The filename is based on the syntax, for example, for deviceManagement:
GET /roleManagement/deviceManagement/roleAssignments

It's also based on the CSDL that defines the last 2 segments in the query URL above:
<EntityType Name="roleManagement">
<NavigationProperty Name="directory" Type="graph.rbacApplication" ContainsTarget="true"/>
<NavigationProperty Name="cloudPC" Type="graph.rbacApplicationMultiple" ContainsTarget="true"/>
<NavigationProperty Name="entitlementManagement" Type="graph.rbacApplication" ContainsTarget="true"/>
<NavigationProperty Name="deviceManagement" Type="graph.rbacApplicationMultiple" ContainsTarget="true"/>
</EntityType>

<EntityType Name="rbacApplicationMultiple" BaseType="graph.entity">
<NavigationProperty Name="resourceNamespaces" Type="Collection(graph.unifiedRbacResourceNamespace)" ContainsTarget="true"/>
<NavigationProperty Name="roleAssignments" Type="Collection(graph.unifiedRoleAssignmentMultiple)" ContainsTarget="true"/>
<NavigationProperty Name="roleDefinitions" Type="Collection(graph.unifiedRoleDefinition)" ContainsTarget="true"/>
</EntityType>

The filenaming is described here as well: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

2021-05-22 04:06 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpc-unifiedroleassignmentmultiple-post.md
Line 9503:
Similar to the "list" operation topic, the "post" operation topic filename should be rbacapplicationmultiple-post-roleassignments.md.

2021-05-22 04:08 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpc-unifiedroleassignmentmultiple-post.md
FYI I renamed the existing file unifiedroleassignmentmultiple-post.md as rbacapplicationmultiple-post-roleassignments.md. I also updated the TOC to point to rbacapplicationmultiple-post-roleassignments.md.

2021-05-22 04:08 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpcrbacapplication-list-roleassignments.md
FYI I renamed the existing file unifiedroleassignmentmultiple-list.md as rbacapplicationmultiple-list-roleassignments.md. I also updated the TOC to point to rbacapplicationmultiple-list-roleassignments.md.

2021-05-22 04:13 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpc-unifiedroleassignmentmultiple-get.md
Line 9501:
@AshleyYangSZ , for the GET operation, please use the existing file unifiedroleassignmentmultiple-get.md.
Please integrate your cloud PC content with that file.
Then you can delete the file cloudpc-unifiedroleassignmentmultiple-get.md.

2021-05-22 04:17 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpc-unifiedroleassignmentmultiple-update.md
Line 9505:
@AshleyYangSZ , for the PATCH operation, please use the existing file unifiedroleassignmentmultiple-update.md.
Please integrate your cloud PC content with that file.
Then you can delete the file cloudpc-unifiedroleassignmentmultiple-update.md.

2021-05-22 04:18 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +              href: api/cloudpc-unifiedroleassignmentmultiple-delete.md
Line 9507:
@AshleyYangSZ , for the DELETE operation, please use the existing file unifiedroleassignmentmultiple-delete.md.
Please integrate your cloud PC content with that file.
Then you can delete the file cloudpc-unifiedroleassignmentmultiple-delete.md.

2021-05-22 04:25 UTC, opbld34 commented
Docs Build status updates of commit _[ebda2e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebda2e944744b99f13b19e0eb2de1fbc3ab93d1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-afc186df)
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-afc186df)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-afc186df)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-afc186df)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-afc186df"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descript [...]

2021-05-22 04:26 UTC, opbld34 commented
Docs Build status updates of commit _[3eac7f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3eac7f1632b77df2e73219b531e8edbbd7a6f8a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-13b29bb5)
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-13b29bb5)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-13b29bb5)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-13b29bb5)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-13b29bb5"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descript [...]

2021-05-22 07:37 UTC, angelgolfer-ms commented on api-reference/beta/resources/rolemanagement.md
> +|cloudPC|[rbacApplicationMultiple](rbacapplicationmultiple.md)| Read-only. Nullable.|
Line 40:
@AshleyYangSZ , can you please add a description?

2021-05-22 07:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/rolemanagement.md
> +
Lines 42, 43:
@abhijeetsinha , can you please add descriptions for these 2 rows?

2021-05-22 07:44 UTC, angelgolfer-ms commented on api-reference/beta/resources/unifiedroledefinition.md
> +
Lines 18-20:
@abhijeetsinha , I didn't include Intune here because the existing CRUD topics under [unifiedRoleDefintion](https://docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta) don't show any syntax or examples for Intune.
If Intune supports unifiedRoleDefinition, please add a bullet point here, and update the CRUD operation topics to include Intune.

2021-05-22 07:49 UTC, opbld34 commented
Docs Build status updates of commit _[8f181be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f181beb496eb480fe083259d7ed8b5651b7d8a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-7e7253f75c611e5f0360fcaac688711c-288f4dce)
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-288f4dce)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-288f4dce)
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-1b355d45e548fd68d24ac961f1a24e58-288f4dce)
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-post?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpcrbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcrbacapplication-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="7e7253f75c611e5f0360fcaac688711c-288f4dce"></a>
### [api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/cloudpc-unifiedroleassignmentmultiple-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get unifiedRoleAssignmentMultiple' is duplicated with other articles: 'beta/api/cloudpc-unifiedroleassignmentmultiple-get.md(10,1), beta/api/unifiedroleassignmentmultiple-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descript [...]

2021-05-22 07:57 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "ChangeList": [
@AshleyYangSZ , did Graph Studio generate these 3 changelist records?

If so, hm, I don't think the descriptions are meaningful to most developers.
The link text such as cloudpc-rbac-rolemanagement, cloud-pc-unifiedroledefinition, and cloud-pc-unifiedroleassignmentmultiple and their links don't map to anything that exists or should exist, right?

Think what's meaningful to customers - that cloud PC RBAC providers now support listing and getting unifiedRoleDefinitions, and the CRUD operations of unifiedRoleAssignmentMultiple?

2021-05-22 08:11 UTC, angelgolfer-ms requested changes
@AshleyYangSZ , I made some commits to update the related resource topics and the "list" operation topic for unifiedRoleDefinition (rbacapplication-list-roledefinitions.md) to incorporate support for cloud PC providers. 
Please take a look, and then do the similar to unifiedroledefinition-get.md, and the 5 CRUD operations topics for unifiedRoleAssignmentMultiple, to incorporate cloud PC as well.

Then, update the TOC for cloud PC role management, to make sure the CRUD operations are pointing to the appropriate, shared files, not the cloud PC-specific operation topics you had created in this PR.
Then you can delete those cloud PC-specific operation topics.

2021-05-24 08:10 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +              href: api/cloudpc-unifiedroledefinition-get.md
Updated.

2021-05-24 11:34 UTC, opbld32 commented
Docs Build status updates of commit _[e35f898](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e35f898f0261f4e82687adbf9030f418f8313d7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-c92dfd0e)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-c92dfd0e)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-c92dfd0e"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Role management navigation property' is duplicated in 'beta/resources/rbacapplication.md(3,14)', 'beta/resources/rbacapplicationmultiple.md(3,14)'.`````

<a id="f81f934e67f6ce3812d54d8f97883c6d-c92dfd0e"></a>
### [api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'roleManagement resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rolemanagement.md(2,8), beta/resources/rolemanagement.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'roleManagement resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rolemanagement.md(10,1), beta/resources/rolemanagement.md(10,1)'. First level hea [...]

2021-05-26 03:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/rolemanagement.md
> +|cloudPC|[rbacApplicationMultiple](rbacapplicationmultiple.md)| Read-only. Nullable. Cloud PC unified RBAC enable IT admins to interact with not only Cloud PC RBAC but all M365 RBACs including AAD wi
Line 40:
Should this description say something like "Provides access to role definitions and role assignments of a Cloud PC RBAC provider."

2 other things:

- Please do not use "M365". This is an internal only acronym. By not using the proper branding, we weaken the brand and customer recognition for Microsoft 365.
- Please put you

r description before "Read-only. Nullable."

2021-05-26 03:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/rolemanagement.md
> +|cloudPC|[rbacApplicationMultiple](rbacapplicationmultiple.md)| Read-only. Nullable. Cloud PC unified RBAC enable IT admins to interact with not only Cloud PC RBAC but all M365 RBACs including AAD wi
In the interest of time, I'm going to change the description to the one above. Please let me know if that's not appropriate.

2021-05-26 03:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/rolemanagement.md
> +
@abhijeetsinha , also in the interest of time (before my OOF-age), I added a similar description for the deviceManagement and directory nav properties:
"Provides access to role definitions and role assignments of an Intune RBAC provider. Read-only. Nullable."
"Provides access to role definitions and role assignments of a Azure AD RBAC provider. Read-only. Nullable."

Let me know if they are not appropriate, and please update the descriptions accordingly.

2021-05-26 03:30 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-get.md
>  One of the following permissions is required to call this API. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
Line 24:
I also updated the lead-in sentence (paragraph) for the permissions table, if you take note in rbacapplication-list-roledefinitions.md. 
FYI that change was actually led by the Identity team; they haven't rolled the change out to all the topics yet. Since this topic uses a special type of permissions table, I made this change manually too so that they can just bypass this topic when they eventually roll out the permissions section updates.

2021-05-26 03:34 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-get.md
> +GET /roleManagement/cloudPC/roleDefinitions/{ids}
Line 36:
Why is the placeholder {ids} and not {id}?

2021-05-26 03:35 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-get.md
> +GET /roleManagement/cloudPC/roleDefinitions/{ids}
FYI I am changing it to {id}. Please let me know if that shouldn't be the case, and make the update again.

2021-05-26 03:46 UTC, angelgolfer-ms commented on api-reference/beta/resources/unifiedroleassignmentmultiple.md
Line 20:
FYI I am rephrasing this to use a more consistent, active voice (second person imperative), than the current passive voice.

2021-05-26 03:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/unifiedroleassignmentmultiple.md
Line 40:
@abhijeetsinha , FYI I am going to move the description for roleDefinition to the "Relationships" table. According to the current beta CSDL, roleDefinition is a nav property. Also, the description in line 40 is a superset of the one  currently in line 52.
Please adjust the description if it's not correct (i.e., doesn't support $filter and startsWith).

2021-05-26 05:08 UTC, opbld34 commented
Docs Build status updates of commit _[931e534](https://github.com/microsoftgraph/microsoft-graph-docs/commits/931e534cb4c7d35cd7df0fd83068cc67913214c6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-ae632b95)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-ae632b95)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-ae632b95"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Role management navigation property' is duplicated in 'beta/resources/rbacapplication.md(3,14)', 'beta/resources/rbacapplicationmultiple.md(3,14)'.`````

<a id="f81f934e67f6ce3812d54d8f97883c6d-ae632b95"></a>
### [api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'roleManagement resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rolemanagement.md(2,8), beta/resources/rolemanagement.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'roleManagement resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rolemanagement.md(10,1), beta/resources/rolemanagement.md(10,1)'. First level hea [...]

2021-05-26 05:09 UTC, opbld30 commented
Docs Build status updates of commit _[33c8ca7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33c8ca7eedb13e96c94478f6c96b2587202d15b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-26cb075a)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-26cb075a)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-26cb075a"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Role management navigation property' is duplicated in 'beta/resources/rbacapplication.md(3,14)', 'beta/resources/rbacapplicationmultiple.md(3,14)'.`````

<a id="f81f934e67f6ce3812d54d8f97883c6d-26cb075a"></a>
### [api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'roleManagement resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rolemanagement.md(2,8), beta/resources/rolemanagement.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'roleManagement resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rolemanagement.md(10,1), beta/resources/rolemanagement.md(10,1)'. First level hea [...]

2021-05-26 08:19 UTC, angelgolfer-ms approved these changes
@AshleyYangSZ , thanks for incorporating the feedback from the last iteration.
FYI I made a few more updates. You can take a look at my comments and what I had changed. I don't have further requests for you for this PR.

@abhijeetsinha , please take a look at 3 comments I have for you. If anything is incorrect, please let Ashley and myself know.

2021-05-26 08:20 UTC, opbld31 commented
Docs Build status updates of commit _[68a9459](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68a9459d0b55bf5a6f4abce29a8353ab1b844fd1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-c4e5967e)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-c4e5967e)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-c4e5967e"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Role management navigation property' is duplicated in 'beta/resources/rbacapplication.md(3,14)', 'beta/resources/rbacapplicationmultiple.md(3,14)'.`````

<a id="f81f934e67f6ce3812d54d8f97883c6d-c4e5967e"></a>
### [api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'roleManagement resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rolemanagement.md(2,8), beta/resources/rolemanagement.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'roleManagement resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rolemanagement.md(10,1), beta/resources/rolemanagement.md(10,1)'. First level hea [...]

2021-05-26 08:30 UTC, AshleyYangSZ commented on api-reference/beta/api/unifiedroledefinition-get.md
> +GET /roleManagement/cloudPC/roleDefinitions/{ids}
You're correct, it should be id. It's typo.

2021-05-26 08:38 UTC, AshleyYangSZ commented on api-reference/beta/resources/rolemanagement.md
> +|cloudPC|[rbacApplicationMultiple](rbacapplicationmultiple.md)| Read-only. Nullable. Cloud PC unified RBAC enable IT admins to interact with not only Cloud PC RBAC but all M365 RBACs including AAD wi
Thank you so much, that's totally fine for us. And I like it.

2021-05-26 08:44 UTC, AshleyYangSZ commented on api-reference/beta/resources/unifiedroleassignmentmultiple.md
Got it. So we don't recommend to use passive voice, right?

2021-05-26 08:45 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangeType": "Addition",
You're right. "Change" is more suitable.

2021-05-26 17:48 UTC, abhijeetsinha commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +- directory (Azure AD)
@AshleyYangSZ , @angelgolfer-ms  - Add 'deviceManagement' as well. Intune is also supported in beta.

2021-05-26 17:54 UTC, abhijeetsinha commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +| Directory | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All, Directory.AccessAsUser.All | Not supported.| RoleManagement.Read.Director
@angelgolfer-ms - Add deviceManagement as well. 

| Device Management | DeviceManagementRBAC.Read.All, DeviceManagementRBAC.ReadWrite.All | Not supported. | DeviceManagementRBAC.Read.All, DeviceManagementRBAC.ReadWrite.All, |

2021-05-26 19:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/unifiedroledefinition.md
> +
Per @abhijeetsinha 's comment in rbacapplication-list-roledefinitions.md, Intune supports unifiedRoleDefinition too. So adding that (on their behalf) for completeness.

2021-05-26 19:49 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
> +### Example 1: Delete a unifiedRoleAssignmentMultiple in an Intune provider
@angelgolfer-ms , @AshleyYangSZ - "in **an** Intune provider" ---> "in Intune provider". We have one and only one Intune and CloudPC proivder. The same change may be needed at other places.

2021-05-26 19:54 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-get.md
> +- directory (Azure AD)
@angelgolfer-ms , @AshleyYangSZ - Add Intune here.

2021-05-26 19:55 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-get.md
> +| Directory | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All, Directory.AccessAsUser.All | Not supported.| RoleManagement.Read.Director
@angelgolfer-ms , @AshleyYangSZ - Add Intune's permissions here.

2021-05-26 19:56 UTC, abhijeetsinha commented on api-reference/beta/api/unifiedroledefinition-get.md
> +### Example4: Get the definition of a cloud PC built-in role
@angelgolfer-ms , @AshleyYangSZ - Keep the heading consistent with other examples.

2021-05-26 19:59 UTC, abhijeetsinha commented on api-reference/beta/resources/rolemanagement.md
>  For more information, see:
@angelgolfer-ms , @AshleyYangSZ - If there is a CloudPC documentation, you can hyperlink it here, along with Azure AD and Intune.

2021-05-26 20:03 UTC, abhijeetsinha commented on api-reference/beta/resources/rolemanagement.md
> +The following RBAC providers are currently supported:
@angelgolfer-ms , @AshleyYangSZ - This is a good article where we have explained the difference between different RBAC systems - https://docs.microsoft.com/en-us/azure/active-directory/roles/concept-understand-roles#how-azure-ad-roles-are-different-from-other-microsoft-365-roles

Do you think we should add it here?

2021-05-26 20:03 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-get.md
> +| Directory | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All, Directory.AccessAsUser.All | Not supported.| RoleManagement.Read.Director
Per @abhijeetsinha 's comment in rbacapplication-list-roledefinitions.md, Intune supports unifiedRoleDefinition too. So adding that (on their behalf) for completeness.

Will also do the same for the POST, PATCH and DELETE operations.

2021-05-26 20:04 UTC, abhijeetsinha commented on api-reference/beta/resources/rolemanagement.md
> +
@angelgolfer-ms - I think what you have is correct.

2021-05-26 20:08 UTC, abhijeetsinha commented on api-reference/beta/resources/unifiedroledefinition.md
> +
@angelgolfer-ms - yes. Intune supports unifiedRoleDefintion. There is difference only in role assignments.

2021-05-26 20:11 UTC, opbld30 commented
Docs Build status updates of commit _[15db432](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15db43294464ed0bdceb04b323cf918f0aa05819)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-83235cba)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-83235cba)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-83235cba"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Role management navigation property' is duplicated in 'beta/resources/rbacapplication.md(3,14)', 'beta/resources/rbacapplicationmultiple.md(3,14)'.`````

<a id="f81f934e67f6ce3812d54d8f97883c6d-83235cba"></a>
### [api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'roleManagement resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rolemanagement.md(2,8), beta/resources/rolemanagement.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'roleManagement resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rolemanagement.md(10,1), beta/resources/rolemanagement.md(10,1)'. First level hea [...]

2021-05-26 21:01 UTC, angelgolfer-ms commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +- directory (Azure AD)
Done.

2021-05-26 21:01 UTC, angelgolfer-ms commented on api-reference/beta/api/rbacapplication-list-roledefinitions.md
> +| Directory | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All, Directory.AccessAsUser.All | Not supported.| RoleManagement.Read.Director
Done.

2021-05-26 21:23 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroleassignmentmultiple-delete.md
> +### Example 1: Delete a unifiedRoleAssignmentMultiple in an Intune provider
I see what you mean in your comment, @abhijeetsinha .
FYI in this context, an article is needed grammatically. 
Should it be "the", or an indefinite article ("an", "a")?
I am using the latter in this context, because each organization would have their own RBAC provider(s). It's not like Microsoft establishes one Intune RBAC provider and all organizations access that one almighty Intune RBAC provider, right? 
And also, an organization can have an RBAC provider for Intune, another RBAC provider for directory, etc. Hence the indefinite article.

Please let me know if I misunderstood.

2021-05-26 21:34 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-get.md
> +- directory (Azure AD)
Did that. Will be committing soon.

2021-05-26 21:35 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-get.md
> +| Directory | RoleManagement.Read.Directory, Directory.Read.All, RoleManagement.ReadWrite.Directory, Directory.ReadWrite.All, Directory.AccessAsUser.All | Not supported.| RoleManagement.Read.Director
Did that. Will be committing soon.

2021-05-26 21:37 UTC, angelgolfer-ms commented on api-reference/beta/api/unifiedroledefinition-get.md
> +### Example4: Get the definition of a cloud PC built-in role
Fixed.

2021-05-26 22:18 UTC, angelgolfer-ms commented on api-reference/beta/resources/rolemanagement.md
> +The following RBAC providers are currently supported:
Yes. 
I also reorganized the content in lines 16-26. Will commit in a moment.

2021-05-26 22:20 UTC, angelgolfer-ms commented on api-reference/beta/resources/rolemanagement.md
>  For more information, see:
Question for @AshleyYangSZ , per the distributed doc model for Microsoft Graph (product teams author /maintain their content) :-)

2021-05-26 22:29 UTC, opbld34 commented
Docs Build status updates of commit _[5fde905](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5fde905599cd8ae6e62afefcd46419074a2aa120)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-1fb9cfe3)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-1fb9cfe3)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-1fb9cfe3"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branc [...]

2021-05-26 22:42 UTC, angelgolfer-ms commented
> @AshleyYangSZ , thanks for incorporating the feedback from the last iteration.
> FYI I made a few more updates. You can take a look at my comments and what I had changed. I don't have further requests for you for this PR.
> 
> @abhijeetsinha , please take a look at 3 comments I have for you. If anything is incorrect, please let Ashley and myself know.

@abhijeetsinha , thanks for the comments. Just so we can publish this PR with more complete messaging for role definitions, I added Intune to various sections in the CRUD operation topics of unifiedRoleDefinition, except for examples. 
For additional content needs for Intune, please contact @davidmu1 ; he can either help or further direct content requests for Intune.
As for an RBAC concept topic for cloud PC, please work with @AshleyYangSZ . 
I have approved and completed the content review for this PR in its current state. Let me know if you have comments for my updates today. :-)
If you need further assistance, please contact @Lauragra as I will be OOF. Thanks!

2021-05-27 02:26 UTC, AshleyYangSZ commented on api-reference/beta/resources/rolemanagement.md
>  For more information, see:
@abhijeetsinha @angelgolfer-ms We don't have individual RBAC doc, we just put CloudPC part in the directory doc.

2021-05-27 02:27 UTC, AshleyYangSZ commented on api-reference/beta/resources/rolemanagement.md
> +The following RBAC providers are currently supported:
Thanks @angelgolfer-ms !

2021-05-27 06:17 UTC, opbld33 commented
Docs Build status updates of commit _[61f531b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61f531bd053f5ce899b4330aee3566f368fe8493)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-16bba4b8)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-16bba4b8)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-16bba4b8"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type' is duplicated with other articles: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(10,1), beta/resources/rbacapplicationmultiple.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branc [...]

2021-05-28 01:08 UTC, opbld32 commented
Docs Build status updates of commit _[3d787e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d787e7c3951654ae79795e09d4aa32c4e773265)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-0e33f3d2)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-0e33f3d2)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/includes/cloudpc-api-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/includes/cloudpc-api-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-0e33f3d2"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type'  [...]

2021-05-28 01:18 UTC, opbld32 commented
Docs Build status updates of commit _[cef2639](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cef2639eb38e2d3edb76ba5d44d3245f6732bca5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-30aa2346)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-30aa2346)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/includes/cloudpc-api-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/includes/cloudpc-api-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-30aa2346"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type'  [...]

2021-05-30 13:11 UTC, opbld30 commented
Docs Build status updates of commit _[7aa5506](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7aa55068b60fdf0463f16ee43a63ecad7bd89ae2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-a116482a)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-a116482a)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/includes/cloudpc-api-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/includes/cloudpc-api-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-a116482a"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type'  [...]

2021-05-31 08:19 UTC, opbld32 commented
Docs Build status updates of commit _[1506f8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1506f8d9996b9559a3bfa12d3b83bd804d82511a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-64e5d5f7)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-64e5d5f7)
[api-reference/beta/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-list-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/rbacapplicationmultiple-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplicationmultiple-post-roleassignments?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroleassignmentmultiple-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-list.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/unifiedroleassignmentmultiple-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroleassignmentmultiple-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignmentmultiple-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroleassignmentmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroleassignmentmultiple.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentmultiple?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[api-reference/includes/cloudpc-api-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/includes/cloudpc-api-preview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&branch=pr-en-us-12237) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="a7ac7d293ea34d4691824a0886205d18-64e5d5f7"></a>
### [api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/RBACAPIs/api-reference/beta/resources/rbacapplicationmultiple.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'rbacApplicationMultiple resource type - Microsoft Graph beta' is duplicated in: 'beta/resources/intune-rbac-rbacapplicationmultiple.md(2,8), beta/resources/rbacapplicationmultiple.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'rbacApplicationMultiple resource type'  [...]

2021-05-31 08:26 UTC, merged