Initial device registration policy - Preview docs
microsoftgraph/microsoft-graph-docs pull request #12257
Opened 2021-04-10 00:47 UTC by spunukol

Ready for review

2021-04-10 00:48 UTC, opbld34 commented
Docs Build status updates of commit _[2d86013](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d860133d1d3dc48d0653655746a291b9a13f0c1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-8bc3d495)
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :warning:Warning | | [Details](#user-content-99755ddf2339201c2e30b32ac38f62cc-8bc3d495)
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :warning:Warning | | [Details](#user-content-a75616de53aa610212cc9164bfa48026-8bc3d495)

<a id="0817dce4456c16725d5333633847d38f-8bc3d495"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml)
 - **Line 10162, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="99755ddf2339201c2e30b32ac38f62cc-8bc3d495"></a>
### [api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md)
 - **Line 58, Column 234**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/devices/overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 59, Column 204**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/devices/overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="a75616de53aa610212cc9164bfa48026-8bc3d495"></a>
### [api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md)
 - **Line 27, Column 194**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/devices/overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 224**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/devices/overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104100047040794-12257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BPEIWr82Xnt2%2FG7gmE%2B1oN30%2B0NLLK65TFJAzNW4%2BuY%3D&st=2021-04-10T00%3A43%3A26Z&se=2021-05-11T00%3A48%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-10 01:04 UTC, opbld33 commented
Docs Build status updates of commit _[c0dba31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0dba312150c822bd0d63cc9afa71656c82dee9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104100103049346-12257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EOwmiwtaCVAMMZjoluOYtiQdAsC3VYL0CrSUc3%2BBXx4%3D&st=2021-04-10T00%3A59%3A22Z&se=2021-05-11T01%3A04%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 17:17 UTC, RavennMSFT commented on api-reference/beta/api/deviceregistrationpolicy-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
which params, can you give some examples

2021-04-12 17:19 UTC, RavennMSFT commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +|multiFactorAuthConfiguration|multiFactorAuthConfiguration|Specifies the authentication policy for a user to complete registration using Azure AD Join or Azure AD registered within your organization.
I dont think we specify unknownFutureValue in the docs

2021-04-12 17:19 UTC, RavennMSFT commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +|azureADRegistration|[azureADRegistrationPolicy](../resources/azureadregistrationpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD registered wi
This cant be modified by admins if Intune is enabled. Can we document that

2021-04-12 17:57 UTC, davidmu1 commented on api-reference/beta/api/deviceregistrationpolicy-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
This sentence needs to be changed to either list the parameters that are supported. If all parameters are supported, the words "some of" need to be removed.

2021-04-12 17:59 UTC, davidmu1 commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +|id|String|Read-only.|
Although it may seem descriptive just from the property name, we need to add a description sentence for the properties. Such as, "The identifier of the deviceRegistrationPolicy object."

2021-04-12 18:03 UTC, davidmu1 commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +|azureADRegistration|[azureADRegistrationPolicy](../resources/azureadregistrationpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD registered wi
```suggestion
|azureADRegistration|[azureADRegistrationPolicy](../resources/azureadregistrationpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD registered within your organization. Required. For more information, see [What is a device identity?](/azure/active-directory/devices/overview).|
```

2021-04-12 18:04 UTC, davidmu1 commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +|azureADJoin|[azureAdJoinPolicy](../resources/azureadjoinpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD Join within your organization. Requir
```suggestion
|azureADJoin|[azureAdJoinPolicy](../resources/azureadjoinpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD Join within your organization. Required. For more information, see [What is a device identity?](/azure/active-directory/devices/overview).|
```

2021-04-12 18:07 UTC, davidmu1 commented on api-reference/beta/resources/azureadjoinpolicy.md
> +description: "Properties and relationships of the azureADJoinPolicy resource"
```suggestion
description: "Represents the policy scope of an Active Directory tenant that controls device registration using Azure AD Join."
```

2021-04-12 18:08 UTC, davidmu1 commented on api-reference/beta/resources/azureadjoinpolicy.md
> +Represents the policy scope of the Azure Active Directory tenant that controls the ability for users and groups to register device identities to your organization using Azure AD Join. Only the read a
```suggestion
Represents the policy scope of the Azure Active Directory tenant that controls the ability for users and groups to register device identities to your organization using Azure AD Join.
```

2021-04-12 18:13 UTC, davidmu1 commented on api-reference/beta/resources/azureadjoinpolicy.md
> +
Should be a section titled Methods and in that section should be a table listing the Get and Update methods with links to the method pages. See other published resource pages for examples.

Method | Return Type | Description
-- | -- | --

2021-04-12 18:14 UTC, davidmu1 commented on api-reference/beta/resources/azureadjoinpolicy.md
> +## Special considerations when using `appliesTo`
This should not be a new section. The information should just be a continuation of the information in the properties section.

2021-04-12 18:17 UTC, davidmu1 commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +description: "Properties and relationships of the azureADRegistrationPolicy resource"
```suggestion
description: "Represents the policy scope of an Active Directory tenant that controls device registration using Azure AD registration."
```

2021-04-12 18:17 UTC, davidmu1 commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +Represents the policy scope of the Azure Active Directory tenant that controls the ability for users and groups to register device identities to your organization using Azure AD registered. Only the
```suggestion
Represents the policy scope of the Azure Active Directory tenant that controls the ability for users and groups to register device identities to your organization using Azure AD registered.
```

2021-04-12 18:18 UTC, davidmu1 commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +
Should be a section titled Methods and in that section should be a table listing the Get and Update methods with links to the method pages. See other published resource pages for examples.

Method | Return Type
-- | --

2021-04-12 18:19 UTC, davidmu1 commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +|allowedGroups|String collection|Group IDs in scope of policy. Required when used with the `selected` value in the `appliesTo` property.|
```suggestion
|allowedGroups|String collection| The group identifiers that are in the scope of the policy. Required when used with the `selected` value in the `appliesTo` property.|
```

2021-04-12 18:20 UTC, davidmu1 commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +|allowedUsers|String collection|User IDs in scope of policy. Required when used with the `selected` value in the `appliesTo` property.|
```suggestion
|allowedUsers|String collection| The user identifiers that are in the scope of the policy. Required when used with the `selected` value in the `appliesTo` property.|
```

2021-04-12 18:20 UTC, davidmu1 commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +|appliesTo|policyScope|Specifies whether to block, allow or fine-grained control of the policy scope. Possible values are: `none`, `all`, `selected`, `unknownFutureValue`. Required.|
```suggestion
|appliesTo|policyScope|Specifies whether to block or allow fine-grained control of the policy scope. Possible values are: `none`, `all`, `selected`, `unknownFutureValue`. Required.|
```

2021-04-12 18:21 UTC, davidmu1 commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +## Special considerations when using `appliesTo`
This should not be a new section. The information should just be a continuation of the information in the properties section.

2021-04-12 18:22 UTC, davidmu1 commented on api-reference/beta/resources/deviceregistrationpolicy.md
> +description: "Properties and relationships of the deviceRegistrationPolicy resource"
```suggestion
description: "Represents the policy scope of the Azure Active Directory tenant that control quota restrictions, additional authentication, and authorization policies."
```

2021-04-12 18:23 UTC, davidmu1 commented on api-reference/beta/resources/deviceregistrationpolicy.md
> +Represents the policy scope of the Azure Active Directory tenant that control quota restrictions, additional authentication and authorization policies to register device identities to your organizati
```suggestion
Represents the policy scope of the Azure Active Directory tenant that control quota restrictions, additional authentication, and authorization policies to register device identities to your organization.
```

2021-04-12 18:24 UTC, davidmu1 commented on api-reference/beta/resources/deviceregistrationpolicy.md
> +|[Get deviceRegistrationPolicy](../api/deviceregistrationpolicy-get.md)|[deviceRegistrationPolicy](../resources/deviceregistrationpolicy.md)|Read the properties and relationships of a [deviceRegistra
```suggestion
|[Get deviceRegistrationPolicy](../api/deviceregistrationpolicy-get.md)|[deviceRegistrationPolicy](../resources/deviceregistrationpolicy.md)|Read the properties of a [deviceRegistrationPolicy](../resources/deviceregistrationpolicy.md) object.|
```

2021-04-12 18:25 UTC, davidmu1 commented on api-reference/beta/resources/deviceregistrationpolicy.md
> +|azureADJoin|[azureAdJoinPolicy](../resources/azureadjoinpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD Join within your organization. [Learn
```suggestion
|azureADJoin|[azureAdJoinPolicy](../resources/azureadjoinpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD Join within your organization. For more information, see [What is a device identity?](/azure/active-directory/devices/overview).|
```

2021-04-12 18:26 UTC, davidmu1 commented on api-reference/beta/resources/deviceregistrationpolicy.md
> +|azureADRegistration|[azureADRegistrationPolicy](../resources/azureadregistrationpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD registered wi
```suggestion
|azureADRegistration|[azureADRegistrationPolicy](../resources/azureadregistrationpolicy.md)|Specifies the authorization policy for controlling registration of new devices using Azure AD registered within your organization. For more information, see [What is a device identity?](/azure/active-directory/devices/overview).|
```

2021-04-12 18:26 UTC, davidmu1 commented on api-reference/beta/resources/deviceregistrationpolicy.md
> +## Special considerations for using `multiFactorAuthConfiguration`
Should not be a new section.

2021-04-12 18:27 UTC, davidmu1 commented on api-reference/beta/resources/deviceregistrationpolicy.md
> +## Special considerations for using `userDeviceQuote`
Should not be a new section.

2021-06-18 20:57 UTC, MicrosoftGuyJFlo commented
#assign:MicrosoftGuyJFlo

2021-06-18 21:00 UTC, spunukol commented
#assign:@MicrosoftGuyJFlo  to complete PR while I am OOF

2021-06-18 22:41 UTC, opbld30 commented
Docs Build status updates of commit _[3e5101b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e5101b21e54767630f256a89033d5a7ae31ddc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106182238430634-12257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v3OUdbg%2B5KI01CF%2BjPbE0cza%2BcBzlLsEPMW0fLdjy2g%3D&st=2021-06-18T22%3A36%3A25Z&se=2021-07-19T22%3A41%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 16:10 UTC, spunukol commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +## Special considerations when using `appliesTo`
JoFlores has fixed up all of the PR while I was OOF. pls review

2021-07-01 11:43 UTC, FaithOmbongi requested changes
Requested a few changes.
- An observation: seems the API returns different values for **multiFactorAuthConfiguration** and **appliesTo** for both complex types. Returning 0,1,2 instead of the specified `none`, `all`, `required`. 
- Let's also add the ToC entry.

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +
This resource looks like a complex type. Methods only apply to the main entity type, **deviceRegistrationPolicy** resource.
```suggestion
```

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +|isAdminConfigurable|Boolean|Specifies whether this `policyScope` is configurable by the admin. Read-only.|
A few observations:
- appliesTo property returns 0,1 ... string values not `none`, `all`, `selected`.
  - Ideally, customers always expect the API to return the string name, not its int representation. Should changes be made to the schema before the docs are published?
- isAdminConfigurable property is updatable.
- None of the properties is required.

```suggestion
|allowedGroups|String collection| The identifiers of the groups that are in the scope of the policy. Required when the **appliesTo** property is set to `selected`. |
|allowedUsers|String collection| The identifiers of users that are in the scope of the policy. Required when the **appliesTo** property is set to `selected`. |
|appliesTo|policyScope| Specifies whether to block or allow fine-grained control of the policy scope. Possible values are: `none`, `all`, `selected`, `unknownFutureValue`. The default value is `0`. The default value is `0`. When set to `2`, at least one user or group identifier must be specified in either **allowedUsers** or **allowedGroups**.  Setting this property to `0` or `1` removes all identifiers in both **allowedUsers** and **allowedGroups**. |
|isAdminConfigurable|Boolean|Specifies whether this policy scope is configurable by the admin. The default value is `false`. |
```

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadjoinpolicy.md
> +description: "Represents the policy scope of an Active Directory tenant that controls device registration using Azure AD Join."
Kindly confirm: is the join type called Azure AD _Joined_ or Azure AD _Join_? [This article you linked to](https://docs.microsoft.com/en-us/azure/active-directory/devices/overview) seems to indicate **Azure AD joined**.

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadjoinpolicy.md
> +Represents the policy scope of the Azure Active Directory tenant that controls the ability for users and groups to register device identities to your organization using Azure AD Join.
Same comment as before: Azure AD _Joined_ or Azure AD _Join_

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadjoinpolicy.md
> +
No methods for complex type. These methods are for the **deviceRegistrationPolicy** entity.
```suggestion
```

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadjoinpolicy.md
> +|isAdminConfigurable|Boolean|Specifies whether this `policyScope` is configurable by the admin. Read-only.|
A few observations:
- appliesTo property returns 0,1 ... string values not `none`, `all`, `selected`.
  - Ideally, customers always expect the API to return the string name, not its int representation. Should changes be made to the schema before the docs are published?
- isAdminConfigurable property is updatable.
- None of the properties is required.

```suggestion
|allowedGroups|String collection|The identifiers of the groups that are in the scope of the policy. Required when the **appliesTo** property is set to `selected`. |
|allowedUsers|String collection|The identifiers of users that are in the scope of the policy. Required when the **appliesTo** property is set to `selected`.|
|appliesTo|policyScope|Specifies whether to block or allow fine-grained control of the policy scope. Possible values are: `none`, `all`, `selected`, `unknownFutureValue`. The default value is `0`. When set to `2`, at least one user or group identifier must be specified in either **allowedUsers** or **allowedGroups**.  Setting this property to `0` or `1` removes all identifiers in both **allowedUsers** and **allowedGroups**.|
|isAdminConfigurable|Boolean|Specifies whether this policy scope is configurable by the admin. The default value is `false`.|
```

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +* The values defaults to **`all`** when **`isAdminConfigurable`** is set to **`false`**. This is when an admin has enabled Intune(MEM) application to manage devices in Azure Active Directory.
- Deleting to merge this into the property descriptions.
- Observation: **isAdminConfiguration** & **appliesTo** are not strictly dependent as the last statement declared. I'm able to set to (false & 1 or false & 0) and (true & 1 or true & 0). Note: appliesTo returns 0, 1, 2, not `none`, `all`, `selected`.

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +|multiFactorAuthConfiguration|multiFactorAuthConfiguration|Specifies the authentication policy for a user to complete registration using Azure AD Join or Azure AD registered within your organization.
Kindly confirm. Neither property seemed required when I tested.
```suggestion
|userDeviceQuota|Int32|Specifies the maximum number of devices that a user can have within your organization before blocking new device registrations. |
|multiFactorAuthConfiguration|multiFactorAuthConfiguration|Specifies the authentication policy for a user to complete registration using Azure AD Join or Azure AD registered within your organization. Possible values are: `notRequired` or `required`. |
```

2021-07-01 11:43 UTC, FaithOmbongi commented on api-reference/beta/api/deviceregistrationpolicy-update.md
> +**Note:** The response object shown here might be shortened for readability.
```suggestion
>**Note:** The response object shown here might be shortened for readability.
```

2021-09-28 20:44 UTC, CelesteDG commented
Reactivated the PR per PM's email message. Waiting for build to finish and also following up on the changes-requested tag.

2021-09-28 20:44 UTC, opbld30 commented
Docs Build status updates of commit _[3e5101b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e5101b21e54767630f256a89033d5a7ae31ddc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109282042563247-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T20%3A44%3A32Z&sr=b&sp=r&sig=IZrAipI4s%2ButDX%2Bldcg2iJnteaedDF0QugPOrzMIq18%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 23:16 UTC, opbld33 commented
Docs Build status updates of commit _[90bc158](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90bc1586d8436865be277df1fb4ada096a697ab5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110012314223383-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T23%3A16%3A10Z&sr=b&sp=r&sig=Km5dFKNOWrq%2FF2JtZCIp0dvONAbS1%2BS5%2BL4%2FAdVWfi8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 23:18 UTC, opbld30 commented
Docs Build status updates of commit _[8c1ec3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c1ec3a2bbe343a7bd2bff36fcf1864c0d5da0c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110012315061896-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T23%3A18%3A16Z&sr=b&sp=r&sig=rISLIB3mRHXmar61s52xtpXEKL3lxmE8tUzATrPQLpw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 23:20 UTC, opbld30 commented
Docs Build status updates of commit _[f570aba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f570aba81bfa00e54faf45981771a70e009a2abd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110012316114773-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T23%3A20%3A06Z&sr=b&sp=r&sig=kGH8Dr7cOt87IqjkW5mof0ocSBIPk3tvBfnnEV4ixvw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 23:20 UTC, spunukol commented on api-reference/beta/resources/azureadjoinpolicy.md
> +description: "Represents the policy scope of an Active Directory tenant that controls device registration using Azure AD Join."
device identity nomenclature is Azure AD Join but he post the actual registration the device is stamped as Azure AD joined (that is on the object itself). This is good as it is in my opinion

2021-10-01 23:20 UTC, spunukol commented on api-reference/beta/resources/azureadjoinpolicy.md
> +Represents the policy scope of the Azure Active Directory tenant that controls the ability for users and groups to register device identities to your organization using Azure AD Join.
same comment as earlier for this one too

2021-10-01 23:21 UTC, spunukol commented on api-reference/beta/resources/azureadregistrationpolicy.md
> +* The values defaults to **`all`** when **`isAdminConfigurable`** is set to **`false`**. This is when an admin has enabled Intune(MEM) application to manage devices in Azure Active Directory.
thx

2021-10-01 23:25 UTC, spunukol commented on changelog/Microsoft.DeviceRegistrationPolicies.json
> +>>>>>>> 02b5165dc186231477649ba4cffdcbf32e206dfe
Done

2021-10-01 23:26 UTC, spunukol reviewed
Changes from Contributor as well as updated Changelog as recommended

2021-10-01 23:27 UTC, opbld32 commented
Docs Build status updates of commit _[7155f7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7155f7b6742204f6692c9dff3aacb4b009d587a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110012325405006-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T23%3A27%3A27Z&sr=b&sp=r&sig=2RMQwqCeJEScGM3EyJF7rxCeCJ98oJUi%2B%2BEM%2FJ9Guf4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 00:12 UTC, opbld34 commented
Docs Build status updates of commit _[4e56e25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e56e25e7b8154ed07867d676e8b2d86f28327c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110020010160615-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-02T00%3A12%3A13Z&sr=b&sp=r&sig=ZtKthP%2BBLEC2OVIc9wvqNhF1jsszSPOFhaKDxq%2FHxVw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-04 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[c812fb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c812fb002ed12dda223ac2504a26186245b27428)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110041850528355-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T18%3A53%3A14Z&sr=b&sp=r&sig=%2BXQGKTsrkVzuVUS%2F%2Fm3TRBlJ8cQ3bAg71bXqU%2BxarHs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-04 19:18 UTC, opbld30 commented
Docs Build status updates of commit _[4c5ebec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c5ebecc4b579e611c590ec6a1400fe43a0307a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110041917056691-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-04T19%3A18%3A49Z&sr=b&sp=r&sig=sRoLcjIx1hj5o3F%2BNzuuJR4vd64oP%2B0KNJWG%2BnS0pLo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-05 08:52 UTC, opbld33 commented
Docs Build status updates of commit _[7f87c6c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f87c6ccb320a0c7c5b82a7c25b46319e759515f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-923ecf71)
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-923ecf71"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml)
 - **Line 1583, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'ediscovery-settings-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110050850248800-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-05T08%3A52%3A13Z&sr=b&sp=r&sig=d%2FqsvarbMSdNHjmHWBVfXpwmNWFkt1wEfZ4DxxGjH6U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-05 09:18 UTC, opbld32 commented
Docs Build status updates of commit _[9fdaa23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fdaa23cc43a8f58754337553bc2e6f1ca6a02cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7f109745)
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-7f109745"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml)
 - **Line 1583, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'ediscovery-settings-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110050915538068-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-05T09%3A18%3A06Z&sr=b&sp=r&sig=dLD6C%2FpMacWucRGN9HqTdFqYOkXHrlY1G3ioL%2BWKjmU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-05 09:18 UTC, FaithOmbongi approved these changes
@spunukol @MicrosoftGuyJFlo , I hadn't seen the TOC entry yesterday. I've made some additional changes before approving:
- Documented the deviceRegistrationPolicy relationship in the policyRoot resource
- Moved the device registration policy API to the policies section in the TOC
- Added descriptions for the Enums

I see this API is not yet live in the public metadata. When the API goes live, kindly add the **ready to merge** label to this PR.

2021-10-05 16:05 UTC, spunukol commented
Ready to merge

2021-10-05 16:17 UTC, opbld34 commented
Docs Build status updates of commit _[7ca5410](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ca541002119985ec1ca0128951e404027945a90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-42623a66)
[api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/device-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/api/deviceregistrationpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/api/deviceregistrationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/deviceregistrationpolicy-update?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadjoinpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadjoinpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadjoinpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/azureadregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/azureadregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azureadregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/deviceregistrationpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/deviceregistrationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/deviceregistrationpolicy?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[api-reference/beta/resources/policyroot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/resources/policyroot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policyroot?view=graph-rest-beta&branch=pr-en-us-12257) (graph-rest-beta) |
[changelog/Microsoft.DeviceRegistrationPolicies.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/changelog/Microsoft.DeviceRegistrationPolicies.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-42623a66"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/spunukol-deviceRegistrationPolicy-initial/api-reference/beta/toc.yml)
 - **Line 1583, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'ediscovery-settings-update.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110051613458420-12257%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-05T16%3A17%3A07Z&sr=b&sp=r&sig=eXpbgOggMsXvl72fynMnCH6PYQToANcpTBb97O20AFY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-05 16:20 UTC, merged