Sent email with MIME content
microsoftgraph/microsoft-graph-docs pull request #12275
Opened 2021-04-12 21:28 UTC by isvargasmsft

Starting with draft

2021-04-12 21:30 UTC, opbld32 commented
Docs Build status updates of commit _[047c309](https://github.com/microsoftgraph/microsoft-graph-docs/commits/047c30969366f941fdbcc5674404df1d12b789de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-sent-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-sent-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-sent-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104122128285012-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1XUqQuY2usArL2bsSu8AQGV2JA2SL5KGrQERgOmgi7Q%3D&st=2021-04-12T21%3A25%3A00Z&se=2021-05-13T21%3A30%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 21:45 UTC, opbld33 commented
Docs Build status updates of commit _[3ef66bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ef66bf9cc567f9fe1fe5cadc2b90dc30075c959)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-6a8037b2)
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="a09d4c88442bd2a1124eb581485232a0-6a8037b2"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 33, Column 162**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-post-mastercategories?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 79**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/messagerule?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0#common-use-cases. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104122143456107-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pbmKXQTpsZw6Pd8W48OZuio%2BCWaLtO4yx%2FLDCbIntfg%3D&st=2021-04-12T21%3A40%3A05Z&se=2021-05-13T21%3A45%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor gui [...]

2021-04-14 03:04 UTC, opbld34 commented
Docs Build status updates of commit _[5160b25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5160b25090ce291bb5c84b9bd1a7ea16a9fe773c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-7c3e9a47)
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) | [Details](#user-content-e1b72782107adab1f6859ca483ee83f1-7c3e9a47)
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |

<a id="a09d4c88442bd2a1124eb581485232a0-7c3e9a47"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 33, Column 162**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-post-mastercategories?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 79**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/messagerule?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0#common-use-cases. Otherwise, remove the view parameter.`````

<a id="e1b72782107adab1f6859ca483ee83f1-7c3e9a47"></a>
### [concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md)
 - **Line 55, Column 1**: **[Suggestion-[table-syntax-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch [...]

2021-04-14 03:14 UTC, opbld33 commented
Docs Build status updates of commit _[5915764](https://github.com/microsoftgraph/microsoft-graph-docs/commits/591576481450dc9c053743317b59952f48a2b7f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-16275bd0)
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="a09d4c88442bd2a1124eb581485232a0-16275bd0"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 33, Column 162**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-post-mastercategories?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 79**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/messagerule?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0#common-use-cases. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104140312519259-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I3Cdir6pdfB0I5aK9RVXPGgYsUxdbRktKLEr2A12kfo%3D&st=2021-04-14T03%3A09%3A09Z&se=2021-05-15T03%3A14%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in t [...]

2021-04-14 15:39 UTC, opbld33 commented
Docs Build status updates of commit _[acc5e90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acc5e9050c888d35e5b19c7d88554fef8ad5d189)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-ba2e38ea)
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="a09d4c88442bd2a1124eb581485232a0-ba2e38ea"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 33, Column 162**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-post-mastercategories?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 79**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/messagerule?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0#common-use-cases. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141536475287-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y3KmHZSaWwoC08S77EF24UVNOQEKii6b%2BBzt6h2nI7w%3D&st=2021-04-14T15%3A34%3A17Z&se=2021-05-15T15%3A39%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in [...]

2021-04-14 20:18 UTC, opbld30 commented
Docs Build status updates of commit _[6bd1f29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bd1f29f848fc14441bac45d0e51a8baa4efc651)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) | [Details](#user-content-e1b72782107adab1f6859ca483ee83f1-e2c81a02)
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-e2c81a02)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |

<a id="e1b72782107adab1f6859ca483ee83f1-e2c81a02"></a>
### [concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md)
 - **Line 28, Column 19**: **[Warning-link-out-of-scope]** `````File '../api-reference/v1.0/resources/message.md' referenced by link '../api-reference/v1.0/resources/message.md' will not be built because it is not included in build scope.`````

<a id="a09d4c88442bd2a1124eb581485232a0-e2c81a02"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 33, Column 162**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-post-mastercategories?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 79**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/messagerule?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better no [...]

2021-04-14 20:29 UTC, opbld33 commented
Docs Build status updates of commit _[df5fc6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df5fc6eba44a30544f93d4ed1bb2adf638351d9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-8c886a34)
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) | [Details](#user-content-e1b72782107adab1f6859ca483ee83f1-8c886a34)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |

<a id="a09d4c88442bd2a1124eb581485232a0-8c886a34"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 33, Column 162**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-post-mastercategories?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 79**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/messagerule?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link t [...]

2021-04-14 20:44 UTC, opbld34 commented
Docs Build status updates of commit _[cdfaeff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cdfaeff4eac537393dd0c747dcf7f2af323d2c87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-0db6b9e1)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="a09d4c88442bd2a1124eb581485232a0-0db6b9e1"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 38, Column 79**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/messagerule?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0#common-use-cases. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104142042579067-12275%5Cworkflow_report.html?sv=2016- [...]

2021-04-14 21:09 UTC, opbld31 commented
Docs Build status updates of commit _[edb7211](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edb7211db529701b698de85dff187637d03ca7ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) | [Details](#user-content-a09d4c88442bd2a1124eb581485232a0-241f3530)
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="a09d4c88442bd2a1124eb581485232a0-241f3530"></a>
### [concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md)
 - **Line 46, Column 18**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/manage-focused-inbox?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 46, Column 101**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/message-get?view=graph-rest-beta#request-2. Otherwise, remove the view parameter.`````
 - **Line 48, Column 9**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mailtips?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 52, Column 146**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/insights?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 57, Column 207**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-post-messages?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 57, Column 282**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/user-sendmail?view=graph-rest-1.0#request-2. Otherwise, remove the view parameter.`````
 - **Line 68, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 69, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 86, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 86, Column 112**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/mail-api-overview?view=graph-rest-1.0#common-use-cases. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104142108065648-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SE4kaoAbpUzJ0abdg4dfF4tPog9ko4R9iHoq4bmymtE%3D&st=2021-04-14T21%3A04%3A24Z&se=2021-05-15T21%3A09%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.do [...]

2021-04-14 23:32 UTC, opbld34 commented
Docs Build status updates of commit _[d43ae29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d43ae294444130564b67c6d03006660d01517118)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104142330240638-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DswcMYAA9DumjOEobE8KUCRUsuJUJRQk49WNRdOWLFI%3D&st=2021-04-14T23%3A27%3A08Z&se=2021-05-15T23%3A32%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 17:33 UTC, jasonjoh requested changes

2021-04-15 17:33 UTC, jasonjoh commented on api-reference/beta/api/message-reply.md
> +|message <br/> mimeContent|[message](../resources/message.md) <br/> Edm.String | Any writeable properties to update in the reply message. <br/> Base64Binary-encoded MIME content of the message being
mimeContent should be it's own row in the table. Don't use <br/> here, instead add an additional line with cells broken up by pipes (`|`). I would add a note to the description of both message and mimeContent that only one should be present (if using message, don't use mimeContent, and vice-versa)

2021-04-15 17:33 UTC, jasonjoh commented on concepts/outlook-send-mime-message.md
> +| sendMail | `mimeContent` | `Edm.String` | Base64Binary-encoded MIME content of the message being sent | No |
All of these also need to be updated right? Each action has it's own topic.

2021-04-19 20:58 UTC, opbld33 commented
Docs Build status updates of commit _[01137e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01137e8b5a74523b99ad0135a52a1678f96db079)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104192056553819-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qAbCvPifPs17%2FzfAi%2F0iRYQPNzMFhbRx4RL3%2BrNXDU8%3D&st=2021-04-19T20%3A53%3A05Z&se=2021-05-20T20%3A58%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 03:12 UTC, opbld30 commented
Docs Build status updates of commit _[ab3784f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab3784f660b97674e4fe40f54984e1cbebe750ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) | [Details](#user-content-e1b72782107adab1f6859ca483ee83f1-de97916d)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |

<a id="e1b72782107adab1f6859ca483ee83f1-de97916d"></a>
### [concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md)
 - **Line 45, Column 28**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-referece/api/user-post-messages'.`````
 - **Line 46, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-update'.`````
 - **Line 47, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-send'.`````
 - **Line 48, Column 24**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-reply'.`````
 - **Line 49, Column 44**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-createreply'.`````
 - **Line 50, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-replyall'.`````
 - **Line 51, Column 47**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-createreplyall'.`````
 - **Line 52, Column 23**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-forward'.`````
 - **Line 53, Column 46**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-createforward'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104200310547169-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2XHvGAHhVKJES3jFYLOf6mBEI3Is%2Bar0axR%2FyFN%2FAxo%3D&st=2021-04-20T03%3A07%3A16Z&se=2021-05-21T03%3A12%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 03:17 UTC, opbld34 commented
Docs Build status updates of commit _[60faa77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60faa778db9557a45ca3d75c7cfa0acb4cb357e8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) | [Details](#user-content-e1b72782107adab1f6859ca483ee83f1-72ad2d98)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |

<a id="e1b72782107adab1f6859ca483ee83f1-72ad2d98"></a>
### [concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md)
 - **Line 45, Column 28**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/user-post-messages'.`````
 - **Line 46, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-update'.`````
 - **Line 47, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-send'.`````
 - **Line 48, Column 24**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-reply'.`````
 - **Line 49, Column 44**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-createreply'.`````
 - **Line 50, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-replyall'.`````
 - **Line 51, Column 47**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-createreplyall'.`````
 - **Line 52, Column 23**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-forward'.`````
 - **Line 53, Column 46**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-createforward'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104200316057248-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2DHvJK2aHsEOu491TgecKKSHY6nRqIFkLflXQuI42fk%3D&st=2021-04-20T03%3A12%3A14Z&se=2021-05-21T03%3A17%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:40 UTC, opbld30 commented
Docs Build status updates of commit _[93e8a6c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93e8a6c2a2d16c7c100fcba2f78b51250ec48eac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) | [Details](#user-content-e1b72782107adab1f6859ca483ee83f1-66034870)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |

<a id="e1b72782107adab1f6859ca483ee83f1-66034870"></a>
### [concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md)
 - **Line 45, Column 28**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/user-post-messages.md'.`````
 - **Line 46, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-update.md'.`````
 - **Line 47, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-send.md'.`````
 - **Line 48, Column 24**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-reply.md'.`````
 - **Line 49, Column 44**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-createreply.md'.`````
 - **Line 50, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/message-replyall.md'.`````
 - **Line 51, Column 47**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-createreplyall.md'.`````
 - **Line 52, Column 23**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-forward.md'.`````
 - **Line 53, Column 46**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api-reference/api/message-createforward.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201838591349-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4L2Llf2TCYiH%2FWCEk77siR6jLN3Ksjl4Jyf6wfnriCs%3D&st=2021-04-20T18%3A35%3A06Z&se=2021-05-21T18%3A40%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:47 UTC, opbld33 commented
Docs Build status updates of commit _[2e852ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e852abba84cce640bf12dae05628260d4fac20c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201845552830-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MgDwoD6H2D%2BEo%2FVufvJaW4U3T0RUQpNh9138vDG%2FRWw%3D&st=2021-04-20T18%3A42%3A06Z&se=2021-05-21T18%3A47%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 20:45 UTC, opbld34 commented
Docs Build status updates of commit _[dd91660](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd91660b1d5178dc07846876794fc643bf9c08ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104202044093622-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lPiSiMQNtYU5IOt%2F0xMImKdUzyNKciv9bnHOA6Hasq8%3D&st=2021-04-20T20%3A40%3A19Z&se=2021-05-21T20%3A45%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 22:05 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +| Name       | Type | Description| Required |
Lines 43-46:
FYI in general for API reference topics, there are fixed templates defining H2 section titles, and corresponding table column titles. We can't add a column without affecting generator tool and API Doctor.

2021-04-20 22:26 UTC, opbld33 commented
Docs Build status updates of commit _[13889d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13889d11585986daa6be9e2d7b6ca01f2b2896db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) | [Details](#user-content-e7337f70602c3161b35f5cfe55f69586-13f9d25b)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="e7337f70602c3161b35f5cfe55f69586-13f9d25b"></a>
### [api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create Message - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-messages.md(2,8), v1.0/api/user-post-messages.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create Message' is duplicated with other ar [...]

2021-04-20 22:32 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
>  POST /users/{id | userPrincipalName}/mailFolders/{id}/messages/{id}/createForward
This comment is for the description section for the method, lines 16-23. (Please also apply this feedback to other method topics in this PR.)
In general, it's a good idea to clearly state in the top description what the method supports. That sentence in line 16 as is only addresses the original approach of specifying a body in JSON, which supports including a comment. That doesn't apply to the MIME body approach.
Suggestion:
"Create a draft message (add link to message.md file on first reference) for forwarding the specified message. You can specify the draft message body in JSON or MIME format.

When specifying the body in JSON format, you can include a comment, specify recipients, and update any message properties all in one **createForward** call. You can then [send](../api/message-send.md) the draft message.

**Note**
- You can specify either a comment or the **body** property of the `message` parameter. Specifying both will return an HTTP 400 Bad Request error.
- You must specify either the `toRecipients` parameter or the **toRecipients** property of the `message` parameter. Specifying both or specifying neither will return an HTTP 400 Bad Request error.

When specifying the body in MIME format, include only the MIME content in the request body. You must specify the recipients, and any updates to **message** properties in a subsequent [send](../api/message-send.md) operation to forward the draft message."

2021-04-20 22:34 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +To send a json object provide the following parameters:
Line 49:
Please clarify this way:
When sending the draft body in JSON format, specify the following parameters.

Please note the appropriate upper-case for "JSON", and the lead-in sentence to a table always ends in a period, not a colon, per Microsoft Writing Style.
Specify the following parameters when

2021-04-20 22:36 UTC, isvargasmsft commented on api-reference/beta/api/message-createforward.md
> +| Name       | Type | Description| Required |
@angelgolfer-ms should removing the additional column be enough? I can move the Required piece to the second column and remove that one.

2021-04-20 22:40 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +
Please don't note this as "important", but instead present the MIME approach as just a peer alternative to the JSON approach.
Also, we want to draw a parallel to how we list the differences between the two approaches in the preceding section, to aid scanning.
So I suggest continuing to start with the phrase "When specifying a MIME body format,..."
Something to the effect of:
"When specifying a MIME body format, include only the MIME content in the request body."

2021-04-20 22:43 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +### Example 1: Create a draft forward message
Line 66:
We need to better clarify what this example does, for example:
"Example 1: Create a draft message in JSON format for forwarding the specified message"

BTW, the original wording "draft forward message" has 3 nouns in a row, that's generally to avoid to reduce confusion for loc. I have tried to break up the noun phrase to make it less ambiguous.

2021-04-20 22:44 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +
Line 155:
For the same as reason as for line 66: Please break up the 3-noun phrase "draft forward message".

2021-04-20 22:49 UTC, angelgolfer-ms requested changes
Hi @isvargasmsft , thank you for the quick turnaround!
Even though this is supposed to be in tech review stage and content review comes only when tech review feedback is incorporated, I wanted to give some general comments so that you can apply them to the topics currently in this PR and the ones you work on for v1.
Basically, please view each method topic more holistically, make sure at the start, it's clear that there are two approaches supported, and every subsequent section clearly states what the customer should do for each approach.

2021-04-20 23:02 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +| Name       | Type | Description| Required |
Yes please.

2021-04-21 01:21 UTC, opbld33 commented
Docs Build status updates of commit _[6a67893](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a67893b1274ea571fc6bfd877eb5d919b70af69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) | [Details](#user-content-643fada326124091419e63fbba69e52a-b92d31ea)
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) | [Details](#user-content-4eeee77bbc9b4bdf46ae6ca693109366-b92d31ea)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="643fada326124091419e63f [...]

2021-04-22 20:35 UTC, opbld34 commented
Docs Build status updates of commit _[25de563](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25de563ed63e766eb362b3d47027ed5fc00eea6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) | [Details](#user-content-298103b5e4b06704ec34e9e939ac2ed0-99a7e5b4)
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) | [Details](#user-content-4eeee77bbc9b4bdf46ae6ca693109366-99a7e5b4)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

<a id="298103b5e4b06704ec34e9e [...]

2021-04-22 20:40 UTC, opbld32 commented
Docs Build status updates of commit _[a828edf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a828edf0a2065719a50739649c9290f1fd13da62)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-22 21:00 UTC, opbld32 commented
Docs Build status updates of commit _[8b5890e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b5890e91b8cc9054f4331fa17185738c3806430)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C22%5C77e68b91-cf [...]

2021-04-22 22:44 UTC, opbld32 commented
Docs Build status updates of commit _[c081d01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c081d014441cf188b35032a19728a8dea90a87f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C22%5C77e68b91-cf [...]

2021-04-22 22:53 UTC, opbld34 commented
Docs Build status updates of commit _[eb69eec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb69eece0661753d35df4abc2785b937f059734c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C22%5C77e68b91-cf [...]

2021-04-23 15:39 UTC, opbld34 commented
Docs Build status updates of commit _[901b8b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/901b8b842a4c3b2986e306ba91e86b9c82b96523)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf [...]

2021-04-23 17:32 UTC, opbld33 commented
Docs Build status updates of commit _[eee8625](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eee8625bdab5ece2e478b3739fb48def40d424a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf [...]

2021-04-23 17:57 UTC, opbld32 commented
Docs Build status updates of commit _[1dfd119](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1dfd11953ecfbcf82ca85eceb5fa3c72a65d8bef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf [...]

2021-04-23 18:06 UTC, opbld30 commented
Docs Build status updates of commit _[3c6116a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c6116ada0d81b718387dc0574e1065befbdcdad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf [...]

2021-04-23 18:23 UTC, opbld34 commented
Docs Build status updates of commit _[d73234e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d73234e72cabb932cea3fc8e618355a97d34733c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf [...]

2021-04-23 19:45 UTC, opbld34 commented
Docs Build status updates of commit _[9523476](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9523476574b93ab63a87362029cc67d1e3f5b8cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf [...]

2021-04-23 20:41 UTC, opbld33 commented
Docs Build status updates of commit _[678218e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/678218eeb02685c3cb025343cf13e24dd9de7de1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) | [Details](#user-content-e1b72782107adab1f6859ca483ee83f1-4cdbe6b4)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |

<a id="e1b72782107adab1f6859ca483ee83f1-4cdbe6b4"></a>
### [concepts/outlook-send-mime-messag [...]

2021-04-23 21:27 UTC, opbld34 commented
Docs Build status updates of commit _[d2ab8c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2ab8c8b186f539a3500316f12cab8ec4393a6a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-mail-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-mail-concept-overview?branch=pr-en-us-12275) |
[concepts/outlook-send-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/concepts/outlook-send-mime-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-send-mime-message?branch=pr-en-us-12275) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf [...]

2021-04-26 22:26 UTC, msft-karlcoelho requested changes

2021-04-26 22:26 UTC, msft-karlcoelho commented on api-reference/beta/api/message-createreply.md
> +POST https://graph.microsoft.com/beta/me/messages/AAMkADA1MTAAAH5JaLAAA=/createreply
Let's keep the camel case consistency. This could be `createReply` like the JSON example.

2021-04-26 22:26 UTC, msft-karlcoelho commented on api-reference/beta/api/message-createreplyall.md
> +POST https://graph.microsoft.com/beta/me/messages/AAMkADA1MTAAAH5JaLAAA=/createreplyall
Same for `createReply`. Consistency on camel casing

2021-04-26 22:26 UTC, msft-karlcoelho commented on api-reference/beta/api/message-send.md
> +POST https://graph.microsoft.com/v1.0/me/sendMail
`sendMail` is different from `/send` the implementation doesn't make any changes to this endpoint. We can leave it alone.

2021-04-27 16:38 UTC, isvargasmsft commented on api-reference/beta/api/message-send.md
> +POST https://graph.microsoft.com/v1.0/me/sendMail
Done!

2021-04-27 16:43 UTC, isvargasmsft commented on api-reference/beta/api/message-createreply.md
> +POST https://graph.microsoft.com/beta/me/messages/AAMkADA1MTAAAH5JaLAAA=/createreply
Done

2021-04-27 16:43 UTC, isvargasmsft commented on api-reference/beta/api/message-createreplyall.md
> +POST https://graph.microsoft.com/beta/me/messages/AAMkADA1MTAAAH5JaLAAA=/createreplyall
Done

2021-04-27 16:45 UTC, opbld34 commented
Docs Build status updates of commit _[d8b8986](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8b898661b8eb43f795cb2243e63a81b4d7ab14d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-04-27 19:51 UTC, opbld30 commented
Docs Build status updates of commit _[68d845a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68d845a7bb2252d7a68905dd51be69953a940692)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-04-28 02:14 UTC, opbld31 commented
Docs Build status updates of commit _[9391bcc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9391bccce326e01029d2ba22201e9ca1de074850)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-04-28 20:14 UTC, msft-karlcoelho requested changes

2021-04-28 20:14 UTC, msft-karlcoelho commented on api-reference/v1.0/api/message-createreply.md
> +This method does not require a request body. However, for creating a reply draft with MIME content, the MIME string should be provided in the body of the request. No parameters are required, just pas
Should mention that the MIME string needs to be Base64-encoded. Not just the MIME plaintext.

2021-04-28 20:14 UTC, msft-karlcoelho commented on api-reference/v1.0/api/message-createreplyall.md
> +When specifying the body in MIME format, include only the MIME content in the request body.
Again, should we be explicit about the MIME string being in Base64 encoding?

2021-04-28 20:14 UTC, msft-karlcoelho commented on api-reference/v1.0/api/message-createreplyall.md
> +This method does not require a request body. However, for creating a replyAll draft with MIME content, the content should be provided in the body of the request. No parameters are required, just past
Similar comment, should be explicit about Base64-encoding the MIME string.

2021-04-29 02:14 UTC, opbld32 commented
Docs Build status updates of commit _[8fd4676](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fd467652573c2e700b04a0c9f9656fb3ba89bd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) | [Details](#user-content-643fada326124091419e63fbba69e52a-4191559e)
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) | [Details](#user-content-16c1e95f2ada410291518206479ddc4e-4191559e)
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) | [Details](#user-content-4eeee77bbc9b4bdf46ae6ca693109366-4191559e)
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) | [Details](#user-content-e7337f70602c3161b35f5cfe55f69586-4191559e)
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://re [...]

2021-04-29 02:14 UTC, isvargasmsft commented on api-reference/v1.0/api/message-createreply.md
> +This method does not require a request body. However, for creating a reply draft with MIME content, the MIME string should be provided in the body of the request. No parameters are required, just pas
Solved

2021-04-29 02:21 UTC, opbld32 commented
Docs Build status updates of commit _[d0b9464](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0b946428afc5648ff1870c6f48edaf973072e36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-04-29 20:24 UTC, opbld30 commented
Docs Build status updates of commit _[7587475](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75874755818eb71971638a953ae61ca705612a28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-04-29 21:09 UTC, opbld30 commented
Docs Build status updates of commit _[fd78fe8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd78fe8ac13bc8a487b61d1b40d2fc894f0e900d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-04-29 21:44 UTC, msft-karlcoelho approved these changes
👍

2021-04-30 14:10 UTC, isvargasmsft commented on api-reference/beta/api/message-createforward.md
> +- S/MIME properties must be previously included in the base64-encoded string.
Fixed.

2021-04-30 14:10 UTC, isvargasmsft commented on api-reference/beta/api/message-createreplyall.md
> +- Microsoft Graph does not suppport editing MIME properties individually, the complete MIME content must be provided in a base64-encoded string.
Thank you. Solved.

2021-04-30 14:11 UTC, opbld31 commented
Docs Build status updates of commit _[8e6bbeb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e6bbeb77cad3f6b8755fcb421c73c2ae80ed634)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-03 16:09 UTC, jasonjoh approved these changes

2021-05-04 06:04 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +- S/MIME properties can be included in the base64-encoded string.
The section for MIME:
In my earlier [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/12275#discussion_r617074997), I suggested the following sentence:
"When specifying the body in MIME format, include only the MIME content in the request body. You must specify the recipients, and any updates to message properties in a subsequent send operation to forward the draft message."

While lines 26 and 27 sort of addressed the MIME content in the request body, there is the second phrase about specifying the recipients, that you should contrast with the JSON case. Otherwise that's a hole in the new scenario.

2021-05-04 06:15 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +- S/MIME properties can be included in the base64-encoded string.
Lines 26 and 27:
The next comment is about parallel sentence structure. You can see examples [here](https://writing-center.phsc.edu/grammar/sentence-structure/problems-sentences/parallelism) or search for "parallel writing" on the Internet.
The group of sentences for the JSON format and for the MIME format should use a parallel grammatical sentence structure, i.e., tell customers what they should do for each case.
But instead, line 26 starts with "Microsoft Graph" as the subject and uses active voice, followed by a phrase in passive voice (second person implied).
And then line 27 is a sentence in passive voice.

2021-05-04 06:40 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +- S/MIME properties can be included in the base64-encoded string.
So just to illustrate my point, I will provide an example of how to address my last two comments, for the section starting with line 25 (MIME case):

"When using MIME format:
- You must specify the complete MIME content in the request body as a base64-encoded string. 
- You may include S/MIME properties as part of the base64-encoded string. Microsoft Graph does not support editing these properties individually.
- You must specify the recipients, and any updates to message properties in a subsequent send operation to forward the draft message.

2021-05-04 06:47 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
Line 50:
The preceding part of your topic describes the JSON case first, then the MIME case.
So please reverse the order of the two in the phrase you added.
Also, because there is normal text mixed with "text/plain" and "application/json" in the same table cell content, you should style the two by enclosing them in tick marks, like `text/plain` and `application/json`.
In general, any programmatic strings that are not part of the Graph API should be styled this way, especially when the strings are embedded with normal text. This would promote customer reading/scanning.

2021-05-04 07:12 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +
The next comment applies to the "Request body" section:
Please apply parallel writing again to line 53 (the JSON case) and line 61 (MIME case).
I suggested that in a previous [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/12275#discussion_r617075645). If you prefer a shorter version, you can start line 53 like this:
"When specifying a draft message in JSON format, include the following parameters."

Then in line 61, you can do this please:
"When specifying a draft message in MIME format, include only the MIME content as **a base64-encoded string** in the request body. Do not include any parameters."
Please note the lower case 'b' for Base64.

FYI there are 2 issues with line 61. First, as is, that line is a run-on sentence. There are two ideas ("no parameters are required" and "include only the MIME content..."), you don't connect them with just a comma. Second, remember, use second person singular or imperative as much as you can. But here, again, you introduced passive voice and broke the parallelism.

2021-05-04 07:14 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +    "id": "AAMkAGNhOWVmNmEyLTgwNjItNDI0NC05ZGI5LWZhYjc4MzcxZWE3YQBGAAAAAADW_NNy5NNRT51Qs4RFfm_PBwDt09JRVj4bRqYt7q6MVBpAAAAAAAEPAADt09JRVj4bRqYt7q6MVBpAAAAiTjnQAAA=",
Line 188:
You forgot to match this id value with the truncated id segment you introduced in the example request in line 167.

In general, whenever you truncate an ID property value, you can do a search and replace to make sure you truncate the same value consistently.

2021-05-04 07:22 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +                "address": "MeganB@M365x765140.OnMicrosoft.com"
Line 229:
Please replace the actual tenant domain by something like "contoso". It's important that as authors and content reviewers, we make sure our docs use only CELA-approved data and do not inadvertently expose real data.
Please look up the related CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103160/Fictitious-names

2021-05-04 07:26 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +If the MIME content in the request body is malformed, this method returns the following error message.
Line 244:
Include this line for API Doctor:
```
<!-- { "blockType": "ignored" } -->
```

2021-05-04 07:32 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +HTTP/1.1 400 Bad Request
Also, I thought we had talked about this - please add this error case to the "Response" section.
This being the very last section in an API topic, and without any H2 section such that it wouldn't appear in the right-side TOC, customers will miss this info.

You can add this as a separate paragraph in the "Response" section:

If successful, this method returns `201 Created` response code and [message](../resources/message.md) object in the response body.
If the request body includes malformed MIME content, this method returns `400 Bad request` and the following error message: 
```
Invalid base64 string for MIME content.
```

2021-05-04 07:38 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +Alternatively, [forward a message](../api/message-forward.md) in a single operation.
Line 18:
I'd suggest moving this line all the way as the last sentence in this section, before line 29, the next H2 section "Permissions".
The reason is lines 20-27 still apply to the createForward method, so it's better to keep them together.
Besides, some customers may get confused and mistake line 20 applies to the method mentioned in the preceding line, line 18.

2021-05-04 07:47 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createreplyall.md
> +- Subsequently [update](../api/message-update.md) the draft message.
Line 22:
Is that true?
Per line 21, the customer can already set property values of the draft message in the request body. Why would we suggest the customer to do a separate PATCH operation to that draft message?

2021-05-04 07:54 UTC, angelgolfer-ms requested changes
@isvargasmsft , thanks for incorporating the last set of feedback for the message-createforward.md topic.
I have reviewed the same beta version of the topic and added a few more comments. A few of the comments relate to writing parallel sentences, a basic writing technique.
Please take a look and apply the comments to the other topics as well. I eyeballed a couple more topics and noticed they all follow a similar pattern.
I'll take a look at the rest of the topics in a day or so.

2021-05-05 15:44 UTC, isvargasmsft commented on api-reference/beta/api/message-createforward.md
Fixed!

2021-05-05 20:12 UTC, opbld32 commented
Docs Build status updates of commit _[d1a0c59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1a0c59d26a21e712bd0310d2f592c88e7a3d75f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-05 21:46 UTC, opbld33 commented
Docs Build status updates of commit _[567d9c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/567d9c04f5e1d92371271a58ba3e0c6a88706357)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7597c2c0)

<a id="7597c2c0"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105052145322894-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G%2BQIlIocjL%2FeszsxtO4yYRbxcczpUZm1bcJ7Z6tpFZA%3D&st=2021-05-05T21%3A41%3A03Z&se=2021-06-05T21%3A46%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 21:58 UTC, opbld32 commented
Docs Build status updates of commit _[462501e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/462501e82aedeacacb1f81787b0ca87071d6e3b4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-89348bfe)

<a id="89348bfe"></a>
###
 - **[Error-CannotMergeCommit]** `````Cannot merge commit 462501e82aedeacacb1f81787b0ca87071d6e3b4 in branch isvargasmsft-mail-mime of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit e9b2ff28a89990fefac7516257d978fa257e40e9). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105052158326677-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SmU71WR0%2F860SxJjjEdOJL6lZ%2B14roYFe0hGmxi%2Bb4o%3D&st=2021-05-05T21%3A53%3A40Z&se=2021-06-05T21%3A58%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 22:07 UTC, opbld34 commented
Docs Build status updates of commit _[f2626d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2626d2599d359ea21f24de28d91215c9138b613)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ae8112c7)

<a id="ae8112c7"></a>
###
 - **[Error-CannotMergeCommit]** `````Cannot merge commit f2626d2599d359ea21f24de28d91215c9138b613 in branch isvargasmsft-mail-mime of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit e9b2ff28a89990fefac7516257d978fa257e40e9). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105052207049794-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wPoX3ChObu7iioRf4QOayJXss9jt8BeZyOj2sdjO2mI%3D&st=2021-05-05T22%3A02%3A12Z&se=2021-06-05T22%3A07%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 22:13 UTC, opbld30 commented
Docs Build status updates of commit _[280e94d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/280e94dac931ea345f84b552731168f095ba6e3c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-75ef9bdc)

<a id="75ef9bdc"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105052212509980-12275%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d30v%2FYuq1%2FW1DHyk8Z4IOwnWsTOAw5q6CJU%2F%2BsGLj%2F4%3D&st=2021-05-05T22%3A08%3A08Z&se=2021-06-05T22%3A13%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 22:20 UTC, opbld33 commented
Docs Build status updates of commit _[3f94072](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f94072ebbd7b747539f2c08e011fe6b57c475e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-05 22:34 UTC, opbld32 commented
Docs Build status updates of commit _[9317e8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9317e8e7c70f7a19987a76c5b394e65cf872d2d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-06 00:39 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createreplyall.md
> +- Include a comment or update any message properties, all in one **createReplyAll** call.
Line 19:
@isvargasmsft , I took a closer look at the current state of this bullet list, just want to make sure we got on the same page with this first bullet item. As is:
"Include a comment or update any message properties, all in one **createReplyAll** call."
this sentence is in imperative voice, implying the customer should do this.
That would be ambiguous with the next bullet point in line 20, which says the customer can choose to EITHER specify a comment, OR, not specify the comment parameter and specify the body property of the message parameter.

Somehow we still need to convey that line 19 is not imperative, and is something the customer can choose to do.

2021-05-06 00:46 UTC, angelgolfer-ms commented on api-reference/v1.0/api/message-createreplyall.md
> +Create a draft to reply to the sender and all the recipients of the specified [message](../resources/message.md) in either JSON or MIME format.
@isvargasmsft , can you please confirm, is it true that the v1 and beta version of createReplyAll do not use the same syntax? That is, the v1 version doesn't take any parameters (and hence we explicitly state in the original line 14 that the customer needs to do a PATCH operation to specify the reply content to the body and so forth)?
Whereas the beta version takes the comment and message parameters?

2021-05-06 01:00 UTC, angelgolfer-ms commented on api-reference/v1.0/api/message-createreplyall.md
> +- Optionally, [update](../api/message-update.md) the draft later to add reply content to the **body** or change other message properties.
Line 17:
If you confirm my last comment as positive - that this method doesn't take any comment or message parameter as in the beta version - then I'd suggest in line 17, we don't specify "Optionally", even though technically our API may not require it. The typical reply-all use case is there's got to be a message body, otherwise why do a reply-all?

Also, since this is just a single bullet point (as opposed to a few bullet points in some other method topics), we shouldn't have a bullet list (per our writing style guide). Perhaps in this case, we don't separate the steps subsequent to calling createReplyAll into line 17, then skip lines 19-21, and resume in line 23?

Instead, for line 16-17, we can just say:
"When specifying the JSON format, you can then update the draft to add reply content to the body or change other message properties, or, simply send the draft."

I think that's clearer than saying "optionally", because in that context, it's not clear what that thing is an option for, as opposed to what.

(Then of course make line 23 a bullet point for the MIME format case.)

2021-05-06 21:40 UTC, angelgolfer-ms commented on concepts/outlook-send-mime-message.md
> +- Send emails in MIME format: message body contents, attachments and sender/recipient information (CC and BCC).
Line 15:
Hm, you refer to "attachments".
The attachment feature is not a simple story. There are 3 vectors to consider:
(a) the types of attachments (file attachment, reference attachment, and Outlook item attachment which in turn can be a contact, event, or message). 
(b) What can you attach to - you can add an attachment to an event, message, or group post.
(c) How do you add the attachment - in general, you can attach to an existing Outlook item, attach to a draft of a message, or add the attachment when creating and sending a message (sendMail method).

So you need to be precise about this - is the supported scenario about attaching a message represented in MIME format, to a draft message? How about attaching to an event or group post? We need to make that clear.

If indeed we support attaching messages, events, or contacts in MIME format to a draft message, then we also need a separate section to illustrate that in the concept topic.

2021-05-06 21:44 UTC, angelgolfer-ms commented on concepts/outlook-send-mime-message.md
> +- Send emails in MIME format: message body contents, attachments and sender/recipient information (CC and BCC).
Also line 15:
What is the MIME support about "sender/recipient information (CC and BCC)"?
Are we referring to the "cc" and "bcc" Internet message headers (which are Internet message headers per RFC 2076), or are we referring to some other MIME headers that serve the cc and bcc purpose?
Please make sure if we're referring to the Internet message headers, then that's not MIME and shouldn't be included here.

2021-05-07 17:31 UTC, opbld33 commented
Docs Build status updates of commit _[1af80fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1af80fd4065ccda7783f9b5b49f3cf6f86824346)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-07 17:36 UTC, opbld31 commented
Docs Build status updates of commit _[69b1f80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69b1f805b34fbd1ddd13a3803248ce5424aac467)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-07 20:23 UTC, opbld32 commented
Docs Build status updates of commit _[6afb7da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6afb7da3aa7aae1107183c49d4bbb978d7ac7d9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-22 23:48 UTC, opbld32 commented
Docs Build status updates of commit _[a943dfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a943dfef98a38c3a87a36ef25b79b7850584fd6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-23 00:50 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createreply.md
> +When using JSON format, you can:
Line 18:
FYI I'm moving the "you can" to line 20, because keeping it in line 18 wouldn't connect with the second bullet point in line 20.
BTW, even though we're doing it in line 18 in message-createforward.md, just so you know in the [style guide](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36412): 
"Global tip
If your content will be localized, avoid lists where an introductory fragment is completed by the list items below it. This can be difficult to translate."

2021-05-23 00:59 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +
Line 25:
FYI I'm making this change to 16 files in your PR:
"... add {something} to..."

2021-05-23 01:30 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
Hm, FYI every description should end with a period, particularly because each table cell already has a phrase that ends with a period.
https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28751

2021-05-23 01:50 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +If the request body includes malformed MIME content, this method returns `400 Bad request` and the following error message: `Invalid base64 string for MIME content`.
Line 69:
FYI I enclosed the error message with double quotes rather than the tick marks.
I chose to do that mainly because of the styling effect (gray background) being applied to the longer length of the sentence. In general, we want to use special styling (like gray background, bolding, etc.) that calls for attention sparingly. The other reason is, in the same context, the phrases `201 Created` and `400 Bad request` are HTTP 1.0+ standards, which might make sense to differentiate them from error messages that are specific to Microsoft.
In general, the current means of styling are limited and doesn't cover all our needs.

2021-05-23 02:20 UTC, angelgolfer-ms commented on api-reference/beta/api/message-createforward.md
> +- Provide the applicable [Internet Message Headers](https://tools.ietf.org/html/rfc2076) and the [MIME content](https://tools.ietf.org/html/rfc2045), all encoded in **base64** format in the request b
Line 24:
FYI "Internet Message Header" should be "Internet message header". I am going to do a search and replace.

2021-05-23 02:54 UTC, angelgolfer-ms commented on api-reference/beta/api/user-post-messages.md
> +- [Update](../api/message-update.md) the draft later to add content to the **body** or change other message properties.
Line 19:
I broke these 2 phrases into 2 bullet points. They are unrelated.

2021-05-23 03:06 UTC, angelgolfer-ms commented on api-reference/beta/api/user-post-messages.md
> +You can save the draft in any folder. To save it in the Drafts folder, use the /messages shortcut.
Line 26:
I know this sentence has been there before this PR: "To save it in the Drafts folder, use the /messages shortcut."
FYI I am going to rephrase it. The way it is makes it sound like "using the /messages shortcut" is an option. AFAIK it's not an option, the CSDL defines the user entity has a messages nav property ("shortcut"?) ; what else can the query URL be otherwise.

2021-05-23 03:06 UTC, angelgolfer-ms commented on api-reference/beta/api/user-post-messages.md
> +You can save the draft in any folder. To save it in the Drafts folder, use the /messages shortcut.
Line 26:
I know this sentence has been there before this PR: "To save it in the Drafts folder, use the /messages shortcut."
FYI I am going to rephrase it. The way it is makes it sound like "using the /messages shortcut" is an option. AFAIK it's not an option, the CSDL defines the user entity has a messages nav property ("shortcut"?) ; what else can the query URL be otherwise.

2021-05-23 03:46 UTC, angelgolfer-ms commented on api-reference/beta/api/user-post-messages.md
>  Here is an example of the request to create a draft of a new message.
Examples section - please note the structure we should use.
Level 2 heading: "Examples"
Level 3 heading: "Example x: {short description}"
Level 4 heading: "Request", "Response". With these headings, we don't keep the count, because the level 3 heading already keeps the count.

2021-05-23 04:29 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/mail-api-overview.md
> +| Send emails with MIME content | [message](../resources/message.md) | [Send MIME content](/graph/outlook-send-mime-message) |
Line 70:
I'm moving this to the section for user-centric actions.

2021-05-23 05:30 UTC, angelgolfer-ms commented on concepts/outlook-mail-concept-overview.md
> +- Integrate with [Focused Inbox](/graph/api/resources/manage-focused-inbox?view=graph-rest-1.0&preserve-view=true) and [@-mentions (preview)](/graph/api/message-get?view=graph-rest-beta&preserve-view
Thanks for fixing these links. FYI including the preserve-view query parameter to versioned links came about only last year. Along with that change was that links to the reference that do not include the ?view query parameter default to v1.0. So we can actually remove the ?view query parameter altogether, and there's no view to preserve either (i.e., don't need to include the preserve-view query parameter).

2021-05-23 07:26 UTC, angelgolfer-ms commented on concepts/outlook-send-mime-message.md
> +There are two supported formarts for creating a [message](/graph/api-reference/v1.0/resources/message.md): (1) JSON metadata (2) MIME content. Specify the selected format in the request header.
FYI, in general, we reserve numbered lists to procedures where the order of the list items matters.
When the order doesn't matter, we use bullet lists.

2021-05-23 07:41 UTC, angelgolfer-ms commented on concepts/outlook-send-mime-message.md
> +| ------| ----- |
Looks like the links in the right column of this table are not specified properly. Site-relative links don't take the file extension (.md).

2021-05-23 07:54 UTC, angelgolfer-ms commented on concepts/outlook-send-mime-message.md
> +## Overview
Lines 11 and 27:
In general, it's a good practice to use section headers for education and SEO purpose, so titling sections within a topic (which is typically shorter than an article) with "Overview" and "Details" are too generic and waste of opportunity.
In a conceptual topic that's usually 1-2 pages, the first part of the topic should summarize the purpose of the topic, so  that being an "overview" is already implicit. We don't usually start a concept topic with a header other than the topic title.

2021-05-23 08:10 UTC, opbld31 commented
Docs Build status updates of commit _[1e3c302](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e3c302fbca82c381fff061070fc40d8a81084e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[concepts/outlook-mail-concept-overview.md](https://github.com/microsoftgraph/micros [...]

2021-05-23 08:24 UTC, angelgolfer-ms requested changes
@isvargasmsft , I made some fixes directly in your PR so that we can publish on 5/24 just before Build. Please take a look at my [commit](https://github.com/microsoftgraph/microsoft-graph-docs/commit/1e3c302fbca82c381fff061070fc40d8a81084e9) and related comments.
There is one thing you should follow up on - the changelog.

2021-05-24 16:08 UTC, opbld30 commented
Docs Build status updates of commit _[84f0d2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84f0d2b4cf144d87854b7e4dd524f241c1e41a23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-grap [...]

2021-05-24 16:27 UTC, opbld31 commented
Docs Build status updates of commit _[5bb513d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bb513d9e5ebf923655e9f0bcf727ee73ace9491)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-grap [...]

2021-05-24 17:27 UTC, opbld30 commented
Docs Build status updates of commit _[9513173](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95131738c2184d25402df90a03e4d583cc3e9233)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-grap [...]

2021-05-24 21:53 UTC, opbld32 commented
Docs Build status updates of commit _[6dab6b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6dab6b620589a38e16b4344252e99c076e4e7e57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/message-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/beta/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/beta/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta&branch=pr-en-us-12275) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/mailfolder-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createforward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createforward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createforward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-createreplyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-createreplyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-createreplyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-forward.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-forward.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-reply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-replyall.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-replyall.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-replyall?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/message-send.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/message-send.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/api/user-sendmail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mail-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-mail-mime/api-reference/v1.0/resources/mail-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0&branch=pr-en-us-12275) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-grap [...]

2021-05-24 22:39 UTC, merged