Add file and file-list docs
microsoftgraph/microsoft-graph-docs pull request #12283
Opened 2021-04-13 15:33 UTC by beth-panx

Add documentation for mgt-file and mgt-file-list

2021-04-13 15:35 UTC, opbld33 commented
Docs Build status updates of commit _[4b723f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b723f435f9688b411b09630e0c33d066d7157af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12283) |
[concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104131533501314-12283%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FXojzSwhauc%2F9wKFTH0AU0FJcOwt%2Bh9TwtzHZqd5KTw%3D&st=2021-04-13T15%3A30%3A19Z&se=2021-05-14T15%3A35%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 03:46 UTC, nmetulev commented
We should target this to a new branch - how about mgt/next/files?

2021-04-20 18:58 UTC, elisenyang requested changes
Looking good! Just left a couple of comments. 

One nitpick: The sections aren't in the same order as some of our other components docs pages. Although I'm not sure if the order is consistent across all of them.

2021-04-20 18:58 UTC, elisenyang commented on concepts/toolkit/components/file.md
> +The File component is used to represent an individual file/folder from OneDrive or SharePoint by displaying information such as the file/folder name, an icon indicating the file type, and other prope
Might be a good idea to add a link to the Files API docs for reference: https://docs.microsoft.com/en-us/graph/onedrive-concept-overview

2021-04-20 18:58 UTC, elisenyang commented on concepts/toolkit/components/file.md
> +| Attribute | Property | Description |
I think it would be helpful to add a couple examples of the different ways to specify a file using the attributes/properties. Maybe under this table?

2021-04-20 18:58 UTC, elisenyang commented on concepts/toolkit/components/file.md
> +| Query | Use if | Permission Scopes |
We should probably update the formatting of this permissions section to match the changes Waldek is making to the other components

2021-04-20 18:58 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +| Attribute | Property | Description |
It would be helpful to add a couple examples of the different ways to specify a file list and also link to the files API docs to provide more context on how to query for drives. https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0

2021-04-20 18:58 UTC, elisenyang commented on concepts/toolkit/components/file-list.md
> +| Query | Use if | Permission Scopes |
Should update this to match the format that Waldek proposes

2021-04-20 19:49 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +| Query | Use if | Permission Scopes |
Can you share a link on the proposal?

2021-04-20 20:01 UTC, beth-panx commented on concepts/toolkit/components/file-list.md
> +| Query | Use if | Permission Scopes |
I found it nvm

2021-04-20 20:15 UTC, opbld31 commented
Docs Build status updates of commit _[2eabc50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eabc5017cfd7fcf06f1f90ae7e290cc97d9c196)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12283) | [Details](#user-content-37d8e9d871a48cebd592fe3f04e9b3c2-7e346910)
[concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) | [Details](#user-content-1e8a4cc28b4884f34f716b86b07844d6-7e346910)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |

<a id="37d8e9d871a48cebd592fe3f04e9b3c2-7e346910"></a>
### [concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md)
 - **Line 10, Column 34**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 10, Column 34**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="1e8a4cc28b4884f34f716b86b07844d6-7e346910"></a>
### [concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md)
 - **Line 10, Column 55**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/onedrive-concept-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104202014396828-12283%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fr1mX3uid2fGTNz24dL0say8FrBAZYfI6iTvt6sr2ds%3D&st=2021-04-20T20%3A10%3A48Z&se=2021-05-21T20%3A15%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 20:26 UTC, opbld30 commented
Docs Build status updates of commit _[839731f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/839731f1b3070f086ea2341543569643b78c1db9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12283) | [Details](#user-content-37d8e9d871a48cebd592fe3f04e9b3c2-965619bd)
[concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) | [Details](#user-content-1e8a4cc28b4884f34f716b86b07844d6-965619bd)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |

<a id="37d8e9d871a48cebd592fe3f04e9b3c2-965619bd"></a>
### [concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md)
 - **Line 10, Column 34**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 10, Column 34**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="1e8a4cc28b4884f34f716b86b07844d6-965619bd"></a>
### [concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md)
 - **Line 10, Column 55**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/onedrive-concept-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104202025350734-12283%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ciaxwDz7vmDV9HYgCln6iuDauhvTUh%2FhMoH2dKUpVbE%3D&st=2021-04-20T20%3A21%3A48Z&se=2021-05-21T20%3A26%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 03:41 UTC, nmetulev commented on concepts/toolkit/components/file-list.md
> +The File List component displays [a list of multiple folders and files](https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0) by using the file/folder name, an icon, and
```suggestion
The File List component displays [a list of multiple folders and files](/graph/api/resources/onedrive) by using the file/folder name, an icon, and other properties specicified by the developer. This component uses the [mgt-file](./file.md) component. The developer is able to specify a specific drive or or site, display a list of files based on insight type (trending, used, or shared), or provide queries to a custom list of files.
```

2021-04-23 03:41 UTC, nmetulev commented on concepts/toolkit/components/file.md
> +The File component is used to represent an individual [file/folder from OneDrive or SharePoint](https://docs.microsoft.com/en-us/graph/onedrive-concept-overview) by displaying information such as the
```suggestion
The File component is used to represent an individual [file/folder from OneDrive or SharePoint](/graph/onedrive-concept-overview) by displaying information such as the file/folder name, an icon indicating the file type, and other properties such as the author, last modified date, or other details selected by the developer. The developer or application provides the identifiers for a file and the component will generate the query to retrieve the file based on the identifiers provided. This component can be used on it's own or as part of the [mgt-file-list](./file-list.md) components.
```

2021-04-23 03:43 UTC, opbld33 commented
Docs Build status updates of commit _[6a3dd85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a3dd8560796983401b4549deef4f56c9cd521d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12283) | [Details](#user-content-37d8e9d871a48cebd592fe3f04e9b3c2-3729ef4c)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |
[concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |

<a id="37d8e9d871a48cebd592fe3f04e9b3c2-3729ef4c"></a>
### [concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md)
 - **Line 10, Column 34**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 10, Column 34**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230341407235-12283%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yRnDcx3NlRkzpVZrBuay9V1gjforuAXwt%2BVHFhSBo0g%3D&st=2021-04-23T03%3A38%3A14Z&se=2021-05-24T03%3A43%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 03:44 UTC, opbld32 commented
Docs Build status updates of commit _[f57d4ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f57d4ba1cbe1881e1fbe4d8fb0d25cf0e78dd8e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12283) |
[concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230341469865-12283%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=566hRm7Rraeo3b16mlPAuauy5bSC6z8qvz%2FPIusjg3c%3D&st=2021-04-23T03%3A39%3A27Z&se=2021-05-24T03%3A44%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 03:51 UTC, nmetulev reviewed
Looks great. Before merging, could you add a caching section for both components, following the same pattern as this PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/12227?

2021-04-23 03:51 UTC, nmetulev commented on concepts/toolkit/components/file-list.md
> +The File List component displays [a list of multiple folders and files](/graph/api/resources/onedrive) by using the file/folder name, an icon, and other properties specicified by the developer. This
```suggestion
The File List component displays [a list of multiple folders and files](/graph/api/resources/onedrive) by using the file/folder name, an icon, and other properties specicified by the developer. This component uses the [mgt-file](./file.md) component. The developer is able to specify a specific drive or site, display a list of files based on insight type (trending, used, or shared), or provide queries to a custom list of files.
```

2021-04-23 03:53 UTC, opbld33 commented
Docs Build status updates of commit _[0157a2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0157a2ecf560655db2bfc6b6bf980705ee6606ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12283) |
[concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230352001553-12283%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K3dJbq%2FkjGUbxChKiuvJmRtL%2BtMuiE%2BtIbww%2FPJS73E%3D&st=2021-04-23T03%3A48%3A08Z&se=2021-05-24T03%3A53%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 18:06 UTC, beth-panx commented
> Looks great. Before merging, could you add a caching section for both components, following the same pattern as this PR: #12227?

Done :)

2021-04-23 18:08 UTC, opbld34 commented
Docs Build status updates of commit _[b9a8634](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9a86342d7475345bfe408ff72400d95f8faa790)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |
[concepts/toolkit/components/file-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12283) |
[concepts/toolkit/components/file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/file+list/concepts/toolkit/components/file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file?branch=pr-en-us-12283) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104231806114393-12283%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=06echQKqciPkLSwejeTXcdiCqwONUMHMRTYfuU5UFTY%3D&st=2021-04-23T18%3A03%3A16Z&se=2021-05-24T18%3A08%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 19:13 UTC, nmetulev approved these changes

2021-04-23 19:13 UTC, merged