Adding documentation for action activateService on organization
microsoftgraph/microsoft-graph-docs pull request #12362
Opened 2021-04-19 13:14 UTC by rungari

2021-04-19 13:15 UTC, opbld34 commented
Docs Build status updates of commit _[35f0962](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35f096228c095c492a97c4c9655051f2d4144734)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-befac5b3)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-befac5b3"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'organization'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104191314240396-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gkXF6Mm8H3OiYKsbxfn9qDLIc5jinSy%2FtBjQCm9qHXs%3D&st=2021-04-19T13%3A10%3A57Z&se=2021-05-20T13%3A15%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 13:22 UTC, opbld33 commented
Docs Build status updates of commit _[3770c49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3770c49fb448145ddeaf388d69d8d154e34f595a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104191321035805-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kZpHexOrNBBuB%2BwWpmU2CnwQQYcIPKsEzL8YGVxSt5k%3D&st=2021-04-19T13%3A17%3A17Z&se=2021-05-20T13%3A22%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-26 19:38 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +description: "`activateService` is used to activate a given service for an organization and will require admin privileges to run."
```suggestion
description: "Activates a service for an organization."
```

2021-04-26 19:39 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +`activateService` is used to activate a given service for an organization and will require admin privileges to run.
```suggestion
The **activateService** object  is used to activate a service for an organization. This operation requires administrator privileges to run.
```

2021-04-26 19:41 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-04-26 19:42 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +| Application | Directory.ReadWrite.All, Directory.ReadWriteAdvanced.All |
```suggestion
| Application | Directory.ReadWriteAdvanced.All, Directory.ReadWrite.All|
```

2021-04-26 19:44 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +In the request body, supply JSON representation of the parameters.
```suggestion
In the request body, supply a JSON representation of the [activateService](../resources/activateService) object.
```

2021-04-26 19:48 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +| Parameter         | Type         | Required? | Description                           |
```suggestion
| Parameter         | Type         | Description                           |
```

2021-04-26 19:48 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +| ----------------- | ------------ | --------- | ------------------------------------- |
```suggestion
| ----------------- | ------------ | ------------------------------------- |
```

2021-04-26 19:49 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +| `service` | `Edm.String` | False     | Name of the service to activate       |
```suggestion
| service`| Edm.String | The name of the service to activate. |
```

2021-04-26 19:50 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +| `servicePlanId`   | `Edm.Guid`   | False     | PlanId of the ServicePlan to activate |
```suggestion
| servicePlanId | Edm.Guid | The plan identifier of the service plan to activate. |
```

2021-04-26 19:52 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +| `skuId`           | `Guid`       | False     | SkuId of SKU the service plan is on   |
```suggestion
| skuId | Guid | The SKU identifier of the service plan. |
```

2021-04-26 19:53 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +POST https://graph.microsoft.com/beta/organization/{organizationId}/activateService
Please provide a real looking identifier instead of the placeholder {organizationId}.

2021-04-26 19:53 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +Content-length: 150
Please remove: "Content-length: 150"

2021-04-26 19:55 UTC, davidmu1 commented on api-reference/beta/resources/organization.md
> +| [activateService](../api/organization-activateservice.md) | None |  Activates a given service for an organization and will require admin privileges to run |
```suggestion
| [activateService](../api/organization-activateservice.md) | None |  Activates a service for an organization. |
```

2021-04-26 19:57 UTC, davidmu1 commented on concepts/changelog.md
>  | Addition | beta | Added the following properties to [Terms of Use agreementfilelocalization](/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&preserve-view=true):<ul><li>isMajorV
Changes to the changelog.md file are no longer needed.

2021-04-27 10:22 UTC, opbld33 commented
Docs Build status updates of commit _[dff9c40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dff9c40d4703e9acad2dea6f31c47868fad7a95d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271021403208-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QWLdo999VLhSQ5hBrb3ueTzajiuK7AfqsTyYxq5TB14%3D&st=2021-04-27T10%3A17%3A53Z&se=2021-05-28T10%3A22%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 10:24 UTC, opbld31 commented
Docs Build status updates of commit _[c2291e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2291e5542726a3e2c856e08ad8885d7994b0fef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271022452209-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h5lU1mpuScNa%2BavEz1RNo3W91uy6YjPud3lAk8%2FW950%3D&st=2021-04-27T10%3A19%3A44Z&se=2021-05-28T10%3A24%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 10:25 UTC, rungari commented on api-reference/beta/api/organization-activateservice.md
> +At least one parameter must be defined for this action to be valid. There are two possible cases: You could have `service` or (`servicePlanId` and `skuId`). If all three parameters are defined, then
Yes this is correct. When the last choice is given then it resolves to the second choice.

2021-04-27 10:27 UTC, opbld32 commented
Docs Build status updates of commit _[06517a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06517a76b67189670b49c8958370b09358611eaa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271022580421-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UYfy6eBU61VpDXWGv%2FU%2BWgfC5I0Bli18hNsqWt857FA%3D&st=2021-04-27T10%3A22%3A14Z&se=2021-05-28T10%3A27%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 10:29 UTC, opbld31 commented
Docs Build status updates of commit _[d14e0fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d14e0fd5b48392a81256f1251903c176e8320021)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271022204637-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NA5Q4oXLQU%2BM64pddcMzcUwDf0TN6jeXgbwDnPsQX84%3D&st=2021-04-27T10%3A24%3A34Z&se=2021-05-28T10%3A29%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 10:30 UTC, opbld33 commented
Docs Build status updates of commit _[a1b0115](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1b011557b454bed8c789aa752e95185361d48bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-e69c8ff6)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-e69c8ff6"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 49, Column 58**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/activateService'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271027330457-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PGfLbEy4a2en1qVcQjXzY5Wabd32%2BGpxFfKNefbB0%2F8%3D&st=2021-04-27T10%3A25%3A44Z&se=2021-05-28T10%3A30%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 10:32 UTC, opbld33 commented
Docs Build status updates of commit _[4aa1197](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4aa119744e5c09099ec7941b2a4e9b3ca3ce3184)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-8f490409)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-8f490409"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 49, Column 58**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/activateService'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271030447590-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8BqvoMnELat6aGp5wPhZhfGeYZh4m7MF3joNSQJy4To%3D&st=2021-04-27T10%3A27%3A06Z&se=2021-05-28T10%3A32%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 10:36 UTC, rungari commented on api-reference/beta/api/organization-activateservice.md
> +At least one parameter must be defined for this action to be valid. There are two possible cases: You could have `service` or (`servicePlanId` and `skuId`). If all three parameters are defined, then
I understand what you mean here, indeed there are three acceptable cases.

2021-04-27 10:39 UTC, opbld33 commented
Docs Build status updates of commit _[bf2f0b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf2f0b904db975ccdf18eae6ffacee30a4d672da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-b5bfb0e3)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-b5bfb0e3"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 49, Column 58**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/activateService'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271037583595-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4CbovhlAaulz3FZoJJgXXXWTWHej5tL7d1MR7z5sbCI%3D&st=2021-04-27T10%3A34%3A47Z&se=2021-05-28T10%3A39%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 10:44 UTC, rungari commented on concepts/changelog.md
>  | Addition | beta | Added the following properties to [Terms of Use agreementfilelocalization](/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&preserve-view=true):<ul><li>isMajorV
Do I need to revert this?

2021-04-27 11:20 UTC, opbld33 commented
Docs Build status updates of commit _[4a6e1fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a6e1faafcdd44053b94e1fadd49401f25beceac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-617b781f)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-617b781f)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-617b781f"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 49, Column 58**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/activateService'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-617b781f"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'actionResultPart resource type' is duplicated with other articles: 'beta/resources/actionresultpart.md(10,1), beta/resources/activateService.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271119160662-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=S6xBiQAhRuEpfQ9kLOinHVAnqiZonwRiLezPdGN5vxI%3D&st=2021-04-27T11%3A15%3A24Z&se=2021-05-28T11%3A20%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 11:27 UTC, opbld30 commented
Docs Build status updates of commit _[c020d68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c020d68729a236b0debd5949904d9a8711d62095)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-04f4daa4)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-04f4daa4)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-04f4daa4"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 49, Column 58**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/activateService'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-04f4daa4"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271125591512-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=99hbnaHNY0LxzstHjsg1L4voB94gL7vy2w%2BSSEcnEiY%3D&st=2021-04-27T11%3A22%3A46Z&se=2021-05-28T11%3A27%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 11:32 UTC, opbld32 commented
Docs Build status updates of commit _[37a0f42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37a0f42e3466af292cb3d60a3fe65bc5a3d01b57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271129501832-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hw6NYrlJvis5nZiyZH3jO61zvy4qXlN64ThXVlG6u1o%3D&st=2021-04-27T11%3A27%3A12Z&se=2021-05-28T11%3A32%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 12:48 UTC, srutto approved these changes

2021-05-04 14:30 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +The **activateService** object  is used to activate a service for an organization. This operation requires administrator privileges to run.
Since there are different administrator types in Azure AD, specify the administrator type. Example, "The requestor needs to have one of the following roles: _Global Administrator_ or _Groups Administrator_.". Then, move this statement just below the permissions table.
```suggestion
The **activateService** object  is used to activate a service for an organization.
```

2021-05-04 14:30 UTC, FaithOmbongi commented on concepts/changelog.md
>  | Addition | beta | Added the following properties to [Terms of Use agreementfilelocalization](/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&preserve-view=true):<ul><li>isMajorV
Yes, please do.

2021-05-04 14:30 UTC, FaithOmbongi commented on api-reference/beta/resources/activateService.md
> +| skuId | Guid | The SKU identifier of the service plan. |
Global: **String** and **Guid** will do.

2021-05-04 14:30 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +**Note:** The response object shown here might be shortened for readability.
Not required with a 204.
```suggestion
```

2021-05-04 14:30 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +| Application | Directory.ReadWriteAdvanced.All, Directory.ReadWrite.All|
_Directory.ReadWriteAdvanced.All_ looks like an undocumented permission. Please document it in the permissions reference and add the changelog entry.

2021-05-04 15:55 UTC, eketo-msft requested changes

2021-05-04 15:55 UTC, eketo-msft commented on api-reference/beta/api/organization-activateservice.md
> +The **activateService** object  is used to activate a service for an organization. This operation requires administrator privileges to run.
ActivateService is an action, not an object. Also there is a double space which should be a single space.

2021-05-04 15:55 UTC, eketo-msft commented on api-reference/beta/api/organization-activateservice.md
> +POST https://graph.microsoft.com/beta/organization/72f988bf-86f1-41af-91ab-2d7cd011db47/activateService
{organizationId} instead of the GUID

2021-05-04 15:55 UTC, eketo-msft commented on api-reference/beta/resources/activateService.md
> +The **activateService** object  is used to activate a service for an organization.
action and single space here too

2021-05-06 19:41 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +At least one parameter must be defined for this action to be valid. There are three possible cases: You could have `service` or (`servicePlanId` and `skuId`). If all three parameters are defined, the
They are properties not parameters.

2021-05-06 19:42 UTC, davidmu1 commented on api-reference/beta/api/organization-activateservice.md
> +### Parameters
This heading isn't needed.

2021-05-06 19:43 UTC, davidmu1 commented on api-reference/beta/resources/activateService.md
> +description: "Payload that activates a service for an organization."
```suggestion
description: "Activates a service for an organization."
```

2021-05-06 19:43 UTC, davidmu1 approved these changes

2021-05-07 08:14 UTC, opbld31 commented
Docs Build status updates of commit _[bdd8ee0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bdd8ee0a1855a0db1953dc9d81aa173f65368903)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-db6b82f1)
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-db6b82f1)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-db6b82f1)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="0817dce4456c16725d5333633847d38f-db6b82f1"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml)
 - **Line 11240, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-db6b82f1"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-db6b82f1"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105070812238290-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L1rBvqGPzOCFT5Bbk4Vk1wg09egTtDnV1HYuH8CKiNs%3D&st=2021-05-07T08%3A09%3A43Z&se=2021-06-07T08%3A14%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-07 08:25 UTC, opbld30 commented
Docs Build status updates of commit _[3ac4331](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ac43310359eec97778c6fb3e614d6a8520c0d06)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6ba8f806)
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-6ba8f806)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-6ba8f806)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="0817dce4456c16725d5333633847d38f-6ba8f806"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml)
 - **Line 11240, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-6ba8f806"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-6ba8f806"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105070823537843-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MuUHN7P1qx0ZxX6RSm91DnkCLkT9K4LHU76Dx3m%2FNQQ%3D&st=2021-05-07T08%3A20%3A12Z&se=2021-06-07T08%3A25%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-17 08:25 UTC, opbld34 commented
Docs Build status updates of commit _[5d1f6b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d1f6b0136beb30a94c506fc13559db9842cfe6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-8190c1b5)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-8190c1b5)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-8190c1b5"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-8190c1b5"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105170824358692-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FpfGhH3gmPD0oneDEN249YPoW3oKSpMuDXYcqgWI2%2FE%3D&st=2021-05-17T08%3A20%3A50Z&se=2021-06-17T08%3A25%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-17 08:29 UTC, rungari commented on api-reference/beta/api/organization-activateservice.md
> +| Application | Directory.ReadWriteAdvanced.All, Directory.ReadWrite.All|
@FaithOmbongi we have realized that this permission is not yet exposed and have removed it from the documentation for now. The other permission should be sufficuent.

2021-05-19 14:02 UTC, FaithOmbongi requested changes
Requested a few changes.

2021-05-19 14:02 UTC, FaithOmbongi commented on concepts/changelog.md
> +| Addition | beta | Added the [activateService](https://docs.microsoft.com/en-us/graph/api/organization-activateService?view=graph-rest-beta) method to the [organization](https://docs.microsoft.com/e
Kindly remove the changelog.md file from the PR. Only the changelog json is required.

2021-05-19 14:02 UTC, FaithOmbongi commented on changelog-stubs/Microsoft.DirectoryServices.json
> +{"changelog":[{"ChangeList":[{"Id":"f72f8abc-a10b-11eb-8cb0-33bc249d550e","ApiChange":"Method","ChangedApiName":"activateService","ChangeType":"Addition","Description":"Added the [activateService](ht
Kindly remove the stub file from the PR.

2021-05-19 14:04 UTC, opbld30 commented
Docs Build status updates of commit _[c7ff183](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7ff183bae1228aadf00bb80280dfa009a6a25b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-a9372507)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-a9372507)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog-stubs/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog-stubs/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-a9372507"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-a9372507"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105191403010508-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BwNLd59cGe0i305kEKkYOQ3OH6OOdpOYgNk5HmXosSQ%3D&st=2021-05-19T13%3A59%3A16Z&se=2021-06-19T14%3A04%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 07:28 UTC, rungari commented on api-reference/beta/api/organization-activateservice.md
> +At least one property must be defined for this action to be valid. There are three possible cases: You could have `service` or (`servicePlanId` and `skuId`). If all three properties are defined, then
I see it as three cases:
1. `service`
2. `servicePlanId` && `skuId`
3. `service`, `servicePlanId` and `skuid` (this internally resolves to (`servicePlanId` && `skuId`)

It all depends on whether we want to see the third option as a case or not.

2021-05-20 07:36 UTC, rungari commented on api-reference/beta/resources/activateService.md
> +}
Removed extra }

2021-05-20 07:37 UTC, opbld30 commented
Docs Build status updates of commit _[d54140e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d54140eeab2dc250e4f1d918d328151474d75aaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-ea74b97a)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-ea74b97a)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-ea74b97a"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-ea74b97a"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105200735519742-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UD0lkC%2FEec6bXPWQWLYh0%2FAhJ6H39oB7O4TZtUE7C7Y%3D&st=2021-05-20T07%3A32%3A19Z&se=2021-06-20T07%3A37%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 07:42 UTC, opbld34 commented
Docs Build status updates of commit _[1a3f992](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a3f992db4e512e2574dfe53d080295b568eafce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-13235bcb)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-69b3fd5b285656692e3985bc1e6d7914-13235bcb)
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-13235bcb"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

<a id="69b3fd5b285656692e3985bc1e6d7914-13235bcb"></a>
### [api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Activates a service for an organization.' is duplicated in 'beta/api/organization-activateservice.md(3,14)', 'beta/resources/activateService.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105200740494617-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GL66WDMfsgu4Cx%2FrbRq4%2FijXBwCLV6TwbkXa54InxaQ%3D&st=2021-05-20T07%3A37%3A09Z&se=2021-06-20T07%3A42%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 07:46 UTC, opbld34 commented
Docs Build status updates of commit _[04ec832](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04ec832ec88d9753abb883f7cfc1f55f7bc97257)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105200745100828-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AGB6vTDA%2FLqfVYzR5HplO4UNcu%2FchyaU89YXDyA1WoA%3D&st=2021-05-20T07%3A41%3A24Z&se=2021-06-20T07%3A46%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 16:19 UTC, eketo-msft commented on api-reference/beta/api/organization-activateservice.md
> +At least one property must be defined for this action to be valid. There are three possible cases: You could have `service` or (`servicePlanId` and `skuId`). If all three properties are defined, then
@davidmu1 do you have advice here?

2021-05-28 08:21 UTC, FaithOmbongi requested changes

2021-05-28 08:21 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +At least one property must be defined for this action to be valid. There are three possible cases: You could have `service` or (`servicePlanId` and `skuId`). If all three properties are defined, then
```suggestion
You must define **service** or **servicePlanId** _and_ **skuId** for this action to be valid.
```

2021-05-28 08:21 UTC, FaithOmbongi commented on api-reference/beta/resources/activateService.md
> +}
JSON representation in resource pages has the data types, the response payload in resource files have real values. See guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103182/Create-new-documentation?anchor=author-content

2021-05-28 08:40 UTC, rungari commented on api-reference/beta/resources/activateService.md
> +}
Updated

2021-05-28 08:44 UTC, rungari commented on api-reference/beta/api/organization-activateservice.md
> +At least one property must be defined for this action to be valid. There are three possible cases: You could have `service` or (`servicePlanId` and `skuId`). If all three properties are defined, then
Based on @FaithOmbongi 's suggestion I have changed it to read this way: 

You must define **service** or **servicePlanId** _and_ **skuId** for this action to be valid.

2021-05-28 09:09 UTC, opbld30 commented
Docs Build status updates of commit _[88d64f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88d64f7f17d897e0ea4d67d3d578793e64dfdcb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280907542521-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xW0JfvB2DnrcnkygP67tgQ556Mnn5mUGgBVon7thL6Y%3D&st=2021-05-28T09%3A04%3A28Z&se=2021-06-28T09%3A09%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 09:19 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +
```suggestion
``` http
POST https://graph.microsoft.com/beta/organization/{:organizationId}/activateService
Content-Type: application/json

{
    "skuId": "6fd2c87f-b296-42f0-b197-1e91e994b900",
    "servicePlanId": "a23b959c-7ce8-4e57-9140-b90eb88a9e97"
}
``` 
```

2021-05-28 09:22 UTC, opbld33 commented
Docs Build status updates of commit _[d758ab4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d758ab4d826c187337d8333fb0933b0ae25e268d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280918296081-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TRHTvpZzOnqVY4iAERjz6prjXVTCBQ9cYUvf4DHBxAU%3D&st=2021-05-28T09%3A17%3A03Z&se=2021-06-28T09%3A22%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 09:24 UTC, FaithOmbongi commented on api-reference/beta/api/organization-activateservice.md
> +```
```suggestion
``` http
POST https://graph.microsoft.com/beta/organization/{:organizationId}/activateService
Content-Type: application/json

{
    "skuId": "6fd2c87f-b296-42f0-b197-1e91e994b900",
    "servicePlanId": "a23b959c-7ce8-4e57-9140-b90eb88a9e97"
}
```

### Response
<!-- {
  "blockType": "response",
  "truncated": true
}
-->
``` http
HTTP/1.1 204 No Content
```
```

2021-05-28 09:26 UTC, opbld32 commented
Docs Build status updates of commit _[c28b546](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c28b54648d060fd006ea5c1b1fc92010130a0e79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) | [Details](#user-content-90c55e0ef4a2a9799a25a7ea3ba8d79a-567ea5b6)
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="90c55e0ef4a2a9799a25a7ea3ba8d79a-567ea5b6"></a>
### [api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md)
 - **Line 70, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280924387967-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hANBcUNs1JU0H5WJTj0iUlKYNcPmWi7NcbJFavIIn6I%3D&st=2021-05-28T09%3A21%3A38Z&se=2021-06-28T09%3A26%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 09:31 UTC, opbld34 commented
Docs Build status updates of commit _[0a74de2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a74de2bc7924c551582b8fff8e212cc696eb1e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280929210136-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BBAQVHVTp1XenM80tb1Do7xzSzQqsISzF3QbLj1AdVk%3D&st=2021-05-28T09%3A26%3A58Z&se=2021-06-28T09%3A31%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 09:45 UTC, opbld34 commented
Docs Build status updates of commit _[b59109a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b59109a9758fbab095c5509f0647b704db0cacbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280944265612-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hIauVxIukbJkDVRkMj1RsH9sHK%2FZ0%2BKjxkkb32uX8p8%3D&st=2021-05-28T09%3A40%3A50Z&se=2021-06-28T09%3A45%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 09:51 UTC, opbld32 commented
Docs Build status updates of commit _[ac7e45b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac7e45bacbdbbe61d753ce802554a073a2aae587)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280949356089-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8Z9F2CCfA4ygNhTbuiRbyxEFErW%2FjpCCFDw52UKbLtQ%3D&st=2021-05-28T09%3A46%3A37Z&se=2021-06-28T09%3A51%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 09:52 UTC, FaithOmbongi approved these changes

2021-06-02 08:01 UTC, opbld32 commented
Docs Build status updates of commit _[b782aaf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b782aaf4516207b04eeb0b743c539ae1fa2dec7f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0f65094c)

<a id="0f65094c"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106020800499324-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4qOGrvytnJdFJT6YIeq7nX%2FLbvAE0K%2FWYP0BxMV3IHg%3D&st=2021-06-02T07%3A56%3A15Z&se=2021-07-03T08%3A01%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 08:09 UTC, opbld31 commented
Docs Build status updates of commit _[b5b3d00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5b3d007957d7a1334c18f0778b8eb0b11183aeb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-12362) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106020808074623-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uYCBdY834LdOGSdPxtg5ivgMxVWA2viYnVV0d5ZoYh0%3D&st=2021-06-02T08%3A04%3A32Z&se=2021-07-03T08%3A09%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 16:02 UTC, eketo-msft approved these changes

2021-06-08 20:44 UTC, Lauragra commented on api-reference/beta/api/organization-activateservice.md
> +## Description
Please remove this non-standard H2 heading. API and resource topics should adhere to the structure that is output by the tool. The text that follows the namespace and beta disclaimer should be the summary description of the resource or API (not a heading - stacked headings are bad for SEO).

2021-06-08 20:45 UTC, Lauragra commented on api-reference/beta/api/organization-activateservice.md
> +The **activateService** action is used to activate a service for an organization.
We don't repeat the name of the entity in the summary statement. For APIs, the summary starts with an imperative verb. Please revise as "Activate a service for an organization." You might want to link to the organization resource as well.

2021-06-09 08:35 UTC, rungari commented on api-reference/beta/api/organization-activateservice.md
> +## Description
Updated

2021-06-09 08:36 UTC, rungari commented on api-reference/beta/api/organization-activateservice.md
> +The **activateService** action is used to activate a service for an organization.
Updated

2021-06-09 08:36 UTC, opbld32 commented
Docs Build status updates of commit _[103d9e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/103d9e1d4dfd27e90b9a3007b648f1d07e5d3f31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateService.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-12362) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106090835141660-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O4XzttX1UbLtdOjCBRRUZg6YM7N6NXjmPVrbRQn%2FUbk%3D&st=2021-06-09T08%3A31%3A43Z&se=2021-07-10T08%3A36%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 17:40 UTC, Lauragra commented on api-reference/beta/resources/activateService.md
> +The **activateService** action is used to activate a service for an organization.
This seems like a description of the action (method topic) not a description of the resource. The resource description might be something like "Represents a service to be activated."

2021-06-22 17:40 UTC, opbld31 commented
Docs Build status updates of commit _[cd4059e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd4059e60564197b7c52f795d9f57faff139aaea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-12362) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106221739019187-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BlKE93cGw49ajSAwexZ1MdW4QkJdM0xKa3CBh1%2F7cCE%3D&st=2021-06-22T17%3A35%3A31Z&se=2021-07-23T17%3A40%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 17:40 UTC, Lauragra commented on api-reference/beta/resources/activateService.md
> +| servicePlanId | Guid | The plan identifier of the service plan to activate. |
GUID is an acronym so should be all caps.

2021-06-22 17:41 UTC, Lauragra commented on api-reference/beta/resources/organization.md
> +|[Get branding](../api/organizationalbrandingproperties-get.md) | [organizationalBrandingProperties](organizationalbrandingproperties.md) collection | Get a organizationalBrandingProperties object co
Please revise the description as: "Get a collection of **organizationalBrandingProperties** objects."

2021-06-22 17:42 UTC, Lauragra commented on api-reference/beta/resources/organization.md
> +| [activateService](../api/organization-activateservice.md) | None |  Activates a service for an organization. |
Use the imperative verb form here, so Activates should be Activate.

2021-06-22 17:42 UTC, Lauragra commented on api-reference/v1.0/resources/printerstatus.md
> +|alertRemovalOfBinaryChangeEntry|36|This is a standard IPP Printer Attribute value described in PWG5100.9.|
Please remove this from the PR. This might have been added due to accidentally syncing your branch from master instead of main (I saw this happen to another PR too).

2021-06-22 17:43 UTC, Lauragra commented on changelog/Microsoft.PrintService.json
> +    {
Remove this change from the PR.

2021-06-22 17:44 UTC, Lauragra commented on concepts/changelog.md
> +## June 2021
Remove this change from the PR.

2021-06-23 07:20 UTC, opbld30 commented
Docs Build status updates of commit _[11a0374](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11a037438a71d6b79836c4ac48e71b8bcace4f02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12362) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106230718300506-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RFKfzyngdhqtoUkjqTlhxNGc1Zag7n9bwlC9HqO%2BdMw%3D&st=2021-06-23T07%3A14%3A59Z&se=2021-07-24T07%3A19%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 07:30 UTC, opbld33 commented
Docs Build status updates of commit _[e69b31c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e69b31c71625c297219746503c4e35e8e304b24c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106230729039867-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KO26Pi83rHZ70zq60oRXlGxRBt4gKyCqZnqVazJ83eY%3D&st=2021-06-23T07%3A25%3A52Z&se=2021-07-24T07%3A30%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 07:36 UTC, opbld33 commented
Docs Build status updates of commit _[343e82e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/343e82ec839f5689e904d0c8cf38794212d47b5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106230732483674-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JUcee56vmydKc0rD%2BJelwuOUyVEL8kOJgrSCB%2FjPHM8%3D&st=2021-06-23T07%3A31%3A06Z&se=2021-07-24T07%3A36%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 07:42 UTC, opbld33 commented
Docs Build status updates of commit _[cc1b745](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc1b7454b7bc9d7feb803a688d6d74bad162225d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106230738597426-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=50Vn07MglMtYAhSk5vowNaIIYSLo1JSVidgW6dIglWg%3D&st=2021-06-23T07%3A37%3A29Z&se=2021-07-24T07%3A42%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 07:43 UTC, rungari commented on changelog/Microsoft.PrintService.json
> +    {
Removed

2021-06-23 07:43 UTC, rungari commented on api-reference/v1.0/resources/printerstatus.md
> +|alertRemovalOfBinaryChangeEntry|36|This is a standard IPP Printer Attribute value described in PWG5100.9.|
Removed

2021-06-23 07:43 UTC, rungari commented on api-reference/beta/resources/organization.md
> +| [activateService](../api/organization-activateservice.md) | None |  Activates a service for an organization. |
Updated

2021-06-23 07:47 UTC, rungari commented on api-reference/beta/resources/activateService.md
> +The **activateService** action is used to activate a service for an organization.
Updated

2021-06-23 07:47 UTC, rungari commented on api-reference/beta/resources/activateService.md
> +| servicePlanId | Guid | The plan identifier of the service plan to activate. |
updated

2021-06-23 07:48 UTC, rungari commented on api-reference/beta/resources/organization.md
> +|[Get branding](../api/organizationalbrandingproperties-get.md) | [organizationalBrandingProperties](organizationalbrandingproperties.md) collection | Get a organizationalBrandingProperties object co
updated

2021-06-24 00:17 UTC, opbld34 commented
Docs Build status updates of commit _[7c4b62a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c4b62a6853308267a6194b69e88cd6a01dbab97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organization-activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/api/organization-activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/activateservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/activateservice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/resources/organization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organization-activateservice?view=graph-rest-beta&branch=pr-en-us-12362) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-org-activateServiceAction/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240015400655-12362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MRHSQD2Pf2amNx0%2ByL3G%2BR0L1%2BOUzedK1OundpZsbJ8%3D&st=2021-06-24T00%3A12%3A10Z&se=2021-07-25T00%3A17%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 00:17 UTC, Lauragra approved these changes

2021-06-24 00:34 UTC, merged