access review policy
microsoftgraph/microsoft-graph-docs pull request #12370
Opened 2021-04-19 22:08 UTC by kaiwenfeng4086

2021-04-19 22:09 UTC, opbld33 commented
Docs Build status updates of commit _[248aa80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/248aa8010d29901699856abd789ec1e25829f997)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/resources/accessreviewpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewpolicy?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104192208352714-12370%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kHO0BqJPyWgktfRlKm1VXrz4r519Eo9go9F6Q6E7jvA%3D&st=2021-04-19T22%3A04%3A47Z&se=2021-05-20T22%3A09%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 22:30 UTC, isabelleatmsft requested changes
Overall looks great. Left a couple comments. Also, could you please update beta/toc.yml to include these new pages in the table of contents?

2021-04-19 22:30 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewpolicy.md
> +Access reviews Policy is a singleton that enable organizations to manage access review directory level policy.
This is good, but I think we should add a sentence giving a little more context: "Access review policy is a singleton that enables administrators to manage directory-level access review policies. For example, administrators can use the access review policy to enable and disable the ability of group owners to create access reviews on group that they own."

2021-04-19 22:30 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewpolicy.md
> +|description|String|Description for this policy.|
description and displayName are not editable, correct? If so, please add "Read-only." to the end of the description column for each.

2021-04-19 22:30 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewpolicy.md
> +  "displayName": "String",
The content team usually requests real values filled in here - could you please fill in the values for each property?

2021-04-19 22:49 UTC, kaiwenfeng4086 commented on api-reference/beta/resources/accessreviewpolicy.md
> +Access reviews Policy is a singleton that enable organizations to manage access review directory level policy.
updated

2021-04-19 22:49 UTC, kaiwenfeng4086 commented on api-reference/beta/resources/accessreviewpolicy.md
> +|description|String|Description for this policy.|
updated

2021-04-19 22:49 UTC, kaiwenfeng4086 commented on api-reference/beta/resources/accessreviewpolicy.md
> +  "displayName": "String",
updated

2021-04-19 22:49 UTC, opbld33 commented
Docs Build status updates of commit _[8870e00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8870e005952837ac87cd8eed21656d050fa4f4ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/resources/accessreviewpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewpolicy?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104192248289279-12370%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c0slkSn98sI5jlrWhTzO%2F%2BgzftBfUVoxgrCS0Sandzo%3D&st=2021-04-19T22%3A44%3A37Z&se=2021-05-20T22%3A49%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 22:52 UTC, isabelleatmsft approved these changes

2021-04-20 06:56 UTC, FaithOmbongi requested changes

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewpolicy-get.md
> +author: "kafen"
Global: Please make sure the author is in the [Microsoft Graph contacts list](https://microsoft.sharepoint.com/sites/Graph/Lists/Microsoft%20Graph%20Contacts/AllItems.aspx?CT=1606755556215&OR=OWA%2DNT&CID=798496d0%2D7bc3%2Df8db%2D49ee%2D45ab03388a04&FilterFields1=LinkTitle&FilterValues1=AAD%3B%23AAD%20B2B%3B%23AAD%20B2C%3B%23Core%3B%23Groups&FilterTypes1=Computed&viewid=56fbc209%2Daadb%2D403b%2Da4f7%2Dcb841ae6a70c&id=%2Fsites%2FGraph%2FLists%2FMicrosoft%20Graph%20Contacts). They are the owner of this workload's docs & are responsible for both PRs & GH issues.

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewpolicy-get.md
> +  "name": "get_accessreviewpolicy"
Global: Differentiate from the first example. For example, "get_accessreviewpolicy_2". Will help when troubleshooting any errors.

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewpolicy-update.md
> +|isGroupOwnerManagementEnabled|Boolean|If true, group owners can create and manage access reviews on groups they own|
```suggestion
|isGroupOwnerManagementEnabled|Boolean|If `true`, group owners can create and manage access reviews on groups they own.|
```

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewpolicy-update.md
> +If successful, this method returns a `204 NoContent` response code.
```suggestion
If successful, this method returns a `204 No Content` response code.
```

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewpolicy-get.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.AccessReviews|
Please ensure **Policy.ReadWrite.AccessReviews** and any other permissions are also documented in the [permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference).

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewpolicy-update.md
> +HTTP/1.1 204 NoContent
```suggestion
HTTP/1.1 204 No Content
```

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewpolicy-update.md
> +HTTP/1.1 204 NoContent
```suggestion
HTTP/1.1 204 No Content
```

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewpolicy.md
> +description: "Access reviews Policy is a singleton that enable organizations to manage access review directory level policy."
```suggestion
description: "Access reviews policy is a singleton that enables organizations to manage directory-level access review policy."
```

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewpolicy.md
> +Access review policy is a singleton that enables administrators to manage directory-level access review policies. For example, administrators can use the access review policy to enable and disable th
```suggestion
Access review policy is a singleton that enables administrators to manage directory-level access review policies. For example, administrators can use the access review policy to enable and disable the ability of group owners to create access reviews on groups that they own.
```

2021-04-20 06:56 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewpolicy.md
> +|isGroupOwnerManagementEnabled|Boolean|If true, group owners can create and manage access reviews on groups they own|
```suggestion
|isGroupOwnerManagementEnabled|Boolean|If `true`, group owners can create and manage access reviews on groups they own.|
```

2021-04-20 06:56 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          },
Can't see **policyRoot**, **accessReviewSet** resources in the public doc set. Are you introducing them in another PR? If not, kindly remove these references.

2021-04-20 06:56 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
>            }
Kindly add this PR's changelog entry as a separate object, first entry; not within an existing object. As you do that, please modify the value of access reviews SubArea to **Governance**.

2021-04-20 18:44 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewpolicy-get.md
> +author: "kafen"
@kaiwenfeng4086 you can put "isabelleatmsft" as the author here so we dont have to expand the contacts list too much

2021-04-26 20:01 UTC, davidmu1 commented on api-reference/beta/api/accessreviewpolicy-update.md
> +Content-length: 163
Content-length isn't needed in the examples.

2021-04-26 20:02 UTC, davidmu1 approved these changes
Agree with Faith's comments.

2021-04-27 18:02 UTC, opbld32 commented
Docs Build status updates of commit _[02c1546](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02c1546826d7d1d56e9832f004f17247345fcb90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/resources/accessreviewpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewpolicy?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271800556092-12370%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4OIoOXXRo5Xg%2F7EYABY8PzvYT6%2BzmDsNsVu2BMgH0Hc%3D&st=2021-04-27T17%3A57%3A08Z&se=2021-05-28T18%3A02%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 18:03 UTC, opbld32 commented
Docs Build status updates of commit _[02c1546](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02c1546826d7d1d56e9832f004f17247345fcb90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/resources/accessreviewpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewpolicy?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271801061605-12370%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0Py%2BpY0mlkOhOlLpWfOnue4rrJV5y77qS2h%2BkjQXxbE%3D&st=2021-04-27T17%3A58%3A34Z&se=2021-05-28T18%3A03%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 18:10 UTC, opbld33 commented
Docs Build status updates of commit _[025971e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/025971e6fd9f48f80edac7ac6a4326107823b4c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/resources/accessreviewpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewpolicy?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271808262987-12370%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uK3f24rnshkjAm3h%2FelY1e35xOx9plMGdwXp68Ih72w%3D&st=2021-04-27T18%3A05%3A15Z&se=2021-05-28T18%3A10%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 18:50 UTC, opbld31 commented
Docs Build status updates of commit _[15b3a38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15b3a3849e66dc77b16526145095355b294a3661)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/api/accessreviewpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/api/accessreviewpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-update?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/resources/accessreviewpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewpolicy?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewpolicy-get?view=graph-rest-beta&branch=pr-en-us-12370) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-04-19-test/AccessReviewPolicy/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271848445618-12370%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JIWyKJHoLVM3Z20F7ZB3PsLwq1YWb3REmKRMdf7CDS0%3D&st=2021-04-27T18%3A44%3A59Z&se=2021-05-28T18%3A49%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 18:56 UTC, isabelleatmsft approved these changes

2021-04-27 18:56 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewpolicy-get.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.AccessReviews|
did this in this PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/12506

2021-04-27 19:19 UTC, FaithOmbongi approved these changes

2021-04-28 01:12 UTC, merged