Add channel email settings documentation
microsoftgraph/microsoft-graph-docs pull request #12449
Opened 2021-04-23 11:15 UTC by shantanu1singh

Add channel email settings documentation

2021-04-23 11:16 UTC, opbld30 commented
Docs Build status updates of commit _[19b5103](https://github.com/shantanu1singh/microsoft-graph-docs/commits/19b5103f4ee51f5e64c7d5ade9da57d7729fee2b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-097ba00f540dee26552b94fbc8f204e5-57eecbe4)
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-bdc5c1ed4d92c23a29bbd9be2cd972ba-57eecbe4)
[api-reference/beta/resources/channelEmailAllowedSenders.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailAllowedSenders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelemailallowedsenders?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-177f60a94903e056b25930d89be56b8d-57eecbe4)
[api-reference/beta/resources/channelEmailSettings.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailSettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelemailsettings?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-4b4da7a0bf81da1eaabd3a94514e0b27-57eecbe4)
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-4f6c0113dc16e6b755dd832273190f0c-57eecbe4)
[api-reference/beta/api/channel-get.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="097ba00f540dee26552b94fbc8f204e5-57eecbe4"></a>
### [api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'shsi' is not a valid GitHub ID.`````

<a id="bdc5c1ed4d92c23a29bbd9be2cd972ba-57eecbe4"></a>
### [api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'shsi' is not a valid GitHub ID.`````

<a id="177f60a94903e056b25930d89be56b8d-57eecbe4"></a>
### [api-reference/beta/resources/channelEmailAllowedSenders.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailAllowedSenders.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'shsi' is not a valid GitHub ID.`````
 - **Line 18, Column 5**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelEmailAllowedSenderType-values' in 'beta/resources/enums.md', did you mean '#channelemailallowedsendertype-values'?`````
 - **Line 25, Column 16**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelEmailAllowedSenderType-values' in 'beta/resources/enums.md', did you mean '#channelemailallowedsendertype-values'?`````

<a id="4b4da7a0bf81da1eaabd3a94514e0b27-57eecbe4"></a>
### [api-reference/beta/resources/channelEmailSettings.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailSettings.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'shsi' is not a valid GitHub ID.`````

<a id="4f6c0113dc16e6b755dd832273190f0c-57eecbe4"></a>
### [api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'shsi' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104231115198872-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OPCBcxGe0w9nIuVQfaV7DBUvk5Pfl0R6GwN5lxYRhu0%3D&st=2021-04-23T11%3A11%3A29Z&se=2021-05-24T11%3A16%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report [...]

2021-04-23 19:28 UTC, opbld30 commented
Docs Build status updates of commit _[c325a5c](https://github.com/shantanu1singh/microsoft-graph-docs/commits/c325a5c68dc83936d2a5fb67aa3c6c9b82d2874b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channelEmailAllowedSenders.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailAllowedSenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelemailallowedsenders?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channelEmailSettings.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelemailsettings?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104231927059929-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HEMywdwatul%2FSfdIHA%2FR%2BDZcyQb0zcpD4oHQj1BZOeg%3D&st=2021-04-23T19%3A23%3A18Z&se=2021-05-24T19%3A28%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 21:23 UTC, anandab-msft commented on api-reference/beta/api/channel-patch.md
> +A channel's email must have been provisioned using the API to [provision channel email](channel-provisionemail.md) before an attempt to update the email settings can be made.
What if the email is provisioned by user action in teams client, then will this not work?

2021-04-23 21:24 UTC, anandab-msft commented on api-reference/beta/api/channel-patch.md
> +> **Note**: Channel email settings currently cannot be updated for shared channels.
we have not released beta API/docs for shared channel, so we should not mention shared channel.

2021-04-23 21:26 UTC, anandab-msft commented on api-reference/beta/api/channel-provisionemail.md
> +> **Note**: This API is currently not supported for shared channels.
lets remove shared channel reference

2021-04-23 21:30 UTC, anandab-msft commented on api-reference/beta/api/channel-removeemail.md
> +To remove a channel's provisioned email address, it must have first been provisioned using the API to [provision channel email](channel-provisionemail.md).
email can be provisioned in teams' client as well

2021-04-23 21:30 UTC, anandab-msft commented on api-reference/beta/api/channel-removeemail.md
> +> **Note**: This API is currently not supported for shared channels.
remove shared channel reference.

2021-04-26 06:20 UTC, shantanu1singh commented on api-reference/beta/api/channel-patch.md
> +A channel's email must have been provisioned using the API to [provision channel email](channel-provisionemail.md) before an attempt to update the email settings can be made.
ah right, good point. I'll add both the API and Teams Client here

2021-04-26 06:20 UTC, shantanu1singh commented on api-reference/beta/api/channel-patch.md
> +> **Note**: Channel email settings currently cannot be updated for shared channels.
I see. Okay, will remove. Thanks!

2021-04-26 06:22 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +> **Note**: This API is currently not supported for shared channels.
done

2021-04-26 06:22 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +To remove a channel's provisioned email address, it must have first been provisioned using the API to [provision channel email](channel-provisionemail.md).
added that too

2021-04-26 06:22 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +> **Note**: This API is currently not supported for shared channels.
done

2021-04-26 06:24 UTC, opbld33 commented
Docs Build status updates of commit _[17db126](https://github.com/shantanu1singh/microsoft-graph-docs/commits/17db126cffd5ad193ad420b3fa38e7e24834ffdb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channelEmailAllowedSenders.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailAllowedSenders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelemailallowedsenders?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channelEmailSettings.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channelEmailSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelemailsettings?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104260623129087-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j%2B32XMn7aBlJBQXccQH%2BXurI%2FqBwMVnwK%2BU6bfuuT84%3D&st=2021-04-26T06%3A19%3A29Z&se=2021-05-27T06%3A24%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:41 UTC, Lauragra commented
@shantanu1singh , please follow the Get started steps to set yourself up to be an internal contributor to the docs.

2021-04-27 09:43 UTC, opbld34 commented
Docs Build status updates of commit _[bafc1be](https://github.com/shantanu1singh/microsoft-graph-docs/commits/bafc1be0971fb9085cc17dc52e60b16d1cb47e69)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-097ba00f540dee26552b94fbc8f204e5-d6180f27)
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="097ba00f540dee26552b94fbc8f204e5-d6180f27"></a>
### [api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md)
 - **Line 46, Column 54**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/channelemailsettings.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270941109349-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H8Ao0nQwY57kSwj%2FK4fQqenLQLBrBLbfj6IFN3tzUnI%3D&st=2021-04-27T09%3A38%3A51Z&se=2021-05-28T09%3A43%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 09:46 UTC, opbld31 commented
Docs Build status updates of commit _[538272b](https://github.com/shantanu1singh/microsoft-graph-docs/commits/538272b6b93d3abf56be53a46ef32d7288852fd6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270944056769-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=25%2FbP%2BPqurNoKpm%2FaquUIj4KrqdJGiRZNcZ7GiHO950%3D&st=2021-04-27T09%3A41%3A19Z&se=2021-05-28T09%3A46%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 09:47 UTC, shantanu1singh commented
> @shantanu1singh , please follow the Get started steps to set yourself up to be an internal contributor to the docs.

@Lauragra could you please link me to 'Get started steps' ? I couldn't find anything other than the CLA agreement which I don't suppose I'll need to sign since I'm a Microsoft employee?

2021-04-27 10:22 UTC, shantanu1singh commented
> > @shantanu1singh , please follow the Get started steps to set yourself up to be an internal contributor to the docs.
> 
> @Lauragra could you please link me to 'Get started steps' ? I couldn't find anything other than the CLA agreement which I don't suppose I'll need to sign since I'm a Microsoft employee?

Never mind, found the guide. I have requested access to join the appropriate group. Can you please help approve?

2021-05-04 05:38 UTC, AkJo commented on api-reference/beta/resources/channel.md
> +  }
Please put this in the same line.

eg:https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta

2021-05-04 05:39 UTC, AkJo commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a Channel that can be used to send messages to a Channel via the email address.
channel

2021-05-04 05:39 UTC, AkJo commented on api-reference/beta/api/channel-provisionemail.md
> +By default, an email address is not provisioned for a Channel.
channel

2021-05-04 05:39 UTC, AkJo commented on api-reference/beta/api/channel-provisionemail.md
> +POST /teams/{id}/channels/{id}/provisionEmail
/teams/{team-id}/channels/{channel-id}/provisionEmail

2021-05-04 05:40 UTC, AkJo commented on api-reference/beta/api/channel-removeemail.md
> +```http
OST /teams/{team-id}/channels/{channel-id}/removeEmail

2021-05-04 05:40 UTC, AkJo approved these changes
Please address comments.

2021-05-04 07:25 UTC, shantanu1singh commented on api-reference/beta/resources/channel.md
> +  }
sure

2021-05-04 07:33 UTC, opbld33 commented
Docs Build status updates of commit _[03fcac5](https://github.com/shantanu1singh/microsoft-graph-docs/commits/03fcac51256342c9393592935c0f5b1ed1374fec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040732017260-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=96IVL4iD7rmjXUKZsznyDEdL5xSg8rlJt3dbG1vHZlM%3D&st=2021-05-04T07%3A28%3A10Z&se=2021-06-04T07%3A33%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 12:13 UTC, opbld31 commented
Docs Build status updates of commit _[695a250](https://github.com/shantanu1singh/microsoft-graph-docs/commits/695a25034e622f6cbde352a7c6f507a4f64d802c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f885bc62)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-f885bc62"></a>
### [api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml)
 - **Line 11238, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105051212375368-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QKRFk%2BPTkK6papvrApkRLwcnqS2Br3CYaQ86a%2B9ux28%3D&st=2021-05-05T12%3A08%3A51Z&se=2021-06-05T12%3A13%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 12:32 UTC, opbld34 commented
Docs Build status updates of commit _[9d6dd7a](https://github.com/shantanu1singh/microsoft-graph-docs/commits/9d6dd7a3209aa37db42c4f0c050037bc3263b553)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-dea69656)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-dea69656"></a>
### [api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml)
 - **Line 11238, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105051231172636-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oKckxEH9SuzPk%2Fv0whcxPygqQIbrEjQMVRGANf%2BJ1Xw%3D&st=2021-05-05T12%3A27%3A21Z&se=2021-06-05T12%3A32%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 01:13 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +Do not supply a request body for this method.
Line 47:
Your api.md specifies there's a emailSettings parameter for this action.
Please document that parameter.
Please follow the guidance for documenting parameters here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103170/Parameters?anchor=documenting-parameters-in-the-request-body

2021-05-12 01:27 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +  "name": "channel_provisionemail"
After line 57:
Please add a "sampleKeys" attribute and note the 2 ID values that you specify in the example request in line 62.
Please find more info here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=id-values-in-example-requests

2021-05-12 01:48 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +
Line 10:
Please follow the topic title convention as described here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title
For this topic, please use the topic title:
channel: provisionEmail

Please note the camel case in the title as specified in the CSDL.

2021-05-12 01:54 UTC, isvargasmsft commented on api-reference/beta/api/channel-removeemail.md
> +# Remove channel email
Please follow the guidelines for topic title [here](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title).

In this case:
channel: removeEmail

Thanks!

2021-05-12 02:01 UTC, isvargasmsft commented on api-reference/beta/api/channel-removeemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
By convention, we want to provide the purpose of the API in a single sentence at the top of each topic. Hence, please add an additional enter (one blank line) after line 16.

2021-05-12 02:19 UTC, isvargasmsft commented on api-reference/beta/api/channel-removeemail.md
> +**Note:** The response object shown here might be shortened for readability.
Line 63: 
Did you use the stub topic generator? If you did, please let us know to report the bug accordingly. 

Anyways, please remove this line as it is redundant (there is no response body for this API).

2021-05-12 02:30 UTC, isvargasmsft commented on api-reference/beta/api/channel-removeemail.md
> +To remove a channel's provisioned email address, it must have first been provisioned using the API to [provision channel email](channel-provisionemail.md) or through the Microsoft Teams client.
Line 19: 
I'd suggest re-phrasing:
You can remove an email address only if it was provisioned using the API or through the Microsoft Teams client. 

Please let me know if I got your idea right. In general, we try to keep sentences simple and easy to scan.

2021-05-12 02:44 UTC, isvargasmsft commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "ChangeList": [{
Please include entries for the new enum type, the 2 new complex types and the new property. 

In addition, please note all items should share the same ID. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

2021-05-12 02:51 UTC, isvargasmsft commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +## See also
Please include line 42 in a separate paragraph at the top (after the first one-line paragraph). 
In general, we want to avoid "See also" sections as people usually overlook them.

2021-05-12 03:32 UTC, isvargasmsft commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +Represents the result of the operation [Provision channel email](..\api\channel-provisionemail.md).
Please re-phrase. The purpose of the top sentence is to provide a summary, a description of the resource type.
If we only point to the reference topic we are creating a loop, as the reference topic itself points at the concept topic. 

We can add the link to the reference topic in a subsequent paragraph (please use lower case "provision channel email"), but for the top sentence please include a description of the resource type, what it represents.

2021-05-12 07:55 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +Do not supply a request body for this method.
So, we've decided to not introduce the emailSettings property just yet as we're currently in the process of migrating channels APIs to a different downstream service and need a bit more time to figure out what the right way to support this property via that service would be.

It's still the same API, just that we don't support a payload just yet. This change was discussed with Anand Joshi from my team who is a member of the Graph council too.

You can refer to my Graph schema CSDL change PR which is consistent with the docs change I have here.

2021-05-12 07:55 UTC, shantanu1singh commented on api-reference/beta/resources/channel.md
> +|[Remove channel email](../api/channel-removeemail.md) | None | Remove a channel's provisioned email.|
So, we've decided to not introduce the emailSettings property just yet as we're currently in the process of migrating channels APIs to a different downstream service and need a bit more time to figure out what the right way to support this property via that service would be.

It's still the same API, just that we don't support a payload just yet. This change was discussed with Anand Joshi from my team who is a member of the Graph council too.

You can refer to my Graph schema CSDL change PR which is consistent with the docs change I have here.

2021-05-12 09:10 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +
sure, will do.

2021-05-12 09:12 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +> **Note**: This API currently does not support admin permissions.
Sure, will remove the line. It didn't refer to admin consent. It meant whether the API will work for callers who are administrators of the team. That being said, we have changed it now so that the API works even for admins so thanks for calling this out :)

2021-05-12 09:14 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +  "name": "channel_provisionemail"
Sure, will do. Thanks!

2021-05-12 09:15 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +# Remove channel email
Will update

2021-05-12 09:17 UTC, shantanu1singh commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +Represents the result of the operation [Provision channel email](..\api\channel-provisionemail.md).
Sure, will update.

We are linking the reader to the reference topic at the bottom so I'm going to skip adding it again out here

2021-05-12 09:18 UTC, shantanu1singh commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +## See also
Sure will do

2021-05-12 09:19 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
Sure

2021-05-12 09:22 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +To remove a channel's provisioned email address, it must have first been provisioned using the API to [provision channel email](channel-provisionemail.md) or through the Microsoft Teams client.
Sure, will rephrase. Yep, that's the intent but I'm going to update it to the following so that the reader has a reference to which API we're talking about here:

> You can remove an email address only if it was provisioned using the [provision channel email](channel-provisionemail.md) API or through the Microsoft Teams client.

2021-05-12 09:24 UTC, shantanu1singh commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "ChangeList": [{
So, as I mentioned in my response to another comment, we aren't including the emailSettings property as of now. You can refer to my CSDL change PR for the change we're making as of now.

The emailSettings property will be introduced in a separate upcoming change.

As far as the IDs go, the stub generator tool created separate IDs for me so I didn't update them. I can go manually fix these for now but it'd be good to fix the tool itself as well

2021-05-12 09:30 UTC, opbld31 commented
Docs Build status updates of commit _[92bfcac](https://github.com/shantanu1singh/microsoft-graph-docs/commits/92bfcacfdf26ef522c05604c257a80b1888bfcb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105120928475856-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9u1MPqC3yREd8ty2DnX%2B41bvjc%2BhUE8LjE3pu8e%2B04w%3D&st=2021-05-12T09%3A24%3A59Z&se=2021-06-12T09%3A29%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 19:49 UTC, isvargasmsft commented on api-reference/beta/api/channel-provisionemail.md
> +
Please make the title change in line 10 as well.

2021-05-12 19:56 UTC, isvargasmsft commented on api-reference/beta/api/channel-removeemail.md
> +# Remove channel email
Please update the title in line 10 as well. Thanks!

2021-05-13 00:14 UTC, isvargasmsft commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +Represents the result of the provision channel email operation and includes the email address provisioned for the channel.
In this case, I'd suggest explaining the resource type by its information, and not only by the operation that creates it. For instance, I noticed it contains email information so, an example could be:

- Email address provisioned for a [channel](link reference to channel here) by using the [provision channel email](link here) operation. 

This way it clarifies the nature of the resource type itself, without relying completely in the method. We try to make it clear and easy to understand even for new developers.

2021-05-13 00:15 UTC, isvargasmsft commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +Represents the result of the provision channel email operation and includes the email address provisioned for the channel.
Quick tip: Remember to always include the link to any method, resource and such, in its first mention in a document.

2021-05-13 00:17 UTC, isvargasmsft requested changes
Thank you very much for reviewing our comments and for the quick actions. Great work on this PR. 

Please take a look at the additional comments I made and feel free to ping me on the side if you have any questions.

Kind regards, 

Isaac Vargas

2021-05-17 09:47 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +
Sure

2021-05-17 09:47 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +# Remove channel email
Sure

2021-05-17 09:50 UTC, shantanu1singh commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +Represents the result of the provision channel email operation and includes the email address provisioned for the channel.
Sure, changed it to the following:

Includes the email address provisioned for a [channel](../resources/channel.md) by using the [provision channel email](..\api\channel-provisionemail.md) operation.

2021-05-17 09:52 UTC, opbld33 commented
Docs Build status updates of commit _[0078402](https://github.com/shantanu1singh/microsoft-graph-docs/commits/007840225d44f72fe6032514e4d8f4a0a84f01b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105170951184306-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kaA1gl9f8HyEMoxNOzp0PXUVol7YB1hDXPyuzAlOcso%3D&st=2021-05-17T09%3A47%3A33Z&se=2021-06-17T09%3A52%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 00:11 UTC, angelgolfer-ms commented on api-reference/beta/resources/channel.md
> +|[Remove channel email](../api/channel-removeemail.md) | None | Remove a channel's provisioned email.|
@shantanu1singh , that's fine, thanks for the clarification.
Yes, normally if a partner team points us to their api.md and CSDL and one or both files are inconsistent with the docs PR, the partner needs to explicitly specify what they intend for the release, save us making the wrong guess :-)

2021-05-18 00:52 UTC, isvargasmsft commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "ChangeList": [{
@shantanu1singh thank you for clarifying. We are opening [a bug](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1401723) to review the stub generator issue with the IDs.

2021-05-18 02:15 UTC, angelgolfer-ms commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +Includes the email address provisioned for a [channel](../resources/channel.md) by using the [provision channel email](..\api\channel-provisionemail.md) operation.
Line 16:
@shantanu1singh , FYI I rephrased this description as:
```
Represents the email address [provisioned](..\api\channel-provisionemail.md) for a [channel](channel.md).
```
In case you wonder:
(a) Using "Represents" instead of "Includes" - Some customers assume "include {x}" to mean {x} is a proper subset and is one of a few elements (properties) in the complex types. Since the summary description is meant to be representative, starting with "include" is inappropriate.  When this complex type includes other properties, we'll change the description as appropriate.

(b) The sentence structure "Includes ... provisioned ... by using the {y} method" is ambiguous for Localization.
In general, a phrase like "by using the {y} method" applies to the _subject_ of the sentence, and in line 60, the implicit subject is "this property", as in "(This property) represents..."
However, this is not what you mean. I think you mean to apply that phrase to the provisioning of the _object_, email address.

For now, I included a link for "provisioned" to link to the channel-provisionemail.md file.
If in case you need to make a point that the email address must be provisioned by that method, then you should do it in a second sentence explicitly, such as:
```
Represents the email address provisioned for a [channel](channel.md).

The email address must be provisioned by the [provision channel email](..\api\channel-provisionemail.md) method.
```

Notice that I refer to the method as "method" and not "operation". 
```

2021-05-18 03:50 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
Line 18:
I am going to rephrase this sentence to make it read more smoothly. It should also come after mentioning there's no email address by default (line 20). 
The use of "set up" doesn't align with the current Teams behavior - the UI text says "Get email address". When a user selects "Get email address", the user has no idea whether they're setting up an email address. And if the channel doesn't already have one provisioned, Teams generates the email address without requiring any further selection or action from the user either.

2021-05-18 03:53 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +To remove a channel's provisioned email address, use the API to [remove channel email](channel-removeemail.md).
Line 22:
The second phrase should read:
"To {action} ..., use {method name}" with "method name" being the link text.
I'm making this change in the PR.

2021-05-18 03:55 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +To remove a channel's provisioned email address, use the API to [remove channel email](channel-removeemail.md).
BTW, another note - since this is the API reference, it's helpful to actually name the API (removeEmail) in the link text, instead of expressing the API in natural language ("remove channel email").

2021-05-18 04:02 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +
Line 50:
In the Response section, it's actually helpful and more scannable for customers if we keep a consistent sentence structure:
```
"... this method returns a `200 OK` response code and a [{response type}](../resources/responsetype.md) object in the response body."
```
We expect customers to click the link to the response type topic to find out further about that object. It appears to me that you want to emphasize the provisioned email address is in the **email** property, so I added it as a separate sentence.

2021-05-18 04:07 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-removeemail.md
> +You can remove an email address only if it was provisioned using the [provision channel email](channel-provisionemail.md) API or through the Microsoft Teams client.
Line 18:
I'm going to remove this sentence since this is orthogonal to the purpose of this API.
Also, the link in line 20 to the provisionEmail method provides sufficient context for more info.

2021-05-18 04:14 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-removeemail.md
> +You can remove an email address only if it was provisioned using the [provision channel email](channel-provisionemail.md) API or through the Microsoft Teams client.
Line 20:
In API reference content, it's ok to use the actual method name provisionEmail as the link text. 
Sometimes we choose to use natural language as the link text if the resultant sentence is easier to read and understand, and we don't have a goal of educating customers of the corresponding API name.
However in this case, the way that natural language is used as the link text makes the sentence read less smoothly:
```
"You can remove an email address only if it was _provisioned_ using the [_provision_ channel email](channel-provisionemail.md) API..."
```

2021-05-18 04:21 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          href: api/channel-provisionemail.md
Line 13354:
We don't include punctuation in TOC titles.
Also, FYI, it's actually not proper to apply apostrophe to a noun that is never alive (e.g., a channel).

Changing this TOC title to "Provision email".

2021-05-18 04:22 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          href: api/channel-removeemail.md
Line 13356:
Changing TOC title to "Remove email address".

2021-05-18 04:30 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>        - name: Chat
General comment for the TOC entry points under the "Channel" node:
It would be a good idea to list the 5 CRUD operations (list, create, get, update, delete), then alphabetize the remaining operations and methods. 
As is right now with a total of 22 methods under "Channel", your customers either not use the TOC, or are forced to go through them one after another until they find what they're looking for :-|

You can take a look at the experience under the "Group" node (https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta).

2021-05-18 04:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/channel.md
> +|[Remove channel email](../api/channel-removeemail.md) | None | Remove a channel's provisioned email.|
Lines 46, 47:
If we choose to represent in the left column those methods using natural language, then technically, they should read "... email address".
That is, "Provision channel email address" and "Remove channel email address".
I think that's a bit wordy.

Let's use the actual method names instead. They're shorter, reinforce learning of the corresponding APIs. The corresponding descriptions should be sufficient to disambiguate anything that's unclear.

BTW, I actually thought the stub topic generator generates the API name in the left column of the Methods table anyway. @shantanu1singh , was that the case?

2021-05-18 04:45 UTC, opbld32 commented
Docs Build status updates of commit _[4623466](https://github.com/shantanu1singh/microsoft-graph-docs/commits/4623466777693a570ed8ab5118e0f4ac5ad04fce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105180444235827-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c8bRy6TS907QsU2VZAWdIj8RLkFhbJNY4o2yyr8VykE%3D&st=2021-05-18T04%3A40%3A39Z&se=2021-06-18T04%3A45%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 04:47 UTC, opbld30 commented
Docs Build status updates of commit _[296c9a7](https://github.com/shantanu1singh/microsoft-graph-docs/commits/296c9a7b49cf3b45f2d01d301ad5d90f015f9669)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105180445146320-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rTc%2Bi6CwIaEavaRfU9oKItxQqn17TeN7topl8A8TErc%3D&st=2021-05-18T04%3A42%3A04Z&se=2021-06-18T04%3A47%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 04:58 UTC, angelgolfer-ms requested changes
Hi @shantanu1singh , I had entered a few more comments and applied the fixes directly to your PR. Please take a look at my [commit](https://github.com/microsoftgraph/microsoft-graph-docs/pull/12449/commits/4623466777693a570ed8ab5118e0f4ac5ad04fce) and let me know if I overlooked anything or if you have questions.

In addition to these fixes, I noticed that the "author" attribute is set to your GitHub name. In general, each workload specifies one Github name for all their topics, i.e., the initial author's name is not necessarily the name to use in the author attribute. In general, the author attribute is used by a bot to notify workload owners of customer Github issues. Can you confirm with your team whose name they decide to put in the author attribute?

Thanks!

2021-05-18 06:33 UTC, shantanu1singh commented on api-reference/beta/resources/provisionChannelEmailResult.md
> +Includes the email address provisioned for a [channel](../resources/channel.md) by using the [provision channel email](..\api\channel-provisionemail.md) operation.
Sure, sounds good

2021-05-18 06:35 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +To remove a channel's provisioned email address, use the API to [remove channel email](channel-removeemail.md).
Sure, sounds good

2021-05-18 06:38 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
I noticed your update here. The following text indicates that the customer should first attempt to get the email address for a channel via the User interface before they can actually call the provisionEmail method. That seems rather confusing.

> Microsoft Teams does not automatically provision an email address for a channel by default. Upon a first attempt in the user interface to get the email address, Teams generates one to enable emailing the channel. 


The intent of this API is to provide a programmatic API driven alternative to that user interface action that the user performs to provision an email address for a channel.

2021-05-18 06:39 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +
Sure

2021-05-18 06:39 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +You can remove an email address only if it was provisioned using the [provision channel email](channel-provisionemail.md) API or through the Microsoft Teams client.
Sure

2021-05-18 06:40 UTC, shantanu1singh commented on api-reference/beta/api/channel-removeemail.md
> +You can remove an email address only if it was provisioned using the [provision channel email](channel-provisionemail.md) API or through the Microsoft Teams client.
I see

2021-05-18 06:42 UTC, shantanu1singh commented on api-reference/beta/toc.yml
> +          href: api/channel-provisionemail.md
sure

2021-05-18 06:42 UTC, shantanu1singh commented on api-reference/beta/toc.yml
> +          href: api/channel-removeemail.md
sure

2021-05-18 06:51 UTC, shantanu1singh commented on api-reference/beta/toc.yml
>        - name: Chat
I see. I'll reorder and update

2021-05-18 06:52 UTC, shantanu1singh commented on api-reference/beta/resources/channel.md
> +|[Remove channel email](../api/channel-removeemail.md) | None | Remove a channel's provisioned email.|
I see. I can't remember if the tool generated the left column with the API name or not. I can check the next time I use it

2021-05-18 07:14 UTC, shantanu1singh commented
@angelgolfer-ms We've decided to keep @anandab-msft as our author. I'll update the PR to change it to his username.
I have also updated the PR to reorder the items in toc.yml

2021-05-18 07:15 UTC, opbld31 commented
Docs Build status updates of commit _[e4f088c](https://github.com/shantanu1singh/microsoft-graph-docs/commits/e4f088c61f620265493fbdb888b538a047911208)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105180714374081-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MA8USYZZkinwMwxZohaTjCvw1PGlGM%2BkVYsyBeaTLQc%3D&st=2021-05-18T07%3A10%3A52Z&se=2021-06-18T07%3A15%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 07:56 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
Hi @shantanu1singh , good point. I was distracted by the original sentence in line 18 and didn't integrate the programmatic approach and the end user approach clearly in the first two paragraphs.

```
Provision an email address for a [channel](../resources/channel.md).

Microsoft Teams does not automatically provision an email address for a channel by default. To have Teams provision an email address, you can call **provisionEmail**, or through the Teams user interface, select **Get email address**, which triggers Teams to generate an email address if none has already been provisioned.

To remove a channel's provisioned email address, use the [removeEmail](channel-removeemail.md) method.
```

2021-05-19 08:03 UTC, angelgolfer-ms commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
I'm making the above change to the channel-provisionemail.md topic. Please let me know if you have further comments.

2021-05-19 08:05 UTC, opbld30 commented
Docs Build status updates of commit _[66efb47](https://github.com/shantanu1singh/microsoft-graph-docs/commits/66efb47c8ea2ca2b96510f35893ff0a50cbccc47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105190804121549-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=54f6%2BOYZKvTXmhDTHXl%2BjK%2BSdqmgm4GOwV0ewmg%2FcsA%3D&st=2021-05-19T08%3A00%3A29Z&se=2021-06-19T08%3A05%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 08:06 UTC, opbld34 commented
Docs Build status updates of commit _[3188426](https://github.com/shantanu1singh/microsoft-graph-docs/commits/3188426dfc030101ca9852a34405770f145a88a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105190804281953-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7HhnTSAKuN18V5ljKjzGzXJ6%2FfkrY5%2Bg4CiOzsLxPBA%3D&st=2021-05-19T08%3A01%3A55Z&se=2021-06-19T08%3A06%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 08:27 UTC, angelgolfer-ms approved these changes
Content is good for publishing from my perspective. Thanks!

2021-05-19 08:33 UTC, angelgolfer-ms commented
> Content is good for publishing from my perspective. Thanks!

@shantanu1singh , I'll let you follow up separately on ordering the children topics of the "channel" node in the v1 TOC. Would be a better experience for customers.

2021-05-19 09:07 UTC, opbld31 commented
Docs Build status updates of commit _[5f2e39e](https://github.com/shantanu1singh/microsoft-graph-docs/commits/5f2e39e70faf539a380dc2643349bf04521fdef5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12449) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105190906411616-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r40%2Bs4uEMYMy6%2FD7PfcTD8vKBylj7uh7ycIxZ9WkTjA%3D&st=2021-05-19T09%3A02%3A53Z&se=2021-06-19T09%3A07%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 09:08 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
@angelgolfer-ms , this is much better but I'm still not sure if it's clear enough to the reader as to where they might find the **Get email address** button.

The reader would need to click on the ellipsis next to a channel to be able to view the pop up where they can select that option. Can we capture that here too?

2021-05-19 09:09 UTC, shantanu1singh commented
@angelgolfer-ms I have re-ordered the v1 toc.yml and also updated the /beta toc.yml to include that 'Update message' API as it was missing. I found it in v1 so I thought I'll add it to beta too

2021-06-04 11:25 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
@angelgolfer-ms can you please help answer my question below?

> @angelgolfer-ms , this is much better but I'm still not sure if it's clear enough to the reader as to where they might find the Get email address button.
> 
> The reader would need to click on the ellipsis next to a channel to be able to view the pop up where they can select that option. Can we capture that here too?

2021-06-04 11:26 UTC, shantanu1singh commented
@isvargasmsft Your status on this PR shows as 'requested changes'. Can you please change your status if the PR looks good to you? Thanks!

2021-06-04 15:25 UTC, isvargasmsft approved these changes

2021-06-07 05:20 UTC, shantanu1singh commented on api-reference/beta/api/channel-provisionemail.md
> +In Microsoft Teams, users can set up a *system generated* email address for a channel that can be used to send messages to a channel via the email address.
@isvargasmsft can you please help me get this item resolved?

2021-06-07 13:20 UTC, opbld30 commented
Docs Build status updates of commit _[71c04e2](https://github.com/shantanu1singh/microsoft-graph-docs/commits/71c04e243a057f49ee6af91d9aad3203029a7e99)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12449) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-0c156b94)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-0c156b94"></a>
### [api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml)
 - **Line 1451, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1455, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2061, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2110, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2160, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3057, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3308, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-mam-conceptual.md'.`````
 - **Line 3636, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-onboarding-conceptual.md'.`````
 - **Line 3942, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-shared-conceptual.md'.`````
 - **Line 3971, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-tem-conceptual.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071318465919-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HonKw9e3Rjv208hciFmmr%2Fjo4CEfIpoUaCeofB5L22Y%3D&st=2021-06-07T13%3A15%3A19Z&se=2021-07-08T13%3A20%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 01:27 UTC, Lauragra commented on api-reference/beta/api/channel-provisionemail.md
> +#### Request
Global: Please follow sequential heading order and make the Request and Response sections H3s (###).

2021-06-08 01:30 UTC, opbld34 commented
Docs Build status updates of commit _[0680bcb](https://github.com/shantanu1singh/microsoft-graph-docs/commits/0680bcb9be9c73ad8a82116ea69e7020efbb4703)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12449) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d534a7fd)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-d534a7fd"></a>
### [api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml)
 - **Line 1451, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1455, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2061, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2110, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2160, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3057, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3308, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-mam-conceptual.md'.`````
 - **Line 3636, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-onboarding-conceptual.md'.`````
 - **Line 3942, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-shared-conceptual.md'.`````
 - **Line 3971, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-tem-conceptual.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106080129054663-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2xQysjJwxZaKGQEqSFEaaAphVPXKf%2FUiSLckvc8Ekus%3D&st=2021-06-08T01%3A25%3A38Z&se=2021-07-09T01%3A30%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 01:32 UTC, opbld31 commented
Docs Build status updates of commit _[0680bcb](https://github.com/shantanu1singh/microsoft-graph-docs/commits/0680bcb9be9c73ad8a82116ea69e7020efbb4703)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12449) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-6ec8b1fb)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-6ec8b1fb"></a>
### [api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml)
 - **Line 1451, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1455, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2061, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2110, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2160, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3057, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3308, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-mam-conceptual.md'.`````
 - **Line 3636, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-onboarding-conceptual.md'.`````
 - **Line 3942, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-shared-conceptual.md'.`````
 - **Line 3971, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-tem-conceptual.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106080129161523-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M8jcCPHq0kOpa9ZVd8e77Km1gG2SBVLntZ2tq0n6OPA%3D&st=2021-06-08T01%3A27%3A14Z&se=2021-07-09T01%3A32%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 01:33 UTC, opbld33 commented
Docs Build status updates of commit _[de89c23](https://github.com/shantanu1singh/microsoft-graph-docs/commits/de89c231f2936ae2a4e4c36d1c8e9d311b5fdaa4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12449) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-da4a0ef7)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-da4a0ef7"></a>
### [api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml)
 - **Line 1451, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1455, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2061, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2110, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2160, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3057, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3308, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-mam-conceptual.md'.`````
 - **Line 3636, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-onboarding-conceptual.md'.`````
 - **Line 3942, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-shared-conceptual.md'.`````
 - **Line 3971, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-tem-conceptual.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106080130261974-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1FgYWCQLt%2F7l%2BnwSVnzOCMjsoA%2BmHU125AaHSLhzwP0%3D&st=2021-06-08T01%3A28%3A48Z&se=2021-07-09T01%3A33%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 01:35 UTC, opbld31 commented
Docs Build status updates of commit _[8e889de](https://github.com/shantanu1singh/microsoft-graph-docs/commits/8e889dee54e5231bc7875cae39be0be98f16d225)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12449) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-c2270cbe)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionchannelemailresult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionchannelemailresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-c2270cbe"></a>
### [api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml)
 - **Line 1451, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1455, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2061, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2110, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2160, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3057, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3308, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-mam-conceptual.md'.`````
 - **Line 3636, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-onboarding-conceptual.md'.`````
 - **Line 3942, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-shared-conceptual.md'.`````
 - **Line 3971, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-tem-conceptual.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106080131549171-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8PTvUvGn88ZSEekmrMmoZLs8O1Y5UKW2Car2%2BPhN3wM%3D&st=2021-06-08T01%3A30%3A21Z&se=2021-07-09T01%3A35%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 01:36 UTC, merged

2021-06-08 01:36 UTC, opbld32 commented
Docs Build status updates of commit _[60733e6](https://github.com/shantanu1singh/microsoft-graph-docs/commits/60733e6e94bf73500d91a97086050e0593d54fb1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12449) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-00efa59c)
[api-reference/beta/api/channel-provisionemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-provisionemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/api/channel-removeemail.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/api/channel-removeemail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-removeemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/resources/provisionChannelEmailResult.md](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/resources/provisionChannelEmailResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/provisionchannelemailresult?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-provisionemail?view=graph-rest-beta&branch=pr-en-us-12449) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-00efa59c"></a>
### [api-reference/v1.0/toc.yml](https://github.com/shantanu1singh/microsoft-graph-docs/blob/shantanu1singh/channelemail/api-reference/v1.0/toc.yml)
 - **Line 1451, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1455, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2061, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2110, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2160, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3057, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3308, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-mam-conceptual.md'.`````
 - **Line 3636, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-onboarding-conceptual.md'.`````
 - **Line 3942, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-shared-conceptual.md'.`````
 - **Line 3971, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-tem-conceptual.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106080129428968-12449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8ITC2oP0giLkeBAx5k7Dc4tVqkUVgpMwffL5lEHb1%2Bw%3D&st=2021-06-08T01%3A31%3A56Z&se=2021-07-09T01%3A36%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>