accessReviewScheduleDefinition docs refresh
microsoftgraph/microsoft-graph-docs pull request #12447
Opened 2021-04-23 09:39 UTC by FaithOmbongi

2021-04-23 09:40 UTC, opbld30 commented
Docs Build status updates of commit _[09b6d5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09b6d5cd17112bd1e8de37be304fe6a76d25833f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :x:Error | | [Details](#user-content-32d8fad90bdc6c244bc059254ffa5b26-a9cb8566)
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :x:Error | | [Details](#user-content-f6520df0844c6aa340c79b43d533fa6d-a9cb8566)

<a id="32d8fad90bdc6c244bc059254ffa5b26-a9cb8566"></a>
### [concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md)
 - **Line 10, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/beta-disclaimer.md'.`````

<a id="f6520df0844c6aa340c79b43d533fa6d-a9cb8566"></a>
### [concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md)
 - **Line 10, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../../includes/beta-disclaimer.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230939175672-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rk6IQHqDK%2Bw9Y4Rt6sjen6QkcjkJd4R5A%2B6IKQxOBxo%3D&st=2021-04-23T09%3A35%3A17Z&se=2021-05-24T09%3A40%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 15:47 UTC, opbld32 commented
Docs Build status updates of commit _[951c12a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/951c12a02f84094a25484e8d9dc7a15438403959)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104231545159483-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zPWcGsJt3SRen0o1Yeem4S%2BtnRITkuy6loJr3voD2us%3D&st=2021-04-23T15%3A42%3A37Z&se=2021-05-24T15%3A47%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-26 21:50 UTC, isabelleatmsft reviewed
this is SO GOOD!!

2021-04-26 21:50 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +|`roleAssignmentScheduleInstances`  |List every accessReviewScheduleDefinition for service principals assigned to privileged role.|Example|
im not sure if the roleAssignmentScheduleInstances definition is correct - is it just reviews of SPs assigned to privileged roles, or is it all reviews of any scope assigned to privileged roles?

2021-04-26 21:50 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +Azure AD [access reviews APIs](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access to your Azure AD resources. This can be a
This can be all users, a set of users (for example, guest users only), as well as service principals and groups with access to Azure AD resources.

2021-04-26 21:50 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +|[accessReviewQueryScope](/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&preserve-view=true)|Best applicable when reviewing the full set or subset of principals who have access to a
Last one: User and service principal access to Entitlement Management access packages

2021-04-26 21:50 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +### Example 1: Review access of all users to a service principal
i didnt even know we offered this!

2021-04-27 10:00 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +## Example 1: Create an access review on a security group
Sounds good. Let's take this up internally.

2021-04-27 17:47 UTC, opbld34 commented
Docs Build status updates of commit _[adfd50e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adfd50eb71136c7b5ecc9050165ef48c2b965211)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) | [Details](#user-content-f6520df0844c6aa340c79b43d533fa6d-e7bbd4ed)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |

<a id="f6520df0844c6aa340c79b43d533fa6d-e7bbd4ed"></a>
### [concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md)
 - **Line 81, Column 240**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviews-scope-concept'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271745431329-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BJ505vc0%2F7xm48kf%2BNrLlamG5%2Fe0J8n1FIssiscN%2Bsg%3D&st=2021-04-27T17%3A42%3A00Z&se=2021-05-28T17%3A47%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 18:03 UTC, opbld33 commented
Docs Build status updates of commit _[0a3a8dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a3a8ddb91ddf5733fd006ee332595212084e870)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271802149327-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hjKnye%2F%2ByS6gwXPD8XOlAxX%2BJMfwpKviWfyYxN5E3E8%3D&st=2021-04-27T17%3A58%3A27Z&se=2021-05-28T18%3A03%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 18:46 UTC, opbld31 commented
Docs Build status updates of commit _[309e441](https://github.com/microsoftgraph/microsoft-graph-docs/commits/309e4412256a2fad6b3b4c0e4d7c87c6e5477b2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271844484075-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hoE%2BDRLPpPMvZHcqA76yPl59QVvgO%2BgVlZ3xtgTNIV4%3D&st=2021-04-27T18%3A41%3A14Z&se=2021-05-28T18%3A46%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 17:09 UTC, opbld30 commented
Docs Build status updates of commit _[784ae96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/784ae9613d41c60c2de4382609ad8006e5079c8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104281707041220-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iI5496HmlYVMiY0Ram0ruoZD%2Fjw5WxVv1nnNCGBqxaA%3D&st=2021-04-28T17%3A04%3A27Z&se=2021-05-29T17%3A09%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 19:31 UTC, opbld34 commented
Docs Build status updates of commit _[d81cba7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d81cba7604422bea3f4f2043e160fae948fad61d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105041930179108-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BRkdNCGp2i7V1c3C0Ra8p%2FMsHQ14TaFsAcgWPQheaBc%3D&st=2021-05-04T19%3A26%3A31Z&se=2021-06-04T19%3A31%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 19:42 UTC, opbld34 commented
Docs Build status updates of commit _[85f5a90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85f5a90450f5a32d1c0ee98b498cb85bca3fb774)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105041940582838-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XKxAyZVVLmP%2Fo8OVEBKMqAHdpw%2BsmmdUayn2jAGKDYo%3D&st=2021-05-04T19%3A37%3A35Z&se=2021-06-04T19%3A42%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 07:16 UTC, opbld34 commented
Docs Build status updates of commit _[4d173e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d173e53a529f4ee9118b6d3061f5aec00aed1a0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c61a41fa)

<a id="c61a41fa"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105050716023091-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WfecCgkT7vmvGlJkhJImt6eZXeIbibbJ31buFDa23BY%3D&st=2021-05-05T07%3A11%3A18Z&se=2021-06-05T07%3A16%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 07:18 UTC, opbld30 commented
Docs Build status updates of commit _[fbf4b5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbf4b5daeab67c22964a481e3afeb7ef23d2931b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105050717274228-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lOxNE5pBnP07jMJ0eEwQNJFgvBKp8CLHAMDW7AOnAyY%3D&st=2021-05-05T07%3A13%3A58Z&se=2021-06-05T07%3A18%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 14:40 UTC, opbld32 commented
Docs Build status updates of commit _[738ace4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/738ace4fbf31c8670c46fce1d2fc890f5e124301)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) | [Details](#user-content-56fb30546863b8208b03a9b061658fed-09c8ce21)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

<a id="56fb30546863b8208b03a9b061658fed-09c8ce21"></a>
### [api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md)
 - **Line 20, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'removeAccessApplyAction.md'.`````
 - **Line 22, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'disableAndDeleteUserApplyAction.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105061439138603-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kc6XEIeXjshIaQHOLrlLIlyo1kaLUExfZbhjv4B%2FeB0%3D&st=2021-05-06T14%3A35%3A32Z&se=2021-06-06T14%3A40%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-bra [...]

2021-05-06 14:45 UTC, opbld31 commented
Docs Build status updates of commit _[2d8a4bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d8a4bcb621e799cfa6503a581ad22ddd5040674)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableAndDeleteUserApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableAndDeleteUserApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeAccessApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeAccessApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105061444285745-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Sf6lgsWYXBP760rerOJVBbEoRVFJbYZCwSK0H%2F2U49I%3D&st=2021-05-06T14%3A40%3A41Z&se=2021-06-06T14%3A45%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 19:45 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> -## Examples
This should stay in the page.

2021-05-06 19:45 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +## Example 1: Create an access review on a group
This should be an H3.

2021-05-06 19:45 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +## Example 2: Create an access review on all teams with inactive guest users
This should be an H3.

2021-05-06 19:48 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
Response heading should be an H4.

2021-05-06 19:48 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +### Request
Should be an H4.

2021-05-06 19:49 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +### Response
Should be an H4.

2021-05-06 19:49 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +## Example 3: Create an access review of all users to a service principal
Should be an H3.

2021-05-06 19:49 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +### Request
Should be an H4.

2021-05-06 19:49 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +### Response
Should be an H4.

2021-05-06 19:51 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> + The signed-in user must also be in a directory role that permits them to read an access review. See access review [role and application permission authorization checks](../resources/accessreviewsv2-
```suggestion
 The signed-in user must also be in a directory role that permits them to read an access review. See access review [role and application permission authorization checks](../resources/accessreviewsv2-root.md#role-and-application-permission-authorization-checks).
```

2021-05-06 19:51 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +The `$filter` query parameter with the `contains` operator is supported on the **scope** property of accessReviewScheduleDefinition. The request statement will take on the following format:
```suggestion
The `$filter` query parameter with the `contains` operator is supported on the **scope** property of accessReviewScheduleDefinition. Use the following format for the request:
```

2021-05-06 19:52 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +where the value of `{object}` can be one of the following:
```suggestion
The value of `{object}` can be one of the following:
```

2021-05-06 19:52 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +|Value of {object}|Description|
```suggestion
|Value|Description|
```

2021-05-06 19:53 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +Note that `$filter` is currently not supported on **accessReviewInactiveUserQueryScope** or **principalResourceMembershipScope**.
```suggestion
The `$filter` query parameter is not supported on **accessReviewInactiveUserQueryScope** or **principalResourceMembershipScope**.
```

2021-05-06 19:54 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> -## Examples
The examples heading should not be removed.

2021-05-06 19:54 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +## Example 1: List the first one hundred access review definitions
Should be an H3.

2021-05-06 19:54 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
>  ### Request
Should be an H4.

2021-05-06 19:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
>  ### Response
Should be an H4.

2021-05-06 19:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +## Example 2: Retrieve all access review definitions scoped to all Microsoft 365 groups in the tenant
Should be an H3.

2021-05-06 19:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +### Request
Should be an H4.

2021-05-06 19:55 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-list.md
> +### Response
Should be an H4.

2021-05-06 19:56 UTC, davidmu1 commented on api-reference/beta/api/accessreviewscheduledefinition-update.md
> +Note that a **PUT** request expects the full object to be passed in, in which all writable properties are included, not just the properties being updated.
```suggestion
A **PUT** request expects the full object to be passed in, which includes all writable properties, not just the properties being updated.
```

2021-05-06 20:00 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +The accessReviewReviewerScope defines who will review instances of an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md). This is expressed as an OData query, which allows reviewers
```suggestion
The accessReviewReviewerScope defines who will review instances of an [accessReviewScheduleDefinition](accessreviewscheduledefinition.md). An OData query that allows reviewers to be specified both as a static list of users (specific users, group owners, and group members) or dynamically in which every user is reviewed by their manager. To create a self-review, do not provide reviewers on [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) creation.
```

2021-05-06 20:01 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewreviewerscope.md
> +| queryRoot | String | In the scenario where reviewers need to be specified dynamically, this property is used to indicate the relative source of the query. This property is only required if a relati
```suggestion
| queryRoot | String | In the scenario where reviewers need to be specified dynamically, this property is used to indicate the relative source of the query. This property is only required if a relative query, for example,  `./manager` or `./owners` is specified. Possible value: `decisions`. |
```

2021-05-06 20:02 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +An accessReviewScheduleDefinition contains a list of [accessReviewInstance](accessreviewinstance.md) objects. Each recurrence of the schedule definition will create an instance. Instances also repres
```suggestion
An accessReviewScheduleDefinition contains a list of [accessReviewInstance](accessreviewinstance.md) objects. Each recurrence of the schedule definition creates an instance. Instances also represent each unique resource being reviewed. If a schedule definition reviews multiple resources (including multiple groups), each resource has a unique instance per each recurrence. In the case of a one-time review, only one instance is created per resource.
```

2021-05-06 20:04 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewscheduledefinition.md
> +| instances |[accessReviewInstance](../resources/accessreviewinstance.md) collection|  Set of access reviews instances for this access review series. Access reviews that do not recur will only have o
```suggestion
| instances |[accessReviewInstance](../resources/accessreviewinstance.md) collection|  Set of access reviews instances for this access review series. Access reviews that do not recur only have one instance; otherwise, there is an instance for each recurrence. |
```

2021-05-06 20:05 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| mailNotificationsEnabled|Boolean | Flag to indicate whether emails are enabled/disabled. Default value is `false`.               |
```suggestion
| mailNotificationsEnabled|Boolean | Indicates whether emails are enabled or disabled. Default value is `false`.               |
```

2021-05-06 20:05 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| reminderNotificationsEnabled|Boolean  | Flag to indicate whether reminders are enabled/disabled. Default value is `false`.  |
```suggestion
| reminderNotificationsEnabled|Boolean  | Indicates whether reminders are enabled or disabled. Default value is `false`.  |
```

2021-05-06 20:05 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| justificationRequiredOnApproval|Boolean | Flag to indicate whether reviewers are required to provide justification with their decision. Default value is `false`. |
```suggestion
| justificationRequiredOnApproval|Boolean | Indicates whether reviewers are required to provide justification with their decision. Default value is `false`. |
```

2021-05-06 20:06 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| defaultDecisionEnabled|Boolean | Flag to indicate whether default decision is enabled/disabled when reviewers do not respond. Default value is `false`. |
```suggestion
| defaultDecisionEnabled|Boolean | Indicates whether the default decision is enabled or disabled when reviewers do not respond. Default value is `false`. |
```

2021-05-06 20:07 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| recurrence|[patternedRecurrence](../resources/patternedrecurrence.md) | Detailed settings for recurrence using standard Outlook recurrence object. Note that only `weekly` and `absoluteMonthly` on *
```suggestion
| recurrence|[patternedRecurrence](../resources/patternedrecurrence.md) | Detailed settings for recurrence using the standard Outlook recurrence object. Only `weekly` and `absoluteMonthly` on **recurrencePattern** are supported. Use the property **startDate** on **recurrenceRange** to determine the day the review starts. |
```

2021-05-06 20:08 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| autoApplyDecisionsEnabled|Boolean | Flag to indicate whether auto-apply feature is enabled. When set to `false`, a user must apply the decisions manually once the reviewer completes the access revi
```suggestion
| autoApplyDecisionsEnabled|Boolean | Indicates whether the **auto-apply** feature is enabled. When set to `false`, a user must apply the decisions manually after the reviewer completes the access review. When set to `true`, decisions are applied automatically after the reviewer completes the access review. Default value is `false`. |
```

2021-05-06 20:09 UTC, davidmu1 commented on api-reference/beta/resources/disableAndDeleteUserApplyAction.md
> +description: "Disable and delete is a complex type of accessReviewApplyAction that indicates disabling any B2B guest user who is denied in an access review for 30 days, then subsequently deleting the
```suggestion
description: "Disable and delete any B2B guest user who is denied in an access review."
```

2021-05-06 20:10 UTC, davidmu1 commented on api-reference/beta/resources/disableAndDeleteUserApplyAction.md
> +Disable and delete is a complex type of [accessReviewApplyAction](accessreviewapplyaction.md) that indicates disabling any B2B guest user who is denied in an access review for 30 days, then subsequen
```suggestion
Disable any B2B guest user who is denied in an access review for 30 days, and then subsequently delete their account. 
```

2021-05-06 20:11 UTC, davidmu1 commented on api-reference/beta/resources/removeAccessApplyAction.md
> +description: "Type of accessReviewApplyAction that indicates removing access to a resource of those denied in an access review of that resource."
```suggestion
description: "Indicates that access is removed from a resource for those denied in an access review of that resource."
```

2021-05-06 20:13 UTC, davidmu1 commented on api-reference/beta/resources/removeAccessApplyAction.md
> +removeAccessApplyAction is a kind of [accessReviewApplyAction](../resources/accessreviewapplyaction.md) that indicates removing access to a resource of those denied in an access review of that resour
```suggestion
Remove access to a resource of those denied in an access review of that resource. This is the default option chosen for [accessReviewApplyAction](../resources/accessreviewapplyaction.md) if an option is not passed in.
```

2021-05-06 20:14 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +localization_priority: Normal
Missing ms.prod and doc_type.

2021-05-06 20:15 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +Note that this property is not required when creating a self-review (where users review their own access).
```suggestion
This property is not required when a self-review (where users review their own access) is created.
```

2021-05-06 20:15 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +### Use accessReviewReviewerScope to configure reviewers
```suggestion
### Configure reviewers
```

2021-05-06 20:17 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +To configure the reviewers and/or fallback reviewers, set the values of **query**, **queryRoot**, and **queryType** properties of accessReviewReviewerScope. [See the accessReviewReviewerScope](/graph
```suggestion
To configure the reviewers and fallback reviewers, set the values of **query**, **queryRoot**, and **queryType** properties of an [accessReviewReviewerScope](/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&preserve-view=true) resource.
```

2021-05-06 20:18 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +
Missing an ## Examples heading

2021-05-06 20:18 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +Example configurations of the **reviewers** or **backupReviewers** property using the accessReviewReviewerScope include the following:
```suggestion
Example configurations of the **reviewers** or **backupReviewers** property using the accessReviewReviewerScope.
```

2021-05-06 20:18 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +#### Example 1: A specific user as the reviewer
Should be an H3.

2021-05-06 20:20 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +### Use accessReviewReviewerScope to configure reviewers
Should be an H2.

2021-05-06 20:20 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +#### Example 1: A specific user as the reviewer
Should be an H3.

2021-05-06 20:20 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +#### Example 2: Members of a group as reviewers
Should be an H3.

2021-05-06 20:21 UTC, davidmu1 commented on concepts/accessreviews-reviewers-concept.md
> +#### Example 3: Group owners as reviewers
Should be an H3.

2021-05-06 20:21 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +### Use accessReviewQueryScope to configure scope
Should be an H2.

2021-05-06 20:22 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 2: Review guest users assigned to a group
Should be an H3.

2021-05-06 20:22 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 3: Review guest users assigned to all groups
Should be an H3.

2021-05-06 20:22 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 5: Review access of all inactive guest users to all groups
Should be an H3.

2021-05-06 20:23 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 6: Review of all inactive guest users assigned to all teams
Should be an H3.

2021-05-06 20:23 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 7: Review of Entitlement Management access package assignment
Should be an H3.

2021-05-06 20:23 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 8: Review of service principals assigned to privileged roles
Should be an H3.

2021-05-06 20:24 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +### Use principalResourceMembershipsScope to configure scope
Should be an H2.

2021-05-06 20:24 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 1: Review access of all inactive guest users to a service principal
Should be an H3.

2021-05-06 20:24 UTC, davidmu1 commented on concepts/accessreviews-scope-concept.md
> +#### Example 2: Review access of all guest users to a directory role
Should be an H3.

2021-05-07 08:25 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +#### Example 1: Review access of all inactive guest users to a service principal
Added the "Examples" H3 for consistency with reviewers conceptual article. I'll have to retain these as H4s.

2021-05-07 08:40 UTC, opbld33 commented
Docs Build status updates of commit _[b36a22d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b36a22dd06ecdd51ee584fe98133c0a184a6f6ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableAndDeleteUserApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableAndDeleteUserApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeAccessApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeAccessApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105070838207296-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=47QY1uh0ge0kLyaF4Tt%2FK8MSAohuirzNBEpHrl4S9%2FY%3D&st=2021-05-07T08%3A35%3A47Z&se=2021-06-07T08%3A40%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-07 09:05 UTC, opbld32 commented
Docs Build status updates of commit _[648defe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/648defe930152470999ca1abd534c1e802597f9d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableAndDeleteUserApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableAndDeleteUserApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeAccessApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeAccessApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105070904054682-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8ml3senC8rdpT%2F1HsJ%2Fcd3YzoWXvc%2BJOGdD5ppIeJYI%3D&st=2021-05-07T09%3A00%3A34Z&se=2021-06-07T09%3A05%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-09 01:01 UTC, isabelleatmsft requested changes
This is so, so, so much better than the docs I originally wrote. Thank you so much for these valuable improvements! I have some small comments to get to before merging, but overall looks great.

2021-05-09 01:01 UTC, isabelleatmsft commented on concepts/accessreviews-scope-concept.md
> +#### Example 1: Review access of all inactive guest users to a service principal
use "to an application" instead of "to a service principal" - we use "application" on the UX of this feature for this scenario

2021-05-12 07:50 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +"scope": {
@shubhamguptacal Could you validate this scope?

2021-05-12 18:19 UTC, davidmu1 approved these changes

2021-05-12 18:39 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewscheduledefinition-create.md
> +  "id": "b0966e21-a01e-43c9-8f8b-9ba30ed5710a",
Yes, to shorten the page. The customer is notified of this via the truncation note. However, I've included the full response object for Example 2, but shortened Example 3 since most properties have similar values.

2021-05-12 18:56 UTC, opbld33 commented
Docs Build status updates of commit _[f9109fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9109fddebcb7ab2aa7e3a28b743b11b3245f4d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableAndDeleteUserApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableAndDeleteUserApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeAccessApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeAccessApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105121854030673-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j7aXmPN3mcBvJX4eLqKEQB71gJYuJTRuSAkPnm1KzXY%3D&st=2021-05-12T18%3A51%3A22Z&se=2021-06-12T18%3A56%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build repo [...]

2021-05-12 19:21 UTC, opbld31 commented
Docs Build status updates of commit _[4a0194f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a0194f5f495c1652a29be5ca649f7e3703f8ad5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableAndDeleteUserApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableAndDeleteUserApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeAccessApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeAccessApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105121920205542-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SxrxFdWsS7%2BjRbEg%2FZ%2FkrHjU3Nh7h9h6WlHhg2LiMvs%3D&st=2021-05-12T19%3A16%3A43Z&se=2021-06-12T19%3A21%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above buil [...]

2021-05-13 18:58 UTC, isabelleatmsft approved these changes

2021-05-13 19:00 UTC, shubhamguptacal commented on concepts/accessreviews-scope-concept.md
> +"scope": {
This scope is not correct. This example : "Example 4 : Review guest users assigned to all Microsoft 365 groups" is correct. Please remove Example 3

2021-05-13 19:14 UTC, opbld31 commented
Docs Build status updates of commit _[89c2f15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89c2f15178a089e59848b64ed7e7f3c51d9ac90b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableAndDeleteUserApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableAndDeleteUserApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeAccessApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeAccessApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105131912408691-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IdeA4T%2B6k%2BUJPXZ9263E1l0zEZfSCgem2INaxANl8xw%3D&st=2021-05-13T19%3A09%3A02Z&se=2021-06-13T19%3A14%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build  [...]

2021-05-14 01:28 UTC, opbld34 commented
Docs Build status updates of commit _[5c2a320](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c2a320983b406f7a881c361c1f702e94fc5041f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableanddeleteuserapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableanddeleteuserapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeAccessApplyAction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeAccessApplyAction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105140127107746-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DpyEGjhaIcQ%2FO1hYEKI9zhJo7fVBnrW106HcjHbC8Z4%3D&st=2021-05-14T01%3A23%3A30Z&se=2021-06-14T01%3A28%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build re [...]

2021-05-14 01:28 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +title: "Assign reviewers to your access review definition"
Do you want these two new articles to be included in the concept TOC?

2021-05-14 01:30 UTC, opbld33 commented
Docs Build status updates of commit _[3f7af36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f7af36af88ddb8f30afebb6c506ace6a7f2e559)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableanddeleteuserapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableanddeleteuserapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeaccessapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105140129023890-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TouuvKODsz7XRj1vbSLWsnoU3dK3K3JmRfu4IFgw8Ws%3D&st=2021-05-14T01%3A25%3A20Z&se=2021-06-14T01%3A30%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build repo [...]

2021-05-14 01:31 UTC, opbld31 commented
Docs Build status updates of commit _[3f7af36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f7af36af88ddb8f30afebb6c506ace6a7f2e559)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableanddeleteuserapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableanddeleteuserapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeaccessapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[concepts/accessreviews-reviewers-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-reviewers-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-reviewers-concept?branch=pr-en-us-12447) |
[concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/concepts/accessreviews-scope-concept.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-scope-concept?branch=pr-en-us-12447) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105140129123538-12447%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MwxwGvHFzLKTcODgRWKJaS30j3uj3j5PLgL9%2Felg07E%3D&st=2021-05-14T01%3A26%3A52Z&se=2021-06-14T01%3A31%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build re [...]

2021-05-14 03:34 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +# Assign reviewers to your access review definition
The title and H1 should include important keywords for SEO, so you might want to add "using the Microsoft Graph access review API".

2021-05-14 03:36 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +description: "Use the reviewers property of accessReviewsScheduleDefinition to assign reviewers of your access review."
It might be better to make this description more high level - "Learn how to use the access reviews API in Microsoft Graph to assign access reviewers."

2021-05-14 03:40 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +Azure AD [access reviews APIs](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access to your Azure AD resources. This can be a
We can refer to it as an API, so revise as: "The Azure AD access reviews API allows you to...". I'm not clear about the meaning of the second sentence. What does "This" refer to? Azure AD resources? Or the types of users who can be assigned as reviewers? In the first sentence, is "programmatically review access" what you intend to say or is it "programmatically assign access reviewers" as the title implies?

2021-05-14 03:41 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +> The [access reviews APIs](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) are currently available in only the Microsoft Graph beta endpoint. Do not use them in pr
Revise as "access reviews API is".

2021-05-14 03:42 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +The primary reviewers are configured in the **reviewers** property of the access reviews [accessReviewScheduleDefinition](/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&pres
Is it important to call out the type for the two properties? The construction in both sentences is awkward.

2021-05-14 03:43 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +This property is not required when a self-review (where users review their own access) is created.
Which property are you referring to here - reviewers, or fallbackReviewers?

2021-05-14 03:44 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +Example configurations of the **reviewers** or **fallbackReviewers** property using the accessReviewReviewerScope include the following:
We don't introduce headings with a colon. I would remove this sentence because the Examples heading already makes that clear.

2021-05-14 03:47 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +### Examples
You can streamline this by removing this H3 and making each example an H3.

2021-05-14 03:48 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +#### Example 4: People managers as the reviewers
Remove "the" here.

2021-05-14 03:48 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +
Do you need to provide response examples?

2021-05-14 03:49 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +Azure AD [access reviews APIs](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access to your Azure AD resources. This can be a
Please make the same edits here as mentioned in the previous concept topic.

2021-05-14 03:49 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +# Configure the scope of your access review definition
Update the title to add "using the Microsoft Graph access reviews API"

2021-05-14 03:50 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +### Examples
Remove the H3 and elevate the H3s to H4s.

2021-05-14 03:50 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +Example configurations of the **scope** property using the accessReviewQueryScope include the following:
Remove introductory text.

2021-05-14 03:52 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +Example configurations of the **scope** property using **principalResourceMembershipsScope** include the following:
Remove

2021-05-14 03:52 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +### Examples
Remove

2021-05-14 03:52 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +```
Do you need to add the response examples?

2021-05-17 18:51 UTC, FaithOmbongi commented on concepts/accessreviews-reviewers-concept.md
> +title: "Assign reviewers to your access review definition"
No. They are not tutorials, just how-to like articles for the configuration of the 2 properties.

2021-05-17 18:51 UTC, FaithOmbongi commented on concepts/accessreviews-reviewers-concept.md
> +Azure AD [access reviews APIs](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access to your Azure AD resources. This can be a
This sentence is intended as a HL overview of the access reviews API. The intent of the 1st sentence is ""programmatically review access". I've reworded the sentence, kindly review.

_The Azure AD access reviews API allow you to programmatically review access—of all users, a set of users (for example, guest users only), as well as service principals and groups—to your Azure AD resources._

2021-05-17 18:51 UTC, FaithOmbongi commented on concepts/accessreviews-reviewers-concept.md
> +This property is not required when a self-review (where users review their own access) is created.
Both, reworded.

2021-05-17 18:51 UTC, FaithOmbongi commented on concepts/accessreviews-reviewers-concept.md
> +The primary reviewers are configured in the **reviewers** property of the access reviews [accessReviewScheduleDefinition](/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&pres
Reworded, since I reference the type in the H2 section that follows.

2021-05-17 18:51 UTC, FaithOmbongi commented on concepts/accessreviews-reviewers-concept.md
> +
Not in this article which focuses only on the configuration of this property (though the request & response are similar). In the POST API doc, we've added a full example that uses this configuration.

2021-05-17 18:51 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +Azure AD [access reviews APIs](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access to your Azure AD resources. This can be a
Similar changes are previous concept topic. Kindly review.

2021-05-17 18:51 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +```
Not in this article which focuses only on the configuration of this property (though the request & response are similar).

2021-05-17 19:13 UTC, opbld32 commented
Docs Build status updates of commit _[90ddf67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90ddf671c9fca036967afd583f4cfb41ba9f0a1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/includes/accessreviews-disclaimer-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/includes/accessreviews-disclaimer-v2.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) | [Details](#user-content-f2e7b1d8beb0d97aa75dfa69987a9c21-59f5a02e)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreview?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableanddeleteuserapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableanddeleteuserapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeaccessapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefi [...]

2021-05-17 19:16 UTC, opbld33 commented
Docs Build status updates of commit _[81a865d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81a865dbf2d2268f7d76fe5f0573db508825981b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreview?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableanddeleteuserapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableanddeleteuserapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeaccessapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/includes/accessreviews-disclaimer-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/includes/accessreviews-disclaimer-v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) ( [...]

2021-05-18 01:37 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +title: "Assign reviewers to your access review definition"
How will users discover them if they aren't in the TOC? Generally we do expose How to articles in the TOC.

2021-05-18 01:38 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +title: "Assign reviewers to your access review definition"
The title field should match the H1 title. You'll want to make sure that the meta title includes all the important keywords because it's used for search.

2021-05-18 01:44 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +The Azure AD [access reviews API](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access—of all users, a set of users (for exam
This sentence still is not clear. Is it trying to say that the APIs "allows you to programmatically review the access that all users, a set of users, and service principals and groups have to your Azure AD resources." ?

2021-05-18 01:44 UTC, opbld34 commented
Docs Build status updates of commit _[bde845c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bde845c78c239472ed33784194b788181cdb8c6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreview?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableanddeleteuserapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableanddeleteuserapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeaccessapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/includes/accessreviews-disclaimer-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/includes/accessreviews-disclaimer-v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) ( [...]

2021-05-18 01:44 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +> The [access reviews API](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) are currently available in only the Microsoft Graph beta endpoint. Do not use them in pro
Change "are" to "is" because we made API singular.

2021-05-18 01:45 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +The primary reviewers are configured in the **reviewers** property of the access reviews [accessReviewScheduleDefinition](/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&pres
To help readability for global readers, please change "using" to "by using". This removes potential ambiguity.

2021-05-18 01:48 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +To configure the reviewers and fallback reviewers, set the values of **query**, **queryRoot**, and **queryType** properties of **accessReviewReviewerScope**. [See the accessReviewReviewerScope](/grap
Global: For cross-references, always tell them what the information is before providing the link; otherwise they potentially click away without getting the full context. So it should be "For descriptions of these properties, see [accessReviewReviewerScope]." Also note that the link text should just be the resource name/title that you're linking to, not the verb.

2021-05-18 01:50 UTC, Lauragra commented on concepts/accessreviews-reviewers-concept.md
> +To specify only a specific non-guest groups owners from a specific country as the reviewers, specify as follows:
This sentence isn't quite clear. You can remove "specify as follows" because you begin the sentence with "To specify". The phrase "non-guest groups owners" is hard to parse. Maybe you mean "group owners"?

2021-05-18 01:51 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +The Azure AD [access reviews API](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access—of all users, a set of users (for exam
Change the verb case because API is singular.

2021-05-18 01:52 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +To configure the scope using the **accessReviewQueryScope** type, set the values of its **query**, **queryRoot**, and **queryType** properties. [See the accessReviewQueryScope](/graph/api/resources/a
Update the cross reference.

2021-05-18 01:54 UTC, Lauragra commented on concepts/accessreviews-scope-concept.md
> +To review *only inactive users* assigned to the group, specify as follows:
A more readable construction here would be "specify the following".

2021-05-19 07:13 UTC, FaithOmbongi commented on concepts/accessreviews-reviewers-concept.md
> +title: "Assign reviewers to your access review definition"
We've added links from the property descriptions and the 3 complex resources we're configuring. For example, the descriptions of **scope** and **reviewers** properties of **accessReviewsScheduleDefinition** have links to the scope and reviewers configuration articles respectively.

2021-05-19 07:13 UTC, FaithOmbongi commented on concepts/accessreviews-scope-concept.md
> +The Azure AD [access reviews API](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allow you to programmatically review access—of all users, a set of users (for exam
"allows you to programmatically review the access that all users, a set of users, and service principals and groups have to your Azure AD resources." sounds better. Thank you. Made the changes.

2021-05-19 07:43 UTC, opbld33 commented
Docs Build status updates of commit _[a231d52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a231d52d202d9ce151630d61604aec0a79e3f650)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/accessreviewscheduledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-list?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/api/accessreviewscheduledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreview?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinactiveusersqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewinactiveusersqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinactiveusersqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewqueryscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviews-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviews-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/disableanddeleteuserapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/disableanddeleteuserapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/disableanddeleteuserapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/patternedrecurrence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/patternedrecurrence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/patternedrecurrence?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/principalresourcemembershipsscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/principalresourcemembershipsscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/principalresourcemembershipsscope?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/resources/removeaccessapplyaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-get?view=graph-rest-beta&branch=pr-en-us-12447) (graph-rest-beta) |
[api-reference/includes/accessreviews-disclaimer-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ARexamples/api-reference/includes/accessreviews-disclaimer-v2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&branch=pr-en-us-12447) ( [...]

2021-05-19 22:59 UTC, Lauragra approved these changes

2021-05-19 22:59 UTC, merged