Add warning enum to CloudPCOnPremisesConnectionStatus
microsoftgraph/microsoft-graph-docs pull request #12455
Opened 2021-04-23 16:37 UTC by RuiHou105

2021-04-23 16:38 UTC, opbld31 commented
Docs Build status updates of commit _[e8815a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8815a7af240c71ea40bb1fd2547425c6ca5bfee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) | [Details](#user-content-7bf1f315aa73f5b36cf7254b91ab3efd-56aab632)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7bf1f315aa73f5b36cf7254b91ab3efd-56aab632"></a>
### [api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md)
 - **Line 49, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ion script storage URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings. The URLs can be found in additional information.|'`````
 - **Line 50, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ed because the WVD URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings.|'`````
 - **Line 51, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'because the Intune URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings.|'`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104231637195662-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v%2FPM32k1MoBoULhTwm46D9sNuLWLuQGeSwwxBQLcks4%3D&st=2021-04-23T16%3A33%3A35Z&se=2021-05-24T16%3A38%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 08:23 UTC, opbld31 commented
Docs Build status updates of commit _[8a72ab8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a72ab83c64296a38d674febcd0de6ca90b2d185)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) | [Details](#user-content-7bf1f315aa73f5b36cf7254b91ab3efd-6468da06)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7bf1f315aa73f5b36cf7254b91ab3efd-6468da06"></a>
### [api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md)
 - **Line 50, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ion script storage URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings. The URLs can be found in additional information.|'`````
 - **Line 51, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ed because the WVD URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings.|'`````
 - **Line 52, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'because the Intune URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings.|'`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105060821134796-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LLgqiGT3km1eORE31Yavm5PE%2BVk%2BQimNYLfgnimoFG8%3D&st=2021-05-06T08%3A18%3A51Z&se=2021-06-06T08%3A23%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 08:36 UTC, opbld31 commented
Docs Build status updates of commit _[a8c2620](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8c262022786bbd832fe41310e3a59352b7db76d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) | [Details](#user-content-7bf1f315aa73f5b36cf7254b91ab3efd-1a9e3ce6)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="7bf1f315aa73f5b36cf7254b91ab3efd-1a9e3ce6"></a>
### [api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md)
 - **Line 50, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ion script storage URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings. The URLs can be found in additional information.|'`````
 - **Line 51, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'ed because the WVD URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings.|'`````
 - **Line 52, Column 1**: **[Suggestion-[sensitive-language-wl](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelisted' is sensitive and should not be used in content or code. Usage: 'because the Intune URL isn’t on the allow list in the network firewall settings. Please add URLs to whitelisted network firewall settings.|'`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105060835354944-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0zUS4YlyguEDeq0O9WF8lLTz5PMt6SZgLiFrP9PgyG0%3D&st=2021-05-06T08%3A31%3A46Z&se=2021-06-06T08%3A36%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-08 23:54 UTC, Lauragra commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckCloudPcUrlNotAllowListed|The endpoint connectivity check failed because the CPC provision script storage URL isn’t on the allow list in the network firewall settings. Please
Please don't use the term "whitelisted"; instead, rephrase i.e. "Add URLs to the list of allowed network firewall settings."

2021-05-10 03:35 UTC, opbld31 commented
Docs Build status updates of commit _[63bcf9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63bcf9ce086ac45b4cae861bb51faf1f45915e8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105100334077747-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aC8%2Fxuxd2CgU88Mx7bXaL1Tv6GA702iMBgbehjl9WfM%3D&st=2021-05-10T03%3A30%3A24Z&se=2021-06-10T03%3A35%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 07:19 UTC, AshleyYangSZ approved these changes

2021-05-27 08:26 UTC, RuiHou105 commented
1. Related api.md: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/8271

2. Related CSDL file (schema-Prod-beta.csdl): https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4415017

2021-06-01 22:37 UTC, cohanley approved these changes

2021-06-04 08:39 UTC, opbld31 commented
Docs Build status updates of commit _[a0df71a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0df71a3d6962e1389b2bfd20d4cc9e974d3ff10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106040837508745-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xlxDsSMLDBNNpC1YzAjodoWjbY2VzHaP7P9AXZ%2FSDoI%3D&st=2021-06-04T08%3A34%3A53Z&se=2021-07-05T08%3A39%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 12:18 UTC, opbld30 commented
Docs Build status updates of commit _[6448a16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6448a16805dc3d35f7fea66e6a10c9996d18d924)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071217097041-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kat0BSn0L4Kj9wBVfRKnpJ0NnDcN09N0zlgSO2jgdfM%3D&st=2021-06-07T12%3A13%3A42Z&se=2021-07-08T12%3A18%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 13:08 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPcOnPremisesConnectionStatus",
ChangedApiName would be "warning", in this case.

2021-06-07 13:09 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPcOnPremisesConnectionHealthCheckErrorType",
ChangedApiName: "endpointConnectivityCheckUrlNotWhitelisted"

2021-06-07 13:10 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPcOnPremisesConnectionHealthCheckErrorType",
Similar observassion. Please note, the ChangedAPIName parameter represents the actual element being added, deleted or changed. In this case: endpointConnectivityCheckCloudPcUrlNotAllowListed.

2021-06-07 13:11 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPcOnPremisesConnectionHealthCheckErrorType",
ChangedApiName: endpointConnectivityCheckWVDUrlNotAllowListed

2021-06-07 13:12 UTC, isvargasmsft commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPcOnPremisesConnectionHealthCheckErrorType",
ChangedApiName: endpointConnectivityCheckIntuneUrlNotAllowListed

2021-06-07 13:13 UTC, isvargasmsft requested changes
@RuiHou105 thank you very much for your work in this PR. Very nice work. 

Please fix the ChangedApiName parameter in your changelog entries. Please note, this parameter represents the actual element being added, changed or deleted. For details: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

2021-06-09 09:06 UTC, opbld31 commented
Docs Build status updates of commit _[a71a733](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a71a73339709021094f7568f96ecf7c5e37ac7ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106090904134537-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nP6QqXCYYK02zExg2Q357hGwIJGtLJuJmnfX1oclw78%3D&st=2021-06-09T09%3A01%3A51Z&se=2021-07-10T09%3A06%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 09:10 UTC, RuiHou105 commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ChangedApiName": "cloudPcOnPremisesConnectionHealthCheckErrorType",
Thank you for your clear clarifying. I've updated these ChangedApiName. Please have a look. Thanks.

2021-06-09 14:31 UTC, isvargasmsft approved these changes
Good for me!

Thanks!

2021-06-09 15:49 UTC, Lauragra approved these changes

2021-06-09 15:50 UTC, opbld33 commented
Docs Build status updates of commit _[21e16e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21e16e5984003605cee3e2f10dc7ce2045552854)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12455) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddWarningEnumToCloudPCOnpremisesConnectionStatus/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106091549310369-12455%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5kCQCciSc%2BQkXSR%2B6cai%2Bou%2F%2BPUeCN%2BZLwwxZ9nHna4%3D&st=2021-06-09T15%3A45%3A57Z&se=2021-07-10T15%3A50%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 18:21 UTC, merged