Added the docs to show how to detect a user's login state in vanilla JS.
microsoftgraph/microsoft-graph-docs pull request #12469
Opened 2021-04-26 08:33 UTC by musale

This closes https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1025

2021-04-26 08:34 UTC, opbld34 commented
Docs Build status updates of commit _[607acf0](https://github.com/musale/microsoft-graph-docs/commits/607acf0f32e16d083bcabbba7432faa7b5af64d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) | [Details](#user-content-503a40948b2b1e2e63e6151dc1e4bb1d-af47a19c)

<a id="503a40948b2b1e2e63e6151dc1e4bb1d-af47a19c"></a>
### [concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md)
 - **Line 134, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104260833225804-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GYUjjibMvqJaHM0bQXWVkg4TVCgOmhBzdDyzkpIJemw%3D&st=2021-04-26T08%3A29%3A33Z&se=2021-05-27T08%3A34%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-26 08:48 UTC, opbld30 commented
Docs Build status updates of commit _[dc5b8e8](https://github.com/musale/microsoft-graph-docs/commits/dc5b8e83dfc71ae79b30906124a70db1a1d70d29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104260846179540-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TzmYF7vu12NJP3fNZwF%2BDuyAQ7f1iZvsC4IU0JDqmjw%3D&st=2021-04-26T08%3A43%3A37Z&se=2021-05-27T08%3A48%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-26 08:51 UTC, opbld33 commented
Docs Build status updates of commit _[d1d9f29](https://github.com/musale/microsoft-graph-docs/commits/d1d9f295ec1995943dd31d2d8653e07324a2ede6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104260849045173-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OR%2FBSJWYtQYi26Jxez%2Fb0rZgso277hObgRco1G2ggj8%3D&st=2021-04-26T08%3A46%3A19Z&se=2021-05-27T08%3A51%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 20:46 UTC, elisenyang requested changes

2021-04-27 20:46 UTC, elisenyang commented on concepts/toolkit/get-started/build-a-web-app.md
> +
```suggestion

---

```

Need to add dashes surrounded by empty lines for proper formatting

2021-04-27 20:46 UTC, elisenyang commented on concepts/toolkit/get-started/build-a-web-app.md
> +# [html](#tab/HTML)
The format here is not consistent with the code samples on the rest of the page. Throughout the doc, the tabs are used to show how to do a certain step in HTML vs. JS. Here, you are using them to show 2 files that are needed together. Can you change this so the HTML tab shows how to do this in only the HTML file and the JS tab shows how to do it in only the JS file?

Not sure if I'm making this clear... ping me if you have questions!

2021-04-28 11:56 UTC, musale commented on concepts/toolkit/get-started/build-a-web-app.md
> +# [html](#tab/HTML)
That's clear. I'm doing an update.

2021-04-29 17:48 UTC, opbld34 commented
Docs Build status updates of commit _[71bb8d6](https://github.com/musale/microsoft-graph-docs/commits/71bb8d6c3999cdd0c30e0d16678a0d6ec336898c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104291746363108-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eR5b4Ku93YqZnvRGqL9fS13tBSHaHKWRFak7E7sg7RA%3D&st=2021-04-29T17%3A43%3A02Z&se=2021-05-30T17%3A48%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 17:52 UTC, opbld30 commented
Docs Build status updates of commit _[5ff5073](https://github.com/musale/microsoft-graph-docs/commits/5ff5073dcef57e72e1adb0c8c997a65b9146359e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104291751164089-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hFY7JfjOt1rmgWlYBDNtQCn31%2BHV9BbikoHs8vv6BtE%3D&st=2021-04-29T17%3A47%3A19Z&se=2021-05-30T17%3A52%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 20:32 UTC, opbld33 commented
Docs Build status updates of commit _[0ef489a](https://github.com/musale/microsoft-graph-docs/commits/0ef489aaabeb19e3f89d79f81858283b06467823)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182030420773-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s2HdCcInvvFLFrBOumO3BU8ZBSFPJmOn3IafxdOZg1o%3D&st=2021-05-18T20%3A27%3A14Z&se=2021-06-18T20%3A32%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 19:35 UTC, opbld31 commented
Docs Build status updates of commit _[bda1c9b](https://github.com/musale/microsoft-graph-docs/commits/bda1c9b655653a2e890b7191a469c7685d4e0451)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105191933404790-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=veOu0WUi8WY7mHHYt3X8nCtAOP93VvYB0xMwiixP6pk%3D&st=2021-05-19T19%3A30%3A12Z&se=2021-06-19T19%3A35%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 23:45 UTC, isvargasmsft commented on concepts/toolkit/get-started/build-a-web-app.md
> +You might want to display some components only when a user is successfully logged in. In such a case, you need to detect when the user login is successful so that you can have the implementation of a
Line 124: Let's improve the phrasing. We try to use less words, avoid passive voice and communicate the message in the easiest way possible. In this case, I'd suggest going directly to the point. For example:
- You can detect when a user has successfully logged in and display specific components accordingly.

Don't you think it communicates the message cleaner and faster?

Please review [Microsoft Writing Style](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=33685) for more details.

2021-05-19 23:58 UTC, isvargasmsft commented on concepts/toolkit/get-started/build-a-web-app.md
> +Using the mgt-loader library, you have access to the `mgt` object which allows you to get the `Providers` and the `ProviderState` that you can use to determine if a user is logged in.
Line 130:
1. When you mention any method, entity, property, enumeration or a word in a UI, please use **bold** letters; and if it is the very first time you mention one of those in the document, please include the link: [resource](link).
2. Use camelCapitalization when mentioning resources, methods, properties, entities and such. 
3. The sentence can be organized for clarity and scannability. My advice: mention first what you want to accomplish and then explain how. It will be easier to scan for customers. For example:

- Determine if a user is logged in by evaluating the **providers** and **providerState** properties. You can access these properties by using the `mgt-loader` library.

2021-05-20 00:01 UTC, isvargasmsft commented on concepts/toolkit/get-started/build-a-web-app.md
> +# [html](#tab/HTML)
Line 128: Please capitalize HTML:
[HTML](#tab/HTML)

2021-05-20 00:04 UTC, isvargasmsft commented on concepts/toolkit/get-started/build-a-web-app.md
> +# [js](#tab/JavaScript)
Please use the proper format for this tab: [JavaScript].
For more details on how to use tabs, please visit the guidelines [here](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/tabbed-conceptual?branch=master#approved-tabs).

2021-05-20 00:22 UTC, isvargasmsft commented on concepts/toolkit/get-started/build-a-web-app.md
> +Using the mgt-loader library, you have access to the `mgt` object which allows you to get the `Providers` and the `ProviderState` that you can use to determine if a user is logged in.
Reading the JavaScript piece, it seems to me that this text applies to both, right? If my assumption is correct, please take the text out of the HTML tab and merge it with the line above.

2021-05-20 02:21 UTC, isvargasmsft commented on concepts/toolkit/get-started/build-a-web-app.md
> +Using the ES6 modules, the `Providers`, `ProviderState`, the MSAL provider initialized in HTML, the Login, and the Agenda component, we can display the agenda component only if the user is logged in.
Line 126: Let's improve this phrasing as well. 
1. The listing inside the sentence is not efficient. 
2. Avoid using 3rd person (we) to maintain the focus on the customer. Details [here](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25524). 

This line precedes a code block with the example, so I'd use it to introduce the code block:
- For example, display the agenda component if the user has logged in. Otherwise, display the login interface.

This way, we introduce the code block and the sentence is easier to scan.

2021-05-20 02:39 UTC, isvargasmsft requested changes
@musale great update to the docs, thank you for putting everything together. 

General re-phrasing recommendations for efficiency. Remember we write to scan first, read later. And we try to use simple words for non native speakers. 

There is one additional issue I'd like to bring into your attention:
- We checked this doc and its family and noticed some inconsistencies in the use of tabs and code boxes. For instance, the use of `js` instead of `JavaScript`, or `ts` instead of `TypeScript`. Also, some tabs and code boxes not included in the approved list. I'd like to address this on the side, so I'll explain further in an email. In the meantime, please review the list of approved tabs and Dev Slang. 

Approved tabs: https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/tabbed-conceptual?branch=master#approved-tabs
Approved Dev Slang: https://review.docs.microsoft.com/en-us/help/contribute/metadata-taxonomies?branch=master#dev-lang

Please feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2021-05-20 02:41 UTC, opbld31 commented
Docs Build status updates of commit _[4221960](https://github.com/musale/microsoft-graph-docs/commits/42219601bdf5585184ae2dd6fc33020d820ca42a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105200240204906-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VESHFvBJvxNHO54YHUjndqvQVRRtvKR59vo9urbPCGI%3D&st=2021-05-20T02%3A36%3A56Z&se=2021-06-20T02%3A41%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 09:08 UTC, musale commented on concepts/toolkit/get-started/build-a-web-app.md
> +Using the mgt-loader library, you have access to the `mgt` object which allows you to get the `Providers` and the `ProviderState` that you can use to determine if a user is logged in.
Yes it does. Previous direction from https://github.com/microsoftgraph/microsoft-graph-docs/pull/12469#discussion_r621587773 required the format to be consistent in the doc so I split it into JS and HTML tabs. 

Removing a tab will cause errors during building. Can I have a different example for the JS tab and give it it's own text?

2021-05-20 09:09 UTC, musale commented on concepts/toolkit/get-started/build-a-web-app.md
> +# [html](#tab/HTML)
I applied this to the rest of the document.

2021-05-20 14:38 UTC, isvargasmsft commented on concepts/toolkit/get-started/build-a-web-app.md
> +Using the mgt-loader library, you have access to the `mgt` object which allows you to get the `Providers` and the `ProviderState` that you can use to determine if a user is logged in.
My apologies for the misunderstanding. I don't think you should remove the JS tab. I am suggesting taking line 130 out of the tabs and merging its content with line 126. 

Keeping line 130 inside the HTML tab gives the impression that it only applies to the HTML example. Please let me know if you have any questions.

2021-05-25 20:42 UTC, opbld32 commented
Docs Build status updates of commit _[fc7dc0f](https://github.com/musale/microsoft-graph-docs/commits/fc7dc0f58179481ecba30bf8493f63ccca710e45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105252040274243-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=05e0sMNqa0q%2FKTapq167XjpBOoqZ%2Fco15xG43gu23pY%3D&st=2021-05-25T20%3A37%3A07Z&se=2021-06-25T20%3A42%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 19:15 UTC, elisenyang approved these changes

2021-05-28 19:17 UTC, opbld31 commented
Docs Build status updates of commit _[2efaf2e](https://github.com/musale/microsoft-graph-docs/commits/2efaf2e41f4c628661e1c1b7ec5fca510304023c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2c2465df)

<a id="2c2465df"></a>
###
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/sandboxEnabledModuleList/'. Try closing and reopening the PR. If you get this Error again, file an issue.`````
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/sandboxEnabledModuleList/'. Try closing and reopening the PR. If you get this Error again, file an issue.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105281915237485-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=weAiMvkJJvpmE3NGcnDA8w5D45kXu1R0YuKyGxY9qis%3D&st=2021-05-28T19%3A12%3A23Z&se=2021-06-28T19%3A17%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 17:25 UTC, opbld30 commented
Docs Build status updates of commit _[bad9ed3](https://github.com/musale/microsoft-graph-docs/commits/bad9ed3db424bff2f8b4d2264d0617a08bdff083)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106111724078151-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C%2FNJ1%2FhST4dPM8MFEMecHqesIFlLu2yS4L6CVBlBwig%3D&st=2021-06-11T17%3A20%3A57Z&se=2021-07-12T17%3A25%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 17:31 UTC, isvargasmsft approved these changes
Thank you very much!

2021-06-12 01:33 UTC, opbld33 commented
Docs Build status updates of commit _[932b9cc](https://github.com/musale/microsoft-graph-docs/commits/932b9cce252b9e117e294f41e53d8069564a37a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-web-app.md](https://github.com/musale/microsoft-graph-docs/blob/detect-login-states-js/concepts/toolkit/get-started/build-a-web-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-web-app?branch=pr-en-us-12469) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106120132079309-12469%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UzY0ibcp%2B1hHsD%2BMzXN0ppeAXCYZfpOWFFKSwOr7K1Q%3D&st=2021-06-12T01%3A28%3A27Z&se=2021-07-13T01%3A33%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:32 UTC, merged