add policy.readwrite.accessreviews permissions
microsoftgraph/microsoft-graph-docs pull request #12506
Opened 2021-04-27 18:55 UTC by isabelleatmsft

2021-04-27 18:56 UTC, opbld31 commented
Docs Build status updates of commit _[2d81e3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d81e3e65f7bf189cc8cc9a78cbe914016e1494c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-12506) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271855366722-12506%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z6LRdvSwd4od1w%2B0P2e7Ewd6tc0kBPPEooz8JRaO1Nc%3D&st=2021-04-27T18%3A51%3A49Z&se=2021-05-28T18%3A56%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:18 UTC, FaithOmbongi approved these changes

2021-04-27 22:14 UTC, markwahl-msft requested changes
I didn't see the rest of the files?  Not sure if this pull request is complete?

2021-04-27 22:14 UTC, markwahl-msft commented on concepts/permissions-reference.md
> +| _Policy.ReadWrite.AccessReviews_ |   Manage all access review policies  | Allows the app to read and write access review policies on behalf of the signed-in user. | Yes |
Please check the description because this is in the app permissions section but it talks about signed in user.

2021-04-27 22:14 UTC, markwahl-msft commented on concepts/permissions-reference.md
>  ### Remarks
I only see one changed file.  What about the API articles themselves, which enumerate the permissions?  And is there a change needed also to mention this in accessreviewsv2-root?  Also don't forget the changelog record to Microsoft.DirectoryServices.json if this is a new permission is needed as well..

2021-04-28 21:18 UTC, isabelleatmsft commented on concepts/permissions-reference.md
>  ### Remarks
The api articles themselves are taken care of by this PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/12370#event-4653889822

Will check the root article and changelog now.

2021-04-28 21:38 UTC, opbld34 commented
Docs Build status updates of commit _[6591ce8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6591ce8bf84fded7dbe37df078adb3327b6c1cff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12506) (graph-rest-beta) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-12506) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104282136205795-12506%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gaGUhUZOxbOisPhuOHMrf7r3fXwiHQdqgpu7iSujafQ%3D&st=2021-04-28T21%3A33%3A29Z&se=2021-05-29T21%3A38%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 21:44 UTC, opbld32 commented
Docs Build status updates of commit _[9184e7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9184e7bfe1f25799516942248f8e3c8265bbb723)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12506) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-12506) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104282142153685-12506%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mNW9vgDAXA8hzKPohLs%2Bp0dsnOAQb6ZU18WEaLQbN9E%3D&st=2021-04-28T21%3A39%3A51Z&se=2021-05-29T21%3A44%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 02:50 UTC, opbld34 commented
Docs Build status updates of commit _[5d668d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d668d089e63d91d07f35be065469b290b16c3c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewsv2-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/api-reference/beta/resources/accessreviewsv2-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&branch=pr-en-us-12506) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isabelleatmsft-patch-2/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-12506) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104290249017121-12506%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FEGVRms89AJ4tx5suYfBVOd1a49ezooMt1yBrMEO8Ow%3D&st=2021-04-29T02%3A45%3A25Z&se=2021-05-30T02%3A50%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 03:01 UTC, merged