Identity provider user flow
microsoftgraph/microsoft-graph-docs pull request #12583
Opened 2021-05-03 18:01 UTC by namkedia

This PR includes the update to the userflow API for B2B and B2C with the new Identity Provider API update

2021-05-03 18:02 UTC, opbld30 commented
Docs Build status updates of commit _[d578718](https://github.com/namkedia/microsoft-graph-docs/commits/d5787185a68d2076b34965f3efeb60148bbdd9a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-ccb554f1)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-ccb554f1)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-ccb554f1)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

<a id="15589d1aeb0faca926dda48f87683b6d-ccb554f1"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="d654518bd6adc9b18abf0e3002e6be26-ccb554f1"></a>
### [api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="1da19d1e6290cf082ca093edb7bb2d0c-ccb554f1"></a>
### [api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105031801075063-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8xlhhkQBBaVXOPblrPF%2BM%2F9J9x2RNy2ti37ZRmd%2BMwM%3D&st=2021-05-03T17%3A57%3A19Z&se=2021-06-03T18%3A02%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 20:08 UTC, opbld34 commented
Docs Build status updates of commit _[8bbef57](https://github.com/namkedia/microsoft-graph-docs/commits/8bbef57043d59d36ef96afef3cf68b9cf8a0dd8c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-947609c3)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-947609c3)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-947609c3)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

<a id="15589d1aeb0faca926dda48f87683b6d-947609c3"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="1da19d1e6290cf082ca093edb7bb2d0c-947609c3"></a>
### [api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="d654518bd6adc9b18abf0e3002e6be26-947609c3"></a>
### [api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List all identityProviders in a b2cIdentityUserFlow' is duplicated with other articles: 'beta/api/b2cidentityuserflow-list-identityproviders.md(10,1), beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105032007391926-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8S4d%2B2q%2F85xTedet9Rz2lv10omBoqwP19endxKj1cU8%3D&st=2021-05-03T20%3A03%3A48Z&se=2021-06-03T20%3A08%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 22:32 UTC, opbld30 commented
Docs Build status updates of commit _[ab7d7cb](https://github.com/namkedia/microsoft-graph-docs/commits/ab7d7cb94c02a7e87f98ea53c864b61348134e37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-426c6d2f)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-426c6d2f)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-426c6d2f)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

<a id="15589d1aeb0faca926dda48f87683b6d-426c6d2f"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider from a b2cIdentityUserFlow - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-identityproviders.md(2,8), beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Delete an identityProvider from a b2cIdentityUserFlow.' is duplicated in 'beta/api/b2cidentityuserflow-delete-identityproviders.md(3,14)', 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete an identityProvider from a b2cIdentityUserFlow' is duplicated with other articles: 'beta/api/b2cidentityuserflow-delete-identityproviders.md(10,1), beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="d654518bd6adc9b18abf0e3002e6be26-426c6d2f"></a>
### [api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List all identityProviders in a b2cIdentityUserFlow - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-list-identityproviders.md(2,8), beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List all identityProviders in a b2cIdentityUserFlow.' is duplicated in 'beta/api/b2cidentityuserflow-list-identityproviders.md(3,14)', 'beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List all identityProviders in a b2cIdentityUserFlow' is duplicated with other articles: 'beta/api/b2cidentityuserflow-list-identityproviders.md(10,1), beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="1da19d1e6290cf082ca093edb7bb2d0c-426c6d2f"></a>
### [api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Add identityProvider to a b2cIdentityUserFlow - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-post-identityproviders.md(2,8), beta/api/b2cidentityuserflow-post-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Add identityProvider to a b2cIdentityUserFlow.' is duplicated in 'beta/api/b2cidentityuserflow-post-identityproviders.md(3,14)', 'beta/api/b2cidentityuserflow-post-userflowidentityproviders.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Add identityProvider to a b2cIdentityUserFlow' is duplicated with other articles: 'beta/api/b2cidentityuserflow-post-identityproviders.md(10,1), beta/api/b2cidentityuserflow-post-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105032231193949-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LuydVJNIyrmrHw6wl3ye9c5op5vPILhFwaMmtTR%2FK8o%3D&st=2021-05-03T22%3A27%3A25Z&se=2021-06-03T22%3A32%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 22:41 UTC, opbld31 commented
Docs Build status updates of commit _[6342b3e](https://github.com/namkedia/microsoft-graph-docs/commits/6342b3ecde24fc478bc4322e074556011b150f83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-4041ffdd)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-4041ffdd)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-4041ffdd)
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

<a id="15589d1aeb0faca926dda48f87683b6d-4041ffdd"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider from a b2cIdentityUserFlow - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-identityproviders.md(2,8), beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Delete an identityProvider from a b2cIdentityUserFlow.' is duplicated in 'beta/api/b2cidentityuserflow-delete-identityproviders.md(3,14)', 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete an identityProvider from a b2cIdentityUserFlow' is duplicated with other articles: 'beta/api/b2cidentityuserflow-delete-identityproviders.md(10,1), beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="d654518bd6adc9b18abf0e3002e6be26-4041ffdd"></a>
### [api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List all identityProviders in a b2cIdentityUserFlow - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-list-identityproviders.md(2,8), beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'List all identityProviders in a b2cIdentityUserFlow.' is duplicated in 'beta/api/b2cidentityuserflow-list-identityproviders.md(3,14)', 'beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List all identityProviders in a b2cIdentityUserFlow' is duplicated with other articles: 'beta/api/b2cidentityuserflow-list-identityproviders.md(10,1), beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="1da19d1e6290cf082ca093edb7bb2d0c-4041ffdd"></a>
### [api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Add identityProvider to a b2cIdentityUserFlow - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-post-identityproviders.md(2,8), beta/api/b2cidentityuserflow-post-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Add identityProvider to a b2cIdentityUserFlow.' is duplicated in 'beta/api/b2cidentityuserflow-post-identityproviders.md(3,14)', 'beta/api/b2cidentityuserflow-post-userflowidentityproviders.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Add identityProvider to a b2cIdentityUserFlow' is duplicated with other articles: 'beta/api/b2cidentityuserflow-post-identityproviders.md(10,1), beta/api/b2cidentityuserflow-post-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105032240088863-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gHWNYwtLdv%2F%2BZ1uf%2BFJ3rN7%2F%2BagH6nJ5Tc%2FHR2qIpAQ%3D&st=2021-05-03T22%3A36%3A11Z&se=2021-06-03T22%3A41%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your  [...]

2021-05-03 22:48 UTC, opbld31 commented
Docs Build status updates of commit _[44cba5b](https://github.com/namkedia/microsoft-graph-docs/commits/44cba5b3369ce2f54e933955e28d38d55ca50e7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105032247399237-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZI7r5Re0%2BLo%2FC5bvD1AMEdJpFRrHNUQ5%2Byu%2B%2F5Gr%2FWE%3D&st=2021-05-03T22%3A43%3A46Z&se=2021-06-03T22%3A48%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 23:36 UTC, opbld33 commented
Docs Build status updates of commit _[70f13d6](https://github.com/namkedia/microsoft-graph-docs/commits/70f13d6081b38fa19d16e42520e87e465ecd099d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105032335404988-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4lo%2BfultN06UboZFsTB1Ws0C5fmC5GieurkWAs1M%2BNs%3D&st=2021-05-03T23%3A31%3A47Z&se=2021-06-03T23%3A36%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[6da6a68](https://github.com/namkedia/microsoft-graph-docs/commits/6da6a689eecdce44691b77b01f2dbd8285d986db)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1bd49f7f)

<a id="1bd49f7f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105032343171050-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l%2Bmxa8Es8GVvfPOccCME8RMvi%2B1Um9Q6qaXK7vEDhKM%3D&st=2021-05-03T23%3A39%3A17Z&se=2021-06-03T23%3A44%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 23:47 UTC, opbld32 commented
Docs Build status updates of commit _[2d750fc](https://github.com/namkedia/microsoft-graph-docs/commits/2d750fc52d262ec2ff0b3402760eaf717542255c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105032346368092-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F1i7mZ%2FFg%2Forlu2hVqzJ2oVk%2BQmAg28%2F0PKP79ie6Xc%3D&st=2021-05-03T23%3A42%3A48Z&se=2021-06-03T23%3A47%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 00:16 UTC, opbld30 commented
Docs Build status updates of commit _[44c4ed4](https://github.com/namkedia/microsoft-graph-docs/commits/44c4ed4eb2353e47908e190ddfcb9363c13ca4fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040014480310-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1Mvt5qcM1oDvGstdWwETsrhd%2F2wrgd%2BRtPOuLApiicA%3D&st=2021-05-04T00%3A11%3A02Z&se=2021-06-04T00%3A16%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 00:48 UTC, saraswatshantanu commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|identityProviders|[identityProvider](../resources/identityproviderbase.md) collection|The identity providers included in the user flow.|
This should be userflowidentityProviders

2021-05-04 00:48 UTC, saraswatshantanu commented on api-reference/beta/resources/b2xidentityuserflow.md
> +|identityProviders|[identityProvider](../resources/identityproviderbase.md) collection|The identity providers included in the user flow.|
This should be userflowidentityProviders

2021-05-04 01:42 UTC, hecthern commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|identityProviders|[identityProvider](../resources/identityproviderbase.md) collection|The identity providers included in the user flow.|
Also the Type should be identityProviderBase isn't ?

2021-05-04 02:17 UTC, namkedia commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|identityProviders|[identityProvider](../resources/identityproviderbase.md) collection|The identity providers included in the user flow.|
Ack to both.

2021-05-04 02:17 UTC, namkedia commented on api-reference/beta/resources/b2xidentityuserflow.md
> +|identityProviders|[identityProvider](../resources/identityproviderbase.md) collection|The identity providers included in the user flow.|
Ack.

2021-05-04 02:19 UTC, opbld32 commented
Docs Build status updates of commit _[c498d16](https://github.com/namkedia/microsoft-graph-docs/commits/c498d1638cb629efef6f225798f206cff8d044a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040218462431-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9hWws1US7FhrWvOGzgzQcGXdCdNdzPdNZ85dtMlGuYg%3D&st=2021-05-04T02%3A14%3A58Z&se=2021-06-04T02%3A19%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 04:04 UTC, opbld33 commented
Docs Build status updates of commit _[8be0565](https://github.com/namkedia/microsoft-graph-docs/commits/8be05656e8e6ac15dfe0be24aed01785acdc4c17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040402580110-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=26kzkHwJZu60ZbxM8DCySLCywt7NhHi8TcoMhnv5Wt8%3D&st=2021-05-04T03%3A59%3A02Z&se=2021-06-04T04%3A04%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 22:15 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md
> +title: "Delete identityProvider from a b2cIdentityUserFlow"
```suggestion
title: "Delete identityProvider"
```

2021-05-04 22:15 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md
> +# Delete an identityProvider from a b2cIdentityUserFlow
```suggestion
# Delete identityProvider
```

2021-05-04 22:16 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md
> +# [HTTP](#tab/http)
line 61 should be removed.

2021-05-04 22:16 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md
> +DELETE https://graph.microsoft.com/beta/identity/b2cUserFlows/{userflow-id}/userflowIdentityProviders/{identityProvider-id}/$ref
Examples should have real looking examples.

2021-05-04 22:17 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md
> +title: "List all identityProviders in a b2cIdentityUserFlow"
```suggestion
title: "List identityProviders"
```

2021-05-04 22:17 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md
> +# List all identityProviders in a b2cIdentityUserFlow
```suggestion
# List identityProviders
```

2021-05-04 22:17 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md
> +# [HTTP](#tab/http)
Line 61 should be removed.

2021-05-04 22:18 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md
> +GET https://graph.microsoft.com/beta/identity/b2cUserFlows/{id}/userflowIdentityProviders
Examples should show real looking id values.

2021-05-04 22:19 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md
>  # [HTTP](#tab/http)
Line 63 should be removed.

2021-05-04 22:19 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md
> +title: "Add identityProvider to a b2cIdentityUserFlow"
```suggestion
title: "Add identityProvider"
```

2021-05-04 22:20 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md
> +# Add identityProvider to a b2cIdentityUserFlow
```suggestion
# Add identityProvider
```

2021-05-04 22:20 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md
> +# [HTTP](#tab/http)
Remove line 62.

2021-05-04 22:20 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md
> +PATCH https://graph.microsoft.com/beta/identity/b2cUserFlows/{id}/userflowIdentityProviders/$ref
Real looking values.

2021-05-04 22:22 UTC, davidmu1 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Add support to the new identityProvider relationship in the b2c identity userflow.",
```suggestion
          "Description": "Add the identityProvider relationship to the b2c identity userflow.",
```

2021-05-04 22:23 UTC, davidmu1 approved these changes

2021-05-05 01:08 UTC, Lauragra commented
@namkedia , please incorporate David's feedback before we merge. Thanks.

2021-06-07 17:50 UTC, opbld32 commented
Docs Build status updates of commit _[ab16cf7](https://github.com/namkedia/microsoft-graph-docs/commits/ab16cf7a35c805dffa45ec443baf780175f1d504)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c31eefee)

<a id="c31eefee"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071749000939-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pX%2BHfb6XRIDw0iy3RjsyL4C22BSGJuKuCqCQqDk6Ons%3D&st=2021-06-07T17%3A45%3A04Z&se=2021-07-08T17%3A50%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 17:51 UTC, opbld31 commented
Docs Build status updates of commit _[5be57f9](https://github.com/namkedia/microsoft-graph-docs/commits/5be57f939b1b79db070add1f0ea2c168ee59d8b5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4216a50b)

<a id="4216a50b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071749440273-12583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xBt6JDljBl1qVpbG7cvTxS%2BASZVJJsqca8JK%2BoKqJgc%3D&st=2021-06-07T17%3A46%3A03Z&se=2021-07-08T17%3A51%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 21:33 UTC, opbld34 commented
Docs Build status updates of commit _[65a804f](https://github.com/namkedia/microsoft-graph-docs/commits/65a804f196bb5f16b4bee1164360992823fc5837)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-b3e4dbd6)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-b3e4dbd6)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-b3e4dbd6)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-b3e4dbd6)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-b3e4dbd6"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentit [...]

2021-06-10 22:33 UTC, namkedia commented on api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md
> +# Add identityProvider to a b2cIdentityUserFlow
The title gives the developer the context they need to where they are adding the identity provider

2021-06-10 22:44 UTC, opbld30 commented
Docs Build status updates of commit _[495bacc](https://github.com/namkedia/microsoft-graph-docs/commits/495bacc4f7c8e06e897f6f7a8c383f1652ae86db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-eebb7589)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-eebb7589)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-eebb7589)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-eebb7589)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-eebb7589"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentit [...]

2021-06-11 00:58 UTC, opbld30 commented
Docs Build status updates of commit _[19d4d15](https://github.com/namkedia/microsoft-graph-docs/commits/19d4d15c166d147218cf23ffadfa702ce204cffc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-334d10ac)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-334d10ac)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-334d10ac"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete identityProvider' is duplicated with other articles: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(10,1), beta/api/identityproviderbase-delete.md(10,1)'. First level hea [...]

2021-06-11 01:06 UTC, opbld32 commented
Docs Build status updates of commit _[bb3accc](https://github.com/namkedia/microsoft-graph-docs/commits/bb3acccab8ef77c8658a4664991bab9a9a59c3f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-94c592e7)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-94c592e7)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-94c592e7"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete identityProvider' is duplicated with other articles: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(10,1), beta/api/identityproviderbase-delete.md(10,1)'. First level hea [...]

2021-06-11 01:09 UTC, opbld32 commented
Docs Build status updates of commit _[2a7e47b](https://github.com/namkedia/microsoft-graph-docs/commits/2a7e47b0538501df1b98b27e40c5ae2e1c92b11e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-b9b51226)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-b9b51226)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-b9b51226"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete identityProvider' is duplicated with other articles: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(10,1), beta/api/identityproviderbase-delete.md(10,1)'. First level hea [...]

2021-06-11 01:10 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the identityProvider relationship to the b2c identity userflow",
I think the relationship that is added to the b2cIdentityUserFlow is userflowIdentityProviders. It looks like identityProvider is marked as deprecated.

2021-06-11 01:11 UTC, opbld34 commented
Docs Build status updates of commit _[2a7e47b](https://github.com/namkedia/microsoft-graph-docs/commits/2a7e47b0538501df1b98b27e40c5ae2e1c92b11e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-ec5ed617)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-ec5ed617)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-ec5ed617"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete identityProvider' is duplicated with other articles: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(10,1), beta/api/identityproviderbase-delete.md(10,1)'. First level hea [...]

2021-06-11 01:12 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the identityProvider relationship to the b2c identity userflow",
Global: Please use the correct resource names and please apply bold formatting to all resource names. Also, add links to topics where relevant. So in this description, it should be "the **b2cIdentityUserFlow** resource."

2021-06-11 01:24 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecate the list identityProviders in a b2cIdentityUserFlow based on the old API.",
"based on the old API" is not clear. Is the "old" API the identityProvider resource? Then the changelist entry would be "Deprecated the identityProvider resource and the associated methods." The ChangeApiName and Target values would be identityProvider (note that List in this entry is not an API name). This comment applies to all of the entries for deprecation of methods.

2021-06-11 01:25 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecate the list identityProviders in a b2cIdentityUserFlow based on the old API.",
Can this just be the entry for the deprecation? The description would be "Deprecated the **identityProviders** resource and associated methods. This resource is replaced with the **identityProviderBase** resource."

2021-06-11 01:31 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangedApiName": "add",
ChangedApiName should be the name of the API; in this case, b2cIdentityUserFlow. Please apply globally to all entries; the value should not be the verb for the operation.

2021-06-11 01:33 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Add support to add identityProviders in b2cIdentityUserFlow based on the new [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase
Please update this and similar constructions to the following: "Added the [method name/link] method to the [identityProviderBase] resource." Please use the method names that map to the titles of the topics in this PR and be sure to link to the method topic.

2021-06-11 01:35 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": ""
Add the subarea - "Identity and sign-in".

2021-06-11 15:37 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md
> +description: "Delete an identityProvider from a b2cIdentityUserFlow."
```suggestion
description: "Delete identityProvider."
```

2021-06-11 15:37 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md
> +ms.prod: "microsoft-identity-platform"
```suggestion
ms.prod: "identity-and-sign-in"
```

2021-06-11 15:40 UTC, davidmu1 commented on api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md
> +# Add identityProvider to a b2cIdentityUserFlow
I understand, but the format that we want is what I suggested. The description can give more information.

2021-06-11 15:41 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md
> +ms.prod: "microsoft-identity-platform"
```suggestion
ms.prod: "identity-and-sign-in"
```

2021-06-11 15:41 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md
> +title: "Delete identityProvider from b2xIdentityUserFlow"
```suggestion
title: "Delete identityProvider"
```

2021-06-11 15:42 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md
> +# Delete identityProvider from b2xIdentityUserFlow
```suggestion
# Delete identityProvider
```

2021-06-11 15:42 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md
> +title: "List userflowidentityproviders in a b2xIdentityUserFlow"
```suggestion
title: "List userflowidentityproviders"
```

2021-06-11 15:42 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md
> +ms.prod: "microsoft-identity-platform"
```suggestion
ms.prod: "identity-and-sign-in"
```

2021-06-11 15:43 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md
> +# List userflowidentityproviders in a b2xIdentityUserFlow
```suggestion
# List userflowidentityproviders
```

2021-06-11 15:43 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md
> +GET https://graph.microsoft.com/beta/identity/b2xUserFlows/{id}/userflowIdentityProviders
The example should have a real looking id.

2021-06-11 15:44 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +title: "Add identityProvider to a b2xIdentityUserFlow"
```suggestion
title: "Add identityProvider"
```

2021-06-11 15:44 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +ms.prod: "microsoft-identity-platform"
```suggestion
ms.prod: "identity-and-sign-in"
```

2021-06-11 15:44 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +# Add identityProvider to a b2xIdentityUserFlow
```suggestion
# Add identityProvider
```

2021-06-11 15:51 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +PATCH https://graph.microsoft.com/beta/identity/b2xUserFlows/{id}/userflowIdentityProviders/$ref
Examples should have a real looking id.

2021-06-11 15:51 UTC, davidmu1 commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +  "@odata.id": "https://graph.microsoft.com/beta/identity/identityProviders/{id}"
Provide a real looking id.

2021-06-28 19:35 UTC, opbld30 commented
Docs Build status updates of commit _[d87d381](https://github.com/namkedia/microsoft-graph-docs/commits/d87d381ab251892bb95b9419681bd7cef2c42a81)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-3c5b67c8)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-3c5b67c8)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-3c5b67c8)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-3c5b67c8"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete identityProvider' is duplicated with other articles: 'beta/api [...]

2021-06-28 19:36 UTC, opbld31 commented
Docs Build status updates of commit _[2add04b](https://github.com/namkedia/microsoft-graph-docs/commits/2add04ba58cda9e80702b72ffa12a0ad9de57e8f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-1386970d)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-1386970d)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-1386970d)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-1386970d)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-1386970d)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-1386970d)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-1386970d)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-1386970d"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-06-28 19:39 UTC, opbld33 commented
Docs Build status updates of commit _[cfeaebc](https://github.com/namkedia/microsoft-graph-docs/commits/cfeaebcf13c894e9847558c9e81bcf2bb292717d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-6d248390)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-6d248390)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-6d248390)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-6d248390)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-6d248390)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-6d248390"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation- [...]

2021-06-28 19:41 UTC, opbld33 commented
Docs Build status updates of commit _[c73c394](https://github.com/namkedia/microsoft-graph-docs/commits/c73c394cc2896fe1c32997aaa2477c3f8fadfb85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-11a15557)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-11a15557)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-11a15557)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-11a15557)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-11a15557)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-11a15557)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-11a15557)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-11a15557"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-06-28 19:42 UTC, opbld30 commented
Docs Build status updates of commit _[8f8e97b](https://github.com/namkedia/microsoft-graph-docs/commits/8f8e97b0232f6a39760b5cc104aba79a31e99f66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-ba11ff14)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-ba11ff14)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-ba11ff14)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-ba11ff14)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-ba11ff14)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-ba11ff14)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-ba11ff14)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-ba11ff14"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-06-28 19:44 UTC, opbld32 commented
Docs Build status updates of commit _[28ce0c4](https://github.com/namkedia/microsoft-graph-docs/commits/28ce0c499ca308376b7b1110cb274267883b816b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-041e10be)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-041e10be)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-041e10be)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-041e10be)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-041e10be)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-041e10be)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-041e10be)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-041e10be"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-06-28 20:35 UTC, opbld30 commented
Docs Build status updates of commit _[3b813be](https://github.com/namkedia/microsoft-graph-docs/commits/3b813be6e2ad7553f65556c0575482a512c52092)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-4c68da9d)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-4c68da9d)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-4c68da9d)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-4c68da9d)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-4c68da9d)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-4c68da9d)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-4c68da9d)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-4c68da9d"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-06-28 21:48 UTC, opbld30 commented
Docs Build status updates of commit _[6e3e480](https://github.com/namkedia/microsoft-graph-docs/commits/6e3e48049c924b58a54740b774c8936ff66761f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-9c8edec2)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-9c8edec2)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-9c8edec2)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-9c8edec2)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-9c8edec2)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-9c8edec2)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-9c8edec2)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-9c8edec2"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-06-30 01:01 UTC, opbld33 commented
Docs Build status updates of commit _[e04b850](https://github.com/namkedia/microsoft-graph-docs/commits/e04b8500425e445a253775494ac9e3c7c40488d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-67774c9e)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-67774c9e)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-67774c9e)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-67774c9e)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-67774c9e)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-67774c9e)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-67774c9e)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-67774c9e"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-06-30 08:19 UTC, FaithOmbongi requested changes

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +In the request body, provide a JSON representation of the `id` of the [identityProvider](../resources/identityproviderbase.md) you want to add. For self-service sign up user flows, the values can be
Are there other types of user flows apart from the self-service sign up ones? Do they have different values? Let's tell the customer about them.
```suggestion
In the request body, provide a JSON representation with the `id` of the [identityProvider](../resources/identityproviderbase.md) you want to add. For self-service sign up user flows, the values can be `Google-OAUTH` or `Facebook-OAUTH`.
```

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +If successful, this method returns a `204 No Content` response code. If unsuccessful, a `4xx` error will be returned with specific details.
```suggestion
If successful, this method returns a `204 No Content` response code. If unsuccessful, a `4xx` error is returned with the specific error details.
```

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +Content-length: 30
```suggestion
```

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +The following is an example of the response.
```suggestion
```

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[Remove identity provider](../api/b2cidentityuserflow-delete-userflowidentityproviders.md)|None|Remove an identity provider from a B2C user flow|
```suggestion
|[Delete identity provider](../api/b2cidentityuserflow-delete-userflowidentityproviders.md)|None|Remove an identity provider from a B2C user flow|
```

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/resources/b2cidentityuserflow.md
> +|[Remove identity provider](../api/b2cidentityuserflow-delete-identityproviders.md) (deprecated)|None|Remove an identity provider from a B2C user flow|
```suggestion
|[Delete identity provider](../api/b2cidentityuserflow-delete-identityproviders.md) (deprecated)|None|Remove an identity provider from a B2C user flow|
```

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/resources/b2xidentityuserflow.md
> +|[Delete user flow](../api/b2xidentityuserflow-delete.md)|None|Delete a B2X user flow.|
I don't think we mention anywhere what B2X means. You might consider mentioning it in the [b2cidentityuserflow ](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?branch=pr-en-us-12583&view=graph-rest-beta)resource description.

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
>               - name: Remove identity provider
```suggestion
             - name: Delete identity provider
```

2021-06-30 08:19 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +             - name: Remove identity provider (deprecated)
```suggestion
             - name: Delete identity provider (deprecated)
```

2021-06-30 08:19 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta) resource relationship to [b2cIdentityUserFlo
Suggestion
```suggestion
          "Description": "Added the [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta) relationship to [b2cIdentityUserFlow](https://docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta) resource. Replaces the [identityprovider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta) relationship.",
```

2021-06-30 08:19 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta) resource relationship to [b2xIdentityUserFlo
Suggestion
```suggestion
          "Description": "Added the [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta) relationship to [b2xIdentityUserFlow](https://docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta) resource. Replaces the [identityprovider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta) relationship.",
```

2021-06-30 08:19 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "change",
I'll get back to you on this.

2021-06-30 08:19 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ApiChange": "Method",
```suggestion
          "ApiChange": "Resource",
```

2021-06-30 08:19 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "change",
Will get back to you on this

2021-06-30 08:19 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        },
Comment and decision on userFlowIdentityProvider vs identityProvider applies to all new methods.

2021-06-30 08:19 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "CreatedDateTime": "2021-06-29T00:00:00",
```suggestion
      "CreatedDateTime": "2021-06-29T00:00:00.000Z",
```

2021-06-30 08:27 UTC, FaithOmbongi commented on api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md
> +
```suggestion
The following is an example of the response.
>**Note:** The response object shown here might be shortened for readability.

```

2021-06-30 08:43 UTC, FaithOmbongi reviewed
Properties in b2cIdentityUserFlow and b2xIdentityUserFlow resources differ in public metadata vs docs. Kindly also check and align.

2021-06-30 08:43 UTC, FaithOmbongi commented on api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md
> +---
I don't think the file name is correct. -post* indicates a POST operation while this reference indicates a PATCH operation. Maybe the file name should be -update*?

2021-06-30 08:43 UTC, FaithOmbongi commented on api-reference/beta/resources/b2xidentityuserflow.md
> +|[Create user flow](../api/identitycontainer-post-b2xuserflows.md)|b2xIdentityUserFlow|Create a new B2X user flow.|
Previous comment about file name matching the operation. Create/POST operation = -post* filename. Update/PATCH operation = -update* filename

2021-06-30 10:14 UTC, FaithOmbongi requested changes

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "change",
```suggestion
          "ChangeType": "Addition",
```

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "change",
```suggestion
          "ChangeType": "Addition",
```

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecated the [identityprovider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta) resource and associated methods. This resource
```suggestion
          "Description": "Deprecated the [identityprovider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta) resource and it's related methods. This resource is replaced by the [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta) resource.",
```

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecated the [identityprovider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta) resource and associated methods. This resource
```suggestion
          "Description": "Deprecated the [identityprovider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta) resource and it's related methods. This resource is replaced by the [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta) resource.",
```

2021-07-08 04:24 UTC, namkedia commented on api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md
> +title: "Delete identityProvider"
even though the relationship is userflowidentity provider it is actually deleting the resource type identityproviderbase. Saying delete an userflowidentityprovider makes little sense.

2021-07-08 04:26 UTC, opbld30 commented
Docs Build status updates of commit _[af9be36](https://github.com/namkedia/microsoft-graph-docs/commits/af9be36e528c99f844a10e491b38656a2603ecd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-6f465dd7)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-6f465dd7)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-6f465dd7)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-6f465dd7)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-6f465dd7)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-6f465dd7)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-6f465dd7)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-6f465dd7"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:28 UTC, opbld33 commented
Docs Build status updates of commit _[9a2e65a](https://github.com/namkedia/microsoft-graph-docs/commits/9a2e65ad2b6d2ab1c719c47500eee1b77bf5b435)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-f4cb7969)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-f4cb7969)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-f4cb7969)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-f4cb7969)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-f4cb7969)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-f4cb7969)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-f4cb7969)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-f4cb7969"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:29 UTC, opbld31 commented
Docs Build status updates of commit _[cf4b116](https://github.com/namkedia/microsoft-graph-docs/commits/cf4b1165a79de663a51ab79becd1aa7a69d46563)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-87517d9f)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-87517d9f)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-87517d9f)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-87517d9f)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-87517d9f)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-87517d9f)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-87517d9f)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-87517d9f"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:31 UTC, opbld30 commented
Docs Build status updates of commit _[960bab6](https://github.com/namkedia/microsoft-graph-docs/commits/960bab6a0b931d25a528155780e8d3ced13d70aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-2b58af6d)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-2b58af6d)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-2b58af6d)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-2b58af6d)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-2b58af6d)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-2b58af6d)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-2b58af6d)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-2b58af6d"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:33 UTC, opbld31 commented
Docs Build status updates of commit _[f47eefc](https://github.com/namkedia/microsoft-graph-docs/commits/f47eefcc4a4c0abd4493c0ecb9995ef75995d448)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-258f769e)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-258f769e)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-258f769e)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-258f769e)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-258f769e)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-258f769e)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-258f769e)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-258f769e"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:46 UTC, opbld32 commented
Docs Build status updates of commit _[721f4b0](https://github.com/namkedia/microsoft-graph-docs/commits/721f4b000f0aa6f610e9c581f50ec77fd7c93c4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-a202fe85)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-a202fe85)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-a202fe85)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-a202fe85)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-a202fe85)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-a202fe85)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-a202fe85)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-a202fe85"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:51 UTC, opbld30 commented
Docs Build status updates of commit _[8349322](https://github.com/namkedia/microsoft-graph-docs/commits/83493224861fa17f6f4b18da2ea2048926d30b0a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-08a37f0a)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-08a37f0a)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-08a37f0a)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-08a37f0a)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-08a37f0a)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-08a37f0a)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-08a37f0a)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-08a37f0a"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:54 UTC, opbld31 commented
Docs Build status updates of commit _[f57b81f](https://github.com/namkedia/microsoft-graph-docs/commits/f57b81f857c417732ac943fd8c9d1c7c029e87c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-2032225d)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-2032225d)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-2032225d)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-2032225d)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-2032225d)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-2032225d)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-2032225d)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-2032225d"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-08 04:55 UTC, opbld30 commented
Docs Build status updates of commit _[8349322](https://github.com/namkedia/microsoft-graph-docs/commits/83493224861fa17f6f4b18da2ea2048926d30b0a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-b3243798)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-b3243798)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-b3243798)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-b3243798)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-b3243798)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-b3243798)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-b3243798)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-b3243798"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-09 03:05 UTC, opbld30 commented
Docs Build status updates of commit _[339c64c](https://github.com/namkedia/microsoft-graph-docs/commits/339c64c63b6dbe5ccc7f04479aa10a6b25045d91)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-15589d1aeb0faca926dda48f87683b6d-bac74d92)
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-bac74d92)
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-1da19d1e6290cf082ca093edb7bb2d0c-bac74d92)
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d44c64dfb59a241d722d55b80ccbf65f-bac74d92)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-bac74d92)
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-a4cf648620203a2ed60eb36345b20c3e-bac74d92)
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-23fc19ab24a6ee23d90412efe3edc676-bac74d92)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="15589d1aeb0faca926dda48f87683b6d-bac74d92"></a>
### [api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md(2,8), beta/api/identityproviderbase-delete.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2021-07-09 03:18 UTC, namkedia commented on api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md
> +Delete an identity provider from a [b2xIdentityUserFlow](../resources/b2xidentityuserflow.md) object. For self-service sign up user flows, the values can be `Google-OAUTH` or `Facebook-OAUTH`.
There is not.

2021-07-09 03:24 UTC, namkedia commented on api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md
> +In the request body, provide a JSON representation of the `id` of the [identityProvider](../resources/identityproviderbase.md) you want to add. For self-service sign up user flows, the values can be
b2xuserfows are self service sign up userflows. There are different documents for other userflows aka b2c. We do not need to mention that here.

2021-07-09 03:31 UTC, opbld34 commented
Docs Build status updates of commit _[09e6c38](https://github.com/namkedia/microsoft-graph-docs/commits/09e6c386c6493a80453780facf0cb5e2dd4f0dfb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-097f6588)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-097f6588)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="d654518bd6adc9b18abf0e3002e6be26-097f6588"></a>
### [api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List a userflowidentityproviders - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-list-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List a userflowidentityproviders' is duplicated with other articles: 'beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(10,1), beta/api/b2xidentityuserflow-list-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e1ffd8e4aefab08494bbc139e2c297b5-097f6588"></a>
### [api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userfl [...]

2021-07-13 04:38 UTC, opbld34 commented
Docs Build status updates of commit _[ccf5a38](https://github.com/namkedia/microsoft-graph-docs/commits/ccf5a38c8d78780177b863b6fe1dcfe97c78e0d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-d654518bd6adc9b18abf0e3002e6be26-4d119175)
[api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) | [Details](#user-content-e1ffd8e4aefab08494bbc139e2c297b5-4d119175)
[api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2cidentityuserflow-userflowidentityproviders-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-userflowidentityproviders-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-userflowidentityproviders-update?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-delete-userflowidentityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-delete-userflowidentityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-list-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/api/b2xidentityuserflow-userflowidentityproviders-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow-userflowidentityproviders-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-userflowidentityproviders-update?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2cidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2cidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/resources/b2xidentityuserflow.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/resources/b2xidentityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-delete-identityproviders?view=graph-rest-beta&branch=pr-en-us-12583) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="d654518bd6adc9b18abf0e3002e6be26-4d119175"></a>
### [api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2cidentityuserflow-list-userflowidentityproviders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List a userflowidentityproviders - Microsoft Graph beta' is duplicated in: 'beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(2,8), beta/api/b2xidentityuserflow-list-userflowidentityproviders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List a userflowidentityproviders' is duplicated with other articles: 'beta/api/b2cidentityuserflow-list-userflowidentityproviders.md(10,1), beta/api/b2xidentityuserflow-list-userflowidentityproviders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="e1ffd8e4aefab08494bbc139e2c297b5-4d119175"></a>
### [api-reference/beta/api/b2xidentityuserflow-list-userflowidentityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/userflowidp/api-reference/beta/api/b2xidentityuserflow [...]

2021-07-13 04:41 UTC, merged