Update insights-customize-item-insights-privacy.md
microsoftgraph/microsoft-graph-docs pull request #12596
Opened 2021-05-04 15:04 UTC by elmakhmu

Adding sub-topics 
1) about what are item insights 
2) new toggles in MAC

2021-05-04 15:05 UTC, elmakhmu commented
@angelgolfer-ms  could you, please, have a look on this PR dedicated to support new admin toggles of existing APIs

2021-05-04 15:06 UTC, opbld31 commented
Docs Build status updates of commit _[25b50f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25b50f0452fdc71a55f717f67e8c0bee33001d6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-d5541b10)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-d5541b10)

<a id="25f5577e9853acc2648990df5c8a6d5c-d5541b10"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 20, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 23, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Customizing item insights privacy in Microsoft Graph (preview)') are not allowed. You can only have one top-level heading.`````
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f5822fe3902110f37fa319085bfe096b-d5541b10"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md)
 - **Line 286, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#how-to-configure-item-insights-setting-via-powershell' in 'insights-customize-item-insights-privacy.md', did you mean '#how-to-configure-item-insights-settings-via-powershell'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105041504111364-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QVZOxXBOdDueBfcNcSt6uqjX6M%2FCZXyjoqwizsj35bg%3D&st=2021-05-04T15%3A01%3A17Z&se=2021-06-04T15%3A06%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 00:49 UTC, angelgolfer-ms commented on concepts/insights-customize-item-insights-privacy.md
> +Learn more about safe computation, usefulness, powering different experience of item insights here [TODO link]
Line 18:
@elmakhmu , what's supposed to be that "TODO link" linking to?

2021-05-27 00:57 UTC, opbld32 commented
Docs Build status updates of commit _[e108152](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1081522006b1d1da83ae562b7813f39d44a7d9c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-faa260f5)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-faa260f5)

<a id="25f5577e9853acc2648990df5c8a6d5c-faa260f5"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 20, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 23, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Customizing item insights privacy in Microsoft Graph (preview)') are not allowed. You can only have one top-level heading.`````
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="f5822fe3902110f37fa319085bfe096b-faa260f5"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md)
 - **Line 374, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#how-to-configure-item-insights-setting-via-powershell' in 'insights-customize-item-insights-privacy.md', did you mean '#how-to-configure-item-insights-settings-via-powershell'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270056215465-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3SzcuBJhgo8wXgxLernVldTIUg1z5fE7Punwnpq9cnY%3D&st=2021-05-27T00%3A52%3A52Z&se=2021-06-27T00%3A57%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 06:55 UTC, angelgolfer-ms commented on concepts/insights-customize-item-insights-privacy.md
> +# Item insights
@elmakhmu , did you mean to retitle this topic to "Item insights"? There should be just one H1 header in a topic and that becomes the topic title. Right now there are two H1 headers (line 10 and line 23).

I think you probably meant to keep the same filename and topic title "Customizing item insights privacy in Microsoft Graph (preview)". The few paragraphs you added (lines 12-18) are indeed general information about item insights.  

Do you plan to have this PR 12596 merged before PR [11518](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11518) which contains the new item-insights-overview.md?

If that's your plan, before PR 11518 (and item-insights-overview.md) is merged, we can keep those few paragraphs as a section in this topic (insights-customize-item-insights-privacy.md). We'll keep the topic title the same ("Customizing item insights privacy in Microsoft Graph (preview)"), and title the first section as "What are item insights?".

When you are ready to get PR 11518 (and the new topic item-insight-overview.md) merged into the repo, then you should please make sure only one topic, item-insight-overview.md, has overview info for item insights. That means by that point, you should please move any unique content from lines 12-18 in this topic insights-customize-item-insights-privacy.md, to the new item-insight-overview.md. There should be just one topic that contains item insights overview. Our topics are not independent articles; we understand customers have limited time, so we try to present only the content they expect, and do not include redundancy.

2021-05-27 06:57 UTC, angelgolfer-ms commented on concepts/insights-customize-item-insights-privacy.md
> +# Item insights
In the interest of time, I am going to assume PR 12596 gets merged before PR 11518, and make lines 12-18 an introductory section "What are item insights?".

2021-05-27 08:50 UTC, opbld34 commented
Docs Build status updates of commit _[de54d5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de54d5fef645f4c1d29f6fb62333465386c0bf5d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-be58ebf3)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-be58ebf3)

<a id="f5822fe3902110f37fa319085bfe096b-be58ebf3"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md)
 - **Line 374, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#how-to-configure-item-insights-setting-via-powershell' in 'insights-customize-item-insights-privacy.md', did you mean '#how-to-configure-item-insights-settings-via-powershell'?`````

<a id="25f5577e9853acc2648990df5c8a6d5c-be58ebf3"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270849341747-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FBkuqQtEckturpyB8t%2Fr6Jq%2B8mAEW2cwk9DfaKqhU24%3D&st=2021-05-27T08%3A45%3A56Z&se=2021-06-27T08%3A50%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 08:52 UTC, opbld30 commented
Docs Build status updates of commit _[f808d6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f808d6bff4e4914b4f3148dbf98b499512538766)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-f7dcb860)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-f7dcb860)

<a id="f5822fe3902110f37fa319085bfe096b-f7dcb860"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md)
 - **Line 374, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#how-to-configure-item-insights-setting-via-powershell' in 'insights-customize-item-insights-privacy.md', did you mean '#how-to-configure-item-insights-settings-via-powershell'?`````

<a id="25f5577e9853acc2648990df5c8a6d5c-f7dcb860"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270851297911-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c%2F8%2BdrDg4JmjitlV8GS3sZ7xLjrDtry7N2CL2bI%2BTLs%3D&st=2021-05-27T08%3A47%3A39Z&se=2021-06-27T08%3A52%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 08:59 UTC, angelgolfer-ms requested changes
@elmakhmu , FYI I rephrased some of the sentences in this PR. 
Please take a look at my commit.
Please take a look at the couple of comments I left. 
In particular, line 18 seems to be missing a link, please add the link.

Please let me know if you have any comments on my edits by 5/27 in the morning PST, as I'll be OOF after 5/27. Thanks!

2021-05-27 14:16 UTC, elmakhmu commented on concepts/insights-customize-item-insights-privacy.md
> +Learn more about safe computation, usefulness, powering different experience of item insights here [TODO link]
@angelgolfer-ms link to overview topic to item insights for end users https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md from that [PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11518/)

2021-05-27 14:23 UTC, elmakhmu commented on concepts/insights-customize-item-insights-privacy.md
> +# Item insights
@angelgolfer-ms I would like to leave the topic name as "Customizing item insights privacy in Microsoft Graph (preview)", just add some short intro about itemInsights since the entire text is devoted for customizing only. I was thinking when admins will come visit this page from the link in MAC toggles, firstly they will like to know what is item insights, not how to tune it via MSGraph APIs

I am planning to publish first  PR 12596, and later completely separately PR 11518. Ok, I see you point about having all overview info in one place. NP, I can delete "What are item insights?" from this topic when ready to publish PR 11518

2021-05-27 14:29 UTC, elmakhmu commented on concepts/insights-customize-item-insights-privacy.md
> +Learn more about safe computation, usefulness, powering different experience of item insights here [TODO link]
since the link will not be live on the moment of publishing this PR, make sense to delete this sentence.

2021-05-27 14:33 UTC, opbld33 commented
Docs Build status updates of commit _[e98b152](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e98b15246172eadad5d003c04ee4053ffe4cabaa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-f0593465)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-f0593465)

<a id="f5822fe3902110f37fa319085bfe096b-f0593465"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md)
 - **Line 374, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#how-to-configure-item-insights-setting-via-powershell' in 'insights-customize-item-insights-privacy.md', did you mean '#how-to-configure-item-insights-settings-via-powershell'?`````

<a id="25f5577e9853acc2648990df5c8a6d5c-f0593465"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271432493866-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A6pFZcy%2FC5CHK3HL0Bc%2Bhdzvq5qjTym0S0YPn8R7%2Fys%3D&st=2021-05-27T14%3A28%3A57Z&se=2021-06-27T14%3A33%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 02:03 UTC, angelgolfer-ms commented on concepts/insights-customize-item-insights-privacy.md
> +# Item insights
Sounds good, @elmakhmu .
Btw, I ended up not adding the section title "What are item insights?", because that introductory content currently begins the  insights-customize-item-insights-privacy.md topic, and technically we shouldn't begin a topic right after the topic title with a section title. If we want a section title in this case, then we'd have to add some text before the section title, but I feel there isn't anything else that makes sense to add before the introductory content.

2021-05-28 03:11 UTC, opbld32 commented
Docs Build status updates of commit _[88a147a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88a147a338d67f6d24e5a4704206675c22e28957)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-5418a945)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-5418a945)

<a id="f5822fe3902110f37fa319085bfe096b-5418a945"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md)
 - **Line 374, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#how-to-configure-item-insights-setting-via-powershell' in 'insights-customize-item-insights-privacy.md', did you mean '#how-to-configure-item-insights-settings-via-powershell'?`````

<a id="25f5577e9853acc2648990df5c8a6d5c-5418a945"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280309490588-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9Il0wSzsbbAJKy1C9tzCTOz074IYuG1AuwCHvKNqm1Q%3D&st=2021-05-28T03%3A06%3A22Z&se=2021-06-28T03%3A11%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 03:12 UTC, opbld34 commented
Docs Build status updates of commit _[4eae12e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4eae12e794ba88f0de63a63c6c19b51df7bef5a2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-f1a29000)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-f1a29000)

<a id="f5822fe3902110f37fa319085bfe096b-f1a29000"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md)
 - **Line 374, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#how-to-configure-item-insights-setting-via-powershell' in 'insights-customize-item-insights-privacy.md', did you mean '#how-to-configure-item-insights-settings-via-powershell'?`````

<a id="25f5577e9853acc2648990df5c8a6d5c-f1a29000"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280311005646-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U5vWrm4xFdKWV2Vb%2B4g4H766cnsX%2Fb9hpRa9UWTPqo8%3D&st=2021-05-28T03%3A07%3A46Z&se=2021-06-28T03%3A12%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 03:17 UTC, opbld32 commented
Docs Build status updates of commit _[0f12a9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f12a9bf1f9e3b596a40902be70217d066fac0a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-d8777799)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) |

<a id="25f5577e9853acc2648990df5c8a6d5c-d8777799"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280316425670-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2LX9zQuEN71M92ocV41MRjnt8tUSUoUNKhsB6HwOzVs%3D&st=2021-05-28T03%3A12%3A56Z&se=2021-06-28T03%3A17%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 03:19 UTC, opbld30 commented
Docs Build status updates of commit _[9c54a44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c54a440b9bac4ebaada5cbd48b3c486f1d7844d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-12596) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-0000fae1)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/whats-new-earlier.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12596) |

<a id="25f5577e9853acc2648990df5c8a6d5c-0000fae1"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-9/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280317480731-12596%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ILNSxhQ%2BzQ9KxNryVienXI%2FAtLAsyXFl8PxyGa70xa4%3D&st=2021-05-28T03%3A14%3A21Z&se=2021-06-28T03%3A19%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 03:56 UTC, merged