[CloudPC]Add supported app-only permissions for APIs
microsoftgraph/microsoft-graph-docs pull request #12628
Opened 2021-05-06 07:29 UTC by AshleyYangSZ

2021-05-06 07:29 UTC, opbld32 commented
Docs Build status updates of commit _[83a1397](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83a1397334b686f35db8b5e19eebdec3d4f985fb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a3dd9a43)

<a id="a3dd9a43"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105060729222468-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eB%2B01l74JADB4VBTdLogPRhGgA%2FUUYiqAAhWQdW0TGk%3D&st=2021-05-06T07%3A24%3A36Z&se=2021-06-06T07%3A29%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 07:30 UTC, opbld33 commented
Docs Build status updates of commit _[a7dd78e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7dd78e8a2632fa5bc30204848054c69f45645d3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b9ca6336)

<a id="b9ca6336"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105060730339963-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0MqTOmwapDeGXDYZ8mE5nc%2BjZ9Nq2Kuv6em5U6uQcjs%3D&st=2021-05-06T07%3A25%3A46Z&se=2021-06-06T07%3A30%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 07:37 UTC, opbld32 commented
Docs Build status updates of commit _[322d3ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/322d3ffa101e149a7b7be654ca523aadd8beb18b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105060736138159-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ViTG5ZJ6x2Qb3DtbZkgfss6uYDr4mH0DVm72d%2BCOasY%3D&st=2021-05-06T07%3A32%3A25Z&se=2021-06-06T07%3A37%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca116 [...]

2021-05-07 06:13 UTC, opbld33 commented
Docs Build status updates of commit _[003a0d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/003a0d816870e98dd4ec16b15209daa4893d0bc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105070611435484-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r0XPnoYzVcWEeEyYt2NAeFQ9%2BCchIUSJGbusS7itKsE%3D&st=2021-05-07T06%3A08%3A52Z&se=2021-06-07T06%3A13%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca116 [...]

2021-05-08 23:47 UTC, Lauragra commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added supported app only permissions for [cloudPc-get](https://docs.microsoft.com/en-us/graph/api/cloudPc-get?view=graph-rest-beta), [cloudPc-list](https://docs.mi
Add a hyphen to "app-only", and use the friendly names for the operations instead of the file name (Get cloudPC, etc.).

2021-05-10 03:02 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added supported app only permissions for [cloudPc-get](https://docs.microsoft.com/en-us/graph/api/cloudPc-get?view=graph-rest-beta), [cloudPc-list](https://docs.mi
Updated. @Lauragra

2021-05-10 16:01 UTC, Lauragra approved these changes

2021-05-10 16:02 UTC, opbld31 commented
Docs Build status updates of commit _[0e4ab52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e4ab52a2324e71c30a65494b88aefdca1432f6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105101601334024-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YjqkV%2FVOH8wiYBW7ycBPFaCqUPId3%2Bdkj%2Fnwp4H5TZ4%3D&st=2021-05-10T15%3A57%3A51Z&se=2021-06-10T16%3A02%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecff [...]

2021-05-10 18:07 UTC, opbld31 commented
Docs Build status updates of commit _[f4e8799](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4e8799dae5da6d002120f7bf1bbdf42a6829cd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105101805157454-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Cc4CiaFtnyoDvOqS%2BNDCh2jvF1Jn4p%2Fn1ftZBSGfZpQ%3D&st=2021-05-10T18%3A02%3A20Z&se=2021-06-10T18%3A07%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca [...]

2021-05-10 18:08 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "ApiChange": "Permissions",
Lines 5-36:
@AshleyYangSZ , please take a look at the examples in the CDK (last 2 examples here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples), and set the attributes in each ChangeList record the similar way.

In particular, please use singular "Permission" for the ApiChange attribute.

2021-05-11 03:50 UTC, opbld31 commented
Docs Build status updates of commit _[0021cf3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0021cf3479020ca78ed49468171925eaa4b5ae2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105110349398660-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fcqq5ftNU89uO%2ByAC3TJ0XJuHLPW89ZGWB%2FKloXKfbg%3D&st=2021-05-11T03%3A45%3A51Z&se=2021-06-11T03%3A50%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecff [...]

2021-05-12 08:07 UTC, angelgolfer-ms requested changes
Hi @AshleyYangSZ , I gave more explanation in Teams how to assign the Target property depending on the content in the Description.

Basically, if you're adding a permission to an action or function, you should specify Target as the name of the action or function. Only one value (one action or function name) at a time for Target.

If you're adding the same permission to one or more CRUD operations of a certain entity, then you can specify Target as the parent entity name. In this case, your description can include the one or multiple CRUD operations, which have the same parent entity.

2021-05-12 08:22 UTC, opbld32 commented
Docs Build status updates of commit _[2671df2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2671df2f5045af481313f788e9f38a9539b5b74d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105120819546931-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aTa4fUcVUh1uOgvWXFEievYq31yKpL3BWrk0fe%2FHjqE%3D&st=2021-05-12T08%3A17%3A09Z&se=2021-06-12T08%3A22%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca11 [...]

2021-05-12 08:45 UTC, AshleyYangSZ commented
> Hi @AshleyYangSZ , I gave more explanation in Teams how to assign the Target property depending on the content in the Description.
> 
> Basically, if you're adding a permission to an action or function, you should specify Target as the name of the action or function. Only one value (one action or function name) at a time for Target.
> 
> If you're adding the same permission to one or more CRUD operations of a certain entity, then you can specify Target as the parent entity name. In this case, your description can include the one or multiple CRUD operations, which have the same parent entity.

Hi @angelgolfer-ms , sorry for my inattention, I updated it. And for cloudpc onpremises connection entity it only support List and get operation for app-only permissions, do I need to add some additional message to indicate this?

2021-05-13 03:07 UTC, opbld34 commented
Docs Build status updates of commit _[534e784](https://github.com/microsoftgraph/microsoft-graph-docs/commits/534e784abc5b5777687bb0ad291264001fefcc37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105130306080515-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KT6iB%2FPV9CabsupvjibRGw6TM%2F%2BUrrNcrgNqTz7XsUY%3D&st=2021-05-13T03%3A02%3A45Z&se=2021-06-13T03%3A07%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecff [...]

2021-05-13 03:10 UTC, opbld30 commented
Docs Build status updates of commit _[6e1c903](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e1c903e01981e30df43acd97a8570e1817bc479)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105130306548181-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kEsHHn5zR%2BBb60ttK74anmzHjQtBESG1In25EEbj7QY%3D&st=2021-05-13T03%3A05%3A00Z&se=2021-06-13T03%3A10%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca11 [...]

2021-05-13 03:33 UTC, opbld34 commented
Docs Build status updates of commit _[805d0e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/805d0e772dbe412bb2ff324263bcbd6b6dc5ed85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpc-reprovision.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12628) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/appOnlyScopes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105130331547065-12628%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iATxhRiKHSspZY39O2sLj%2F63%2BugL%2BpohLiKvpqpK8Zo%3D&st=2021-05-13T03%3A28%3A06Z&se=2021-06-13T03%3A33%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecff [...]

2021-05-13 03:35 UTC, angelgolfer-ms approved these changes
Thanks for the fixes, @AshleyYangSZ .
FYI the link text to resources in the changelog JSON should use the actual resource names, instead of breaking the name up into words in natural language. I made those fixes.

2021-05-13 03:35 UTC, merged