Adding disabledByMicrosoftStatus property for App and SP resources
microsoftgraph/microsoft-graph-docs pull request #12678
Opened 2021-05-10 21:15 UTC by tilarso

Adding disabledByMicrosoftStatus to App and SP resources to reflect when an application has been disabled by Microsoft due to a violation of our ToU / found to be malicious in nature.

2021-05-10 21:18 UTC, opbld31 commented
Docs Build status updates of commit _[52695e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52695e5968765fad01140e7bdc711ead2981e6e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-8b641f6a)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-8b641f6a)
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) | [Details](#user-content-48a7f987a50112421e49e6fddf6a9702-8b641f6a)
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) |
[api-reference/v1.0/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-8b641f6a"></a>
### [api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/application.md)
 - **Line 67, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="436c9311274b0a6f54e0ccb92667511d-8b641f6a"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/serviceprincipal.md)
 - **Line 41, Column 271**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/saas-apps/tutorial-list' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 86, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="48a7f987a50112421e49e6fddf6a9702-8b641f6a"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 191**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105102115509056-12678%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5bH3GFZ3aURidzYn9B1hAeqOI52ZavwXgOtNTvJjR54%3D&st=2021-05-10T21%3A13%3A02Z&se=2021-06-10T21%3A18%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-17 15:18 UTC, FaithOmbongi requested changes

2021-05-17 15:18 UTC, FaithOmbongi commented on api-reference/beta/resources/application.md
> +|disabledByMicrosoftStatus|String|Specifies if the registered application object has been disabled by Microsoft and the reason why. These reasons may include suspicious/abusive activity, malicious ac
```suggestion
| disabledByMicrosoftStatus | String | Specifies whether Microsoft has disabled the registered application. Possible values are: `null` (default value), `NotDisabled`, and `DisabledDueToViolationOfServicesAgreement` (reasons may include suspicious, abusive, or malicious activity, or a violation of the Microsoft Services Agreement). |
```

2021-05-17 15:18 UTC, FaithOmbongi commented on api-reference/beta/resources/serviceprincipal.md
> +|disabledByMicrosoftStatus|String|Specifies if the registered application object has been disabled by Microsoft and the reason why. These reasons may include suspicious/abusive activity, malicious ac
```suggestion
| disabledByMicrosoftStatus | String | Specifies whether Microsoft has disabled the registered application. Possible values are: `null` (default value), `NotDisabled`, and `DisabledDueToViolationOfServicesAgreement` (reasons may include suspicious, abusive, or malicious activity, or a violation of the Microsoft Services Agreement). |
```

2021-05-17 15:18 UTC, FaithOmbongi commented on api-reference/v1.0/resources/application.md
> +|disabledByMicrosoftStatus|String|Specifies if the registered application object has been disabled by Microsoft and the reason why. These reasons may include suspicious/abusive activity, malicious ac
```suggestion
| disabledByMicrosoftStatus | String | Specifies whether Microsoft has disabled the registered application. Possible values are: `null` (default value), `NotDisabled`, and `DisabledDueToViolationOfServicesAgreement` (reasons may include suspicious, abusive, or malicious activity, or a violation of the Microsoft Services Agreement). |
```

2021-05-17 15:18 UTC, FaithOmbongi commented on api-reference/v1.0/resources/serviceprincipal.md
> +|disabledByMicrosoftStatus|String|Specifies if the registered application object has been disabled by Microsoft and the reason why. These reasons may include suspicious/abusive activity, malicious ac
```suggestion
| disabledByMicrosoftStatus | String | Specifies whether Microsoft has disabled the registered application. Possible values are: `null` (default value), `NotDisabled`, and `DisabledDueToViolationOfServicesAgreement` (reasons may include suspicious, abusive, or malicious activity, or a violation of the Microsoft Services Agreement). |
```

2021-05-17 15:18 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    },
- Looks like Application.ReadWrite.OwnedBy is an existing permission. No changelog entry required.
- Add entries for disabledByMicrosoftStatus to servicePrincipal resource (beta), and to both application resource (beta, v1.0). Add v1.0 & beta entries as separate changelog objects because the `"Version": "v1.0"`, line.

2021-05-21 15:34 UTC, opbld34 commented
Docs Build status updates of commit _[8fb3a19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fb3a195e064a016d48723040a8ed63f6d6be99b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8d3da41d)

<a id="8d3da41d"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211533566537-12678%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aPnkWnk6WTKIB6ykJwt8WbNVb1vzNmaqbsKD1NZQJ%2B4%3D&st=2021-05-21T15%3A29%3A11Z&se=2021-06-21T15%3A34%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 15:35 UTC, opbld30 commented
Docs Build status updates of commit _[a0a999d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0a999dcaf114320a9d59cc016b5225666d85078)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-058834f3)

<a id="058834f3"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211534019339-12678%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ejM5PAWpm0h2GR1yH93WUiQl28zWv4YTqWCXFXxPri0%3D&st=2021-05-21T15%3A30%3A41Z&se=2021-06-21T15%3A35%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 15:36 UTC, opbld33 commented
Docs Build status updates of commit _[7cfd38f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cfd38f064f1f354dcd602cd16e906a038aa1a8f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-13c105ca)

<a id="13c105ca"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211534355150-12678%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ChNRThMWbm%2FHXJiCB27KRmuaYY%2BT7TfT%2FgtTXKu7PXI%3D&st=2021-05-21T15%3A31%3A05Z&se=2021-06-21T15%3A36%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 15:45 UTC, tilarso reviewed
Approved changes ssuggested

2021-05-21 16:22 UTC, FaithOmbongi approved these changes
Approved with changelog fix requested.

2021-05-21 16:22 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +    {
Add another changelog object for additions to the beta version.
The id's should be similar for all entries of a changelog object. (Seems this was a stub generator bug)

2021-05-25 23:13 UTC, jesakowi approved these changes
Looks good to me

2021-05-26 20:01 UTC, opbld32 commented
Docs Build status updates of commit _[e119652](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e119652e6e86c178130b168f3e133c8fd27d97b1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dd3bde29)

<a id="dd3bde29"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105262000498122-12678%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XS%2B109nEzHstmh6Ok0FyeYcik%2F7CJQAUgu5g7td8vgk%3D&st=2021-05-26T19%3A56%3A22Z&se=2021-06-26T20%3A01%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 01:36 UTC, opbld30 commented
Docs Build status updates of commit _[fc2948c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc2948c4eef1c5141486ec84cd9ed4cb046c8f8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-c256e254)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-c256e254)
[api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) | [Details](#user-content-48a7f987a50112421e49e6fddf6a9702-c256e254)
[api-reference/beta/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) |
[api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&branch=pr-en-us-12678) (graph-rest-beta) |
[api-reference/v1.0/api/application-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/api/serviceprincipal-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-12678) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-c256e254"></a>
### [api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/application.md)
 - **Line 67, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="436c9311274b0a6f54e0ccb92667511d-c256e254"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/beta/resources/serviceprincipal.md)
 - **Line 86, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="48a7f987a50112421e49e6fddf6a9702-c256e254"></a>
### [api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-10-tilarso-applicationstatus/api-reference/v1.0/resources/application.md)
 - **Line 61, Column 191**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106080134567645-12678%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VSjw%2Btf7iJoA7C%2Frjw7wLsY0YqPZsa7ErNhdotZlajs%3D&st=2021-06-08T01%3A31%3A27Z&se=2021-07-09T01%3A36%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 01:39 UTC, merged