Adding CDN properties for Organization Branding images
microsoftgraph/microsoft-graph-docs pull request #12671
Opened 2021-05-10 11:29 UTC by nkimaina

2021-05-10 11:30 UTC, opbld34 commented
Docs Build status updates of commit _[d390262](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d39026279eadbf228d72d48db5be78eaff55062b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) | [Details](#user-content-90592e6421307e4e6ae931d0003205f5-6f00d6fa)
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

<a id="90592e6421307e4e6ae931d0003205f5-6f00d6fa"></a>
### [api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md)
 - **Line 15, Column 200**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/azure/active-directory/fundamentals/active-directory-get-started-premium' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105101129060582-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Wwca128%2Bg3Rcl27QGlY28lhBd%2FDpZAldQIWZdzIWItI%3D&st=2021-05-10T11%3A25%3A20Z&se=2021-06-10T11%3A30%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 10:17 UTC, FaithOmbongi requested changes
In the CREATE API:

1. **Request body** section, add the sentence:

"_In the request body, supply a JSON representation of organizationalBrandingProperties object. The following table lists the properties that are required when you create the default branding._"

2. Are these additional properties required? @AlexanderMars, looping you in to confirm the existing properties.
3. On this note, for required properties, add "Required" to their descriptions in organizationalbrandingproperties.md.

2021-05-12 10:17 UTC, FaithOmbongi commented on api-reference/beta/api/organizationalbrandingproperties-update.md
> +|squareLogoDark|Stream|Dark square version of your company logo. This appears in Windows 10 out-of-box (OOBE) experiences and when Windows Autopilot is enabled for deployment. .png or .jpg no larger
```suggestion
|bannerLogo|Stream|A banner version of your company logo which appears on the sign-in page. Allowed types are PNG or JPEG no larger than 36 × 245 pixels. We recommend a transparent image with no padding around the logo.|
|signInPageText|String|Text that appears at the bottom of the sign-in box. You can use this to communicate additional information, such as the phone number to your help desk or a legal statement. This text must be Unicode and not exceed 1024 characters.|
|squareLogo|Stream|Square version of your company logo that appears in Windows 10 out-of-box experiences (OOBE) and when Windows Autopilot is enabled for deployment. Allowed types are PNG or JPEG no larger than 240 ⅹ 240 pixels and no more than 10 KB in size. We recommend a transparent image with no padding around the logo.|
|squareLogoDark|Stream| A dark square version of your company logo that appears in Windows 10 out-of-box experiences (OOBE) and when Windows Autopilot is enabled for deployment. Allowed types are PNG or JPEG no larger than 240 ⅹ 240 pixels and no more than 10 KB in size. We recommend a transparent image with no padding around the logo. |
```

2021-05-12 10:17 UTC, FaithOmbongi commented on api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md
> +|squareLogoDark|Stream| A dark square version of your company logo. This appears in Windows 10 out-of-box (OOBE) experiences and when Windows Autopilot is enabled for deployment. .png or .jpg no larg
```suggestion
|bannerLogo|Stream|A banner version of your company logo which appears on the sign-in page. Allowed types are PNG or JPEG no larger than 36 × 245 pixels. We recommend a transparent image with no padding around the logo.|
|signInPageText|String|Text that appears at the bottom of the sign-in box. You can use this to communicate additional information, such as the phone number to your help desk or a legal statement. This text must be Unicode and not exceed 1024 characters.|
|squareLogo|Stream|Square version of your company logo that appears in Windows 10 out-of-box experiences (OOBE) and when Windows Autopilot is enabled for deployment. Allowed types are PNG or JPEG no larger than 240 ⅹ 240 pixels and no more than 10 KB in size. We recommend a transparent image with no padding around the logo.|
|squareLogoDark|Stream| A dark square version of your company logo that appears in Windows 10 out-of-box experiences (OOBE) and when Windows Autopilot is enabled for deployment. Allowed types are PNG or JPEG no larger than 240 ⅹ 240 pixels and no more than 10 KB in size. We recommend a transparent image with no padding around the logo. |
```

2021-05-12 10:17 UTC, FaithOmbongi commented on api-reference/beta/resources/organizationalbrandingproperties.md
> +  "squareLogoDark": "Stream",
Add all new properties here.

2021-05-12 18:15 UTC, davidmu1 approved these changes

2021-06-15 11:42 UTC, opbld31 commented
Docs Build status updates of commit _[498159d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/498159d81bf47ffc4600853c0fe0de7cac97ac42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151140518944-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ujv8WKCxD0oePuXxfPJutkx70eB0dssvbUwTj02OKc8%3D&st=2021-06-15T11%3A37%3A47Z&se=2021-07-16T11%3A42%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 18:42 UTC, FaithOmbongi approved these changes

2021-06-15 18:42 UTC, FaithOmbongi commented on api-reference/beta/api/organizationalbrandingproperties-create.md
>  | Property     | Type        | Description |
```suggestion
In the request body, supply a JSON representation of [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md) object. The following table lists the properties that are required when you create the default branding.

| Property     | Type        | Description |
```

2021-06-15 18:44 UTC, opbld32 commented
Docs Build status updates of commit _[aa92d73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa92d7348df6cce98f56d56cc65d0071f836928e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151843120395-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z5frsMGfzzBZeXqQDOlRPY2rxdnDiVZRcmRP85fVJYw%3D&st=2021-06-15T18%3A39%3A45Z&se=2021-07-16T18%3A44%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 11:35 UTC, opbld34 commented
Docs Build status updates of commit _[8379043](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83790436c524119b5b2df2128af2ae2e686c8048)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106171133320978-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rbCYyYFanh0Telf11yFkfPjHyE0%2B8hPEl4NuTut0m2c%3D&st=2021-06-17T11%3A30%3A04Z&se=2021-07-18T11%3A35%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 14:33 UTC, FaithOmbongi requested changes
1. I recommend regenerating the examples to provide better context than 1/2 the properties having `null` values. If using the canary endpoint, replace that with the public endpoint in the docs.
2. List the properties in alphabetical order in both the table & JSON representation for scanability.
3. Find “ ”, replace with " ".
4. Don't forget the changelog.

2021-06-17 22:21 UTC, opbld34 commented
Docs Build status updates of commit _[02235b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02235b208a86c96c5b33c386884b2372bca9c3ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106172219309826-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IjEYwf9%2FapkLt%2BV%2BULfs1xXFEF%2FKzjSxa4JyyUPJ2E4%3D&st=2021-06-17T22%3A16%3A00Z&se=2021-07-18T22%3A21%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 09:45 UTC, opbld31 commented
Docs Build status updates of commit _[80eb34f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80eb34f0288d3f54eaf3e5a352627725a1dc3494)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106180943343347-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=44laAFzy3zPHG2AsMtlh15Dy%2Fm9iqEVarjByN94WleU%3D&st=2021-06-18T09%3A40%3A07Z&se=2021-07-19T09%3A45%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 10:12 UTC, opbld34 commented
Docs Build status updates of commit _[4626d75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4626d7504f18a3b2678b9bdec8bc891aacab865f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181010361156-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N0oCUS1epmlE2fPazMYjkn98dJ3WdbsMgZGIihQ00M8%3D&st=2021-06-18T10%3A07%3A21Z&se=2021-07-19T10%3A12%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 11:47 UTC, opbld31 commented
Docs Build status updates of commit _[53e77e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53e77e7277e251dd2faa0d5ba3e7684f31a87357)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181145036237-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iQV9T36tv7XOVSymzT1fCeLL%2FXrZKtpo%2FcARjBFolZM%3D&st=2021-06-18T11%3A41%3A59Z&se=2021-07-19T11%3A46%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 08:18 UTC, opbld31 commented
Docs Build status updates of commit _[3bc73c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bc73c93918827550578ac3ab0bcea4e9ddc2264)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106210816555966-12671%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E3a04DGIXjTAiYs%2BzMtDfqX%2BO1C4cU9%2F%2FxsL6MQBdxw%3D&st=2021-06-21T08%3A13%3A40Z&se=2021-07-22T08%3A18%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 07:54 UTC, opbld34 commented
Docs Build status updates of commit _[9c57df0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c57df09e08852c2f9c6e04146ea25469dcb2910)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[api-reference/beta/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/api-reference/beta/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&branch=pr-en-us-12671) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/org-branding-cdn-list/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107160751545333-12671%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A32%3A25Z&ske=2021-07-20T08%3A37%3A25Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T07%3A49%3A18Z&se=2021-08-16T07%3A54%3A18Z&sr=b&sp=r&sig=Fz6pYgFDry2FUa%2B6tsvpXTV87WEm2%2FqP%2BrSpBNc1VRY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-11 15:00 UTC, closed without merging