Publish teams/{team-id}/permissionGrants
microsoftgraph/microsoft-graph-docs pull request #12689
Opened 2021-05-11 18:02 UTC by jessiechan27

2021-05-11 18:03 UTC, opbld31 commented
Docs Build status updates of commit _[6ff7e00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ff7e001fe79f646dd387af77474c05c2220fb5e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/command.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/command.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/command?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-7e8db651438cd947858ad02949ab2ba9-b432d479)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-b432d479)
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |

<a id="7e8db651438cd947858ad02949ab2ba9-b432d479"></a>
### [api-reference/beta/resources/command.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/command.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 7, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'finsharp' is not a valid GitHub ID.`````
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-b432d479"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105111802201793-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MkCrg0s08AyrpXQL4J1Ce87VvP5dlZm883iRbwRb0U0%3D&st=2021-05-11T17%3A58%3A18Z&se=2021-06-11T18%3A03%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 20:51 UTC, opbld32 commented
Docs Build status updates of commit _[069eba1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/069eba16507d469b4e1bb3cd6bfe2b60ba5bd1bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-de9c0974)
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-de9c0974"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212050222165-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MgB%2BSuvAmyfRYpfka2pv2zrWsg6w2Ac%2B9aXmdU0OkCc%3D&st=2021-05-21T20%3A46%3A36Z&se=2021-06-21T20%3A51%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 18:15 UTC, opbld31 commented
Docs Build status updates of commit _[97ce360](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97ce360eab9e48161398883ee10004503d6b1aed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-2e9ae3f6)
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-2e9ae3f6"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105251814022114-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yWT7gtpWudqb%2FecFfJVta9mqT1sImXnlEFg3pTDC2c0%3D&st=2021-05-25T18%3A10%3A17Z&se=2021-06-25T18%3A15%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-26 19:10 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: List permission grants of team
'List permission grants' should suffice,

2021-05-26 19:11 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/team-list-permissiongrants.md
Please add a similar entry for chat node as well.

2021-05-26 19:12 UTC, AkJo commented on api-reference/beta/toc.yml
>          items:
Please add a fresh top-level node:

Resource specific permission
href: resources/resourcespecificpermissiongrant.md

2021-05-27 16:58 UTC, opbld32 commented
Docs Build status updates of commit _[f8e8e89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8e8e899ff3da4ec138ba5a5f8efaef030250d03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-8c7c60ac)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-8c7c60ac"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271656139533-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MC4nTCKdzNSB3SXU9fyquXkWBtcV5rFQh%2BqXBqnsF74%3D&st=2021-05-27T16%3A53%3A48Z&se=2021-06-27T16%3A58%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 00:17 UTC, opbld33 commented
Docs Build status updates of commit _[fe26ace](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe26ace5896d09f1585b541f90436df455d0c4db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-78efe28f)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-78efe28f"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290014454274-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nkKQgFxh%2BCB0YGhzwMeEvLOzIF0%2BODtahEP95aqc%2BD8%3D&st=2021-05-29T00%3A12%3A22Z&se=2021-06-29T00%3A17%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 08:55 UTC, AkJo approved these changes

2021-06-14 17:08 UTC, opbld30 commented
Docs Build status updates of commit _[21210a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21210a4c6cc900d36c37817bba39a7c5bf573213)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-4c11b0f9)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-4c11b0f9"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141706497280-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rEQ%2BYGPMDcA4Gp6YS0iD%2FP2h2WnAMfllfx52juvpHFc%3D&st=2021-06-14T17%3A03%3A18Z&se=2021-07-15T17%3A08%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 20:13 UTC, JarbasHorst requested changes

2021-06-14 20:13 UTC, JarbasHorst commented on api-reference/beta/resources/team.md
> +|permissionGrants|[resourceSpecificPermissionGrant](resourcespecificpermissiongrant.md) collection| A collection of permissions granted to apps for the team.|
For a better understanding, I recommend you updating this sentence. Suggested revision:

A collection of permissions granted to Azure AD apps to access the team.

2021-06-14 20:13 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **permissionGrants** relationship to [team](https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta) resource.",
Please, remove `en-us` from the link you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-14 21:42 UTC, JarbasHorst requested changes

2021-06-14 21:42 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +      "ChangeList": [
The ChangeList doesn't contain the new method you have added to the team resource: team-list-permissiongrants.md. Can you please update the ChangeList accordingly?

2021-06-14 22:58 UTC, jessiechan27 commented on api-reference/beta/resources/team.md
> +|permissionGrants|[resourceSpecificPermissionGrant](resourcespecificpermissiongrant.md) collection| A collection of permissions granted to apps for the team.|
Saying it's an AAD app would be incorrect, but I can update the sentence to clarify the meaning

2021-06-14 23:24 UTC, opbld34 commented
Docs Build status updates of commit _[19fbab9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19fbab9ec8237cfc0abddfdb737b32f0474a2d28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-8c99f70d)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-8c99f70d"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142322552970-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qEn7Stpbx326jUW28aOD2hFRlH5ryi2yzp7pZC%2BWLNg%3D&st=2021-06-14T23%3A19%3A22Z&se=2021-07-15T23%3A24%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 23:28 UTC, jessiechan27 commented on changelog/Microsoft.Teams.Core.json
> +      "ChangeList": [
the team-list-permissiongrants is the addition of this navigation property. This is autogenerated. This is our process for generating the changelog using the Aggregated Graph Services tooling. If you need something else, please add a link to how to generate it and the process for that

2021-06-14 23:43 UTC, opbld31 commented
Docs Build status updates of commit _[ea0cae0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea0cae0b0db3370080917da9675e10527617334b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-a90ea9a7)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-a90ea9a7"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142342035575-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gJdB73BY8wQ4NoFlx0bARcVFZMpPmiwoejOaEdmiJHo%3D&st=2021-06-14T23%3A38%3A20Z&se=2021-07-15T23%3A43%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 18:21 UTC, opbld32 commented
Docs Build status updates of commit _[b9055ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9055ea421de1b3c4792cded6f8eb6d2252368f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-1116d18d)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-1116d18d"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151820154229-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bGAuHcx4eVdpqXfEcq%2F5U06lQ7y6gCeY%2FqixfwCtJyE%3D&st=2021-06-15T18%3A16%3A41Z&se=2021-07-16T18%3A21%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 15:32 UTC, opbld33 commented
Docs Build status updates of commit _[22297be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22297be29f339f49b03b92c9c60303b95670e82d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-9541b641)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-9541b641"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161531227659-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xI7qLdxpAyQeCCkiFiRQspMcT22Ix8ODLcaZl6FsW6s%3D&st=2021-06-16T15%3A27%3A48Z&se=2021-07-17T15%3A32%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 19:24 UTC, opbld33 commented
Docs Build status updates of commit _[8d65049](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d6504961fb87a2d79142b3ff14feff9c79990b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-d1e50359)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-d1e50359"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161923118056-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xwzYY5XLfurVA2A5vjYSEfqYolwQuRVfl7XX1ix0Zw4%3D&st=2021-06-16T19%3A19%3A45Z&se=2021-07-17T19%3A24%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 19:52 UTC, opbld32 commented
Docs Build status updates of commit _[22297be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22297be29f339f49b03b92c9c60303b95670e82d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-1ab49e79)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-1ab49e79"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161950262077-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6sEiy243C%2F8LSTTQ6M7P9QuPdEYCkkoC2C6pVIITtcU%3D&st=2021-06-16T19%3A47%3A43Z&se=2021-07-17T19%3A52%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 20:24 UTC, JarbasHorst requested changes

2021-06-16 20:24 UTC, JarbasHorst commented on api-reference/beta/api/team-list-permissiongrants.md
> +  "@odata.type": "Collection(microsoft.graph.resourceSpecificPermissionGrant)"
The @odata.type value should match the definition in the Microsoft Graph metadata. In your case, the correct definition is: `microsoft.graph.resourceSpecificPermissionGrant`. Please, use the `isCollection` property to indicate an array. Suggested revision:
</br>
<!--StartFragment-->&lt;!-- {  "blockType": "response",  "@odata.type": "microsoft.graph.resourceSpecificPermissionGrant", "isCollection": true}--&gt;<!--EndFragment-->

</br></br>
API Doctor can still throw an exception because your example leaves out one property that is defined under the JSON representation section of the resource type. In this case, you can use the `truncated` property which tells API Doctor to skip the validation of the response. For example,

"truncated": true

2021-06-16 21:43 UTC, opbld33 commented
Docs Build status updates of commit _[08a3a51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08a3a512309c6d78c9b9cd05e4a9b8cf1cc638cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-8bba7742)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-8bba7742"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162141103019-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KkZ3MTH0fAcQc2YWmWay2Zg4Yeax6ZxNdwQIbcuMZsI%3D&st=2021-06-16T21%3A38%3A47Z&se=2021-07-17T21%3A43%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 21:50 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-06-16 21:59 UTC, opbld32 commented
Docs Build status updates of commit _[ae08604](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae086042d4bea0db517882295e49de43356280d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-20a57312)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-20a57312"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162158037161-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cwRhIArlZVMNVYQr%2Bmywbk8sJvU3Guoqgnz7fsSt7Yo%3D&st=2021-06-16T21%3A54%3A33Z&se=2021-07-17T21%3A59%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:00 UTC, opbld34 commented
Docs Build status updates of commit _[8e115e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e115e1039feeb46936c171dd218ec28b44850d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-4cd2f318)
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/api/team-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/api/team-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-12689) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-4cd2f318"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/team-list-permissiongrants/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162159061388-12689%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J8AvMfpAo3OI8XKyObaiUnLiVZYMwP5EdqDDrTH9DFQ%3D&st=2021-06-16T21%3A55%3A50Z&se=2021-07-17T22%3A00%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:02 UTC, merged