Add accessReviewNotificationRecipient
microsoftgraph/microsoft-graph-docs pull request #12695
Opened 2021-05-12 02:36 UTC by jingyang1114

Add definitionand API example for accessReviewNotificationRecipient

2021-05-12 02:38 UTC, opbld31 commented
Docs Build status updates of commit _[499d776](https://github.com/microsoftgraph/microsoft-graph-docs/commits/499d776a71f10f1677cb0357d8194da966117705)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-e1b9322fc0939ce092bee62cd25ee188-e364a1cc)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-e364a1cc)
[api-reference/beta/resources/command.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/command.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/command?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-7e8db651438cd947858ad02949ab2ba9-e364a1cc)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |

<a id="e1b9322fc0939ce092bee62cd25ee188-e364a1cc"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ingyangatmsft' is not a valid GitHub ID.`````

<a id="54974c7a126366e7915039e1a4dc49ee-e364a1cc"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'jingyangatmsft' is not a valid GitHub ID.`````

<a id="7e8db651438cd947858ad02949ab2ba9-e364a1cc"></a>
### [api-reference/beta/resources/command.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/command.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 7, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'finsharp' is not a valid GitHub ID.`````
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105120236528836-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GEvEfHNXyz%2BuOqNI1EhKVvMTr7HB23E4JnBvjNELNiE%3D&st=2021-05-12T02%3A33%3A12Z&se=2021-06-12T02%3A38%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 19:50 UTC, opbld31 commented
Docs Build status updates of commit _[76d83ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76d83ed0f7ffea9219058ba2e6993677bcad370f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-e1b9322fc0939ce092bee62cd25ee188-6b8a08fa)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-6b8a08fa)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |

<a id="e1b9322fc0939ce092bee62cd25ee188-6b8a08fa"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ingyangatmsft' is not a valid GitHub ID.`````

<a id="54974c7a126366e7915039e1a4dc49ee-6b8a08fa"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'jingyangatmsft' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105141948088624-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jJirsjsxOYmJnj5yYG2qoOeZKznvZrryU%2BhYQuC%2FY78%3D&st=2021-05-14T19%3A45%3A32Z&se=2021-06-14T19%3A50%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 19:53 UTC, opbld30 commented
Docs Build status updates of commit _[6e44563](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e44563fe70f8c19d4247e65e3ddcfd10fec5b2f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-94f9ea14)
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |

<a id="54974c7a126366e7915039e1a4dc49ee-94f9ea14"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'jingyangatmsft' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105141952387167-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nrl0KnEamoKLUk2Jd5I3baUskT4%2B%2FiCmKpQbu5M2KyI%3D&st=2021-05-14T19%3A48%3A57Z&se=2021-06-14T19%3A53%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 20:02 UTC, opbld33 commented
Docs Build status updates of commit _[dcda477](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcda47709b0c95adcd690a9d149dbd0fda88ea04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105142001426106-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gcswWa8OtMtrZg4djvIG9wpbd5m6fXgKtDkDIMmOWbs%3D&st=2021-05-14T19%3A57%3A55Z&se=2021-06-14T20%3A02%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 20:04 UTC, opbld32 commented
Docs Build status updates of commit _[26cbf11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26cbf1119adbd2a4a29dc7df7bed6c2a17332daf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105142003101750-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WdQlDx1lM%2FqT2RCm7p7WdKBaojA8eok%2BJm0KndjyBZ0%3D&st=2021-05-14T19%3A59%3A32Z&se=2021-06-14T20%3A04%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 22:35 UTC, opbld32 commented
Docs Build status updates of commit _[b3b514b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3b514b8ec48936426d36e0e7f52bb0faabe70c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182233439792-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kdBBPIIiCe5JDrsc9aoOqHtzyt2iLlUwsvIL0iHbeVU%3D&st=2021-05-18T22%3A30%3A06Z&se=2021-06-18T22%3A35%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 21:27 UTC, opbld34 commented
Docs Build status updates of commit _[69576e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69576e18913fa1c967e0966d563a7a6806a4706e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c6781ad5)

<a id="c6781ad5"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202127224425-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ca3vGFuu30GoIYU15W3%2FeCPZ5hPW16wRRcPubyudSKo%3D&st=2021-05-20T21%3A22%3A37Z&se=2021-06-20T21%3A27%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 22:05 UTC, opbld31 commented
Docs Build status updates of commit _[5d10c8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d10c8e9b2161364a274e8be987d683d049188f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-6c8e56d907bb167c24cbd054aac50e85-ef6e303b)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-dddc222f9c66c7ec03a24d4bae6d2ddd-ef6e303b)
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="6c8e56d907bb167c24cbd054aac50e85-ef6e303b"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-create.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create accessReviewScheduleDefinition - Microsoft Graph beta' is duplicated in: 'beta/api/accessreviewscheduledefinition-create.md(2,8), beta/api/accessreviewscheduledefinition-post.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create accessReviewScheduleDefinition' is duplicated with other articles: 'beta/api/accessreviewscheduledefinition-create.md(10,1), beta/api/accessreviewscheduledefinition-post.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Create a new accessReviewScheduleDefinition object.' is duplicated in 'beta/api/accessreviewscheduledefinition-create.md(3,14)', 'beta/api/accessreviewscheduledefinition-post.md(3,14)'.`````

<a id="dddc222f9c66c7ec03a24d4bae6d2ddd-ef6e303b"></a>
### [api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create accessReviewScheduleDefinition - Microsoft Graph beta' is duplicated in: 'beta/api/accessreviewscheduledefinition-create.md(2,8), beta/api/accessreviewscheduledefinition-post.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create accessReviewScheduleDefinition' is duplicated with other articles: 'beta/api/accessreviewscheduledefinition-create.md(10,1), beta/api/accessreviewscheduledefinition-post.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Create a new accessReviewScheduleDefinition object.' is duplicated in 'beta/api/accessreviewscheduledefinition-create.md(3,14)', 'beta/api/accessreviewscheduledefinition-post.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202204384459-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RlPFcOeVJZBbaRKH31Ec5PpzJZfjimn0Sv68gYt12UI%3D&st=2021-05-20T22%3A00%3A53Z&se=2021-06-20T22%3A05%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 22:10 UTC, opbld31 commented
Docs Build status updates of commit _[586bca6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/586bca61b9302aeea74535c98cd1872bdeffe2f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202209108878-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Cv0kvdS9ewX%2FPygprboNaSmWbucuq891qliqp7YRSWg%3D&st=2021-05-20T22%3A05%3A35Z&se=2021-06-20T22%3A10%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 22:42 UTC, opbld31 commented
Docs Build status updates of commit _[08cde35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08cde35c911a3f45693b07ec36d3d74e0f85780c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202240518239-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2p9%2B%2Fevci2cjlsMyURTHZl7bwcUvnMUwwd38MwbXLEA%3D&st=2021-05-20T22%3A37%3A04Z&se=2021-06-20T22%3A42%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 23:12 UTC, opbld31 commented
Docs Build status updates of commit _[13d9b8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13d9b8f25719527e22953cbd154cca07623f7313)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202311367076-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SSCE8yG7Ywirj6pP2xkdSg8IXf3415qalHA9HuvRyKs%3D&st=2021-05-20T23%3A07%3A49Z&se=2021-06-20T23%3A12%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 23:28 UTC, opbld30 commented
Docs Build status updates of commit _[9a09619](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a09619132dff28b4cf84cccf66c0ce31dc7e25b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202325410872-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=llROeSRIOceasrBB00kCBvJDyFuar0BMibs3NN0nre0%3D&st=2021-05-20T23%3A23%3A10Z&se=2021-06-20T23%3A28%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 23:38 UTC, opbld32 commented
Docs Build status updates of commit _[c80c81b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c80c81b82f609769d19ca341d6f7af82b10ac90c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202336569963-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JaIjXxzyhd21y5bUbrRGyGFAYE7Cl8exRWVrOHxk4eI%3D&st=2021-05-20T23%3A33%3A07Z&se=2021-06-20T23%3A38%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 00:11 UTC, opbld33 commented
Docs Build status updates of commit _[f8aa55c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8aa55c01643a47b6e6fee97aa2d995624264610)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-836e2e8a5fe3e064aca4937a1fc5dc16-3a3cd35e)
[api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/removeaccessapplyaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/removeaccessapplyaction?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-4f4130940c7df029c4f1e81d5ac4d048-3a3cd35e)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-3a3cd35e)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="836e2e8a5fe3e064aca4937a1fc5dc16-3a3cd35e"></a>
### [api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'removeAccessApplyAction resource type' is duplicated with other articles: 'beta/resources/accessReviewnotificationrecipientqueryscope.md(10,1), beta/resources/removeaccessapplyaction.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents who will receive notification for access reviews.' is duplicated in 'beta/resources/accessReviewnotificationrecipientqueryscope.md(3,14)', 'beta/resources/accessreviewnotificationrecipientscope.md(3,14)'.`````

<a id="4f4130940c7df029c4f1e81d5ac4d048-3a3cd35e"></a>
### [api-reference/beta/resources/removeaccessapplyaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/removeaccessapplyaction.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'removeAccessApplyAction resource type' is duplicated with other articles: 'beta/resources/accessReviewnotificationrecipientqueryscope.md(10,1), beta/resources/removeaccessapplyaction.md(10,1)'. First level headings must be unique within a docset.`````

<a id="54974c7a126366e7915039e1a4dc49ee-3a3cd35e"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents who will receive notification for access reviews.' is duplicated in 'beta/resources/accessReviewnotificationrecipientqueryscope.md(3,14)', 'beta/resources/accessreviewnotificationrecipientscope.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105210009507613-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AOLcEvHs68dx3vFfxnxL5mv%2Bi5ACyy%2FS3WK2nJfBRus%3D&st=2021-05-21T00%3A06%3A08Z&se=2021-06-21T00%3A11%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 00:41 UTC, opbld33 commented
Docs Build status updates of commit _[6101fb7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6101fb714fe860f903babc0ffe5655c5c6562dac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-836e2e8a5fe3e064aca4937a1fc5dc16-ffb9d8be)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-ffb9d8be)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="836e2e8a5fe3e064aca4937a1fc5dc16-ffb9d8be"></a>
### [api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents who will receive notification for access reviews.' is duplicated in 'beta/resources/accessReviewnotificationrecipientqueryscope.md(3,14)', 'beta/resources/accessreviewnotificationrecipientscope.md(3,14)'.`````

<a id="54974c7a126366e7915039e1a4dc49ee-ffb9d8be"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents who will receive notification for access reviews.' is duplicated in 'beta/resources/accessReviewnotificationrecipientqueryscope.md(3,14)', 'beta/resources/accessreviewnotificationrecipientscope.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105210040228577-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q5%2F8VfDANvm8TNLJk%2Bdckta2T%2Fu3UroEOudCOHqC9Ts%3D&st=2021-05-21T00%3A36%3A41Z&se=2021-06-21T00%3A41%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 02:05 UTC, opbld34 commented
Docs Build status updates of commit _[cd20046](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd20046c3ed9be5d16089d8fdbb2bc51bf808200)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-836e2e8a5fe3e064aca4937a1fc5dc16-0c3b6d6d)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-0c3b6d6d)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="836e2e8a5fe3e064aca4937a1fc5dc16-0c3b6d6d"></a>
### [api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents who will receive notification for access reviews.' is duplicated in 'beta/resources/accessReviewnotificationrecipientqueryscope.md(3,14)', 'beta/resources/accessreviewnotificationrecipientscope.md(3,14)'.`````

<a id="54974c7a126366e7915039e1a4dc49ee-0c3b6d6d"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Represents who will receive notification for access reviews.' is duplicated in 'beta/resources/accessReviewnotificationrecipientqueryscope.md(3,14)', 'beta/resources/accessreviewnotificationrecipientscope.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105210204363341-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a8a9LMK8pjlDZ3PR68wujGAj6ZJOjPp5bowXpjz42so%3D&st=2021-05-21T02%3A00%3A51Z&se=2021-06-21T02%3A05%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 15:00 UTC, isabelleatmsft requested changes

2021-05-21 15:00 UTC, isabelleatmsft commented on api-reference/beta/api/accessreviewscheduledefinition-post.md
> +| `additionalNotificationRecipients`   |[accessReviewNotificationRecipientItem](../resources/accessReviewNotificationRecipientItem.md) collection| Define the list of additional notification recipient
| additionalNotificationRecipients   |[accessReviewNotificationRecipientItem](../resources/accessReviewNotificationRecipientItem.md) collection| Defines the list of additional AAD users or AAD group members to be notified of review progress. |

2021-05-21 16:02 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientitem.md
> +| notificationRecipientScope |[accessReviewNotificationRecipientScope](../resources/accessreviewnotificationrecipientscope.md)  | Determines who the notification email will be sent to.|
```suggestion
| notificationTemplateType  |String  | Indicates the type of access review email to be sent. Supported template type is `CompletedAdditionalRecipients` which sends review completion notifications to the recipient.|
| notificationRecipientScope |[accessReviewNotificationRecipientScope](../resources/accessreviewnotificationrecipientscope.md)  | Determines the recipient of the notification email.|
```

2021-05-21 16:03 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientitem.md
> +Represents an Azure AD [access review](accessreviewsv2-root.md) notification event on an instance of a review. This item contains email templateType and recipient properties to enable sending certain
```suggestion
Represents an Azure AD [access review](accessreviewsv2-root.md) notification event on an instance of a review. This item contains an email template type and recipient properties to enable sending certain type of notifications for a given [access review instance](accessreviewinstance.md).
```

2021-05-21 16:03 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientitem.md
> +```
JSON representations don't have values, just types. See the child resource for reference.

2021-05-21 16:04 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +description: "Represents who will receive notification for access reviews."
```suggestion
description: "Represents who will receive access review notifications."
```

2021-05-21 16:11 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +- **accessReviewNotificationRecipientQueryScope** is a derived type of `accessReviewNotificationRecipientScope` that is expressed as an OData query. It allows notification recipients to be specified
Info on the child resource can go to the child resource's page.
```suggestion
The `accessReviewNotificationRecipientScope` represents a base class for defining users who will receive notifications on instances of [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) objects. It is inherited by **accessReviewNotificationRecipientQueryScope**.
```

2021-05-21 16:12 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +- **accessReviewNotificationRecipientQueryScope** is a derived type of `accessReviewNotificationRecipientScope` that is expressed as an OData query. It allows notification recipients to be specified
Link to accessReviewNotificationRecipientQueryScope

2021-05-21 16:13 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +
Since this if info for accessReviewNotificationRecipientQueryScope, move it there.

2021-05-21 16:14 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +            "SubArea": "Governance"
Changelog entries are in LIFO order.

2021-05-21 23:42 UTC, jingyang1114 commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +| query | String | This represents the query for what the recipients are. See table for examples. |
Thank you, updated.

2021-05-22 00:01 UTC, opbld31 commented
Docs Build status updates of commit _[2106baf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2106baf3a978441c530207060c47a2689ebc2362)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105220000290431-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IjUfnUZUV8NDVbPibt%2FAp3AWvicBcFYyCcoQSy3Djms%3D&st=2021-05-21T23%3A56%3A51Z&se=2021-06-22T00%3A01%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-22 00:11 UTC, jingyang1114 commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +Inherits from [accessreviewnotificationrecipientscope](../resources/accessreviewnotificationrecipientscope.md).
fixed.

2021-05-22 00:11 UTC, jingyang1114 commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +| queryRoot | String | In the scenario where reviewers need to be specified dynamically, this property is used to indicate the relative source of the query. This property is only required if a relati
fixed.

2021-05-22 00:11 UTC, jingyang1114 commented on api-reference/beta/resources/accessreviewnotificationrecipientitem.md
> +description: "Defines users or groups who will receive notifications on access review."
fixed.

2021-05-22 00:12 UTC, jingyang1114 commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +description: "Represents who will receive notification for access reviews."
fixed.

2021-05-22 00:12 UTC, jingyang1114 commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +- **accessReviewNotificationRecipientQueryScope** is a derived type of `accessReviewNotificationRecipientScope` that is expressed as an OData query. It allows notification recipients to be specified
fixed.

2021-05-22 00:12 UTC, jingyang1114 commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +            "SubArea": "Governance"
fixed.

2021-05-22 00:16 UTC, opbld31 commented
Docs Build status updates of commit _[cde6b80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cde6b8060e032dd4469321b9889cb7c1289cac93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105220015147340-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FNXwFmd%2BfOa2STTWixvPbNUUTy5w14OXiA4An%2BQRX34%3D&st=2021-05-22T00%3A11%3A31Z&se=2021-06-22T00%3A16%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 07:43 UTC, FaithOmbongi reviewed
Recommended minor updates + additions to changelog

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewscheduledefinition-post.md
> +| `additionalNotificationRecipients`   |[accessReviewNotificationRecipientItem](../resources/accessReviewNotificationRecipientItem.md) collection| Defines the list of additional users or group member
```suggestion
| additionalNotificationRecipients   |[accessReviewNotificationRecipientItem](../resources/accessReviewNotificationRecipientItem.md) collection| Defines the list of additional users or group members to be notified of the access review progress. |
```

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewscheduledefinition-post.md
>      "reminderNotificationsEnabled": true,
No need to add the object into the existing body

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +author: "jingyang"
```suggestion
author: "isabelleatmsft"
```

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +description: "Represents who will receive notification for access reviews."
```suggestion
description: "Represents users who will receive notifications for access reviews."
```

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +An **accessReviewNotificationRecipientQueryScope** object specifies a static list of recipients (for example, specific users, group owners, group members) to receive access review notifications.
```suggestion
An **accessReviewNotificationRecipientQueryScope** object specifies a static list of recipients (for example, specific users, group owners, or group members) to receive access review notifications.
```

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +| query | String | This represents the query for who the recipients are. For example, /groups/{group id}/members for group members and /users/{user id} for a specific user. |
```suggestion
| query | String | This represents the query for who the recipients are. For example, `/groups/{group id}/members` for group members and `/users/{user id}` for a specific user. |
```

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md
> +
Recommending delete since you've added this into the description of **query**.
```suggestion
```

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +[accessReviewNotificationRecipientQueryScope](../resources/accessReviewNotificationRecipientQueryScope.md).
```suggestion
The **accessReviewNotificationRecipientScope** represents a base class for defining users who will receive notifications on instances of [accessReviewScheduleDefinition](accessreviewscheduledefinition.md) objects. It is inherited by [accessReviewNotificationRecipientQueryScope](../resources/accessReviewNotificationRecipientQueryScope.md).
```

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientscope.md
> +### JSON representation
Restoring the deleted H2s but indicating **None**.
```suggestion
## Properties
None.

## Relationships
None.

## JSON representation
```

2021-06-09 07:43 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +                    "Description": "Added additionalNotificationRecipients to [accessreviewscheduledefinition](https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=gr
```suggestion
                    "Description": "Added the **additionalNotificationRecipients** property to the [accessReviewScheduleDefinition](https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&tabs=http) resource.",
```

2021-06-09 07:43 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +                    "Target": "accessreviewscheduledefinition"
2 more changelog entries for the 2 complex types you've added: accessReviewNotificationRecipientItem, accessReviewNotificationRecipientQueryScope

2021-06-09 07:43 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewnotificationrecipientitem.md
> +| notificationTemplateType  |String  | Indicates the type of access review email to be sent. Supported template type is `CompletedAdditionalRecipients` which sends review completion notifications to
```suggestion
| notificationTemplateType  |String  | Indicates the type of access review email to be sent. Supported template type is `CompletedAdditionalRecipients` which sends review completion notifications to the recipients.|
```

2021-06-10 02:29 UTC, opbld30 commented
Docs Build status updates of commit _[d033509](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d03350950fab79ed2618bb8ac30a5c5b8600ffc8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100228289002-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dsc2O40%2BkOcnIzqTmopOMWgcHx3uLnXnxdICEhiVPEE%3D&st=2021-06-10T02%3A24%3A47Z&se=2021-07-11T02%3A29%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 02:31 UTC, opbld30 commented
Docs Build status updates of commit _[ffd2116](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffd2116615a079d7d9f7318ee651fd823152fbae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100228405045-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y9E9PqOZxlddYg2wOavGpKZHMe5HP6K5vHmadlCWfT8%3D&st=2021-06-10T02%3A26%3A16Z&se=2021-07-11T02%3A31%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 02:33 UTC, opbld30 commented
Docs Build status updates of commit _[65e5984](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65e5984b22a02987e4352668707f5913e84081e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100231499460-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vonnr2%2FJLNMUBhFromc3aPHGAmC%2FKGudQxJKpBUzI7k%3D&st=2021-06-10T02%3A28%3A22Z&se=2021-07-11T02%3A33%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 02:34 UTC, opbld33 commented
Docs Build status updates of commit _[a70d24b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a70d24b046b23f7bf57c03d0467f84f219b3e7aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100232034288-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iq8XrLiGBRrvvm6sG0WCK3GsoO4RXwa7y%2FwVSaijyHU%3D&st=2021-06-10T02%3A29%3A42Z&se=2021-07-11T02%3A34%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 02:36 UTC, opbld34 commented
Docs Build status updates of commit _[a0a0cfb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0a0cfb2ca7a84e2e77dadae1966b14f965b2f74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-65d29061)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="54974c7a126366e7915039e1a4dc49ee-65d29061"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 22, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 38, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100233357763-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IXwQaxjQM%2FhIf5mXPoCzGMFu7vjm7j4Za%2F9vx5wgT1U%3D&st=2021-06-10T02%3A31%3A21Z&se=2021-07-11T02%3A36%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 02:38 UTC, opbld31 commented
Docs Build status updates of commit _[a0a0cfb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0a0cfb2ca7a84e2e77dadae1966b14f965b2f74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-a5448173)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="54974c7a126366e7915039e1a4dc49ee-a5448173"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 22, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 38, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100233256164-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gbtSEvEsjuh48vItYffWuE2rBtWBz6zqlKH1MXRkkHU%3D&st=2021-06-10T02%3A33%3A01Z&se=2021-07-11T02%3A38%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 03:15 UTC, opbld33 commented
Docs Build status updates of commit _[2435e42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2435e4221a0c1d71c8a987cefa0504f7698ca47a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-378f755f)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="54974c7a126366e7915039e1a4dc49ee-378f755f"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 22, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 38, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100313587617-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5aqidnfTgGKMFTRbkdUE6pvx9%2BLZuhc4%2Fyr0GmQrIHc%3D&st=2021-06-10T03%3A10%3A27Z&se=2021-07-11T03%3A15%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 09:13 UTC, FaithOmbongi approved these changes
Approved with caveat. Add the additionalNotificationRecipients property to the properties table of accessreviewscheduledefinition.md (Use same description as in the *-post API).

2021-06-10 20:54 UTC, jingyang1114 commented
> Approved with caveat. Add the additionalNotificationRecipients property to the properties table of accessreviewscheduledefinition.md (Use same description as in the *-post API).

Thank you, fixed

2021-06-10 20:57 UTC, opbld30 commented
Docs Build status updates of commit _[2b1ec47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b1ec47d8009a895a4554cb93d40dad990fcba7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-009f7b95)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="54974c7a126366e7915039e1a4dc49ee-009f7b95"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 22, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 38, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106102054190174-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eYhSz34Iasut7nANPvi6DEV2gHEYTk8OfBGXjzlfrpA%3D&st=2021-06-10T20%3A52%3A49Z&se=2021-07-11T20%3A57%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 00:14 UTC, isabelleatmsft approved these changes

2021-06-11 01:38 UTC, opbld31 commented
Docs Build status updates of commit _[0091f01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0091f01425d3e96d4db6535309a7337e75b06818)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-c7238b01)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="54974c7a126366e7915039e1a4dc49ee-c7238b01"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 22, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 38, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110137272043-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q0%2BGs29hcCcThwKMzIniIsnpyt%2BJkWhi0aqWduro%2Blk%3D&st=2021-06-11T01%3A33%3A54Z&se=2021-07-12T01%3A38%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 01:41 UTC, opbld30 commented
Docs Build status updates of commit _[62e69e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62e69e6de2c04af95f64b1c32a5eb65e289e56d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-c40752b3)
[api-reference/beta/api/accessreviewscheduledefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/api/accessreviewscheduledefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessReviewnotificationrecipientqueryscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewnotificationrecipientitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientitem?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewscheduledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewscheduledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-beta&branch=pr-en-us-12695) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="54974c7a126366e7915039e1a4dc49ee-c40752b3"></a>
### [api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewNotificationRecipient/api-reference/beta/resources/accessreviewnotificationrecipientscope.md)
 - **Line 22, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````
 - **Line 38, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Relationships''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110140160976-12695%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=71N%2FUds7NfhpBfyy1Rl5W2nJmSwNxIsQW84BoOiFGYk%3D&st=2021-06-11T01%3A36%3A45Z&se=2021-07-12T01%3A41%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 01:43 UTC, merged