Abheek Das Hidden Folders Features GA Release Doc Updates
microsoftgraph/microsoft-graph-docs pull request #12703
Opened 2021-05-12 10:27 UTC by abheek-das

Promoting new mailFolder property: "isHidden" & query parameter - includeHiddenFolders from Graph Beta to GA.

2021-05-12 10:29 UTC, opbld31 commented
Docs Build status updates of commit _[761c266](https://github.com/microsoftgraph/microsoft-graph-docs/commits/761c26643d414aca63bf6b715ffb97688ed846c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-bfbb54c9)
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-bfbb54c9"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105121027561734-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kkb8%2BXpLGr8R7ZLRFv3qJr18Ho02SpWNZ7UZoq71Q8k%3D&st=2021-05-12T10%3A24%3A10Z&se=2021-06-12T10%3A29%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 10:31 UTC, opbld32 commented
Docs Build status updates of commit _[0104239](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0104239eeb174929764f73b50ad7684e2525c0ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-4410ae47)
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-4410ae47"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105121030266145-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BlZ3TUT%2BbJwNDoiG0OPdYoeaead63yrSvnLUJyfMIrw%3D&st=2021-05-12T10%3A26%3A34Z&se=2021-06-12T10%3A31%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 10:42 UTC, opbld33 commented
Docs Build status updates of commit _[258afcf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/258afcf33b61e93c7e8401904621f48274b7ed6f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-dccb190a)
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-dccb190a"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105121040222210-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zAY3FoW03du%2Buh2cQglPv%2B1RC3PMx5MoYCzqqxtJEek%3D&st=2021-05-12T10%3A37%3A40Z&se=2021-06-12T10%3A42%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 22:04 UTC, angelgolfer-ms commented on api-reference/v1.0/api/user-post-mailfolders.md
>  Use this API to create a new mail folder in the root folder of the user's mailbox.
@abheek-das , this comment isn't specific to this file but applicable for this PR:
In Graph Explorer, the operation documented in mailfolder-post-childfolders.md also supports setting isHidden, in beta and v1. 

So looks like we overlooked updating these 2 files in beta before, and we need to do that for both beta and v1 now:
mailfolder-post-childfolders.md 
mailfolder-list-childfolders.md

Do you mind following up on that please?

2021-05-18 23:02 UTC, opbld30 commented
Docs Build status updates of commit _[af729e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af729e07efd9b7bf0b70c87c5d5fca01a35d8243)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-29f5ee4f)
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-29f5ee4f"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182301142905-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xRth7CT2dIk5iOiXJS8%2B%2FM7GATTlP%2F87l0XKbHI86wM%3D&st=2021-05-18T22%3A57%3A36Z&se=2021-06-18T23%3A02%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 23:03 UTC, opbld30 commented
Docs Build status updates of commit _[388053c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/388053c4875ee215db5051e1235f6f2af8895cc4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-b801a270)
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-b801a270"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182302124656-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=otbdJ6EJf5TBmtnzt9yi80SolC8kjNNNnCJ%2FijtbHvs%3D&st=2021-05-18T22%3A58%3A52Z&se=2021-06-18T23%3A03%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 23:21 UTC, angelgolfer-ms commented on api-reference/v1.0/api/user-post-mailfolders.md
>  Use this API to create a new mail folder in the root folder of the user's mailbox.
Also, please add these 2 operations to the Methods table in mailfolder.md. 
To the same Methods table, please add the "list mailFolder" operation (user-list-mailfolders.md) as well.
Add these 3 operations to the Methods table, in v1 and in beta, please.

2021-05-18 23:24 UTC, angelgolfer-ms requested changes
Hi @abheek-das , thanks for the PR. Please take a look at my comments about updating the 2 topics mailfolder-post-childfolders.md and mailfolder-list-childfolders.md, and adding the 2 operations plus the user-list-mailfolders.md operation to the Methods table.

FYI I reorganized the order of the children topics under the "Mail folder" node in the v1 and beta TOC.

Thanks!

2021-05-21 20:31 UTC, opbld30 commented
Docs Build status updates of commit _[82ca9ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82ca9ffbb214fc8c31e3df81a759d8c72b9a8b12)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-1f56aaff)
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-1f56aaff"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212030444686-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UZOsky5cIB0NUAmgYkyMaUzxkSAqgO%2Fz9KxdZD9GOxM%3D&st=2021-05-21T20%3A26%3A56Z&se=2021-06-21T20%3A31%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 20:33 UTC, opbld33 commented
Docs Build status updates of commit _[ba3e2ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba3e2ffb9a1a04cf456f5b3bf114526885f136bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-e04437ec)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-e04437ec)
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="aa0633ccc910c1746abaf6544b489339-e04437ec"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-e04437ec"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212031007447-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FHRej3B99VXPXwveiLK%2Fx49SAhCvGUtr%2F54ZcU9x2ME%3D&st=2021-05-21T20%3A28%3A19Z&se=2021-06-21T20%3A33%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:10 UTC, opbld32 commented
Docs Build status updates of commit _[93b392e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93b392e523f4258b93d8c062cec60f5752b32e6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) | [Details](#user-content-9345cf5c0fc631af3d6776e3bbf8273c-0544af05)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-0544af05)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-0544af05)
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="9345cf5c0fc631af3d6776e3bbf8273c-0544af05"></a>
### [api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md)
 - **Line 252, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="aa0633ccc910c1746abaf6544b489339-0544af05"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-0544af05"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212109221485-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kbBhE%2FgO7Lwnwj0GeoAaeQQpbNdywsJiZglG83R8XME%3D&st=2021-05-21T21%3A05%3A24Z&se=2021-06-21T21%3A10%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:11 UTC, opbld32 commented
Docs Build status updates of commit _[a700953](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a700953b2a15ac3722596ec10c3ad61b01772727)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) | [Details](#user-content-9345cf5c0fc631af3d6776e3bbf8273c-9abae91c)
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-9abae91c)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-9abae91c)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-9abae91c)
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="9345cf5c0fc631af3d6776e3bbf8273c-9abae91c"></a>
### [api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md)
 - **Line 252, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-9abae91c"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 129, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="aa0633ccc910c1746abaf6544b489339-9abae91c"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-9abae91c"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212109266634-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dCy7zM8MNlJsKDliJXmgIHvy9MmXjqaqjQbK64eYFH4%3D&st=2021-05-21T21%3A06%3A36Z&se=2021-06-21T21%3A11%3A36Z&sp=r).

If you see build warnings/errors with permissi [...]

2021-05-21 21:36 UTC, opbld34 commented
Docs Build status updates of commit _[af45739](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af457390e39e88a522183ab7d81ea8c7968e6206)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) | [Details](#user-content-9345cf5c0fc631af3d6776e3bbf8273c-24439df8)
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-24439df8)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-24439df8)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-24439df8)
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="9345cf5c0fc631af3d6776e3bbf8273c-24439df8"></a>
### [api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md)
 - **Line 252, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-24439df8"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 129, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="aa0633ccc910c1746abaf6544b489339-24439df8"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-24439df8"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https:/ [...]

2021-05-21 21:37 UTC, opbld33 commented
Docs Build status updates of commit _[b1a6465](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1a64652a84ab3e3be37b8def58d45aab1d64b7b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) | [Details](#user-content-9345cf5c0fc631af3d6776e3bbf8273c-c4f84fea)
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-c4f84fea)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-c4f84fea)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-c4f84fea)
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="9345cf5c0fc631af3d6776e3bbf8273c-c4f84fea"></a>
### [api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md)
 - **Line 252, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-c4f84fea"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 129, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="aa0633ccc910c1746abaf6544b489339-c4f84fea"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-c4f84fea"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https:/ [...]

2021-05-21 21:48 UTC, opbld30 commented
Docs Build status updates of commit _[7eab1cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7eab1cd267b93bce9d90d724c20f0066edbc00c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-c2ed2fdf)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-c2ed2fdf)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-c2ed2fdf)
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-c2ed2fdf"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 129, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="aa0633ccc910c1746abaf6544b489339-c2ed2fdf"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-c2ed2fdf"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212146213576-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BoD4HCkBVx3ilbFi%2FYvtt252%2BeXO7VpI8A52HQStYts%3D&st=2021-05-21T21%3A43%3A01Z&se=2021-06-21T21%3A48%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/ [...]

2021-05-21 21:49 UTC, opbld33 commented
Docs Build status updates of commit _[6930b68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6930b680c1744f4b4d9c87afaa4680412f7ef722)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-b7466dc7)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-b7466dc7)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-b7466dc7)
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-b7466dc7"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="aa0633ccc910c1746abaf6544b489339-b7466dc7"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-b7466dc7"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212147013381-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d9%2B7b4ca%2F%2F%2BVkSBR%2BPZAvDDWRym1B0MmgieMsXXsyC4%3D&st=2021-05-21T21%3A44%3A28Z&se=2021-06-21T21%3A49%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For b [...]

2021-05-21 21:58 UTC, abheek-das commented
Hi @angelgolfer-ms:
Thanks for your review, I've addressed the comments that you left previously. 
One question, shouldn't the title of pages mailfolder-post-childfolders.md be "Create ChildFolder" instead of "Create MailFolder". We already have user-post-mailfolders.md which tells us how to "Create MailFolder".

2021-05-21 22:20 UTC, abheek-das commented on api-reference/v1.0/api/user-post-mailfolders.md
>  Use this API to create a new mail folder in the root folder of the user's mailbox.
Indeed looks like mailfolder-post-childfolders.md & mailfolder-list-childfolders.md got missed. I've added them now for both Beta and v1.0.

Updated the Methods table in mailfolder.md as well. Ensured that following pages are listed as one of the operations:
- mailfolder-get.md
- user-list-mailfolders.md
- user-post-mailfolders.md
- mailfolder-list-childfolders.md
- mailfolder-post-childfolders.md

2021-05-21 22:22 UTC, opbld31 commented
Docs Build status updates of commit _[6be9323](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6be93232ef361cce6dfcd3a4ca6e9eeffd83269e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-5ed1b358)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-5ed1b358)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-5ed1b358)
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-5ed1b358"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="aa0633ccc910c1746abaf6544b489339-5ed1b358"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-5ed1b358"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212221324783-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ja%2Fvs3XA7VuIx8lKnsWNSrJQj4BmWiRTrZQd8Zr2SKs%3D&st=2021-05-21T22%3A17%3A55Z&se=2021-06-21T22%3A22%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken li [...]

2021-05-21 22:24 UTC, opbld31 commented
Docs Build status updates of commit _[24124b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24124b31e76cbd75d00fe19a1033a7c407464bff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-25f5559c)
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-aa0633ccc910c1746abaf6544b489339-25f5559c)
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-87b6a2c4d3c09e8e5cbad03d25fcaa08-25f5559c)
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-25f5559c"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="aa0633ccc910c1746abaf6544b489339-25f5559c"></a>
### [api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

<a id="87b6a2c4d3c09e8e5cbad03d25fcaa08-25f5559c"></a>
### [api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create MailFolder - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/mailfolder-post-childfolders.md(2,8), v1.0/api/user-post-mailfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create MailFolder' is duplicated with other articles: 'v1.0/api/mailfolder-post-childfolders.md(10,1), v1.0/api/user-post-mailfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212221552415-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FuNApQy3g%2FeRzXSlIgCt%2FLUwzZSRwESMFrR560QmYEM%3D&st=2021-05-21T22%3A19%3A19Z&se=2021-06-21T22%3A24%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken  [...]

2021-05-22 00:18 UTC, angelgolfer-ms commented
> Hi @angelgolfer-ms:
> Thanks for your review, I've addressed the comments that you left previously.
> One question, shouldn't the title of pages mailfolder-post-childfolders.md (both beta/v1.0) be "Create ChildFolder" instead of "Create MailFolder". We already have user-post-mailfolders.md which tells us how to "Create MailFolder".

If we look at only the topic titling rules used by the generator, "create" operation topics follow the "Create {resource name}" rule. So "Create mailFolder" would be what's generated in this case. (Also documented [here](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title).)

On the other hand, I understand from the perspectives of SEO and docs.microsoft.com-generated warning, having two or more topics in the same version ("doc set") of the docs with the same topic title is not ideal. Since the warning will turn into a build error at some point, we should mitigate it by retitling. I'd suggest "Create child folder" for both the TOC and topic title.

2021-05-22 08:26 UTC, angelgolfer-ms commented on api-reference/v1.0/api/mailfolder-post-childfolders.md
>  [mailFolder](../resources/mailfolder.md) object.
Line 54:
I think we should add a table row for the isHidden body parameter, right?
In the interest of time (got a few things to do before Build), I'm going to add that table row, in both this topic and the beta version of the topic.

2021-05-22 08:47 UTC, opbld34 commented
Docs Build status updates of commit _[568db92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/568db92a153ccd9d5c90ff36841437e0e024fd10)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-948d3fe8)
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-948d3fe8"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105220846090485-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mSqEI44Cyoujab%2BH%2Fp3MeutN9laB9S6sXzIvr0wUy3I%3D&st=2021-05-22T08%3A42%3A28Z&se=2021-06-22T08%3A47%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-22 08:48 UTC, opbld30 commented
Docs Build status updates of commit _[3bcb880](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bcb880f3171ca7ae09b4bdd952dde0eae4462fa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) | [Details](#user-content-3e3d7c67ea30ecae03c15082ce8ceb56-f1aba237)
[api-reference/beta/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-list-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-beta&branch=pr-en-us-12703) (graph-rest-beta) |
[api-reference/v1.0/api/mailfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/mailfolder-post-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-post-childfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-post-childfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-list-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-post-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/user-post-mailfolders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-mailfolders?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/resources/mailfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-1.0&branch=pr-en-us-12703) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="3e3d7c67ea30ecae03c15082ce8ceb56-f1aba237"></a>
### [api-reference/v1.0/api/mailfolder-list-childfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-hidden-folders-GA/api-reference/v1.0/api/mailfolder-list-childfolders.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List childFolders - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/contactfolder-list-childfolders.md(2,8), v1.0/api/mailfolder-list-childfolders.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List childFolders' is duplicated with other articles: 'v1.0/api/contactfolder-list-childfolders.md(10,1), v1.0/api/mailfolder-list-childfolders.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105220846508651-12703%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8HFdA7Lijj%2F628YB5hBOfisEzM%2Fn2R1Jd0MShWDuUn0%3D&st=2021-05-22T08%3A43%3A53Z&se=2021-06-22T08%3A48%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-22 08:53 UTC, merged