Create SensitivityLabel
microsoftgraph/microsoft-graph-docs pull request #12714
Opened 2021-05-13 10:58 UTC by SanjoyanM

This is how this resource type will be used
https://graph.microsoft.com/v1.0/me/drive/items/ID?$select=**sensitivitylabel**.

2021-05-13 10:59 UTC, opbld32 commented
Docs Build status updates of commit _[42c4178](https://github.com/SanjoyanM/microsoft-graph-docs/commits/42c4178911ba1a44e561f91293435b24178d063c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/SensitivityLabel](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/SensitivityLabel) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105131058149893-12714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wdPcQsyWN9vrtt%2BUFOOiptTfiyRLWdAbWlvGwsvN%2BBY%3D&st=2021-05-13T10%3A54%3A28Z&se=2021-06-13T10%3A59%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 09:09 UTC, opbld31 commented
Docs Build status updates of commit _[a074f6f](https://github.com/SanjoyanM/microsoft-graph-docs/commits/a074f6f74882b37e0ecf831122549b1de9cb7cfe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/SensitivityLabel](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/SensitivityLabel) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105140908380436-12714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FdW1x0cwJjV1boSCsLMfRk0Xj4udM29JI%2FWwTPad3Tc%3D&st=2021-05-14T09%3A04%3A58Z&se=2021-06-14T09%3A09%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 10:02 UTC, SanjoyanM commented
> Thanks for your pull request SanjoyanM! I've added the "do not merge" label as a default status. Please remove this label and add the "content review" label to start a review. Once completed, label the reviewed PR with the "ready to merge" label when you are ready for the docs team to merge your pull request.
> 
> **Note:** Pull requests will not be merged until the "ready to merge" label is set.

Hi I dont have rights to change the "label" ... can you change the label for me please

2021-05-18 10:03 UTC, opbld34 commented
Docs Build status updates of commit _[283472b](https://github.com/SanjoyanM/microsoft-graph-docs/commits/283472b408b67282c3355e82f42fd1e7913f2b48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/SensitivityLabel](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/SensitivityLabel) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105181002415951-12714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2pinhAyDZe5hrDwkSqfj0kUH5G93ibV583vu86s%2Fr2c%3D&st=2021-05-18T09%3A58%3A57Z&se=2021-06-18T10%3A03%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-28 01:43 UTC, opbld34 commented
Docs Build status updates of commit _[e3e1b2e](https://github.com/SanjoyanM/microsoft-graph-docs/commits/e3e1b2e9137795e6a86f8e09688681e75627e1f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/SensitivityLabel](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/SensitivityLabel) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106280141159255-12714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ay5lG9EwpLvpfChe19gfdpXKqUCAfdzczJfbQkoKIqY%3D&st=2021-06-28T01%3A38%3A45Z&se=2021-07-29T01%3A43%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 23:00 UTC, opbld33 commented
Docs Build status updates of commit _[f649965](https://github.com/SanjoyanM/microsoft-graph-docs/commits/f64996550553f50050ea19915238473856130906)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/SensitivityLabel](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/SensitivityLabel) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152259143500-12714%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A50%3A00Z&ske=2021-07-20T07%3A55%3A00Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T22%3A55%3A55Z&se=2021-08-15T23%3A00%3A55Z&sr=b&sp=r&sig=O1Hz9%2BY2mlj37Zr84UzwewDlPLKAvwfvJ3kguc6EmiA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[f316365](https://github.com/SanjoyanM/microsoft-graph-docs/commits/f31636541ac444e97a555fb355e306c4ae264f53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/SensitivityLabel](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/SensitivityLabel) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107201830032444-12714%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A19%3A18Z&ske=2021-07-26T02%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T18%3A26%3A46Z&se=2021-08-20T18%3A31%3A46Z&sr=b&sp=r&sig=5LxQfa4wa51RUGYhv%2BUxZU%2FqRAG4UV6MI11CygW1xvA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 02:02 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +ms.date: 05/05/2021
Please refer to the guidance for metadata and make the metadata consistent. We don't use the ms.date attribute. The ms.prod value should be "sites-and-lists".

2021-08-12 02:03 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +---
Please make the file name all lowercase and add the .md file extension.

2021-08-12 02:04 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +The **SensitivityLabel** resource groups sensitivity-label related data items into a single structure.
Resource topics generally begin with the verb without repeating the name of the resource in the description, so you can update to be "Group sensitivity label-related data items into a single structure." Note that the hyphen should be after label.

2021-08-12 02:05 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +# SensitivityLabel resource type
Resource names are lower camel case; please lowercase the S here and in the title and description fields.

2021-08-12 02:06 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +## Properties
We maintain a consistent order for the H2 headings; please move this section to come before the JSON representation section.

2021-08-12 02:06 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +## Remarks
Please remove this non-standard H2.

2021-08-12 02:06 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +| id                | string                   | The unique identifier (guid) for sensitivity label.
Change guid to GUID (it's an acronym).

2021-08-12 02:07 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +| protectionEnabled | boolean                  | Specifies if the label has an encryption policy attached or not.
Boolean should be capitalized. Change the description to "Indicates whether the label..." for clarity/consistency.

2021-08-12 02:07 UTC, Lauragra submitted a review, later dismissed
Please include a changelog entry with this PR and address editorial feedback.

2021-08-12 02:12 UTC, Lauragra commented on api-reference/v1.0/resources/SensitivityLabel
> +| Property          | Type                     | Description
This entity is defined in the beta metadata but not in v1.0. Did you mean to add it to the /beta/resources folder? Also, in the metadata, the properties shown do not match the properties in this table. Please update the Properties table to list all properties of this resource.

2021-08-12 20:29 UTC, opbld31 commented
Docs Build status updates of commit _[38e2a03](https://github.com/SanjoyanM/microsoft-graph-docs/commits/38e2a0391027e6519b1a094c772cddac078f11b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/filesensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/filesensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/filesensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) | [Details](#user-content-98187cd18c69228ddb4781dd1d329c8f-e446ddf6)

<a id="98187cd18c69228ddb4781dd1d329c8f-e446ddf6"></a>
### [api-reference/v1.0/resources/filesensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/filesensitivitylabel.md)
 - **Line 2, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'Sanjoyan Mustafi' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108122027570111-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YPdySNzpucvfac7kSEsSzt3MIK1pUz1F4sUxhugpWoo%3D&st=2021-08-12T20%3A24%3A52Z&se=2021-09-12T20%3A29%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 20:37 UTC, opbld33 commented
Docs Build status updates of commit _[17b0f78](https://github.com/SanjoyanM/microsoft-graph-docs/commits/17b0f78d5a28351aa19a8a1446f1615983c14519)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/filesensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/filesensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/filesensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) | [Details](#user-content-98187cd18c69228ddb4781dd1d329c8f-bf177afd)

<a id="98187cd18c69228ddb4781dd1d329c8f-bf177afd"></a>
### [api-reference/v1.0/resources/filesensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/filesensitivitylabel.md)
 - **Line 2, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'smustafi' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108122036316521-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6BFL1mBBPT%2FAc%2BhfunMLDgQ1KbkCbAPpWN9XtwVdnCY%3D&st=2021-08-12T20%3A32%3A43Z&se=2021-09-12T20%3A37%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 20:40 UTC, opbld31 commented
Docs Build status updates of commit _[7fa3183](https://github.com/SanjoyanM/microsoft-graph-docs/commits/7fa31839935372558e1586d662fafe32c1944952)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/filesensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/filesensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/filesensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108122039089417-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Q8%2Bi0OBvnUu8vYaB2aRLlmneZ54wkGOecrRgupUQivk%3D&st=2021-08-12T20%3A35%3A23Z&se=2021-09-12T20%3A40%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 16:12 UTC, jasonjoh commented
Docs Build status updates of commit _[f71a25a](https://github.com/SanjoyanM/microsoft-graph-docs/commits/f71a25a84b8f824c83fd950e7d4a39f3ceb360e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021610203412-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1sIecA6sB2JU8lOHWKLhUb0FGcO9sga7OviJmDxbPX4%3D&st=2021-09-02T16%3A07%3A36Z&se=2021-10-03T16%3A12%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 16:30 UTC, jasonjoh commented
Docs Build status updates of commit _[78bb39b](https://github.com/SanjoyanM/microsoft-graph-docs/commits/78bb39bd5f79f2598a42295c1cb3ceb7c1ab6bbd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) | [Details](#user-content-bcd5ed6e590d15439f2398f6295aa9a3-ec5b699c)

<a id="bcd5ed6e590d15439f2398f6295aa9a3-ec5b699c"></a>
### [api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md)
 - **Line 29, Column 4**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/information-protection/develop/reference/mip-enums-and-structs#assignmentmethod-enum' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 44, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/driveitem_setsensitivitylabel.md'.`````
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 29, Column 4**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/information-protection/develop/reference/mip-enums-and-structs#assignmentmethod-enum' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021628047124-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=iEwCMpN4MBm1DlI3URDMX8vtynS6eFrjASUY25i%2B5zE%3D&st=2021-09-02T16%3A25%3A38Z&se=2021-10-03T16%3A30%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 01:13 UTC, jasonjoh commented
Docs Build status updates of commit _[86675d3](https://github.com/SanjoyanM/microsoft-graph-docs/commits/86675d3484893fa8c11b300df42cf2f34d8389af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) | [Details](#user-content-bcd5ed6e590d15439f2398f6295aa9a3-3f0d29f3)

<a id="bcd5ed6e590d15439f2398f6295aa9a3-3f0d29f3"></a>
### [api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md)
 - **Line 47, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/driveitem_setsensitivitylabel.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070111328749-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8OetOCQYusisS9lzfiwZ82gjARUrGxMSd4HhtT3U864%3D&st=2021-09-07T01%3A08%3A13Z&se=2021-10-08T01%3A13%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-07 01:21 UTC, jasonjoh commented
Docs Build status updates of commit _[5b140cf](https://github.com/SanjoyanM/microsoft-graph-docs/commits/5b140cfefde8438a4709673286a720fd445d3e06)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) | [Details](#user-content-bcd5ed6e590d15439f2398f6295aa9a3-8c5b8b0c)

<a id="bcd5ed6e590d15439f2398f6295aa9a3-8c5b8b0c"></a>
### [api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md)
 - **Line 47, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/driveitem_setsensitivitylabel.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109070119262950-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=kt9wZRC%2BphGFMJbaF5IRK459vqH%2BW%2Frys3u9cFnqORM%3D&st=2021-09-07T01%3A16%3A04Z&se=2021-10-08T01%3A21%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 18:36 UTC, chackman commented on api-reference/v1.0/resources/filesensitivitylabel.md
> +
Is the "Methods" section required even if there are no methods defined on the type?

2021-09-14 21:25 UTC, opbld30 commented
Docs Build status updates of commit _[7457fb7](https://github.com/SanjoyanM/microsoft-graph-docs/commits/7457fb7bafb26ae0f6bb63b6b27b0febcc3a4d27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109142124222069-12714%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=MdAEb3QCIXx4NrlNuAa2EIPHCTwZrJ%2F8GHkN2Ncv7gc%3D&st=2021-09-14T21%3A20%3A58Z&se=2021-10-15T21%3A25%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 19:32 UTC, opbld33 commented
Docs Build status updates of commit _[84e0986](https://github.com/SanjoyanM/microsoft-graph-docs/commits/84e098648f1ddfd05050308679909848bc5190d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151928554070-12714%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T19%3A32%3A27Z&sr=b&sp=r&sig=btWT%2FWer6eMnIZK1rUlsQLItXiRng04N%2FdKdvPfnGD4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 19:35 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +description: This represents a sensitivity label of a file in SharePoint and OneDrive for Business.
Please include the rest of the headers: ms.prod, doc_type, ms.localizationpriority. Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103166/Metadata

2021-09-15 19:46 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +# SensitivityLabel type
Line 6: Title should be: sensitivityLabel resource type.

Note the camel case and the name **resource type**.

2021-09-15 20:49 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +The sensitivityLabel resource represents a sensitivity label of a file in SharePoint and OneDrive for Business.
Lines 4 and 8: These 2 descriptions should match. Please rephrase to use imperative voice:
* Represents a sensitivity label of...

2021-09-15 20:49 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +```
This section should go at the end of the document.

2021-09-15 21:02 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +| assignmentMethod     | AssignmentMethod | The assignment method of the label on the document. Whether the assignment of the label was done automatically, standard or as a privileged operation (The
According to the metadata, this resource type has many more properties and 1 relationship:
<EntityType Name="sensitivityLabel" BaseType="graph.entity">
<Property Name="applicableTo" Type="graph.sensitivityLabelTarget"/>
<Property Name="applicationMode" Type="graph.applicationMode"/>
<Property Name="assignedPolicies" Type="Collection(graph.labelPolicy)"/>
<Property Name="autoLabeling" Type="graph.autoLabeling"/>
<Property Name="description" Type="Edm.String"/>
<Property Name="displayName" Type="Edm.String"/>
<Property Name="isDefault" Type="Edm.Boolean"/>
<Property Name="isEndpointProtectionEnabled" Type="Edm.Boolean"/>
<Property Name="labelActions" Type="Collection(graph.labelActionBase)"/>
<Property Name="name" Type="Edm.String"/>
<Property Name="priority" Type="Edm.Int32"/>
<Property Name="toolTip" Type="Edm.String"/>
<NavigationProperty Name="sublabels" Type="Collection(graph.sensitivityLabel)" ContainsTarget="true"/>

2021-09-15 21:03 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +| unknownFutureValue  | Marker value for future compatibility.
Could you please clarify why are you including this section in the resource topic? It is not part of the structure for a resource topic. More details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103174/Templates

2021-09-15 21:05 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +
Please clarify the supported method for this resource. Does it support CRUD operations?

2021-09-15 21:06 UTC, isvargasmsft commented on api-reference/v1.0/resources/sensitivitylabel.md
> +---
General comments:
Please include an entry for this resource type in the TOC.
Please include an entry in the Changelog.

2021-09-15 21:08 UTC, isvargasmsft requested changes
Thank you very much @SanjoyanM, 

There are some clarifications needed and files missing. Please let me know if you have any questions. I am here to help. 

Kind regards!

2021-09-17 16:34 UTC, opbld31 commented
Docs Build status updates of commit _[21c1154](https://github.com/SanjoyanM/microsoft-graph-docs/commits/21c1154904213505b136426f57a1ae862e82b4f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109171630222057-12714%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-18T16%3A34%3A48Z&sr=b&sp=r&sig=PrLapbC11ktp%2BpszF7%2BZfo%2FKroHl%2BjMbHvXBptbAUbw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-21 20:01 UTC, SanjoyanM reviewed
@isvargasmsft Please review and let me know what is pending. Thanks in advance.

2021-09-21 20:01 UTC, SanjoyanM commented on api-reference/v1.0/resources/sensitivitylabel.md
> +| assignmentMethod     | AssignmentMethod | The assignment method of the label on the document. Whether the assignment of the label was done automatically, standard or as a privileged operation (The
Issac, not sure I understand what change is expected from documentation point here? Based on our last discussion can we resolve this or you are looking for specific information?

2021-09-21 20:04 UTC, opbld34 commented
Docs Build status updates of commit _[28e1f49](https://github.com/SanjoyanM/microsoft-graph-docs/commits/28e1f4992680c854802707ade52889b9653309a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/sensitivitylabel.md](https://github.com/SanjoyanM/microsoft-graph-docs/blob/patch-1/api-reference/v1.0/resources/sensitivitylabel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/sensitivitylabel?view=graph-rest-1.0&branch=pr-en-us-12714) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109212001455307-12714%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-22T20%3A04%3A06Z&sr=b&sp=r&sig=HJoiUbzBkTQGMt4AlHoZxiD0Wd2Jlwcow%2BMuBMj01K4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 17:38 UTC, isvargasmsft commented
Moving this PR to https://github.com/microsoftgraph/microsoft-graph-docs/pull/14170

2021-09-22 17:38 UTC, closed without merging