[CloudPC]Add user setting resource
microsoftgraph/microsoft-graph-docs pull request #12725
Opened 2021-05-14 09:20 UTC by AshleyYangSZ

2021-05-14 09:22 UTC, opbld31 commented
Docs Build status updates of commit _[9f062cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f062cb42cac04b64e4b23a0ffc92c15fcf61feb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-af641531)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-af641531)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-af641531)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-af641531)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-af641531)
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-94395027eed9bce412fb4b743c934d28-af641531)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-af641531)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-af641531)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-af641531)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-af641531)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-af641531)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-af641531)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-af641531"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-af641531"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level h [...]

2021-05-14 09:38 UTC, opbld33 commented
Docs Build status updates of commit _[3d70a13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d70a134365acaa37e9a9beb407f1e123ae8d76e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-65d48242)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-65d48242)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-65d48242)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-65d48242)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-65d48242)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-65d48242)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-65d48242)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-65d48242)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-65d48242)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-65d48242)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-65d48242)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-65d48242"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-65d48242"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-05-14 09:57 UTC, opbld34 commented
Docs Build status updates of commit _[2b267b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b267b79a5120fb50b5921ccf4b5d2e4a76b9702)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-91c610ff)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-91c610ff)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-91c610ff)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-91c610ff)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-91c610ff)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-91c610ff)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-91c610ff)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-91c610ff)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-91c610ff)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-91c610ff)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-91c610ff)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-91c610ff"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-91c610ff"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-05-18 04:37 UTC, opbld34 commented
Docs Build status updates of commit _[1cff471](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cff4710dfee32489c76acc875526453ccd225f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-d9cf9052)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-d9cf9052)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-d9cf9052)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-d9cf9052)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-d9cf9052)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d9cf9052)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-d9cf9052)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-d9cf9052)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-d9cf9052)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-d9cf9052)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-d9cf9052)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-d9cf9052"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-d9cf9052"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-05-20 10:34 UTC, opbld31 commented
Docs Build status updates of commit _[7933f80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7933f803bc3388fbf1e23cbc97484d9091135c7c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-de519972)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-de519972)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-de519972)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-de519972)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-de519972)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-de519972)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-de519972)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-de519972)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-de519972)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-de519972)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-de519972)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-de519972"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-de519972"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-05-20 10:43 UTC, opbld33 commented
Docs Build status updates of commit _[6b07c95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b07c95baf6a06bfc4ec92eee54bee6133abf878)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-8da2929e)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-8da2929e)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-8da2929e)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-8da2929e)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-8da2929e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8da2929e)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-8da2929e)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-8da2929e)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-8da2929e)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-8da2929e)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-8da2929e)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-8da2929e"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-8da2929e"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-05-27 07:31 UTC, AshleyYangSZ commented
This is the related [design review PR](https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/7738).
This is the related schema PRs: [https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4517605](https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4517605) &[ https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4542980]( https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4542980). @Lauragra @angelgolfer-ms FYI

2021-05-31 09:36 UTC, opbld30 commented
Docs Build status updates of commit _[9925d9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9925d9de8468df7c627288c20ce8c61b982aba18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-447a111a)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-447a111a)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-447a111a)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-447a111a)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-447a111a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-447a111a)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-447a111a)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-447a111a)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-447a111a)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-447a111a)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-447a111a)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-447a111a"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-447a111a"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-06-08 16:21 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-assign.md
> +POST /deviceManagement/virtualEndpoint/userSettings/{id}/assign
Line 358: In the placeholder, could you please include the name of the ID. For example:
/userSettings/{setting-ID}/   or
/userSettings/{group-ID}/

2021-06-08 16:22 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-assign.md
> +POST https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/userSettings/{id}/assign
Please use a real looking ID in the example, instead of the placeholder. It doesn't have to be a real ID, but a value that looks like a real one.

2021-06-08 16:28 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-get.md
> +GET /deviceManagement/virtualEndpoint/userSettings/{id}
Please indicate the name of the ID in the placeholder: /{resource-ID}/

2021-06-08 16:28 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/userSettings/{id}
Please provide a real looking ID in the example.

2021-06-08 16:29 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/usersettings/{id}?$expand=assignments
Please provide a real looking ID in the example.

2021-06-08 18:08 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-update.md
> +PATCH /deviceManagement/virtualEndpoint/provisioningPolicies/{id}
Please include the id name: /privisioningPolicies/{policy-ID}

2021-06-08 18:45 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-update.md
> +|displayName|String|The setting name as it appears in the user interface. |
"Please avoid using verbs as "appears" or "show up" for objects. In this case, please re-phrase to:
The setting name displayed in the user interface.

2021-06-08 18:46 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-update.md
> +PATCH https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/userSettings/{cloudPcUserSettingId}
Please use a real looking example of cloudPcUserSetting-ID.

2021-06-08 18:55 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusetsetting-delete.md
> +DELETE /deviceManagement/virtualEndpoint/userSettings/{id}
Please include the name of the ID: /userSettings/{settings-ID}

2021-06-08 18:56 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusetsetting-delete.md
> +DELETE https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/userSettings/{cloudPcUserSettingId}
Please use real looking IDs in the examples.

2021-06-08 19:35 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcusersetting.md
> +|displayName|String|The setting name as it appears in the user interface. |
Please rephrase to: The setting name displayed in the user interface.

2021-06-08 19:41 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcusersetting.md
> +|assignments|[cloudPcUserSettingAssignment](../resources/cloudpcusersettingassignment.md) collection|The user settings will be applied to the Azure AD user groups identified in this collection. Only
What do you think about re-phrasing to: "Office 365 and security groups in Azure AD can have a set of user settings assigned."

In general, we try to avoid passive voice as it usually leads to confusion. Details here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523

2021-06-08 19:43 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcusersettingassignment.md
> +description: "CloudPC user setting assignments"
The description in this line should match the first sentence of the article, which is meant to explain what the feature is about. Please consider, search engines use this line to display search results. 

I like line 16 so I suggest to copy it here.

2021-06-08 19:47 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcusersettingassignment.md
> +|id|String|Unique Identifier for the user setting assignment. Read-only. If `target` is a user group, then the ID is shown as {policyId}_{groupId}.|
Line 24. 
"If `target` is a user group, then the ID is shown as {policyId}_{groupId}."
Let's re-phrase to:
If the target is a user group, the ID has this structure: {policyID}_{groupID}.

2021-06-08 19:48 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcusersettingassignment.md
> +|createdDateTime|DateTimeOffset|he date and time this assignment was created. The Timestamp type represents the date and time information using ISO 8601 format and is always in UTC time. For example,
Typo in the 3rd column: The date...*

2021-06-08 19:48 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcusersettingassignment.md
> +None.
Please rephrase to:
This resource type doesn't have relationships.

2021-06-08 19:51 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +          - name: List
Could you please add the name of the resource in each ToC line? 
Guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=guidelines-and-examples

2021-06-08 19:55 UTC, isvargasmsft requested changes
Hello @AshleyYangSZ, thank you very much for your work in this PR. Very nice and tidy!

Some general observations:
1. Please include the names of the expected IDs in the placeholders in HTTP section. 
2. Please use real looking IDs in the examples. 
3. Please add the resource names in the ToC entries. 
4. Please fix the conflicts between this branch and the main. 

Remember to keep updating and refreshing your branch. 

Please feel free to ping me on the side if you have any questions. I am here to help!

Kind regards, 

Isaac Vargas

2021-06-11 10:52 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcusersetting-assign.md
> +POST /deviceManagement/virtualEndpoint/userSettings/{id}/assign
Hi, @isvargasmsft is it the must? As we already just used "id" in all of our Get APIs, if it's required, we may need to change all of them.

2021-06-11 11:20 UTC, opbld33 commented
Docs Build status updates of commit _[65dde4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65dde4ddee76963d84221a6da5690f10c4dd0512)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-f2293bf2)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-f2293bf2)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-f2293bf2)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-f2293bf2)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-f2293bf2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f2293bf2)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-f2293bf2)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-f2293bf2)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-f2293bf2)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-f2293bf2)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-f2293bf2)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-f2293bf2"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-f2293bf2"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-06-11 11:20 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcusersetting.md
> +|assignments|[cloudPcUserSettingAssignment](../resources/cloudpcusersettingassignment.md) collection|The user settings will be applied to the Azure AD user groups identified in this collection. Only
Agree, will update. Thanks.

2021-06-11 11:28 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +          - name: List
Hi @isvargasmsft , thanks for comment, but I saw this sentence in the wiki, seems like basic CRUD operation APIs don't need to add resource name in title, what's your opinion? ![image](https://user-images.githubusercontent.com/72924235/121679503-f9616600-caea-11eb-856a-5df2b43be962.png)

2021-06-11 11:34 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcusersetting-get.md
> +GET /deviceManagement/virtualEndpoint/userSettings/{id}
If it's a must, I will update all ids.

2021-06-11 11:41 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcusersettingassignment.md
> +None.
This is generated by the doc generator, and I checked other docs also use None. when no relationships for this entity. Can we just leave it as it is?

2021-06-11 11:47 UTC, opbld34 commented
Docs Build status updates of commit _[13a3406](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13a3406dc112d32f658310a0e53b06e863788459)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5559018b4c713374056407d279d379b0-af7d4749)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-af7d4749)
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-5f6e4e9ed84c4cceae01c99f45c0089c-af7d4749)
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-e91d98ab72c7f005bfc3fff5a98a103b-af7d4749)
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-d824e9f6bef6040afb40dd6da882e2e0-af7d4749)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-af7d4749)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-ad3928d9f7e361850f456959efad3eff-af7d4749)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-dadb46177cd34394b5f8c0102b5cbac7-af7d4749)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-697cad2e2e5111f612c2f6c776737a98-af7d4749)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-4ee7f7e652e9978bb795a7141fbd735e-af7d4749)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-14a87c3a70ca31b4369f4bde4ebb2315-af7d4749)
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="5559018b4c713374056407d279d379b0-af7d4749"></a>
### [api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'cloudPcProvisioningPolicy: assign' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-assign.md(10,1), beta/api/cloudpcusersetting-assign.md(10,1)'. First level headings must be unique within a docset.`````

<a id="213d600994e354637bc78f1781a1f6fc-af7d4749"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get cloudPcProvisioningPolicy' is duplicated with other articles: 'beta/api/cloudpcprovisioningpolicy-get.md(10,1), beta/api/cloudpcusersetting-get.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3 [...]

2021-06-14 13:45 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-assign.md
> +title: "cloudPcUserSetting: assign"
I noticed the title in line 2 doesn't match the title in line 10. Could you please fix for consistency across all docs in this PR?

2021-06-14 14:00 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcusersetting-assign.md
> +title: "cloudPcUserSetting: assign"
Good catch! Updated!

2021-06-14 14:01 UTC, opbld31 commented
Docs Build status updates of commit _[935b380](https://github.com/microsoftgraph/microsoft-graph-docs/commits/935b38022113ceda3b6bde1bdc34eef99728b9b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-56004a82)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-56004a82)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-56004a82"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml)
 - **Line 9589, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcusersettings-delete.md'.`````
 - **Line 9591, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcusersettings-assign.md'.`````

<a id="213d600994e354637bc78f1781a1f6fc-56004a82"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a cloudPcProvisioningPolicy object.' is duplicated in 'beta/api/cloudpcprovisioningpolicy-get.md(3,14)', 'beta/api/cloudpcusersetting-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141359460444-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lpLLbZkydOUo%2BWZZe0fqLjff2W%2Ft4jixvdhVXtqCpHk%3D&st=2021-06-14T13%3A56%3A14Z&se=2021-07-15T14%3A01%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0 [...]

2021-06-14 14:05 UTC, opbld32 commented
Docs Build status updates of commit _[f8e1a5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8e1a5e8564ce4d0dcd4d721e63b0c5132de091c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-144e228d)
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-213d600994e354637bc78f1781a1f6fc-144e228d)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusetsetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusetsetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusetsetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-144e228d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml)
 - **Line 9589, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcusersettings-delete.md'.`````
 - **Line 9591, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/cloudpcusersettings-assign.md'.`````

<a id="213d600994e354637bc78f1781a1f6fc-144e228d"></a>
### [api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Read the properties and relationships of a cloudPcProvisioningPolicy object.' is duplicated in 'beta/api/cloudpcprovisioningpolicy-get.md(3,14)', 'beta/api/cloudpcusersetting-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141404160600-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SwY%2FLiXeYvZARvbZVObcCytnWRikB%2FeZuOvDhDErqhY%3D&st=2021-06-14T14%3A00%3A47Z&se=2021-07-15T14%3A05%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0 [...]

2021-06-14 14:09 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusetsetting-delete.md
> +title: "Delete cloudPcUserSetting"
Please fix typo in the name of the file: cloudpcusersetting-delete.md*

2021-06-14 14:10 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +            href: api/cloudpcusersettings-assign.md
The file is called usersetting but here you mentioned usersettings. Could you please fix for consistency?

2021-06-14 14:11 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcusersetting-get.md
> +description: "Read the properties and relationships of a cloudPcProvisioningPolicy object."
Please make this description consistent with line 16.

2021-06-14 14:21 UTC, opbld30 commented
Docs Build status updates of commit _[3601cd9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3601cd9deb40b05cc7cdcaf597408ebfed1397df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) | [Details](#user-content-94395027eed9bce412fb4b743c934d28-6625cc4e)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="94395027eed9bce412fb4b743c934d28-6625cc4e"></a>
### [api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md)
 - **Line 27, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/cloudpcusetsetting-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141419452845-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zjV7kxnnnY92JXQ03AlP1a61ZP5Y7BBqcvsL68vk%2FMg%3D&st=2021-06-14T14%3A16%3A18Z&se=2021-07-15T14%3A21%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=7 [...]

2021-06-14 14:24 UTC, opbld30 commented
Docs Build status updates of commit _[affb107](https://github.com/microsoftgraph/microsoft-graph-docs/commits/affb10767bde0d89eedc0b7f6f3ad29d4d070a34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141422590491-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rvGETuYtDNwMa5uTKWRVsEWThLv3GS3TjBc4eXnAkNQ%3D&st=2021-06-14T14%3A19%3A12Z&se=2021-07-15T14%3A24%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 14:27 UTC, isvargasmsft approved these changes
Thank you very much for the quick response!

2021-06-14 21:00 UTC, Lauragra commented on api-reference/beta/api/cloudpcusersetting-assign.md
> +>**Note:** The response object shown here might be shortened for readability.
Global: When there's no response body, please remove this note.

2021-06-14 22:15 UTC, opbld30 commented
Docs Build status updates of commit _[b9c3e5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9c3e5a20eb7d82b33b0f8d8c82ac33640e1b46c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142213559151-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8ZTarZ10pw0YmSPQOpvEqKyreBN0P%2Bx35D92LPqmG5E%3D&st=2021-06-14T22%3A10%3A24Z&se=2021-07-15T22%3A15%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:37 UTC, opbld31 commented
Docs Build status updates of commit _[be69e11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be69e119d226b3603b7b79561e37cb3d7dcbe242)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150235320594-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sv3cWmNfDbE4phOSpiqiWFxPQTbX5LQJrkwN7Js3bkc%3D&st=2021-06-15T02%3A32%3A03Z&se=2021-07-16T02%3A37%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:38 UTC, opbld31 commented
Docs Build status updates of commit _[95c200d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95c200d96a444a203af933fb366d0ee3e3f053e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150237324573-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PsXW9%2FqdXcMWpMVr7ulHMFuQlhPTT8qGT%2Bdkapj6rd8%3D&st=2021-06-15T02%3A33%3A50Z&se=2021-07-16T02%3A38%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:41 UTC, opbld34 commented
Docs Build status updates of commit _[711ffd3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/711ffd3b3a0f73048e26e9fc98dfc37c162a2fc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150239366850-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FMhwoBzBeLtm9i%2FBLcHIGmNjd73%2BLVLp1XT3qw0jEos%3D&st=2021-06-15T02%3A36%3A08Z&se=2021-07-16T02%3A41%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:43 UTC, opbld30 commented
Docs Build status updates of commit _[c2f272e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2f272ecf538a0ba5923c67e3864b7787005ca76)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150241542602-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rzhx58OduZ0nxyGaCYJdpIiNApfOi9KYoATlID7srsU%3D&st=2021-06-15T02%3A38%3A20Z&se=2021-07-16T02%3A43%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:45 UTC, opbld30 commented
Docs Build status updates of commit _[cbbdc63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbbdc63660ff5c6933ea34a1d01cd6cb13776970)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150243087999-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EvF%2FstMDdLqqgHickB1lgkBiWYWhm0xXQTLTeCG5EKI%3D&st=2021-06-15T02%3A40%3A05Z&se=2021-07-16T02%3A45%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:46 UTC, opbld33 commented
Docs Build status updates of commit _[dfeace2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfeace217cb265a6c91df10cfd239b117f820bef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150245055390-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t%2Fulrui2ctiApSXCUetXfjuVmYnA99O77jidaE0lqic%3D&st=2021-06-15T02%3A41%3A45Z&se=2021-07-16T02%3A46%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:47 UTC, Lauragra commented on api-reference/beta/resources/cloudpcusersetting.md
> +|localAdminEnabled|Boolean|To turn on the local admin option, change this setting to True.  |
Is this a sufficient description of the property, or should it be something like "Indicates whether the local admin option is enabled. Default value is `false`. To enable the local admin option, change the setting to `true`. (This comment is global to all occurrences of this property.)

2021-06-15 02:48 UTC, Lauragra commented on api-reference/beta/resources/cloudpcusersetting.md
> +|selfServiceEnabled|Boolean|To turn on the self service option, change this setting to True. |
Same question here - should be "Indicates whether the self-service option is enabled. Default value is `false`. To enable the self-service option, change the setting to `true`." (global)

2021-06-16 01:46 UTC, opbld32 commented
Docs Build status updates of commit _[1c53825](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c538256eeda4a8d9443dcfaa2a496f361b9f2fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160145016820-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LD4vPetmThTCUtU68DrGtCtlXw%2B3iiDnddtD%2FlVbVVE%3D&st=2021-06-16T01%3A41%3A18Z&se=2021-07-17T01%3A46%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 02:20 UTC, Lauragra approved these changes

2021-06-17 02:20 UTC, opbld32 commented
Docs Build status updates of commit _[3f61e88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f61e8802b7421f86a1ff70936cb89973f8b9668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpc-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcdeviceimage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-assign.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-assign?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-delete?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/cloudpcusersetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/cloudpcusersetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcusersetting-update?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-list-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-post-usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/api/virtualendpoint-post-usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-usersettings?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersetting?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcusersettingassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/cloudpcusersettingassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcusersettingassignment?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-12725) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/usersetting/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106170218356114-12725%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e3mmQcfR0oIgucjTiJtfQQP2EdL3I2zENUiOaC%2BIAnI%3D&st=2021-06-17T02%3A15%3A10Z&se=2021-07-18T02%3A20%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 02:22 UTC, merged