Create documentation for new workload on graph
microsoftgraph/microsoft-graph-docs pull request #12722
Opened 2021-05-13 22:00 UTC by payiAzure

1. The API and Resource files are generated by graph documentation generator tool.
2. Propose a ToC for M365ServiceCommsPlatform workload and update it in toc.yml file
3. Create a changelog placeholder for new workload M365ServiceCommsPlatform (since the generator tool couldn't generate changelog)

2021-05-13 22:01 UTC, opbld33 commented
Docs Build status updates of commit _[d56ce22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d56ce2294a6762993eed7c031aeb0092dfc6317f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-22ced2bd)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-22ced2bd)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-22ced2bd)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-22ced2bd)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-22ced2bd)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | | [Details](#user-content-e31555adbfe773946826479126211fb0-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | | [Details](#user-content-837dd719b1dbf260dfe180b896549017-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-22ced2bd)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | | [Details](#user-content-fde9b1253be13aa031756589bab47469-22ced2bd)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-22ced2bd)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-22ced2bd)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-22ced2bd)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-22ced2bd)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-22ced2bd)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-22ced2bd)
[api-reference/beta/resources/serviceupdatemessageviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessageviewpoint.md) | :warning:Warning | | [Details](#user-content-bb1b8c3e28cbbf24152c2794d290e26e-22ced2bd)

<a id="0817dce4456c16725d5333633847d38f-22ced2bd"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml)
 - **Line 14002, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 13998, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="a199b1b37e3e179b6484a15622624b7c-22ced2bd"></a>
### [api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'payi (GitHub name payiAzure)' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'MS prod'.`````

<a id="ce81674bbd3d06aeaceb750f449d118b-22ced2bd"></a>
### [api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'payi (GitHub name payiAzure)' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invali [...]

2021-05-14 03:56 UTC, opbld31 commented
Docs Build status updates of commit _[a84b96d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a84b96d8619fa93f5f9592b9a72b26c1d2cb91b4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-9bd0732e)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-9bd0732e)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-9bd0732e)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-9bd0732e)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-9bd0732e)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | | [Details](#user-content-e31555adbfe773946826479126211fb0-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | | [Details](#user-content-837dd719b1dbf260dfe180b896549017-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-9bd0732e)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | | [Details](#user-content-fde9b1253be13aa031756589bab47469-9bd0732e)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-9bd0732e)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-9bd0732e)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-9bd0732e)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-9bd0732e)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-9bd0732e)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-9bd0732e)
[api-reference/beta/resources/serviceupdatemessageviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessageviewpoint.md) | :warning:Warning | | [Details](#user-content-bb1b8c3e28cbbf24152c2794d290e26e-9bd0732e)

<a id="0817dce4456c16725d5333633847d38f-9bd0732e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml)
 - **Line 14002, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 13998, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="a199b1b37e3e179b6484a15622624b7c-9bd0732e"></a>
### [api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'M365ServiceCommsPlatform'.`````

<a id="ce81674bbd3d06aeaceb750f449d118b-9bd0732e"></a>
### [api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'M365ServiceCommsPlatform'.`````

<a id="dc6b2db8d87fe8723bee408308a137e1-9bd0732e"></a>
### [api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-tec [...]

2021-05-14 04:52 UTC, opbld34 commented
Docs Build status updates of commit _[1bcb87e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bcb87ec8eaa2e589004968af02eaef38fa19c40)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-9db3d46c)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-9db3d46c)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-9db3d46c)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-9db3d46c)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-9db3d46c)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | | [Details](#user-content-e31555adbfe773946826479126211fb0-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | | [Details](#user-content-837dd719b1dbf260dfe180b896549017-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-9db3d46c)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | | [Details](#user-content-fde9b1253be13aa031756589bab47469-9db3d46c)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-9db3d46c)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-9db3d46c)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-9db3d46c)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-9db3d46c)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-9db3d46c)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-9db3d46c)
[api-reference/beta/resources/serviceupdatemessageviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessageviewpoint.md) | :warning:Warning | | [Details](#user-content-bb1b8c3e28cbbf24152c2794d290e26e-9db3d46c)

<a id="0817dce4456c16725d5333633847d38f-9db3d46c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml)
 - **Line 14002, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 13998, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="a199b1b37e3e179b6484a15622624b7c-9db3d46c"></a>
### [api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'm365-servicecommsplatform'.`````

<a id="ce81674bbd3d06aeaceb750f449d118b-9db3d46c"></a>
### [api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'm365-servicecommsplatform'.`````

<a id="dc6b2db8d87fe8723bee408308a137e1-9db3d46c"></a>
### [api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-t [...]

2021-05-17 05:17 UTC, opbld34 commented
Docs Build status updates of commit _[9833eeb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9833eeb073665c2c58aee7da99f114ce0305e8c9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-cc8bb7a7)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-cc8bb7a7)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-cc8bb7a7)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-cc8bb7a7)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-cc8bb7a7)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | | [Details](#user-content-e31555adbfe773946826479126211fb0-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | | [Details](#user-content-837dd719b1dbf260dfe180b896549017-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-cc8bb7a7)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | | [Details](#user-content-fde9b1253be13aa031756589bab47469-cc8bb7a7)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-cc8bb7a7)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-cc8bb7a7)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-cc8bb7a7)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-cc8bb7a7)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-cc8bb7a7)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-cc8bb7a7)
[api-reference/beta/resources/serviceupdatemessageviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessageviewpoint.md) | :warning:Warning | | [Details](#user-content-bb1b8c3e28cbbf24152c2794d290e26e-cc8bb7a7)

<a id="0817dce4456c16725d5333633847d38f-cc8bb7a7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml)
 - **Line 14002, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 13998, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="a199b1b37e3e179b6484a15622624b7c-cc8bb7a7"></a>
### [api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="ce81674bbd3d06aeaceb750f449d118b-cc8bb7a7"></a>
### [api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="dc6b2db8d87fe8723bee408308a137e1-cc8bb7a7"></a>
### [api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technol [...]

2021-05-18 04:39 UTC, opbld30 commented
Docs Build status updates of commit _[934dd1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/934dd1d6153a0c68cb4cb9565f4e6fe192326b15)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-63b76f38)

<a id="63b76f38"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105180438570698-12722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kEUAzpy3A5Q7ppLz8%2BWKJzEkuhfctin7PwxGUCJP4D0%3D&st=2021-05-18T04%3A34%3A11Z&se=2021-06-18T04%3A39%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 04:45 UTC, opbld33 commented
Docs Build status updates of commit _[2bebdb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bebdb1116056c67918ad0590faa801ad6074e75)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-960018b3)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-960018b3)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-960018b3)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-960018b3)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-960018b3)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-960018b3)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-960018b3)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-960018b3)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | | [Details](#user-content-e31555adbfe773946826479126211fb0-960018b3)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | | [Details](#user-content-837dd719b1dbf260dfe180b896549017-960018b3)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-960018b3)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-960018b3)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-960018b3)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | | [Details](#user-content-fde9b1253be13aa031756589bab47469-960018b3)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-960018b3)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-960018b3)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-960018b3)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-960018b3)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-960018b3)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-960018b3)
[api-reference/beta/resources/serviceupdatemessageviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessageviewpoint.md) | :warning:Warning | | [Details](#user-content-bb1b8c3e28cbbf24152c2794d290e26e-960018b3)

<a id="0817dce4456c16725d5333633847d38f-960018b3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml)
 - **Line 14043, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="a199b1b37e3e179b6484a15622624b7c-960018b3"></a>
### [api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="ce81674bbd3d06aeaceb750f449d118b-960018b3"></a>
### [api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="dc6b2db8d87fe8723bee408308a137e1-960018b3"></a>
### [api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Inva [...]

2021-05-18 04:51 UTC, opbld34 commented
Docs Build status updates of commit _[4870c99](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4870c9969080e5ae99e5209b4ead4dee61d43e20)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-d7a72212)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-d7a72212)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-d7a72212)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-d7a72212)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-d7a72212)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-d7a72212)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-d7a72212)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-d7a72212)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | | [Details](#user-content-e31555adbfe773946826479126211fb0-d7a72212)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | | [Details](#user-content-837dd719b1dbf260dfe180b896549017-d7a72212)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-d7a72212)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-d7a72212)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-d7a72212)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | | [Details](#user-content-fde9b1253be13aa031756589bab47469-d7a72212)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-d7a72212)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-d7a72212)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-d7a72212)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-d7a72212)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-d7a72212)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-d7a72212)
[api-reference/beta/resources/serviceupdatemessageviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessageviewpoint.md) | :warning:Warning | | [Details](#user-content-bb1b8c3e28cbbf24152c2794d290e26e-d7a72212)

<a id="0817dce4456c16725d5333633847d38f-d7a72212"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml)
 - **Line 14043, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="a199b1b37e3e179b6484a15622624b7c-d7a72212"></a>
### [api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="ce81674bbd3d06aeaceb750f449d118b-d7a72212"></a>
### [api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="dc6b2db8d87fe8723bee408308a137e1-d7a72212"></a>
### [api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Inva [...]

2021-06-02 02:37 UTC, opbld30 commented
Docs Build status updates of commit _[c1b2830](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1b28308fdfa1f57f28cb8145396d2a432542b1b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-7a93ddf3)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-7a93ddf3)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-7a93ddf3)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-7a93ddf3)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-7a93ddf3)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | | [Details](#user-content-e31555adbfe773946826479126211fb0-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | | [Details](#user-content-837dd719b1dbf260dfe180b896549017-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-7a93ddf3)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | | [Details](#user-content-fde9b1253be13aa031756589bab47469-7a93ddf3)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-7a93ddf3)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-7a93ddf3)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-7a93ddf3)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-7a93ddf3)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-7a93ddf3)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-7a93ddf3)
[api-reference/beta/resources/serviceupdatemessageviewpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessageviewpoint.md) | :warning:Warning | | [Details](#user-content-bb1b8c3e28cbbf24152c2794d290e26e-7a93ddf3)

<a id="0817dce4456c16725d5333633847d38f-7a93ddf3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/toc.yml)
 - **Line 14163, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="a199b1b37e3e179b6484a15622624b7c-7a93ddf3"></a>
### [api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="ce81674bbd3d06aeaceb750f449d118b-7a93ddf3"></a>
### [api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'service communications'.`````

<a id="dc6b2db8d87fe8723bee408308a137e1-7a93ddf3"></a>
### [api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Inva [...]

2021-06-02 20:07 UTC, opbld32 commented
Docs Build status updates of commit _[4da55ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4da55eeeb0b7aae980de9832bddea8a71a704b94)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-612e13fa)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-612e13fa)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-612e13fa)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-612e13fa)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-612e13fa)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-612e13fa)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-612e13fa)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-612e13fa)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-612e13fa)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-612e13fa)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-612e13fa)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-612e13fa)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-612e13fa)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-612e13fa)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-612e13fa)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-612e13fa)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-612e13fa)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-612e13fa)
[api-refe [...]

2021-06-02 22:51 UTC, opbld31 commented
Docs Build status updates of commit _[f18d264](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f18d26490f8981bf2991d7dcf79f9d69e2de0ba2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-fabd73bd)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-fabd73bd)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-fabd73bd)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-fabd73bd)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-fabd73bd)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-fabd73bd)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-fabd73bd)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-fabd73bd)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-fabd73bd)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-fabd73bd)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-fabd73bd)
[api-refe [...]

2021-06-02 23:16 UTC, opbld30 commented
Docs Build status updates of commit _[22d3205](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22d3205a0332457c8e9000f061a9b951cfd0974f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-0e3a9c0a)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-0e3a9c0a)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-0e3a9c0a)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-0e3a9c0a)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-0e3a9c0a)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-0e3a9c0a)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-0e3a9c0a)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-0e3a9c0a)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-0e3a9c0a)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-0e3a9c0a)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-0e3a9c0a)
[api-refe [...]

2021-06-02 23:33 UTC, opbld34 commented
Docs Build status updates of commit _[75e021c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75e021c51aa4ed8cc4fb85cd188fee4d6b9cde5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-7fba5a2c)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-7fba5a2c)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-7fba5a2c)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-7fba5a2c)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-7fba5a2c)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-7fba5a2c)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-7fba5a2c)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-7fba5a2c)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-7fba5a2c)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-7fba5a2c)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-7fba5a2c)
[api-refe [...]

2021-06-02 23:37 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +Read service health overview of a specified service for tenant. The operation returns a [serviceHealth](../resources/servicehealth.md) object.
Line 15: The very first line in a reference topic should work as document description, which is meant to be clear and useful for search engines. For this reason, we try to keep the description in a single sentence, 1 paragraph. 

In the case of Get topics, we try to keep it clear and to the point. For example:

Retrieve the properties and relationships of a [serviceHealth] (link to resource type doc) object. 
//a blank line to jump paragraphs.
Any additional information that you consider necessary to clarify at the beginning. This can be supported formats (if applicable), links to related or similar topics the customer may want to check and such.

2021-06-02 23:53 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +GET /admin/serviceAnnouncement/healthOverviews('{Service Name}'))
Line 34: Is there a reason to close twice())?

2021-06-03 00:01 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +
Since we are including more than 1 examples, please use the following structure:

H2: Examples
H3: Example 1: Get the properties of a serviceHealth object
H4: Request
H4: Response
H3: Example 2: Include navigation property issues
H4: Request
H4: Response

2021-06-03 00:07 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +  "@odata.type": "m365ServiceHealth.readServices.commercialWebService.models.serviceHealth"
Regarding the odata type:
Shouldn't it be microsoft.graph.serviceHealth?

2021-06-03 01:02 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +    "@odata.type": "#m365ServiceHealth.readServices.commercialWebService.models.serviceHealth",
Same question here. I've been trying to test this response in Graph Explorer but its been acting up. 

I'll double check later.

2021-06-03 01:03 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +### Including navigation property issues in the [serviceHealth](../resources/servicehealth.md) object
Please see my previous comment regarding the examples section structure. 

In this case, please use the format:
H3 Example 2: Include navigation ...

Dont forget to use imperatives in the title: Include instead of Including.

2021-06-03 01:04 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews('Microsoft 365 suite')?$expand=issues
Please add the API Doctor code before the request. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor

2021-06-03 01:05 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews('Microsoft 365 suite')?$expand=issues
In addition, please add H4 Request header

2021-06-03 01:05 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +### Response
H4 here please

2021-06-03 01:05 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +HTTP/1.1 200 OK
Please include the API Doctor code. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor

2021-06-03 01:07 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +### Including navigation property issues in the [serviceHealth](../resources/servicehealth.md) object
In addition, please avoid using links inside titles.

2021-06-03 02:08 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +Get service health overviews of tenant's all services. Returns a list of the [serviceHealth](../resources/servicehealth.md) objects and their properties.
Similar suggestion in the other doc. I think the second sentence should suffice.

2021-06-03 02:09 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +### Request
Please follow the Examples structure as commented previously. 
H2 Examples
H3 Example 1: Get a list of serviceHealth objects
H4: Request

etc

2021-06-03 02:11 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews('Microsoft 365 suite')
Just to confirm: Do we really need to use /admin/? Or could a user with the proper permissions go with /me/?

2021-06-03 02:14 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +Get service health overviews of tenant's all services. Returns a list of the [serviceHealth](../resources/servicehealth.md) objects and their properties.
Please use Retrieve instead of returns. We try to use imperative in introductory sentences.

2021-06-03 02:15 UTC, isvargasmsft commented on api-reference/beta/api/servicehealthissue-get.md
> +## Examples
If it is just one example, please write the title in singular: Example

2021-06-03 02:21 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +This POST action is to mark the status of a list of service update messages as archived for the login user.
Lets improve this one:
1. Please use imperative. 
2. We avoid using verbs that can be nouns as well (mark in this case).
3. Why don't we use archive as the verb for this sentence? For example:

Archive a list of [service update messages] (include reference please).

2021-06-03 05:33 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +GET /admin/serviceAnnouncement/healthOverviews('{Service Name}'))
typo. will remove

2021-06-03 05:43 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +
Thanks. Will fix this.

2021-06-03 05:57 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +  "@odata.type": "m365ServiceHealth.readServices.commercialWebService.models.serviceHealth"
Oh. The example response here are from postman that are not returned by Graph, since our service is not ready on Graph yet when I started the documentation. I will update all example request response that returned by graph explorer.

2021-06-03 06:15 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +    "@odata.type": "#m365ServiceHealth.readServices.commercialWebService.models.serviceHealth",
same here. I will use the response from Graph Explorer as example in the documentation for each api operations.

2021-06-03 14:40 UTC, opbld31 commented
Docs Build status updates of commit _[e30619c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e30619c99215ed313c8c4d9cbc48fe8342149bea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-c80aea13)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-c80aea13)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-c80aea13)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-c80aea13)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-c80aea13)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-c80aea13)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-c80aea13)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-c80aea13)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-c80aea13)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-c80aea13)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-c80aea13)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-c80aea13)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-c80aea13)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-c80aea13)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-c80aea13)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-c80aea13)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-c80aea13)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-c80aea13)
[api-refe [...]

2021-06-03 15:12 UTC, isvargasmsft commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +Gets the post incident report (PIR) document of a specified service issue for tenant. This operation returns Edm.Stream. The PIR won't be returned to tenant if the specified issue is not visible to t
Please use imperative. Retrieve is a good verb for GET topics :)

2021-06-03 18:28 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +Read service health overview of a specified service for tenant. The operation returns a [serviceHealth](../resources/servicehealth.md) object.
will update in all GET apis

2021-06-03 18:28 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +### Response
will update

2021-06-03 18:29 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +HTTP/1.1 200 OK
will add API Doctor code for each Request and Response

2021-06-03 18:31 UTC, payiAzure commented on api-reference/beta/api/servicehealth-list.md
> +Get service health overviews of tenant's all services. Returns a list of the [serviceHealth](../resources/servicehealth.md) objects and their properties.
yes. will update descriptions for all GET operations: use 1 sentence to describe the api, and 1 para after first line to add more explanations

2021-06-03 18:31 UTC, payiAzure commented on api-reference/beta/api/servicehealth-list.md
> +### Request
will update

2021-06-03 18:38 UTC, payiAzure commented on api-reference/beta/api/servicehealthissue-get.md
> +## Examples
yes, will update

2021-06-03 18:55 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +This POST action is to mark the status of a list of service update messages as archived for the login user.
make sense.
for the markRead, markUnread, Favorite, Unfavorite POST actions, I haven't think of a better 'verb' description for them.

2021-06-03 19:01 UTC, opbld33 commented
Docs Build status updates of commit _[8cdecbb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cdecbb623275dc8360743850b91159b28baf6b6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-5db770b7)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-5db770b7)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-5db770b7)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-5db770b7)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-5db770b7)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-5db770b7)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-5db770b7)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-5db770b7)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-5db770b7)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-5db770b7)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-5db770b7)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-5db770b7)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-5db770b7)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-5db770b7)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-5db770b7)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-5db770b7)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-5db770b7)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-5db770b7)
[api-refe [...]

2021-06-03 19:04 UTC, payiAzure commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +Gets the post incident report (PIR) document of a specified service issue for tenant. This operation returns Edm.Stream. The PIR won't be returned to tenant if the specified issue is not visible to t
Update to use "Retrieve" for all GET operations.

2021-06-03 19:07 UTC, opbld32 commented
Docs Build status updates of commit _[97f0a95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97f0a955737cf16ccf7d9fe2e843099166cd7e8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-f0d72835)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-f0d72835)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-f0d72835)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-f0d72835)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-f0d72835)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-f0d72835)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-f0d72835)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-f0d72835)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-f0d72835)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-f0d72835)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-f0d72835)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-f0d72835)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-f0d72835)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-f0d72835)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-f0d72835)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-f0d72835)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-f0d72835)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-f0d72835)
[api-refe [...]

2021-06-04 01:40 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +description: "Read service health overview of a specified service for tenant. The operation returns a [serviceHealth](../resources/servicehealth.md) object."
Please match the description with the first line of the doc (line 15). Just copy line 15 here, but without the link.

2021-06-04 01:40 UTC, opbld31 commented
Docs Build status updates of commit _[d4d6a63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4d6a63617f6afd5d128ad505c4ac2de572ff420)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-671546c5)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-671546c5)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-671546c5)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-671546c5)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-671546c5)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-671546c5)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-671546c5)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-671546c5)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-671546c5)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-671546c5)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-671546c5)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-671546c5)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-671546c5)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-671546c5)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-671546c5)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-671546c5)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-671546c5)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-671546c5)
[api-refe [...]

2021-06-04 01:48 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +This operation is to retrieve health overviews of a specified service for tenant.
Line 17: I feel this is a bit redundant. I understand the intention so, my suggestion:

- This operation provides the health report of the specified service in a tenant.

What do you think?

2021-06-04 01:50 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +### Example 1: Get the properties of a [serviceHealth](../resources/servicehealth.md) object
Line 56: Please remove the link from the tittle (serviceHealth).

2021-06-04 01:51 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +  "name": "get_servicehealth"
Line 95: Could you please use a different name for this example? 

You already used this name in Example 1 above.

2021-06-04 01:53 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +This operation is to retrieve health overviews of tenant's all subscribed services.
Line 17: similar observation as above:

This operation provides the health report of all subscribed services in a tenant.

2021-06-04 01:54 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +description: "Get service health overviews of tenant's all services. Returns a list of the serviceHealth objects and their properties."
Please use the description in line 15 here.

2021-06-04 01:54 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +### Example 1: Get properties of a list of [serviceHealth](../resources/servicehealth.md) objects
Please remove the link in serviceHealth

2021-06-04 02:06 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +  "name": "list_servicehealth"
Please use a different name for each example.

2021-06-04 02:07 UTC, isvargasmsft commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +This operation is to retrieve the post incident report (PIR) document of a specified service issue for tenant. The PIR won't be returned to tenant if the specified issue is not visible to tenant.
Please use "provides" instead of "is to retrieve".

2021-06-04 02:10 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-markunread.md
> +This POST action is to mark the status of a list of [service update messages](../resources/serviceupdatemessage.md) as unread for the login user.
Please use imperative:
Change the status of a list of service update messages to unread.

2021-06-04 02:11 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-markunread.md
> +If successful, this action returns a `200 OK` response code and a Boolean value True in the response body. Otherwise, will return False in the response body.
I dont think we need to use caps in "Boolean" and "true"

2021-06-04 02:11 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unarchive.md
> +This POST action is unarchive a list of [service update messages](../resources/serviceupdatemessage.md) for the login user.
Please use imperative:

Unarchive a list of...

2021-06-04 02:12 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unfavorite.md
> +This POST action is to mark the status of a list of [service update messages](../resources/serviceupdatemessage.md) as unfavorited for the login user.
Change the status of a list...

2021-06-04 02:15 UTC, isvargasmsft commented on api-reference/beta/resources/serviceannouncement.md
> +serviceAnnouncement is a top level container for service communications resources.
Please avoid starting sentences with the name of the resource. You can include an article at the beginning:
A serviceAnnouncement is a top level...

2021-06-04 02:17 UTC, isvargasmsft commented on api-reference/beta/resources/serviceannouncement.md
> +None.
Line 19:
This resource type doesn't have methods.

2021-06-04 02:17 UTC, isvargasmsft commented on api-reference/beta/resources/serviceannouncement.md
> +None.
This resource type doesn't have properties.

2021-06-04 02:19 UTC, isvargasmsft commented on api-reference/beta/resources/serviceannouncementbase.md
> +A base resource type for [serviceHealthIssue](../resources/servicehealthissue.md) and [serviceUpdateMessage](../resources/serviceupdatemessage.md).
Could we define the resource type by itself? It is better if we avoid relying on other resources to define one.

2021-06-04 02:22 UTC, isvargasmsft commented on api-reference/beta/resources/serviceannouncementbase.md
> +None.
Suggestion: This resource type doesn't have methods.

2021-06-04 02:22 UTC, isvargasmsft commented on api-reference/beta/resources/servicehealth.md
> +A resource type for service health, to represent the health information of a service.
Line 16: Represents the health information of a service.

2021-06-04 02:26 UTC, isvargasmsft commented on api-reference/beta/resources/servicehealthissue.md
> +An entity resource type inherited from [serviceAnnouncementBase](../resources/serviceannouncementbase.md), to represent an issue happened for a service. The service health issue could be a service in
Line 16: Represents an service health issue in a service. 
(blank line)
The service health issue can be either a service incident or a service advisory. For example: 
- Service incident: "Exchange mailbox is down".
- Service advisory: "Users may experience delays in emails reception".

What do you think?

2021-06-04 02:57 UTC, isvargasmsft commented on api-reference/beta/resources/servicehealthissuepost.md
> +This complex type represents the history posts which involving new post type for the service issue.
Line 16: This description is not clear. 
1. Do you mean historical posts? All posts? 
2. What is "involving new post type"?

2021-06-04 03:37 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-get.md
> +        ...
Lines 148 and 151: I think these "..." are causing an API Doctor error. Could you please remove them?

2021-06-04 03:38 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +    ...
Line 97: I think the 3 dots are causing an API Doctor error, could you remove them please?

2021-06-04 03:39 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +    ...
161, 164, 167: Please remove the 3 dots to see if that solves the API Doctor error.

2021-06-04 03:43 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-list.md
> +  "@odata.type": "Collection(microsoft.grpah.serviceUpdateMessage)"
Line 71: There is a typo: microsoft.graph.serviceUpdateMessage

2021-06-04 03:45 UTC, isvargasmsft commented on api-reference/beta/api/servicehealth-list.md
> +  "@odata.type": "Collection(microsoft.graph.serviceHealth)"
Please dont use: Collection(data type). 

Instead, please use:
 "@odata.type": "microsoft.graph.serviceHealth",
  "isCollection": true

Please apply this in all "List: documents.

2021-06-04 03:52 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +An entity resource type inherited from base type [serviceAnnouncementBase](../resources/serviceannouncementbase.md) to represent announcement, such as major update, for a service. e.g. Windows servic
Please make it clear and short. These descriptions lines are what search engines use to display results. My suggestion:
Represents the announcements of changes in a service. 

This resource type inherits from serviceAnnouncements, and serves to important publications such as major updates in a product. For example, the publication of a new Windows feature.

What do you think?

2021-06-04 04:03 UTC, isvargasmsft requested changes
Hello Pan Yi! 

Very nice work in this PR! Thank you very much. 

Please pay attention to:
1. The description should match the first line of each document. 
2. The first line of each document should be clear, short and simple. Please consider this is what search engines use to display results. Try to use imperatives and simple words. 
3. If a resource type does not have methods, please state it in a sentence. 
4. Please pay attention to the API Doctor errors. I know we are waiting for this service area, but there are some details we can fix now. 
5. Please use different names in each example in the API Doctor code. 

Remember to implement comments across all docs. Please feel free to ping me on the side if you have questions. 

Kind regards, 

Isaac Vargas

2021-06-04 04:55 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +### Including navigation property issues in the [serviceHealth](../resources/servicehealth.md) object
will remove links in title

2021-06-04 04:55 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews('Microsoft 365 suite')?$expand=issues
will update

2021-06-04 04:56 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +description: "Read service health overview of a specified service for tenant. The operation returns a [serviceHealth](../resources/servicehealth.md) object."
got it. will do.

2021-06-04 05:00 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +This operation is to retrieve health overviews of a specified service for tenant.
Thanks. I will use "This operation provides the health report of the specified service **for** a tenant."

2021-06-04 05:16 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +### Example 1: Get the properties of a [serviceHealth](../resources/servicehealth.md) object
will remove

2021-06-04 05:17 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-markunread.md
> +If successful, this action returns a `200 OK` response code and a Boolean value True in the response body. Otherwise, will return False in the response body.
Will update in all action files

2021-06-04 05:18 UTC, payiAzure commented on api-reference/beta/resources/serviceannouncement.md
> +serviceAnnouncement is a top level container for service communications resources.
will update it with "A serviceAnnouncement is a top level container .....".

2021-06-04 05:19 UTC, payiAzure commented on api-reference/beta/resources/serviceannouncementbase.md
> +A base resource type for [serviceHealthIssue](../resources/servicehealthissue.md) and [serviceUpdateMessage](../resources/serviceupdatemessage.md).
yes, make sense. I will remove the serviceannouncementbase resource. And define properties for servicehealthissue and serviceupdatemessage resource correspondingly.

2021-06-04 05:24 UTC, payiAzure commented on api-reference/beta/resources/servicehealthissue.md
> +An entity resource type inherited from [serviceAnnouncementBase](../resources/serviceannouncementbase.md), to represent an issue happened for a service. The service health issue could be a service in
Thanks. looks Much better! I will update it

2021-06-04 05:25 UTC, payiAzure commented on api-reference/beta/resources/servicehealthissuepost.md
> +This complex type represents the history posts which involving new post type for the service issue.
I will update the description as:
This complex type represents a historical post object for a service health issue.

2021-06-04 05:25 UTC, payiAzure commented on api-reference/beta/api/servicehealth-get.md
> +        ...
yes, found this error in API doctor validation. will remove them in all example response

2021-06-04 05:26 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-list.md
> +  "@odata.type": "Collection(microsoft.grpah.serviceUpdateMessage)"
Thanks for catching. Will fix it.

2021-06-04 05:26 UTC, payiAzure commented on api-reference/beta/api/servicehealth-list.md
> +  "@odata.type": "Collection(microsoft.graph.serviceHealth)"
will update.

2021-06-04 05:29 UTC, payiAzure commented on api-reference/beta/resources/serviceupdatemessage.md
> +An entity resource type inherited from base type [serviceAnnouncementBase](../resources/serviceannouncementbase.md) to represent announcement, such as major update, for a service. e.g. Windows servic
yes, make sense.

2021-06-04 05:41 UTC, opbld31 commented
Docs Build status updates of commit _[8d690ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d690ca18eede7b9141905c3997f2790fba64f96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-0f51ad3c)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-0f51ad3c)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-0f51ad3c)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-0f51ad3c)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-0f51ad3c)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-0f51ad3c)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-0f51ad3c)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-0f51ad3c)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-0f51ad3c)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-0f51ad3c)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-0f51ad3c)
[api-reference/bet [...]

2021-06-04 18:07 UTC, opbld34 commented
Docs Build status updates of commit _[34137c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34137c4c5c381e39661ed727cec2d8d784bba719)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-656448df)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-656448df)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-656448df)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-656448df)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-656448df)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-656448df)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-656448df)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-656448df)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-656448df)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-656448df)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-656448df)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-656448df)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-656448df)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-656448df)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-656448df)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-656448df)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-656448df)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-656448df)
[api-reference/bet [...]

2021-06-04 18:20 UTC, opbld34 commented
Docs Build status updates of commit _[2cc97f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cc97f8d8386f9ed53daa193f2457d06b036793b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-23f3b608)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-23f3b608)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-23f3b608)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-23f3b608)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-23f3b608)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-23f3b608)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-23f3b608)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-23f3b608)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-23f3b608)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-23f3b608)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-23f3b608)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-23f3b608)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-23f3b608)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-23f3b608)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-23f3b608)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-23f3b608)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-23f3b608)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-23f3b608)
[api-reference/bet [...]

2021-06-04 18:21 UTC, payiAzure commented on api-reference/beta/resources/serviceupdatemessage.md
> +An entity resource type inherited from base type [serviceAnnouncementBase](../resources/serviceannouncementbase.md) to represent announcement, such as major update, for a service. e.g. Windows servic
will update

2021-06-04 18:21 UTC, payiAzure commented on api-reference/beta/api/servicehealth-list.md
> +    ...
yes, removed them in updates

2021-06-04 18:28 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-unarchive.md
> +This POST action is unarchive a list of [service update messages](../resources/serviceupdatemessage.md) for the login user.
yes, updated the descriptions for all POST actions.

2021-06-04 20:15 UTC, opbld34 commented
Docs Build status updates of commit _[9bd962e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bd962e8b8beef2a0bc4ba3acddd0aaae3c4b164)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-afd80664)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-afd80664)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-afd80664)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-afd80664)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-afd80664)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-afd80664)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-afd80664)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-afd80664)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-afd80664)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-afd80664)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-afd80664)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-afd80664)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-afd80664)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-afd80664)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-afd80664)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-afd80664)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-afd80664)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-afd80664)
[api-reference/bet [...]

2021-06-05 03:30 UTC, opbld33 commented
Docs Build status updates of commit _[549b96a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/549b96a86598337308d094f77baad890de8ca879)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-730d6fbf)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-730d6fbf)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-730d6fbf)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-730d6fbf)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-730d6fbf)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-730d6fbf)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-730d6fbf)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-730d6fbf)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-730d6fbf)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-730d6fbf)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-730d6fbf)
[api-reference/bet [...]

2021-06-05 04:05 UTC, opbld32 commented
Docs Build status updates of commit _[9a9aebd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a9aebd461786c9ad29240c6e8b0f78a86c5f00e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-d5cf0b97)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-d5cf0b97)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-d5cf0b97)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-d5cf0b97)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-d5cf0b97)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-d5cf0b97)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-d5cf0b97)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-d5cf0b97)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-d5cf0b97)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-d5cf0b97)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-d5cf0b97)
[api-reference/bet [...]

2021-06-05 04:37 UTC, opbld33 commented
Docs Build status updates of commit _[b0e86e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0e86e998fc0219e5c8a3e5e472d409a3bd64ef4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-9513053a)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-9513053a)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-9513053a)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-9513053a)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-9513053a)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-9513053a)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-9513053a)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-9513053a)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-9513053a)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-9513053a)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-9513053a)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-9513053a)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-9513053a)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-9513053a)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-9513053a)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-9513053a)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-9513053a)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-9513053a)
[api-reference/bet [...]

2021-06-05 05:00 UTC, opbld30 commented
Docs Build status updates of commit _[3e0a966](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e0a9665dd54fa6585d2d262791750bd4e10955e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-0765fa96)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-0765fa96)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-0765fa96)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-0765fa96)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-0765fa96)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-0765fa96)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-0765fa96)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-0765fa96)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-0765fa96)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-0765fa96)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-0765fa96)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-0765fa96)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-0765fa96)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-0765fa96)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-0765fa96)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-0765fa96)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-0765fa96)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-0765fa96)
[api-reference/bet [...]

2021-06-07 17:36 UTC, opbld31 commented
Docs Build status updates of commit _[4599b62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4599b6233303fb0da0dc605510970fe5e2f9701f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-3730896f)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-3730896f)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-3730896f)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-3730896f)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-3730896f)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-3730896f)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-3730896f)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-3730896f)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-3730896f)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-3730896f)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-3730896f)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-3730896f)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-3730896f)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-3730896f)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-3730896f)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-3730896f)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-3730896f)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-3730896f)
[api-reference/bet [...]

2021-06-07 20:31 UTC, isvargasmsft commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +This operation provides the post incident report (PIR) document of a specified service issue for tenant. The PIR won't be returned to tenant if the specified issue is not visible to tenant.
Please re-phrase using imperative and avoid using passive voice. For example:
Retrieve the post incident report (PIR) document of a specified service issue for a tenant. 
//blank line
This operation returns an error if the tenant does not have the required permissions to see the issue.

2021-06-07 20:34 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +  "messageIds": ["messageid-value"]
Can we use real looking information in this example as well? 

I'd deeply appreciate it.

2021-06-07 20:35 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +Change the status of a list of service update messages to favorited for the login user.
Favorite*
Is it a typo or intentional?

2021-06-07 20:37 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +|messageIds|String collection|Tell which messages for the user will be marked wtih **favorited** status|
Please re-phrase to avoid passive voice:
List of message IDs to save as favorite.

2021-06-07 20:37 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +  "messageIds": ["messageid-value"]
Could we please use a real looking ID in line 69?

2021-06-07 20:42 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-get.md
> +This operation retrieves a specified SHD service message for the tenant. If the message is not visible to tenant or the message does not impact the tenant, it won't be returned.
Line 17: 
1. Please mention the complete name for SHD the first time. You can include the name and the initials inside parentheses. 
2. Please avoid using passive voice.

2021-06-07 20:48 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +Change the status of a list of service update messages to favorited for the login user.
it is intentional

2021-06-07 20:50 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-list.md
> +This operation retrieves all SHD service messages that are visible to the tenant and impact the tenant.
Similar observation above:
Please rephrase using active voice and include the complete name instead of acronyms in the first mention. For example:

This operation retrieves all Service Health Documents?(SHD) that affected the tenant. The operation returns an error if the tenant doesn't have the required permissions to see the SHD.

2021-06-07 20:53 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-markread.md
> +  "messageIds": ["messageid-value"]
Line 68: Please include a real looking example of messageID

2021-06-07 20:54 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-markunread.md
> +Change the status of a list of service update messages to unread for the login user.
Is serviceUpdateMessage a resource type? If so, please include the reference link.

2021-06-07 20:56 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +Change the status of a list of service update messages to favorited for the login user.
Please include the reference link to serviceUpdateMessage.

2021-06-07 20:56 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +Archive a list of service update messages for the login user.
Please include the reference link to serviceUpdateMessage.

2021-06-07 20:57 UTC, isvargasmsft commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +Provides incident report in Edm.Steam.
Isn't incidentReport a resource type? If so, please include the reference link.

2021-06-07 20:58 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-markread.md
> +Change the status of a list of service update messages to read for the login user.
Please include the reference link to serviceUpdateMessage.

2021-06-07 20:59 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unarchive.md
> +Unarchive a list of service update messages for the login user.
Please include the link to serviceUpdateMessage.

2021-06-07 21:00 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +|messageIds|String collection|Tell which messages for the user will be marked wtih **archived** status|
Please re-phrase to avoid passive voice:
List of message IDs to archive.

2021-06-07 21:08 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-markread.md
> +|messageIds|String collection|Tell which messages for the user will be marked wtih **read** status|
Please re-phrase to avoid passive voice:
List of message IDs to mark as read.

2021-06-07 21:10 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-markread.md
> +Change the status of a list of service update messages to read for the login user.
I am reconsidering this line 15. The Outlook user interface uses **Mark as Read**. So I think users would search using those words. In this particular case, it would be good to use:
Mark a list of [serviceUpdateMessage] (link here)s as **read** for the login user.

2021-06-07 21:12 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unarchive.md
> +|messageIds|String collection|Tell which messages for the user will be marked wtih **unarchived** status|
Please re-phrase to avoid passive voice:
List of message IDs to unarchive.

2021-06-07 21:12 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unarchive.md
> +  "messageIds": ["messageid-value"]
Could we please use examples of real looking messages IDs here?

2021-06-07 21:15 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unfavorite.md
> +Change the status of a list of service update messages to unfavorited for the login user.
Line 15:
1. Please include the reference link to serviceUpdateMessages. 
2. Is "unfavorited" a valid status for this resource type? If not, please rephrase. My suggestion:
Remove the favorite status of [serviceUpdateMessage} (link here)s.

2021-06-07 21:16 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unfavorite.md
> +Change the status of a list of service update messages to unfavorited for the login user.
Remember to change this in line 3 (description) as well.

2021-06-07 21:17 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unfavorite.md
> +|messageIds|String collection|Tell which messages for the user will be marked wtih **unfavorited** status|
Please re-phrase to avoid passive voice:
List of message IDs to remove from favorites.

2021-06-07 21:17 UTC, isvargasmsft commented on api-reference/beta/api/serviceupdatemessage-unfavorite.md
> +  "messageIds": ["messageid-value"]
Please use a real looking message ID.

2021-06-07 21:48 UTC, isvargasmsft commented on api-reference/beta/resources/servicehealthissue.md
> +|details|Collection([keyValuePair](../resources/keyvaluepair.md))|More details about service health issue that don't need to be filter based properties are put in this key value pair collection.|
Line 34: Please rephrase using active voice. For example:
Additional details about the service issue. This property doesn't support filters.

2021-06-07 21:48 UTC, payiAzure commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +This operation provides the post incident report (PIR) document of a specified service issue for tenant. The PIR won't be returned to tenant if the specified issue is not visible to tenant.
for the description after blank line: "This operation returns an error if the tenant does not have the required permissions to see the issue."
I prefer to use: the operation returns an error if the the specified issue shouldn't be visible to tenant.

Since it is not permission related restriction for the tenant. If we use "required permission" here, it mislead the customer about our API permission and tenant-service mapping stuff provided by our service.

2021-06-07 21:50 UTC, isvargasmsft commented on api-reference/beta/resources/servicehealthissue.md
> +|isResolved|Boolean|Boolean value to tell if the issue is resolved. Used by filter.|
Please rephrase with simple words:
Indicates whether the issue is resolved.

2021-06-07 21:52 UTC, isvargasmsft commented on api-reference/beta/resources/servicehealthissue.md
> +|origin|serviceHealthOrigin|The origin of the service issue, tells the cause of the issue is from Microsoft, or third party or customer. Possible values are: `Microsoft`, `ThirdParty`, `Customer`, `u
Please re-phrase with friendly words:
Indicates the origin of the incident. Possible values are: ...

2021-06-07 21:52 UTC, isvargasmsft commented on api-reference/beta/resources/servicehealthissue.md
> +|service|String|The affected service by the service issue|
Line 44: Indicates the service affected by the issue.

2021-06-07 21:55 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +|messageIds|String collection|Tell which messages for the user will be marked wtih **favorited** status|
yes, will do for other action files as well.

2021-06-07 21:55 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +  "messageIds": ["messageid-value"]
yes, updating it with real example. also in other action files example

2021-06-07 21:59 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-get.md
> +This operation retrieves a specified SHD service message for the tenant. If the message is not visible to tenant or the message does not impact the tenant, it won't be returned.
Thanks. I will remove SHD here since it was put here for no reason.
we prefer to use the description as:
This operation retrieves a specified service update message for the tenant. The operation returns an error if the message is not visible to tenant or the message does not impact the tenant.

2021-06-07 22:02 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-list.md
> +This operation retrieves all SHD service messages that are visible to the tenant and impact the tenant.
I will remove SHD. update the description as:
This operation retrieves a specified service update message for the tenant. The operation returns an error if the message is not visible to tenant or the message does not impact the tenant.

2021-06-07 22:02 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +|[List serviceUpdateMessages](../api/serviceupdatemessage-list.md)|[serviceUpdateMessage](../resources/serviceupdatemessage.md) collection|Gets all SHD service messages for the tenant. The operation
Line 23: 
1. Gets all messages in a **Service Health Dashboard (SHD)** for a tenant.
2. Please fix typo in The operation returns a list of...

2021-06-07 22:04 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +  "messageIds": ["messageid-value"]
yes, will use real looing ID here. as well as other examples in unread/read/archive/unarchive/unfavorite

2021-06-07 22:05 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-markunread.md
> +Change the status of a list of service update messages to unread for the login user.
yes. it is a real resource. will add ref link for it here. as well as other files

2021-06-07 22:05 UTC, payiAzure commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +Provides incident report in Edm.Steam.
no. it is not a resource.

2021-06-07 22:23 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-markread.md
> +|messageIds|String collection|Tell which messages for the user will be marked wtih **read** status|
will update

2021-06-07 22:25 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-unfavorite.md
> +Change the status of a list of service update messages to unfavorited for the login user.
yes, it is a valid status for user for the resource serviceUpdateMessage

2021-06-07 22:38 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +|[markRead](../api/serviceupdatemessage-markread.md)|Boolean|This POST action is to change the status of a list of service update messages to read for the login user.|
Please use the actual descriptions of each document. In this case: Change the status of serviceUpdateMessages to read for the login user.

2021-06-07 22:38 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +|[markRead](../api/serviceupdatemessage-markread.md)|Boolean|This POST action is to change the status of a list of service update messages to read for the login user.|
Please apply to other lines in this table.

2021-06-07 22:40 UTC, payiAzure commented on api-reference/beta/resources/servicehealthissue.md
> +|details|Collection([keyValuePair](../resources/keyvaluepair.md))|More details about service health issue that don't need to be filter based properties are put in this key value pair collection.|
will update. and also update this property in serviceUpdateMessage

2021-06-07 22:42 UTC, payiAzure commented on api-reference/beta/resources/servicehealthissue.md
> +|isResolved|Boolean|Boolean value to tell if the issue is resolved. Used by filter.|
will update

2021-06-07 22:42 UTC, payiAzure commented on api-reference/beta/resources/servicehealthissue.md
> +|origin|serviceHealthOrigin|The origin of the service issue, tells the cause of the issue is from Microsoft, or third party or customer. Possible values are: `Microsoft`, `ThirdParty`, `Customer`, `u
will update

2021-06-07 22:43 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +|actionRequiredByDateTime|DateTimeOffset|The time by when the required action needs to be done for the service message|
35: Can we re-phrase: The expected deadline or ETA for the action?

2021-06-07 22:44 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +|details|Collection([keyValuePair](../resources/keyvaluepair.md)|More details about service message that don't need to be filter based properties are put in this key value pair collection.|
Can we rephrase line 38: Additional details about the service issue. This property doesn't support filters.

2021-06-07 22:45 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +|isMajorChange|Boolean|The value indicating whether the message describes a major update for the service|
Line 41: Indicates whether the message describes a major service update.

2021-06-07 22:46 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessage.md
> +None.
This resource type doesn't have relationships.

2021-06-07 22:47 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessageviewpoint.md
> +A complex type represents user view points data for a service update message. For example, indicating whether a message is marked as read/archived/favorited for the user.
Please make this one consistent with line 3:
Represents user view points data for a [serviceUpdateMessage] (include link in line 16).

2021-06-07 22:49 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessageviewpoint.md
> +|isRead|Boolean|The value indicating whether the message is favorited by the user|
Lines 21 to 23: 
Indicates whether the user read the message.
Indicates whether the user archived the message. 
Indicates whether the user marked the message as favorite.

2021-06-07 22:49 UTC, isvargasmsft commented on api-reference/beta/resources/serviceupdatemessageviewpoint.md
> +None.
This resource type doesn't have relationships.

2021-06-07 22:51 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +        - name: Service communications (preview)
Line 14181: Is there a reason to add the "(preview)"?

If this is in beta I believe it is not necessary.

2021-06-07 22:52 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +          - name: healthOverviews
I think we can use regular caps here instead of camel caps: Health overviews.

2021-06-07 22:53 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +            - name: Get service health
Please use camel caps in this one: Get serviceHealth. Because serviceHealth is a resource type.

2021-06-07 22:53 UTC, isvargasmsft commented on api-reference/beta/toc.yml
> +            - name: Get service health
Please apply camel caps to all other resource types, methods and such in this list.

2021-06-07 22:57 UTC, isvargasmsft requested changes
Final details here. 
1. Please use real looking IDs in the examples. 
2. Please pay attention to general phrasing choices. I encourage you to take time to review [Microsoft Writing Style](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=33685).

2021-06-08 00:10 UTC, payiAzure commented on api-reference/beta/toc.yml
> +        - name: Service communications (preview)
I see this information: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/138210/Mark-beta-API-as-preview?anchor=mark-content-for-beta-api-as-preview.
**APIs that are only available in the beta endpoint and not the GA (v1.0 currently) endpoint are in "preview" status.**

so I followed the instruction to mark content and preview

2021-06-08 04:11 UTC, payiAzure commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +This operation provides the post incident report (PIR) document of a specified service issue for tenant. The PIR won't be returned to tenant if the specified issue is not visible to tenant.
suggestions from our PM: we only return message like "the operation returns an error if the issue does not exist for the tenant"

2021-06-08 04:12 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +Change the status of a list of service update messages to favorited for the login user.
Will update the description as: 
Change the status of a list of [serviceUpdateMessage](../resources/serviceupdatemessage.md) to favorite for the login user.

2021-06-08 04:25 UTC, payiAzure commented on api-reference/beta/api/serviceupdatemessage-markread.md
> +Change the status of a list of service update messages to read for the login user.
got it. will update it as you suggested. also update the unread.

Mark a list of [serviceUpdateMessage] (link here)s as read for the login user.

2021-06-08 04:47 UTC, payiAzure commented on api-reference/beta/resources/serviceupdatemessage.md
> +|[markRead](../api/serviceupdatemessage-markread.md)|Boolean|This POST action is to change the status of a list of service update messages to read for the login user.|
yes, updates description as the same as the action documentation description for each.

2021-06-08 04:53 UTC, payiAzure commented on api-reference/beta/resources/serviceupdatemessage.md
> +None.
will update

2021-06-08 04:58 UTC, payiAzure commented on api-reference/beta/resources/serviceupdatemessageviewpoint.md
> +|isRead|Boolean|The value indicating whether the message is favorited by the user|
will update

2021-06-08 05:11 UTC, opbld31 commented
Docs Build status updates of commit _[448a20c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/448a20c407ce25e6ae1856c503b29d5b6b2448db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-fc392938)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-fc392938)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-fc392938)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-fc392938)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-fc392938)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-fc392938)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-fc392938)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-fc392938)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-fc392938)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-fc392938)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-fc392938)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-fc392938)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-fc392938)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-fc392938)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-fc392938)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-fc392938)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-fc392938)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-fc392938)
[api-reference/bet [...]

2021-06-08 19:48 UTC, opbld33 commented
Docs Build status updates of commit _[c2a72f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2a72f52f807af6624ca94e52f98eeeff1413606)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-061b89c7)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-061b89c7)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-061b89c7)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-061b89c7)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-061b89c7)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-061b89c7)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-061b89c7)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-061b89c7)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-061b89c7)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-061b89c7)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-061b89c7)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-061b89c7)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-061b89c7)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-061b89c7)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-061b89c7)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-061b89c7)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-061b89c7)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-061b89c7)
[api-reference/bet [...]

2021-06-08 22:30 UTC, opbld33 commented
Docs Build status updates of commit _[59a5165](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59a5165f1a57e007599dc9b8187d2aaa26d82502)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-592e08fc)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-592e08fc)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-592e08fc)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-592e08fc)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-592e08fc)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-592e08fc)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-592e08fc)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-592e08fc)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-592e08fc)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-592e08fc)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-592e08fc)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-592e08fc)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-592e08fc)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-592e08fc)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-592e08fc)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-592e08fc)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-592e08fc)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-592e08fc)
[api-reference/bet [...]

2021-06-10 04:28 UTC, opbld31 commented
Docs Build status updates of commit _[d5d5a0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5d5a0ced937e068b412f50d8a58fc823db22dc1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-f7a3e3fb)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-f7a3e3fb)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-f7a3e3fb)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-f7a3e3fb)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-f7a3e3fb)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-f7a3e3fb)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-f7a3e3fb)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-f7a3e3fb)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-f7a3e3fb)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-f7a3e3fb)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-f7a3e3fb)
[api-reference/bet [...]

2021-06-10 04:53 UTC, opbld31 commented
Docs Build status updates of commit _[d1e0780](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1e0780783edb86eff90096fd57e817df3029ad2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-229afb4a)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-229afb4a)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-229afb4a)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-229afb4a)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-229afb4a)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-229afb4a)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-229afb4a)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-229afb4a)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-229afb4a)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-229afb4a)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-229afb4a)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-229afb4a)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-229afb4a)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-229afb4a)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-229afb4a)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-229afb4a)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-229afb4a)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-229afb4a)
[api-reference/bet [...]

2021-06-10 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[c21d5a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c21d5a9d1071dbc64dd48c82e96c02b39980bf9e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-43549f75)
[api-reference/beta/api/servicehealth-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ce81674bbd3d06aeaceb750f449d118b-43549f75)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-43549f75)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-43549f75)
[api-reference/beta/api/servicehealthissue-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a72d6a4d5e7074c8fc2c15e0a4f9ad50-43549f75)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-43549f75)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-43549f75)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-43549f75)
[api-reference/beta/api/serviceupdatemessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-list?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-837dd719b1dbf260dfe180b896549017-43549f75)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-43549f75)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-43549f75)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-43549f75)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-43549f75)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-43549f75)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-43549f75)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-43549f75)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-43549f75)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-1fe35ab6aca3c107838b5e8b133ff3e0-43549f75)
[api-reference/bet [...]

2021-06-10 19:14 UTC, isvargasmsft approved these changes
Thank you very much Pan. Very nice work in this PR.

2021-06-11 01:48 UTC, Lauragra commented on api-reference/beta/api/servicehealth-get.md
> +**Note:** The response object shown here might be shortened for readability.
Global: This boilerplate text should be formatted as a note, for consistency. I think we had a bug in our stub generator for a period of time. To format this text as a note, please add a ">" symbol at the beginning of the line. Please apply globally to all occurrences.

2021-06-11 01:51 UTC, Lauragra commented on api-reference/beta/api/servicehealth-get.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews/Microsoft 365 suite
Please verify that it's accurate to have spaces in the URL? The spaces are not replaced with special characters (i.e. "%20")?

2021-06-11 01:56 UTC, Lauragra commented on api-reference/beta/api/servicehealth-list.md
> +GET /admin/serviceAnnouncement/healthOverviews
Based on this syntax, it looks like the file name here should be serviceannouncement-list-healthoverviews. The title would be List healthOverviews. The description and title for this topic don't currently appear to match the HTTP request syntax. Please double-check and verify whether it's the filename/title/description that's off or whether the HTTP syntax here is not accurate. The examples appear to match this syntax so it might be the former that needs to be updated.

2021-06-11 01:57 UTC, Lauragra commented on api-reference/beta/api/servicehealth-get.md
> +## Optional query parameters
Global: For the Optional query parameters section, it's helpful if you can update the boilerplate text to specify whether some, all, or no query parameters are supported, and if applicable, which ones.

2021-06-11 01:57 UTC, Lauragra commented on api-reference/beta/api/servicehealth-get.md
> +GET /admin/serviceAnnouncement/healthOverviews/{Service Name}
If the space shouldn't be in the URL, you might also want to update the placeholder, i.e. {service-name}.

2021-06-11 02:07 UTC, Lauragra commented on api-reference/beta/api/servicehealthissue-get.md
> +|Delegated (work or school account)|ServiceHealth.Read.All|
This looks like a new permission - please include an update to the permissions reference to list this new permission as part of this PR.

2021-06-11 04:01 UTC, Lauragra commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +Provides the post incident report (PIR) document of a specified service issue for tenant.
Use the imperative verb form - Provide.

2021-06-11 04:05 UTC, Lauragra commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +Provides the post incident report (PIR) document of a specified service issue for tenant.
Please double-check the use of the acronym PIR. I see it used for Post-Incident Review. Also, I recommend hyphenated post-incident for clarity and to assist with localization.

2021-06-11 04:09 UTC, Lauragra commented on api-reference/beta/api/servicehealthissue-incidentreport.md
> +If successful, this function returns a `200 OK` response code and a Stream in the response body.
Is Stream a proper noun? Is it a reference to the Microsoft Stream service, and how is that related to incident reports? Will this concept be clear to readers? In the response example, is the Stream value a placeholder for something that represents an incident report?

2021-06-11 04:10 UTC, Lauragra commented on api-reference/beta/api/servicehealthissue-list.md
> +Retrieve a list of the [serviceHealthIssue](../resources/servicehealthissue.md) objects and their properties.
Remove "the" in this sentence because you aren't referring to a specific serviceHealthIssue.

2021-06-11 04:10 UTC, Lauragra commented on api-reference/beta/api/servicehealthissue-list.md
> +This operation retrieves information of all service health issues that exist for the tenant.
Change "information of" to "information about".

2021-06-11 04:12 UTC, Lauragra commented on api-reference/beta/api/servicehealthissue-list.md
> +title: "List serviceHealthIssues"
The file name here should be serviceannouncement-list-issues, and the title should be "List issues". For list operations, we use the nav property name, not the resource type. For reference see the file naming guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming and the topic title guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title.

2021-06-11 04:13 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +Archive a list of [serviceUpdateMessage](../resources/serviceupdatemessage.md)s for the login user.
Add the s to the link text; otherwise it will look strange on the live site. Also, change the last part of the sentence to "for the signed in user."

2021-06-11 04:14 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +|Delegated (personal Microsoft account)|ServiceMessageViewpoint.Write|
Add the Application row here.

2021-06-11 04:15 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +If successful, this action returns a `200 OK` response code and a boolean value true in the response body. Otherwise, will return false in the response body.
Boolean is always capitalized. Please also add tic marks around the values, i.e. `true`, `false`.

2021-06-11 04:15 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-archive.md
> +**Note:** The response object shown here might be shortened for readability.
If the response is only ever true or false, we don't need this note in that case.

2021-06-11 04:16 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +Change the status of a list of [serviceUpdateMessage](../resources/serviceupdatemessage.md)s to favorite for the login user.
Here and in the description, change "the login user" to "the signed in user". Also move the s here to inside the link.

2021-06-11 04:18 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +|Delegated (personal Microsoft account)|ServiceMessageViewpoint.Write|
Add the missing Application row.

2021-06-11 04:19 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +In the request body, supply JSON representation of the parameters.
Add the missing article "a" after supply.

2021-06-11 04:19 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +If successful, this action returns a `200 OK` response code and a boolean value true in the response body. Otherwise, will return false in the response body.
Capitalize Boolean and add the formatting to the values.

2021-06-11 04:20 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-favorite.md
> +**Note:** The response object shown here might be shortened for readability.
Remove note.

2021-06-11 19:15 UTC, opbld34 commented
Docs Build status updates of commit _[28cb3d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28cb3d8020c912cb50654d7790f02ff3c5f02032)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-98f8ae58)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-98f8ae58)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-98f8ae58)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-98f8ae58)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-98f8ae58)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-98f8ae58)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-98f8ae58)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-98f8ae58)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-98f8ae58)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-98f8ae58)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-98f8ae58)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-98f8ae58)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-98f8ae58)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-98f8ae58)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-98f8ae58)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-98f8ae58)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-98f8ae58)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-11 23:11 UTC, opbld33 commented
Docs Build status updates of commit _[f6aa4db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6aa4db31633e4f105cb41ad791b00144576a14c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-529c7618)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-529c7618)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-529c7618)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-529c7618)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-529c7618)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-529c7618)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-529c7618)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-529c7618)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-529c7618)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-529c7618)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-529c7618)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-529c7618)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-529c7618)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-529c7618)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-529c7618)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-529c7618)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-529c7618)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-14 21:04 UTC, Lauragra commented on api-reference/beta/api/serviceannouncement-list-healthoverviews.md
> +Retrieve the [serviceHealth](../resources/servicehealth.md) resources from the healthOverviews navigation property.
Global: Property names should have bold formatting; please make healthOverviews bold.

2021-06-14 22:07 UTC, opbld31 commented
Docs Build status updates of commit _[99742d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99742d8d4448a66d07fa02363db283758ad680fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-fd763809)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-fd763809)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-fd763809)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-fd763809)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-fd763809)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-fd763809)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-fd763809)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-fd763809)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-fd763809)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-fd763809)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-fd763809)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-fd763809)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-fd763809)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-fd763809)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-fd763809)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-fd763809)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-fd763809)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-14 22:15 UTC, opbld31 commented
Docs Build status updates of commit _[c77b173](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c77b173a6e3a6ffd6777133662625c6e7ffe7f17)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-d4ae951f)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-d4ae951f)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-d4ae951f)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-d4ae951f)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-d4ae951f)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-d4ae951f)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-d4ae951f)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-d4ae951f)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-d4ae951f)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-d4ae951f)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-d4ae951f)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-d4ae951f)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-d4ae951f)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-d4ae951f)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-d4ae951f)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-d4ae951f)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-d4ae951f)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-14 23:36 UTC, Lauragra commented on api-reference/beta/api/servicehealth-get.md
> +GET https://graph.microsoft.com/beta/admin/serviceAnnouncement/healthOverviews/Microsoft 365 suite?$expand=issues
Just to verify, this request URL will work with the spaces in the service name?

2021-06-14 23:39 UTC, opbld32 commented
Docs Build status updates of commit _[d847482](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d847482933d13b07fdd097bfbf452d0792d9ddd5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-c815ebca)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-c815ebca)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-c815ebca)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-c815ebca)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-c815ebca)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-c815ebca)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-c815ebca)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-c815ebca)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-c815ebca)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-c815ebca)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-c815ebca)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-c815ebca)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-c815ebca)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-c815ebca)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-c815ebca)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-c815ebca)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-c815ebca)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-14 23:45 UTC, Lauragra commented on api-reference/beta/api/serviceupdatemessage-markread.md
> +|Delegated (personal Microsoft account)|ServiceMessageViewpoint.Write|
Global: Add the Application row to all tables in the Permissions sections.

2021-06-14 23:47 UTC, Lauragra commented on api-reference/beta/resources/serviceannouncement.md
> +|[List healthOverviews](../api/serviceannouncement-list-healthoverviews.md)|[serviceHealth](../resources/servicehealth.md) collection|Get the serviceHealth resources from the **healthOverviews** navi
How are we determining which methods to list here? These methods technically aren't on the serviceAnnouncement resource. Should this be a list of all methods, since it's currently the root topic of the TOC node?

2021-06-14 23:48 UTC, Lauragra commented on api-reference/beta/resources/serviceannouncement.md
> +|[List healthOverviews](../api/serviceannouncement-list-healthoverviews.md)|[serviceHealth](../resources/servicehealth.md) collection|Get the serviceHealth resources from the **healthOverviews** navi
Global: Note that resource names in descriptions also need to be bold, i.e. **serviceHealth**.

2021-06-14 23:53 UTC, Lauragra commented on api-reference/beta/resources/serviceannouncement.md
> +|Property|Type|Description|Contained Navigation Property|Nullable|ReadOnly|
The Contained Navigation Property, Nullable, and ReadOnly columns here are non-standard. Please move that information into the Description. Also property descriptions typically do not start with an imperative verb; they should be noun phrases.

2021-06-14 23:53 UTC, Lauragra commented on api-reference/beta/resources/serviceannouncement.md
> +This resource type doesn't have properties.
It's sufficient just to put "None." here.

2021-06-14 23:58 UTC, Lauragra commented on api-reference/beta/resources/servicehealth.md
> +Represent the health information of a service.
Change Represent to Represents.

2021-06-14 23:58 UTC, Lauragra commented on api-reference/beta/resources/serviceannouncement.md
> +A top level container for service communications resources.
Hyphenate top-level.

2021-06-15 00:03 UTC, Lauragra commented on api-reference/beta/resources/servicehealth.md
> +|issues|Collection([serviceHealthIssue](../resources/servicehealthissue.md))|Show a collection is issues happened on the service, with detailed information for each issue.|
The nav property description should be a noun phrase, not a verb phrase (unclear what the subject of the verb Show is). Also there seems to be a typo in the description.

2021-06-15 00:04 UTC, Lauragra commented on api-reference/beta/resources/servicehealthissue.md
> +Represent a [service health issue](../resources/servicehealthissue.md) in a service.
Change Represent to Represents. Also remove the link as it is a link to the current topic.

2021-06-15 00:05 UTC, Lauragra commented on api-reference/beta/resources/servicehealthissue.md
> +The service health issue could be a service incident or service advisory. For example:
Change "could" to "can"; simpler verb forms are easier for global readers to understand.

2021-06-15 00:06 UTC, Lauragra commented on api-reference/beta/resources/servicehealthissue.md
> +|[Get serviceHealthIssue](../api/servicehealthissue-get.md)|[serviceHealthIssue](../resources/servicehealthissue.md)|Retrieve the properties and relationships of a [serviceHealthIssue](../resources/s
In the descriptions, the first sentence should be sufficient; the additional detail is provided in the method topics.

2021-06-15 00:11 UTC, Lauragra commented on api-reference/beta/resources/servicehealthissuepost.md
> +This complex type represents a historical post in a service health issue.
It's sufficient to start the description with the verb "Represents".

2021-06-15 00:11 UTC, Lauragra commented on api-reference/beta/resources/servicehealthissuepost.md
> +|createdDateTime|DateTimeOffset|The published time of the post|
Make sure that the descriptions end with a period.

2021-06-15 00:13 UTC, Lauragra commented on api-reference/beta/resources/serviceupdatemessage.md
> +Represent the announcements of changes in a service.
Change Represent to Represents. Suggested revision for clarity: "Represents announcements about changes to a service."

2021-06-15 00:14 UTC, Lauragra commented on api-reference/beta/resources/serviceupdatemessage.md
> +This resource type serves to important publications such as major updates in a product. For example, the publication of a new Windows feature.
The phrase "serves to" does not seem clear; please clarify.

2021-06-15 00:16 UTC, Lauragra commented on api-reference/beta/resources/serviceupdatemessageviewpoint.md
> +Represent user view points data for a [serviceUpdateMessage](../resources/serviceupdatemessage.md).
Change Represent to Represents.

2021-06-15 00:24 UTC, Lauragra commented on api-reference/beta/toc.yml
> +      - name: Health overviews
We need to surface the resource topics in the TOC. We shouldn't have TOC entries for navigation properties. Please update the TOC structure to surface the following resources with the associated methods as child topics:
Service health
Service health issue
Service update message

2021-06-15 00:27 UTC, Lauragra commented on api-reference/beta/toc.yml
> +    - name: Service communications (preview)
If we decide that this will be a top-level node in the TOC rather than grouped with other sets of APIs, this should be in alphabetical order rather than at the end after "Workbooks and charts". We should move it to follow Security.

2021-06-15 00:28 UTC, Lauragra commented on changelog/Microsoft.M365ServiceCommsPlatform.json
> +          "ChangeList":[
Remove this ChangeList item - it does not appear to be related.

2021-06-15 00:40 UTC, opbld32 commented
Docs Build status updates of commit _[cf51f96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf51f969c6eab6d130c4bbf7ecb679e2b2012b9e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-8a49edbb)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-8a49edbb)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-8a49edbb)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-8a49edbb)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-8a49edbb)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-8a49edbb)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-8a49edbb)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-8a49edbb)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-8a49edbb)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-8a49edbb)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-8a49edbb)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-8a49edbb)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-8a49edbb)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-8a49edbb)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-8a49edbb)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-8a49edbb)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-8a49edbb)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-15 01:14 UTC, Lauragra commented on concepts/service-communications-concept-overview.md
> +The Microsoft Service Communications API provides access to Service Health and Message Center posts for your tenant.
Unless Service Communications is an official trademarked product name, this reference should likely be "Microsoft Graph service communications API". Also not sure that Service Health and Message Center should be treated as proper nouns.

2021-06-15 01:16 UTC, Lauragra commented on concepts/service-communications-concept-overview.md
> +### Get Service Health and Message Center posts for your tenant
This heading and the sentence that follows basically repeats the introductory sentence to this article. It might be helpful to enhance your introduction to explain what the Office 365 (or Microsoft 365) Service Communications product/service is or does, and then describe the scenarios that the APIs in Microsoft Graph enable.

2021-06-15 01:22 UTC, Lauragra commented on concepts/service-communications-concept-overview.md
> +* Integrate active Service Health issues directly into custom applications, to triager and share with the impacted audiences.
Please revise so we don't just have two bullets here with no introduction. These bullets can probably just be sentences: "You can use the service communications API to integrate active service health issues directly into custom applications, to triage and share with the affected audiences. You can also enable custom workflows for reviewing, assigning, and triaging change communications through the message center."

2021-06-15 01:56 UTC, Lauragra commented on concepts/service-communications-concept-overview.md
> +| Update service message status for login user | Update status operations can be found [here](/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&preserve-view=true)|
Change "for login user" to "for the signed in user". Revise the description to "For a list of status operations, see [serviceUpdateMessage](/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&preserve-view=true)."

2021-06-15 01:56 UTC, Lauragra commented on concepts/toc.yml
> +      - name: Service communications
Add (preview) to the TOC entry.

2021-06-15 01:57 UTC, Lauragra commented on concepts/service-communications-concept-overview.md
> +- Get started with Service Communications in Microsoft Graph by learning more about [Service Communications API](/graph/api/resources/serviceannouncement?view=graph-rest-beta&preserve-view=true).
Revise/simplify the text here "Learn more about the [service communications API](/graph/api/resources/serviceannouncement?view=graph-rest-beta&preserve-view=true)."

2021-06-15 01:58 UTC, Lauragra commented on concepts/service-communications-concept-overview.md
> +- Select and try service communications sample queries in [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer/?request=admin%2FserviceAnnouncement%2FhealthOverviews&version=beta).
Simplify this by having just one verb, "Try...".

2021-06-15 04:48 UTC, opbld33 commented
Docs Build status updates of commit _[fdcebae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdcebae26f19b0c889b39d0ff7564feb46ceb044)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-747b85a5)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-747b85a5)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-747b85a5)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-747b85a5)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-747b85a5)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-747b85a5)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-747b85a5)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-747b85a5)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-747b85a5)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-747b85a5)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-747b85a5)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-747b85a5)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-747b85a5)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-747b85a5)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-747b85a5)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-747b85a5)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-747b85a5)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-16 03:43 UTC, opbld34 commented
Docs Build status updates of commit _[1f6e657](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f6e6575ead03dd3588ae70cd818ce9cdd6ed482)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-6d7fcf05)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-6d7fcf05)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-6d7fcf05)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-6d7fcf05)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-6d7fcf05)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-6d7fcf05)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-6d7fcf05)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-6d7fcf05)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-6d7fcf05)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-6d7fcf05)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-6d7fcf05)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-6d7fcf05)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-6d7fcf05)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-6d7fcf05)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-6d7fcf05)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-6d7fcf05)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-6d7fcf05)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-16 04:33 UTC, opbld33 commented
Docs Build status updates of commit _[8d56025](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d5602523526146c829db54a49cf302d74891a4d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-ee233ce0)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-ee233ce0)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-ee233ce0)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-ee233ce0)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-ee233ce0)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-ee233ce0)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-ee233ce0)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-ee233ce0)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-ee233ce0)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-ee233ce0)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-ee233ce0)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-ee233ce0)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-ee233ce0)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-ee233ce0)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-ee233ce0)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-ee233ce0)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-ee233ce0)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-16 05:11 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +      href: resources/serviceannouncement.md
Line 13072:
@payiAzure , FYI I am moving this link (href line) further down, below line 13073, so that we can give a more appropriate TOC label for the serviceAnnouncement entity topic. The way you have it right now has "Service health and communications (preview)" as the TOC label, and that creates a surprise when customers click that node and see a topic title "serviceAnnouncement resource type".
@Lauragra has probably commented for you that you actually need an API overview topic to set expectations for developers what's in your API set and the use cases for those resources and methods. I understand the serviceAnnouncement methods capture part of the functionality, but that topic doesn't include the use cases that are supported by the serviceUpdateMessage methods. So please follow up on the API overview.

2021-06-16 05:19 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Get post-incident review report
Lines 13084-13087:
FYI I am reversing the order of "list" and "get" operations. There is a convention in Graph docs that we order CRUD topics this way: list, create, get, update, delete, where supported.
Refer to this topic for more info: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title

2021-06-16 05:23 UTC, opbld30 commented
Docs Build status updates of commit _[b83dfab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b83dfabd2765f2c1e9ffb8c530ede461454cc257)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-79ffac45)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-79ffac45)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-79ffac45)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-79ffac45)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-79ffac45)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-79ffac45)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-79ffac45)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-79ffac45)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-79ffac45)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-79ffac45)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-79ffac45)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-79ffac45)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-79ffac45)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-79ffac45)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-79ffac45)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-79ffac45)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-79ffac45)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-16 08:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/servicehealthissue.md
> +title: "serviceHealthIssue resource type"
@payiAzure , please document the base type serviceAnnouncementBase, and add a sentence after line 21 (the last thing before the first H2 section "Methods" in the topic) to mention it inherits from that base type, with a link to the base type topic.

This comment applies to the topic for the other derived type serviceUpdateMessage as well.

2021-06-17 20:22 UTC, opbld33 commented
Docs Build status updates of commit _[ab98430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab984308ff5fca5eaf469cd5a91152b9555fc54d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-533c463b)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-533c463b)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-533c463b)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-533c463b)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-533c463b)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-533c463b)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-533c463b)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-533c463b)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-533c463b)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-533c463b)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-533c463b)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-533c463b)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-533c463b)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-533c463b)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-533c463b)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-533c463b)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-533c463b)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-18 01:41 UTC, angelgolfer-ms commented on api-reference/beta/resources/serviceupdatemessage.md
> +
Please see the comment in servicehealthissue.md about exposing the base type microsoft.graph.serviceAnnouncementBase.

2021-06-18 07:35 UTC, angelgolfer-ms commented on concepts/service-communications-concept-overview.md
> +# Service Communications API overview
Line 10 (topic title):
@payiAzure , since we decided on using "Service health and communications" as the TOC title, it's important that the topic title correlates with the TOC title, and upon clicking the TOC label, customers don't doubt something is amiss or out of sync in the topic title. Because the topic title mentions 2 things - health and communications - and "Service communications API overview" mentions only communications, I think we need to use a topic title that transitions better.
We typically include the terms "overview" and "API" in the topic title for SEO, but in this case, I would prioritize the customer experience I just described over consistency with other overview topics. I think including the term "service communications" in the topic title, and the actual API name "service communications API" in the first paragraph is ok, without impacting SEO.

For these reasons, I am changing the topic title to "Overview for accessing service health and communications in Microsoft Graph".

2021-06-18 07:40 UTC, angelgolfer-ms commented on concepts/service-communications-concept-overview.md
> +### Get Service Health and Message Center posts for your tenant
@payiAzure , I feel the same as @Lauragra . 
FYI I am using the first sentence to make the connection from the topic title "Overview for accessing service health and communications in Microsoft Graph" to the actual set of API "service communications API".

I also attempt to identify those cloud services that your API supports. Taken from the api.md file: 
"Currently, the Office 365 Service Comms API contains data for Office 365, Yammer, Dynamics CRM and Microsoft Intune cloud services."
FYI I added the sentence to the first paragraph:
"Currently, the API supports data for Office client apps in Microsoft 365, Dynamics 365 for CRM, and Microsoft Intune."

**Please make sure you update that sentence is it's not correct.**

2021-06-18 07:55 UTC, angelgolfer-ms commented on concepts/service-communications-concept-overview.md
> +
Lines 13-20:
@payiAzure , if you take a look at the topic about [conceptual topics](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103154/Conceptual-topics), there's a difference in perspective and the level of depth going into the actual APIs, between the service-level conceptual overview (which is this topic for your workload), and the API overview (which is currently missing for your workload).

This service-level conceptual overview is about the value proposition of your service, to convince customers what they could do with the data your service provides. It's more about high level scenarios. It's not about which APIs to use to get what data; that's lower level content appropriate for the API overview.

FYI to help you achieve this guideline, and in the interest of time, I reorganized and rewrote your original content to fit into that conceptual overview and API overview framework.

Lines 25-36 actually already form a major section in the API overview. When you create the API overview, retitle line 25 as "Common use cases" and drop the API name from the section title.

2021-06-18 08:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/enums.md
> +
@payiAzure , can you please apply camel case to the enum values that you added, to be consistent with the CSDL and with the majority of the Microsoft Graph API enums?

2021-06-18 08:22 UTC, angelgolfer-ms commented on api-reference/beta/resources/enums.md
> +
The last comment also applies to the resource topics in this PR where you list enum values. Please also make sure they use camel case. I will not be commenting on those instances individually.

2021-06-18 08:26 UTC, opbld34 commented
Docs Build status updates of commit _[be5de3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be5de3a36e74184ee6cd1cdf3ff5f69f284ac55a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-985b0825)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-985b0825)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-985b0825)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-985b0825)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-985b0825)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-985b0825)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-985b0825)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-985b0825)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-985b0825)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-985b0825)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-985b0825)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-985b0825)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-985b0825)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-985b0825)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-985b0825)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-985b0825)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-440eaf15e7c772e71d6a6bfcd1db6fdb-985b0825)
[api-reference/beta/resources/serviceupdatemessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceupdatemessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceupdatemessage?view=graph-rest-beta&branch=pr-en-u [...]

2021-06-21 18:40 UTC, opbld30 commented
Docs Build status updates of commit _[13ac7c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13ac7c328d6f72660df2a4112a7128ca3b74779d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-abd0080e)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-abd0080e)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-abd0080e)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-abd0080e)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-abd0080e)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-abd0080e)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-abd0080e)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-abd0080e)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-abd0080e)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-abd0080e)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-abd0080e)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-abd0080e)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-abd0080e)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-abd0080e)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-abd0080e)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-f2bc9c1a739629b23b8c687926fe59bc-abd0080e)
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7975589eeffce1d894a21056e9a0d3db-abd0080e)
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissuepost.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissuepost?view=graph-rest-beta&branc [...]

2021-06-21 20:47 UTC, angelgolfer-ms commented on api-reference/beta/resources/serviceannouncement.md
> +None.
Hm, actually, by default, the stub topic generator includes any list and create operations that an entity with navigation properties supports. In this case, the main purpose of serviceAnnouncement is, as the description says, a top-level container for the resources of the API set, so it's also helpful to point out the from the serviceAnnouncement resource, one can use these list operations to get to the other main resources of the API.

Based on the api.md file, the list operations of serviceHealth, serviceHealthIssue, and serviceUpdateMessage are supported. So @payiAzure , please add the list operations back. Sorry for the confusion.

2021-06-22 06:51 UTC, opbld30 commented
Docs Build status updates of commit _[8f7eb31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f7eb3147a543f0e7470fa32771652f8207afa13)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7b9095fb)

<a id="7b9095fb"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220649398312-12722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xwu05ODX0BdSFN95UKNMnqJ%2FigC48kbjuaR3hZiOxZ4%3D&st=2021-06-22T06%3A46%3A02Z&se=2021-07-23T06%3A51%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 19:16 UTC, opbld34 commented
Docs Build status updates of commit _[1530b97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1530b978364169d5f3d60207584e0f3c053fa830)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-78432edc)

<a id="78432edc"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106221915275618-12722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0jXoCQNAv%2ByzXHUE%2Bu5ODg7289GMbmmhUsKTVuH08DM%3D&st=2021-06-22T19%3A11%3A49Z&se=2021-07-23T19%3A16%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 20:07 UTC, opbld34 commented
Docs Build status updates of commit _[8a36015](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a36015d7c6bc77e8d4c57f0b8ca76e9fc787cd5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2c31c822)

<a id="2c31c822"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106222006516286-12722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WkWlwKwuTa5bTQiZOGPD3bwwGnIQmWSIc67ICRAO6fU%3D&st=2021-06-22T20%3A02%3A06Z&se=2021-07-23T20%3A07%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 20:11 UTC, opbld30 commented
Docs Build status updates of commit _[5ed3219](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ed321941076cbb70221d675b116bc0e86cdfd84)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ee5e60600a41c1483732e5180d5c9e66-e99562bc)
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-4fa982075d17508babfe12c46b027515-e99562bc)
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5571d77fee9c82a238af0e7d0e0a94e7-e99562bc)
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a199b1b37e3e179b6484a15622624b7c-e99562bc)
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-dc6b2db8d87fe8723bee408308a137e1-e99562bc)
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-240f49dde9f0817e98a010ac8b27415d-e99562bc)
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-74a336360fc5ec3c6c88fb75bdd68621-e99562bc)
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-5cfc84a186a3d5704fddd7ae196e3e6d-e99562bc)
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e31555adbfe773946826479126211fb0-e99562bc)
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-7e14c0d419bfd71f7f7a5ea4c4a85c51-e99562bc)
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-0bfd1a38bf9c9bf41bdaabbcac444b29-e99562bc)
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-ea3cae2edda34d093b9ef630755d08db-e99562bc)
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-fde9b1253be13aa031756589bab47469-e99562bc)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-e99562bc)
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-789344de8d68b5fb9e3935d038db437b-e99562bc)
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-e93e72b5f891d847c53d395d08fdad62-e99562bc)
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-d7a3fd5b33e59e2f985cf7e393c634e9-e99562bc)
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?vi [...]

2021-06-22 20:19 UTC, opbld32 commented
Docs Build status updates of commit _[e293e53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e293e535d34d919e1d52a6639858e32059dae894)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-3a5ba579)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-22 21:19 UTC, opbld34 commented
Docs Build status updates of commit _[f5dfcfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5dfcfd6a96b138363743f261441730f57dd7808)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-511df527)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-23 02:04 UTC, opbld32 commented
Docs Build status updates of commit _[a1919ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1919ef77b2b6f842703f8a3c0c95cee3f030cbf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-5a0170b6)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-23 02:09 UTC, angelgolfer-ms commented on concepts/service-communications-concept-overview.md
> +
FYI I pulled this out and list it as one of the value propositions.
Then I showed examples of dashboards in the admin center, in a separate H2 section, outside of the list of value propositions.

2021-06-23 02:15 UTC, angelgolfer-ms commented on concepts/service-communications-concept-overview.md
> +
In the last build of this topic, I found because the screen shots each had titles that were displayed in a font and color very similar to the section titles in the topic, at a glance all the text content and the content of each screen shot blended together to form a very long topic (which beats the purpose of inserting images to break up the wall of text).

So I tried to make it visually clearer that this section is just 3 examples, each example showing a screen shot with a gray border (differentiated from the text content). 

Also, in each screen shot (that has a lot of UI text), I marked the corresponding data with a blue box, to help customers identify where the data is.
Lines 32-34:
FYI I called this list of 3 examples in a bullet list

2021-06-23 02:19 UTC, angelgolfer-ms commented on concepts/service-communications-concept-overview.md
> +
Forgot to mention - I decided not to show the screen shot for the admin center that shows the Health section UI. 
The simple instructions to get to the dashboards are sufficient; that screen shot is only supportive in nature, to get to the dashboards. That can make the topic a little shorter, just focusing what the API can do, and one less screen shot to go out of date later on to maintain :-)

2021-06-23 02:21 UTC, angelgolfer-ms commented on concepts/service-communications-concept-overview.md
> +
If you agree that's a better idea, then please delete the file service-communications-concept-overview-admin-center-dashboards.png from the repo.

2021-06-23 04:12 UTC, opbld33 commented
Docs Build status updates of commit _[a256382](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a256382bdaa2363fbe8698a48eb04f89c7a7968a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-3e10fe55)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-23 04:15 UTC, opbld32 commented
Docs Build status updates of commit _[1209091](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12090918275d70a195736f96b2d0ab38f656a103)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-1c44338d)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-23 04:18 UTC, opbld30 commented
Docs Build status updates of commit _[3ab1af2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ab1af213ee1624efbbb8c53ee928c7b201df6c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-0358d982)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-23 04:24 UTC, opbld33 commented
Docs Build status updates of commit _[cd1bd74](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd1bd7425fa0c50c9da86ae0ce6c1e838a5fcde0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-9051c5af)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-23 04:30 UTC, angelgolfer-ms approved these changes
@payiAzure , I tightened the two overview topics in the PR, please take a look at them and if the staged topics of the PR look good to you too, please follow the workflow and set the PR to ready to merge.

2021-06-23 17:31 UTC, opbld30 commented
Docs Build status updates of commit _[73db138](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73db1384e6d288cded59ec34ebcb575ebbd5c5c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-ffce4846)
[api-reference/beta/api/serviceannouncement-list-healthoverviews.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-healthoverviews.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-healthoverviews?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-issues?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceannouncement-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceannouncement-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceannouncement-list-messages?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealth-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealth-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealth-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/servicehealthissue-incidentreport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/servicehealthissue-incidentreport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/servicehealthissue-incidentreport?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-archive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-archive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-favorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-favorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-favorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-get?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-markunread.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-markunread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-markunread?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unarchive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unarchive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unarchive?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/api/serviceupdatemessage-unfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/api/serviceupdatemessage-unfavorite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceupdatemessage-unfavorite?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/service-communications-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncement?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/serviceannouncementbase.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/serviceannouncementbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceannouncementbase?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealth.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealth?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiAzure-SCPGraphDocs/api-reference/beta/resources/servicehealthissue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta&branch=pr-en-us-12722) (graph-rest-beta) |
[api-reference/beta/resources/servicehealthissuepost.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/payiA [...]

2021-06-24 01:09 UTC, merged