Docs for new recipient types in the Teams Activity Feed API
microsoftgraph/microsoft-graph-docs pull request #12720
Opened 2021-05-13 18:34 UTC by eddie-lee-msft

Docs for new recipient types in the Teams Activity Feed API.

2021-05-13 18:35 UTC, opbld33 commented
Docs Build status updates of commit _[e08e62b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e08e62b43176755e6b700fb2423b68337be40790)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105131834123477-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=apay308jAz5MXpaO1D30Mbr9MZfkO5Nc9vf5KF7Irls%3D&st=2021-05-13T18%3A30%3A27Z&se=2021-06-13T18%3A35%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-13 20:23 UTC, opbld31 commented
Docs Build status updates of commit _[3f5d5ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f5d5ee3c8aff52b642d5ad7402a927bfd15c3f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105132022270204-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mc6FYVpoHAhxABgV34Rh35ibIaYmQqx7gdMNdkAWxqI%3D&st=2021-05-13T20%3A18%3A41Z&se=2021-06-13T20%3A23%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 09:39 UTC, RamjotSingh requested changes
You should also update the concept doc with new examples.

2021-05-18 18:24 UTC, opbld31 commented
Docs Build status updates of commit _[d9d2660](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9d266078f8bc61527726b858b1f8294e829fd30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105181823416272-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rhy1KDVLyxCgZmjT%2B2ZMdKmAoKvmMTzCcyYQcpIZ7PE%3D&st=2021-05-18T18%3A19%3A53Z&se=2021-06-18T18%3A24%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 21:55 UTC, RamjotSingh approved these changes
Update api/resources/teamworknotificationrecipient as well add reference to new types there.

2021-05-19 23:35 UTC, opbld34 commented
Docs Build status updates of commit _[40eb63f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40eb63f10bfae6b51510828de1d4ab3553be4f68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105192334106023-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xzdvX2iHg33QywAeCpFm4zeSJWhlGmJ8g23l3RUKqEg%3D&st=2021-05-19T23%3A30%3A34Z&se=2021-06-19T23%3A35%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 21:31 UTC, JarbasHorst requested changes

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +### Example 4: Notify the members of a team about an event
Please, update for readability: `Notify the team members about...`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +This example shows how you can send an activity feed notification to all of the members of a team. This example notifies the team members about a new event.
Please, update for readability: `...feed notification to all team members.`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +> **Note:** The ability to send notifications to all of the members of a team is currently only available in beta.
Please, update for readability: `...to all team members is currently...`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +### Example 5: Notify the members of a channel about an event
Please, update for readability: `Notify the channel members about...`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +This example shows how you can send an activity feed notification to all of the members of a channel. This example notifies the channel members about a new event.
Please, update for readability: `...feed notification to all channel members.`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +> **Note:** The ability to send notifications to all of the members of a channel is currently only available in beta.
Please, update for readability: `...notifications to all of channel members...`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +        "webUrl": <Teams webUrl>
In JSON, strings should be wrapped in double quotes. Please, fix it: `<Teams webUrl>`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +        "webUrl": <Teams webUrl>
In JSON, strings should be wrapped in double quotes. Please, fix it: `<Teams webUrl>`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +        "webUrl": <Teams webUrl>
In JSON, strings should be wrapped in double quotes. Please, fix it: `<Teams webUrl>`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +### Example 6: Notify the members of a chat about an event
Please, update for readability: `Notify the chat members about...`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +This example shows how you can send an activity feed notification to all of the members of a chat. This example notifies the chat members about a new event.
Please, update for readability: `...feed notification to all chat members.`

2021-06-07 21:31 UTC, JarbasHorst commented on concepts/teams-send-activityfeednotifications.md
> +> **Note:** The ability to send notifications to all of the members of a chat is currently only available in beta.
Please, update for readability: `...notifications to all chat members is currently...`

2021-06-09 23:55 UTC, opbld34 commented
Docs Build status updates of commit _[5aa715a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5aa715afc403f868072b940f99c5dc2b4436f717)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-46ef5d9f)

<a id="46ef5d9f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106092355032795-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W2JW0cGex82HUnthOokbgoyc1US4EVlk2WvuQiUT8RU%3D&st=2021-06-09T23%3A50%3A28Z&se=2021-07-10T23%3A55%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 00:00 UTC, opbld34 commented
Docs Build status updates of commit _[eb70175](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb70175b09392461c6d0bba4c28033952b21d2bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106092359063232-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YkPNWXHDDppSzJ62hRQqwXPBz7fwEoFXaDEDk1ldf78%3D&st=2021-06-09T23%3A55%3A35Z&se=2021-07-11T00%3A00%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 00:04 UTC, opbld32 commented
Docs Build status updates of commit _[9d08937](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d089375126d1be3568347828cb2f5a0de8b7663)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100003135157-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2C%2BpapDA5yffAWgzmvg%2F%2FXl%2Fvsd7oEzdELTgFov3%2BpI%3D&st=2021-06-09T23%3A59%3A36Z&se=2021-07-11T00%3A04%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 19:11 UTC, JarbasHorst commented
@Lauragra this PR is ready for the final review.

2021-06-14 20:25 UTC, Lauragra commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Id": "48f75989-6c06-11eb-83a5-b441f1c9dab6",
Instead of adding these items to an existing ChangeList entry that was published earlier, please create a new ChangeList entry for these changes, with a different unique ID and publish date.

2021-06-14 20:27 UTC, opbld33 commented
Docs Build status updates of commit _[33471fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33471fa693a26b671a1d988d52f99d064d0466b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142026065088-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Az4Q7S%2BEJ00CpQg2Z3uJ5SHEADGv85PJPGGT2%2Bmpd4s%3D&st=2021-06-14T20%3A22%3A48Z&se=2021-07-15T20%3A27%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 20:40 UTC, opbld31 commented
Docs Build status updates of commit _[394c6cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/394c6cb0c946becc2e47470adb5876b5ec0a6ddf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142038505337-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iiiLW9%2B2TkeBLrcqwAK4XkvByOeYc8v7A5EXRg5Gojc%3D&st=2021-06-14T20%3A35%3A16Z&se=2021-07-15T20%3A40%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 20:47 UTC, opbld31 commented
Docs Build status updates of commit _[5111c4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5111c4cd4dd44ccab206431f02b2ab919fa97b70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142046201620-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hhhniytf3ALDkQfRP9cixY1oo%2B5JtDBjz4BYYQR7MjY%3D&st=2021-06-14T20%3A42%3A49Z&se=2021-07-15T20%3A47%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 20:58 UTC, opbld31 commented
Docs Build status updates of commit _[6a6d5fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a6d5fa966365f14b03ad2abc1a38e933e8a9c49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelMembersNotificationRecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelMembersNotificationRecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142056239626-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EE%2FvyA4ZlMvXx1P8xJJRmT80e9RlUD8VOriwE9SvJPE%3D&st=2021-06-14T20%3A53%3A36Z&se=2021-07-15T20%3A58%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 21:00 UTC, opbld33 commented
Docs Build status updates of commit _[8886e85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8886e85438af59b8a486ff09268ae399024eee71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142057278922-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NgR1hdD6%2BoZvIjppBBZOPC8qJ9sVLcaTTUumWY3BzSQ%3D&st=2021-06-14T20%3A55%3A07Z&se=2021-07-15T21%3A00%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-25 19:55 UTC, eddie-lee-msft commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Id": "48f75989-6c06-11eb-83a5-b441f1c9dab6",
Done.

2021-06-25 19:57 UTC, opbld34 commented
Docs Build status updates of commit _[2d93005](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d93005880e431e0d88a377fd9b96d17ba4c7706)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106251954424751-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q19yHoIDmkINBJleVxFIPiF1ob%2FPR7gc06yixcOEtRk%3D&st=2021-06-25T19%3A52%3A03Z&se=2021-07-26T19%3A57%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-25 20:02 UTC, opbld33 commented
Docs Build status updates of commit _[b35da67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b35da67e23e23f8cb9d1bdea1e21bb2c008d2eed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106252000268820-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=63zUZLto1hMvxHabVKzGRvlcQn%2FSkB0QwUDPi73PeaU%3D&st=2021-06-25T19%3A57%3A09Z&se=2021-07-26T20%3A02%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-26 00:57 UTC, Lauragra approved these changes

2021-06-26 01:37 UTC, opbld30 commented
Docs Build status updates of commit _[547e1db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/547e1dbdcbe33f0c61518f13860269fe152a2d0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106260135568850-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=elpx2137e7BaFOsfYQCFCJ14zFKYtCRJdR8gV6xi8IA%3D&st=2021-06-26T01%3A32%3A23Z&se=2021-07-27T01%3A37%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-26 01:39 UTC, opbld31 commented
Docs Build status updates of commit _[547e1db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/547e1dbdcbe33f0c61518f13860269fe152a2d0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106260136075381-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KsAn2g2e7I2aarLw9ONJwehqiUJezr9mfV%2FyywoKRCk%3D&st=2021-06-26T01%3A34%3A10Z&se=2021-07-27T01%3A39%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 01:12 UTC, opbld34 commented
Docs Build status updates of commit _[6bb345e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bb345eb7c3d72661b42b6c2acb853319bf67e3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106300111068011-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DAvZucOKX%2FlJmsNYtJ1hu7eTte%2BCxkXioepSffXWYpk%3D&st=2021-06-30T01%3A07%3A45Z&se=2021-07-31T01%3A12%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 01:14 UTC, opbld31 commented
Docs Build status updates of commit _[6bb345e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bb345eb7c3d72661b42b6c2acb853319bf67e3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/channelmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/channelmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channelmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/chatmembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/chatmembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teammembersnotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teammembersnotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teammembersnotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-12720) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edle/FeedsNewRecipientTypesDocs/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-12720) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106300111180732-12720%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uxGEG7fxdWMH5pFqdhqrPM23VkA%2BtQX7gS%2F%2Fc8Do7mM%3D&st=2021-06-30T01%3A09%3A13Z&se=2021-07-31T01%3A14%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 01:20 UTC, merged