change notification for team and channels crud
microsoftgraph/microsoft-graph-docs pull request #12740
Opened 2021-05-17 10:57 UTC by anandab-msft

Added doc for change notification for crud of team and channels

2021-05-17 10:58 UTC, opbld32 commented
Docs Build status updates of commit _[7e074d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e074d3ffb2b65146593ddaec048befc40b8989a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-1965849b)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-1965849b)
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) | [Details](#user-content-432224b71eeb2c00e54d5f21ae1ccd4e-1965849b)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-1965849b)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-1965849b)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="e8b2d78ce86acda2d3af67b160da3b31-1965849b"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md)
 - **Line 31, Column 190**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 64, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 31, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 64, Column 553**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' will be broken in isolated environments. Replace with a relative link.`````

<a id="833005bfa1a8f3ee3adca88f08780851-1965849b"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 12, Column 135**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 135**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 12, Column 135**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true. Otherwise, r [...]

2021-05-17 11:14 UTC, abshar-teams approved these changes

2021-05-18 16:51 UTC, RamjotSingh requested changes

2021-05-18 16:51 UTC, RamjotSingh commented on api-reference/beta/api/subscription-delete.md
> +|[channels](../resources/channel.md) (/teams/getAllChannels – all channels in an organization) | Channel.ReadBasic.All, ChannelSettings.Read.All  | Not supported | Channel.ReadBasic.All, ChannelSetti
Tenant wide should not supported in delegated context

2021-05-18 16:51 UTC, RamjotSingh commented on api-reference/beta/api/subscription-delete.md
> +|[channels](../resources/channel.md) (/teams/{id}/channels) | Channel.ReadBasic, ChannelSettings.Read  | Not supported | Channel.ReadBasic, ChannelSettings.Read  |
Fix application only permission strings here and below.

2021-05-18 16:51 UTC, RamjotSingh commented on api-reference/beta/api/subscription-get.md
> +|[channels](../resources/channel.md) (/teams/getAllChannels – all channels in an organization) | Channel.ReadBasic.All, ChannelSettings.Read.All  | Not supported | Channel.ReadBasic.All, ChannelSetti
Same fixes as other places here and other docs too.

2021-05-18 16:51 UTC, RamjotSingh commented on api-reference/beta/resources/webhooks.md
> +| Delegated - work or school account     | [alert][], [channel][],[contact][], [conversation][], [conversationMember][], [driveItem][], [list][], [event][], [group][], [message][], [user][], [presenc
Add links to resources here and above.

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/teams-changenotifications-team-and-channels.md
> +|Application | Channel.ReadBasic  ,ChannelSettings.Read   | beta |
2 notes

1. The permission strings for app context should be ending with .All check them
2. Add RSC permissions where supported.

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/toc.yml
>                - name: Get change notifications for chat and channel messages
This looks super odd that we have 3 pages next to each other basically talking about the exact same thing. So

1. Have a subheading and put all 3 pages under it
2. Pull out the common stuff (like working with teams change notifications, what to send, what to expect etc) and then add it to a central doc, see what you can collapse etc

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/webhooks.md
> +- Teams [channel][]
Links to resources.

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/webhooks.md
> +|[channel][] | 10-20 seconds | 60 minutes |
Links to resources.

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/webhooks.md
> +|[conversationMemeber][] | Less than 15 minutes | 60 minutes |
Spelling

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/webhooks.md
> +|[conversationMemeber][] | Less than 15 minutes | 60 minutes |
Why 15 mins?

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/webhooks.md
> +|[team][] | Less than 15 minutes | 60 minutes |
Why 15 mins?

2021-05-18 16:51 UTC, RamjotSingh commented on concepts/webhooks.md
> +[conversationMemeber]: /graph/api/resources/conversationmember
Fix typo at all places. Add links where it makes sense.

2021-05-18 18:28 UTC, anandab-msft commented on api-reference/beta/api/subscription-get.md
> +|[channels](../resources/channel.md) (/teams/getAllChannels – all channels in an organization) | Channel.ReadBasic.All, ChannelSettings.Read.All  | Not supported | Channel.ReadBasic.All, ChannelSetti
updated for post/get/update/delete files

2021-05-18 18:42 UTC, anandab-msft commented on concepts/webhooks.md
> +- Teams [channel][]
reference to channel is added in  line no 344

2021-05-19 07:21 UTC, opbld30 commented
Docs Build status updates of commit _[81cdfe0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81cdfe005d0f2526c93e57561ccbfc1a2bfcd350)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-793fed5e)
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) | [Details](#user-content-432224b71eeb2c00e54d5f21ae1ccd4e-793fed5e)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-793fed5e)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-793fed5e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="833005bfa1a8f3ee3adca88f08780851-793fed5e"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 12, Column 135**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 135**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 12, Column 135**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true. Otherwise, remove the view parameter.`````
 - **Line 178, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 178, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 178, Column 134**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 178, Column 134**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL [...]

2021-05-19 08:08 UTC, anandab-msft commented on api-reference/beta/resources/webhooks.md
> +| Delegated - work or school account     | [alert][], [channel][],[contact][], [conversation][], [conversationMember][], [driveItem][], [list][], [event][], [group][], [message][], [user][], [presenc
link reference in mentioned at bottom of this page, line no 67,68,81

2021-05-19 08:08 UTC, anandab-msft commented on concepts/webhooks.md
> +|[conversationMemeber][] | Less than 15 minutes | 60 minutes |
fixed

2021-05-19 08:14 UTC, opbld31 commented
Docs Build status updates of commit _[db76011](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db76011ca598a2e8d820d4e4bde54b67e61695e7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-1e0b1adc)
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) | [Details](#user-content-432224b71eeb2c00e54d5f21ae1ccd4e-1e0b1adc)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-1e0b1adc)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-1e0b1adc)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="833005bfa1a8f3ee3adca88f08780851-1e0b1adc"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 12, Column 135**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 135**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 12, Column 135**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true. Otherwise, remove the view parameter.`````
 - **Line 178, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 178, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 178, Column 134**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 178, Column 134**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL [...]

2021-05-23 12:32 UTC, opbld34 commented
Docs Build status updates of commit _[1373333](https://github.com/microsoftgraph/microsoft-graph-docs/commits/137333318652e4f9d9807ffa2fba88a888225c62)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) | [Details](#user-content-dc6a1e7db0cc3a246bef1d195992676c-8f8fced5)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-8f8fced5)
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) | [Details](#user-content-432224b71eeb2c00e54d5f21ae1ccd4e-8f8fced5)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) | [Details](#user-content-d6641161fd46c78dd4128bccd65500b6-8f8fced5)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-8f8fced5)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="dc6a1e7db0cc3a246bef1d195992676c-8f8fced5"></a>
### [concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md)
 - **Line 18, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'link'.`````
 - **Line 19, Column 140**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'link'.`````
 - **Line 21, Column 7**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'link'.`````
 - **Line 29, Column 39**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Link'.`````

<a id="833005bfa1a8f3ee3adca88f08780851-8f8fced5"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 12, Column 135**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 178, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 135**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 12, Column 135**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=preserve-view=true. Otherwise, remove the view parameter.`````
 - **Line 178, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https:// [...]

2021-05-23 14:05 UTC, opbld31 commented
Docs Build status updates of commit _[754f4b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/754f4b71c5e3b831d6628860020b874eb5166c1f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) | [Details](#user-content-dc6a1e7db0cc3a246bef1d195992676c-dec4d7db)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-dec4d7db)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-dec4d7db)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="dc6a1e7db0cc3a246bef1d195992676c-dec4d7db"></a>
### [concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md)
 - **Line 18, Column 130**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'link'.`````
 - **Line 19, Column 143**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'link'.`````

<a id="833005bfa1a8f3ee3adca88f08780851-dec4d7db"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 175, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 175, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 175, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 175, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 175, Column 134**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 175, Column 134**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you real [...]

2021-05-23 14:14 UTC, opbld31 commented
Docs Build status updates of commit _[d10b729](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d10b7294efa2a528065dc7623e1c897fa980caad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-5b6b5364)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-5b6b5364)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="833005bfa1a8f3ee3adca88f08780851-5b6b5364"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 175, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 175, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 175, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 175, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 175, Column 134**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 175, Column 134**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="5a4bf723696c90353d87e6f17ef663f5-5b6b5364"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonic [...]

2021-05-23 14:18 UTC, anandab-msft commented on concepts/toc.yml
>                - name: Get change notifications for chat and channel messages
@RamjotSingh - made some changes, pls review

2021-05-24 07:37 UTC, abshar-teams commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[channels](../resources/channel.md) (/teams/{id}/channels) | Channel.ReadBasic, ChannelSettings.Read  | Not supported | Channel.ReadBasic.All, ChannelSettings.Read.All  |
individual resources doesn't require .All permissions

2021-05-24 07:41 UTC, abshar-teams commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Change notifications enable you to subscribe to changes (create, update, and delete) to a resource, change notifications provide a low latency model by allowing you to maintain a [subscription](/grap
Can we re-phrase the second line here ?

2021-05-24 07:42 UTC, abshar-teams commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +## Change notificaiton types
typo

2021-05-24 07:48 UTC, abshar-teams commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Notifications without resource data give you enough information to make GET calls to get the message content. Subscriptions for notifications without resource data do not require an encryption certif
remove 'message content'

2021-05-24 07:49 UTC, abshar-teams commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Above example shows notification corresponding to chat message resource, in actual notification resource and resource data filed will represent the resource which has trigerred the notification. The
typo-resource spelling (last word of sentence)

2021-05-24 07:52 UTC, abshar-teams commented on concepts/teams-changenotifications-team-and-channels.md
> +|Delegated (work or school account) | Not supported. | Not supported. |
specific team subscritions are supported in user-context

2021-05-24 07:53 UTC, abshar-teams commented on concepts/teams-changenotifications-team-and-channels.md
> +|Delegated (work or school account) | Not supported. | Not supported. |
same for others too, check the chat message one's doc

2021-05-24 07:58 UTC, abshar-teams commented on concepts/teams-changenotifications-team-and-channels.md
> +## Notification payloads
i dont feel, we need this and the below paragraphs anymore here, this has already been explained in the common section.
Can't we just mention the payload type and the excluded properties at the end of each section above ? or if required, can just paste a sample. The paragraphs 'Notifications with/without resource data' shouldn't be needed

2021-05-24 07:59 UTC, abshar-teams commented on concepts/teams-changenotifications-teamMembership.md
> +To get change notifications for membership change in any team in tenant, subscribe to `teams/{id}/members`. This resource supports [including resource data](webhooks-with-resource-data.md) in the not
just replace 'any team in tenant' with 'any team across the tenant' everywhere

2021-05-24 08:00 UTC, abshar-teams commented on concepts/teams-changenotifications-teamMembership.md
> +To get change notifications for membership change in any team in tenant, subscribe to `teams/{id}/members`. This resource supports [including resource data](webhooks-with-resource-data.md) in the not
For this section, we should add a note that tenant-wide changes are not supported for this

2021-05-24 08:00 UTC, abshar-teams commented on concepts/teams-changenotifications-teamMembership.md
> +|Delegated (work or school account) | Not supported. | Not supported. |
same, user context is supported in this too

2021-05-24 08:01 UTC, abshar-teams requested changes
Added Minor comments

2021-05-24 08:13 UTC, opbld31 commented
Docs Build status updates of commit _[92e2578](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92e25789be445e204796199039f4b7ad4ce09f08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) | [Details](#user-content-70c609bef49a002ed6cb898da617ba84-91aea1ae)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-91aea1ae)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-91aea1ae)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="70c609bef49a002ed6cb898da617ba84-91aea1ae"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 10, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Create subscription'.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 8, Column 1**: **[Suggestion-[heading-with-underline](https://review.docs.microsoft.com/help/contribute/validation-ref/html-link?branch=main)]** 
`````
Bad H2 'title: "Create subscription"
description: "Subscribes a listener application to receive change notifications when data on a Microsoft Graph resource changes."
localization_priority: Normal
author: "Jumaodhiss"
doc_type: apiPageType
ms.prod: "change-notifications"' format. Use hashes to create H1(#) or H2 (##)
`````

<a id="833005bfa1a8f3ee3adca88f08780851-91aea1ae"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 172, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 172, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-u [...]

2021-05-24 08:43 UTC, opbld33 commented
Docs Build status updates of commit _[e37590a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e37590a63e5e41959694d4eb6963d197318f5e4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) | [Details](#user-content-70c609bef49a002ed6cb898da617ba84-332e06dc)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-332e06dc)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-332e06dc)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="70c609bef49a002ed6cb898da617ba84-332e06dc"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 10, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Create subscription'.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 8, Column 1**: **[Suggestion-[heading-with-underline](https://review.docs.microsoft.com/help/contribute/validation-ref/html-link?branch=main)]** 
`````
Bad H2 'title: "Create subscription"
description: "Subscribes a listener application to receive change notifications when data on a Microsoft Graph resource changes."
localization_priority: Normal
author: "Jumaodhiss"
doc_type: apiPageType
ms.prod: "change-notifications"' format. Use hashes to create H1(#) or H2 (##)
`````

<a id="833005bfa1a8f3ee3adca88f08780851-332e06dc"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 172, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 172, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-u [...]

2021-05-25 10:56 UTC, RamjotSingh requested changes

2021-05-25 10:56 UTC, RamjotSingh commented on api-reference/beta/resources/webhooks.md
> +| Delegated - work or school account     | [alert][], [channel][],[contact][], [conversation][], [conversationMember][], [driveItem][], [list][], [event][], [group][], [message][], [user][], [presenc
Add here as well, whereever u mention the resource link it.

2021-05-25 10:56 UTC, RamjotSingh commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +The decrypted notification payload looks like the following. The payload conforms to the [chatMessage](/graph/api/resources/chatMessage?preserve-view=true) schema. The payload is similar to that retu
Fix the text to specify this is just an example for chatMessage resource and payload is dependent on the resource subscribed.

2021-05-25 10:56 UTC, RamjotSingh commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Notifications without resource data give you enough information to make GET calls to get the message. Subscriptions for notifications without resource data do not require an encryption certificate (b
calls to get the resource

2021-05-25 10:56 UTC, RamjotSingh commented on concepts/teams-changenotifications-team-and-channels.md
> +"allowAddRemoveApps": true,
Format Json properly.

2021-05-25 10:56 UTC, RamjotSingh commented on concepts/teams-changenotifications-team-and-channels.md
> +"moderationSettings": null
format Json

2021-05-25 10:56 UTC, RamjotSingh commented on concepts/teams-changenotifications-team-and-channels.md
> +"id": "19:a3f841d969cd4ae0a7cbe847fc10b371@thread.tacv2",
Format json

2021-05-25 10:56 UTC, RamjotSingh commented on concepts/toc.yml
> +                    href: change-notification-in-Microsoft-Teams-overview.md
use lowercase in file names.

2021-05-25 10:56 UTC, RamjotSingh commented on concepts/webhooks.md
> +- Teams [channel][]
Same here, link everywhere.

2021-05-25 12:29 UTC, opbld34 commented
Docs Build status updates of commit _[46c25cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46c25cc7462aa0ac62ca025bc57aea23ad941755)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) | [Details](#user-content-70c609bef49a002ed6cb898da617ba84-210f938f)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-210f938f)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-210f938f)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="70c609bef49a002ed6cb898da617ba84-210f938f"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 10, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Create subscription'.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 8, Column 1**: **[Suggestion-[heading-with-underline](https://review.docs.microsoft.com/help/contribute/validation-ref/html-link?branch=main)]** 
`````
Bad H2 'title: "Create subscription"
description: "Subscribes a listener application to receive change notifications when data on a Microsoft Graph resource changes."
localization_priority: Normal
author: "Jumaodhiss"
doc_type: apiPageType
ms.prod: "change-notifications"' format. Use hashes to create H1(#) or H2 (##)
`````

<a id="833005bfa1a8f3ee3adca88f08780851-210f938f"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 172, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 172, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-u [...]

2021-05-25 16:52 UTC, abshar-teams approved these changes

2021-05-25 18:36 UTC, opbld30 commented
Docs Build status updates of commit _[a964f05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a964f053298152e8fabb191906e3c36c3d60e278)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) | [Details](#user-content-70c609bef49a002ed6cb898da617ba84-c5cd61dd)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-c5cd61dd)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-c5cd61dd)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="70c609bef49a002ed6cb898da617ba84-c5cd61dd"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 10, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Create subscription'.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 8, Column 1**: **[Suggestion-[heading-with-underline](https://review.docs.microsoft.com/help/contribute/validation-ref/html-link?branch=main)]** 
`````
Bad H2 'title: "Create subscription"
description: "Subscribes a listener application to receive change notifications when data on a Microsoft Graph resource changes."
localization_priority: Normal
author: "Jumaodhiss"
doc_type: apiPageType
ms.prod: "change-notifications"' format. Use hashes to create H1(#) or H2 (##)
`````

<a id="833005bfa1a8f3ee3adca88f08780851-c5cd61dd"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 172, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 172, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-u [...]

2021-05-28 21:29 UTC, JarbasHorst requested changes

2021-05-28 21:29 UTC, JarbasHorst commented on api-reference/beta/api/subscription-delete.md
> +|[teams](../resources/team.md) (/teams – all teams in an organization) | Team.ReadBasic.All,TeamSettings.Read.All | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-28 21:29 UTC, JarbasHorst commented on api-reference/beta/api/subscription-delete.md
> +|[teams](../resources/team.md) (/teams/{id}) | Team.ReadBasic,TeamSettings.Read | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-28 21:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "55906116-5e73-4252-a6e9-49ced6556d7b",
Please, replace this ID with change list record's ID => 8575a784-e80a-4f96-a782-39b0f19fc24d

2021-05-28 21:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "300c4e34-43fd-435a-a3fd-ef744302cd65",
Please, replace this ID with change list record's ID => 8575a784-e80a-4f96-a782-39b0f19fc24d

2021-05-28 21:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "88b84275-63bb-48ef-97a2-5ce98b984bf1",
Please, replace this ID with change list record's ID => 8575a784-e80a-4f96-a782-39b0f19fc24d

2021-05-28 21:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/en-us/graph/api/resources/subscription) for change notifications to the [channel](https://docs.m
Please, remove `en-us` from the links you've added. Let docs.microsoft.com figure out the correct locale.

2021-05-28 21:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/en-us/graph/api/resources/subscription) for change notifications to the [team](https://docs.micr
Please, remove `en-us` from the links you've added. Let docs.microsoft.com figure out the correct locale.

2021-05-28 21:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/en-us/graph/api/resources/subscription) for change notifications to the [conversationMember](htt
Please, remove `en-us` from the links you've added. Let docs.microsoft.com figure out the correct locale.

2021-05-28 21:29 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes related to a resource across tenant** e.g. one can subscribe to change in messages in any channel across tenant and get notified whenever a message is cre
Avoid non-English words. Please, replace `e.g.` with `for example`

2021-05-28 21:29 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes for a specific respource**  e.g. one can subscribe to change in messages in a particular channel and get notified when ever a message is created in that c
Avoid non-English words. Please, replace `e.g.` with `for example`

2021-05-28 21:29 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes for a specific respource**  e.g. one can subscribe to change in messages in a particular channel and get notified when ever a message is created in that c
Please, fix typo

2021-05-28 21:29 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Above example shows notification corresponding to chat message resource, in actual notification resource and resource data filed will represent the resource which has trigerred the notification. The
Please, consider using here same format as before: **resource** and **resourceData**

2021-05-28 21:29 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channels.md
> +Notifications without resource data give you enough information to make GET calls to get the message content. Subscriptions for notifications without resource data do not require an encryption certif
Use common contractions. Please, replace `do not` with `don't`.

2021-05-28 21:29 UTC, JarbasHorst commented on concepts/teams-changenotifications-teamMembership.md
> +Notifications without resource data give you enough information to make GET calls to get the message content. Subscriptions for notifications without resource data do not require an encryption certif
Use common contractions. Please, replace `do not` with `don't`.

2021-05-28 21:29 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Notifications without resource data give you enough information to make GET calls to get the resource. Subscriptions for notifications without resource data do not require an encryption certificate (
Use common contractions. Please, replace `do not` with `don't`.

2021-05-29 06:32 UTC, opbld31 commented
Docs Build status updates of commit _[6106d23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6106d2321c62d3fc949b53af010b657154a6b759)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) | [Details](#user-content-70c609bef49a002ed6cb898da617ba84-f98d985c)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-f98d985c)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-f98d985c)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="70c609bef49a002ed6cb898da617ba84-f98d985c"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 10, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Create subscription'.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 8, Column 1**: **[Suggestion-[heading-with-underline](https://review.docs.microsoft.com/help/contribute/validation-ref/html-link?branch=main)]** 
`````
Bad H2 'title: "Create subscription"
description: "Subscribes a listener application to receive change notifications when data on a Microsoft Graph resource changes."
localization_priority: Normal
author: "Jumaodhiss"
doc_type: apiPageType
ms.prod: "change-notifications"' format. Use hashes to create H1(#) or H2 (##)
`````

<a id="833005bfa1a8f3ee3adca88f08780851-f98d985c"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 172, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 172, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-u [...]

2021-05-29 06:56 UTC, opbld32 commented
Docs Build status updates of commit _[2358c24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2358c2454ad01f7e7a3945c080d22a9f8d80e7be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) | [Details](#user-content-70c609bef49a002ed6cb898da617ba84-f93e1642)
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) | [Details](#user-content-833005bfa1a8f3ee3adca88f08780851-f93e1642)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-f93e1642)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="70c609bef49a002ed6cb898da617ba84-f93e1642"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 10, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Create subscription'.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 8, Column 1**: **[Suggestion-[heading-with-underline](https://review.docs.microsoft.com/help/contribute/validation-ref/html-link?branch=main)]** 
`````
Bad H2 'title: "Create subscription"
description: "Subscribes a listener application to receive change notifications when data on a Microsoft Graph resource changes."
localization_priority: Normal
author: "Jumaodhiss"
doc_type: apiPageType
ms.prod: "change-notifications"' format. Use hashes to create H1(#) or H2 (##)
`````

<a id="833005bfa1a8f3ee3adca88f08780851-f93e1642"></a>
### [concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md)
 - **Line 172, Column 12**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 134**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 172, Column 12**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 172, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-u [...]

2021-05-29 07:14 UTC, anandab-msft commented
@JarbasHorst  - made changes suggested by you, pls review/approve.

2021-05-31 19:51 UTC, JarbasHorst commented
Thanks @anandab-msft. Starting second iteration.

2021-05-31 21:19 UTC, JarbasHorst commented
@anandab-msft 

I noticed that these Graph permissions used in your articles don't exist in Azure. Is that a typo or are we releasing new Graph permissions? The list below also contains the permissions I found in Azure:

|Permissions used in your articles|Correct permissions?|
|---|---|
|Channel.ReadBasic|Channel.ReadBasic.All|
|ChannelSettings.Read|ChannelSettings.Read.All|
|TeamMember.Read|TeamMember.Read.All|
|Team.ReadBasic|Team.ReadBasic.All|
|TeamSettings.Read|TeamSettings.Read.All|

If that is a typo, please update following files with the correct permissions:
- subscription-get.md
- subscription-post-subscriptions.md
- subscription-update.md
- subscription-delete.md
- teams-changenotifications-team-and-channels.md
- teams-changenotifications-teamMembership.md

2021-05-31 21:56 UTC, JarbasHorst requested changes

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/api/subscription-get.md
> +|[teams](../resources/team.md) (/teams/{id}) | Team.ReadBasic,TeamSettings.Read | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic,TeamSettings.Read" and "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/api/subscription-get.md
> +|[teams](../resources/team.md) (/teams – all teams in an organization) | Team.ReadBasic.All,TeamSettings.Read.All | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/api/subscription-post-subscriptions.md
> +  ---
Please, remove additional space as it it breaks MD format

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[teams](../resources/team.md) (/teams/{id}) | Team.ReadBasic,TeamSettings.Read | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic,TeamSettings.Read" and "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[teams](../resources/team.md) (/teams – all teams in an organization) | Team.ReadBasic.All,TeamSettings.Read.All | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/api/subscription-update.md
> +|[teams](../resources/team.md) (/teams/{id}) | Team.ReadBasic,TeamSettings.Read | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic,TeamSettings.Read" and "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/api/subscription-update.md
> +|[teams](../resources/team.md) (/teams – all teams in an organization) | Team.ReadBasic.All,TeamSettings.Read.All | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |
Please, add space between the permissions "Team.ReadBasic.All,TeamSettings.Read.All" for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on api-reference/beta/resources/subscription.md
> +| Teams **channel**    | 60 minutes (1 hour)  |
Should this table "Maximum length of subscription per resource type" also have an entry for conversationMember?

2021-05-31 21:56 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/graph/api/resources/subscription) for change notifications to the [channel](https://docs.microso
Please, remove `en-us` from the link "https://docs.microsoft.com/en-us/graph/api/resources/channel". Let docs.microsoft.com figure out the correct locale.

2021-05-31 21:56 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/graph/api/resources/subscription) for change notifications to the [team](https://docs.microsoft.
Please, remove `en-us` from the link "https://docs.microsoft.com/en-us/graph/api/resources/team". Let docs.microsoft.com figure out the correct locale.

2021-05-31 21:56 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/graph/api/resources/subscription) for change notifications to the [conversationMember](https://d
Please, remove `en-us` from the link "https://docs.microsoft.com/en-us/graph/api/resources/conversationMember". Let docs.microsoft.com figure out the correct locale.

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes for a specific resource**,  for example one can subscribe to change in messages in a particular channel and get notified when ever a message is created in
Please, fix typo "when ever"

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Notifications without resource data gives you enough information to make GET calls to get the resource. Subscriptions for notifications without resource data don't require an encryption certificate (
Please, fix typo. Either use "notification gives" or "notifications give"

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channels.md
> +Notifications without resource data gives you enough information to make GET calls to get the message content. Subscriptions for notifications without resource data don't require an encryption certif
Please, fix typo. Either use "notification gives" or "notifications give"

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-teamMembership.md
> +Notifications without resource data gives you enough information to make GET calls to get the message content. Subscriptions for notifications without resource data don't require an encryption certif
Please, fix typo. Either use "notification gives" or "notifications give"

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/toc.yml
> +                  - name: Change notifications for team and channel
Should the name be "Change notifications for team and channel**s**" to align with href: teams-changenotifications-team-and-channel**s**.md

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channels.md
> +|Delegated (work or school account) | Not supported. | Not supported. |
In articles _subscription-get.md_, _subscription-post-subscriptions.md_, _subscription-update.md_, and _subscription-delete.md_ you mentioned that Delegated (work or school account) permissions are supported. What article(s) is/are wrong?

Copied from subscription-update.md:

`|[teams](../resources/team.md) (/teams – all teams in an organization) | Team.ReadBasic.All,TeamSettings.Read.All | Not supported | Team.ReadBasic.All,TeamSettings.Read.All |`

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channels.md
> +
Please, remove this empty line from JSON example for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channels.md
> +>**Note:** [discoverySettings](https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta)  and [classSettings](https://docs.microsoft.com/en-us/graph/api/resourc
Please, remove `en-us` from the links "https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta" and "https://docs.microsoft.com/en-us/graph/api/resources/teamclasssettings?view=graph-rest-beta" you've added. Let docs.microsoft.com figure out the correct locale.

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channels.md
> +>**Note:** [discoverySettings](https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta)  and [classSettings](https://docs.microsoft.com/en-us/graph/api/resourc
Please, replace all absolute links with relative links.

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channels.md
> +>**Note:** [discoverySettings](https://docs.microsoft.com/en-us/graph/api/resources/teamdiscoverysettings?view=graph-rest-beta)  and [classSettings](https://docs.microsoft.com/en-us/graph/api/resourc
Please, remove the view parameter from both URLs if you don't need to link to a specific version. If you really need to link to a specific version, add &preserve-view=true.

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-teamMembership.md
> +|Delegated (work or school account) | TeamMember.Read. | Not supported. |
Please, remove the dot after TeamMember.Read

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-teamMembership.md
> +
Please, remove this empty line from JSON example for consistency.

2021-05-31 21:56 UTC, JarbasHorst commented on concepts/teams-changenotifications-teamMembership.md
> +
Please, remove this empty line from JSON example for consistency.

2021-06-01 06:02 UTC, opbld33 commented
Docs Build status updates of commit _[3243d77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3243d77d07c464cda170b023842f36aa680d5b24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-71644fd9)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channels?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-71644fd9"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean  [...]

2021-06-01 06:08 UTC, anandab-msft commented on api-reference/beta/resources/subscription.md
> +| Teams **channel**    | 60 minutes (1 hour)  |
added

2021-06-01 06:12 UTC, anandab-msft commented on concepts/teams-changenotifications-team-and-channels.md
> +|Delegated (work or school account) | Not supported. | Not supported. |
delegated is supported for team specific (/teams/id) but not for all teams (/teams). Made changes to reflect same in all pages.

2021-06-01 06:19 UTC, anandab-msft commented on concepts/toc.yml
> +                  - name: Change notifications for team and channel
i would prefer `team and channel`  ,renaming the file accordingly.

2021-06-01 07:08 UTC, opbld32 commented
Docs Build status updates of commit _[25adc2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25adc2e136017340276fe022dee8a2195d7395d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-93836c8d)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-93836c8d"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-01 09:29 UTC, anandab-msft commented
@JarbasHorst  - made changes all per your suggestions.

2021-06-01 22:06 UTC, JarbasHorst requested changes

2021-06-01 22:06 UTC, JarbasHorst commented on api-reference/beta/resources/webhooks.md
> +| Teams [channel][] | Changes to channel in all channels in all teams:<br>`/teams/getAllChannels` <br>Changes to channel in a specific team:<br>`/teams/{id}/channels` | Yes |
Suggestion:
Replace `Changes to channel in all channels...` with `Changes in all channels...`. 
"Changes in all channels..." sounds more logical.

2021-06-02 05:49 UTC, anandab-msft commented on api-reference/beta/resources/webhooks.md
> +| Teams [channel][] | Changes to channel in all channels in all teams:<br>`/teams/getAllChannels` <br>Changes to channel in a specific team:<br>`/teams/{id}/channels` | Yes |
change to `Changes in channels in all teams` to make it more consistent with other messages.

2021-06-02 06:05 UTC, opbld33 commented
Docs Build status updates of commit _[2565985](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2565985e1ff332a47d48333635f174c47d8007df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-e1c3f812)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-e1c3f812"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-02 08:01 UTC, anandab-msft commented
@JarbasHorst - made changes as you suggested.

2021-06-02 21:42 UTC, JarbasHorst requested changes

2021-06-02 21:42 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Change notifications enable you to subscribe to changes (create, update, and delete) to a resource, it provides a low latency model by allowing you to maintain a [subscription](/graph/api/resources/w
Please, replace the comma with a period  => `...to a resource. It provides...`

2021-06-02 21:42 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channel.md
> +description: "Get change notifications for change in creation, updation or deletion of team and channels using Microsoft Graph"
Please rephrase for simplicity and consistency. My suggestion:

Get change notifications for changes (create, update, and delete) in team and channels using Microsoft Graph

2021-06-02 21:42 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channel.md
> +title: "Get change notifications for creation, updation or deletion of team and channels using Microsoft Graph"
Please rephrase for simplicity and consistency. My suggestion:

Get change notifications for changes (create, update, and delete) in team and channels using Microsoft Graph

2021-06-02 21:42 UTC, JarbasHorst commented on api-reference/beta/resources/webhooks.md
> +| Teams [conversationMember][] | Changes to member in a specific team:<br>`/teams/{id}/members` | Yes |
Since in article _teams-changenotifications-teamMembership.md_ you are already talking about membership, I would suggest you replacing `Changes to member in a specific team` with `Changes to membership in a specific team`.

2021-06-03 05:45 UTC, opbld30 commented
Docs Build status updates of commit _[1939c08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1939c0827e0b31879a75704c08af125daa666ffe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-fedbcd77)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-fedbcd77"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-03 05:47 UTC, anandab-msft commented
@JarbasHorst - made suggested changes

2021-06-03 21:43 UTC, JarbasHorst requested changes

2021-06-03 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channel.md
> +>**Note:** Private channel is not supported.
Please, rephrase for clarity and conformity. My suggestion:

`Private channels aren't supported.`

2021-06-03 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channel.md
> +>**Note:** [discoverySettings](/graph/api/resources/teamdiscoverysettings?preserve-view=true)  and [classSettings](/graph/api/resources/teamclasssettings?preserve-view=true) are not exposed in payloa
Please, use common contractions. Replace `are not` with `aren't`.

2021-06-03 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-team-and-channel.md
> +>**Note:** Channel email address is not returned in payload.
Please, rephrase for conformity. My suggestion:

`The channel email address isn't returned in the payload.`

2021-06-03 21:43 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes related to a resource across tenant** - for example, one can subscribe to change in messages in any channel across tenant and get notified whenever a mess
Please, rephrase the sentence to [include articles](https://docs.microsoft.com/en-us/style-guide/global-communications/writing-tips). My suggestion:

`one can subscribe to change in messages in any channel across the tenant and get notified whenever a message is created in any channel in the tenant.`

2021-06-03 21:43 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +For notifications with resource data, the payload looks like the following. This payload is for notification corresponding to chat message resource, in actual notification **resource** and **resource
Please, rephrase for simplicity and to include articles. My suggestion:

`... This payload is for a notification corresponding to the chat message resource. The actual notification includes the **resource** and **resourceData** properties, which represents the resource that has triggered the notification.`

2021-06-03 21:43 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +The example above shows a notification corresponding to a chat message resource. The actual notification includes the resource and resourceData properties, which represents the resource that has trig
Please, highlight the **resource** and **resourceData** properties for consistency.

2021-06-03 21:43 UTC, JarbasHorst commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes related to a resource across tenant** - for example, one can subscribe to change in messages in any channel across tenant and get notified whenever a mess
Please, rephrase the sentence to include articles. My suggestion:

`**Change notification to track all changes related to a resource across the tenant**`

2021-06-03 21:43 UTC, JarbasHorst commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[Teams](../resources/team.md)|`/teams`,`/teams/{id}`|
Please, add a empty space here: "`/teams`, `/teams/{id}`"

2021-06-04 15:18 UTC, anandab-msft commented on concepts/teams-changenotifications-teamMembership.md
> +# Get change notifications for change in teams membership using Microsoft Graph
here i meant team inside `microsoft teams`, i have changed `teams` to `team`

2021-06-04 15:34 UTC, opbld30 commented
Docs Build status updates of commit _[4dd97f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4dd97f89af383a185619ccc2cad7cd9486b40ca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-4016f040)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-4016f040"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-04 16:00 UTC, anandab-msft commented
@JarbasHorst - made suggested changes

2021-06-04 20:09 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-06-05 00:00 UTC, opbld33 commented
Docs Build status updates of commit _[7568b5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7568b5d14ff3c373192a27e5d33a52ae9dc6b32a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-c727f798)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-c727f798"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-05 00:01 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +# Change notifications for resources in Microsoft Teams using Microsoft Graph
The H1 and the title field should match. Would this work for the title: "Change notifications for Microsoft Teams resources in Microsoft Graph"? That's a little more concise and still includes the important keywords.

2021-06-05 00:01 UTC, opbld34 commented
Docs Build status updates of commit _[7568b5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7568b5d14ff3c373192a27e5d33a52ae9dc6b32a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-d3be6d02)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-d3be6d02"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-05 00:04 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Change notifications enable you to subscribe to changes (create, update, and delete) to a resource. It provides a low latency model by allowing you to maintain a [subscription](/graph/api/resources/w
Change "it provides" to "Change notifications provide". Otherwise because you are using a singular pronoun when change notifications is plural, it's not clear what "It" refers to. In the last sentence, change "One" to "You", as we generally use second person in our content.

2021-06-05 00:07 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes related to a resource across the tenant** - for example, one can subscribe to change in messages in any channel across the tenant and get notified wheneve
In these bullet points, change "one" to "you". In the example in the first bullet, you only mention that they get notified when a message is created, should you say "created, updated, or deleted"? Also "change" should be "changes". In both bullet points, to be more concise, can we remove "Change notifications to"?

2021-06-05 00:08 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes for a specific resource** - for example, one can subscribe to change in messages in a particular channel and get notified whenever a message is created in
In the second bullet you also say "track all changes" but only mention messages getting created. Please update "change" to "changes here too.

2021-06-05 00:09 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Check [Microsoft Graph change notifications](webhooks.md) to see what resources support what type of change notification.
For consistency and readability, we introduce the subject before we provide the link. In this case, please revise the cross-reference: "For details about which resources support which types of change notifications, see [Microsoft Graph change notifications]."

2021-06-05 00:10 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +Depending on your subscription, you can either get the notification with resource data, or without resource data. Subscribing with resource data allows you to get the message payload along with the n
Revise "notification removing" to "notification, which removes".

2021-06-05 00:13 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +For notifications with resource data, the payload looks like the following.  This payload is for a notification corresponding to the chat message resource. The actual notification includes the **reso
Change "represents" to "represent", assuming that both properties represent the resource.

2021-06-05 00:14 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +The decrypted notification payload looks like the following. For above example decrypted payload conforms to the [chatMessage](/graph/api/resources/chatMessage?preserve-view=true) schema. The payload
Change "For above example" to "The decrypted payload for the previous example".

2021-06-05 00:16 UTC, Lauragra commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +The example above shows a notification corresponding to a chat message resource. The actual notification includes the **resource** and **resourceData** properties, which represents the resource that
We avoid using the words "above" and "below" per Microsoft style because those terms don't translate well for a global audience. Instead of above, use "previous example". Also avoid using gerunds where possible; in this case, you can change "corresponding" to "that corresponds". Represents should be represent here too.

2021-06-05 00:18 UTC, Lauragra commented on concepts/teams-changenotifications-chatmessage.md
> -Change notifications enable you to subscribe to changes (create, update, and delete) to [messages](/graph/api/resources/chatMessage?preserve-view=true) in a [channel](/graph/api/resources/channel?pre
Why is this introduction getting deleted? Note that for SEO and general readability, we don't begin an article with a heading. Please restore or add an introduction to this article.

2021-06-05 00:19 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +title: "Get change notifications for changes (create, update, and delete) in team and channels using Microsoft Graph"
The title should match the H1. In this case, I suggest: "Get change notifications for teams and channels using Microsoft Graph".

2021-06-05 00:19 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +
This article will also need an introduction.

2021-06-05 00:20 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +### Subscribe to changes in any team at tenant level
The first heading within an article should be an H2, not an H3.

2021-06-05 00:20 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +To get change notifications for all changes related to any team (create, update, and delete) in a tenant, subscribe to `/teams`. This resource supports [including resource data](webhooks-with-resourc
I recommend moving the parenthetical to follow changes instead of team, for clarity.

2021-06-05 00:21 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +#### Permissions
When you change the heading to an H2, also update these to be H3s, so the heading order is sequential.

2021-06-05 00:22 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +### Subscribe to changes in a particular team
This should also be an H2, please elevate the headings by one level throughout.

2021-06-05 00:22 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +To get change notifications for all changes related to any channel (create, update, and delete) in a tenant, subscribe to `/teams/getAllChannels`. This resource supports [including resource data](web
Move the parenthetical to come after changes.

2021-06-05 00:28 UTC, Lauragra commented on concepts/teams-changenotifications-team-and-channel.md
> +description: "Get change notifications for changes (create, update, and delete) in team and channels using Microsoft Graph"
The description field should generally be a one-sentence summary of what the article covers, and it shouldn't duplicate the title. This description potentially appears in search results. Suggested revision: "Learn how to get notifications for changes (create, update, and delete) for teams and channels using Microsoft Graph APIs."

2021-06-05 00:29 UTC, Lauragra commented on concepts/teams-changenotifications-teamMembership.md
> +# Get change notifications for change in team membership using Microsoft Graph
Make sure that the title field matches the H1. The second occurrence of change in the title should be plural, "changes".

2021-06-05 00:30 UTC, Lauragra commented on concepts/teams-changenotifications-teamMembership.md
> +description: "Get change notifications for any change in Teams membership using Microsoft Graph"
Add a description that provides the intent and does not repeat the title.

2021-06-05 00:31 UTC, Lauragra commented on concepts/teams-changenotifications-teamMembership.md
> +
Add an introduction to the article.

2021-06-05 00:31 UTC, Lauragra commented on concepts/teams-changenotifications-teamMembership.md
> +### Subscribe to changes in membership of a particular team
Adjust all the heading levels - this should be an H2, and so on.

2021-06-05 00:31 UTC, Lauragra commented on concepts/teams-changenotifications-teamMembership.md
> +To get change notifications for membership change in a particular team, subscribe to `/teams/{id}/members`. This resource supports [including resource data](webhooks-with-resource-data.md) in the not
"membership change' -> "membership changes"

2021-06-05 00:36 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Change notification in Microsoft Teams
I'm not sure about this TOC placement - seems a bit buried and potentially disconnected. I wonder if we want to surface these topics under the Teamwork node under Learn, where we have some other concept topics related to Teams Maybe we streamline the TOC titles too, for example (also a flat list instead of nesting for discoverability):
Change notifications
Get changes for chat and channel messages
Get changes for teams and channels
Get changes for team membership

2021-06-05 14:30 UTC, anandab-msft commented on concepts/change-notification-in-Microsoft-Teams-overview.md
> +- **Change notification to track all changes related to a resource across the tenant** - for example, one can subscribe to change in messages in any channel across the tenant and get notified wheneve
If I remove `Change notification to`  then the bullet points will look out of context

Microsoft Teams supports two types of change notifications:
- **Track all changes related to a resource across the tenant** - for example..
- **Track all changes for a specific resource** - for example..

2021-06-08 06:36 UTC, anandab-msft commented on concepts/teams-changenotifications-chatmessage.md
> -Change notifications enable you to subscribe to changes (create, update, and delete) to [messages](/graph/api/resources/chatMessage?preserve-view=true) in a [channel](/graph/api/resources/channel?pre
restored introduction

2021-06-08 06:47 UTC, anandab-msft commented on concepts/teams-changenotifications-team-and-channel.md
> +
added

2021-06-08 07:02 UTC, anandab-msft commented on concepts/toc.yml
> +              - name: Change notification in Microsoft Teams
@Lauragra 

- I agree with the discoverability part, but there are other items such as `notification without resource data ` and `overview` page which are related , so if we have to move then we need to move the entire thing (the `change notification` node itself)
- will changing TOC titles to below make sense
    * Change notificaiton in Microsoft Teams
        * Overview
        * Chat and channel messages
        * Teams and channels
        * Team membership

2021-06-08 07:12 UTC, opbld32 commented
Docs Build status updates of commit _[f7e0cd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7e0cd5dcbedf74573d913d135d4ff90aad080b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-9e2c55f3)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-9e2c55f3"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-08 07:14 UTC, anandab-msft commented
@JarbasHorst - can you do one more round of quick pass, i have added introduction and fixed Heading.

2021-06-09 20:25 UTC, opbld30 commented
Docs Build status updates of commit _[dbaa759](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbaa7592aeb42b0b1465d2fa12bd5aa5d9c84cbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-20b91956)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-20b91956"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-10 02:49 UTC, opbld31 commented
Docs Build status updates of commit _[0b32148](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b32148a76f255d2be224743446445d1b521bd60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-7bad833d)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-7bad833d"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-10 02:51 UTC, opbld32 commented
Docs Build status updates of commit _[0b32148](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b32148a76f255d2be224743446445d1b521bd60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-efcae1d1)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-efcae1d1"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-10 02:51 UTC, Lauragra approved these changes

2021-06-10 02:52 UTC, opbld31 commented
Docs Build status updates of commit _[8df3068](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8df3068d0c38ed35767db01eb6dc2882a4470fa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-1fa437ff)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-1fa437ff"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-15 02:54 UTC, opbld33 commented
Docs Build status updates of commit _[7248e0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7248e0a9c0907c016f5e53a11cdbd285cdad4f10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-565e4372)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-565e4372"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-15 02:55 UTC, opbld30 commented
Docs Build status updates of commit _[7248e0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7248e0a9c0907c016f5e53a11cdbd285cdad4f10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-12740) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-64a74382)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-12740) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/change-notification-in-Microsoft-Teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/change-notification-in-Microsoft-Teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-team-and-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-team-and-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-team-and-channel?branch=pr-en-us-12740) |
[concepts/teams-changenotifications-teamMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/teams-changenotifications-teamMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-teammembership?branch=pr-en-us-12740) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/change-notification-in-microsoft-teams-overview?branch=pr-en-us-12740) |

<a id="5a4bf723696c90353d87e6f17ef663f5-64a74382"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandab-msft-TCM-notification/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to  [...]

2021-06-15 02:56 UTC, merged