[CloudPC] Add audit event resource
microsoftgraph/microsoft-graph-docs pull request #12775
Opened 2021-05-19 08:20 UTC by ecmadao

2021-05-19 08:42 UTC, opbld33 commented
Docs Build status updates of commit _[d860c2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d860c2a05b9443f650c1f0ffcb360ab6257a40a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105190840125809-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=41Z5suB51wKXFxaV2CLbBM7fKpT3SVROR6e2FBXVCk8%3D&st=2021-05-19T08%3A37%3A15Z&se=2021-06-19T08%3A42%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 07:16 UTC, opbld30 commented
Docs Build status updates of commit _[7b3e9f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b3e9f1f8abbd11d323ad3c62f0bbd9972fd9c95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106030715052111-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OayC%2FSR%2FgzTCgaFvDGkOe980XGtR9AmOBaNUx32GKek%3D&st=2021-06-03T07%3A11%3A30Z&se=2021-07-04T07%3A16%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 15:53 UTC, ecmadao commented on api-reference/beta/api/cloudpcauditevent-get.md
> +GET /deviceManagement/virtualEndpoint/auditEvents/{cloudPcAuditEventId}
Thanks, done

2021-06-09 15:53 UTC, ecmadao commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +# [C#](#tab/csharp)
Thanks, done

2021-06-09 15:54 UTC, ecmadao commented on changelog/Microsoft.CloudManagedDesktop.json
> +            "WorkloadArea": "Microsoft.CloudManagedDesktop",
Thanks, done

2021-06-09 15:54 UTC, ecmadao commented on api-reference/beta/api/cloudpcauditevent-get.md
> +GET https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/auditEvents/{cloudPcAuditEventId}
Thanks, done

2021-06-09 15:55 UTC, opbld33 commented
Docs Build status updates of commit _[69fef90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69fef9011700255c9eeafe4849c8b615fa70fe5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106091553355615-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KragPxlGfIKThoQZX3M1GW4gOE%2BgzmAlOWe0us2OPHU%3D&st=2021-06-09T15%3A50%3A08Z&se=2021-07-10T15%3A55%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 08:42 UTC, opbld34 commented
Docs Build status updates of commit _[f9a5370](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9a53704934506429ae3ba40668c9d6d177f80ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100841003077-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aLPTUK0G2ckYPnEzX8FnDx%2B9XdKNyMLZrpjUKp%2Bh9uE%3D&st=2021-06-10T08%3A37%3A19Z&se=2021-07-11T08%3A42%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 14:33 UTC, opbld33 commented
Docs Build status updates of commit _[23314df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23314dfc07336cd674f51153bcfeed5cca67bde5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141431528533-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WOIZJLaneJ1tmYblvslevrb1%2F8658SkQSOGtPZlNVy4%3D&st=2021-06-14T14%3A28%3A12Z&se=2021-07-15T14%3A33%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 14:42 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcauditevent-get.md
> +description: "Read the properties and relationships of the cloudPcAuditEvent object."
Line 3 (description): Please change "the" to "a" because we are not talking about a particular one, but any. 

* Read the properties and relationships of a cloudPcAuditEvent object.

Please make this change in line 16 as well.

2021-06-14 14:53 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +List properties and relationships of the [cloudPcAuditEvent](../resources/cloudpcauditevent.md) objects.
Let's re-think the description (lines 3 and 16). May I suggest:
* List all audit events for the tenant.

What do you think?

2021-06-14 14:56 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +# [HTTP](#tab/http)
Please remove this line. Tabs are automatically generated for docs.

2021-06-14 14:56 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +# [HTTP](#tab/http)
You can add an introductory boilerplate such as: "Here is an example of a request."

2021-06-14 14:58 UTC, isvargasmsft commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +  "@odata.type": "Collection(microsoft.graph.cloudPcAuditEvent)"
Please change to:
oadata.type: microsoft.graph.cloudPcAuditEvent, 
isCollection: true

Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=set-up-for-api-doctor-in-an-api-topic

2021-06-14 15:07 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcauditactor.md
> +Represents the audit actor. The actor is AAD user and application that are associated with the audit event.
Lines 3 and 16 (description): May I suggest:
The audit actor represented by the Azure AD user and application associated with the audit event.

2021-06-14 15:08 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcauditactor.md
> +|applicationId|String|AAD Application Id.|
Please use "Azure AD" instead of "AAD".

2021-06-14 15:22 UTC, isvargasmsft commented on api-reference/beta/resources/cloudpcauditactor.md
> +|actorType|[cloudPcAuditActorType](#cloudpcauditactortype-values)|The actor type. Possible values include ItPro, Application, Partner and Unknown.|
Line 24: The name of this property in the metadata is just "type". Can we please make it consistent with the metadata?

2021-06-14 17:05 UTC, isvargasmsft requested changes
Hello, thank you very much for your work on this PR. 

Some general re-phrasing requests and details in structure. Great work overall. 

Please feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2021-06-15 05:40 UTC, ecmadao commented on api-reference/beta/resources/cloudpcauditactor.md
> +|actorType|[cloudPcAuditActorType](#cloudpcauditactortype-values)|The actor type. Possible values include ItPro, Application, Partner and Unknown.|
Thanks! This should be a typo. Fixed

2021-06-15 05:40 UTC, opbld32 commented
Docs Build status updates of commit _[ffe32db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffe32db97d403b301196795ef9fcb887b79b2362)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150539180026-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=09docptyRWaYA6UolKfF2v7pcBc3zVohWrXIGjh5aNs%3D&st=2021-06-15T05%3A35%3A45Z&se=2021-07-16T05%3A40%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 05:42 UTC, ecmadao commented on api-reference/beta/api/cloudpcauditevent-get.md
> +description: "Read the properties and relationships of the cloudPcAuditEvent object."
Thanks, resolved

2021-06-15 06:26 UTC, opbld34 commented
Docs Build status updates of commit _[d659c69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d659c69c736725c7a76d1bb693bbd7cdc2caa298)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150624508597-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l%2BdRNazdKVHakpgLbrh0WsyPvW9YXFyCOjhRsqwJets%3D&st=2021-06-15T06%3A21%3A18Z&se=2021-07-16T06%3A26%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 06:37 UTC, ecmadao commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +# [HTTP](#tab/http)
Thanks for point out. Removed.

2021-06-15 06:38 UTC, ecmadao commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +  "@odata.type": "Collection(microsoft.graph.cloudPcAuditEvent)"
Thanks, resolved now.

2021-06-15 06:38 UTC, ecmadao commented on api-reference/beta/resources/cloudpcauditactor.md
> +|applicationId|String|AAD Application Id.|
Sure, updated.

2021-06-15 06:40 UTC, ecmadao commented on api-reference/beta/resources/cloudpcauditactor.md
> +Represents the audit actor. The actor is AAD user and application that are associated with the audit event.
Thanks for the suggestion. I updated the description now.

2021-06-15 06:41 UTC, ecmadao commented on api-reference/beta/api/virtualendpoint-list-auditevents.md
> +List properties and relationships of the [cloudPcAuditEvent](../resources/cloudpcauditevent.md) objects.
Thanks, I updated this to "List all the [cloudPcAuditEvent](../resources/cloudpcauditevent.md) objects for the tenant."

2021-06-16 02:32 UTC, opbld33 commented
Docs Build status updates of commit _[3a9b3b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a9b3b3c0ffb452681abf72f2957d71d2e6b4d22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160230457320-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9Rqrdkor0HSYcdmzLuno0gzQOpd657gbQBwSXxvqkZE%3D&st=2021-06-16T02%3A27%3A31Z&se=2021-07-17T02%3A32%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 03:30 UTC, opbld31 commented
Docs Build status updates of commit _[05d5e5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05d5e5b04e94f1572367a12bf1229e1fd70b3916)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106170327595895-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=warU%2BxZAOZ482FsWuOHoO67jjgfDkMYHCwal%2FrpWUz0%3D&st=2021-06-17T03%3A25%3A18Z&se=2021-07-18T03%3A30%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 16:12 UTC, opbld32 commented
Docs Build status updates of commit _[6e15fff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e15fffad27f72dbbd1602b380c8f686089b63e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181549028304-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3z2rMeI6pLUpX1qqfb3QZxzwO6QkjE9OXgEseKHYTYs%3D&st=2021-06-18T16%3A07%3A37Z&se=2021-07-19T16%3A12%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 21:14 UTC, opbld32 commented
Docs Build status updates of commit _[3130694](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31306944db55b52501fe4a2c36324f6dd19ebc21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106212109318343-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j0OUyb4KmcDpjYddXTfd5pZ5f1OX%2FLmKIp893GBWMpo%3D&st=2021-06-21T21%3A09%3A16Z&se=2021-07-22T21%3A14%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 21:25 UTC, isvargasmsft commented on api-reference/beta/api/cloudpcauditevent-get.md
> +ms.prod: "cloud-pc"
Line 6: please verify the ms.product is "cloud-pc". In the guidance we have "cloud-communications" and "cloud-printing".

2021-06-22 20:12 UTC, opbld30 commented
Docs Build status updates of commit _[eab5c5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eab5c5e864abee965e883300da3812a554111fd6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2db2581c)

<a id="2db2581c"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106222010528654-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KQ6BrHKR3heIs%2Bqaa%2BSfGNK9gjHEPcxuh9%2Bh3s6qOow%3D&st=2021-06-22T20%3A07%3A11Z&se=2021-07-23T20%3A12%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 20:36 UTC, opbld32 commented
Docs Build status updates of commit _[404e7b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/404e7b2c57840b0b0c14beba4ef3b18c7ec1aa50)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5c197d6a)

<a id="5c197d6a"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106222036221479-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pQr1G%2FBdrR6TCkfYtmgTK1BMcMVsChf7nptMs%2Fr0lFs%3D&st=2021-06-22T20%3A31%3A43Z&se=2021-07-23T20%3A36%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 20:38 UTC, isvargasmsft requested changes
Thank you very much for your response to my comments. 

Please resolve the conflicts with the main branch.

2021-06-23 01:58 UTC, ecmadao commented on api-reference/beta/api/cloudpcauditevent-get.md
> +ms.prod: "cloud-pc"
Thanks! I checked with my teammates, the `ms.prod` here is "cloud-pc", it also align with other docs for our Graph endpoints.

2021-06-23 02:04 UTC, opbld34 commented
Docs Build status updates of commit _[4d4c56c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d4c56c1610653008b6210ff2bebd6956ba22d6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106230203121648-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BLBCk8kSWlOoZpYv%2BBdcMvcUGXpitSEWltHfc1HSAmo%3D&st=2021-06-23T01%3A59%3A24Z&se=2021-07-24T02%3A04%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 19:39 UTC, opbld33 commented
Docs Build status updates of commit _[60b5e86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60b5e86f09c83e8c6df94097c2eef9c4f19c90e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106231938137287-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9GZEECcMpR3Dd7J4TiSfkmh1JsckQevW5bDJogXoJ2E%3D&st=2021-06-23T19%3A34%3A46Z&se=2021-07-24T19%3A39%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 20:08 UTC, opbld31 commented
Docs Build status updates of commit _[127b81d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/127b81dd7846bf7b5aae820ea1d3178d160b9773)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106232007028340-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4wsnhfPCHTiKb2Gpm6xFyswkZsoBvHHfj4BfxRq5krI%3D&st=2021-06-23T20%3A03%3A32Z&se=2021-07-24T20%3A08%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 20:14 UTC, isvargasmsft approved these changes
Thank you for your work on this PR!

2021-06-24 03:18 UTC, opbld32 commented
Docs Build status updates of commit _[2ada3dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ada3dc21ba038fd57e719395b80a16014106f96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240316390924-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=S6NDOLjyNmSCRSMeepcwetJhdiP%2FDeggdh7z1bCeceo%3D&st=2021-06-24T03%3A13%3A12Z&se=2021-07-25T03%3A18%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 03:29 UTC, AshleyYangSZ approved these changes

2021-06-24 15:02 UTC, opbld33 commented
Docs Build status updates of commit _[303a3d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/303a3d48bd9ce67f0339bf76b2bed7712356b5fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241500311052-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a6%2BVkC4I5ApGY%2BabXNfKjs593fU0TaBhQ%2Fa%2FvqZI2Ik%3D&st=2021-06-24T14%3A57%3A08Z&se=2021-07-25T15%3A02%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 22:16 UTC, opbld34 commented
Docs Build status updates of commit _[2502f96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2502f96773391b0866297525e1784dd6d65b0c96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242215270751-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ohYM7T9lAHQKJjgSeuSx4BUfvDvkCdANkVfBA73Tmcc%3D&st=2021-06-24T22%3A11%3A55Z&se=2021-07-25T22%3A16%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 22:20 UTC, opbld31 commented
Docs Build status updates of commit _[21052f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21052f43d9a1cf12a705f057124b8806b15f99b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242216158970-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dJ6%2FGVD%2FNmXTaFSygOv1no8AEyMkoTasChgMmCyY19w%3D&st=2021-06-24T22%3A15%3A26Z&se=2021-07-25T22%3A20%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 22:22 UTC, opbld34 commented
Docs Build status updates of commit _[ee3693f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee3693f35e99cc51f8fecd06dca09bdd730c1aba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242218169565-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g1fnsuXmktrun6s6N4b7GtWjrGeCD3niR1wD8eIpSZ4%3D&st=2021-06-24T22%3A17%3A16Z&se=2021-07-25T22%3A22%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 22:28 UTC, opbld30 commented
Docs Build status updates of commit _[3648546](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36485465a8a3cdb1085051b3804a854106a68acb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242226313577-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=16f8gHJFKesA74vgjWHHjay0Oae3ckmFtomGgVoJ7Ng%3D&st=2021-06-24T22%3A23%3A10Z&se=2021-07-25T22%3A28%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 22:36 UTC, Lauragra commented on api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md
> +Get audit activity types by tenant ID.
Should the HTTP request include an ID for the tenant?

2021-06-24 22:39 UTC, opbld30 commented
Docs Build status updates of commit _[c6d04fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6d04fd2b07588463ee5d62ffc062bd5f5424165)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242237529461-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aoAh6WbVdpCLV4LWRJR%2F3bbQK9ZgKbr93giigd2pIAU%3D&st=2021-06-24T22%3A34%3A35Z&se=2021-07-25T22%3A39%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 22:41 UTC, opbld30 commented
Docs Build status updates of commit _[a9e625b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9e625ba483d3b191d966e109c0766dc931cf8e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242238555518-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GXEc4Dx8cQxPTis8qKJ1%2FOyIoU1l2n9GYnnvegP1PE4%3D&st=2021-06-24T22%3A36%3A25Z&se=2021-07-25T22%3A41%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 23:12 UTC, opbld32 commented
Docs Build status updates of commit _[176c34a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/176c34a32a96e7f6f528b412ffe90d9566fe6ffd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242310400896-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=73d2E0UzoIl0AaSb1wUI%2FFgrL0Ou5dLXsw%2FlCXqLdc4%3D&st=2021-06-24T23%3A07%3A16Z&se=2021-07-25T23%3A12%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 23:14 UTC, cohanley approved these changes

2021-06-24 23:15 UTC, opbld33 commented
Docs Build status updates of commit _[6428dea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6428deaf1c57489745afea05860fafcc69ebad56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106242313387946-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=avXOSSqdY3U%2BFeUNAi3Dgk0hDHo2coNzGzsh0LO1Ytw%3D&st=2021-06-24T23%3A10%3A13Z&se=2021-07-25T23%3A15%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 23:19 UTC, Lauragra approved these changes

2021-06-29 12:08 UTC, ecmadao commented on api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md
> +Get audit activity types by tenant ID.
Thanks for point out. Don't need to have the tenant ID in URL, we will parse it from token.

2021-06-30 01:58 UTC, Lauragra approved these changes

2021-06-30 01:59 UTC, opbld30 commented
Docs Build status updates of commit _[dd52f35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd52f35dc447a2d8ef0ca01b60271f284c438829)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcauditevent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/cloudpcauditevent-getauditactivitytypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-getauditactivitytypes?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/api/virtualendpoint-list-auditevents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/api/virtualendpoint-list-auditevents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-auditevents?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditactor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditactor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditactor?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditevent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditevent?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditproperty.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditproperty?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcauditresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcauditresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcauditresource?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcuserrolescopetaginfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/cloudpcuserrolescopetaginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcuserrolescopetaginfo?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/resources/virtualendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/resources/virtualendpoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/virtualendpoint?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcauditevent-get?view=graph-rest-beta&branch=pr-en-us-12775) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/edward/audit/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106300157435094-12775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qthHLojMQEsygv06ufP5Ldhz1deyn%2Fy5og7PQeTzXM0%3D&st=2021-06-30T01%3A54%3A13Z&se=2021-07-31T01%3A59%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 02:01 UTC, merged