EDU assignments: follow up on prior deprecations and additional beta updates
microsoftgraph/microsoft-graph-docs pull request #12795
Opened 2021-05-20 05:41 UTC by sharaaU7

1. remove makecode, form, onenote resource support, 
2. add documentation for assignment level resources folder, 
3. remove deprecated properties

2021-05-20 05:43 UTC, opbld34 commented
Docs Build status updates of commit _[0bd829f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0bd829f63b759b5374acdc69d003b6a5ec5844f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105200541557707-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3gPDLsc7BRnnpJhQ9Vy04%2FZLrnECEH3vk1Y8mG90GJ4%3D&st=2021-05-20T05%3A38%3A19Z&se=2021-06-20T05%3A43%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 21:39 UTC, opbld33 commented
Docs Build status updates of commit _[8a8ce61](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a8ce6150927a6816198f16e016d36a4fb834ff5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105202138357163-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g2foLyPpCIVSIyQwkXnM%2FSyGlqNw0JZCil4JBPAZgGM%3D&st=2021-05-20T21%3A34%3A52Z&se=2021-06-20T21%3A39%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 23:40 UTC, ssriniva-msft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +title: "educationAssignment: setupResourcesFolder"
setUp

2021-05-21 05:35 UTC, opbld32 commented
Docs Build status updates of commit _[a919fe7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a919fe7f560b19263f96b01aa1e6a7e75647f0f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105210533461151-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Vj7yLGtYZ4qyNBbfiPBx5jpbY%2BEpoDmhJRgo5aL52EA%3D&st=2021-05-21T05%3A30%3A10Z&se=2021-06-21T05%3A35%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 14:39 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-get.md
> +>**Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
In general we try to avoid passive voice, as it lead to further questions like who? or how?
In this case, please re-phrase in active voice. For example:
- An actual call will return all the properties.

2021-05-21 16:39 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +This function triggers the SharePoint resource folder creation where all file-based resources (Word, Excel, and so on) should be uploaded for a given assignment.
Let's re-phrase for efficiency:
1. We avoid using "and so on". Please check [Microsoft Writing Style here](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=29202).
2. The phrasing could be more specific and clear.
3. Please include the link to the **assignment** resource type.
For example:
- Create a SharePoint folder to upload files for the specified [educationAssignment](the link here).

2021-05-21 16:47 UTC, opbld30 commented
Docs Build status updates of commit _[8cf3de4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cf3de4e282bbeff8678c25d4787742a63385bed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211645323194-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kbvJq4au831dEAAdI9Omn%2B8QktbMW4T7%2FofDjV%2BFc%2BY%3D&st=2021-05-21T16%3A42%3A52Z&se=2021-06-21T16%3A47%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 16:58 UTC, opbld32 commented
Docs Build status updates of commit _[76bebbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76bebbda8474ac8a8c8a40f0f49cf4dc53aa7bea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211657245030-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fTQICabae1gkV8NSzt2Xb%2B2837XhXXs6Sff625D%2FQSA%3D&st=2021-05-21T16%3A53%3A24Z&se=2021-06-21T16%3A58%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 16:59 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +Note that files must be located in this folder in order to be added as resources. Only a teacher in the class can determine what files to upload in the assignment level resource folder.
In general, we have certain rules for using passive voice as it usually leads to questions (like "who?" or "how?") and it's not the most clear way for non native speakers. More details here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523 

In this case, please re-phrase for clarity and efficiency. For example:
Only files in this folder are saved as [educationAssignmentResource](reference link here). The teacher will determine the files to upload to the **assignment**'s folder.

2021-05-21 17:02 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +If successful, this method returns a `200 Ok` response code. The body will contain the assignment model.
Does the response contain an object? If the answer is yes, please re-phrase with the link:
- If successful, this method returns a `200 Ok` response code and [assignment](link here) object in the request body.

2021-05-21 17:08 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Request
Is there a reason to change this to H3? In general, we use H5 for request and response in examples.

2021-05-21 17:10 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Response
Same comment as above. Please use H5 for responses and requests inside examples.

2021-05-21 17:12 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-update.md
> +>**Note:** The response object shown here might be shortened for readability. All of the properties will be returned from an actual call.
Could you please clarify the reason to add this sentence? If we explain in the Response section above that the operation returns an object in the request body, I don't feel this additional sentence adds value. 

Please let me hear your thoughts and let's align across all docs in this PR.

2021-05-21 17:15 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +POST https://graph.microsoft.com/beta/education/classes/11012/assignments/19002/setUpResourcesFolder
Please include "keyProperty": "id", in the API Doctor box above (lines 48 to 51) and list the ids for classes and assignments there. For guidance please check: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor

Please do the same for all docs.

2021-05-21 17:17 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-get.md
> +>**Note:** The response object shown here might be shortened for readability. An actual call will return all the properties.
Please review my previous comment regarding the nature of this additional sentence.

2021-05-21 17:24 UTC, Lauragra commented on api-reference/beta/api/educationassignment-get.md
> +>**Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
@isvargasmsft , @sharaaU7 , FYI, this sentence should be removed. This is old boilerplate that we've removed from the stub generator tool because it isn't technically accurate (not all calls return all properties).

2021-05-21 17:25 UTC, isvargasmsft commented on api-reference/beta/resources/educationassignment.md
> +|[Set up assignment resources folder](../api/educationassignment-setupresourcesfolder.md)| string| The OneDrive folder into which file-based resources should be placed to be part of an assignment res
Let's re-phrase in active voice. For example:
Creates a folder to upload resources for the specified assignment. Only files in this folder are saved as assignment resources.

2021-05-21 17:28 UTC, Lauragra commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Response
@isvargasmsft , @sharaaU7 , FYI, the Request and Response headings in the Examples section should be H3s. This was an error in our old topic generator that has been fixed. The exception is when there are multiple examples, then you have a structure like so:
## Examples
### Example 1: <title>
#### Request
#### Response

In general for SEO, heading levels within articles should be sequential.

2021-05-21 17:28 UTC, isvargasmsft commented on api-reference/beta/resources/educationsubmission.md
> +|[Set up submission specific resources folder](../api/educationsubmission-setupResourcesFolder.md) |[educationSubmission](educationsubmission.md) | Trigger the creation of the SharePoint resource fol
Please avoid using "and so on". Details here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=29202
In this case, please re-phrase for clarify. Example:
Creates a SharePoint folder to upload files as submission resources.

2021-05-21 17:29 UTC, Lauragra commented on api-reference/beta/api/educationassignment-update.md
> +>**Note:** The response object shown here might be shortened for readability. All of the properties will be returned from an actual call.
This is inaccurate boilerplate text from the old topic generator tool that should be removed. (We should do this globally someday).

2021-05-21 17:29 UTC, Lauragra commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Request
To clarify, heading levels should be sequential so it is correct to make these H3s.

2021-05-21 17:33 UTC, Lauragra commented on api-reference/beta/resources/educationassignment.md
> +|[Set up assignment resources folder](../api/educationassignment-setupresourcesfolder.md)| string| The OneDrive folder into which file-based resources should be placed to be part of an assignment res
Minor fix - we use imperative verbs for method descriptions, so it would be "Create".

2021-05-21 17:34 UTC, isvargasmsft commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Removed the **releasedDateTime** property from the [educationSubmission](https://docs.microsoft.com/en-us/graph/api/resources/educationSubmission?view=graph-rest-beta) resou
Is there a reason to delete old ChangeLists? 
If you are deprecating or deleting something, please create a new ChangeList and use the ChangeType: deletion option. 

Please **do not delete Changelog entries** as it would nullify the purpose of the Changelog.

2021-05-21 17:40 UTC, sharaaU7 commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Request
will do, I think I saw an earlier comment in one of the prior PR from Laura.

2021-05-21 17:41 UTC, sharaaU7 commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Response
will do

2021-05-21 17:41 UTC, sharaaU7 commented on api-reference/beta/api/educationassignment-update.md
> +>**Note:** The response object shown here might be shortened for readability. All of the properties will be returned from an actual call.
We can remove it, was added for clarity

2021-05-21 17:42 UTC, isvargasmsft commented on concepts/whats-new-overview.md
> +- Graph user (Teacher) can now trigger the assignment level resources folder creation before uploading assignment resources on OneDrive, teachers can trigger the assignment resources folder creation
Let's re-phrase for consistency and inclusion and the current phrasing is way too complicated for non native readers. 
My suggestion:
- [Create a folder](link to method) to upload files as [educationAssignment](link to resource) resources.

2021-05-21 17:43 UTC, sharaaU7 commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Removed the **releasedDateTime** property from the [educationSubmission](https://docs.microsoft.com/en-us/graph/api/resources/educationSubmission?view=graph-rest-beta) resou
good catch, It should have been a new entry

2021-05-21 17:43 UTC, isvargasmsft commented on concepts/whats-new-overview.md
> +- Graph user (Student) can now trigger the submission level resources folder creation before uploading a OneDrive resource for a given submission, student can trigger the submission resources folder
Similar observation above. My suggestion:
- [Create a folder](link to method) to upload files as [educationSubmission](link to resource) resources.

2021-05-21 17:47 UTC, isvargasmsft requested changes
@sharaaU7 thank you very much for putting everything together on this PR. 

Some general re-phrasing suggestions for efficiency and consistency. Please use [Microsoft Writing Style](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=33685) and [Graph Guidelines](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103149/Guidelines) for details.

In addition, please do not remove Changelog entries. Instead, create a new entry and use the ChangeType: deletion option. Mode details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

Please feel free to ping me on the side if you have any questions.

2021-05-21 17:48 UTC, opbld34 commented
Docs Build status updates of commit _[f10dc01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f10dc019c8c535368831b747ad3a0e29f07fc257)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211747364249-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bVOw7misgQYuuJr0QRTkyfgM6vy1jU7B673dIplurrw%3D&st=2021-05-21T17%3A43%3A50Z&se=2021-06-21T17%3A48%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 17:51 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Response
@sharaaU7 please review Laura's comment above. H3 are ok in this case because we have just one example. Thanks and sorry for the misunderstanding.

2021-05-21 17:51 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +### Request
@sharaaU7 please disregard this comment as per Laura's clarification above.

2021-05-21 18:49 UTC, sharaaU7 commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +If successful, this method returns a `200 Ok` response code. The body will contain the assignment model.
is the link correct in the new iteration?

2021-05-21 18:56 UTC, sharaaU7 commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +POST https://graph.microsoft.com/beta/education/classes/11012/assignments/19002/setUpResourcesFolder
at par with educationassignment-setupresourcesfolder.md now

2021-05-21 19:00 UTC, opbld31 commented
Docs Build status updates of commit _[b935b45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b935b45e45aaa93ee817a80c56a0c26870161148)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211859322018-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QzNlGUduXWAi4EZ4Mi7r39uZND8gz%2Fq4RLla4Tj%2F1do%3D&st=2021-05-21T18%3A55%3A45Z&se=2021-06-21T19%3A00%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 19:12 UTC, opbld30 commented
Docs Build status updates of commit _[119b0a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/119b0a7f1c62b6a550e63d987bddf6ac9d6ed596)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211911043208-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FZjudxB6ZVBnHescKdPfHclre4pqyGHA%2Blz5eQXfNHw%3D&st=2021-05-21T19%3A07%3A15Z&se=2021-06-21T19%3A12%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 19:15 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +  "blockType": "request",
Please change to response in  line 74.

2021-05-21 19:16 UTC, opbld31 commented
Docs Build status updates of commit _[31ba743](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31ba7439208371189c28d4eded4f43fa5c1d3475)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211915153460-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uzZNoGJ%2B5gzuCQdsOTjbPBvncwlxP2TwTzbnixtHv%2Bk%3D&st=2021-05-21T19%3A11%3A25Z&se=2021-06-21T19%3A16%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 19:19 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +<!-- { "blockType": "ignored" } -->
Please include the block for API Doctor validation. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=set-up-for-api-doctor-in-an-api-topic

2021-05-21 19:28 UTC, opbld34 commented
Docs Build status updates of commit _[0681714](https://github.com/microsoftgraph/microsoft-graph-docs/commits/068171463f2ebd4705ea0a85c65cd694ca6b6d43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211927194551-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mJIkNhgkrahY6RZHRYZeEKfvJWYPg6maApDILIZjBsg%3D&st=2021-05-21T19%3A23%3A29Z&se=2021-06-21T19%3A28%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 19:44 UTC, opbld33 commented
Docs Build status updates of commit _[4a8c13d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a8c13de088aa13586afe995359b84b953fd5e1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211943021415-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Au3SllGRTF82SJs%2BdCqptzojAacRi14IUjta5aq4GhE%3D&st=2021-05-21T19%3A39%3A36Z&se=2021-06-21T19%3A44%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 20:33 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-get.md
> +description: " teachers and applications can see all assignments in a class."
Would you be so kind to update the description of this document? In the first paragraph we try to include a summary in a single sentence. In this case, please change line 16:

> Get the properties and relationships of an [assignment](link here). 
> (a blank line in between)
> Students can only see assignments assigned to them; teachers and applications with application permissions can see all assignments in a class.

And in line 3, please include the first sentence only (without the link):
Get the properties and relationships of an assignment.

I'd deeply appreciate if you can help me with this correction from previous iterations.

2021-05-21 20:51 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +Create a SharePoint resource folder for all file-based resources (of type Word, Excel, PowerPoint, or other accepted file format) for a given [educationAssignment](../resources/educationassignment.md
Line 14: I have my doubts with this one. We try to avoid using more than 2 nouns in a row (SharePoint resource folder, assignment level resources folder).
Would you be so kind to re-phrase this line? My suggestion:

> Create a SharePoint folder to upload files for a given [educationAssingment](thanks for the link). 
> (blank line here).
> The teacher determines the resources to upload in the assignment's folder. Include only [accepted file formats](is there a list of accepted formats?) such as docx, xlsx and pptx.
> 

Please let me hear your thoughts.

2021-05-21 20:52 UTC, isvargasmsft requested changes
Great work! Thank you for the quick response!

I am requesting your help with 2 additional corrections, for consistency purposes.

2021-05-21 21:02 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-setupresourcesfolder.md
> +Create a SharePoint resource folder for all file-based resources (of type Word, Excel, PowerPoint, or other accepted file format) for a given [educationAssignment](../resources/educationassignment.md
"Include only [accepted file formats](is there a list of accepted formats?) such as docx, xlsx and pptx."

If this last sentence is not necessary, I'd suggest removing it.

2021-05-21 21:16 UTC, opbld32 commented
Docs Build status updates of commit _[fa890d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa890d97c13e24c30b4691b4a0f46c0990bdd24a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212115444252-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n4oh7IHitjHbWa3x0iMbJZDfxUX%2BRe3jz%2BwK6qRDe%2Fk%3D&st=2021-05-21T21%3A11%3A58Z&se=2021-06-21T21%3A16%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:29 UTC, opbld31 commented
Docs Build status updates of commit _[6011cd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6011cd5f29d54ea84172d451a623d9814b442aac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212127346729-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=suB0Qz5%2B%2FLCGEF5OzMeQ0bYqGOPkvuM2fl6KgXdei%2FI%3D&st=2021-05-21T21%3A24%3A09Z&se=2021-06-21T21%3A29%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:33 UTC, isvargasmsft approved these changes
Great work, thank you for the quick response. 

Approved from my end.

2021-05-21 22:46 UTC, opbld34 commented
Docs Build status updates of commit _[348bfb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/348bfb6ec506fc3b387880535741fe5c79e849e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-getresourcesfolderurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-getresourcesfolderurl.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/resources/educationformresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationformresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationmakecoderesource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationmakecoderesource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationonenoteresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationonenoteresource.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/resources/educationsubmission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12795) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-beta-updates/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-12795) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212244471890-12795%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z9EFsyBxP8Q5D0NOsn5KJ8FtUkw83SgKWL%2BoEHZBaf4%3D&st=2021-05-21T22%3A41%3A09Z&se=2021-06-21T22%3A46%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 23:09 UTC, merged