Updating reporting endpoints
microsoftgraph/microsoft-graph-docs pull request #12791
Opened 2021-05-20 02:04 UTC by nilakhan

Taking forward Karan's change:

Rename daily and monthly user/printer usage report entities according to latest review with Graph
Rename periodStart and periodEnd arguments for retrieving archived jobs to startDateTime and endDateTime respectively.

2021-05-20 02:06 UTC, opbld34 commented
Docs Build status updates of commit _[d6f138d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6f138de9994b3507a0efc9b909e56a226c62d67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105200204589231-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RSmNqP%2Bz58TRjEjlq3ZcgyBskYM542%2BIqda2UQgJ66M%3D&st=2021-05-20T02%3A01%3A37Z&se=2021-06-20T02%3A06%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-20 16:07 UTC, braedenp-msft approved these changes

2021-05-24 18:15 UTC, opbld32 commented
Docs Build status updates of commit _[333028b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/333028bcb30947145e005db7c207c3372a056eb8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105241814392281-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PXQUUeZJD%2FBgGKaDs%2BRJP50x8ZkCxQ96vzbi3hjhh3U%3D&st=2021-05-24T18%3A10%3A58Z&se=2021-06-24T18%3A15%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-24 21:12 UTC, isvargasmsft commented on api-reference/beta/api/printusagebyprinter-get.md
> +Retrieve a [printer](../resources/printer.md)'s usage summary for a particular time period. For descriptions of each of the endpoints, see [printUsageByPrinter](../resources/printUsageByPrinter.md).
In general, we try to keep the first paragraph in a single sentence, so its easier to scan. Please include a blank line between the first and the second sentence:
- Retrieve a printer usage summary for a particular time period.
- (blank like here).
- For descriptions of each of the endpoints...

2021-05-24 21:26 UTC, isvargasmsft commented on api-reference/beta/api/printusagebyprinter-get.md
>  ##### Request
Line 52: Request and Response headings in the Examples sections should be H3. The exception is when there are multiple examples.

2021-05-24 21:27 UTC, isvargasmsft commented on api-reference/beta/api/printusagebyuser-get.md
>  ##### Request
Please use H3 headers here as well.

2021-05-24 21:28 UTC, isvargasmsft commented on api-reference/beta/api/printusagebyuser-get.md
> +Retrieve a user's usage summary for a particular time period. See the [printUsageByUser](../resources/printUsageByUser.md) documentation for descriptions of each of the endpoints.
Please include a blank between the 1st and 2nd sentences.

2021-05-24 22:32 UTC, isvargasmsft commented on api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md
>  ##### Request
Please use H3 headers for the Request and Response sections in the examples.

2021-05-24 22:33 UTC, isvargasmsft commented on api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md
>  ##### Request
H3 as well, please.

2021-05-24 22:36 UTC, isvargasmsft commented on changelog/Microsoft.PrintService.json
> +      "Id": "dc4d5c05-64f8-11eb-8de9-f7f8b8b7f046",
All elements in a single changelist should share the same GUID. Would you be so kind to use the same GUID across your Changelist, please?

2021-05-24 22:40 UTC, isvargasmsft requested changes
@nilakhan thank you very much for the careful update to this docs. Great work!
Just a couple of suggestions:
- Please use H3 headers for the Request and Response sections inside examples. 
- Please use a single GUID for all elements inside a ChangeList in the changelog. 

Thanks, 

Isaac Vargas

2021-05-24 22:41 UTC, opbld30 commented
Docs Build status updates of commit _[83ddfe3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83ddfe34b8e79a8a51b994a4b2b9380c11d9921e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105242240360978-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PB%2FMqAE3A0ATduFOjtHpDmrh6T4J7n%2FQVkQXVbIHRek%3D&st=2021-05-24T22%3A36%3A55Z&se=2021-06-24T22%3A41%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 00:34 UTC, opbld32 commented
Docs Build status updates of commit _[bc9ca9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc9ca9f7a81ee59576176b24548d6e391ec64eb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105250033175917-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FjVSGp5nqyLoSMzCAmr3WoBxIkOqeOS80o%2FdSzzMKhM%3D&st=2021-05-25T00%3A29%3A32Z&se=2021-06-25T00%3A34%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 00:38 UTC, opbld32 commented
Docs Build status updates of commit _[c38f7f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c38f7f70c52f97911db508102e034aa0e9ea80cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105250037244288-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bQMA0vNeaYPqbwn8eDtZ0DnsFPpjOHd%2F6yHdOO2PlW0%3D&st=2021-05-25T00%3A33%3A46Z&se=2021-06-25T00%3A38%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 16:59 UTC, opbld31 commented
Docs Build status updates of commit _[eaeb0b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaeb0b62ebe6387a464acbec93727473e799587c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105251658155349-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B9xHzxu8ZPthTxVvlrQxoz57I5X5rGZJAHlZT0Lbjck%3D&st=2021-05-25T16%3A54%3A34Z&se=2021-06-25T16%3A59%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 19:58 UTC, isvargasmsft commented on api-reference/beta/api/printusagebyprinter-get.md
> +GET https://graph.microsoft.com/beta/print/reports/dailyPrintUsageByPrinter/{id}
Would you be so kind to add a real looking ID to the examples? We try to use placeholders in the HTTP Request section above, but real looking data in the examples. 

It doesn't have to be a real ID, but one that looks like a real one. Once you do that, please include the SampleKeys attribute to the API Doctor block in lines 58 to 61. More details [here](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor):

> sampleKeys: Specify this for example HTTP requests that include one or more ID values indexing into collections in the request query. This property is a collection of strings, each string representing an ID value in the example request. For more information about specifying real ID values in examples, see the section ID values in example requests.

2021-05-25 20:11 UTC, isvargasmsft commented on api-reference/beta/api/printusagebyuser-get.md
> +GET https://graph.microsoft.com/beta/print/reports/dailyPrintUsageByUser/{id}
Same observation here. Sorry for not catching it in the first review. Please add real looking IDs to the examples and include sampleKeys attribute in the API Doctor block.

2021-05-25 20:19 UTC, isvargasmsft requested changes
Just a couple of additional changes. Please include real looking ID in the examples. 

Thank you very much!

2021-05-25 20:23 UTC, opbld33 commented
Docs Build status updates of commit _[0f65e8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f65e8e319bf2329c49b307bfa6b49e28a9013eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105252022110336-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K3wy7JBV9xSk3JlaXsnZmGcxIJX1vAblDf9R0dCTdnM%3D&st=2021-05-25T20%3A18%3A17Z&se=2021-06-25T20%3A23%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-26 22:58 UTC, opbld34 commented
Docs Build status updates of commit _[6f5d0c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f5d0c96039efc147ae6a0b38f103052737f6a3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105262257110405-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KgyYH9kuHWWam0DOCplCZa1SCKfe0vnUSHC5H4a4RZE%3D&st=2021-05-26T22%3A53%3A20Z&se=2021-06-26T22%3A58%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-26 22:59 UTC, opbld31 commented
Docs Build status updates of commit _[60dc59c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60dc59ce692c3ed7da89f5126bc79304e6528b7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105262258280480-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D%2F85ON6sL%2B6Lg4k5OS96T9LS1ipP%2Bkm7%2B66OvOPvIlU%3D&st=2021-05-26T22%3A54%3A57Z&se=2021-06-26T22%3A59%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-26 23:01 UTC, opbld32 commented
Docs Build status updates of commit _[0a2f7f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a2f7f94eed30aaa2109a6b7e9308425db1ae533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105262258468551-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mVCKWH1XNbGvyEukwZMVI3K%2FJc4TVwTdbOMwwaM1dqI%3D&st=2021-05-26T22%3A56%3A18Z&se=2021-06-26T23%3A01%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 00:51 UTC, nilakhan commented on api-reference/beta/api/printusagebyprinter-get.md
> +GET https://graph.microsoft.com/beta/print/reports/dailyPrintUsageByPrinter/{id}
Added

2021-05-27 00:51 UTC, opbld31 commented
Docs Build status updates of commit _[3c051b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c051b830a2482910c513422f967e8663ac3ad3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270050277288-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DE7QTBIS4ZH6eUBw2GyZnZhZEGAYKJWFPk5wQ0HTGAM%3D&st=2021-05-27T00%3A46%3A49Z&se=2021-06-27T00%3A51%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 00:53 UTC, opbld34 commented
Docs Build status updates of commit _[1fb6a8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fb6a8a621f1fcf0fcf6aea71358098b35450587)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270051238652-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pFhLraoH%2BaLt6rD3VKyXZBaVR8bHPqU0tKMHBq%2B0IgQ%3D&st=2021-05-27T00%3A48%3A15Z&se=2021-06-27T00%3A53%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 00:54 UTC, opbld33 commented
Docs Build status updates of commit _[5b03f8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b03f8b32672bf2a142c6c1523be63d8b12b76cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270053200959-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lpsyXMrZdRaI2warAqKRqA2JZ2N%2FigrfybVOqtSC5oc%3D&st=2021-05-27T00%3A49%3A33Z&se=2021-06-27T00%3A54%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 00:55 UTC, opbld34 commented
Docs Build status updates of commit _[5e31c50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e31c5070a3e8b4d9a5d3f0d43e65cf65100785f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270053448649-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iUfanN7u9QPSNm%2FDh1qUE8bB1fAB2AE4OSy1Oel5y6o%3D&st=2021-05-27T00%3A50%3A58Z&se=2021-06-27T00%3A55%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 16:00 UTC, opbld33 commented
Docs Build status updates of commit _[070c263](https://github.com/microsoftgraph/microsoft-graph-docs/commits/070c26357fe4015b6c3c063adde1f27f3b9d9604)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106011558560251-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gq4HK0FlHI5P721zMOyHkaQi38q5nvSHYa4qkNPK2rg%3D&st=2021-06-01T15%3A55%3A21Z&se=2021-07-02T16%3A00%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 02:56 UTC, Lauragra commented
@isvargasmsft , if this PR looks good on your end can you please approve? Thanks.

2021-06-04 01:00 UTC, opbld33 commented
Docs Build status updates of commit _[4530abd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4530abd454c77e07f856a41bae377183b05ff267)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106040058118542-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2%2FJjtratZif6K0M6iJiLfftnWP0T6wnlA2eZOsUJ9s8%3D&st=2021-06-04T00%3A55%3A05Z&se=2021-07-05T01%3A00%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 01:05 UTC, isvargasmsft approved these changes
Thank you very much! Great work!

2021-06-04 01:08 UTC, opbld32 commented
Docs Build status updates of commit _[d8dac82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8dac82ce28d1a2951917309f67e5287b84b9257)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-12791) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106040107138516-12791%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UvMNtpI31yBrr4xYb2TvN8hLLaIHSMz4YHKyUhron6Q%3D&st=2021-06-04T01%3A03%3A44Z&se=2021-07-05T01%3A08%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 01:29 UTC, merged