Document eventual consistency
microsoftgraph/microsoft-graph-docs pull request #12832
Opened 2021-05-21 18:12 UTC by FaithOmbongi

2021-05-21 18:15 UTC, opbld33 commented
Docs Build status updates of commit _[1626240](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1626240c9371d9129702fd2289a74cee607e27f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-12832) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-4f962c4b)
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) | [Details](#user-content-37a80c639bb3f2d728857a4d192fbc34-4f962c4b)
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) | [Details](#user-content-a29a10c0bb7991517fecc32cd9af1089-4f962c4b)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-4f962c4b)
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) | [Details](#user-content-ae623d2d4dda2083049001f9fd8794b7-4f962c4b)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |

<a id="b6c979e090f802360b5fb2b0e8db6f73-4f962c4b"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset.`````

<a id="37a80c639bb3f2d728857a4d192fbc34-4f962c4b"></a>
### [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md)
 - **Line 260, Column 210**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'search-query-parameter'.`````

<a id="a29a10c0bb7991517fecc32cd9af1089-4f962c4b"></a>
### [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md)
 - **Line 11, Column 16**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'query-parameters'.`````
 - **Line 169, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'query-parameters'.`````

<a id="f5822fe3902110f37fa319085bfe096b-4f962c4b"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

<a id="ae623d2d4dda2083049001f9fd8794b7-4f962c4b"></a>
### [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md)
 - **Line 39, Column 83**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/directoryrole?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211812421770-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xiYXwIYZpsRodpfit6zdT8Px1D993YTGItVuS6et2Ms%3D&st=2021-05-21T18%3A10%3A08Z&se=2021-06-21T18%3A15%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 18:28 UTC, opbld34 commented
Docs Build status updates of commit _[b476e0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b476e0b669cc86a6923d7c6982179e381acdce8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-12832) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-0d1fb086)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-0d1fb086)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |

<a id="b6c979e090f802360b5fb2b0e8db6f73-0d1fb086"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset.`````

<a id="f5822fe3902110f37fa319085bfe096b-0d1fb086"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211827337499-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GeHiAPuLLOHgxMrLpzx9WpUJsbLT3ZT97duxyfv01nk%3D&st=2021-05-21T18%3A23%3A38Z&se=2021-06-21T18%3A28%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 18:36 UTC, jasonjoh commented on api-reference/beta/resources/user.md
> +| accountEnabled | Boolean | `true` if the account is enabled; otherwise, `false`. This property is required when a user is created. <br><br>Supports `$filter` (`eq`,`in`) and `ne` operator only in e
What is "eventual consistency"? It's used repeatedly but I don't see anywhere in our docs where it's actually explained. The only thing I see is this in some docs:

```
| ConsistencyLevel | eventual. This header and `$count` are required when using the `$search`, `$filter`, `$orderby`, or OData cast query parameters. It uses an index that might not be up-to-date with recent changes to the object. |
```

Which I'm sure is what it refers to, but even then it seems very "hand-wavy".

2021-05-21 18:52 UTC, FaithOmbongi commented on api-reference/beta/resources/user.md
> +| accountEnabled | Boolean | `true` if the account is enabled; otherwise, `false`. This property is required when a user is created. <br><br>Supports `$filter` (`eq`,`in`) and `ne` operator only in e
I've introduced it in the query parameters doc. We're trying to find a good way to 
1. Introduce why the **ConsistencyLevel:eventual** header and **$count=true** query string are sometimes required.
2. Document properties & parameters that work only when 1 is fulfilled.

Still a WIP and your guidance is highly welcome.

2021-05-21 18:59 UTC, jasonjoh commented on api-reference/beta/resources/user.md
> +| accountEnabled | Boolean | `true` if the account is enabled; otherwise, `false`. This property is required when a user is created. <br><br>Supports `$filter` (`eq`,`in`) and `ne` operator only in e
Awesome. I don't have a good understanding of it myself so I'm not sure what to recommend. If it only applies to those query params, then it probably is OK to put in the query params doc. I'd put it in its own section with a heading so it could be deep-linked. Then you could convert those instances of `eventual consistency` to a link.

2021-05-21 19:00 UTC, jasonjoh commented on api-reference/beta/resources/user.md
> +| accountEnabled | Boolean | `true` if the account is enabled; otherwise, `false`. This property is required when a user is created. <br><br>Supports `$filter` (`eq`,`in`) and `ne` operator only in e
Oh and include an example maybe that illustrated the impact of using that header. It sounds like you might be searching against old data?

2021-05-22 00:08 UTC, Licantrop0 commented on api-reference/beta/resources/user.md
> +| accountEnabled | Boolean | `true` if the account is enabled; otherwise, `false`. This property is required when a user is created. <br><br>Supports `$filter` (`eq`,`in`) and `ne` operator only in e
I don't think specifying "on the Get user API (`GET /users/{ID}` or `/me`)" is necessary.

2021-05-22 00:26 UTC, Licantrop0 requested changes
this change requires a little more discussion. Let's sync.

2021-05-22 00:26 UTC, Licantrop0 commented on api-reference/beta/resources/user.md
> +| aboutMe | String | A freeform text entry field for the user to describe themselves. <br>Returned only on `$select` on the Get user API (`GET /users/{ID}` or `/me`). |
I don't think specifying "on the Get user API (`GET /users/{ID}` or `/me`)" is necessary.

2021-05-22 00:26 UTC, Licantrop0 commented on concepts/known-issues.md
> +* Query parameters specified in a request might fail silently. This can be true for unsupported query parameters as well as for unsupported combinations of query parameters.
This is only true for AAD workload.

2021-05-22 00:26 UTC, Licantrop0 commented on concepts/search-query-parameter.md
> +---
if we are going to make $search a separate page, maybe we should do it for all the other parameters for consistency?

2021-05-24 17:15 UTC, opbld32 commented
Docs Build status updates of commit _[6fc2754](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fc275439e039cdb142c999c372e02cdb4cd0da1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-12832) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-f31647ce)
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) | [Details](#user-content-37a80c639bb3f2d728857a4d192fbc34-f31647ce)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-f31647ce)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |

<a id="b6c979e090f802360b5fb2b0e8db6f73-f31647ce"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset.`````

<a id="37a80c639bb3f2d728857a4d192fbc34-f31647ce"></a>
### [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md)
 - **Line 117, Column 264**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#consistency-levels-and-query-parameters' in 'query-parameters.md'.`````
 - **Line 129, Column 187**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#consistency-levels-and-query-parameters' in 'query-parameters.md'.`````
 - **Line 186, Column 38**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#consistency-levels-and-query-parameters' in 'query-parameters.md'.`````
 - **Line 189, Column 104**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#consistency-levels-and-query-parameters' in 'query-parameters.md'.`````

<a id="f5822fe3902110f37fa319085bfe096b-f31647ce"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105241714254577-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eMdbml8XzIkqHS7ao7wdG8iKTURJAXSX3pJIrffryOo%3D&st=2021-05-24T17%3A10%3A43Z&se=2021-06-24T17%3A15%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-24 17:20 UTC, opbld31 commented
Docs Build status updates of commit _[a3f26ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3f26ecdc550b3473ecec5dd5d66429ac261b2c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-12832) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-ae716e3c)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-ae716e3c)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |

<a id="b6c979e090f802360b5fb2b0e8db6f73-ae716e3c"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset.`````

<a id="f5822fe3902110f37fa319085bfe096b-ae716e3c"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105241719101346-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KmNXEyUwTejDZmT%2F087v8Et2rdOHgInQbcaaq%2FZioJc%3D&st=2021-05-24T17%3A15%3A28Z&se=2021-06-24T17%3A20%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 09:12 UTC, opbld30 commented
Docs Build status updates of commit _[043b389](https://github.com/microsoftgraph/microsoft-graph-docs/commits/043b38953dae26bc899c3d6b1d8aa165b7bc00a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-73918265)

<a id="73918265"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105250911503877-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zi7KxVvj2AnFfopcrJK6QHe3BfTqiBDe9flDh070xjI%3D&st=2021-05-25T09%3A07%3A07Z&se=2021-06-25T09%3A12%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-26 15:01 UTC, opbld31 commented
Docs Build status updates of commit _[b903c4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b903c4a9a364aba67214d9bfa3bb4b182acb3f32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-12832) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-c3560c26)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-c3560c26)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |

<a id="b6c979e090f802360b5fb2b0e8db6f73-c3560c26"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset.`````

<a id="f5822fe3902110f37fa319085bfe096b-c3560c26"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105261500238361-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vMnu5zrtYFxm45aNsVL3%2F%2F3fQ3LmgUgLe48PU2aBgQg%3D&st=2021-05-26T14%3A56%3A42Z&se=2021-06-26T15%3A01%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 14:48 UTC, opbld33 commented
Docs Build status updates of commit _[7afd80b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7afd80b02304f312bfff088aab79b0da2f1cc1b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-fa927da7)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-fa927da7)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="83430e0b7d55c1f7666aae8731a7e700-fa927da7"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 13, Column 559**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#other-odata-url-capabilities' in 'aad-advanced-queries.md'.`````
 - **Line 70, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="f5822fe3902110f37fa319085bfe096b-fa927da7"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271447133262-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=46sCWjZ57vKn77JPZjmz99mOdV3LEe7dVqSTk24guBI%3D&st=2021-05-27T14%3A43%3A28Z&se=2021-06-27T14%3A48%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 15:37 UTC, opbld33 commented
Docs Build status updates of commit _[868046b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/868046b09e64fb2744d9c11c7b9a7c0c81c3e298)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-7b585af5)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-7b585af5)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-12832) (graph-rest-beta) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="83430e0b7d55c1f7666aae8731a7e700-7b585af5"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 13, Column 559**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'query-parameters'.`````

<a id="f5822fe3902110f37fa319085bfe096b-7b585af5"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271536388266-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TCpY6bVi15Z9QDEn14%2BHo9kft1SlmOP78jGOJbAyBz8%3D&st=2021-05-27T15%3A32%3A48Z&se=2021-06-27T15%3A37%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 18:06 UTC, opbld33 commented
Docs Build status updates of commit _[58610fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58610fec604e719d20b2e845c69b602268ba9a70)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-d0b6a5f8)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-d0b6a5f8"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271805202685-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uz6Urqq9ePk9I2Vafq0ZJJjokoV3oeLsjqIZmI08bZk%3D&st=2021-05-27T18%3A01%3A33Z&se=2021-06-27T18%3A06%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 18:13 UTC, FaithOmbongi commented on concepts/search-query-parameter.md
> +---
As agreed, only the $search and advanced query capabilities would be separate pages due to their many differences across resources.

2021-05-27 19:18 UTC, opbld32 commented
Docs Build status updates of commit _[75852d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75852d4534f3d7fda677bd2254cb429f0d8dbc8f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-cf538853)
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) | [Details](#user-content-37a80c639bb3f2d728857a4d192fbc34-cf538853)
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) | [Details](#user-content-a29a10c0bb7991517fecc32cd9af1089-cf538853)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-cf538853)
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="83430e0b7d55c1f7666aae8731a7e700-cf538853"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 53, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="37a80c639bb3f2d728857a4d192fbc34-cf538853"></a>
### [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md)
 - **Line 85, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 127, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 231, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="a29a10c0bb7991517fecc32cd9af1089-cf538853"></a>
### [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md)
 - **Line 15, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="f5822fe3902110f37fa319085bfe096b-cf538853"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271917192135-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AIehxCXck2sV0R0GNsFp%2BhpMIA%2BDyn91OoK5DuiIDZI%3D&st=2021-05-27T19%3A13%3A44Z&se=2021-06-27T19%3A18%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 06:26 UTC, opbld31 commented
Docs Build status updates of commit _[fec63c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fec63c627449c260aec9d968dd49c183dd817b49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-e10ae478)
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) | [Details](#user-content-37a80c639bb3f2d728857a4d192fbc34-e10ae478)
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) | [Details](#user-content-a29a10c0bb7991517fecc32cd9af1089-e10ae478)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-e10ae478)
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="83430e0b7d55c1f7666aae8731a7e700-e10ae478"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 61, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="37a80c639bb3f2d728857a4d192fbc34-e10ae478"></a>
### [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md)
 - **Line 85, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 127, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 231, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="a29a10c0bb7991517fecc32cd9af1089-e10ae478"></a>
### [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md)
 - **Line 15, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="f5822fe3902110f37fa319085bfe096b-e10ae478"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280625393005-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TeO8mDYqefbeICTj4%2F1kc3vpgxqh5cLD4M%2Bn8BWl2Gk%3D&st=2021-05-28T06%3A21%3A57Z&se=2021-06-28T06%3A26%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 06:36 UTC, opbld32 commented
Docs Build status updates of commit _[0893a92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0893a926fe896fe6f7b76b4104f7d6c815dd5f4c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-90a103ae)
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) | [Details](#user-content-37a80c639bb3f2d728857a4d192fbc34-90a103ae)
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) | [Details](#user-content-a29a10c0bb7991517fecc32cd9af1089-90a103ae)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-90a103ae)
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="83430e0b7d55c1f7666aae8731a7e700-90a103ae"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 61, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="37a80c639bb3f2d728857a4d192fbc34-90a103ae"></a>
### [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md)
 - **Line 85, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 127, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 231, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="a29a10c0bb7991517fecc32cd9af1089-90a103ae"></a>
### [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md)
 - **Line 15, Column 1**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

<a id="f5822fe3902110f37fa319085bfe096b-90a103ae"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280634536924-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FcczHxhaZvm49xs8%2FSa8FHIC5U3tvswvlz5ylvMpcjI%3D&st=2021-05-28T06%3A31%3A15Z&se=2021-06-28T06%3A36%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 20:44 UTC, Licantrop0 requested changes

2021-05-28 20:44 UTC, Licantrop0 commented on concepts/aad-advanced-queries.md
> +| Property                      |  eq   |  ne   |  ge   |  le   |  in   | startsWith | endsWith | null value |
@FaithOmbongi null value indexing is only supported with Advanced Queries.
for example, [this query](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3Dcountry%20eq%20null%26%24select%3Did%2CdisplayName%2Ccountry&method=GET&version=beta&GraphUrl=https://graph.microsoft.com) doesn't work without mezzo parameters.

We also need to find a way to indicate whenever the "null default value" is implemented (e.g. for accountEnabled all nulls fall back to 'false' value). Null indexing and Null default value are mutually exclusive and they can be represented in the same column.

2021-05-28 20:44 UTC, Licantrop0 commented on concepts/aad-advanced-queries.md
> +| accountEnabled                |   ⚪   |   ⚫   |   ⚫   |   ⚫   |   ⚪   |            |          |            |
using only colored dots is not a best practice for accessibility, can we find symbols that have different shapes? (also considering the 3rd one regarding null indexes / null default values.

2021-05-31 06:29 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +| accountEnabled                |   ⚪   |   ⚫   |   ⚫   |   ⚫   |   ⚪   |            |          |            |
Let me revisit the accessibility guidelines. I see [Azure DB docs use ticks](https://azure.microsoft.com/en-us/product-categories/databases/).

2021-06-07 19:18 UTC, opbld34 commented
Docs Build status updates of commit _[3dc6e24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dc6e240320cd765b247753cb5e9e1c445ac2882)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-d27986ce)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-d27986ce)
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="83430e0b7d55c1f7666aae8731a7e700-d27986ce"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 57, Column 80**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#support-for-the-filter-query-parameter-on-properties-of-azure-ad-directory-objects' in 'aad-advanced-queries.md'.`````
 - **Line 83, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

<a id="f5822fe3902110f37fa319085bfe096b-d27986ce"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071916335608-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=suBwmbAQJ4%2FvMjwX0WZe49u%2BZgz4vF6gzNhtZ8n%2B3kw%3D&st=2021-06-07T19%3A13%3A04Z&se=2021-07-08T19%3A18%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 19:22 UTC, opbld32 commented
Docs Build status updates of commit _[1c930dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c930dd5c0643935b626ad72b0cce12054c3f771)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-dac4f8fb)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-dac4f8fb)
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="83430e0b7d55c1f7666aae8731a7e700-dac4f8fb"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 57, Column 80**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#support-for-the-filter-query-parameter-on-properties-of-azure-ad-directory-objects' in 'aad-advanced-queries.md'.`````

<a id="f5822fe3902110f37fa319085bfe096b-dac4f8fb"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071920499993-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9Uu3tXWv4Y8sFONca%2FnOQsyPAKVai60KgRv6QXGmYcE%3D&st=2021-06-07T19%3A17%3A17Z&se=2021-07-08T19%3A22%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 19:34 UTC, opbld31 commented
Docs Build status updates of commit _[3848c38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3848c389e3d486d3ed75cd49c6808df0a41f6414)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-b8b59025)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-b8b59025"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071933232678-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kqDaPInvVtOh7K25rvykN1mXaH0JrmQX7s1hPpP0as0%3D&st=2021-06-07T19%3A29%3A56Z&se=2021-07-08T19%3A34%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 05:36 UTC, Licantrop0 requested changes

2021-06-08 05:36 UTC, Licantrop0 commented on concepts/aad-advanced-queries.md
> +| Property                      | eq | ne | NOT | ge | le | in | startsWith | endsWith | null values |
ne and NOT are **always** supported with advanced queries, probably not useful to call out in the table since we told in the line above?

2021-06-08 05:36 UTC, Licantrop0 commented on concepts/aad-advanced-queries.md
> +| Property                      | eq | ne | NOT | ge | le | in | startsWith | endsWith | null values |
we need to find a way to clarify when `$filter=property eq null` is supported
and when `$filter=property eq false` actually means false or null.

2021-06-08 05:36 UTC, Licantrop0 commented on concepts/aad-advanced-queries.md
> +
we should add a similar table for the orderBy support

2021-06-08 07:02 UTC, opbld30 commented
Docs Build status updates of commit _[b4b656e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4b656ece63247e01b10b0c1adc25ca34d90a52f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-c584d842)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/yes.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/yes.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/yes.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | |

<a id="f5822fe3902110f37fa319085bfe096b-c584d842"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106080701026329-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q8oGG0YEqa0JWRtn6jSxRj14j1FxNWbxi8Id2Oofdck%3D&st=2021-06-08T06%3A57%3A28Z&se=2021-07-09T07%3A02%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 15:54 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +
I think we can add that to the individual property descriptions.

2021-06-08 15:57 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +| Property                      | eq | ne | NOT | ge | le | in | startsWith | endsWith | null values |
We can discuss this further.

2021-06-08 16:16 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +| Property                      | eq | ne | NOT | ge | le | in | startsWith | endsWith | null values |
Anything to simplify the table and group shared scenarios would be good.

1. But, do all properties support NOT and ne?
2. Or, can we say a common rule is that all properties that support eq also support NOT and ne? With a note that ne cannot be used inside any/all clauses (hit this error when I tried)

2021-06-08 16:26 UTC, opbld33 commented
Docs Build status updates of commit _[f84421d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f84421d7abe4069a917d72ceb9dcbf5c196ecf8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-6982c26e)
[filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/filter-directory-objects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-03bd1431a164079d0e99933eff02519f-6982c26e)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-6982c26e)
[concepts/images/advanced-query-parameters/AQP.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/AQP.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/aqp.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | |

<a id="83430e0b7d55c1f7666aae8731a7e700-6982c26e"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 68, Column 3**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.' is duplicated. Within an article, alt text must be unique.`````

<a id="03bd1431a164079d0e99933eff02519f-6982c26e"></a>
### [filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/filter-directory-objects.md)
 - **Line 3, Column 173**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(3,173)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 3, Column 129**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(3,129)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 3, Column 85**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(3,85)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 4, Column 85**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(4,85)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 5, Column 135**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(5,135)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 6, Column 135**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(6,135)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 7, Column 135**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(7,135)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 8, Column 379**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(8,379)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 8, Column 85**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(8,85)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 9, Column 299**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(9,299)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 9, Column 255**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(9,255)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 9, Column 211**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/valid [...]

2021-06-08 16:31 UTC, opbld30 commented
Docs Build status updates of commit _[3b8e2ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b8e2efbbdcb665f7d188663ec16b2b5fb49e57c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-cf2edf35)
[filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/filter-directory-objects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-03bd1431a164079d0e99933eff02519f-cf2edf35)
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-cf2edf35)
[concepts/images/advanced-query-parameters/AQP.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/AQP.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/aqp.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | |

<a id="83430e0b7d55c1f7666aae8731a7e700-cf2edf35"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 68, Column 3**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.' is duplicated. Within an article, alt text must be unique.`````

<a id="03bd1431a164079d0e99933eff02519f-cf2edf35"></a>
### [filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/filter-directory-objects.md)
 - **Line 3, Column 173**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(3,173)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 3, Column 129**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(3,129)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 3, Column 85**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(3,85)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 4, Column 85**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(4,85)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 5, Column 135**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(5,135)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 6, Column 135**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(6,135)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 7, Column 135**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(7,135)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 8, Column 379**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(8,379)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 8, Column 85**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(8,85)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 9, Column 299**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(9,299)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 9, Column 255**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Requires Advanced Query Parameters.'(aad-advanced-queries.md(84,1) -> ../filter-directory-objects.md(9,255)) is duplicated. Within an article, alt text must be unique.`````
 - **Line 9, Column 211**: **[Warning-[duplicate-alt-text](https://review.docs.microsoft.com/help/contribute/valid [...]

2021-06-08 16:50 UTC, opbld32 commented
Docs Build status updates of commit _[96e28d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96e28d48c6b53267732ac3268166e5885298286e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-97e78ba2)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/AQP.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/AQP.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/aqp.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-97e78ba2"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106081648391848-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZmtqB8HpfTv0RQGKuELtALEvpzKTJ4TA98y8P5fTGKY%3D&st=2021-06-08T16%3A45%3A05Z&se=2021-07-09T16%3A50%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 17:55 UTC, opbld32 commented
Docs Build status updates of commit _[2db47aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2db47aa30026213ff19a1ea3f14fa4a3f671f11d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-c02d5950)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/AQP.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/AQP.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/aqp.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-c02d5950"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106081754039392-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q5hCRy%2Fe8pWrVS4el%2Bp9bmMYKDvxFWvDxYAxDL85Ndc%3D&st=2021-06-08T17%3A50%3A34Z&se=2021-07-09T17%3A55%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 18:10 UTC, opbld34 commented
Docs Build status updates of commit _[f117b01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f117b0198c41626249dc805a00a374ec6f2cd5ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-6ea98793)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/AQP.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/AQP.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/aqp.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-6ea98793"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106081809092358-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=htbcBsQHx4ATxkkT3pwnXUDvsWQeMpGdbMsjB4%2ByPxk%3D&st=2021-06-08T18%3A05%3A38Z&se=2021-07-09T18%3A10%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 18:21 UTC, opbld30 commented
Docs Build status updates of commit _[de34296](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de342961e55fb1be9dc81baad3e42a07de3cc8ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-2be363c6)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/AQP.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/AQP.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/aqp.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-2be363c6"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106081820007147-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BJaxslWsHXH3iWKPJ1E4OA2qauhYV%2BMHMYhE2X0lCAo%3D&st=2021-06-08T18%3A16%3A28Z&se=2021-07-09T18%3A21%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 19:03 UTC, opbld33 commented
Docs Build status updates of commit _[16a2888](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16a28885012546fd2a02f951bdc342f234900680)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-7a55d607)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/AQP.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/AQP.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/aqp.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-7a55d607"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106081902040462-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rOjqnrYWJ8YDZOh6aOY8q6b3%2FhK9R8fZcixTuPpuN1k%3D&st=2021-06-08T18%3A58%3A32Z&se=2021-07-09T19%3A03%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 19:31 UTC, davidmu1 commented on concepts/aad-advanced-queries.md
> +As Azure AD continues to deliver more capabilities and improvements in stability, availability, and performance, Microsoft Graph also continues to evolve and scale to efficiently access the data. One
"in October 2020" isn't needed.

2021-06-08 19:34 UTC, davidmu1 commented on concepts/aad-advanced-queries.md
> +Properties of directory objects behave differently in their support for query parameters. The following table summarizes support for `$filter` operators by properties on the [users](/graph/api/resour
We shouldn't include text that implies promises of future functionality: "Properties for other directory objects will be added soon."

2021-06-08 19:36 UTC, davidmu1 commented on concepts/aad-advanced-queries.md
> +- ![Requires Advanced Query Parameters.](/graph/images/advanced-query-parameters/AQP.png) The property supports `$filter` with the operator by default.
Since advanced query parameters isn't a brand name, I don't think the term should be capitalized.

2021-06-08 19:38 UTC, davidmu1 commented on concepts/aad-advanced-queries.md
> +> [!NOTE]
I don't think the note format is necessary. And the bullet items are not steps to complete so shouldn't be numbered.

2021-06-08 19:38 UTC, davidmu1 commented on concepts/aad-advanced-queries.md
> +Counting Directory Objects is only supported using the advanced queries parameters.
```suggestion
Counting directory objects is only supported using the advanced queries parameters.  
```

2021-06-08 19:44 UTC, davidmu1 commented on concepts/aad-advanced-queries.md
> +If the `ConsistencyLevel=eventual` header is not specified, the request will return an error in case raw count is used (`/$count` query segment) or silently ignoring the count parameter in case inlin
```suggestion
If the `ConsistencyLevel=eventual` header is not specified, the request returns an error when the $count segment is used or silently ignores the $count query parameter (?$count=true) if it's used.
```

2021-06-08 19:47 UTC, davidmu1 commented on concepts/query-parameters.md
> +> Use of `$count` is currently not supported in Azure AD B2C tenants.
```suggestion
> Use of `$count` is not supported in Azure AD B2C tenants.
```

2021-06-08 19:49 UTC, davidmu1 commented on concepts/query-parameters.md
> +> **Note:** If you're using OData Count (adding `$count=true` in the query string) for queries against directory objects, the `@odata.count` property will be present only in the first page.
```suggestion
> **Note:** If you're using OData Count (adding `$count=true` in the query string) for queries against directory objects, the `@odata.count` property is present only in the first page.
```

2021-06-09 10:24 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +> [!NOTE]
Well noted. The patterns have also grown from the origin 2.

2021-06-09 10:30 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +If the `ConsistencyLevel=eventual` header is not specified, the request will return an error in case raw count is used (`/$count` query segment) or silently ignoring the count parameter in case inlin
Added change in local branch.

2021-06-09 10:32 UTC, FaithOmbongi commented on concepts/aad-advanced-queries.md
> +As Azure AD continues to deliver more capabilities and improvements in stability, availability, and performance, Microsoft Graph also continues to evolve and scale to efficiently access the data. One
Was thinking of this in the context of "improvements, evolution, and scalability" pointed out in the 1st sentence.

2021-06-09 11:42 UTC, opbld33 commented
Docs Build status updates of commit _[0a8bce9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a8bce95be3bf64b6d5874d942e5e46e96d21338)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-aae3cd1a)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-aae3cd1a)
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-aae3cd1a"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

<a id="83430e0b7d55c1f7666aae8731a7e700-aae3cd1a"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 49, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106091141171783-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G4k1Pj2stVOalEVshL3wD8%2FucC%2FLJPJd1KvNo0z24Pg%3D&st=2021-06-09T11%3A37%3A46Z&se=2021-07-10T11%3A42%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 12:43 UTC, opbld33 commented
Docs Build status updates of commit _[228b9f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/228b9f071649a2c9435a190eb7ed2d573b277e97)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-5fd7b81f)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-5fd7b81f)
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-5fd7b81f"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

<a id="83430e0b7d55c1f7666aae8731a7e700-5fd7b81f"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 49, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106091241507599-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kEnBBMQmGAQ3%2F5TL1%2FRNfkEGQtUTNlVXTJs3cx35we8%3D&st=2021-06-09T12%3A38%3A12Z&se=2021-07-10T12%3A43%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 11:31 UTC, opbld33 commented
Docs Build status updates of commit _[98b8a93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98b8a93f6a3fb4759e18c1ef7fef25668874d163)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-ce97f7c5)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-ce97f7c5)
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-ce97f7c5"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

<a id="83430e0b7d55c1f7666aae8731a7e700-ce97f7c5"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 49, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101128549822-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LRc9ZrIUqRYkO2tCa%2F12uXgYw7DFRJ5epaJ7Bc6ZYNA%3D&st=2021-06-10T11%3A26%3A15Z&se=2021-07-11T11%3A31%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 11:41 UTC, opbld32 commented
Docs Build status updates of commit _[304c932](https://github.com/microsoftgraph/microsoft-graph-docs/commits/304c932b1e889b6501f56541e17b3c9528dbd590)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-135f1ba2)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) | [Details](#user-content-83430e0b7d55c1f7666aae8731a7e700-135f1ba2)
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-135f1ba2"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

<a id="83430e0b7d55c1f7666aae8731a7e700-135f1ba2"></a>
### [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md)
 - **Line 49, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101139377232-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0ZSJzfemBGJNGv0FnWpa6ZL8Rt2ZdFCT9pDYAEL4fmQ%3D&st=2021-06-10T11%3A36%3A11Z&se=2021-07-11T11%3A41%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 11:46 UTC, opbld31 commented
Docs Build status updates of commit _[f709c62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f709c62d10d48cc7a85144fdde8ba99cd294480a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-56dcd81f)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-56dcd81f"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101144482632-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=plLfk0KCFPjdyQKYKd8pOw53eW2CuB1tRTmbG4y8fXQ%3D&st=2021-06-10T11%3A41%3A22Z&se=2021-07-11T11%3A46%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 19:03 UTC, opbld33 commented
Docs Build status updates of commit _[4c56a70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c56a70b30ba532e2b66b26c99be1328e23aade0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-a4fac8e4)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-a4fac8e4"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101901347620-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5xeHLatwrSVaUnmWqi27H%2F9Z17yyDH5fHaocbsv%2F3yU%3D&st=2021-06-10T18%3A58%3A39Z&se=2021-07-11T19%3A03%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 19:35 UTC, opbld32 commented
Docs Build status updates of commit _[b4e2370](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4e2370baf94b23c3aa7bef8768851147dfe4c63)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-2f17e2d5)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-2f17e2d5"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101934035273-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y4Jy66tdwbghg5UuDYjIgI0RpMMYC%2FIEmmF5VAUZDsI%3D&st=2021-06-10T19%3A30%3A56Z&se=2021-07-11T19%3A35%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 10:54 UTC, opbld34 commented
Docs Build status updates of commit _[8359397](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83593974d69902e5a99012eb9bf809512d46f6aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-7ef97e9c)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-7ef97e9c"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-search-on-directory-object-collections' in 'query-parameters.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106111051374163-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F8tT8Kfel%2Bdch0K4kEIVTz3YI003EpJxzWh16C8qEXA%3D&st=2021-06-11T10%3A49%3A09Z&se=2021-07-12T10%3A54%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 10:54 UTC, FaithOmbongi commented on api-reference/beta/resources/user.md
> +| accountEnabled | Boolean | `true` if the account is enabled; otherwise, `false`. This property is required when a user is created. <br><br>Supports `$filter` (`eq`,`in`) and `ne` operator only in e
Moving the explanation of consistency levels in Azure AD to another PR/topic. This PR is now only for advanced query capabilities on directory objects.

2021-06-14 20:12 UTC, davidmu1 commented on concepts/aad-advanced-queries.md
> +1. Use the `$filter` query parameter with the `eq` operator. This request will work by default, that is, the request does not require the advanced query parameters.
These should not be numbered. Numbering implies a sequential order of operation.

2021-06-14 20:13 UTC, davidmu1 approved these changes

2021-06-15 09:35 UTC, opbld32 commented
Docs Build status updates of commit _[f7204b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7204b7a8cca73f2e64106f4f6be2cc8412a4cdb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) | [Details](#user-content-f5822fe3902110f37fa319085bfe096b-a08cac52)
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

<a id="f5822fe3902110f37fa319085bfe096b-a08cac52"></a>
### [concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md)
 - **Line 782, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './search-query-parameter'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150934180274-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VMXXw8YVJlAj7N4CmwtkgpVJSSwnEkSVSp1l27MAdm8%3D&st=2021-06-15T09%3A30%3A38Z&se=2021-07-16T09%3A35%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 14:18 UTC, opbld31 commented
Docs Build status updates of commit _[2ced577](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ced577f951faa1f88c1c49c0b859a13c5f2a41a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151417168303-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x3f7upNx16XaX3Rs9e1wKKrX%2FIa3u2%2BvZ6Ejy34ffFc%3D&st=2021-06-15T14%3A13%3A33Z&se=2021-07-16T14%3A18%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 14:14 UTC, opbld31 commented
Docs Build status updates of commit _[e574d1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e574d1b7785d8cd5d000c03fa9815ad2e99e3a62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/aad-advanced-queries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/advanced.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/advanced.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/advanced.png?branch=pr-en-us-12832) |
[concepts/images/advanced-query-parameters/default.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/images/advanced-query-parameters/default.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/advanced-query-parameters/default.png?branch=pr-en-us-12832) |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-12832) |
[concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/paging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/paging?branch=pr-en-us-12832) |
[concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/query-parameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-12832) |
[concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/search-query-parameter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-query-parameter?branch=pr-en-us-12832) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |
[concepts/whats-new-earlier.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/concepts/whats-new-earlier.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-earlier?branch=pr-en-us-12832) |
[includes/filter-directory-objects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/advancedQuerying/includes/filter-directory-objects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/aad-advanced-queries?branch=pr-en-us-12832) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161413276797-12832%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GU2I5lX1ZzrJfrJgI1dL5%2FERnj%2BhOqfruzI1sNPzQ0E%3D&st=2021-06-16T14%3A09%3A53Z&se=2021-07-17T14%3A14%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-19 00:49 UTC, merged