Documents scopes in Microsoft Graph Toolkit components
microsoftgraph/microsoft-graph-docs pull request #12857
Opened 2021-05-25 13:41 UTC by waldekmastykarz

Documents scopes in Microsoft Graph Toolkit components. Closes https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/720

2021-05-25 13:42 UTC, opbld30 commented
Docs Build status updates of commit _[46ffc1b](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/46ffc1bf1a817d797351c96a4c992bbd307199df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/tasks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12857) | [Details](#user-content-a38868362734ab4ed78dd093018407e4-f38ddad2)
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/person.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12857) | [Details](#user-content-ff167cedaf2a45415fb1483626f22995-f38ddad2)
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/todo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12857) | [Details](#user-content-a83e0148535313be5d55d1ca43c5e707-f38ddad2)
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12857) |
[concepts/toolkit/components/file-list.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12857) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12857) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12857) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12857) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12857) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12857) |

<a id="a38868362734ab4ed78dd093018407e4-f38ddad2"></a>
### [concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/tasks.md)
 - **Line 154, Column 288**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/plannerplan-list-tasks'.`````
 - **Line 156, Column 289**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/plannerplan-list-tasks'.`````
 - **Line 157, Column 253**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/plannerplan-list-tasks'.`````
 - **Line 154, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannergroup-list-plans?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 154, Column 185**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 154, Column 288**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 155, Column 76**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-list-taskgroups?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 155, Column 205**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlooktaskfolder-list-tasks?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 155, Column 326**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlooktaskfolder-list-tasks?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 100**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-get?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 186**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to [...]

2021-05-25 19:06 UTC, waldekmastykarz commented
@nmetulev, @elisenyang could you please review the PR? 🙂

2021-06-02 16:32 UTC, beth-panx requested changes
Great work! Thanks for helping with the revamp of this. It's going to be so much easier for developers to understand the association of properties and permissions.
I pulled up preview and compared permissions to the docs link, found some differences and broken links.

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/people-picker.md
> +| `group-id` set | People.Read, User.Read.All | [/groups/\${groupId}/members](/graph/api/group-list-members) |
Seems like this should be Group.Read.All based on [this function](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/87be56d08cfd3688c08a8c13841086e060f4899e/packages/mgt-components/src/graph/graph.groups.ts#L249) which matches the docs link.
```suggestion
| `group-id` set | Group.Read.All | [/groups/\${groupId}/members](/graph/api/group-list-members) |
```

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/people-picker.md
> +| `type` set to `Group` or searching for users and `type` set to `Group` or `any` | Group.Read.All | [/groups](/group-list) |
broken link

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/people.md
Remove mgt-person permissions for consistency of change.

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo`, retrieved person is a contact and `useContactApis` set to `true` | Contacts.Read | [/me/contacts/\*](/gra
broken link

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo` and person is not a contact or `useContactApis` is set to `false` | User.ReadBasic.All | [/users/{id}/phot
Wrong link to get photo. Should it be this one /graph/api/profilephoto-get ?

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo` and user specified via email | User.ReadBasic.All | [/users/{id}/photo/$value](/graph/api/user-list-people
Wrong link to get photo. Should it be this one /graph/api/profilephoto-get ?

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo` and contact specified via email | Contacts.Read | [/me/contacts/\*](/graph/api/user-list-contacts&tabs=cs)
broken link

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/person.md
> +| `userId` set | User.ReadBasic.All | | [/users/{id}](/graph/api/user-list-people) |
extra column
```suggestion
| `userId` set | User.ReadBasic.All | [/users/{id}](/graph/api/user-list-people) |
```

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/person.md
> +| `personQuery` set to a value other than `me` and `useContactApis` set to `true` | People.Read, User.ReadBasic.All, Contacts.Read | [/me/people/?$search=](/graph/api/user-list-people), [/users?$sear
broken link for contact
also not sure if the /user?search= reference is correct, should it be /graph/api/user-list instead?

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/person.md
> +| `personQuery` set to a value other than `me` and `useContactApis` set to `false` | People.Read, User.ReadBasic.All | [/me/people/?$search=](/graph/api/user-list-people), [/users?$search=](/graph/ap
not sure if the /user?search= reference is correct, should it be /graph/api/user-list instead?

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/tasks.md
> +| `groupId` set and `dataSource` set to `TasksSource.planner` | Group.Read.All | [/groups/${group-id}/planner/plans](/graph/api/plannergroup-list-plans?view=graph-rest-1.0&tabs=http), [/planner/plans
last link is broken [/planner/buckets/${bucketId}/tasks](graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=http)

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/tasks.md
> +| `targetId` set and `dataSource` set to something else than `TasksSource.todo` | Group.Read.All | [/planner/plans/${planId}](/graph/api/plannerplan-get?view=graph-rest-1.0&tabs=http), [/planner/plan
same here, last link is broken [/planner/buckets/${bucketId}/tasks](graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=http)

2021-06-02 16:32 UTC, beth-panx commented on concepts/toolkit/components/tasks.md
> +| `dataSource` set to `TasksSource.planner` | Group.Read.All | [/me/planner/plans](/graph/api/planneruser-list-plans?view=graph-rest-1.0&tabs=http), [/planner/plans/${planId}/buckets](/graph/api/plan
same here, last link is broken [/planner/buckets/${bucketId}/tasks](graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=http)

2021-06-03 06:56 UTC, waldekmastykarz commented
Thank you for such a thorough review @beth-panx and sorry for missing the broken links. Should've checked better.

2021-06-03 07:00 UTC, waldekmastykarz commented on concepts/toolkit/components/people-picker.md
> +| `group-id` set | People.Read, User.Read.All | [/groups/\${groupId}/members](/graph/api/group-list-members) |
Looking at the code, it seems like when you set `groupId`, we call `findGroupMembers` which requires the scopes I mentioned:

https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/87be56d08cfd3688c08a8c13841086e060f4899e/packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts#L789-L792

https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/87be56d08cfd3688c08a8c13841086e060f4899e/packages/mgt-components/src/graph/graph.user.ts#L322

2021-06-03 07:03 UTC, waldekmastykarz commented on concepts/toolkit/components/people-picker.md
> +| `type` set to `Group` or searching for users and `type` set to `Group` or `any` | Group.Read.All | [/groups](/group-list) |
Fixed

2021-06-03 07:04 UTC, waldekmastykarz commented on concepts/toolkit/components/people.md
Adjusted.

2021-06-03 07:05 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo`, retrieved person is a contact and `useContactApis` set to `true` | Contacts.Read | [/me/contacts/\*](/gra
Fixed

2021-06-03 07:06 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo` and person is not a contact or `useContactApis` is set to `false` | User.ReadBasic.All | [/users/{id}/phot
You're right. Adjusted

2021-06-03 07:06 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo` and user specified via email | User.ReadBasic.All | [/users/{id}/photo/$value](/graph/api/user-list-people
Fixed

2021-06-03 07:06 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `personDetails` set without image, `fetchImage` set to `true`, `avatarType` set to `photo` and contact specified via email | Contacts.Read | [/me/contacts/\*](/graph/api/user-list-contacts&tabs=cs)
Fixed

2021-06-03 07:07 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `userId` set | User.ReadBasic.All | | [/users/{id}](/graph/api/user-list-people) |
Removed

2021-06-03 07:11 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `personQuery` set to a value other than `me` and `useContactApis` set to `true` | People.Read, User.ReadBasic.All, Contacts.Read | [/me/people/?$search=](/graph/api/user-list-people), [/users?$sear
So this is coming from https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/87be56d08cfd3688c08a8c13841086e060f4899e/packages/mgt-components/src/components/mgt-person/mgt-person.ts#L986 where we call `findUsers` which does `/users?$search` https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/87be56d08cfd3688c08a8c13841086e060f4899e/packages/mgt-components/src/graph/graph.user.ts#L288-L291

2021-06-03 07:11 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `personQuery` set to a value other than `me` and `useContactApis` set to `true` | People.Read, User.ReadBasic.All, Contacts.Read | [/me/people/?$search=](/graph/api/user-list-people), [/users?$sear
Link for contact fixed

2021-06-03 07:12 UTC, waldekmastykarz commented on concepts/toolkit/components/person.md
> +| `personQuery` set to a value other than `me` and `useContactApis` set to `false` | People.Read, User.ReadBasic.All | [/me/people/?$search=](/graph/api/user-list-people), [/users?$search=](/graph/ap
This is coming from https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/87be56d08cfd3688c08a8c13841086e060f4899e/packages/mgt-components/src/components/mgt-person/mgt-person.ts#L986 where we call findUsers which does /users?$search https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/87be56d08cfd3688c08a8c13841086e060f4899e/packages/mgt-components/src/graph/graph.user.ts#L288-L291

2021-06-03 07:13 UTC, waldekmastykarz commented on concepts/toolkit/components/tasks.md
> +| `groupId` set and `dataSource` set to `TasksSource.planner` | Group.Read.All | [/groups/${group-id}/planner/plans](/graph/api/plannergroup-list-plans?view=graph-rest-1.0&tabs=http), [/planner/plans
Fixed

2021-06-03 07:13 UTC, waldekmastykarz commented on concepts/toolkit/components/tasks.md
> +| `targetId` set and `dataSource` set to something else than `TasksSource.todo` | Group.Read.All | [/planner/plans/${planId}](/graph/api/plannerplan-get?view=graph-rest-1.0&tabs=http), [/planner/plan
Fixed

2021-06-03 07:14 UTC, waldekmastykarz commented on concepts/toolkit/components/tasks.md
> +| `dataSource` set to `TasksSource.planner` | Group.Read.All | [/me/planner/plans](/graph/api/planneruser-list-plans?view=graph-rest-1.0&tabs=http), [/planner/plans/${planId}/buckets](/graph/api/plan
Fixed

2021-06-03 07:16 UTC, opbld32 commented
Docs Build status updates of commit _[425fd40](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/425fd40cf7dfa107937ea1b8f4ba7ff12c9905cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12857) | [Details](#user-content-a38868362734ab4ed78dd093018407e4-2ffdaf7d)
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/todo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12857) | [Details](#user-content-a83e0148535313be5d55d1ca43c5e707-2ffdaf7d)
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12857) |
[concepts/toolkit/components/file-list.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12857) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12857) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12857) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12857) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12857) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12857) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12857) |

<a id="a38868362734ab4ed78dd093018407e4-2ffdaf7d"></a>
### [concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/tasks.md)
 - **Line 154, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannergroup-list-plans?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 154, Column 185**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 154, Column 288**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 155, Column 76**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-list-taskgroups?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 155, Column 205**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlooktaskfolder-list-tasks?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 155, Column 326**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlooktaskfolder-list-tasks?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 100**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-get?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 186**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 289**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-vi [...]

2021-06-03 17:03 UTC, beth-panx commented
> Thank you for such a thorough review @beth-panx and sorry for missing the broken links. Should've checked better.

Oh no worries! That's why we have reviews haha. Thanks for making this change!

2021-06-03 17:04 UTC, beth-panx approved these changes
🚀

2021-06-03 17:05 UTC, opbld33 commented
Docs Build status updates of commit _[2592938](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/25929387ebb46c4ee01d6ad12fe8da56f34c246d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/tasks?branch=pr-en-us-12857) | [Details](#user-content-a38868362734ab4ed78dd093018407e4-44bdeaae)
[concepts/toolkit/components/todo.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/todo.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-12857) | [Details](#user-content-a83e0148535313be5d55d1ca43c5e707-44bdeaae)
[concepts/toolkit/components/agenda.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/agenda.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/agenda?branch=pr-en-us-12857) |
[concepts/toolkit/components/file-list.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/file-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/file-list?branch=pr-en-us-12857) |
[concepts/toolkit/components/get.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/get?branch=pr-en-us-12857) |
[concepts/toolkit/components/login.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/login.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/login?branch=pr-en-us-12857) |
[concepts/toolkit/components/people-picker.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/people-picker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people-picker?branch=pr-en-us-12857) |
[concepts/toolkit/components/people.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/people.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/people?branch=pr-en-us-12857) |
[concepts/toolkit/components/person-card.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/person-card.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person-card?branch=pr-en-us-12857) |
[concepts/toolkit/components/person.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/person?branch=pr-en-us-12857) |

<a id="a38868362734ab4ed78dd093018407e4-44bdeaae"></a>
### [concepts/toolkit/components/tasks.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-scopes/concepts/toolkit/components/tasks.md)
 - **Line 154, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannergroup-list-plans?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 154, Column 185**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 154, Column 288**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 155, Column 76**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlookuser-list-taskgroups?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 155, Column 205**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlooktaskfolder-list-tasks?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 155, Column 326**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/outlooktaskfolder-list-tasks?view=graph-rest-beta&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 100**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-get?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 186**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=http. Otherwise, remove the view parameter.`````
 - **Line 156, Column 289**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-vi [...]

2021-06-04 00:32 UTC, merged