[Teams] Install app during chat creation
microsoftgraph/microsoft-graph-docs pull request #12866
Opened 2021-05-25 17:31 UTC by jessiechan27

2021-05-25 17:35 UTC, opbld32 commented
Docs Build status updates of commit _[eb6391a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb6391a965d427b7e4d2ecb8009d77709b34e857)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) | [Details](#user-content-6953476485db05786767bf6587b1a233-5cf75845)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-5cf75845)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5cf75845)
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |

<a id="6953476485db05786767bf6587b1a233-5cf75845"></a>
### [api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md)
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/team-list-permissiongrants.md'.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-5cf75845"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/team.md)
 - **Line 46, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/team-list-permissiongrants.md'.`````
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

<a id="0817dce4456c16725d5333633847d38f-5cf75845"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml)
 - **Line 13312, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/team-list-permissiongrants.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105251733493241-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gCyYQA%2FddXXPgx%2BRDmWYSa0hJXgCsw9JnGtpE5QWMoE%3D&st=2021-05-25T17%3A30%3A20Z&se=2021-06-25T17%3A35%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 17:41 UTC, opbld33 commented
Docs Build status updates of commit _[7713d3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7713d3ba6d9a80876897a48570245f5696a8609c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105251740019750-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qP6%2FgvRd1F1g13cgceQTggV7WU%2Bos122oM2shOTWvyU%3D&st=2021-05-25T17%3A36%3A18Z&se=2021-06-25T17%3A41%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 18:25 UTC, AkJo commented on api-reference/beta/api/chat-post.md
> +      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/05F59CEC-A742-4A50-A62E-202A57E478A4"
Did you try this out?

It does not seem right.

IIRC, it should be 
installedApps": [
      {"teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"}
      ]

<!--StartFragment-->installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"<!--EndFragment-->



<!--StartFragment-->installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"<!--EndFragment-->



<!--StartFragment-->installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"<!--EndFragment-->



<!--StartFragment-->installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"<!--EndFragment-->



<!--StartFragment-->installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"<!--EndFragment-->



<!--StartFragment-->installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/12345678-9abc-def0-123456789a"<!--EndFragment-->




<!--StartFragment--> "installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/05F59CEC-A742-4A50-A62E-202A57E478A4"<!--EndFragment-->



<!--StartFragment-->"installedApps": [      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/05F59CEC-A742-4A50-A62E-202A57E478A4"<!--EndFragment-->

2021-05-25 18:30 UTC, eddie-lee-msft commented
When the request includes the 'installedApps' field and the request is successful, it will not return 201, but a 202 along with a Graph path like '/chats('chat-id')/operations('operation-id')' in the response headers. Please include this information too. It may also help to include a completely separate, third example to illustrate this instead of putting in the first and second examples.

2021-05-25 18:33 UTC, jessiechan27 commented on api-reference/beta/api/chat-post.md
> +      "teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/05F59CEC-A742-4A50-A62E-202A57E478A4"
o u right. I'll try it out next time

2021-05-26 00:35 UTC, opbld33 commented
Docs Build status updates of commit _[e65c8a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e65c8a90119c503a3536f5d18f0382dfb4941a4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105260034316782-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bkSyJK%2B86qyrLnPp4U1mE%2BXf9tVU5Rp6wQwr%2BJ9tuDs%3D&st=2021-05-26T00%3A30%3A50Z&se=2021-06-26T00%3A35%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 18:59 UTC, opbld33 commented
Docs Build status updates of commit _[98c3b7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98c3b7bc108acc385aea20ece63a6194239e1fce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271858181016-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qt%2BTRQiI3JHm5e3w%2BU7mEfz3iyEsN8rQ3iy7Suqlq24%3D&st=2021-05-27T18%3A54%3A37Z&se=2021-06-27T18%3A59%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 00:07 UTC, opbld30 commented
Docs Build status updates of commit _[4557710](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4557710e279dc4b74637d0252dada606a8c9fb84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280006063372-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oWyVrxXqcFbFpsImmnjH45kJ2nTImmbAjt9VLoPQo%2Bk%3D&st=2021-05-28T00%3A02%3A30Z&se=2021-06-28T00%3A07%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 00:14 UTC, opbld33 commented
Docs Build status updates of commit _[5e957f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e957f73bb143c31e3b1b92a254bba83a7476ed3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280012422197-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7tXDuEPc46eegwUSRHe4Ffom%2F8AkRAFx4gZvUYPZRSA%3D&st=2021-05-28T00%3A09%3A05Z&se=2021-06-28T00%3A14%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 00:46 UTC, opbld34 commented
Docs Build status updates of commit _[e5ef24d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5ef24d7d16fae8b5cca323429f0a1c21a7c6a00)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-3d539fd9)
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-3d539fd9"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/toc.yml)
 - **Line 3694, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/educationroot-list-schools.md'.`````
 - **Line 3696, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/educationroot-post-schools.md'.`````
 - **Line 3721, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/educationroot-list-classes.md'.`````
 - **Line 3723, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/educationroot-post-classes.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280045238834-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bFEi%2FzYQ%2BWZ8JqE2F1JOssFqez1GVJ9FoqHt8LVaTZQ%3D&st=2021-05-28T00%3A41%3A43Z&se=2021-06-28T00%3A46%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 00:51 UTC, opbld33 commented
Docs Build status updates of commit _[7c82408](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c824087544f47515820196a243436ca5acaa0be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280050182852-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=raFgc6PXE0cQMHhAlF43mJ6HgdwKOlWsK2JctuU3I9c%3D&st=2021-05-28T00%3A46%3A41Z&se=2021-06-28T00%3A51%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 02:52 UTC, opbld34 commented
Docs Build status updates of commit _[257bcaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/257bcaa0e67b9bf8ef472b15ed893b171da54e0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280250363904-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oCsrUTHeVS3ijvkOqZBzC38AVY2xtAWGuCGjOxdBtJQ%3D&st=2021-05-28T02%3A47%3A00Z&se=2021-06-28T02%3A52%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 18:52 UTC, AkJo commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
Clear out the subarea.

2021-05-29 00:15 UTC, opbld30 commented
Docs Build status updates of commit _[40e01a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40e01a34093df6eb7e1adc99cd57e1574aabe816)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290013290914-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9ZLSTwXd5jgsFw4Buv6dj40x%2FymtJqs8PA0CR2epWA4%3D&st=2021-05-29T00%3A10%3A48Z&se=2021-06-29T00%3A15%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 08:44 UTC, AkJo commented on api-reference/beta/api/chat-post.md
> +If the request includes apps to install and the request is successful, this method returns a `202 Accepted` response code. The response will also contain a Location header, which contains a link to t
@Lauragra, can you please confirm that this is the right format.

2021-06-11 08:44 UTC, AkJo approved these changes

2021-06-14 17:04 UTC, opbld31 commented
Docs Build status updates of commit _[8c7b003](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c7b003301b119e5e84461a31182cf03481550fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141703086728-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z6fHvdzNsCe7LDtVEAwpFqqpT2l1TLINRBZhQiNVkWY%3D&st=2021-06-14T16%3A59%3A41Z&se=2021-07-15T17%3A04%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 21:33 UTC, JarbasHorst requested changes

2021-06-14 21:33 UTC, JarbasHorst commented on api-reference/beta/resources/chat.md
> +|[List operations on chat](../api/chat-list-operations.md) | [teamsAsyncOperation](teamsAsyncOperation.md) collection | Get the list of async operations that ran or are running on this team.|
According to the description available in the teamsasyncoperation article, the description for *List operations on chat* should be "on the chat" instead of "on this team".

2021-06-14 21:33 UTC, JarbasHorst commented on api-reference/beta/resources/chat.md
> +|[Get operation on chat](../api/chat-get-operation.md) | [teamsAsyncOperation](teamsAsyncOperation.md) | Get a single async operation that ran or is running on this team.|
According to the description available in the teamsasyncoperation article, the description for *Get operation on chat* should be "on the chat" instead of "on this team".

2021-06-14 21:33 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **operations** relationship to [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) resource.",
Please, remove `en-us` from the link you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-14 21:33 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "2be0f907-b973-4695-8792-380f383d9779",
This PR doesn't include your changes applied to the teamsAsyncOperationType file. Did you forget to commit this change?

2021-06-14 21:33 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +      "ChangeList": [
The ChangeList doesn't contain the new methods you have added to the chat resource: chat-list-operations.md and chat-get-operation.md. Can you please update the ChangeList accordingly?

2021-06-14 21:33 UTC, JarbasHorst commented on api-reference/beta/api/chat-post.md
> +
Please, add an H3 heading here to explain the relationship of the paragraph below and the use case scenario. Suggested revision:

\#\#\# Response for creating a one-on-one chat with installed apps

2021-06-14 21:35 UTC, Lauragra commented on api-reference/beta/api/chat-get-operation.md
> +title: "Get operation on a chat"
The nav property name is plural, "operations", so  it should be plural in the file name, title, and H1. Unless it would be sufficient in this case to have a topic teamsasyncoperation-get?

2021-06-14 22:26 UTC, jessiechan27 commented on changelog/Microsoft.Teams.Core.json
> +      "ChangeList": [
those are not new operations I added. I was just adding missing documentation for them

2021-06-14 22:28 UTC, jessiechan27 commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "2be0f907-b973-4695-8792-380f383d9779",
It says "Added the **createChat** member to the **teamsAsyncOperationType** enumeration" here in the changelog. I didn't make any other changes to teamsAsyncOperationType

2021-06-14 22:31 UTC, jessiechan27 commented on api-reference/beta/api/chat-get-operation.md
> +title: "Get operation on a chat"
This is only getting a single operation because the path is operations/{operation-id}

2021-06-14 22:40 UTC, jessiechan27 commented on api-reference/beta/api/chat-get-operation.md
> +title: "Get operation on a chat"
There's another file added here called chat-list-operations for the multiple operations

2021-06-14 22:53 UTC, opbld33 commented
Docs Build status updates of commit _[d7b1c30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7b1c302c31ff2663826596a824eda76706ca47b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142252054136-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fC98%2F1pSGFgMz1Hki%2Fotj%2FqAAKRz2V5tWqe41OS%2BTC8%3D&st=2021-06-14T22%3A48%3A34Z&se=2021-07-15T22%3A53%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 18:12 UTC, opbld32 commented
Docs Build status updates of commit _[04d03bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04d03bdca0fba5c25151f3ad4fbb684ad59655cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151811035744-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hvLGGK4FkzqPRYa9o08V9G8OPR9hrCYZ4GPT2xW0tX4%3D&st=2021-06-15T18%3A07%3A36Z&se=2021-07-16T18%3A12%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 18:30 UTC, opbld31 commented
Docs Build status updates of commit _[210f1df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/210f1df5da1d5c1a4688241c9fe29ea950061fc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151829126538-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3omrTbez4big5i3xT%2FWCDp6FiaXbc2Ch%2BauxrndkWSs%3D&st=2021-06-15T18%3A25%3A43Z&se=2021-07-16T18%3A30%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 18:47 UTC, opbld31 commented
Docs Build status updates of commit _[d9ad608](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9ad60815a15466f753ec7cff9053e3164ae5f8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151845571838-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nd7Ln%2FdESqiLrt6cfMcA2MAAgx%2B663GCczhmqEcB0Eg%3D&st=2021-06-15T18%3A42%3A27Z&se=2021-07-16T18%3A47%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 21:24 UTC, JarbasHorst requested changes

2021-06-15 21:24 UTC, JarbasHorst commented on api-reference/beta/api/chat-post.md
> +If successful, this method returns a 201 Created response code and the newly created [chat](../resources/chat.md) resource in the response body.
For consistency, please emphasize the HTTP status code. Suggested revision:

\`201 Created\`

2021-06-15 21:24 UTC, JarbasHorst commented on api-reference/beta/api/chat-post.md
> +If successful, this method returns a `202 Accepted` response code and Location header containing a link to the [teamsAsyncOperation](../resources/teamsasyncoperation.md). The link can be used to get
Please, avoid using gerunds where possible; in this case, you can change "containing" to "that contains".

2021-06-15 21:24 UTC, JarbasHorst commented on api-reference/beta/api/chat-post.md
> +The async operation is initiated, and the response contains a Location header, which contains a link to the [teamsAsyncOperation](../resources/teamsasyncoperation.md). The link can be used to get the
For readability, I recommend: 

"The previous response shows an initiated async operation that contains a Location header which includes a link to the..."

2021-06-15 21:24 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "2be0f907-b973-4695-8792-380f383d9779",
Maybe I am wrong, but I thought this PR should also include the modified teamsAsyncOperationType enum file. The change should look like:

## Members

| Member | Value| Description |
|:---------------|:--------|:----------|
|invalid|0|Invalid value.|
|cloneTeam|1|Operation to clone a team.|
|archiveTeam|2|Operation to archive a team.|
|unarchiveTeam|3|Operation to restore an archived team.|
|createTeam|4|Operation to create a team from scratch.|
|**createChat**|**5**|**...**|

2021-06-16 15:08 UTC, jessiechan27 commented on api-reference/beta/api/chat-post.md
> +The async operation is initiated, and the response contains a Location header, which contains a link to the [teamsAsyncOperation](../resources/teamsasyncoperation.md). The link can be used to get the
The response doesn't show the operation and this is not the returned response body, so I couldn't use your full sentence. I tweaked it to look more like yours!

2021-06-16 15:10 UTC, opbld31 commented
Docs Build status updates of commit _[6ab79c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ab79c8d8bd09a7cb64e2edd616a2d3c717d632a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d4f23b45)

<a id="d4f23b45"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161508432255-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iHCTgqcZGj5B4Q41ADomXR3j6M8jQSABomjgym%2BIvSI%3D&st=2021-06-16T15%3A05%3A13Z&se=2021-07-17T15%3A10%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 15:21 UTC, opbld33 commented
Docs Build status updates of commit _[56a1c50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56a1c5056a049b76030e47a39298a47070288f16)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8a502a9a)

<a id="8a502a9a"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161521205868-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M1Prs0RkPfXnupS5DaWOFcdK8UFBP1w27HWXSJU%2BSjs%3D&st=2021-06-16T15%3A16%3A39Z&se=2021-07-17T15%3A21%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 15:34 UTC, opbld34 commented
Docs Build status updates of commit _[fde9d28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fde9d28e3e3a31a0f835a0b809b8ae1b05300f20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161533127406-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F1bwYiZJrTA9KtQ4wDNZEFrF%2F5TyD3kHrsvLxj17qSQ%3D&st=2021-06-16T15%3A29%3A43Z&se=2021-07-17T15%3A34%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 19:37 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. 

The changelog contains the following entry: "Added the **createChat** member to the **teamsAsyncOperationType** enumeration."

Maybe I am wrong, but I was expecting this PR to include the modified teamsAsyncOperationType enum file. The modified file could look like:

## Members

| Member | Value| Description |
|:---------------|:--------|:----------|
|invalid|0|Invalid value.|
|cloneTeam|1|Operation to clone a team.|
|archiveTeam|2|Operation to archive a team.|
|unarchiveTeam|3|Operation to restore an archived team.|
|createTeam|4|Operation to create a team from scratch.|
|**createChat**|**5**|**...**|

2021-06-16 21:33 UTC, jessiechan27 commented
> @Lauragra this PR is ready for final review.
> 
> The changelog contains the following entry: "Added the **createChat** member to the **teamsAsyncOperationType** enumeration."
> 
> Maybe I am wrong, but I was expecting this PR to include the modified teamsAsyncOperationType enum file. The modified file could look like:
> 
> ## Members
> Member	Value	Description
> invalid	0	Invalid value.
> cloneTeam	1	Operation to clone a team.
> archiveTeam	2	Operation to archive a team.
> unarchiveTeam	3	Operation to restore an archived team.
> createTeam	4	Operation to create a team from scratch.
> **createChat**	**5**	**...**

@JarbasHorst thanks for pointing that out! I made the changes

2021-06-16 21:36 UTC, opbld34 commented
Docs Build status updates of commit _[369ddb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/369ddb84c9293c340780340edef384c36695ffa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162133167770-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PTE%2BhwFx%2BA25JJNXjIJ%2FYhThcR9CLDfUHM4geHKR%2B80%3D&st=2021-06-16T21%3A31%3A00Z&se=2021-07-17T21%3A36%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 21:44 UTC, opbld33 commented
Docs Build status updates of commit _[d800b53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d800b53fb804bc8d30d16be99b97b37269bb4aad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162142431691-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iwvHBHizR2f8kFWkJLz1ZNMLsItEgqslYUDAgnaoya0%3D&st=2021-06-16T21%3A39%3A15Z&se=2021-07-17T21%3A44%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:09 UTC, opbld30 commented
Docs Build status updates of commit _[9c7f818](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c7f81807a1a76b30a9ff83a1fd4703358f620f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162207426672-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jJ1uVbz78evCcMUeYGN8CsvWVC4H647U%2Bn30Zfrb1fo%3D&st=2021-06-16T22%3A04%3A17Z&se=2021-07-17T22%3A09%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:20 UTC, Lauragra commented on api-reference/beta/api/chat-get-operation.md
> +title: "Get operation on a chat"
For this operation, we should have one topic, file name teamsasyncoperation-get, with the title Get teamsAsyncOperation. Does the same operation also apply to a team resource?

2021-06-16 22:23 UTC, opbld34 commented
Docs Build status updates of commit _[94a1a8d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94a1a8dab678d8ebd05bd6e173fc03538366f581)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162221276702-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ksVfqEBlOlm1Q3hzDoaI61CDRRuDbQFrGTgwOKHo%2F%2Bc%3D&st=2021-06-16T22%3A18%3A20Z&se=2021-07-17T22%3A23%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:24 UTC, opbld31 commented
Docs Build status updates of commit _[852eb40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/852eb4040434477d14bc65a191ec4c8ff9b443d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162222189839-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZcSMSs%2Fm122EFLwUjL3V72ilv%2BDmtmP1C3CB3kA0eGk%3D&st=2021-06-16T22%3A19%3A53Z&se=2021-07-17T22%3A24%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:28 UTC, opbld30 commented
Docs Build status updates of commit _[45c2001](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45c200126e9e66ca4101aaba049af5ec7cae4668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162227149387-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2gR%2Byvm7KT9Cx1Qeii9gdcJmp5iXoYfjbIbYWCbB4f8%3D&st=2021-06-16T22%3A23%3A40Z&se=2021-07-17T22%3A28%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:40 UTC, opbld31 commented
Docs Build status updates of commit _[61b8764](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61b87642da270718a7c3b421e6e2fef64bb6ff58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162239172192-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aTwa6Rezk0WSWa7ZHy5daN0ic%2FYxpH4U%2B6NRPFuAkt8%3D&st=2021-06-16T22%3A35%3A41Z&se=2021-07-17T22%3A40%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 09:51 UTC, AkJo commented on api-reference/beta/api/chat-get-operation.md
> +title: "Get operation on a chat"
Given that there are bugs in the toc at not being able to navigate correctly to the page if two entries in the toc map to the same page, I would suggest just renaming the file o chat-get-operations.

@jessiechan27, can you refer to channel-get-members as an example.

2021-06-17 15:24 UTC, opbld34 commented
Docs Build status updates of commit _[793014f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/793014fdabc54f34becb4619aa8a6e3a2e6ad2f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-get-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-get-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106171523248335-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jQtOEg%2F8R6Kx0a8AwI9i6wdGewY%2BwIu5R9IKUNWINzA%3D&st=2021-06-17T15%3A19%3A51Z&se=2021-07-18T15%3A24%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 17:48 UTC, opbld33 commented
Docs Build status updates of commit _[19bbfc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19bbfc81fff73f1690f70f26ee50d0dcc2c7933f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) | [Details](#user-content-f0f4390ba9269f3db09256b66ffb3bf6-1a848513)
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) | [Details](#user-content-6c5bf3f07ed2d1ce0175cd9ca9b18b75-1a848513)
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/teamsasyncoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/teamsasyncoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsasyncoperation-get?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f0f4390ba9269f3db09256b66ffb3bf6-1a848513"></a>
### [api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md)
 - **Line 62, Column 254**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'teamsasyncoperation-get'.`````
 - **Line 228, Column 254**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'teamsasyncoperation-get'.`````

<a id="6c5bf3f07ed2d1ce0175cd9ca9b18b75-1a848513"></a>
### [api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md)
 - **Line 53, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamsasyncoperation-get'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181737264039-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8YqVsq3AJWu%2BwZGFVLLyeAPwXiy3WFb%2B0Ot166VuQgc%3D&st=2021-06-18T17%3A43%3A21Z&se=2021-07-19T17%3A48%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 19:02 UTC, opbld33 commented
Docs Build status updates of commit _[b37e33e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b37e33e1c358eab8181d31c1e6c5953560bcee60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/teamsasyncoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/teamsasyncoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsasyncoperation-get?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181855020919-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oo8eTUGNg3RK2P5wxxZ0JDoJnD%2BaZrxWvg1uSOj6E%2F4%3D&st=2021-06-18T18%3A57%3A43Z&se=2021-07-19T19%3A02%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 21:00 UTC, Lauragra approved these changes

2021-06-18 21:03 UTC, opbld31 commented
Docs Build status updates of commit _[3d20c0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d20c0b8c97c793b9b0d997e1bdcaea4c4b5d07b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list-operations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-list-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/api/teamsasyncoperation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/api/teamsasyncoperation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsasyncoperation-get?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/resourcespecificpermissiongrant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/resourcespecificpermissiongrant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/resourcespecificpermissiongrant?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-operations?view=graph-rest-beta&branch=pr-en-us-12866) (graph-rest-beta) |
[api-reference/v1.0/resources/teamsasyncoperationtype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/api-reference/v1.0/resources/teamsasyncoperationtype.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperationtype?view=graph-rest-1.0&branch=pr-en-us-12866) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/install-app-chat-creation/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106182100353399-12866%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d6UgzM9vH5WN9zX2Bw369qHc3%2BkxWksyPG%2BtDNf0kn4%3D&st=2021-06-18T20%3A58%3A55Z&se=2021-07-19T21%3A03%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 21:18 UTC, merged