added External groups doc
microsoftgraph/microsoft-graph-docs pull request #12870
Opened 2021-05-25 19:33 UTC by mecampos

added External groups doc

2021-05-25 19:37 UTC, opbld31 commented
Docs Build status updates of commit _[d9a2173](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9a2173260adcb4ae76d0e3caee2c70d48b215f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105251935569691-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ae7QzlQ2hdc6jKUrAEfq%2F91SAXZu7mLbPGKYIjBgkD4%3D&st=2021-05-25T19%3A32%3A11Z&se=2021-06-25T19%3A37%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 19:44 UTC, opbld31 commented
Docs Build status updates of commit _[360afa7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/360afa75efb1b20b133852be7f33b165e2acb3a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105251943224255-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2vy0gr5%2BEu6p5Y7O6KOJdtXY%2BRmA6xgonXcmFlb8JDU%3D&st=2021-05-25T19%3A39%3A42Z&se=2021-06-25T19%3A44%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-26 16:55 UTC, opbld31 commented
Docs Build status updates of commit _[f4edc2d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4edc2d39ee6a5ca3e0303153b1dc0e4e2eafb70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105261650522264-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V2ycUF9e7X1EwurmEyUX2Y%2Fc3O8YRwSIJjHBmQROWIg%3D&st=2021-05-26T16%3A50%3A21Z&se=2021-06-26T16%3A55%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-26 17:12 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +# External groups overview
Line 9: Please keep consistency with the title in line 2. In this case, I'd prefer to keep it simple and just use "External groups" as title.

2021-05-26 17:49 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +The access control list is used to specify who has permissions to view [external items](/graph/api/resources/externalitem?view=graph-rest-beta&preserve-view=true) in a Microsoft Graph connection, in
Line 11: Let's improve this section. 
- For concept topics we try to first introduce the service in one or two sentences. 
- In this case we are introducing the actual topic until line 44, after the json block. Please remember we write to scan first, read later. To maintain scannability, please introduce the topic with a description of external groups and its functionality. Guidance [here](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103154/Conceptual-topics?anchor=what-to-write-for-your-service-overview%3F).
- In general, we have [guidance to use passive voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=25523), because it usually leads to further questions. In this case, I think we can re-phrase to active voice. 
- We avoid using acronyms to maintain inclusion and clarity. Please avoid using ACLs or AAD. Please use complete words instead.

My suggestion:
Manage security trimming for external items with [external groups](reference link) and connect to data sources outside Azure Active Directory groups.

2021-05-26 17:59 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +Here are two common non-AAD application-specific group examples.
I'd prefer having this section in a separate H2 title, such as "## Common scenarios". 

What do you think?

2021-05-26 18:09 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +<!---Using json to adjust the size of the image --->
Regarding the images, please follow the guidelines [here](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36404).
My main concerns are the shapes (consistency and accessibility) and the font used (Calibri instead of Segoe). If you need assistance with the design, please contact [Brand Central](https://microsoft.sharepoint.com/teams/BrandCentral/).

2021-05-26 19:18 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +<br><img src="images/connectors-images/bu-teams-D365.png" alt="Example of Business Units and Teams in Dynamics 365" style="width:400px;"/>
Regarding the alt text: Could you please include a more detailed description? Please keep in mind, alt text is used by screen readers, so we should think about people with visual disabilities that rely completely on this description to understand the image. 
For example: Diagram of an structure in Dynamics 365. A business unit has a team and a manager under it. This manager has other users.

2021-05-26 19:20 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +<!---Using json to adjust the size of the image --->
Same issues regarding this image. Please follow guidelines, use a single art style and use Segoe UI font. In addition, please include a more detailed alt text.

2021-05-26 19:27 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +Here are two common non-AAD application-specific group examples.
Please leverage this section to define what a "non-AAD" group/entity is. It is constantly mentioned across the doc and for someone with little to non experience will be difficult to catch.

2021-05-26 20:06 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +To use external groups for your connections that use application-specific, non-AAD identities for permission control, do the following:
This phrasing is not easy for non-native readers. Let's make it simple. For example:
"To use external groups in your connections:"

2021-05-26 20:09 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +* For each non-AAD group, create an external group in Microsoft Graph using the Groups API.
Are these sequential items? If so, please use numbers instead of bullets. Details [here](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36412).

In addition, please include the reference link for Groups API.

2021-05-26 20:10 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +* Use the external group when defining the ACL for your external items as necessary.
Please use complete words instead of acronyms - ACL in this case.

2021-05-26 21:54 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +External groups are scoped to a connection. For each application-specific, non-AAD group associated with your connection, create an external group using the Groups API in Microsoft Graph as shown bel
Line 71: Let's improve this for clarity and efficiency. 
1. What do we mean by "scoped"? Could we say: "External groups belong to a connection"? //Note the change to active voice. 
2. This name "application-specific, non-AAD group" is not clear. Can we use a cleaner phrasing for this? 
3. I'd suggest moving the third sentence to a different paragraph so its easier to scan. Also, let's explain the ID field a bit. For example: Provide either an identifier or a name in the ID field. Use this value to call the external group in subsequent requests.
4. Why are we referencing different entities with the id and the displayName? Aren't both supposed to be properties of the externalGroup resource?

2021-05-27 00:03 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +External groups are scoped to a connection. For each application-specific, non-AAD group associated with your connection, create an external group using the Groups API in Microsoft Graph as shown bel
Please use caps when mentioning "ID".

2021-05-27 00:18 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +```json
If the intention of the code block is to provide a JSON representation of the entity, please remove the POST line. 
On the other hand, if the intention is to provide the instruction to create a new externalGroup, please use this format:
http
POST /connections/{id}/externalGroups 
Content-type: application/json

{
the json rep here
}

This is meant to keep consistency across docs in Graph.

2021-05-27 01:15 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +# External groups overview
Changed as recommended.

2021-05-27 01:33 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +```json
Changed to http.

2021-05-27 02:10 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +> * URL and  FileName Safe Base 64 Character Set are allowed.
Line 83: Please capitalize "ID" and let's make it simple.
Line 84: Please re-phrase to active voice. 
Question: Why isn't the information in line 84 described in the [externalGroups](https://docs.microsoft.com/en-us/graph/api/resources/externalgroup) topic? Should we update this as well?
For example: 
- The ID field has a limit of 128 characters.
- You can encode the name in base 64 format in the displayName field or even use a URL.

Please correct me if line 84 should apply to the ID field instead of the displayName field.

2021-05-27 02:12 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +* Another external group (external groups support nested external groups)
Lets avoid acronyms and include reference links if possible. For example:
- An Azure Active Directory [user](link here).
- An Azure Active Directory [group](link here).
- Any external groups, including nested external groups.

2021-05-27 02:38 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +You need to ensure that external group memberships are up to date in Microsoft Graph. When memberships change in your custom group, make sure that the change is reflected in the external group at a t
Line 162, first sentence: Please re-phrase in a friendly tone. For example
Keep your the membership of your external group up to date in Microsoft Graph.

2021-05-27 02:40 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +## Related
Can we change this for a See also section? Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103167/Next-steps-and-see-also

2021-05-27 02:41 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +### Use external groups in the ACLs
Please use complete words instead of the acronym "ACLs".

2021-05-27 02:47 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +You can use external groups when defining ACLs for external items. In addition to AAD users and AAD groups, an external item can have external groups in its ACEs, as shown next.
Line 119: 
First sentence: Could you include a reference link to ACLs info? 
Second sentence: Please rephrase: In addition to Azure Active Directory users and groups, an external item can have external groups in its access control entries (? please include full words and reference links).

2021-05-27 02:51 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +{
Block code from 120 to 155: 
1. I think this should be HTTP instead of JSON. 
2. Please include a blank line between line 122 and 123. 
3. Please indent the lines properly so the code looks organized and cleaner.

2021-05-27 02:55 UTC, isvargasmsft commented on concepts/connecting-external-content-external-groups.md
> +After you create the group, you can add members to the group as in the examples shown below.
Line 90: Please add a blank line between the list and this line.
Is there a particular reason to include these examples in a concept topic? Can we just point readers to the right direction? For example:
See [create externalGroupMembers](../api/externalgroup-post-members) to add members to your  external group.

2021-05-27 03:06 UTC, isvargasmsft requested changes
@mecampos thank you very much for your work on these docs. Very nice document!

Some general recommendations regarding [Microsoft Writing Style](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=33685) and [Microsoft Graph guidelines](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103154/Conceptual-topics).

In summary:
- Let's avoid using acronyms because it excludes readers that are not familiar with our terms. 
- Let's review and rethink the images. Please contact **Brand Central** if you want assistance.
- Remember we write friendly, easy and simple. To scan first and read later.
- Please include reference links when mentioning a resource, API, method or such.

Please feel free to ping me on the side if you have any questions. I'm here to help!

Kind regards, 

Isaac Vargas

2021-05-27 03:49 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +# External groups overview
Agree that the title and H1 should be consistent. We should also make sure that we're including important keywords. In this case, we have a Groups node/API, so we'll want to ensure that we clearly differentiate the title. Is this something like "Connecting external groups using the Microsoft Graph connectors API"?

2021-05-27 03:50 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +description: Concept page for external groups
This description should be a complete sentence and should describe, ideally in a single sentence, the intent of the article - i.e. what the reader will get out of reading it. It's hard to discern what the intent of this article is. Note that the description that you specify here can show up as the article description in search results, so you'll want to be clear/complete and include important keywords.

2021-05-27 03:58 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +The access control list is used to specify who has permissions to view [external items](/graph/api/resources/externalitem?view=graph-rest-beta&preserve-view=true) in a Microsoft Graph connection, in
You're using the article "The" in the first sentence which implies that you're referring to a specific access control list, which hasn't bee introduced. Would it be accurate to revise as "Access control lists are used..."?

I will also say, generally, that the introductory paragraph doesn't make the intent/purpose of the article particularly clear. I don't see any mention of external groups? Please try revising to help us better understand what you expect users to learn/do by reading the article.

Note to Isaac: This is a concept topic so the practice to have a single, scannable introductory sentence doesn't necessarily apply. Concept topics can have a richer/more detailed introduction. Agree that acronyms should be spelled out at first mention and some acronyms, like AAD, are not permitted (it's a brand violation to form acronyms of trademarked product names - should be Azure AD); some acronyms are standard/permitted though so it's okay to use ACL after spelling out at first mention "access control list (ACL)".

2021-05-27 04:00 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +However, for data sources that use non-AAD groups or group-like constructs, is recommended that you use [external groups](/graph/api/resources/externalgroup?view=graph-rest-beta&preserve-view=true),
Change "is recommended" to "we recommend". This is one case where the first person plural "we" is acceptable to use in content. https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/we

I see that we are now getting to mentions of external groups. This value proposition should be stated up front in the article. Is the phrase "security trimming" going to be clear to the target audience?

2021-05-27 04:03 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +Here are two common non-AAD application-specific group examples.
Also be sure to spell out as Azure AD. Avoid the passive "here are" construction; you can revise as "The following are common non-Azure AD application-specific group examples." I'm also not clear as to whether the non- applies to the whole phrase, or just Azure AD. Depending on the intended meaning, you can recast as "The following are two group examples that are not specific to Azure AD applications", for example.

2021-05-27 04:09 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +1. Microsoft Dynamics 365 allows customers to structure their CRMs with Business Units and Teams. The membership information for these Business Units and Teams is not stored in AAD.
I don't think in this context that Business Units and Teams are proper nouns; please lowercase. Note that Teams can easily be confused with the Microsoft Teams product.

2021-05-27 16:49 UTC, opbld34 commented
Docs Build status updates of commit _[49b0683](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49b06839d05c89cb99220fd7b91733e144ddd8cc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-145a0e7a)

<a id="145a0e7a"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105271648522718-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1xVFtaJphZVdL8NEthtU9gZf2V9P8czdO4cSAbNogOw%3D&st=2021-05-27T16%3A44%3A11Z&se=2021-06-27T16%3A49%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 22:37 UTC, opbld30 commented
Docs Build status updates of commit _[16e9078](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16e9078a80cc01d4f7ecf9370344f3d07d97e28d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105272236259505-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1zp5udFLrmitbAOCTgMu3jPest56cmOq8x084uhIWo8%3D&st=2021-05-27T22%3A32%3A49Z&se=2021-06-27T22%3A37%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 22:41 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +*Figure 1. Business Units & Teams in Dynamics 365*
I don't know that you need to include figure numbers, especially if you aren't referencing figures in the text. This seems a bit overly formal for this article. Also note that when you number figures, if you revise later to add/remove/rearrange art, you need to update the numbering, so there's a bit of overhead.

2021-05-27 22:42 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +* Use the external group when defining the ACL for your external items as necessary.
FYI, it's okay to use ACL as an acronym after first mention, it's an industry-accepted acronym.

2021-05-27 22:43 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +To use external groups for your connections that use application-specific, non-AAD identities for permission control, do the following:
For brevity, you can remove "do the following" and just have the colon.

2021-05-27 23:23 UTC, opbld34 commented
Docs Build status updates of commit _[b8aa599](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8aa59936a930c3837e8706c2bb7aa274daa6464)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105272321543216-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=akSNsBeDt9V5BTTCQMcl5g5%2FYRvm3rPcKr1FsveNPx4%3D&st=2021-05-27T23%3A18%3A32Z&se=2021-06-27T23%3A23%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 01:05 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +# External groups overview
The doc intends to present "external groups'' as a feature of connectors. "External groups” was created as an option for clients who do not want to create AAD groups only to use connectors, allowing them to use their custom groups for authorization.

2021-05-28 01:14 UTC, opbld30 commented
Docs Build status updates of commit _[f6f853b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6f853b73dbc7e179d6ece9a01f26af861067866)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280113207492-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QsSWl0BgfV6rbdcR9EkiCDOG8G2I19WtQF1ZDka%2FTec%3D&st=2021-05-28T01%3A09%3A38Z&se=2021-06-28T01%3A14%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 01:16 UTC, opbld33 commented
Docs Build status updates of commit _[2aba14e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2aba14e01c0ff9d25ddae6b2b72c187087fc07bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280114475735-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V6Dl8yJJswPTiC97QzjgPTFvabBKQAmm4k2OrNNX%2FFQ%3D&st=2021-05-28T01%3A11%3A04Z&se=2021-06-28T01%3A16%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 01:21 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +The access control list is used to specify who has permissions to view [external items](/graph/api/resources/externalitem?view=graph-rest-beta&preserve-view=true) in a Microsoft Graph connection, in
Changed as recommended.

2021-05-28 05:12 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +Here are two common non-AAD application-specific group examples.
Added examples to define what a "non-AAD" group is.
Changed to "The following are common non-Azure AD application-specific group examples."

2021-05-28 05:15 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +To use external groups for your connections that use application-specific, non-AAD identities for permission control, do the following:
Changed as recommended.

2021-05-28 05:28 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +* Use the external group when defining the ACL for your external items as necessary.
Added mention in line 15.

2021-05-28 05:36 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +* For each non-AAD group, create an external group in Microsoft Graph using the Groups API.
Changed as recommended.

2021-05-28 05:51 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +> * URL and  FileName Safe Base 64 Character Set are allowed.
The id in this case is for the externalItem, and the note is for the ID field.
Please note that in this case “URL & FileName Safe Base 64 Character Set” is the technical term that we need to use.
Changed to ID.

2021-05-28 05:53 UTC, mecampos commented
Also, updated the code following lines:

Lines 27, 33, 109, 140, 146: changed identity source from "Azure Active Directory" to "azureActiveDirectory"
Line 78: changed "/connections/{id}/externalGroups" to "/connections/{connectionId}/groups"
Lines 97, 105, 113: changed "POST /connections/{id}/externalgroups/{id}/externalGroupMembers " to "POST /connections/{connectionId}/groups/{groupId}/members"

2021-05-28 05:54 UTC, opbld32 commented
Docs Build status updates of commit _[9821780](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9821780c22ef34edd830e91c71fa2da3bfca87d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) | [Details](#user-content-d8c334a72beb7ea5a5cd1de8aa15cb7d-dd5ab1d5)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

<a id="d8c334a72beb7ea5a5cd1de8aa15cb7d-dd5ab1d5"></a>
### [concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md)
 - **Line 70, Column 87**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /en-us/graph/api/resources/group?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280552316526-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NFDZZHJ05Flu18ALHevAOPMK%2BPi1RaXgg3Dv85frikA%3D&st=2021-05-28T05%3A49%3A55Z&se=2021-06-28T05%3A54%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 00:15 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +* Another external group (external groups support nested external groups)
Changed as recommended.

2021-05-29 00:36 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +You need to ensure that external group memberships are up to date in Microsoft Graph. When memberships change in your custom group, make sure that the change is reflected in the external group at a t
Changed as recommended.

2021-05-29 00:37 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +## Related
Changed as recommended.

2021-05-29 00:49 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +You can use external groups when defining ACLs for external items. In addition to AAD users and AAD groups, an external item can have external groups in its ACEs, as shown next.
Changed as recommended

2021-05-29 01:05 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +{
Changed as recommended.

2021-05-29 01:13 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +After you create the group, you can add members to the group as in the examples shown below.
I'll leave the examples here for now, and I'll check with the developers in case that we need to update the api doc too.

2021-05-29 01:15 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +description: Concept page for external groups
Changed as recommended.

2021-05-29 01:51 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +The access control list is used to specify who has permissions to view [external items](/graph/api/resources/externalitem?view=graph-rest-beta&preserve-view=true) in a Microsoft Graph connection, in
Updated the first and second paragraphs.

2021-05-29 01:55 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +However, for data sources that use non-AAD groups or group-like constructs, is recommended that you use [external groups](/graph/api/resources/externalgroup?view=graph-rest-beta&preserve-view=true),
Changed as recommended.

2021-05-29 02:02 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +1. Microsoft Dynamics 365 allows customers to structure their CRMs with Business Units and Teams. The membership information for these Business Units and Teams is not stored in AAD.
Changed as recommended.

2021-05-29 02:02 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +*Figure 1. Business Units & Teams in Dynamics 365*
Changed as recommended.

2021-05-29 02:03 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +To use external groups for your connections that use application-specific, non-AAD identities for permission control, do the following:
Changed per previous comment to: "To use external groups in your connections:"

2021-05-29 02:05 UTC, opbld31 commented
Docs Build status updates of commit _[d6dd47a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6dd47acc6cb91e21426c6ae81e8780ad3039f8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) | [Details](#user-content-d8c334a72beb7ea5a5cd1de8aa15cb7d-d9e9734b)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

<a id="d8c334a72beb7ea5a5cd1de8aa15cb7d-d9e9734b"></a>
### [concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md)
 - **Line 37, Column 87**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /en-us/graph/api/resources/group?view=graph-rest-beta. Otherwise, remove the view parameter.`````
 - **Line 46, Column 49**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/externalgroup?view=graph-rest-beta#properties. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290204313535-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lKftIaoLFMKRDvbIhyNTIdokZ%2FfEYjXlIK08%2Bp%2Bk%2BdM%3D&st=2021-05-29T02%3A00%3A52Z&se=2021-06-29T02%3A05%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 03:30 UTC, opbld31 commented
Docs Build status updates of commit _[8687555](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8687555a540da0543f6d6d0c56ef899880598676)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290328164615-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nslXqjhhVleT1I98iPDZ0%2F6%2Bng%2B%2BstBZgWsss0r11fo%3D&st=2021-05-29T03%3A25%3A37Z&se=2021-06-29T03%3A30%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 03:38 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +### Use external groups in the ACLs
Leaving acronym, per previous comment ( it's an industry-accepted acronym).

2021-05-29 04:09 UTC, opbld34 commented
Docs Build status updates of commit _[ed07e98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed07e986289db1898c06ab80003bf507cdb3a818)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290407210539-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qAjs5z7RQFuibOrF9bpKLgBbAQFSdFgJ8pfw5SDzrR0%3D&st=2021-05-29T04%3A04%3A51Z&se=2021-06-29T04%3A09%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 05:13 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +<br><img src="images/connectors-images/bu-teams-D365.png" alt="Example of Business Units and Teams in Dynamics 365" style="width:400px;"/>
Updated images, using illustration libraries from Brand Central.

2021-05-29 05:13 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +<!---Using json to adjust the size of the image --->
Updated images, using illustration libraries from Brand Central.

2021-05-29 05:13 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +<!---Using json to adjust the size of the image --->
Updated images, using illustration libraries from Brand Central.

2021-05-29 05:14 UTC, opbld31 commented
Docs Build status updates of commit _[a04347c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a04347c0014f7272ff5b2f027964543807dc37c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290512342325-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ovWs2909ILPBDBFfqb3Jq%2F0iaU6ULAzDt0AeQzazgLk%3D&st=2021-05-29T05%3A09%3A00Z&se=2021-06-29T05%3A14%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 05:18 UTC, opbld30 commented
Docs Build status updates of commit _[780428e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/780428e8970e706900ce10c19a7c808980f2d33f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290516394035-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZQpG1mMInbtJSjpaNrLqlgbAsUEVaiND9JhMFwNPO7Q%3D&st=2021-05-29T05%3A13%3A01Z&se=2021-06-29T05%3A18%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 05:42 UTC, opbld34 commented
Docs Build status updates of commit _[7db6b94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7db6b94bbebb6824d14b65edfff72828ca328699)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290540522936-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Yx%2FZaepPl6az3sXoeY3Hti4jpE2kccOwIK5exw2SBvk%3D&st=2021-05-29T05%3A37%3A36Z&se=2021-06-29T05%3A42%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 05:44 UTC, opbld34 commented
Docs Build status updates of commit _[3a79324](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a79324354f419d5dccf20ef70c449889a03b428)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290543272803-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=THQ49cqin4GYlJTAC73EOV9DLDYCdv5lNNJRyboTHQE%3D&st=2021-05-29T05%3A39%3A52Z&se=2021-06-29T05%3A44%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 05:57 UTC, opbld32 commented
Docs Build status updates of commit _[f719401](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f719401c01a4c3af17211e71e013d7b300ce8f2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105290555309636-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cd00VnotsC6RXosArLxRnEcRtFRB9UU2UsWLLWv%2FlcI%3D&st=2021-05-29T05%3A52%3A01Z&se=2021-06-29T05%3A57%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-29 05:58 UTC, mecampos commented
Thank you, @isvargasmsft, I updated the document according to the feedback. Please continue your review.

2021-05-29 15:54 UTC, opbld34 commented
Docs Build status updates of commit _[a9a75b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9a75b20e5e1da44b72703d6d637f0f8bb24eba3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105291553253177-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MFxhpyuacQfwHmPgm3jO3mAaesAU5ArjKFP4JtuRDCI%3D&st=2021-05-29T15%3A49%3A55Z&se=2021-06-29T15%3A54%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 00:03 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +description: Learn about external groups to manage security trimming for external items.
What does "security trimming" mean? Is that a term that will be familiar to readers?

2021-06-02 00:06 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +title: External groups
The title and H1 for this article needs to include important keywords for search and better clarify the topic. Note that we have a concept of Groups in Microsoft Graph and you want to be sure to differentiate this as having the context of connectors. Something like "Use external groups to manage permissions to Microsoft Graph connectors data sources".
```

2021-06-02 00:06 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +# External groups
Please update as per my comment o line 2.

2021-06-02 00:07 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +For data sources that rely on Azure Active Directory users and groups, you set permissions on external items by associating an access control list (ACL) with an Azure Active Directory user and group
On first mention, use "Azure Active Directory (Azure AD)"; thereafter, you can shorten to Azure AD.

2021-06-02 00:21 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +1. Microsoft Dynamics 365 allows customers to structure their CRMs with business units and teams. The membership information for these business units and teams is not stored in Azure Active Directory
Please provide an introduction before you start describing the scenarios, to set the context for the reader. Also, why are the scenarios a numbered list? Generally we use numbered lists for things that are sequential, like procedures. The scenarios can just be described in paragraphs. Also, the scenarios are not connected to the intent of the article. I would expect to see descriptions of the scenarios, followed by an explanation for how the organization uses external groups. What is the reader expected to get out of reading the Comment scenarios section?

2021-06-02 00:22 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +    The following is an example of business units and teams in Dynamics 365:
I think what you mean to say here is "The following image shows the structure of the business units and teams."

2021-06-02 00:23 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +    The following is an example of roles in Salesforce:
And this would be "The following image shows the structure of the membership information in Salesforce."

2021-06-02 00:24 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +1. For each non-Azure AD group, create an external group in Microsoft Graph using the [Group API](/en-us/graph/api/resources/group?view=graph-rest-beta&preserve-view=true).
Change Group API to Groups API.

2021-06-02 00:26 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +* Use the Group API in Microsoft Graph as shown in the code below.
Move the code block to follow this bullet point, and remove the text "in the code below". The sentence can just end with "as shown". Also change Group to groups.

2021-06-02 00:28 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +    > The ID field allows to use URL and FileName Safe Base 64 Character Set, and it has a limit of 128-character.
A word is missing here, I think in between "allows" and "to". Also please check the capitalization for that string of capitalized words. Base-64 is generally hyphenated. "128-character" should just be 128 characters.

2021-06-02 00:29 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +* The [displayName](/graph/api/resources/externalgroup?view=graph-rest-beta&preserve-view=true) and description are optional fields.
This bullet should just be a note preceding the code block in the first bullet (after you move the code block).

2021-06-02 00:31 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +After you create the group, you can add members to the group as in the examples shown below.
Please avoid using "below" (or "above") to refer to content in an article. You can use "following" or "preceding". In this case please revise the sentence to say "... you can add members, as shown in the following examples."

2021-06-02 00:33 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +You can use external groups when defining [ACL](connecting-external-content-manage-items.md#access-control-list) for external items. In addition to Azure Active Directory users and groups, an externa
Revise as "an [ACL]" or "[ACLs}", depending on your intent.

2021-06-02 00:34 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +```http
Please introduce the example to set the context for the reader.

2021-06-02 00:35 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +> You can use external groups in ACL even before the groups are created.
You need to change to "an ACL" or "ACLs" for correct grammar.

2021-06-02 00:38 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +You can use the Groups API to manage your external groups and group membership. See [externalGroup](/graph/api/resources/externalgroup?view=graph-rest-beta&preserve-view=true) and [externalGroupMembe
For consistency, please use the same construction for all cross-references - introduce the subject matter first, and then provide the link. So the second sentence should be "For details, see [externalGroup] and [externalGroupMember]." Also change Groups to groups.

2021-06-02 00:39 UTC, Lauragra commented on concepts/connecting-external-content-external-groups.md
> +To learn more about the Microsoft Graph connectors API, visit the following link: [Working with the connectors API](connecting-external-content-connectors-api-overview.md)
Change "visit the following link:" to "see" (no colon), for consistency and to reduce unnecessary words.

2021-06-03 05:49 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +To learn more about the Microsoft Graph connectors API, visit the following link: [Working with the connectors API](connecting-external-content-connectors-api-overview.md)
Changed as recommended.

2021-06-03 05:51 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +You can use the Groups API to manage your external groups and group membership. See [externalGroup](/graph/api/resources/externalgroup?view=graph-rest-beta&preserve-view=true) and [externalGroupMembe
Changed.

2021-06-03 05:53 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +> You can use external groups in ACL even before the groups are created.
Changed as recommended.

2021-06-03 05:58 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +```http
Changed

2021-06-03 05:58 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +You can use external groups when defining [ACL](connecting-external-content-manage-items.md#access-control-list) for external items. In addition to Azure Active Directory users and groups, an externa
Changed

2021-06-03 05:59 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +{
Changed

2021-06-03 06:03 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +    > The ID field allows to use URL and FileName Safe Base 64 Character Set, and it has a limit of 128-character.
Safe Base-64 Character Set is the term recommended by the developers.

2021-06-03 06:05 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +* Use the Group API in Microsoft Graph as shown in the code below.
Changed

2021-06-03 06:07 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +* The [displayName](/graph/api/resources/externalgroup?view=graph-rest-beta&preserve-view=true) and description are optional fields.
Changed

2021-06-03 06:07 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +    > The ID field allows to use URL and FileName Safe Base 64 Character Set, and it has a limit of 128-character.
Changed

2021-06-03 06:08 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +1. For each non-Azure AD group, create an external group in Microsoft Graph using the [Group API](/en-us/graph/api/resources/group?view=graph-rest-beta&preserve-view=true).
changed

2021-06-03 06:09 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +    The following is an example of business units and teams in Dynamics 365:
Changed

2021-06-03 06:09 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +    The following is an example of roles in Salesforce:
Changed

2021-06-03 06:15 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +description: Learn about external groups to manage security trimming for external items.
Changed

2021-06-03 06:16 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +title: External groups
Changed as recommended

2021-06-03 06:19 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +For data sources that rely on Azure Active Directory users and groups, you set permissions on external items by associating an access control list (ACL) with an Azure Active Directory user and group
Changed

2021-06-03 06:19 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +# External groups
Changed

2021-06-03 06:23 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +However, for data sources that use non-Azure Active Directory groups (non-Azure AD groups), or group-like constructs, like Salesforce Profiles, Dynamics Business Units, SharePoint groups, ServiceNow
Changed

2021-06-03 06:24 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +However, for data sources that use non-Azure Active Directory groups (non-Azure AD groups), or group-like constructs, like Salesforce Profiles, Dynamics Business Units, SharePoint groups, ServiceNow
Changed

2021-06-03 06:28 UTC, mecampos commented on concepts/connecting-external-content-external-groups.md
> +1. Microsoft Dynamics 365 allows customers to structure their CRMs with business units and teams. The membership information for these business units and teams is not stored in Azure Active Directory
Added introduction.

2021-06-03 06:30 UTC, opbld32 commented
Docs Build status updates of commit _[45280d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45280d13e046444bff330ff503cad39e103776dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106030628495474-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aatNv833L50aTta62UCY2s%2B0Svn5pmq1KIpkc%2F9AEIU%3D&st=2021-06-03T06%3A25%3A12Z&se=2021-07-04T06%3A30%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 06:35 UTC, opbld32 commented
Docs Build status updates of commit _[f509a0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f509a0e6d9a3b89593eb5cd75703e45832e2fc37)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) | [Details](#user-content-d8c334a72beb7ea5a5cd1de8aa15cb7d-bd1cf6d0)
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

<a id="d8c334a72beb7ea5a5cd1de8aa15cb7d-bd1cf6d0"></a>
### [concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md)
 - **Line 23, Column 1**: **[Warning-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````
 - **Line 30, Column 1**: **[Warning-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106030634058741-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KWorir%2BKVRBWEUoUeKaGaQ7ncZAxUTADnlupQp2le%2Bc%3D&st=2021-06-03T06%3A30%3A32Z&se=2021-07-04T06%3A35%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 15:59 UTC, opbld32 commented
Docs Build status updates of commit _[bb6b4da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb6b4da0365c4bc7ef9789d2338ae9d23e86b221)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106031558195163-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UuJDusyLzmi1yKN7zCL4RtOGSrTxDaBJqezVXqmdlmA%3D&st=2021-06-03T15%3A54%3A47Z&se=2021-07-04T15%3A59%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 00:36 UTC, Lauragra approved these changes

2021-06-04 00:38 UTC, opbld31 commented
Docs Build status updates of commit _[570910d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/570910d5b5b10685a974143783a47d09c1712480)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/connecting-external-content-external-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/bu-teams-D365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/bu-teams-D365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/images/connectors-images/roles-salesforce.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/images/connectors-images/roles-salesforce.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mecampos-connectors-ext/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/connecting-external-content-external-groups?branch=pr-en-us-12870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106040036348838-12870%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CBpTIzHX0O7wxZ3BtzAxC%2BiqoPr2Er2T3O1J4CiQqNE%3D&st=2021-06-04T00%3A33%3A08Z&se=2021-07-05T00%3A38%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 00:39 UTC, merged