Rename and add azureAdDeviceSyncCheck related error types
microsoftgraph/microsoft-graph-docs pull request #12896
Opened 2021-05-27 03:42 UTC by RuiHou105

2021-05-27 03:43 UTC, opbld33 commented
Docs Build status updates of commit _[a492eae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a492eae8c4ff8609a32cf271958771c32c752694)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270342286875-12896%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nJf2npWFCiWGIe0pnjLkFtqgQJ4je75U3yggRgIOTvE%3D&st=2021-05-27T03%3A38%3A39Z&se=2021-06-27T03%3A43%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 05:59 UTC, opbld31 commented
Docs Build status updates of commit _[05d577f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05d577f6d35deed44890f4ea77e4697584dfb140)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270556507170-12896%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ihUuLJrUd5qEOxQfWIpiFFLQEr82imBwq85paVcrpnA%3D&st=2021-05-27T05%3A54%3A04Z&se=2021-06-27T05%3A59%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-27 08:18 UTC, RuiHou105 commented
1. Related api.md: https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/8480

2. Related CSDL file (schema-Prod-beta.csdl): https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4575379

2021-06-01 22:48 UTC, cohanley commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|azureAdDeviceSyncCheckDeviceNotFound|The Azure AD device sync check failed because the device that on-premises network connection created in Active Directory hasn’t been synced via AAD connect and c
change to "cannot be found in the customer's Azure AD devices list. Please wait for the next AAD sync cycle."

2021-06-01 22:48 UTC, cohanley commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|azureAdDeviceSyncCheckLongSyncCircle|The Azure AD device sync check failed because the device that on-premises network connection created has been synced into Active Directory via AAD connect, but A
change to "but the AAD Connect sync cycle is too long, which may block provisioning. Please shorten your AAD sync cycle for a smoother experience."

2021-06-01 22:54 UTC, Lauragra commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|azureAdDeviceSyncCheckLongSyncCircle|The Azure AD device sync check failed because the device that on-premises network connection created has been synced into Active Directory via AAD connect, but A
Global: Per branding requirements, please don't use the acronym AAD. We don't create acronyms of trademarked product names. Please spell out as Azure Active Directory (Azure AD) at first mention and use Azure AD thereafter.

2021-06-02 06:14 UTC, opbld31 commented
Docs Build status updates of commit _[79ef9ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79ef9eddef96627c539511b8dd27bd50f85c556c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106020612532780-12896%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gc%2FuBjgWkGnuc%2F7Ea%2BY0TwsZiGLEoQiUiOlQj5Dj87Y%3D&st=2021-06-02T06%3A09%3A16Z&se=2021-07-03T06%3A14%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 06:15 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|azureAdDeviceSyncCheckLongSyncCircle|The Azure AD device sync check failed because the device that on-premises network connection created has been synced into Active Directory via AAD connect, but A
Thanks @cohanley and @Lauragra . Already updated the description following your suggestions. Please have a look when you got time. Thanks!

2021-06-15 09:49 UTC, opbld31 commented
Docs Build status updates of commit _[9916071](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9916071a8466f18d7f761372438b302f56eef66f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150947341295-12896%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0qyjUqbuXP2b28KwemJs94QAWbcINej1hY9N1dV3Nbs%3D&st=2021-06-15T09%3A44%3A02Z&se=2021-07-16T09%3A49%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 06:38 UTC, opbld31 commented
Docs Build status updates of commit _[643294f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/643294fd03012200927c97be15700c657555c95c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cfc63c93)

<a id="cfc63c93"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240638421313-12896%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CIzLXjLq4SCZesHphs%2BMSTBAon4HKGBM4grJCzo7Z3A%3D&st=2021-06-24T06%3A33%3A56Z&se=2021-07-25T06%3A38%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 07:05 UTC, opbld31 commented
Docs Build status updates of commit _[ac8a745](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac8a7450769b57b92e951251122434a06fffc175)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240702238396-12896%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IzUE7u8lLJYUXxHlDTAiuASa5QZB5bVFXRlaKhsB3og%3D&st=2021-06-24T07%3A00%3A40Z&se=2021-07-25T07%3A05%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 23:13 UTC, cohanley approved these changes

2021-07-01 21:37 UTC, JarbasHorst requested changes

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckCloudPcUrlNotAllowListed|During provisioning, a required URL/s couldn't be contacted. Please make sure that all of the required URL’s are allowed through the firewalls and p
Please, replace URL’s with URLs. Also, for clarity and readability I recommend you to rephrase part of the sentence. Suggested revision:

- During provisioning, one or more required URLs couldn't be contacted.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckWVDUrlNotAllowListed|During provisioning, a required WVD URL/s couldn't be contacted. Please make sure that all of the required URL's are allowed through the firewalls and p
Please, replace URL’s with URLs. Also, for clarity and readability I recommend you to rephrase part of the sentence. Suggested revision:

- During provisioning, one or more required WVD URLs couldn't be contacted.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckIntuneUrlNotAllowListed|During provisioning, a required Intune URL/s couldn’t be contacted. Please make sure that all of the required URL's are allowed through the firewalls
Please, replace URL’s with URLs. Also, for clarity and readability I recommend you to rephrase part of the sentence. Suggested revision:

- During provisioning, one or more required Intune URLs couldn't be contacted.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckUnknownError|During provisioning, a required URL/s couldn't be contacted. Please make sure that all of the required URL's are allowed through the firewalls and proxies.|
Please, replace URL’s with URLs. Also, for clarity and readability I recommend you to rephrase part of the sentence. Suggested revision:

- During provisioning, one or more required URLs couldn't be contacted.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|azureAdDeviceSyncCheckDeviceNotFound|The cloud PC computer object can't be found in Azure Active Directory. Please make sure that Azure AD connect is working and syncing frequently so that the cloud
Before using acronyms, I recommend you to spell out the words first followed by the acronym in parentheses. Suggested revision:

- ...can't be found in Azure Active Directory (Azure AD)...

Also, avoid using gerunds where possible; in this case, you can change the sentence to replace working and syncing. Suggested revision:

- Please make sure that Azure AD connect works and syncs frequently so that the cloud PC computer objects are synced to Azure AD.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|azureAdDeviceSyncCheckLongSyncCircle|Checking whether the cloud PC computer object has been synced to Azure Active Directory has timed out. Please make sure that Azure AD connect is working and sync
Before using acronyms, I recommend you to spell out the words first followed by the acronym in parentheses. Suggested revision:

- ...can't be found in Azure Active Directory (Azure AD)...

Also, avoid using gerunds where possible; in this case, you can change the sentence to replace working and syncing. Suggested revision:

- Please make sure that Azure AD connect works and syncs frequently so that the cloud PC computer objects are synced to Azure AD.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|azureAdDeviceSyncCheckUnknownError|Hybrid Azure Active Directory connectivity check failed. Please make sure that Azure AD connect is working and syncing frequently so that the cloud PC computer obj
Before using acronyms, I recommend you to spell out the words first followed by the acronym in parentheses. Suggested revision:

- ...can't be found in Azure Active Directory (Azure AD)...

Also, avoid using gerunds where possible; in this case, you can change the sentence to replace working and syncing. Suggested revision:

- Please make sure that Azure AD connect works and syncs frequently so that the cloud PC computer objects are synced to Azure AD.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckNoSubnetIP|The subnet provided doesn't have IP addresses available. Please make sure that the subnet provided in the on-premises network connection has sufficient IP address
Please, remove the comma after subnet. Suggested revision:

- ...selected subnet or select a...

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckAzurePolicyViolation|The Azure subscription provided cannot be found. Please ensure the Azure subscription is available for provisioning.|
Please, use common contractions to create a friendly, informal tone. Replace cannot  with can't

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|resourceAvailabilityCheckUnknownError|An unknown error occurred while checking Azure resources. Please ensure that all Azure resources meet prerequisites.|
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the after meet. Suggested revision:

- ...resources meet the prerequisites...

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckNoSubscriptionReaderRole|Cloud PC service principal doesn't have sufficient permissions on the Azure subscription. Please make sure that cloud PC service principal has the Reader perm
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before  all appearances of Cloud PC. Also, I recommend you to make *Reader* italic to emphasize the permission required.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckNoResourceGroupOwnerRole|Cloud PC service principal doesn't have sufficient permissions on the Azure resource group. Please make sure that cloud PC service principal has the Owner per
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before  all appearances of Cloud PC. Also, I recommend you to make *Owner* italic to emphasize the permission required.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckNoVNetContributorRole|Cloud PC service principal doesn't have sufficient permissions on the Azure vNet. Please make sure that cloud PC service has the Network contributor permissions
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before all appearances of Cloud PC. Also, I recommend you to make *Network contributor* italic to emphasize the permission required.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckUnknownError|Cloud PC service principal doesn't have sufficient permissions. Please make sure that cloud PC service principal is granted sufficient Azure permissions.|
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add the before  all appearances of Cloud PC.

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|internalServerErrorUnableToRunDscScript|During provisioning, some PowerShell DSC scripts are executed on the cloud PC. Unable to either download these DSC scripts or execute them during the health c
Please, use common contractions to create a friendly, informal tone. Replace is not with isn't

2021-07-01 21:37 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|internalServerUnknownError|Provisioning has failed due to an internal error. Please contact customer support.|
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add The before provisioning

2021-07-02 07:20 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|dnsCheckFqdnNotFound|The DNS resolution failed for the domain name. Possible error causes: 1.The specified Azure vNet's DNS server can't resolve the domain name. Please update the vNet with an appro
Corrected. Thanks.

2021-07-02 07:24 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckFqdnNotFound|While attempting domain join, the domain name could not be found. Please make sure a domain controller for the domain name can be contacted by the vNet defined in the on-prem
Great suggestion. Thanks!

2021-07-02 07:42 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckUnknownError|During provisioning, a required URL/s couldn't be contacted. Please make sure that all of the required URL's are allowed through the firewalls and proxies.|
Corrected all URLs and rephrase sentences. Thanks.

2021-07-02 08:11 UTC, opbld33 commented
Docs Build status updates of commit _[3f8d5fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f8d5fdfcd64c5020508dfbd25f5aeaa147d7b71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107020808388966-12896%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HCilyhOvZ8ZCKlJno6GjCRe0xjTl1%2B4DLg74hrf5FOY%3D&st=2021-07-02T08%3A06%3A04Z&se=2021-08-02T08%3A11%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-02 08:48 UTC, RuiHou105 commented
@JarbasHorst  Thanks for your review. I've resolved all your comments. Please take a second look when you got time. Appreciate it.

2021-07-05 20:15 UTC, JarbasHorst requested changes

2021-07-05 20:15 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckFqdnNotFound|While attempting domain join, the domain name couldn't be found. Please make sure a domain controller for the domain name can be contacted by the vNet defined in the on-premi
Avoid using gerunds where possible; in this case, you can change the sentence to replace attempting. Suggested revision:

- The domain join check failed because the domain name couldn't be found.

2021-07-05 20:15 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckIncorrectCredentials|While attempting domain join, credentials provided for the domain aren't correct. Please update the on-premises network connection with correct credentials.|
Avoid using gerunds where possible; in this case, you can change the sentence to replace attempting. Suggested revision:

- The domain join check failed because the credentials provided for the domain aren't correct.

2021-07-05 20:15 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckOrganizationalUnitNotFound|While attempting domain join, the organizational unit (OU) can't be found. Please provide an OU in the domain. The OU must be in Distinguished Name format. Exam
Avoid using gerunds where possible; in this case, you can change the sentence to replace attempting. Suggested revision:

- The domain join check failed because the organizational unit (OU) can't be found.

2021-07-05 20:15 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckOrganizationalUnitIncorrectFormat|While attempting domain join, the organizational unit (OU) can't be found. Please provide an OU in the domain. The OU must be in Distinguished Name forma
Avoid using gerunds where possible; in this case, you can change the sentence to replace attempting. Suggested revision:

- The domain join check failed because the organizational unit (OU) can't be found.

2021-07-05 20:15 UTC, JarbasHorst commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckAccessDenied|While attempting domain join, the user account provided doesn't have sufficient permissions to join the domain. Please make sure that the account provided has sufficient perm
Avoid using gerunds where possible; in this case, you can change the sentence to replace attempting. Suggested revision:

- The domain join check failed because the user account provided doesn't have sufficient permissions to join the domain.

2021-07-06 02:59 UTC, RuiHou105 commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|adJoinCheckAccessDenied|While attempting domain join, the user account provided doesn't have sufficient permissions to join the domain. Please make sure that the account provided has sufficient perm
corrected. Thanks!

2021-07-06 03:03 UTC, opbld32 commented
Docs Build status updates of commit _[252107e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/252107efebd11e831208638f7d0cddef015777c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107060301316962-12896%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-05T10%3A21%3A31Z&ske=2021-07-12T10%3A26%3A31Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-06T02%3A58%3A03Z&se=2021-08-06T03%3A03%3A03Z&sr=b&sp=r&sig=4TitQ2pymIA60buKiZyAoaoVR0vTYRKq%2B%2BRZax9tV9I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-06 03:05 UTC, RuiHou105 commented
@JarbasHorst All comments resolved. Could you please review/approve it? Thanks ahead.

2021-07-06 18:12 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-07-08 04:40 UTC, Lauragra approved these changes

2021-07-08 04:41 UTC, opbld34 commented
Docs Build status updates of commit _[0b9420a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b9420a5da57a8dce8d44eb6f410adc906ac1868)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080440233749-12896%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A03%3A42Z&ske=2021-07-13T07%3A08%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T04%3A36%3A56Z&se=2021-08-08T04%3A41%3A56Z&sr=b&sp=r&sig=G5Mo6K9I00tRLflllpN4Gh9PynUp3RL%2FAEHZVHJmN6k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 09:30 UTC, opbld33 commented
Docs Build status updates of commit _[91c00e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91c00e2c859bd2ec8fc07c3798a6f7bff21997c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-12896) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/RenameAndAddErrorType/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080929266223-12896%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A21%3A19Z&ske=2021-07-13T09%3A26%3A19Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T09%3A25%3A54Z&se=2021-08-08T09%3A30%3A54Z&sr=b&sp=r&sig=CtFmcBg3ZZ7DqhRWQxROi5R1MCTEkHRRkSa3zBo7Ez8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 03:15 UTC, merged