Docs for SoftwareOATH
microsoftgraph/microsoft-graph-docs pull request #12938
Opened 2021-05-31 06:30 UTC by andres-canello

2021-05-31 06:32 UTC, opbld30 commented
Docs Build status updates of commit _[9d5e729](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d5e72925cdf5083397c192001ec202937f00829)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) | [Details](#user-content-6876a52f61c5e2f3a19a030c1d5513c7-1563b10d)
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) | [Details](#user-content-1ac9db32e52c8638175697f11bb17293-1563b10d)
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) | [Details](#user-content-fb240da6d6662ddb5bd104e75f5c3fd0-1563b10d)
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) | [Details](#user-content-bc4416381ea642f0495a0a1dda7ded62-1563b10d)

<a id="6876a52f61c5e2f3a19a030c1d5513c7-1563b10d"></a>
### [api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="1ac9db32e52c8638175697f11bb17293-1563b10d"></a>
### [api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="fb240da6d6662ddb5bd104e75f5c3fd0-1563b10d"></a>
### [api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="bc4416381ea642f0495a0a1dda7ded62-1563b10d"></a>
### [api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/softwareoathauthenticationmethod-create.md'.`````
 - **Line 27, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/softwareoathauthenticationmethod-update.md'.`````
 - **Line 29, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/softwareoathauthenticationmethod-enablesmssignin.md'.`````
 - **Line 30, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/softwareoathauthenticationmethod-disablesmssignin.md'.`````
 - **Line 31, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/softwareoathauthenticationmethod-resetpassword.md'.`````
 - **Line 31, Column 76**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/passwordresetresponse.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105310630444200-12938%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wd%2BPvp7wfoKAsyE5JR2cuU4U7feppl%2BluIFyehmczJo%3D&st=2021-05-31T06%3A2 [...]

2021-05-31 23:29 UTC, opbld30 commented
Docs Build status updates of commit _[215a3f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/215a3f658ccd42b1341a286706a6d6ba2179c102)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105312327502711-12938%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T527tGHkekoHyeKrgksJE5K0kBbPXFFARp1iZNRbD9I%3D&st=2021-05-31T23%3A24%3A13Z&se=2021-07-01T23%3A29%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-31 23:56 UTC, opbld32 commented
Docs Build status updates of commit _[38dde3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38dde3b357787707f3f666777285eb7a83566477)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0607f770)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |

<a id="0817dce4456c16725d5333633847d38f-0607f770"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml)
 - **Line 10710, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/softwareOathAuthenticationMethods.md'.`````
 - **Line 10713, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/softwareOathAuthenticationMethods-list.md'.`````
 - **Line 10715, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/softwareOathAuthenticationMethods-get.md'.`````
 - **Line 10717, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/softwareOathAuthenticationMethods-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105312355002659-12938%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z8gpxglo1Pkn7Zo1AODTWR8lc08CnFtIhpiYM%2BtjAjY%3D&st=2021-05-31T23%3A51%3A15Z&se=2021-07-01T23%3A56%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 04:41 UTC, opbld32 commented
Docs Build status updates of commit _[2a2c150](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a2c150f07b962e8cdf87f82a01687fe8f8fff0b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-71d0cdfb)
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-71d0cdfb"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml)
 - **Line 10710, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/softwareOathAuthenticationMethods.md'.`````
 - **Line 10713, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/softwareOathAuthenticationMethods-list.md'.`````
 - **Line 10715, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/softwareOathAuthenticationMethods-get.md'.`````
 - **Line 10717, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/softwareOathAuthenticationMethods-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100440015518-12938%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F21j3sJ4WTInvqZqg3jmIvojtyJiWM%2BaPWKShm9P17Y%3D&st=2021-06-10T04%3A36%3A31Z&se=2021-07-11T04%3A41%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 04:49 UTC, opbld31 commented
Docs Build status updates of commit _[650f5dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/650f5dd8d30879e98c9fcf90cfd135b6ff6b882e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100447550485-12938%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zJvWaWrgFezI93RPpIzjbroA%2FcrzY0yoF38%2B2yyyNFo%3D&st=2021-06-10T04%3A44%3A29Z&se=2021-07-11T04%3A49%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 22:58 UTC, opbld31 commented
Docs Build status updates of commit _[8002a5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8002a5e9414e57074dac5fff3684045703ecfdd1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107082256282162-12938%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T10%3A16%3A46Z&ske=2021-07-13T10%3A21%3A46Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T22%3A53%3A06Z&se=2021-08-08T22%3A58%3A06Z&sr=b&sp=r&sig=tjI8OtHwaEe5EFYKzGDjcJ3Qn4whI31nCZUwyqBQIMw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 23:05 UTC, opbld33 commented
Docs Build status updates of commit _[788c273](https://github.com/microsoftgraph/microsoft-graph-docs/commits/788c2733e9208805e29357f08f1b84fe9572cacf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107082303508132-12938%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A57%3A11Z&ske=2021-07-13T08%3A02%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T23%3A00%3A52Z&se=2021-08-08T23%3A05%3A52Z&sr=b&sp=r&sig=aD1fHb%2FLNzcsk870Zk7KuKIAsyXR%2Fh3fsSsdPSYrPiE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 23:40 UTC, mmcla commented on api-reference/beta/resources/authenticationmethods-overview.md
> +|[softwareOathAuthenticationMethod](../resources/softwareoathauthenticationmethod.md)| Allow users to perform multifactor authentication using an application that supporters the OATH specification an
Supports

2021-07-08 23:46 UTC, mmcla commented on api-reference/beta/resources/softwareoathauthenticationmethod.md
> +A representation of a Software OATH token registered to a user. Software OATH is a multi-factor authentication method.
A representation of a software OATH token registered to a user. A software OATH token is a software-based number generator that uses the OATH TOTP standard. A software OATH token is used for multi-factor authentication. Note that this API will not return Microsoft Authenticator authentication method entities, though it will return an entity if Microsoft Authenticator was set up via the third-party software authenticator flow.

2021-07-09 00:40 UTC, andres-canello commented on api-reference/beta/resources/authenticationmethods-overview.md
> +|[softwareOathAuthenticationMethod](../resources/softwareoathauthenticationmethod.md)| Allow users to perform multifactor authentication using an application that supporters the OATH specification an
Done

2021-07-09 00:41 UTC, andres-canello commented on api-reference/beta/resources/softwareoathauthenticationmethod.md
> +A representation of a Software OATH token registered to a user. Software OATH is a multi-factor authentication method.
Done

2021-07-09 00:41 UTC, opbld31 commented
Docs Build status updates of commit _[b2ef35f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2ef35f0bfbb0d9446454fbd2d010bd167e5dca0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107090040296086-12938%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A59%3A36Z&ske=2021-07-13T08%3A04%3A36Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T00%3A36%3A53Z&se=2021-08-09T00%3A41%3A53Z&sr=b&sp=r&sig=dHzw9ZEbh3sFZZmSy5l1Lo5tZKXyP2Y4cftgWcVa9MA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 08:14 UTC, FaithOmbongi requested changes
Proposed minor changes.

- Of note: missing relationship in [authenticationMethod](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) resource topic. Also the [authenticationMethod](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) topic differs from the CSDL in the properties & relationships. Might want to take a look at that too.

2021-07-13 08:14 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethod-delete.md
> +* Authentication admin
```suggestion
When acting on another user, the calling user needs to belong to one of the following directory roles. To learn more about directory roles, see [Azure AD built-in roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
* Global administrator
* Privileged authentication administrator
* Authentication administrator
```

2021-07-13 08:14 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethod-get.md
> +* Authentication admin
```suggestion
When acting on another user, the calling user needs to belong to one of the following directory roles. To learn more about directory roles, see [Azure AD built-in roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
* Global administrator
* Privileged authentication administrator
* Authentication administrator
```

2021-07-13 08:14 UTC, FaithOmbongi commented on api-reference/beta/api/softwareoathauthenticationmethod-list.md
> +* Authentication admin
```suggestion
When acting on another user, the calling user needs to belong to one of the following directory roles. To learn more about directory roles, see [Azure AD built-in roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
* Global administrator
* Privileged authentication administrator
* Authentication administrator
```

2021-07-13 08:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **softwareOathMethods** navigation property to the [authenticationmethod](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethod?view=graph-rest
- Kindly document this relationship.
- I see the [authenticationMethod](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethod?view=graph-rest-beta) resource topic differs from the CSDL in the properties & relationships. Might want to take a look at that too.

2021-07-14 04:15 UTC, andres-canello commented on api-reference/beta/api/authentication-list-methods.md
> +
I added that text as a note because I feel making it part of the description is easier to miss, do you agree?

2021-07-14 04:15 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-delete.md
> +* Authentication admin
Making this change will make this document inconsistent with the wording we have on all ather auth methods docs. I think if we want to change the text we should change all of them.

2021-07-14 04:17 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-get.md
> +* Authentication admin
Same as other comment.

2021-07-14 04:19 UTC, opbld33 commented
Docs Build status updates of commit _[4b276aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b276aaa0ebb1bd1c916ca58b4dcc30b705ddacb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140417397545-12938%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A50%3A40Z&ske=2021-07-20T07%3A55%3A40Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T04%3A14%3A20Z&se=2021-08-14T04%3A19%3A20Z&sr=b&sp=r&sig=L9F1qDBuPCp7%2BQORaXaEcqaCli0w0a%2F0FFtptTRJvxo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 04:19 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
We have removed this section on all other methods that don't support optional query parameters, for consistency I would recommend removing it on these docs as well

2021-07-14 04:19 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Same comment

2021-07-14 04:21 UTC, opbld34 commented
Docs Build status updates of commit _[ae65ca8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae65ca847bf85ba895e0c963535470c52eba5b3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140418444365-12938%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A50%3A51Z&ske=2021-07-20T07%3A55%3A51Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T04%3A15%3A59Z&se=2021-08-14T04%3A20%3A59Z&sr=b&sp=r&sig=Ty019YUhaDCubfwLfcWHmFLEGwSKRrwuy04aZV124gg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 04:23 UTC, opbld30 commented
Docs Build status updates of commit _[05d6474](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05d64744f28f2b7e73bf736375fde286f1ed0029)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140421200847-12938%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A46%3A13Z&ske=2021-07-20T07%3A51%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T04%3A17%3A59Z&se=2021-08-14T04%3A22%3A59Z&sr=b&sp=r&sig=haHEPBHYJUNRwlxeUhEzS10FwPBHOLmvYQqDUSuEtCg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 04:24 UTC, andres-canello commented on api-reference/v1.0/api/authentication-list-methods.md
> +> Listing users' authentication methods only returns methods supported on this API version. See [Azure AD authentication methods API overview](../resources/authenticationmethods-overview.md) for a li
I added that text as a note because I feel making it part of the description is easier to miss, do you agree?

2021-07-14 04:24 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-list.md
> +* Authentication admin
Same comment

2021-07-14 04:24 UTC, opbld33 commented
Docs Build status updates of commit _[b5a6ff6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5a6ff652d6e3bbef615fb498af2664306269107)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140422177158-12938%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T09%3A54%3A23Z&ske=2021-07-20T09%3A59%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T04%3A19%3A52Z&se=2021-08-14T04%3A24%3A52Z&sr=b&sp=r&sig=RUwnHxcd69WqWHieVN3O12rYfXqaNBxmTN17l6pTrnI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 04:28 UTC, andres-canello commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **softwareOathMethods** navigation property to the [authenticationmethod](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethod?view=graph-rest
Can you please suggest the changes needed to reflect this?

2021-07-14 15:04 UTC, FaithOmbongi approved these changes
Approved but recommending an internal follow-up on the right resource that auth methods are r/ships of - is it **authentication** (as per the CSDL) or **authenticationMethod**?

2021-07-27 03:33 UTC, CelesteDG commented
@andres-canello Bumping this back up your queue. Some feedback awaiting your review. Also it looks like some conflict with the changelog.

CC @FaithOmbongi

2021-07-27 04:03 UTC, andres-canello commented
> @andres-canello Bumping this back up your queue. Some feedback awaiting your review. Also it looks like some conflict with the changelog.
> 
> CC @FaithOmbongi

Thanks for checking @CelesteDG, I really need @mmcla input here. I have started a thread to discuss how we untangle this conflict we have.

2021-08-05 21:33 UTC, opbld33 commented
Docs Build status updates of commit _[81edf0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81edf0d369f372fb812d3dcb2deee9beeea3dad0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5bb46f44)

<a id="5bb46f44"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108052133346142-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=SCsfK5jPuupd9SkSIoLsXdNm42tsF%2F%2FW5Lt7PzZlE3Y%3D&st=2021-08-05T21%3A28%3A56Z&se=2021-09-05T21%3A33%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 16:01 UTC, opbld33 commented
Docs Build status updates of commit _[81edf0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81edf0d369f372fb812d3dcb2deee9beeea3dad0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201559456481-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=wrzoyT2MUJCRrBKa72nxtQ0hdRlONcbiTPMgYSuoEv0%3D&st=2021-08-20T15%3A56%3A19Z&se=2021-09-20T16%3A01%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 16:51 UTC, opbld31 commented
Docs Build status updates of commit _[795202d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/795202da4f41739b1092d66f65bfcb868251a435)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201649279004-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=k%2BDde3NfYia4aT9hOrVtwz7jKHlt5AzcOOi%2Fcm265RE%3D&st=2021-08-20T16%3A46%3A03Z&se=2021-09-20T16%3A51%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-29 23:31 UTC, andres-canello commented on api-reference/beta/api/authentication-list-methods.md
> +
Done

2021-08-29 23:33 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-delete.md
> +* Authentication admin
Done

2021-08-29 23:34 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-get.md
> +* Authentication admin
Done

2021-08-29 23:35 UTC, andres-canello commented on api-reference/beta/api/softwareoathauthenticationmethod-list.md
> +* Authentication admin
Done

2021-08-29 23:37 UTC, andres-canello commented on api-reference/v1.0/api/authentication-list-methods.md
> +> Listing users' authentication methods only returns methods supported on this API version. See [Azure AD authentication methods API overview](../resources/authenticationmethods-overview.md) for a li
Done

2021-08-29 23:37 UTC, andres-canello commented on api-reference/v1.0/api/authentication-list-methods.md
>  Retrieve a list of [authentication method](../resources/authenticationmethod.md) objects.
Done

2021-08-29 23:38 UTC, andres-canello commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **softwareOathMethods** navigation property to the [authenticationmethod](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethod?view=graph-rest
Thanks

2021-08-29 23:40 UTC, opbld34 commented
Docs Build status updates of commit _[94af59f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94af59f769ba89dbfaf2ee31afd550db6462c3c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108292338407309-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=QiLGX899u8bYsBM7qRMxRtZuok8PhQHRlcCp39VBN%2B0%3D&st=2021-08-29T23%3A35%3A21Z&se=2021-09-29T23%3A40%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 02:59 UTC, andres-canello commented
@FaithOmbongi @Lauragra I've addressed all comments, can you please review and publish?
@mmcla FYI

2021-08-30 07:41 UTC, opbld33 commented
Docs Build status updates of commit _[834b3a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/834b3a8c3e6ef508341f072fbfa3cded0880dad3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108300738461554-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zclyo7vdE9BgQl2KrPf16LVw%2BJSMpyKAS3lAIMT4xoE%3D&st=2021-08-30T07%3A36%3A14Z&se=2021-09-30T07%3A41%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 08:23 UTC, FaithOmbongi approved these changes
Hi @andres-canello: as resolved internally, I removed the changelog entry for the nav property.

2021-08-31 01:42 UTC, opbld33 commented
Docs Build status updates of commit _[e655dcc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e655dccccefc1e566b9e3acd879ebdadeb222609)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310140311130-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6e4KxIsQWSnWboIC3hnjE%2Fb9uPU7MdGkf7%2BkyM0kA54%3D&st=2021-08-31T01%3A37%3A37Z&se=2021-10-01T01%3A42%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 02:09 UTC, opbld32 commented
Docs Build status updates of commit _[03731ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03731adbde21da86787141b8b67c27de7bf300d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310206339609-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=EM7rLsOx7jO61pM77tadMEz4lRXA6Pty%2FReAbrW6XjQ%3D&st=2021-08-31T02%3A04%3A25Z&se=2021-10-01T02%3A09%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 02:32 UTC, opbld31 commented
Docs Build status updates of commit _[24d722e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24d722e7ad6a2ab98b2975542e21152b82ca0d40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310230568720-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=k24cc6mGudPyoFm0KNYGLoBgqFCQ4T5ePnACS1DDa4Y%3D&st=2021-08-31T02%3A27%3A24Z&se=2021-10-01T02%3A32%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 19:54 UTC, jasonjoh commented
Docs Build status updates of commit _[0e0539a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e0539a00d4b4b5d66c4c2c1c2af06065277aaf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011952327623-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=UN4gxghtjE3mNA4fjEyLKwiXMEk75m1gdt2bplVXOGI%3D&st=2021-09-01T19%3A49%3A20Z&se=2021-10-02T19%3A54%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 20:00 UTC, jasonjoh commented
Docs Build status updates of commit _[9a9fa84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a9fa84227e85491da3f506e7542a2ac0701e658)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109011957526963-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xYge4P66bjq%2FeuoWeuLc6ZcgRiBwOTg%2BbGye3u1Hymg%3D&st=2021-09-01T19%3A55%3A02Z&se=2021-10-02T20%3A00%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-01 20:08 UTC, jasonjoh commented
Docs Build status updates of commit _[5601319](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5601319d461d345abba8dfe5560dd84c14e9fb3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/authentication-list-softwareoathmethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/authentication-list-softwareoathmethods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-softwareoathmethods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/api/softwareoathauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/api/softwareoathauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/softwareoathauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/resources/softwareoathauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/resources/softwareoathauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/softwareoathauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-beta&branch=pr-en-us-12938) (graph-rest-beta) |
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-12938) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-31-Andresc-SoftwareOATH/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109012006416953-12938%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LSbEldfyD9kvKc%2FOV16pbi7keuC7bnClCHmovZNIJD8%3D&st=2021-09-01T20%3A03%3A46Z&se=2021-10-02T20%3A08%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 02:31 UTC, merged