Remove Calendar.ReadWrite from permissions table
microsoftgraph/microsoft-graph-docs pull request #12976
Opened 2021-06-02 20:27 UTC by Jordanndahl

Calendar.ReadWrite should be removed from beta and V1.0 documentation

2021-06-02 20:29 UTC, opbld34 commented
Docs Build status updates of commit _[90d9549](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90d954953088af8232e5d630f22f0a153e921515)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/api/group-update-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update-event?view=graph-rest-1.0&branch=pr-en-us-12976) (>= graph-rest-1.0) | [Details](#user-content-7ba83a39fbe4d43c266dfa4340100933-8acf42ce)
[api-reference/beta/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/beta/api/group-update-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update-event?view=graph-rest-beta&branch=pr-en-us-12976) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-12976) (>= graph-rest-1.0) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12976) |

<a id="7ba83a39fbe4d43c266dfa4340100933-8acf42ce"></a>
### [api-reference/v1.0/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/api/group-update-event.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106022027431920-12976%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e40WWXXtcYuR3ksuSVFjyYy82pMfPhWysvmWtuaV5Zw%3D&st=2021-06-02T20%3A24%3A19Z&se=2021-07-03T20%3A29%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 20:34 UTC, opbld33 commented
Docs Build status updates of commit _[15c792b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15c792bbe0e770e88588a219a3d9d421e68cff21)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/api/group-update-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update-event?view=graph-rest-1.0&branch=pr-en-us-12976) (>= graph-rest-1.0) | [Details](#user-content-7ba83a39fbe4d43c266dfa4340100933-d9eda2a2)
[api-reference/beta/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/beta/api/group-update-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update-event?view=graph-rest-beta&branch=pr-en-us-12976) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-12976) (>= graph-rest-1.0) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12976) |

<a id="7ba83a39fbe4d43c266dfa4340100933-d9eda2a2"></a>
### [api-reference/v1.0/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/api/group-update-event.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106022032247796-12976%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bjnYocpzYITZEfRdPFAAJWDoeIFy%2F7GzOL66XCH3DMM%3D&st=2021-06-02T20%3A29%3A07Z&se=2021-07-03T20%3A34%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 18:37 UTC, opbld32 commented
Docs Build status updates of commit _[4b2b072](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b2b07288c23baeaf63ba499ce2faa71b109d25a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/api/group-update-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update-event?view=graph-rest-1.0&branch=pr-en-us-12976) (>= graph-rest-1.0) | [Details](#user-content-7ba83a39fbe4d43c266dfa4340100933-77d2e38c)
[api-reference/beta/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/beta/api/group-update-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-update-event?view=graph-rest-beta&branch=pr-en-us-12976) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-12976) (>= graph-rest-1.0) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-12976) |

<a id="7ba83a39fbe4d43c266dfa4340100933-77d2e38c"></a>
### [api-reference/v1.0/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodah-group-doc-updates/api-reference/v1.0/api/group-update-event.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106041836110664-12976%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ycUntpV1cYRdIROAje%2F9ICImtoQi2xJKEVgqTz%2FAsPE%3D&st=2021-06-04T18%3A32%3A35Z&se=2021-07-05T18%3A37%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 20:31 UTC, Jordanndahl commented
#sign-off

2021-07-09 21:07 UTC, Lauragra commented on api-reference/v1.0/resources/printerstatus.md
>  |developerLow|33|The device is low on developer.|
Please remove the unrelated changes from this PR. Is it possible that you pulled from master instead of main to update your branch?

2021-07-19 20:23 UTC, FaithOmbongi requested changes
- Seems you pulled changes from someone else's PR? Only the group-update-event.md files seem related to the change you wish to make.
- The changelog is not required for this fix. Also kindly note that the changelog.md was deprecated on favor of the workload changelog JSONs.

2021-07-19 20:23 UTC, FaithOmbongi commented on api-reference/v1.0/resources/printerstatus.md
>  |developerLow|33|The device is low on developer.|
+1 for Laura's feedback.

2021-07-27 03:26 UTC, CelesteDG commented
@Jordanndahl - Bringing this back up to your inbox so you can see that some changes are being requested. Thank you.

2021-08-17 20:22 UTC, closed without merging

2023-03-17 09:37 UTC, FaithOmbongi commented
The changes are live. Removing the changes requested label to avoid unactionable notifications.