Exposing property recommendationLookBackDuration to accessReviewSched…
microsoftgraph/microsoft-graph-docs pull request #12973
Opened 2021-06-02 19:31 UTC by shubhamguptacal

Recommendations for access reviews are calculated by looking back at 30 days of data(w.r.t the start date of the review) by default. However, in some scenarios, customers want to change how far back to look at and want to configure 60 days, 90 days, etc. instead. This setting allows customers to configure this duration.

2021-06-02 19:33 UTC, opbld31 commented
Docs Build status updates of commit _[0beaa2f](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/0beaa2fb79dc4b9305166528e8236e55c3965030)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021931519980-12973%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Az%2F%2BHQqlTCG0RRuT%2F2y6enBfOCKxTEgNKG%2BNgRZFB7M%3D&st=2021-06-02T19%3A28%3A19Z&se=2021-07-03T19%3A33%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 01:40 UTC, opbld33 commented
Docs Build status updates of commit _[8d4b38c](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/8d4b38c737767c91e343a226ba5b61fed965114f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106040139105519-12973%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HaaIHBPidkzIUJfg115fdYUSQgt6Qn5mRodITOecHQY%3D&st=2021-06-04T01%3A35%3A39Z&se=2021-07-05T01%3A40%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 20:46 UTC, opbld31 commented
Docs Build status updates of commit _[829c04d](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/829c04d292c0f96dbd221650ca193b2c8356429f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106182040540810-12973%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FUAuKE226T4t3JyAmv7GL4ZZDLNoh%2Bwhre1%2Fo2lufdY%3D&st=2021-06-18T20%3A41%3A42Z&se=2021-07-19T20%3A46%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 21:16 UTC, opbld33 commented
Docs Build status updates of commit _[13dcf9d](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/13dcf9dc97614ea839932182d344a0733010f52e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106182115273676-12973%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ilwZw7e3JpBdmc%2BnCpBkVa%2FnrNBMeoRA27iE2hPZsyY%3D&st=2021-06-18T21%3A11%3A54Z&se=2021-07-19T21%3A16%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 20:45 UTC, opbld30 commented
Docs Build status updates of commit _[9206922](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/9206922d8834b891f7b21ad96aa01865d3b014c5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 20:51 UTC, opbld30 commented
Docs Build status updates of commit _[4368773](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/4368773f7e1b67b4ea0aa7eadf3ef7e8fb1405f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107272049366540-12973%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-27T09%3A08%3A08Z&ske=2021-08-03T09%3A13%3A08Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T20%3A46%3A06Z&se=2021-08-27T20%3A51%3A06Z&sr=b&sp=r&sig=26a143etMKgYt7DEzopNGVfOVlK0DaQuPJLtHqsJJbg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 21:55 UTC, isabelleatmsft requested changes

2021-08-03 21:55 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewreviewer.md
> +# accessReviewReviewer resource type
@FaithOmbongi does this resource type need to be added to the TOC?

2021-08-03 21:55 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewreviewer.md
> +# accessReviewReviewer resource type
And maybe we should add an explainer of the new "contacted reviewers" concept to [Assign reviewers to your access review definition using the Microsoft Graph API](/graph/accessreviews-scope-concept)

2021-08-03 21:55 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewinstance.md
> +| contactedReviewers   |[accessReviewReviewer](../resources/accessreviewreviewer.md) collection| This is a read-only property. In the access review process, reviewers(who are users) are contacted to
```suggestion
| contactedReviewers   |[accessReviewReviewer](../resources/accessreviewreviewer.md) collection| Returns the collection of reviewers who were contacted to complete this review based on the configuration of `reviewers` and `fallbackReviewers` properties during accessReviewScheduleDefinition creation or updates. Use this property to determine which users were contacted to complete a review. Supports `$select`. Read-only. |
```

2021-08-03 21:55 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewreviewer.md
> +In the access review process, reviewers(who are users) are contacted to do the review. Based on the reviewers configuration(groups, managers, etc.), the expanded list of users is constructed and thos
```suggestion
This navigation link returns the collection of users who are contacted to complete a review, expanded to show individual users instead of reviewer types, such as group owner or manager. In the access review process, reviewers (who are users) are determined based on the configuration of the 'reviewers' and 'fallbackReviewers' properties of the [accessReviewScheduleDefinition](accessreviewscheduledefinition.md). From these configurations of [accessReviewScope](accessreviewscope.md) objects, the expanded list of users is constructed and those reviewers are contacted to do the review when the review starts.
```

2021-08-03 21:55 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewreviewer.md
> +| createdDateTime | DateTimeOffset | Date when the reviewer was added |
@shubhamguptacal is it the date when the reviewer was added or contacted?

2021-08-03 21:55 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewschedulesettings.md
> +| recommendationLookBackDuration | Duration| Recommendations for access reviews are calculated by looking back at 30 days of data(w.r.t the start date of the review) by default. However, in some scen
```suggestion
| recommendationLookBackDuration | Duration| Optional field. Indicates the time period of inactivity (with respect to the start date of the review instance) that recommendations will be configured from. Recommendation will be to deny if user is never active during the look back duration. Supported durations are 30, 60, or 90 days.  |
```

2021-08-03 21:58 UTC, isabelleatmsft commented
@FaithOmbongi , quick explanation of these changes as you review:
1. We are adding "contactedReviewers" on the review instance level, which informs the admins who the reviewers actually are that were contacted for each instance, instead of only having them rely on the accessReviewScope dynamic types such as group owner or manager.
2. We are making review recommendations more flexible - now, admins can configure recommendations to be calculated based on 30, 60 or 90 days of inactivity.

2021-08-04 10:52 UTC, FaithOmbongi requested changes
- contactedReviewers, definition, and decisions are navigation properties of accessReviewInstance. Let's move them to relationships.
- I see isDraft & customData properties returned in response objects but are hidden properties. Could you look into this?
- Cleaning up: let's ensure all properties in the properties tables are ordered. This improves scanning by our customers.
- Changelog fixes.

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstance.md
> +| definition |[accessReviewScheduleDefinition](accessreviewscheduledefinition.md) | There is exactly one **accessReviewScheduleDefinition** associated with each instance. It is the parent schedule fo
```suggestion
| definition |[accessReviewScheduleDefinition](accessreviewscheduledefinition.md) | This is the parent schedule for the instance. There is exactly one **accessReviewScheduleDefinition** associated with each instance. |
```

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstancedecisionitemresource.md
> +Every decision item in an access review represents a principal's access to a resource. accessReviewInstanceDecisionItemResource represents the resource associated with the decision item. accessReview
```suggestion
Every decision item in an access review represents a principal's access to a resource that is identified by an accessReviewInstanceDecisionItemResource object. accessReviewInstanceDecisionItemResource is an open type that allows for other properties to be passed in.
```

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewreviewer.md
> +# accessReviewReviewer resource type
> does this resource type need to be added to the TOC?

No, shouldn't be exposed in the TOC.

> And maybe we should add an explainer of the new "contacted reviewers" concept to Assign reviewers to your access review definition using the Microsoft Graph API

Might be off because the article covers only accessReviewScheduleDefinition which doesn't have this property.

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewreviewer.md
> +Inherits from [accessReviewScope](../resources/accessreviewscope.md).
```suggestion
Inherits from [entity](entity.md).
```

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewreviewer.md
> +| createdDateTime | DateTimeOffset | Date when the reviewer was added |
```suggestion
| id | String | Identifier of the reviewer. Inherited from [entity](entity.md). |
| displayName | String | Name of reviewer. |
| userPrincipalName | String | User principal name of the user. |
| createdDateTime | DateTimeOffset | Date when the reviewer was added. |
```

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewreviewer.md
> +  "createdDateTime": "DateTimeOffset"
```suggestion
  "createdDateTime": "String (timestamp)",
```

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewreviewer.md
> +description: "Represents a contacted reviewer for an access review."
```suggestion
description: "Represents a reviewer who was contacted for an access review."
```

2021-08-04 10:52 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewreviewer.md
> +| createdDateTime | DateTimeOffset | Date when the reviewer was added |
Can reviewers be added and contacted on different dates? Or do we capture dates of reminder notifications?
Proposed description
_The date when the reviewer was [added/contacted] for the access review._

2021-08-04 10:52 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +          },
- All entries to be in one ChangeList since they affect the same workload.
- Same Id for all entries.
- Sub area is Governance.

2021-08-04 10:54 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewreviewer.md
> +author: "shubhamguptacal"
Isabelle's alias. Need [single point of contact ](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103185/GitHub-owners)for all customer issues relating to access reviews.

2021-08-09 22:18 UTC, opbld33 commented
Docs Build status updates of commit _[3a5e568](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/3a5e5686f564cdd910c5485e4950009137117816)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108092216303469-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=DhbjKoWUI3qtl%2FNPrULFjCYt4dSkjHGVgUXyU97IQ1E%3D&st=2021-08-09T22%3A13%3A54Z&se=2021-09-09T22%3A18%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 22:21 UTC, opbld33 commented
Docs Build status updates of commit _[e89755c](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/e89755c5d2f66289e837c597e02ed2987492b173)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108092219271235-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Y52g42mOrfBRwmWrWrk8zCnsQ8lN5GII69VLScap8Wk%3D&st=2021-08-09T22%3A15%3A59Z&se=2021-09-09T22%3A20%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 22:25 UTC, opbld30 commented
Docs Build status updates of commit _[177f08a](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/177f08ad7040d220b0fb9e232414c958b5c1f958)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108092223405928-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=EDSK4eTs0%2B86CoQdZKUUotfVIWIz%2Fwy4MChEYYla8p4%3D&st=2021-08-09T22%3A20%3A04Z&se=2021-09-09T22%3A25%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 22:26 UTC, isabelleatmsft approved these changes

2021-08-10 06:48 UTC, FaithOmbongi reviewed
@isabelleatmsft , let's alphabetically order the properties in the properties tables of accessReviewInstance and accessReviewReviewer resources. This improves scanning by our customers.

2021-08-10 06:48 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +            "Id": "48e7726c-c31d-11eb-995f-5903f88189f5",
Same id for the ChangeList
```suggestion
            "Id": "48e9d736-c31d-11eb-995f-5903f88189f5",
```

2021-08-11 04:37 UTC, opbld31 commented
Docs Build status updates of commit _[20d00eb](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/20d00eb7f3fec219078451046fc877efa0cf5ca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110436239111-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=TBmjMg4IDOj3VQSKt2ukMOe3qbszLfvlJCnyCZWG4CE%3D&st=2021-08-11T04%3A32%3A57Z&se=2021-09-11T04%3A37%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 04:40 UTC, opbld31 commented
Docs Build status updates of commit _[1551a1c](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/1551a1ce2968e9cfe9d314f7a40de2f65b0e16b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110439327664-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=H3Ai943xv8md%2BG%2FYl%2F6ABjpMwe5BKVGntY0lAkmHFr4%3D&st=2021-08-11T04%3A35%3A49Z&se=2021-09-11T04%3A40%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 04:42 UTC, opbld32 commented
Docs Build status updates of commit _[5cc07a8](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/5cc07a89e39d17cd2c1ef38a377315e3b4aaf710)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110440401964-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=sZDyajY7w8C8KxpWEbUQUr253gP4Xy3weOz5zI8vyx4%3D&st=2021-08-11T04%3A37%3A26Z&se=2021-09-11T04%3A42%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 04:43 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewreviewer.md
> +| createdDateTime | DateTimeOffset | Date when the reviewer was added |
Updated

2021-08-11 04:44 UTC, opbld30 commented
Docs Build status updates of commit _[375966b](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/375966be69d5207b718ea9d7a6bd1150694db1f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110442585660-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=N4eZvkB2JCoGVEwSPTh%2B12EFa7QaMOgXftiKMUF%2FqEI%3D&st=2021-08-11T04%3A39%3A28Z&se=2021-09-11T04%3A44%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 04:47 UTC, isabelleatmsft commented
alphabetized properties and moved contactedReviewers, definitions and decisions to relationships

2021-08-11 04:47 UTC, opbld32 commented
Docs Build status updates of commit _[1ae8e74](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/1ae8e7413f3c5b4c4ce8e6e431bdd8f6add234f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110445542048-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=gPVqm3Q%2FZ6WDGOAEALrTN9K3SEFsm71V7RWyyGBIi2I%3D&st=2021-08-11T04%3A42%3A34Z&se=2021-09-11T04%3A47%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 06:21 UTC, opbld33 commented
Docs Build status updates of commit _[9b425df](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/9b425df2444779d24dfbe3c06de13db2417c6952)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e8e0c89f)

<a id="e8e0c89f"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110621169571-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=VB2WlB25cb8Sv3lcnwmSCPCkSz4vXTaRXFlCHY38DqQ%3D&st=2021-08-11T06%3A16%3A29Z&se=2021-09-11T06%3A21%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 06:22 UTC, FaithOmbongi approved these changes

2021-08-11 11:23 UTC, opbld30 commented
Docs Build status updates of commit _[9b425df](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/9b425df2444779d24dfbe3c06de13db2417c6952)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstancedecisionitemresource.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewinstancedecisionitemresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstancedecisionitemresource?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewreviewer.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewreviewer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewer?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewschedulesettings.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/api-reference/beta/resources/accessreviewschedulesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewschedulesettings?view=graph-rest-beta&branch=pr-en-us-12973) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-update/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108111121427614-12973%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7YeTlLdLFPFRWjWwk9XmNqTC9W8qJZE%2FgxJfpKZszVI%3D&st=2021-08-11T11%3A18%3A19Z&se=2021-09-11T11%3A23%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 03:13 UTC, merged