EDU Assignments V1.0 (new release)
microsoftgraph/microsoft-graph-docs pull request #12993
Opened 2021-06-03 19:47 UTC by sharaaU7

We are adding v1.0 documentation for EDU assignments as we are taking graph API to V1.0

2021-06-03 19:49 UTC, opbld31 commented
Docs Build status updates of commit _[0ae7813](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ae7813461fb88bae3627cd5ad6e82c6750003a5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :x:Error | | [Details](#user-content-da61d3d8efddcda3b0a5d8938dc6fe65-e9ff3f62)
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :x:Error | | [Details](#user-content-6a0bd087acc6ee57d79e92bdb8f01d73-e9ff3f62)
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :x:Error | | [Details](#user-content-f05ed8af3537a22faec330918913d6e9-e9ff3f62)
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :x:Error | | [Details](#user-content-d9ae4fcb879baef35c4ab21c90c86832-e9ff3f62)
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :x:Error | | [Details](#user-content-b213fd10763a57fd238c274355270fe0-e9ff3f62)
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :x:Error | | [Details](#user-content-bfd8c19de3575aa712e64aac5152826f-e9ff3f62)
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :x:Error | | [Details](#user-content-f5492cae9efc7da02a1abee26b850abc-e9ff3f62)
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :x:Error | | [Details](#user-content-600dfb56ffed50cff3151220e78b7d05-e9ff3f62)
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-update.md) | :x:Error | | [Details](#user-content-f44076ba0efbd1fb7d282d7ebc3a1517-e9ff3f62)
[api-reference/v1.0/api/educationassignmentdefaults-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentdefaults-get.md) | :x:Error | | [Details](#user-content-1e0c5d59830f33817754565ea7d13883-e9ff3f62)
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :x:Error | | [Details](#user-content-653b6860603451598ea67d0ca83e5274-e9ff3f62)
[api-reference/v1.0/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentresource-delete.md) | :x:Error | | [Details](#user-content-2236923b98e5a2c3d2951bc86ae774e8-e9ff3f62)
[api-reference/v1.0/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentresource-get.md) | :x:Error | | [Details](#user-content-87ea1e1fc1c69fa7194c2ff768c2dccd-e9ff3f62)
[api-reference/v1.0/api/educationassignmentsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentsettings-get.md) | :x:Error | | [Details](#user-content-330500bd13f0fb6762fd8def5d2f0c4f-e9ff3f62)
[api-reference/v1.0/api/educationassignmentsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentsettings-update.md) | :x:Error | | [Details](#user-content-dd855bf0080de4f0e33f8e2ed45c5fb8-e9ff3f62)
[api-reference/v1.0/api/educationcategory-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationcategory-delete.md) | :x:Error | | [Details](#user-content-d02c8f4c3487f1af4a6bb554c458dc17-e9ff3f62)
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationoutcome-update.md) | :x:Error | | [Details](#user-content-51166e9c1e8eaef40c176a57fbc8d8f7-e9ff3f62)
[api-reference/v1.0/api/educationrubric-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationrubric-delete.md) | :x:Error | | [Details](#user-content-6d7c3f10ec497469a766ec1de7cd7301-e9ff3f62)
[api-reference/v1.0/api/educationrubric-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationrubric-get.md) | :x:Error | | [Details](#user-content-317701bdb55301a95834c8097e39987c-e9ff3f62)
[api-reference/v1.0/api/educationrubric-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationrubric-update.md) | :x:Error | | [Details](#user-content-ffcd82434e2169f2cfb59d8172f35f1d-e9ff3f62)
[api-reference/v1.0/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmission-get.md) | :x:Error | | [Details](#user-content-0f10d743bbd31fa195ea5fbfc1b55778-e9ff3f62)
[api-reference/v1.0/api/educationsubmission-list-outcomes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmission-list-outcomes.md) | :x:Error | | [Details](#user-content-0cb981c984f2229d1f766057e6297f0e-e9ff3f62)
[api-reference/v1.0/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmission-list-resources.md) | :x:Error | | [Details](#user-content-d7f10f00a6d3e3a0274cfd0c0958266a-e9ff3f62)
[api-reference/v1.0/api/educationsubmission-return.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmission-return.md) | :x:Error | | [Details](#user-content-eba94ce262f918b8c308528084f0b273-e9ff3f62)
[api-reference/v1.0/api/educationsubmission-submit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmission-submit.md) | :x:Error | | [Details](#user-content-824281fcc0458c5365bca9e50f09b87c-e9ff3f62)
[api-reference/v1.0/api/educationsubmission-unsubmit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmission-unsubmit.md) | :x:Error | | [Details](#user-content-37f8421db112673cdf452353f4c94ba5-e9ff3f62)
[api-reference/v1.0/api/educationsubmissionresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmissionresource-delete.md) | :x:Error | | [Details](#user-conte [...]

2021-06-03 21:28 UTC, opbld34 commented
Docs Build status updates of commit _[56864f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56864f37985f929bf899fc8290f4be75167b7789)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignmentsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentsettings-get.md) | :x:Error | | [Details](#user-content-330500bd13f0fb6762fd8def5d2f0c4f-3119f713)
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationoutcome-update.md) | :x:Error | | [Details](#user-content-51166e9c1e8eaef40c176a57fbc8d8f7-3119f713)
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :warning:Warning | | [Details](#user-content-600dfb56ffed50cff3151220e78b7d05-3119f713)
[api-reference/v1.0/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationclass-list-assignments.md) | :warning:Warning | | [Details](#user-content-ef3e0a8407d71f02da14d2566c95ce6b-3119f713)
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-list-assignments.md) | :warning:Warning | | [Details](#user-content-91bc6aabd5b9e1aa60b4ca142c41bf62-3119f713)
[api-reference/v1.0/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-post-rubrics.md) | :warning:Warning | | [Details](#user-content-f33a0c01a661ec3be7069ce540fe3e1c-3119f713)
[api-reference/v1.0/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationcategory.md) | :warning:Warning | | [Details](#user-content-e23536feeaaaf821508f1e794d182981-3119f713)
[api-reference/v1.0/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentresource-delete.md) | :bulb:Suggestion | | [Details](#user-content-2236923b98e5a2c3d2951bc86ae774e8-3119f713)

<a id="330500bd13f0fb6762fd8def5d2f0c4f-3119f713"></a>
### [api-reference/v1.0/api/educationassignmentsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentsettings-get.md)
 - **Line 65, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-educationassignmentsettings-csharp-snippets.md'.`````
 - **Line 69, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-educationassignmentsettings-javascript-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-educationassignmentsettings-objc-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-educationassignmentsettings-java-snippets.md'.`````

<a id="51166e9c1e8eaef40c176a57fbc8d8f7-3119f713"></a>
### [api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationoutcome-update.md)
 - **Line 147, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-educationpointsoutcome-javascript-snippets.md'.`````
 - **Line 151, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-educationpointsoutcome-csharp-snippets.md'.`````
 - **Line 155, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/update-educationpointsoutcome-objc-snippets.md'.`````
 - **Line 159, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/update-educationpointsoutcome-java-snippets.md'.`````
 - **Line 248, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/update-educationoutcome-javascript-snippets.md'.`````
 - **Line 252, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/update-educationoutcome-csharp-snippets.md'.`````
 - **Line 256, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/update-educationoutcome-objc-snippets.md'.`````
 - **Line 260, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/update-educationoutcome-java-snippets.md'.`````
 - **Line 62, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````

<a id="600dfb56ffed50cff3151220e78b7d05-3119f713"></a>
### [api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create educationRubric' is duplicated with other articles: 'v1.0/api/educationassignment-put-rubric.md(10,1), v1.0/api/educationuser-post-rubrics.md(10,1)'. First level headings must be unique within a docset.`````

<a id="ef3e0a8407d71f02da14d2566c95ce6b-3119f713"></a>
### [api-reference/v1.0/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationclass-list-assignments.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationclass-list-assignments.md(2,8), v1.0/api/educationuser-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'v1.0/api/educationclass-list-assignments.md(10,1), v1.0/api/educationuser-list-assignments.md(10,1)'. First level headings must be unique within a docset.`````

<a id="91bc6aabd5b9e1aa60b4ca142c41bf62-3119f713"></a>
### [api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-list-assignments.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationclass-list-assignments.md(2,8), v1.0/api/educationuser-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'v1.0/api/educationclass-list-assignments.md(10,1), v1.0/api/educationuser [...]

2021-06-03 22:48 UTC, opbld33 commented
Docs Build status updates of commit _[8c0410d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c0410dfc8c52d4c13cc2cdb471c5410e49e8eb8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationclass-list-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-ef3e0a8407d71f02da14d2566c95ce6b-e0127d5e)
[api-reference/v1.0/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationoutcome-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-51166e9c1e8eaef40c176a57fbc8d8f7-e0127d5e)
[api-reference/v1.0/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-list-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-91bc6aabd5b9e1aa60b4ca142c41bf62-e0127d5e)
[api-reference/v1.0/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-post-rubrics.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-f33a0c01a661ec3be7069ce540fe3e1c-e0127d5e)
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-remove-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-remove-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-remove-category?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentdefaults-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/micr [...]

2021-06-03 22:59 UTC, opbld34 commented
Docs Build status updates of commit _[23aabc3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23aabc37167ff73eabbce3728e48dadf2c5102d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-remove-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-remove-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-remove-category?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-setupresourcesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentdefaults-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentdefaults-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentdefaults-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-update?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentsettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentsettings-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignmentsettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignmentsettings-update.md) | :white_check_mark:Succeeded |  [...]

2021-06-04 00:44 UTC, opbld31 commented
Docs Build status updates of commit _[95d49de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95d49dec8eac57e8295afea5f5cd01c7e2eb0087)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/education-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-8cbfaf04b7cdebb272d2a23aecc85450-9ad309a5)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9ad309a5)
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=g [...]

2021-06-04 04:59 UTC, opbld30 commented
Docs Build status updates of commit _[cdf5756](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cdf57569b0a32f50b5edb3eddd7cd58d8e8c23e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-2b1c8d34)
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-remove-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-remove-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-remove-category?view=graph-rest-1.0&branch=pr-en- [...]

2021-06-04 05:47 UTC, opbld31 commented
Docs Build status updates of commit _[8b9a706](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b9a7065fd1e4969d5d2fdcee368ed1721843c3a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-c0eb3788)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-c0eb3788)
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest- [...]

2021-06-04 15:53 UTC, opbld32 commented
Docs Build status updates of commit _[b934428](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9344287b3f8bc55affbbbc5900f113234e08590)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-7c02b985)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-7c02b985)
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest- [...]

2021-06-04 19:30 UTC, isvargasmsft commented on api-reference/beta/api/educationassignment-put-rubric.md
> +# Attach educationRubric to an Assignment
Please write assignment in lower caps.

2021-06-04 19:31 UTC, isvargasmsft commented on api-reference/beta/api/educationassignmentresource-delete.md
> +description: "Delete a specific resource attached to an assignment."
Please update line 16 as well. The description should match the first sentence in the article.

2021-06-04 19:34 UTC, isvargasmsft commented on api-reference/beta/api/educationclass-list-assignments.md
> +# List class specific user assignments
Why are we changing these titles? Please note this new title does not meet the requirements here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title

It's not clear and difficult to understand because it uses several nouns together. Is there a reason to change these titles?

2021-06-04 19:37 UTC, isvargasmsft commented on api-reference/beta/api/educationoutcome-update.md
> -# [HTTP](#tab/http)
I don't understand the changes to this file. Why are we removing these sections?
If this PR intention is to publish a feature from beta to v1 I don't think we should be editing the beta files.

2021-06-04 19:39 UTC, isvargasmsft commented on api-reference/beta/api/educationuser-list-assignments.md
> +# List user's all assignments
I'd suggest: List assignments of a user. 

It's easier to understand for non-native readers.

2021-06-04 19:41 UTC, isvargasmsft commented on api-reference/beta/api/educationuser-post-rubrics.md
> -# [C#](#tab/csharp)
Is there a reason to remove these sections and edit beta files?

2021-06-04 19:43 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-add-categories.md
> +Add one or more existing [educationCategory](../resources/educationcategory.md) objects to this [educationAssignment](../resources/educationassignment.md).
Please use "... objects to a educationAssignment" instead of "objects to this educationAssignment". "a" instead of "this".
Another option is "to the specified".

2021-06-04 19:46 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-delete-rubric.md
> +Remove an [educationRubric](../resources/educationrubric.md) from an [educationAssignment](../resources/educationassignment.md).  This does not delete the rubric itself.
Please add a blank line between the 2 sentences, and re-phrase: This method does not delete the rubric...

2021-06-04 19:47 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-delete-rubric.md
> +# [HTTP](#tab/http)
Line 56: I think you can remove this line. Tabs are automatically generated for the document.

2021-06-04 21:17 UTC, isvargasmsft requested changes
Hello! 

Thank you for your work on this PR. 

May I please clarify the reason why we are editing beta documents in this PR? It's not clear and I need to understand why we are making such changes. 

Thank you!

Isaac Vargas

2021-06-04 22:50 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-get.md
> +# [HTTP](#tab/http)
Global: Remove this H1 as well when you remove the other SDK snippet H1s.

2021-06-04 23:08 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-post-resources.md
> +description: "odata.type to indicate which type of resource is being created. Note that file-based resources must first be uploaded to the assignments **resourceFolder**."
The description should be a summary statement about the topic so it's best to use the first sentence of the article or similar. "Create an education assignment resource."

2021-06-07 06:46 UTC, opbld33 commented
Docs Build status updates of commit _[d933534](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d933534ba55dbe7bdbe728a8cdd5f76c5d9152cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-d2f24a9e)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d2f24a9e)
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest- [...]

2021-06-07 13:18 UTC, opbld30 commented
Docs Build status updates of commit _[a542c3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a542c3e47037d4ed38a0df81bb6054d7cda8b618)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-8aefcaab)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-8aefcaab)
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest- [...]

2021-06-07 19:20 UTC, opbld30 commented
Docs Build status updates of commit _[19555d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19555d1cf90b3538e92401f0c3a1a8ba2cb3092a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-77b5ef88)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-77b5ef88)
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest- [...]

2021-06-09 21:58 UTC, opbld34 commented
Docs Build status updates of commit _[aa342f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa342f5a1065e2c2be60b60b4221d332e9777bf4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-0da5a921)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-0da5a921)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr [...]

2021-06-09 23:51 UTC, ssriniva-msft approved these changes

2021-06-09 23:51 UTC, ssriniva-msft commented on api-reference/beta/api/educationassignment-add-categories.md
>  author: "dipakboyed"
Question for @Lauragra  - is it possible to specify multiple comma/semicolon delimited aliases here? Dipak isn't going to be owning this docset :) - would like to have a couple of others instead

2021-06-10 02:53 UTC, Lauragra commented on api-reference/beta/api/educationassignment-add-categories.md
>  author: "dipakboyed"
We prefer to have one owner specified here. That is the person who will be assigned Issues or PRs related to the content. I'm not actually sure that we can have multiple owners. I would put the GitHub name here of the individual who is on point to respond to feedback.

2021-06-10 04:22 UTC, opbld33 commented
Docs Build status updates of commit _[f82ffb7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f82ffb7679a1756cb6d8bc93244c3730374d2abb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-988e6cd9)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-988e6cd9)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr [...]

2021-06-10 05:27 UTC, opbld31 commented
Docs Build status updates of commit _[a230a35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a230a35a804585880b3e7e7381fdc6849779fe27)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-ea686d7e)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-ea686d7e)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationoutcome-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationoutcome-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationoutcome-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-post-rubrics.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-post-rubrics.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-post-rubrics?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-update?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr [...]

2021-06-10 05:39 UTC, opbld33 commented
Docs Build status updates of commit _[b8fb6a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8fb6a4860353c0d9ddc0ecb81c4562bfe40a8b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-f66bd99d)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-f66bd99d)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs. [...]

2021-06-10 05:53 UTC, opbld34 commented
Docs Build status updates of commit _[08efa3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08efa3ba09d4ca39267bcdb99bf2cc4e8aef1d3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-180239aa)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-180239aa)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs. [...]

2021-06-10 06:23 UTC, opbld32 commented
Docs Build status updates of commit _[8c3c8d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c3c8d4b469379ea16ce8e3e1792efa0deecd8f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-bfeff4a7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-bfeff4a7)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs. [...]

2021-06-10 14:43 UTC, opbld33 commented
Docs Build status updates of commit _[912c474](https://github.com/microsoftgraph/microsoft-graph-docs/commits/912c474e271138dfbb832b656db878cc0f012361)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-1ae2c46c)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1ae2c46c)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs. [...]

2021-06-10 14:50 UTC, opbld30 commented
Docs Build status updates of commit _[f960dc3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f960dc32c41a94ce7dc9b80068216ad7d47b05e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-56fc42f9)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-56fc42f9)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs. [...]

2021-06-10 16:18 UTC, isvargasmsft commented on api-reference/beta/api/educationassignmentresource-delete.md
> +Delete a specific resource attached to an assignment. Only teachers in the class can remove a resource. After an assignment has been published to students, teachers cannot remove resources that are m
Line 16: Let's improve this section. 
Delete a specific resource attached to an assignment. 
//blank line
In general, only teachers in the class can remove a resource. However, teachers cannot remove resources marked as "distributeToStudents", after the assignment has been published to students.

2021-06-10 16:20 UTC, isvargasmsft commented on api-reference/beta/api/educationclass-list-assignments.md
>  description: "Retrieve a list of assignment objects. A teacher or an application executing with application permissions is allowed to see all assignment objects for the class. Students can only see a
Please change "is allowed" for "can". Please make the change in line 16 as well.

2021-06-10 16:22 UTC, isvargasmsft commented on api-reference/beta/api/educationclass-list-assignments.md
> +title: "List class specific user assignments"
Please rephrase:
List user assignments for a class.

2021-06-10 16:23 UTC, isvargasmsft commented on api-reference/beta/api/educationclass-list-assignments.md
> +title: "List class specific user assignments"
Please make the change in the ToC as well.

2021-06-10 16:32 UTC, isvargasmsft commented on api-reference/beta/api/educationuser-list-assignments.md
>  description: "Returns a list of assignments assigned to a user for all classes. This utility namespace allows a caller to find all a student's assignments in a single call rather than having to reque
Please rephrase to: "Returns a list of assignments assigned to a user for all classes in a single call."

In line 16, please include a blank line between this first sentence and the rest of the text. That is to say, please separate the first sentence and the rest in different paragraphs.

2021-06-10 16:34 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-add-categories.md
> +Add one or more existing [educationCategory](../resources/educationcategory.md) objects to this [educationAssignment](../resources/educationassignment.md).
Is there a reason to resolve this change request?

2021-06-10 16:42 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-add-categories.md
> +  "blockType": "ignored",
Please update the proper blockType for a request. Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=set-up-for-api-doctor-in-an-api-topic

2021-06-10 16:43 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-add-categories.md
> +  "blockType": "ignored",
Please update the proper blockType for a response: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=set-up-for-api-doctor-in-an-api-topic

2021-06-10 16:57 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-delete.md
> +  "name": "delete_educationassignment_1"
I'd appreciate if you can add the `sampleKeys` parameter here an include the IDs.
Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-06-10 17:06 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-get-rubric.md
> +If successful, this method returns a `200 OK` response code and an [educationRubric](../resources/educationrubric.md) object in the response body.
Please explain what happens if there is no educationRubric in the educationAssignment.

2021-06-10 17:51 UTC, opbld31 commented
Docs Build status updates of commit _[24edc9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24edc9c01bdae22cac0a2983cb38a5bdb80b83c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-72bed63a)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-72bed63a)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs. [...]

2021-06-10 17:58 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-get.md
> +  "name": "get_educationassignment"
I'd appreciate if you can add the sampleKeys property here as well.

2021-06-10 18:03 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-list-categories.md
> +  "blockType": "ignored",
Please use the proper blockType: request. 
Please include sampleKeys properties.

2021-06-10 18:04 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-list-categories.md
> +  "blockType": "ignored",
Please use the proper blockType: response.

2021-06-10 18:07 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-list-resources.md
> +  "blockType": "request",
I'd appreciate if you can include the sampleKeys parameter.

2021-06-10 18:10 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-list-submissions.md
> +            "displayName": "Susana Rocha",
Please use approved fictitious names here. Guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103160/Fictitious-names

2021-06-10 18:10 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-list-submissions.md
> +            "displayName": "Susana Rocha",
Please use CELA approved fictitious names. Guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103160/Fictitious-names

2021-06-10 18:18 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-post-resources.md
> +Create an [assignment resource](../resources/educationassignmentresource.md). The resource itself has an @odata.type to indicate which type of resource is being created. Note that file-based resource
Line 16: Please re-organize:
Create an assignment resource. 
//blank line
All educationAssignment objects have an @odata.type to indicate the resource type. 

" > [!IMPORTANT] "
" > Upload file-based resource to the assignments [resourceFolder] (link here) before creating the resource. "

2021-06-10 18:25 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-publish.md
> +description: "This action changes the state of an assignment from its original draft status to the published status. Only a teacher in the class can make this call. When an assignment is in draft sta
Please make the change in line 16 as well.

2021-06-10 18:25 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-publish.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Please remove the beta disclaimer **from all v1 documents**.

2021-06-10 18:31 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-publish.md
> +This action changes the state of an assignment from its original draft status to the published status. Only a teacher in the class can make this call. When an assignment is in draft status, students
Please separate the first sentence in a different paragraph from the rest. 

In the last sentence, please re-phrase to active voice:
Calling this API creates [submission] (link here please) objects and displays the **assignment** in each student's list.

2021-06-10 18:32 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-publish.md
> +  "name": "educationassignment_publish_2"
I'd appreciate if you can add the sampleKeys property here.

2021-06-10 20:46 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-put-rubric.md
> +  "@odata.id": "https://graph.microsoft.com/v1.0/education/me/rubrics/{id}"
Same in this line, please include real looking IDs.

2021-06-10 20:47 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-remove-category.md
> +  "blockType": "ignored",
Please use the proper blockType: request and include the sampleKeys.

2021-06-10 20:49 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-remove-category.md
> +  "blockType": "ignored",
Please use the proper blockType response.

2021-06-10 20:50 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-setupresourcesfolder.md
> +  "name": "educationassignment_setupresourcesfolder"
I'd appreciate if you can include the sampleKeys parameter in this one.

2021-06-10 21:00 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +description: "Update the assignment object. Only teachers in the class can do this. Note that you can't use a PATCH request to change the status of an assignment. Use the publish action to change the
Please re-phrase to: Update an educationAssigment object. 

Please remove any other sentences.

2021-06-10 21:05 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +Update the assignment object. Only teachers in the class can do this. Note that you can't use a PATCH request to change the status of an assignment. Use the [publish](../api/educationassignment-publi
Please make the first line consistent with the changes in line 3 (please see my suggestion above). Regarding the rest of the information, please rephrase and restructure:
Update an [educationAssignment] object. 
//blank line
Only teachers can perform this action. 
//Blank line
Alternatively, request to change the status of an assignment with [publish] (link here) action. Don't use a PATCH operation for this purpose.

2021-06-10 21:09 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +In the request body, supply the values for relevant fields that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated
Please include a blank line between the 1st and second sentence and rephrase to active voice:
In the request body, supply only the values of the fields you want to update. 
//blank line
Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values. For best performance, don't include existing values that haven't changed.

2021-06-10 21:14 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +|addedStudentAction|String| Controls the behavior for students who are added after the assignment is published.|
Could you please re-phrase this description with a more technical explanation? It is not clear what the feature actually does. 
Since this is a property, please use a verb like "Indicates" or "Describes". 

Please avoid using the word "behavior". 

Please use "assignment publication date" instead of "assignment is published". Active voice tricks ;)

2021-06-10 21:15 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +|allowLateSubmissions|Boolean| Whether submissions can be submitted after the due date.|
Please re-phrase the description to:
Whether students can send submission after the due date.

2021-06-10 21:18 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +|allowStudentsToAddResourcesToSubmission|Boolean| Whether a student can add resources to a submission. Indicated whether the only items on the submission came from the assignment resource list. |
The first sentence is very good. Could you please clarify the second sentence?
Can we re-phrase to:
Also, indicates whether all items in the submission correspond to the assignment resource list.

2021-06-10 21:21 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +|assignDateTime|DateTimeOffset| Date the assignment should be published to students. |
Indicates the date to publish the assignment to students.

2021-06-10 21:31 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignment-update.md
> +|notificationChannelUrl|String| Channel to post assignment publish notification. Updating the channel URL is not allowed after the assignment has been published and is only allowed when the **assignT
The first sentence is not easy for non-native readers. 
Could we re-phrase?

The channel to communicate notifications related to the assignment. To change the URL, set the `assignTo` value to [educationAssignmentClassRecipient] (link). The channel URL can't change after the publication of the assignment.

2021-06-10 21:33 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-get.md
> +Read the properties and relationships of an [educationAssignmentDefaults](../resources/educationassignmentdefaults.md) object. These are the class-level assignment defaults respected by new assignmen
Please include a blank line after the first sentence. We do this to benefit scanability.

2021-06-10 21:34 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-get.md
> +GET https://graph.microsoft.com/v1.0/education/classes/{id}/assignmentDefaults
Please use a real looking ID in the example.

2021-06-10 21:34 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-get.md
> +    "notificationChannelUrl": "https://graph.microsoft.com/beta/teams('id')/channels('id')"
Same here, please use real looking IDs.

2021-06-10 22:21 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-update.md
> +In the request body, supply the values for relevant fields of the [educationAssignmentDefaults](../resources/educationassignmentdefaults.md) object that should be updated. Existing properties that ar
I made a similar observation above. Please re-phrase and re-organize:
In the request body, supply only the values of the fields you want to update.
//blank line
Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values. For best performance, don't include existing values that haven't changed.

2021-06-10 22:23 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-update.md
> +|addedStudentAction|educationAddedStudentAction|Class-level default behavior for handling students who are added after the assignment is published. Possible values are: `none`, `assignIfOpen`. The de
Please re-phrase:
Class-level default actions for students added after the assignment publication...

2021-06-10 22:24 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-update.md
> +|notificationChannelUrl|String|Default Teams channel to which notifications will be sent. Default value is `null`.|
Please re-phrase to:
Default Teams channel to send notifications related to the assignment.

2021-06-10 22:25 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-update.md
> +PATCH https://graph.microsoft.com/v1.0/education/classes/{id}/assignmentDefaults
Please use a real looking ID.

2021-06-10 22:25 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-update.md
> +  "notificationChannelUrl": "https://graph.microsoft.com/beta/teams('id')/channels('id')"
Please use real looking IDs here as well.

2021-06-10 22:25 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentdefaults-update.md
> +  "notificationChannelUrl": "https://graph.microsoft.com/beta/teams('id')/channels('id')"
Please use real looking IDs here.

2021-06-10 22:39 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentresource-delete.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Please remember to remove the beta disclaimer from the v1 docs.

2021-06-10 22:41 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentresource-get.md
> +
Please include the example request. It is missing in this one.

2021-06-10 22:42 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentresource-get.md
> +        "displayName": "Susana Rocha",
Please use approved fictitious names here.

2021-06-10 22:42 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentresource-get.md
> +        "displayName": "Susana Rocha",
Please use approved fictitious names here.

2021-06-10 22:44 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentsettings-get.md
> +GET https://graph.microsoft.com/v1.0/education/classes/{id}/assignmentSettings
Please use real looking IDs in the examples.

2021-06-10 22:45 UTC, isvargasmsft commented on api-reference/v1.0/api/educationassignmentsettings-update.md
> +PATCH https://graph.microsoft.com/v1.0/education/classes/{id}/assignmentSettings
Please use a real looking ID in this example.

2021-06-10 22:46 UTC, isvargasmsft commented on api-reference/v1.0/api/educationcategory-delete.md
> +Delete an existing category.
Please include the reference link to the category resource type or the related document.

2021-06-10 22:46 UTC, isvargasmsft commented on api-reference/v1.0/api/educationcategory-get.md
> +  "blockType": "ignored",
Please use the proper blockType: request.

2021-06-10 22:47 UTC, isvargasmsft commented on api-reference/v1.0/api/educationcategory-get.md
> +GET https://graph.microsoft.com/v1.0/education/classes/{id}/assignmentCategories/{id}
Please include real looking IDs in the example.

2021-06-10 22:47 UTC, isvargasmsft commented on api-reference/v1.0/api/educationcategory-get.md
> +##### Request
Please use H3

2021-06-10 22:47 UTC, isvargasmsft commented on api-reference/v1.0/api/educationcategory-get.md
> +##### Response
Please use H3 as well.

2021-06-10 22:47 UTC, isvargasmsft commented on api-reference/v1.0/api/educationcategory-get.md
> +  "blockType": "ignored",
Please use the proper blockType: response.

2021-06-10 22:49 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-list-assignments.md
> +description: "Retrieve a list of assignment objects. A teacher or an application executing with application permissions is allowed to see all assignment objects for the class. Students can only see a
Search engines use this description to display results. Please include the first sentence only.

2021-06-10 22:51 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-list-assignments.md
> +title: "List class specific user assignments"
I think I made a similar comment in the beta topic. Can we update this title to: List class assignments.

2021-06-10 22:52 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-list-assignments.md
> +Retrieve a list of assignment objects. A teacher or an application executing with application permissions is allowed to see all assignment objects for the class. Students can only see assignments tha
Please re-organized as advised in the beta topic. 
Change " is allowed" to can.

2021-06-10 22:54 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-list-categories.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
Please remember to remove the beta disclaimer from the v1 docs.

2021-06-10 22:55 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-list-categories.md
> +GET https://graph.microsoft.com/v1.0/education/classes/{id}/assignmentCategories
Please include real looking IDs here.

2021-06-10 22:56 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-post-assignments.md
> +description: "Creates a new assignment. Only teachers in a class can create an assignment. Assignments start in the Draft state, which means that students will not see the assignment until publish is
Please include the first sentence only and use imperative: Create a new assignment.

2021-06-10 22:57 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-post-assignments.md
> +Creates a new assignment. Only teachers in a class can create an assignment. Assignments start in the Draft state, which means that students will not see the assignment until publish is called.
Please use imperative and re-organize this lines:
Create a new assignment. 
//blank line
Only teachers in a class can create an assignment. Assignments start in the Draft state, which means that students will not see the assignment until publication.

2021-06-10 22:57 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-post-assignments.md
> +##### Request
Please use H3 header in this Request section.

2021-06-10 22:58 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-post-assignments.md
> +  "blockType": "ignored",
Please use the proper blockType: request.

2021-06-10 22:59 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-post-category.md
> +##### Request
Please use H3

2021-06-10 22:59 UTC, isvargasmsft commented on api-reference/v1.0/api/educationclass-post-category.md
> +  "blockType": "ignored",
Please use blockType request.

2021-06-10 23:02 UTC, isvargasmsft commented on api-reference/v1.0/api/educationoutcome-update.md
> +The educationOutcome object will be one of the following derived types: **educationPointsOutcome**, **educationFeedbackOutcome**, or **educationRubricOutcome**. Supply the specific properties relevan
Is this parameter provided by the user? If so, please clarify:
Specify one of the following values for the educationOutcome property: ...

2021-06-10 23:03 UTC, isvargasmsft commented on api-reference/v1.0/api/educationoutcome-update.md
> +All derived outcome types have a regular and a "published" property appropriate to that type of outcome; for example, **points** and **publishedPoints**, **feedback** and **publishedFeedback**. Do no
In the second sentence: please remember we are encourage to use contractions as per Microsoft Writing Style. 
Please use "Don't" instead of "Do not".

2021-06-10 23:03 UTC, isvargasmsft commented on api-reference/v1.0/api/educationoutcome-update.md
> +PATCH https://graph.microsoft.com/v1.0/education/classes/{id}/assignments/{id}/submissions/{id}/outcomes/{id}
Please use real looking examples.

2021-06-10 23:05 UTC, isvargasmsft commented on api-reference/v1.0/api/educationrubric-get.md
> +Note that when getting the rubric of an assignment (`GET /education/classes/{id}/assignments/{id}/rubric`), what is returned is an immutable copy of the original rubric that exists under `/education/
Please include the reference link to get the rubric of an assignment.

2021-06-10 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[e255345](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e25534589e5f90559a36cab2ac7b06fe27658530)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-3e8dbd1d)
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/education-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-8cbfaf04b7cdebb272d2a23aecc85450-3e8dbd1d)
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-3fd825001d81322e262a1ed28da94e39-3e8dbd1d)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-3e8dbd1d)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md [...]

2021-06-11 00:03 UTC, opbld31 commented
Docs Build status updates of commit _[b7c41b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7c41b38a66701ddf9881a975026946c99d7ac0f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-6b3ec1cc)
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/education-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-8cbfaf04b7cdebb272d2a23aecc85450-6b3ec1cc)
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-3fd825001d81322e262a1ed28da94e39-6b3ec1cc)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-6b3ec1cc)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md [...]

2021-06-11 00:25 UTC, opbld33 commented
Docs Build status updates of commit _[2143f50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2143f5077450ff5e8363d1b9969a1d82354269c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-1daa59c5)
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/education-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-8cbfaf04b7cdebb272d2a23aecc85450-1daa59c5)
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-3fd825001d81322e262a1ed28da94e39-1daa59c5)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1daa59c5)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md [...]

2021-06-11 00:45 UTC, opbld30 commented
Docs Build status updates of commit _[a8a18e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8a18e75d3aec3a11072f6001a6ce3cb21aa6fb5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-8012bde5)
[api-reference/v1.0/resources/education-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/education-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/education-overview?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-8cbfaf04b7cdebb272d2a23aecc85450-8012bde5)
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-3fd825001d81322e262a1ed28da94e39-8012bde5)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-8012bde5)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md [...]

2021-06-11 01:21 UTC, opbld34 commented
Docs Build status updates of commit _[27e1545](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27e1545d95ef24d0a3f75b9fe3f95795356fa684)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-ab2b25a7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-ab2b25a7)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resource.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2021-06-11 01:44 UTC, opbld33 commented
Docs Build status updates of commit _[fa59082](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa59082ab7bce01ade186d191877238746e47fa5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-b8214932)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-b8214932)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resource.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2021-06-11 02:00 UTC, opbld34 commented
Docs Build status updates of commit _[8bc048c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bc048c003d1333815fea3b6da932f2f29bd5d58)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-b7410296)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-b7410296)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resource.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2021-06-11 02:21 UTC, opbld32 commented
Docs Build status updates of commit _[b850cd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b850cd5e24e5d4a2fa707f2848651da0585b98f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-a7f7b6ca)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-a7f7b6ca)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-post-resource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-post-resource.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2021-06-11 02:52 UTC, opbld31 commented
Docs Build status updates of commit _[cb4286c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb4286c0d50d48da070767d608883ecc6fd81b27)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-170600b8)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-170600b8)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-submissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-submissions.md) | :white_check_mark:Succeeded | [...]

2021-06-11 03:05 UTC, opbld34 commented
Docs Build status updates of commit _[70516d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70516d98526c1061b06bf739b225ae7f3aa173d7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-969d2ad4)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-969d2ad4)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ [...]

2021-06-11 03:22 UTC, opbld33 commented
Docs Build status updates of commit _[fe8a61f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe8a61f6a6c37d544ed3e347cea7bc99a2f385e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-0299b6ac)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-0299b6ac)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ [...]

2021-06-11 03:55 UTC, opbld34 commented
Docs Build status updates of commit _[61b22d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61b22d504e21c7e1215c568bce30f11d557ac83f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-52030fb0)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-52030fb0)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ [...]

2021-06-11 04:25 UTC, opbld33 commented
Docs Build status updates of commit _[8e9be7a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e9be7a977e20514829c9c873b059ff30bb49b73)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-fa1801b9)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-fa1801b9)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2021-06-11 04:48 UTC, opbld34 commented
Docs Build status updates of commit _[ae07bf5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae07bf54f8ff43bac8b78bbb1d00a272872b0da1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-b5d04dc5)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-b5d04dc5)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2021-06-11 04:54 UTC, opbld32 commented
Docs Build status updates of commit _[2327207](https://github.com/microsoftgraph/microsoft-graph-docs/commits/232720708c3f71a696ee40da8c71621afd1ffb7d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-6d86e35e)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-6d86e35e)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2021-06-11 05:23 UTC, opbld34 commented
Docs Build status updates of commit _[6d2ed4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d2ed4af43c6332dcad0aabfbffba11f370a901a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-d16bdc66)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d16bdc66)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2021-06-11 05:35 UTC, opbld30 commented
Docs Build status updates of commit _[cd380a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd380a793257f99f5711982990512be724e9c9b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-80cb8dbd)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-80cb8dbd)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2021-06-11 05:41 UTC, opbld31 commented
Docs Build status updates of commit _[7699c10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7699c1082c821a6f512bf554280b87390fbfc550)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-b37dea84)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-b37dea84)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-get-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-get-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.co [...]

2021-06-11 08:20 UTC, opbld34 commented
Docs Build status updates of commit _[7db7469](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7db74693dfb224f769ae3eefa13c8da4813fad74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-0ff47a21)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-0ff47a21)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-06-11 12:30 UTC, opbld33 commented
Docs Build status updates of commit _[d839ac9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d839ac9666acd8b69adf78d0ed03de3975a7b476)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-02e62149)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-02e62149)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2021-06-11 12:31 UTC, isvargasmsft commented on api-reference/beta/api/educationclass-list-assignments.md
> +# List class specific user assignments
The title here should match the title in line 2. Please use Line 2 as title: List class assignments.

2021-06-11 12:50 UTC, isvargasmsft commented on api-reference/v1.0/api/educationsubmission-get.md
> +Retrieve a particular submission. A submission object represents a student's work for an assignment. Resources associated with the submission represent this work. Only the student the submission is a
Please let's fix this section:
Retrieve a particular submission. 
//blank line
A submission object represents a student's work for an assignment. Resources associated with the submission contain this work.
//blank line
Only the assigned student can see and modify the submission. A teacher or application with application permissions has full access to all submissions.


IMPORTANT: The main issue is in the phrase: "Only the student the submission is assigned to". This phrase is very hard to understand if you are not an advanced English reader. Let's fix this phrasing at least, please.

2021-06-11 13:35 UTC, opbld30 commented
Docs Build status updates of commit _[d91961c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d91961cbadf02a241692a7350296f049d16b2ed3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-16e71942)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 14:49 UTC, opbld31 commented
Docs Build status updates of commit _[3bea6c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bea6c840c2bffbb6690f44a96ae680203d1e91c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-6e2d71ce)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 15:04 UTC, isvargasmsft approved these changes
Thank you for the fast response to my comments. 

Let's take a deeper review in the future to address minor phrasing and structure issues.

2021-06-11 17:16 UTC, Lauragra commented on api-reference/beta/api/educationassignment-delete-rubric.md
> -# [HTTP](#tab/http)
Global: Please restore this line, assuming the intent here was not to remove the snippets from the beta files. This tab is added as part of the automated snippet generation process.

2021-06-11 17:19 UTC, opbld32 commented
Docs Build status updates of commit _[15494f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15494f3540eff5400abcc00a3848a63672a00a44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1cbc56b9)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 17:35 UTC, opbld31 commented
Docs Build status updates of commit _[7715bb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7715bb39234dace5df258913bfae6a1e2fe2302e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-21edb6ec)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 17:37 UTC, Lauragra commented on api-reference/beta/api/educationclass-list-assignments.md
> +# List class assignments
Technically to follow our file naming guidance, the title here would be "List assignments"; is there a reason you have added the "class" descriptor?

2021-06-11 17:37 UTC, opbld34 commented
Docs Build status updates of commit _[765a246](https://github.com/microsoftgraph/microsoft-graph-docs/commits/765a2467dc6fdd74984db879292162af305c2e2c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-fc4d844d)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 17:43 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-add-categories.md
> +# Add educationCategories
Please see the guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22. Because the metadata includes ContainsTarget="true", the title should be "Create educationCategories". The file name should be -post instead of add. As applicable, please also update in the beta topic.

2021-06-11 18:11 UTC, opbld31 commented
Docs Build status updates of commit _[359bd85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/359bd854faddc5f3924e86c995fae9c4d8e5dcde)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-96345d76)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 18:13 UTC, Lauragra commented on api-reference/v1.0/api/educationassignment-delete-rubric.md
> +Remove an [educationRubric](../resources/educationrubric.md) from an [educationAssignment](../resources/educationassignment.md).
The rubric navigation property also has ContainsTarget="true" applied, in which case technically this should be a Delete, although that is not compatible with the description that you provide. Not sure if we should update the content here or if you should investigate whether there is an error in the CSDL?

2021-06-11 18:23 UTC, opbld32 commented
Docs Build status updates of commit _[4a82df5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a82df558333c7588dd910cba2a044b030ae7d4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-96391947)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 18:25 UTC, opbld32 commented
Docs Build status updates of commit _[24b8fd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24b8fd7bac32c03f6be0a69e648ddd0c6ae1dea4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationassignment-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-list-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-b213fd10763a57fd238c274355270fe0-cf5d9e48)
[api-reference/v1.0/api/educationsubmission-list-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmission-list-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-resources?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-d7f10f00a6d3e3a0274cfd0c0958266a-cf5d9e48)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-cf5d9e48)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white [...]

2021-06-11 18:27 UTC, opbld33 commented
Docs Build status updates of commit _[22ae167](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22ae167bec62d612ea8296024c29b2e0bb52c1b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-44dd412b)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 18:29 UTC, opbld30 commented
Docs Build status updates of commit _[2ae0f18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ae0f1812f939142382f6e1bd4808de48812fc6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-74b7ef8c)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 18:33 UTC, opbld34 commented
Docs Build status updates of commit _[3208a48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3208a483a8f40aa6440967d7c83b17630be9d625)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1ae4f0ce)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 18:35 UTC, opbld30 commented
Docs Build status updates of commit _[9147908](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9147908b4536ffe73e5663301428d583d5810bd5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-46423e3d)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 18:36 UTC, opbld32 commented
Docs Build status updates of commit _[575d664](https://github.com/microsoftgraph/microsoft-graph-docs/commits/575d6644bc66b55d35242fc1933ae10e3dcf2e96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-ad7f6e4b)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 19:06 UTC, opbld31 commented
Docs Build status updates of commit _[7041162](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7041162c58169b358a36567eaaa5f267042a2af5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-43a3a01b)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 19:11 UTC, opbld34 commented
Docs Build status updates of commit _[d9bed52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9bed52346ddde5ad7108080fd65001d4960af79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9e0be1d3)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 19:17 UTC, opbld32 commented
Docs Build status updates of commit _[46e2347](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46e234788e332e2d14fd9b6505cc64f55dfb421e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-c6b98340)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete?view=graph-rest-1.0&bra [...]

2021-06-11 19:19 UTC, opbld34 commented
Docs Build status updates of commit _[bfb54c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfb54c6d652f43579ef3a79932e6c33e13934447)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-45ed07e541e79cf2e9e3eb1ce3a0eda9-19784ba4)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-19784ba4)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://r [...]

2021-06-11 19:25 UTC, Lauragra commented on api-reference/v1.0/api/educationuser-get-user.md
> +# Get user from educationUser
I'm not sure that this title change is clear. The original title "Get educationUser" is accurate per our topic titling guidelines. Can we restore the original title?

2021-06-11 19:27 UTC, opbld32 commented
Docs Build status updates of commit _[5cc4092](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cc4092a8938612c776fd79b0f385c4e8826d2cf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-45ed07e541e79cf2e9e3eb1ce3a0eda9-18ff4370)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-18ff4370)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://r [...]

2021-06-11 19:33 UTC, opbld34 commented
Docs Build status updates of commit _[53e8db8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53e8db88e08cd17909b0b77da0eda7b376472535)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationsubmittedsubmissionresource-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmittedsubmissionresource-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-45ed07e541e79cf2e9e3eb1ce3a0eda9-81c717d5)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-81c717d5)
[api-reference/beta/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/v1.0/api/educationassignment-add-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-add-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-add-categories?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) |
[api-reference/v1.0/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://r [...]

2021-06-11 22:03 UTC, opbld30 commented
Docs Build status updates of commit _[53a0c13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53a0c133c0d3185e1be178baff03297b6406b965)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-4842f66b)
[api-reference/v1.0/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-3fd825001d81322e262a1ed28da94e39-4842f66b)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-4842f66b)
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) | [Details](#user-content-c2e14fd514a0819251a4832e17db9865-4842f66b)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeed [...]

2021-06-11 22:07 UTC, opbld30 commented
Docs Build status updates of commit _[7ebf2e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ebf2e07aa0b5c2bbf71e8a84fa1b9d0241c93bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-1ea363d3)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1ea363d3)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-11 22:32 UTC, opbld33 commented
Docs Build status updates of commit _[eeb52dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eeb52ddeb2c5180d4ec5858ff6f645df58651f70)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-454cf0a7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-454cf0a7)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-11 22:32 UTC, Lauragra commented on api-reference/v1.0/api/educationuser-update.md
> -# [C#](#tab/csharp)
Why are we removing the SDK snippets from this topic?

2021-06-11 22:40 UTC, Lauragra commented on api-reference/v1.0/resources/educationassignment.md
> +|[List resources](../api/educationassignment-list-resources.md) |[educationAssignmentResource](educationassignmentresource.md) collection| Get an **educationAssignmentResource** object collection.|
In Methods tables and the TOC, we list the CRUD operations first and then other methods. So the order for the first methods should be List, Create, Get, Update, Delete, and then other actions and such can follow.

2021-06-11 22:43 UTC, Lauragra commented on api-reference/v1.0/resources/educationassignmentdefaults.md
> +  "addedStudentAction": "none",
The JSON representation should only show the types, not actual values. So for this property, it should be "string", not a value, and so on.

2021-06-11 22:46 UTC, opbld31 commented
Docs Build status updates of commit _[3fc3446](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fc3446c5057404b6a44c92d0182e756bca37205)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-5e290909)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-5e290909)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-11 22:47 UTC, Lauragra commented on api-reference/v1.0/resources/educationassignmentrecipient.md
> +description: "Used within the **assignments.assignTo** property. This superclass is abstract and you cannot"
Global: Please check all the descriptions to ensure that they are a complete sentence and don't include part of an incomplete sentence.

2021-06-11 22:48 UTC, opbld34 commented
Docs Build status updates of commit _[a8f43b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8f43b0b1c56fc470a040251b49670d890c7e1b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-97b2df32)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-97b2df32)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-11 22:52 UTC, Lauragra commented on api-reference/v1.0/resources/educationfeedback.md
> +Feedback from a teacher to a student. This property represents both the text part of the feedback along with the who.
The phrase "along with the who" is not clear; by this, do you mean "along with who provided the feedback"?

2021-06-11 23:05 UTC, opbld34 commented
Docs Build status updates of commit _[7a86b6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a86b6e9ca54a05749f258e8b2f5a9c94575b959)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-ded010db)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-ded010db)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-11 23:06 UTC, opbld34 commented
Docs Build status updates of commit _[7a86b6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a86b6e9ca54a05749f258e8b2f5a9c94575b959)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-d8edef77)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d8edef77)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-11 23:16 UTC, Lauragra commented on concepts/whats-new-overview.md
> +The APIs for assignments service are now generally available.
You might want to have a link her to the v1.0 documentation.

2021-06-11 23:19 UTC, Lauragra commented on changelog/Microsoft.EducationAssignment.json
> +          "ApiChange": "ComplexType",
ComplexType isn't one of the values listed for this attribute. Should be Resource. Was this ChangeList entry generated by the tool? There might be a gap in our documentation if this is an allowed value.

2021-06-11 23:20 UTC, Lauragra commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Added the [educationAssignment](https://docs.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-1.0) resource",
Please make sure that all the descriptions end with a period.

2021-06-11 23:21 UTC, Lauragra commented on changelog/Microsoft.EducationAssignment.json
> +          "ApiChange": "EntityType",
EntityType also is not one of the approved values. This is either a change due to the new changelog generation tool, or we need to update it to Resource.

2021-06-11 23:35 UTC, Lauragra commented on changelog/Microsoft.EducationAssignment.json
> +          "Description": "Added the [publish](https://docs.microsoft.com/en-us/graph/api/publish?view=graph-rest-1.0) method to the [publish](https://docs.microsoft.com/en-us/graph/api/publish?view=g
The descriptions for the method topics don't look accurate. I assume that the second link should be to a resource topic, not a repeat of the method.

2021-06-11 23:36 UTC, Lauragra commented on changelog/Microsoft.EducationAssignment.json
> +    {
Remove this changelist item, the GA of the APIs should be reflected in the previous ChangeList, i.e. it should list all the APIs that are generally available in the v1.0 endpoint.

2021-06-11 23:40 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +        - name: Create assignment
Where you're listing CRUD operations in the TOC, you can make the TOC entries more concise by just using the verb without repeating the resource name - List, Create, Get, Update, Delete.

2021-06-12 00:29 UTC, opbld30 commented
Docs Build status updates of commit _[bddafa0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bddafa0a0f53fa02175bc33109fc372274f1a0db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-1dfefc97)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1dfefc97)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-12 00:38 UTC, opbld31 commented
Docs Build status updates of commit _[fca2e5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fca2e5fee6c03634ade32fc705d6361379bec6fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-513280a7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-513280a7)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-12 00:39 UTC, opbld31 commented
Docs Build status updates of commit _[fca2e5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fca2e5fee6c03634ade32fc705d6361379bec6fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-d996f9b9)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-d996f9b9)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-12 00:41 UTC, opbld30 commented
Docs Build status updates of commit _[34f6c9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34f6c9d98f76a3e993e74cea9bd2f0521cfbb585)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-261c7831)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-261c7831)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-12 00:48 UTC, opbld33 commented
Docs Build status updates of commit _[78ec66c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78ec66c6d45608210e7c3d4808d81ee06a16f75d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-1c0eef62)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1c0eef62)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-list-submittedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-list-submittedresources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationuser-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationuser-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/resources/educationcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/resources/educationcategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationcategory?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api- [...]

2021-06-12 01:10 UTC, opbld31 commented
Docs Build status updates of commit _[7eeb92f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7eeb92f0d7ab20d797629f57bcc3ae13d42cb394)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-79a46ce0)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-79a46ce0)
[api-reference/v1.0/resources/educationlinkresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationlinkresource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationlinkresource?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-6b83187d7de81f71c4e0bebe79ed59e1-79a46ce0)
[api-reference/v1.0/resources/educationpowerpointresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationpowerpointresource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationpowerpointresource?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-3459a880f6c9e7fa51ef2075c791d7f0-79a46ce0)
[api-reference/v1.0/resources/educationwordresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationwordresource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationwordresource?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-11b89e1ddcce99fe8c5b1f1e0a8331f3-79a46ce0)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/ [...]

2021-06-12 01:17 UTC, opbld34 commented
Docs Build status updates of commit _[956e5c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/956e5c6a393863176078228b7c2d5c64230abe3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationuser-get-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/api/educationuser-get-user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationuser-get-user?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-906a937bf6a3c70d2c809325665ddd12-67aff4e3)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentdefaults-get?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-67aff4e3)
[api-reference/v1.0/resources/educationlinkresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationlinkresource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationlinkresource?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-6b83187d7de81f71c4e0bebe79ed59e1-67aff4e3)
[api-reference/v1.0/resources/educationpowerpointresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationpowerpointresource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationpowerpointresource?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-3459a880f6c9e7fa51ef2075c791d7f0-67aff4e3)
[api-reference/v1.0/resources/educationwordresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/v1.0/resources/educationwordresource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationwordresource?view=graph-rest-1.0&branch=pr-en-us-12993) (>= graph-rest-1.0) | [Details](#user-content-11b89e1ddcce99fe8c5b1f1e0a8331f3-67aff4e3)
[api-reference/beta/api/educationassignment-delete-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-delete-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-delete-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-post-resources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-post-resources?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-publish?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-put-rubric.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignment-put-rubric.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationassignmentresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationassignmentresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignmentresource-delete?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationcategory-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-list-categories.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationclass-post-category.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/educationsubmission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationsubmission-get?view=graph-rest-beta&branch=pr-en-us-12993) (graph-rest-beta) |
[api-reference/beta/api/educationsubmission-list-submittedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharaaU7-assignments-v1-0/api-reference/beta/api/ [...]

2021-06-12 01:28 UTC, merged