transitive count API
microsoftgraph/microsoft-graph-docs pull request #13007
Opened 2021-06-04 20:17 UTC by davidmu1

2021-06-04 20:18 UTC, opbld31 commented
Docs Build status updates of commit _[71569ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71569ecd70858e732e7890452c43dadcca9e681f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) | [Details](#user-content-d26e07f3d91980aa9310c4f4c98890a4-b22690de)
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) | [Details](#user-content-5f7e6b4586c4e3d73d842ac94e979420-b22690de)
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="d26e07f3d91980aa9310c4f4c98890a4-b22690de"></a>
### [api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get transitiveReports - Microsoft Graph beta' is duplicated in: 'beta/api/orgcontact-get-transitivereports.md(2,8), beta/api/user-get-transitivereports.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get transitiveReports' is duplicated with other articles: 'beta/api/orgcontact-get-transitivereports.md(10,1), beta/api/user-get-transitivereports.md(10,1)'. First level headings must be unique within a docset.`````

<a id="5f7e6b4586c4e3d73d842ac94e979420-b22690de"></a>
### [api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get transitiveReports - Microsoft Graph beta' is duplicated in: 'beta/api/orgcontact-get-transitivereports.md(2,8), beta/api/user-get-transitivereports.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get transitiveReports' is duplicated with other articles: 'beta/api/orgcontact-get-transitivereports.md(10,1), beta/api/user-get-transitivereports.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106042017233148-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9RbE%2B1fpFIzcAAeF%2F6YP6Wq95pR5N60PcdgiTu4IlgQ%3D&st=2021-06-04T20%3A13%3A47Z&se=2021-07-05T20%3A18%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 20:37 UTC, opbld30 commented
Docs Build status updates of commit _[ddde45d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ddde45d3d2b154b7c139b52af0d7fb00ad165bfb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106042035548578-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ptYFPrRzLIOaO1plPYASr6JE0RR%2FRpEXQMmLUV6wDuA%3D&st=2021-06-04T20%3A32%3A22Z&se=2021-07-05T20%3A37%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 21:00 UTC, Licantrop0 requested changes

2021-06-04 21:00 UTC, Licantrop0 commented on api-reference/beta/api/user-get-transitivereports.md
> +This method requires the `$count` query parameter. For more information, see [OData Query Parameters](/graph/query-parameters).
as the comment above, it requires the $count segment, not the query parameter `$count=true`, as listing the reports is not supported, only counting them.
That's why in the sample above we need to add /$count otherwise it will not work.

2021-06-07 05:24 UTC, opbld31 commented
Docs Build status updates of commit _[869386b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/869386b2865de816bac3fbd3b3d64df7017f7f8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106070523162766-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uS9peOV0vJ13IjZiKYrsuZTW2JW%2B%2BSIXF0KBEVqjB3w%3D&st=2021-06-07T05%3A19%3A37Z&se=2021-07-08T05%3A24%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 05:42 UTC, millicentachieng commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +  "@odata.type": "microsoft.graph.transitivereports",
Remove this line since response has no body to validate against the odata type

2021-06-07 05:42 UTC, millicentachieng commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +5
Is the number 5 expected here?

2021-06-07 17:49 UTC, opbld31 commented
Docs Build status updates of commit _[e0d0571](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0d057156a91f7ba9b643dad0812047dab870d1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071748267359-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=InhvL8dH4%2BDjD6ogqjseaD2srVNpOaXxGzwviaiMOwc%3D&st=2021-06-07T17%3A44%3A58Z&se=2021-07-08T17%3A49%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 17:51 UTC, davidmu1 commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +  "@odata.type": "microsoft.graph.transitivereports",
Removed.

2021-06-07 17:51 UTC, davidmu1 commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +5
Yes.

2021-06-08 05:25 UTC, Licantrop0 requested changes

2021-06-08 05:25 UTC, Licantrop0 commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +This method does not support the use of query parameters, but does require the `$count` query segment.
it does support $filter=accountEnabled eq 'value'
Only accountEnabled property is supported on filter clause and the two supported values are 'true' or 'false'
See https://microsoftgraph.visualstudio.com/_git/onboarding/pullrequest/4612?_a=files&path=%2Freviews%2F4379-add-gettransitivereportscount-api-for-a-given-user%2Fapi.md

2021-06-08 05:25 UTC, Licantrop0 commented on api-reference/beta/api/user-get-transitivereports.md
> +This method does not support the use of query parameters, but does require the `$count` query segment.
see my comment above

2021-06-08 13:32 UTC, millicentachieng commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +5
What's the number representing? It looks misplaced in the docs.

![image](https://user-images.githubusercontent.com/25274795/121194118-1c83df80-c877-11eb-95a6-aec8cdcf7574.png)

2021-06-08 18:06 UTC, davidmu1 commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +5
It's representing the response. It doesn't work to put it in the code block.

2021-06-09 15:46 UTC, opbld34 commented
Docs Build status updates of commit _[5aaa589](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5aaa589b367ff33bb32f7530bdd50d1d89c9afb0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106091544420741-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BW72XJVy5kAh7%2BhiaqXcbXCIAxJDWb2bln9NndGuhOM%3D&st=2021-06-09T15%3A41%3A07Z&se=2021-07-10T15%3A46%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 03:59 UTC, Licantrop0 approved these changes

2021-06-10 03:59 UTC, opbld32 commented
Docs Build status updates of commit _[fe9ae8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe9ae8eac9ed545410f99446a807c31d89af6748)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106100358252813-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bLRs8e7mHNca2ht9lTYUL8eMmRLDjvyNtYHdyQ2MQ6A%3D&st=2021-06-10T03%3A54%3A56Z&se=2021-07-11T03%3A59%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 02:22 UTC, Lauragra commented on api-reference/beta/api/orgcontact-get-transitivereports.md
> +### Get the count of transitive reports for an organizational contact
There's only one example so we don't need this H3, just make the Request and Response headings H3s.

2021-06-15 02:23 UTC, Lauragra commented on api-reference/beta/api/user-get-transitivereports.md
> +title: "user: Get transitiveReports"
The title and H1 should be "Get transitiveReports for a user".

2021-06-15 02:29 UTC, Lauragra commented on api-reference/beta/api/user-get-transitivereports.md
> +### Get the count of transitive reports for a user
Remove and elevate Request and Response to H3s.

2021-06-23 22:38 UTC, opbld32 commented
Docs Build status updates of commit _[4132a2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4132a2fb1a4bdfca037b29c4bf2c32558d7f122a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106232237249292-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=b%2Fj6BPeZSM9ngR%2BlSxGwepCPMluWkvW%2F%2Bf%2F2LHl3vwM%3D&st=2021-06-23T22%3A33%3A45Z&se=2021-07-24T22%3A38%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 22:46 UTC, opbld33 commented
Docs Build status updates of commit _[641c8e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/641c8e15463eb33efff91cc37c2c50df2e0f0b8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106232245146670-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6VX%2Fwf%2BRrdtrKjBIbTfQLXWffTTQd%2FMHLAciM%2BJPgt0%3D&st=2021-06-23T22%3A41%3A52Z&se=2021-07-24T22%3A46%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 22:51 UTC, opbld32 commented
Docs Build status updates of commit _[a71af3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a71af3f6400919b7797180d02a42171b8c425189)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106232250105223-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0p714t8iMMOXKCLJSUVtjo%2FrMpAPYIDHLFgKilOoqxw%3D&st=2021-06-23T22%3A46%3A50Z&se=2021-07-24T22%3A51%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 17:52 UTC, opbld34 commented
Docs Build status updates of commit _[611c491](https://github.com/microsoftgraph/microsoft-graph-docs/commits/611c4917f2e3eb02c1a936f273bb5f4688e59429)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241750307908-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G0qP9F8CIfhWeLsQtrAKc7vm9ygW1ETIg98gDSoxzlM%3D&st=2021-06-24T17%3A47%3A11Z&se=2021-07-25T17%3A52%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-25 17:02 UTC, opbld31 commented
Docs Build status updates of commit _[213755e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/213755e23e653e8a1153c51d1884b508129960c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106251700576415-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EEE8GPpmTKYbfMaQRWiuku8TNeCeCFZUX%2FSTi3X3n8Y%3D&st=2021-06-25T16%3A57%3A24Z&se=2021-07-26T17%3A02%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-25 23:02 UTC, Lauragra approved these changes

2021-06-25 23:02 UTC, opbld31 commented
Docs Build status updates of commit _[a73cd18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a73cd188f5392ddb347e9d68eabd4d21ca6a1c9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106252301272949-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BVJ%2BT71Yn%2FiKww7hp3rXUbzmi23QWl4bC4sUjxirhwM%3D&st=2021-06-25T22%3A57%3A54Z&se=2021-07-26T23%3A02%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-25 23:04 UTC, opbld31 commented
Docs Build status updates of commit _[d3b6f6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3b6f6f8cdf926362c8c412e74035adb770bb77b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/orgcontact-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/orgcontact-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/api/user-get-transitivereports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/api/user-get-transitivereports.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-transitivereports?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-13007) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/transitivecount1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106252302171479-13007%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BjtnfQ2P6FXegQHJMTNsZwrPF22IlG%2BwqH8jVl%2F31H8%3D&st=2021-06-25T22%3A59%3A21Z&se=2021-07-26T23%3A04%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-26 00:44 UTC, merged