Shifting to custom derivatives of identity and identitySet for Microsoft Teams messaging
microsoftgraph/microsoft-graph-docs pull request #13037
Opened 2021-06-08 20:43 UTC by RamjotSingh

2021-06-08 20:44 UTC, opbld31 commented
Docs Build status updates of commit _[045de7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/045de7ce81c3c443df1c2c8a98e55b7df2fdbee5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) | [Details](#user-content-1c8c93c1f51f8a7848e523040b0f0c84-12fa1278)
[api-reference/v1.0/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworktagidentity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) | [Details](#user-content-ad79bffcbff30dbf3848954631e388f8-12fa1278)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) |  [...]

2021-06-08 20:52 UTC, opbld34 commented
Docs Build status updates of commit _[d9327be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9327be26012f33e2347324751558173140bf325)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-09 10:57 UTC, opbld33 commented
Docs Build status updates of commit _[df47e31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df47e31829f671012f7e69e61108b27a9cabc863)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-10 02:53 UTC, opbld30 commented
Docs Build status updates of commit _[1e744ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e744ed881127c3b26e4aa1c668bf961b027ac7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-11 20:00 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkapplicationidentity.md
> +|displayName|String|Inherited from [identity](../resources/identity.md). Optional display name of the application.|
Please, update the sentence for conformity. Suggested revision:

"Display name of the application. Optional."

2021-06-11 20:05 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkconversationidentity.md
> +|conversationIdentityType|teamworkConversationIdentityType|Type of conversation. Possible values are: `team`, `channel`, `chat`.|
According to the teamworkConversationIdentityType enum type, possible values should also contain "unknownFutureValue"

2021-06-11 20:06 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +description: "Represents a conversation in Microsoft Teams"
Please, add a period at the end of the sentence.

2021-06-11 20:06 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +Represents a conversation (chat, team, channel) in Microsoft Teams.
Please, add "or " before "channel"

2021-06-11 20:07 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +|conversationIdentityType|teamworkConversationIdentityType|Type of conversation. Possible values are: `team`, `channel`, `chat`.|
According to the teamworkConversationIdentityType enum type, possible values should also contain "unknownFutureValue"

2021-06-11 20:07 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +|conversationIdentityType|teamworkConversationIdentityType|Type of conversation. Possible values are: `team`, `channel`, `chat`.|
Please, add "and " before the last possible value.

2021-06-11 20:09 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +|displayName|String|Inherited from [identity](../resources/identity.md). Optional display name of the conversation.|
Please, update the sentence for conformity. Suggested revision:

"Display name of the conversation. Optional."

2021-06-11 20:09 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworktagidentity.md
> +description: "Represents a tag in Microsoft Teams"
Please, add a period at the end of the sentence.

2021-06-11 20:10 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworktagidentity.md
> +Represents a tag in Microsoft Teams. Tags allow users to quickly connect to subset of users in a team. Please refer to [docs](/microsoftteams/manage-tags) for more info.
For consistency and readability, we introduce the subject before we provide the link. In this case, I recommend: "For details about tag management in Microsoft Teams, see [Manage tags in Microsoft Teams](/microsoftteams/manage-tags)."

2021-06-11 20:11 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkuseridentity.md
> +description: "Represents a user in Microsoft Teams"
Please, add a period at the end of the sentence.

2021-06-11 20:12 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkuseridentity.md
> +Represents a user in Microsoft Teams. The object contains user's Id, optional name and the type of user it is.
Please, rephrase the sentence for readability. Suggested revision:

"...The user ID is required in the user object. Optional properties are the display name and the user type."

2021-06-11 20:12 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkuseridentity.md
> +|displayName|String|Inherited from [identity](../resources/identity.md). Optional display name of the user.|
Please, update the sentence for conformity. Suggested revision:

"Display name of the user. Optional."

2021-06-11 20:14 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
According to the teamworkUserIdentityType enum type, possible values should also contain "unknownFutureValue"

2021-06-11 20:14 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
According to the teamworkUserIdentityType enum type, possible values should also contain "unknownFutureValue"

2021-06-11 20:14 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
Please, add "and " before the last possible value

2021-06-11 20:15 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-beta) to represent applications in Micro
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:16 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkUserIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkUserIdentity?view=graph-rest-beta) to represent users in Microsoft Teams. This new
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:17 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkConversationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkConversationIdentity?view=graph-rest-beta) to represent conversations (team
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:17 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkTagIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkTagIdentity?view=graph-rest-beta) to present tags in Microsoft Teams. This new type
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageFromIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageFromIdentitySet?view=graph-rest-beta) to represent sender of a [chatMessag
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageMentionedIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageMentionedIdentitySet?view=graph-rest-beta) to represent user or appli
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageReactionIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageReactionIdentitySet?view=graph-rest-beta) to represent user which reac
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-1.0) to represent applications in Micros
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkUserIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkUserIdentity?view=graph-rest-1.0) to represent users in Microsoft Teams. This new t
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkConversationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkConversationIdentity?view=graph-rest-1.0) to represent conversations (team,
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkTagIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkTagIdentity?view=graph-rest-1.0) to present tags in Microsoft Teams. This new type d
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageFromIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageFromIdentitySet?view=graph-rest-1.0) to represent sender of a [chatMessage
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageMentionedIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageMentionedIdentitySet?view=graph-rest-1.0) to represent user or applic
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:19 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageReactionIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageReactionIdentitySet?view=graph-rest-1.0) to represent user which react
Please, remove `en-us` from all links you've added. Let docs.microsoft.com figure out the correct locale.

2021-06-11 20:27 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
Please, replace "Resource" with "Enum type"

2021-06-11 20:28 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
Please, replace "Resource" with "Enum type"

2021-06-11 20:28 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
Please, replace "Resource" with "Enum type"

2021-06-11 20:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
Please, replace "Resource" with "Enum type"

2021-06-11 20:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
Please, replace "Resource" with "Enum type"

2021-06-11 20:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "Resource",
Please, replace "Resource" with "Enum type"

2021-06-14 22:56 UTC, RamjotSingh commented on api-reference/beta/resources/chatmessagefromidentityset.md
> +description: "Represents the sender of a chatMessage"
For all the docs since chatMessage (which is a resource and not message in a chat). I have rewritten it to mention message in a chat or a channel.

2021-06-15 01:16 UTC, RamjotSingh commented on api-reference/beta/resources/teamworkuseridentity.md
> +Represents a user in Microsoft Teams. The object contains user's Id, optional name and the type of user it is.
Got rid of the sentence, the table below talks about optional part of the properties already.

2021-06-15 01:21 UTC, opbld30 commented
Docs Build status updates of commit _[03e833c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03e833c5f21bc48af3d3b6581e47c94c5a8759a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-15 01:22 UTC, RamjotSingh commented on api-reference/beta/resources/teamworkapplicationidentity.md
> +|applicationIdentityType|teamworkApplicationIdentityType| Type of application being referenced. Possible values are: `aadApplication`, `bot`, `tenantBot`, `office365Connector`, `outgoingWebhook`.|
unknwnFutureValue is not sent over the wire it is meant for marking the end of enumeration (so that if we extend the enum it is used as a fallback). But I can add it.

2021-06-15 01:23 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-beta) to represent applications in Micro
I am following the existing pattern in this json. In my case the doc generation broke, but I understand that the doc generation does the same.

2021-06-15 01:24 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkUserIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkUserIdentity?view=graph-rest-beta) to represent users in Microsoft Teams. This new
Same as other place.

2021-06-15 01:24 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkConversationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkConversationIdentity?view=graph-rest-beta) to represent conversations (team
Same as other place.

2021-06-15 01:24 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkTagIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkTagIdentity?view=graph-rest-beta) to present tags in Microsoft Teams. This new type
Same as other place.

2021-06-15 01:24 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageFromIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageFromIdentitySet?view=graph-rest-beta) to represent sender of a [chatMessag
Same as other place.

2021-06-15 01:24 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageMentionedIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageMentionedIdentitySet?view=graph-rest-beta) to represent user or appli
Same as other place.

2021-06-15 01:24 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageReactionIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageReactionIdentitySet?view=graph-rest-beta) to represent user which reac
Same as other place.

2021-06-15 01:25 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-1.0) to represent applications in Micros
Same as other place.

2021-06-15 01:25 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkUserIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkUserIdentity?view=graph-rest-1.0) to represent users in Microsoft Teams. This new t
Same as other place.

2021-06-15 01:25 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkConversationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkConversationIdentity?view=graph-rest-1.0) to represent conversations (team,
Same as other place.

2021-06-15 01:25 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageFromIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageFromIdentitySet?view=graph-rest-1.0) to represent sender of a [chatMessage
Same as other place.

2021-06-15 01:25 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageMentionedIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageMentionedIdentitySet?view=graph-rest-1.0) to represent user or applic
Same as other place.

2021-06-15 01:25 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageReactionIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageReactionIdentitySet?view=graph-rest-1.0) to represent user which react
Same as other place.

2021-06-15 01:30 UTC, opbld32 commented
Docs Build status updates of commit _[5ae8e5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ae8e5abc50fdef51ef1242e78d08502a23741d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-15 02:17 UTC, opbld33 commented
Docs Build status updates of commit _[30d05f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30d05f40fceac958afe3f1c73aac4908967bfefd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-16 21:47 UTC, JarbasHorst requested changes

2021-06-16 21:47 UTC, JarbasHorst commented on api-reference/v1.0/resources/chatmessagementionedidentityset.md
> +|conversation|[teamworkConversationIdentity](../resources/teamworkconversationidentity.md)|If present, represents a conversation (for instance team or channel) @mentioned in a [message](../resources/
Please, add a comma after for instance

2021-06-16 21:47 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkapplicationidentity.md
> +Represents an application in Microsoft Teams. `teamworkApplicationIdentity` is used to represents bots and outgoing webhooks @mentioned in messages.
Please, replace represents with represent

2021-06-16 21:47 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +Represents a conversation (chat, team, channel) in Microsoft Teams.
Please, add "or " before "channel"

2021-06-16 21:47 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkapplicationidentity.md
> +|applicationIdentityType|teamworkApplicationIdentityType| Type of application being referenced. Possible values are: `aadApplication`, `bot`, `tenantBot`, `office365Connector`, `outgoingWebhook`, and
Since "unknownFutureValue" can't be really used, it's not worth it to mention this enum member in this article. In this case, can you please remove "unknownFutureValue" from possible values.

2021-06-16 21:47 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +|conversationIdentityType|teamworkConversationIdentityType|Type of conversation. Possible values are: `team`, `channel`, `chat`, and `unknownFutureValue`.|
Since "unknownFutureValue" can't be really used, it's not worth it to mention this enum member in this article. In this case, can you please remove "unknownFutureValue" from possible values.

2021-06-16 21:47 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
Since "unknownFutureValue" can't be really used, it's not worth it to mention this enum member in this article. In this case, can you please remove "unknownFutureValue" from possible values.

2021-06-16 22:20 UTC, RamjotSingh commented on api-reference/v1.0/resources/teamworkconversationidentity.md
> +|conversationIdentityType|teamworkConversationIdentityType|Type of conversation. Possible values are: `team`, `channel`, `chat`, and `unknownFutureValue`.|
This is v1. So I think it is worth keeping the value here since adding anything new will mean use of unknownFutureValue

2021-06-16 22:20 UTC, RamjotSingh commented on api-reference/v1.0/resources/teamworkuseridentity.md
> +|userIdentityType|teamworkUserIdentityType| Type of user. Possible values are: `aadUser`, `onPremiseAadUser`, `anonymousGuest`, `federatedUser`, `personalMicrosoftAccountUser`, `skypeUser`, `phoneUse
Same as other v1 doc

2021-06-16 22:23 UTC, opbld31 commented
Docs Build status updates of commit _[f55ae5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f55ae5b47bb6f01cdf62e598126e27db0587fd24)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-410a7304)

<a id="410a7304"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106162222536522-13037%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V%2FZ%2BMz0RHGw3hn2sBUzXZP2P6uzTdyYyqRTl2ESfxeA%3D&st=2021-06-16T22%3A18%3A14Z&se=2021-07-17T22%3A23%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 22:25 UTC, opbld32 commented
Docs Build status updates of commit _[2b16d27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b16d275b7bcb6caba54539d2b9b6b0b31a23f9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-17 21:39 UTC, JarbasHorst requested changes

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-beta) to represent applications in Micro
Please, mention that teamworkApplicationIdentity is a resource. Suggested revision:

Added the ... resource ...

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkUserIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkUserIdentity?view=graph-rest-beta) to represent users in Microsoft Teams. This new
Please, mention that teamworkUserIdentity is a resource. Suggested revision:

Added the ... resource ...

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkTagIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkTagIdentity?view=graph-rest-beta) to present tags in Microsoft Teams. This new type
Please,

- replace present with represent
- mention that teamworkTagIdentity is a resource. Suggested revision:
Added the ... resource ...

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageReactionIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageReactionIdentitySet?view=graph-rest-beta) to represent user which reac
Please,

- mention that chatMessageReactionIdentitySet is a resource. Suggested revision:
Added the ... resource ...
- write JSON with capital letters

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-1.0) to represent applications in Micros
Please, mention that teamworkApplicationIdentity is a resource. Suggested revision:

Added the ... resource ...

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkUserIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkUserIdentity?view=graph-rest-1.0) to represent users in Microsoft Teams. This new t
Please, mention that teamworkUserIdentity is a resource. Suggested revision:

Added the ... resource ...

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkConversationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkConversationIdentity?view=graph-rest-1.0) to represent conversations (team,
Please,

- add or before chat
- mention that teamworkConversationIdentity is a resource. Suggested revision:
Added the ... resource ...

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [teamworkTagIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkTagIdentity?view=graph-rest-1.0) to present tags in Microsoft Teams. This new type d
Please,

- replace present with represent
- mention that teamworkTagIdentity is a resource. Suggested revision:
Added the ... resource ...

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added teamworkApplicationIdentityType to represent types of application in Microsoft Teams (bot, aadApplication etc)",
- Please, mention that teamworkApplicationIdentityType is an enumeration. Suggested revision:
Added the ... enumeration ...
- I recommend moving the parenthetical to follow application instead of Microsoft Teams, for clarity

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added teamworkConversationIdentityType to represent types of conversations in Microsoft Teams (chat, channel, team etc)",
- Please, mention that teamworkConversationIdentityType is an enumeration. Suggested revision:
Added the ... enumeration ...
- I recommend moving the parenthetical to follow conversations instead of Microsoft Teams, for clarity

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added teamworkUserIdentityType to represent types of users in Microsoft Teams (aadUser, federatedUser etc)",
- Please, mention that teamworkUserIdentityType is an enumeration. Suggested revision:
Added the ... enumeration ...
- I recommend moving the parenthetical to follow users instead of Microsoft Teams, for clarity

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageFromIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageFromIdentitySet?view=graph-rest-1.0) to represent sender of a [chatMessage
Please,

- mention that chatMessageFromIdentitySet is a resource. Suggested revision:
Added the ... resource ...
- write JSON with capital letters

2021-06-17 21:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added [chatMessageReactionIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageReactionIdentitySet?view=graph-rest-1.0) to represent user which react
Please,

- mention that chatMessageReactionIdentitySet is a resource. Suggested revision:
Added the ... resource ...
- write JSON with capital letters

2021-06-17 21:39 UTC, JarbasHorst commented on api-reference/beta/resources/teamworkapplicationidentity.md
> +|applicationIdentityType|teamworkApplicationIdentityType| Type of application being referenced. Possible values are: `aadApplication`, `bot`, `tenantBot`, `office365Connector`, and `outgoingWebhook`.
Please, avoid using gerunds where possible; in this case, you can change "being" to "that is".

2021-06-17 21:39 UTC, JarbasHorst commented on api-reference/v1.0/resources/teamworkapplicationidentity.md
> +|applicationIdentityType|teamworkApplicationIdentityType| Type of application being referenced. Possible values are: `aadApplication`, `bot`, `tenantBot`, `office365Connector`, `outgoingWebhook` and
Please, avoid using gerunds where possible; in this case, you can change "being" to "that is".

2021-06-23 06:10 UTC, RamjotSingh commented on api-reference/v1.0/resources/chatmessagementionedidentityset.md
> +{
We don't have tags in v1 yet.

2021-06-23 06:28 UTC, opbld33 commented
Docs Build status updates of commit _[bcda374](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bcda37494898c73da0cdd76f6dd16814c9cf4b16)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-69c92a8b)

<a id="69c92a8b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106230627428630-13037%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qd%2FxRSn5M0yjEyOUkaCBNTLPKqC6tVdT0eaQr5XDaJk%3D&st=2021-06-23T06%3A23%3A05Z&se=2021-07-24T06%3A28%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 06:33 UTC, opbld31 commented
Docs Build status updates of commit _[2c5f422](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c5f422c0edbfaf7b981234dd2b09bb74f84d801)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-23 19:29 UTC, JarbasHorst requested changes

2021-06-23 19:29 UTC, JarbasHorst commented on api-reference/v1.0/resources/chatmessagementionedidentityset.md
> +|tag|[teamworkTagIdentity](../resources/teamworktagidentity.md)|If present, represents a tag @mentioned in a team [message](../resources/chatmessage.md).|
According to your feedback, v1 doesn't support tags yet. In this case, the tag property should be removed from the ## Properties section, right?

2021-06-23 19:29 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the resource [teamworkConversationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkConversationIdentity?view=graph-rest-beta) to represent conver
Please, add or before chat.

2021-06-23 19:39 UTC, JarbasHorst requested changes

2021-06-23 19:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the resource [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-beta) to represent applicat
Please, add a dot after etc.

2021-06-23 19:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the enumeration teamworkApplicationIdentityType to represent types of application (bot, aadApplication etc) in Microsoft Teams",
Please, add a dot after etc.

2021-06-23 19:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the enumeration teamworkUserIdentityType to represent types of users (aadUser, anonymousGuest etc) in Microsoft Teams",
Please, add a dot after etc.

2021-06-23 19:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the resource [teamworkApplicationIdentity](https://docs.microsoft.com/en-us/graph/api/resources/teamworkApplicationIdentity?view=graph-rest-1.0) to represent applicati
Please, add a dot after etc.

2021-06-23 19:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the enumeration teamworkApplicationIdentityType to represent types of application (bot, aadApplication etc) in Microsoft Teams",
Please, add a dot after etc.

2021-06-23 19:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the enumeration teamworkConversationIdentityType to represent types of conversations (chat, channel, team etc) in Microsoft Teams",
Please, add a dot after etc.

2021-06-23 19:39 UTC, JarbasHorst commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the enumeration teamworkUserIdentityType to represent types of users (aadUser, anonymousGuest etc) in Microsoft Teams",
Please, add a dot after etc.

2021-06-23 20:40 UTC, RamjotSingh commented on api-reference/v1.0/resources/chatmessagementionedidentityset.md
> +|tag|[teamworkTagIdentity](../resources/teamworktagidentity.md)|If present, represents a tag @mentioned in a team [message](../resources/chatmessage.md).|
Right, removing. Copy paste issue.

2021-06-23 21:00 UTC, RamjotSingh commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the enumeration teamworkConversationIdentityType to represent types of conversations (chat, channel, team etc) in Microsoft Teams",
Changed to OR since there are only 3.

2021-06-23 21:02 UTC, opbld31 commented
Docs Build status updates of commit _[9e91537](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e915371355348799ebada54b8ffd12a16dcef94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-23 21:38 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-06-25 00:49 UTC, opbld32 commented
Docs Build status updates of commit _[ff7c1ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff7c1eca31f364bac69b2b28ee50abd44bdf1a2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-25 00:51 UTC, Lauragra commented on api-reference/beta/resources/chatmessagementionedidentityset.md
> +|application|[identity](../resources/identity.md)|Inherited from [identitySet](../resources/identityset.md). If present, represents an application (for instance, bot) @mentioned in a [message](../res
Global: Please use "example" instead of "instance" for clarity and consistency. The word "instance" can also mean "occurrence"; I think what you mean here is example.

2021-06-25 00:51 UTC, Lauragra commented on api-reference/beta/resources/chatmessagereactionidentityset.md
> +Represents a user that reacted to a [message](../resources/chatmessage.md) in a chat or a channel. Only the `user` property has a value.
We apply bold formatting to property names; please update the formatting of user.

2021-06-25 00:52 UTC, Lauragra commented on api-reference/beta/resources/chatmessagereactionidentityset.md
> +|application|[identity](../resources/identity.md)|Inherited from [identitySet](../resources/identityset.md). Not set since applications can't react to messages.|
Change since to because. Since is another word that can have a different meaning (can imply time); we should use unambiguous words where possible to help readability.

2021-06-25 00:53 UTC, Lauragra commented on api-reference/beta/resources/chatmessagereactionidentityset.md
> +|user|[identity](../resources/identity.md)|Inherited from [identitySet](../resources/identityset.md). Details about the user which reacted to the message.|
Please change which to who, which is the appropriate pronoun when the subject is a person.

2021-06-25 00:55 UTC, Lauragra commented on api-reference/beta/resources/teamworkapplicationidentity.md
> +Represents an application in Microsoft Teams. `teamworkApplicationIdentity` is used to represent bots and outgoing webhooks @mentioned in messages.
Resource names should have bold formatting applied.

2021-06-25 00:56 UTC, Lauragra commented on api-reference/beta/resources/teamworkapplicationidentity.md
> +|id|String|Inherited from [identity](../resources/identity.md). Id of the application.|
In regular text, please use ID as the abbreviation for identity.

2021-06-25 00:56 UTC, Lauragra commented on api-reference/beta/resources/teamworkconversationidentity.md
> +|id|String|Inherited from [identity](../resources/identity.md). Id of the user.|
Id -> ID

2021-06-25 00:57 UTC, Lauragra commented on api-reference/beta/resources/teamworktagidentity.md
> +|id|String|Inherited from [identity](../resources/identity.md). Id of the tag.|
Id -> ID. Please fix globally.

2021-06-25 00:58 UTC, Lauragra commented on api-reference/v1.0/resources/chatmessagefromidentityset.md
> +Represents the sender of a [message](../resources/chatmessage.md) in a chat or a channel. This object may be `null` for a message that has been deleted or sent by the Microsoft Teams internal system,
Add a semicolon after system and change instance to example.

2021-06-28 23:19 UTC, opbld33 commented
Docs Build status updates of commit _[9c42cd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c42cd728e988619a2f4dd2cb203b7a3556b464c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-30 02:50 UTC, opbld33 commented
Docs Build status updates of commit _[4169dcf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4169dcf351b5a46b53403846320a7d3b8d683b25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkapplicationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkconversationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkconversationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkconversationidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworktagidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagidentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/beta/resources/teamworkuseridentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/beta/resources/teamworkuseridentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkuseridentity?view=graph-rest-beta&branch=pr-en-us-13037) (graph-rest-beta) |
[api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagefromidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagefromidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagemention.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagemention.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagemention?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagementionedidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagementionedidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagereactionidentityset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/chatmessagereactionidentityset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagereactionidentityset?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-13037) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkapplicationidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-08-ramjsing-messagingschemaidentitysetremoval/api-reference/v1.0/resources/teamworkapplicationidentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamwo [...]

2021-06-30 03:10 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the resource [chatMessageReactionIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatMessageReactionIdentitySet?view=graph-rest-beta) to represent us
Is there a reason to mention that the JSON schema for chatMessage hasn't changed in the changelog?

2021-06-30 03:16 UTC, merged