added new complex and action, updated changelog
microsoftgraph/microsoft-graph-docs pull request #13041
Opened 2021-06-09 03:44 UTC by ajburnle

2021-06-09 03:46 UTC, opbld30 commented
Docs Build status updates of commit _[7830d5c](https://github.com/ajburnle/microsoft-graph-docs/commits/7830d5cecdd6be53fc093d612f02a45f20cd4c89)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-cd3ccf56)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-5548ba7312c6df79ecc8604c23a1176d-cd3ccf56)
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-cd3ccf56"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 57, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="5548ba7312c6df79ecc8604c23a1176d-cd3ccf56"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md)
 - **Line 38, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106090344499702-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Wm%2FgqSVK9idC7RePDoW35vcZHLyWUcUIret0z7zNvn8%3D&st=2021-06-09T03%3A41%3A10Z&se=2021-07-10T03%3A46%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 03:52 UTC, opbld30 commented
Docs Build status updates of commit _[6bf4264](https://github.com/ajburnle/microsoft-graph-docs/commits/6bf4264f6e7720d52784f67ff34e50329d3239f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106090351172084-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OhoxMdnNXPOkesjaC8V8gCmgM5JuFqLslQ9vRIO20yk%3D&st=2021-06-09T03%3A47%3A45Z&se=2021-07-10T03%3A52%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 12:50 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +> This operation has no side effects, but because it accepts optional parameters in the POST body, it is configured as an action instead.
```suggestion
> This operation has no side effects, but because it accepts optional parameters in the POST body, it is configured as an action.
```

2021-06-09 12:51 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| Post body | microsoft.graph.accessPackageSubject | The user to evaluate for; if not specified, the user from the token is used instead. |
```suggestion
```
I am pretty sure we are not ready to support this yet.  Mark/Deb to confirm/deny.

2021-06-09 12:52 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +The following table shows the action that can be used to request an assignment for an access package.
```suggestion
The following table shows the return value that can be used to request an assignment for an access package.
```

2021-06-09 12:54 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +  "name": "accesspackageassignmentrequest_filterByCurrentUser"
```suggestion
  "name": "accesspackage_getapplicablepolicyrequirements"
```
Looks like copy/paste typo.

2021-06-09 12:55 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +            "existingAnswers": []
Can you double check with Mark about whether these should be empty or just not included?

2021-06-09 12:56 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +accessPackageAssignmentRequestRequirements are requirements that a caller must fulfill in order to successfully request an accessPackageAssignmentRequest for the accessPackage specified as part of th
```suggestion
`accessPackageAssignmentRequestRequirements` are requirements that a caller must fulfill in order to successfully create an `accessPackageAssignmentRequest` for the `accessPackage` specified as part of the URL. Requirements are determined by evaluating policies associated with the `accessPackage`. 
```

2021-06-09 12:58 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +> All properties are not-required and effectively read-only because we have no API for a caller to create/modify one of these objects.
```suggestion
```

I don't think this makes sense for public docs.

2021-06-09 13:00 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +```json
I think this blob has a bunch of unnecessary whitespace (maybe a side effect of copy/pasting with different line endings).

2021-06-09 17:53 UTC, ajburnle commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +```json
removed white space

2021-06-09 18:04 UTC, opbld30 commented
Docs Build status updates of commit _[d5049d3](https://github.com/ajburnle/microsoft-graph-docs/commits/d5049d3de9659890f1867f80958032dec71a7be9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106091802205102-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0OJzAi7Hef%2FYn5gPFnDmo0N4YRuxhJjnXN353du6Yxc%3D&st=2021-06-09T17%3A59%3A35Z&se=2021-07-10T18%3A04%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 18:06 UTC, opbld31 commented
Docs Build status updates of commit _[d5049d3](https://github.com/ajburnle/microsoft-graph-docs/commits/d5049d3de9659890f1867f80958032dec71a7be9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106091802098311-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jlWG42V9Qitnsim3PfYf7HhMC0n7J7d5DrYkkFi22bw%3D&st=2021-06-09T18%3A01%3A26Z&se=2021-07-10T18%3A06%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 18:10 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +## Function parameters
The order/naming of the H2 titles is standard. For example, an API article like this one should have the following H2 titles:
**Permissions** 
**HTTP request**
**Function parameters** - _review comment made here_
**Optional query parameters**
 **Request headers** 
**Request body**
**Response**
**Examples**.

2021-06-09 18:13 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| Collection(microsoft.graph.accessPackageAssignmentRequestRequirements) | One for each policy that the user is an `allowedRequestor` for. If there is a policy with no requirements, the `accessPackag
+ Previous feedback on H2 titles applies
+ Is this the **Response** section? Should be titled **Response** and only has details of the response code + the object type returned.
+ Applying previous feedback on H2s: Can't have a response object before showing the request syntax via a **HTTP request** H2 section.

2021-06-09 18:13 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +GET https://graph.microsoft.com/identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements)
```suggestion
GET https://graph.microsoft.com/identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements
```

2021-06-09 18:16 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +title: "accessPackageAssignmentRequestRequirements complex type"
File name looks off. Might be something like **accesspackageassignmentrequestrequirements.md**. Kindly check with the stub.

2021-06-09 18:17 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +description: "The accessPackageAssignmentRequestRequirements type identifies a collection requirements necessary to request the specified access package"
```suggestion
description: "The accessPackageAssignmentRequestRequirements type identifies the requirements necessary to request the specified access package."
```

2021-06-09 18:18 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +`accessPackageAssignmentRequestRequirements` are requirements that a caller must fulfill in order to successfully create an `accessPackageAssignmentRequest` for the `accessPackage` specified as part
Link accessPackageAssignmentRequest & accessPackage to the respective resources
```suggestion
**accessPackageAssignmentRequestRequirements** are requirements that a caller must fulfill in order to successfully create an accessPackageAssignmentRequest for the accessPackage specified as part of the URL. Requirements are determined by evaluating policies associated with the **accessPackage**. 
```

2021-06-09 18:21 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +| existingAnswers | Collection(microsoft.graph.accessPackageQuestion) | Answers that have already been provided. |
Link requestSchedule , accessPackageQuestion to the respective resources.
```suggestion
| schedule | requestSchedule | Schedule restrictions enforced, if any; null if none. |
| questions | accessPackageQuestion collection | Questions that are configured on the policy, required or optional; callers can determine if a question is required or optional based on the **isRequired** property on accessPackageQuestion. `null` if no questions are configured. |
| existingAnswers | accessPackageQuestion collection | Answers that have already been provided. |
```

2021-06-09 18:22 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +}
+ Remove whitespaces.
+ **isCustomAssignmentScheduleAllowed** property is a Boolean, so value is `false`.
+ 3 properties-**schedule**, **questions**, **existingAnswers**-missing here.

2021-06-09 18:25 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +> This operation has no side effects, but because it accepts optional parameters in the POST body, it is configured as an action.
Not required.

2021-06-10 01:12 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| Post body | microsoft.graph.accessPackageSubject | The user to evaluate for; if not specified, the user from the token is used instead. |
Yeah, I should have corrected this in the doc.  The parameters are something that we intend to support later, but not now.

The correct CSDL that we intend to publish for now is this:
```
<Action Name="getApplicablePolicyRequirements" IsBound="true">
    <Parameter Name="bindingParameter" Type="Microsoft.IGAELM.EC.FrontEnd.ExternalModel.accessPackage"/>
    <ReturnType Type="Collection(Microsoft.IGAELM.EC.FrontEnd.ExternalModel.accessPackageAssignmentRequestRequirements)"/>
</Action>
```

2021-06-10 17:29 UTC, opbld33 commented
Docs Build status updates of commit _[59dea00](https://github.com/ajburnle/microsoft-graph-docs/commits/59dea007446c09a5a26fa8df370ccadab2d15e22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101725163497-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mrk8DvqIOeDR9xrivKoCcjJCJ%2F%2FFsNXnaK1y6tNHxLs%3D&st=2021-06-10T17%3A24%3A05Z&se=2021-07-11T17%3A29%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 17:34 UTC, opbld31 commented
Docs Build status updates of commit _[3b47a38](https://github.com/ajburnle/microsoft-graph-docs/commits/3b47a388f8505d08f7dd7d8aa569b58fc208759c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-90b6e278)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-90b6e278"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101725475826-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XSmJv9Lzz1H5gyhXdyhj%2BGMJGnb1Qhp41ec8VcRJnio%3D&st=2021-06-10T17%3A29%3A09Z&se=2021-07-11T17%3A34%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 17:43 UTC, opbld33 commented
Docs Build status updates of commit _[fd1d573](https://github.com/ajburnle/microsoft-graph-docs/commits/fd1d573f2997d0510873f11c43e25e28291fb680)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-93627fbe)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-93627fbe"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106101739421846-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rIeEVg31ZgDqt%2Fm8T81TpWiP7ePYx4vPVCUP0QgIrGs%3D&st=2021-06-10T17%3A38%3A50Z&se=2021-07-11T17%3A43%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 23:29 UTC, opbld34 commented
Docs Build status updates of commit _[8eb0edc](https://github.com/ajburnle/microsoft-graph-docs/commits/8eb0edc4898e665579df233c1e4a261af6a6e430)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-0b8704c4)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-0b8704c4"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106102324400733-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4K5BJVU%2B3rVurByHZ4bkDjpgJfTk7vLTkWJ0BKpEUug%3D&st=2021-06-10T23%3A24%3A34Z&se=2021-07-11T23%3A29%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 23:35 UTC, opbld31 commented
Docs Build status updates of commit _[42917cd](https://github.com/ajburnle/microsoft-graph-docs/commits/42917cd1b200121c9012e24b0da41e3f80a96288)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-f96fa14e)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-f96fa14e"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106102330418711-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YS%2FoR8xRnD%2B%2Bv3pxB2EluMh%2FWJQfr7qElJpeexCb3qw%3D&st=2021-06-10T23%3A30%3A47Z&se=2021-07-11T23%3A35%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 23:38 UTC, opbld30 commented
Docs Build status updates of commit _[36e1a7c](https://github.com/ajburnle/microsoft-graph-docs/commits/36e1a7c96f6ad4dbf6b11c3182da903b254c67ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-3a035e1d)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-3a035e1d"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106102334539540-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=joMZJ1dq79%2B3ZBm3z1U%2BIpquhi4UyHP%2FBfDV%2BW%2B0NJM%3D&st=2021-06-10T23%3A33%3A51Z&se=2021-07-11T23%3A38%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 00:07 UTC, opbld33 commented
Docs Build status updates of commit _[f80dc4a](https://github.com/ajburnle/microsoft-graph-docs/commits/f80dc4a673ea3466b7f3bfd8c0ba429a59a0fb7d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-cf7ce488)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-cf7ce488"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110006150711-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wKZUq0A%2Br0Jc8ReanV%2BQ1rpjFLlEeJSEgE2mDOxWmQs%3D&st=2021-06-11T00%3A02%3A52Z&se=2021-07-12T00%3A07%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 00:10 UTC, opbld33 commented
Docs Build status updates of commit _[0c9b0f9](https://github.com/ajburnle/microsoft-graph-docs/commits/0c9b0f9bbb5df320899adfb554417c484adf0a23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-573eeccb)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-573eeccb"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110008510962-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vauN%2B5Wi5BsU63DOMFlEgZ2M9o%2F9iwy5Ts4hYRn2hEk%3D&st=2021-06-11T00%3A05%3A58Z&se=2021-07-12T00%3A10%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 00:14 UTC, opbld31 commented
Docs Build status updates of commit _[1513b8f](https://github.com/ajburnle/microsoft-graph-docs/commits/1513b8f8cb12ac6fb8ff0c0da8e46c17d2dde482)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-4d24494328fcf68a761c449f360709eb-514bfa9b)
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="4d24494328fcf68a761c449f360709eb-514bfa9b"></a>
### [api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 2, Column 21**: **[Warning-yaml-header-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110012580828-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hfTirIBlI%2F04GWytsTdRmCa6ke89%2F9hHEf%2F3l%2FEWatk%3D&st=2021-06-11T00%3A09%3A52Z&se=2021-07-12T00%3A14%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 00:55 UTC, opbld31 commented
Docs Build status updates of commit _[315adc3](https://github.com/ajburnle/microsoft-graph-docs/commits/315adc36c12fa6183be829d16148794c859fdf20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110054252573-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GIT1h0O4H%2FzEak4wBnYf8B1MF%2BeWVlOorr2YO2ZrjKw%3D&st=2021-06-11T00%3A50%3A58Z&se=2021-07-12T00%3A55%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 01:05 UTC, opbld33 commented
Docs Build status updates of commit _[315adc3](https://github.com/ajburnle/microsoft-graph-docs/commits/315adc36c12fa6183be829d16148794c859fdf20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110103369563-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tej2zP02NoCNdqSfMyKML1TzrrZkB2212%2FNsQwIRB9I%3D&st=2021-06-11T01%3A00%3A04Z&se=2021-07-12T01%3A05%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 01:11 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +|:---|:---|
@maaaatthill what are the request headers?

2021-06-11 01:11 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +## Optional query parameters
@maaaatthill and @FaithOmbongi  is it correct to put none here?

2021-06-11 01:12 UTC, opbld32 commented
Docs Build status updates of commit _[3b33c78](https://github.com/ajburnle/microsoft-graph-docs/commits/3b33c7865ecd4ea6fc2d052453bbbab780eaf70a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-requirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequest-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-requirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106110109581563-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O6ToVLSSnE6%2FtJun48wIEzD81vxwCz8OTyzAARbsQ9Q%3D&st=2021-06-11T01%3A07%3A36Z&se=2021-07-12T01%3A12%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 01:12 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| on | Microsoft.IGAELM.EC.FrontEnd.ExternalModel.accessPackage | |
@maaaatthill I updated based on new cdsl, but i didn't know the description. What should we put here?

2021-06-11 01:13 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +Do not supply a request body for this method.
@maaaatthill is this correct?

2021-06-11 01:13 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +## Response
@maaaatthill and @FaithOmbongi please review this section

2021-06-11 01:15 UTC, ajburnle commented
@FaithOmbongi I put all the sections in, but still got the apidoctor-beta failure. The error says "PowerShell exited with code '1'." What should I do next?

2021-06-11 15:42 UTC, FaithOmbongi reviewed
A few comments.
For the API doctor error, try changing the resource filename. The error leans towards it.

2021-06-11 15:42 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +**accessPackageAssignmentRequestRequirements** are requirements that a caller must fulfill in order to successfully create an accessPackageAssignmentRequest for the accessPackage specified as part of
- "create an accessPackageAssignmentRequest" - change to a link to the API.
- Q: Is this API in any way related/dependent on what has been set in [accessPackageAssignmentPolicy](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta)?
    - I see references to "policies" but it's not clear which these policies are.
    - If there's any dependency, let's make that clear. If the properties below inherit from accessPackageAssignmentPolicy, let's also make that clear, even in their descriptions.
    - I see from the accesspackage-getapplicablepolicyrequirements.md, you say there's no request body, and there's also no create API to set them...to me, both states infer that the properties are inherited from somewhere.

```suggestion
In [Azure AD Entitlement Management](entitlementmanagement-root.md), access package assignment request requirements are requirements that a caller must fulfill in order to successfully create an accessPackageAssignmentRequest for an accessPackage. Requirements are determined by evaluating policies associated with the **accessPackage**. 
```

2021-06-11 15:42 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +title: "accessPackageAssignmentRequestRequirements"
```suggestion
title: "accessPackageAssignmentRequestRequirements resource type"
```

2021-06-11 15:42 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +> All properties are not-required and effectively read-only because we have no API for a caller to create/modify one of these objects.
To remove.

2021-06-11 15:42 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +| existingAnswers | accessPackageQuestion collection | Answers that have already been provided. |
Previous comment on possible dependency/inheritance relationship applies here.

2021-06-11 15:42 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +            "isCustomAssignmentScheduleAllowed": [],
```suggestion
            "isCustomAssignmentScheduleAllowed": false,
```

2021-06-11 15:42 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the accessPackageAssignmentRequestRequirements complex type.",
Link to the complex type

2021-06-11 15:42 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the getApplicablePolicyRequirements operation.",
Added the [getApplicablePolicyRequirements](link to the API file] action to the [accessPackage](link) resource.

2021-06-11 15:42 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +GET https://graph.microsoft.com/identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements
API version missing.
GLOBAL: Resource names are in camel case, even in the URL, i.e. identityGovernance, entitlementManagement

2021-06-11 15:42 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "getApplicablePolicyRequirements"
Target looks like the **accessPackage** resource? 
For reference, changelog guidelines: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

2021-06-11 15:42 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest-requirements.md
> +
## Relationships

None

2021-06-11 16:32 UTC, opbld30 commented
Docs Build status updates of commit _[5e53416](https://github.com/ajburnle/microsoft-graph-docs/commits/5e5341626254b4798522c52db8ad7f38ba8aedd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106111630336387-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CA0ajkf8NvzRFIWaoxVq3jFMQBuvTgsG0GfZG7%2B%2Bn4s%3D&st=2021-06-11T16%3A27%3A09Z&se=2021-07-12T16%3A32%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 16:34 UTC, opbld32 commented
Docs Build status updates of commit _[e570fba](https://github.com/ajburnle/microsoft-graph-docs/commits/e570fba8d79740f5b50f1e30168590c5dabc99d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106111630587722-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Iw%2FTmNgafP3XnmmANBEbesPmxpNMagv%2F%2FraiSdg0EZk%3D&st=2021-06-11T16%3A29%3A42Z&se=2021-07-12T16%3A34%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 16:45 UTC, opbld34 commented
Docs Build status updates of commit _[e570fba](https://github.com/ajburnle/microsoft-graph-docs/commits/e570fba8d79740f5b50f1e30168590c5dabc99d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106111643311783-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H7mVO8itrLlpUANpkdhD6w9SnUjg0Zn%2B%2FwupuQq3c6I%3D&st=2021-06-11T16%3A40%3A05Z&se=2021-07-12T16%3A45%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 17:08 UTC, FaithOmbongi reviewed
Add the action to the [Methods table of accessPackage resource](https://docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta#methods).

Recommending you ask the API doctor experts about the error. Shared the channel via mail..

2021-06-11 17:08 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +# accesspackageassignmentrequestrequirements
```suggestion
# accessPackageAssignmentRequestRequirements resource type
```

2021-06-11 22:39 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +GET /identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements
Minor: This looks like inconsistent casing.  Should it be all lowercase (if so, accessPackages is inconsistent)?  Or should they be camelCase (in which case identityGovernance, entitlementManagement, and getApplicablePolicyRequirements are inconsistent).

2021-06-11 22:42 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +|:---|:---|
We'll eventually add support for the Accept-Language header, but until then, just the standard headers.

2021-06-11 23:05 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| on | Microsoft.IGAELM.EC.FrontEnd.ExternalModel.accessPackage | |
I actually think the whole Function parameters section shouldn't be here.  I'm hoping we can chat to clear up our confusions (which new CSDL? I hope I didn't give you something bad).

From [here](https://github.com/microsoftgraph/microsoft-graph-docs/blob/215b59bb20792c365033bb4d99f6a257c6bb1fe9/api-reference/beta/api/appconsentrequest-filterByCurrentUser.md), it looks like it doesn't include the binding parameter.

2021-06-11 23:06 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +Do not supply a request body for this method.
Yep, looks correct.

2021-06-11 23:08 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +If successful, this method returns a `200 OK` response code and an accessPackageAssignmentRequestRequirements collection in the response body, one object for each policy that the user is an `allowedR
```suggestion
If successful, this method returns a `200 OK` response code and an `accessPackageAssignmentRequestRequirements` collection in the response body, one object for each policy that the user is an `allowedRequestor`. If there is a policy with no requirements, the `accessPackageAssignmentRequestRequirements` will have false and null values. If there are no policies where the user is an `allowedRequestor`, an empty collection will be returned instead.
```

2021-06-11 23:09 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +GET /identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements
```suggestion
POST /identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements
```

2021-06-11 23:09 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +GET https://graph.microsoft.com/identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements
```suggestion
POST https://graph.microsoft.com/identitygovernance/entitlementmanagement/accessPackages/fb449cf8-3a59-4d86-bdfd-a1b7299681de/getapplicablepolicyrequirements
```

2021-06-14 20:17 UTC, davidmu1 approved these changes

2021-06-14 22:13 UTC, opbld34 commented
Docs Build status updates of commit _[1014654](https://github.com/ajburnle/microsoft-graph-docs/commits/10146543e0c853b4e232c433e1cf453a146664d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142212158380-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3nhf3i4nXeHQ5UQKOSg7R%2BkgGvSrph1crZhvmzG%2BctM%3D&st=2021-06-14T22%3A08%3A52Z&se=2021-07-15T22%3A13%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 22:15 UTC, opbld31 commented
Docs Build status updates of commit _[2a30812](https://github.com/ajburnle/microsoft-graph-docs/commits/2a3081288ca508f6ea2119ab42cfd44129285a9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142213373750-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=03qptvRzqJXFRmyZAAw%2Fs2MvSkuUVEcoOmtqB39%2BzYA%3D&st=2021-06-14T22%3A10%3A29Z&se=2021-07-15T22%3A15%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 22:17 UTC, opbld30 commented
Docs Build status updates of commit _[70d645c](https://github.com/ajburnle/microsoft-graph-docs/commits/70d645c6ba476c1d83bfa776c2a90354e5f173ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142213099405-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TvAArGfkBF0r4H%2B84rfELR43rl0kFErn2iU6JKEXc0Y%3D&st=2021-06-14T22%3A12%3A10Z&se=2021-07-15T22%3A17%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 01:40 UTC, opbld32 commented
Docs Build status updates of commit _[576acd4](https://github.com/ajburnle/microsoft-graph-docs/commits/576acd42f660193d329bea21b42d0b4da4b78a01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150138345354-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vPeyyRDb1zYy%2FXn1bEI%2BQ4zUjn42NWyzZrul4eOfOVs%3D&st=2021-06-15T01%3A35%3A22Z&se=2021-07-16T01%3A40%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 07:42 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| on | Microsoft.IGAELM.EC.FrontEnd.ExternalModel.accessPackage | |
Agreed. Checked the CSDL and no binding parameter is listed.

2021-06-15 07:48 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +            "isCustomAssignmentScheduleAllowed": [],
```suggestion
            "isCustomAssignmentScheduleAllowed": false,
```

2021-06-15 07:56 UTC, FaithOmbongi reviewed
- Minor comments.
- Previous unresolved comment on accessPackageAssignmentRequestRequirements.md still applies.

2021-06-15 07:56 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| policyId | String | The ID of the policy that these requirements are associated with. This ID can be used when creating a new assignment request. |
```suggestion
| policyId | String | The identifier of the policy that these requirements are associated with. This identifier can be used when creating a new assignment request. |
```

2021-06-15 07:56 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +
```suggestion
```

2021-06-15 07:56 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| schedule | requestSchedule | Schedule restrictions enforced, if any; null if none. |
```suggestion
| schedule | requestSchedule | Schedule restrictions that are enforced, if any; `null` if none. |
```

2021-06-15 07:56 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +None
Authorization header required.

2021-06-15 19:02 UTC, FaithOmbongi reviewed
Additional proposed corrections

2021-06-15 19:02 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the [getApplicablePolicyRequirements](../api/accesspackage-getapplicablepolicyrequirements.md) the [accessPackage][../resources/accesspackage.md] resource.",
```suggestion
          "Description": "Added the [getApplicablePolicyRequirements](https://docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements.md) action to the [accessPackage](https://docs.microsoft.com/en-us/graph/api/resources/accessPackage?view=graph-rest-beta) resource.",
```

2021-06-15 20:20 UTC, millicentachieng commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +
Add this block and include any other necessary properties
```
<!-- {
  "blockType": "resource",
  "@odata.type": "microsoft.graph.accessPackageAssignmentRequestRequirements"
}-->
```

2021-06-15 22:43 UTC, opbld31 commented
Docs Build status updates of commit _[77fb37a](https://github.com/ajburnle/microsoft-graph-docs/commits/77fb37af07cd534e5383b23b3a3cd69bde779986)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152241574941-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FgdZMaIqShcyGlAjJS614njmjX49SH05sM%2F3bjCq5I4%3D&st=2021-06-15T22%3A38%3A27Z&se=2021-07-16T22%3A43%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 22:45 UTC, opbld34 commented
Docs Build status updates of commit _[39c1061](https://github.com/ajburnle/microsoft-graph-docs/commits/39c1061886a7f95c38cb9f8fde5544f73048fcbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152242479466-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MspFbfwuVjBJgYT7a%2FVZ0BLW9pq%2B4buT9kocgV6%2BxSY%3D&st=2021-06-15T22%3A40%3A01Z&se=2021-07-16T22%3A45%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 22:46 UTC, opbld30 commented
Docs Build status updates of commit _[fd7ae75](https://github.com/ajburnle/microsoft-graph-docs/commits/fd7ae754e0bcd377b7b80a1e7749a00c98c880cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152244134300-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C7Lmo2%2BeDpaBjreddkODfzqiFet1vLD%2FpY7YV0i9b%2B4%3D&st=2021-06-15T22%3A41%3A50Z&se=2021-07-16T22%3A46%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 22:48 UTC, opbld32 commented
Docs Build status updates of commit _[7d57dae](https://github.com/ajburnle/microsoft-graph-docs/commits/7d57daed59144418a47f1837a76f66a968023fff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152246212416-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U22xET%2B4loy4DIiN4Jl2IGifuWzsrnWIyWujQn8iJdY%3D&st=2021-06-15T22%3A43%3A22Z&se=2021-07-16T22%3A48%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 22:50 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +None
@maaaatthill where can i find the authorization header for this doc?

2021-06-15 22:50 UTC, opbld32 commented
Docs Build status updates of commit _[efdf8c1](https://github.com/ajburnle/microsoft-graph-docs/commits/efdf8c12b76e357db89a60e20736bb53970b591c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-23b22c9c93468277ed6bd990b7036aea-fee43639)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="23b22c9c93468277ed6bd990b7036aea-fee43639"></a>
### [api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md)
 - **Line 39, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152248499181-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=90W%2Bi8tzr6w4omUnnl2%2F8hKj5dRY8GzVM9Su5WNdn9Y%3D&st=2021-06-15T22%3A45%3A21Z&se=2021-07-16T22%3A50%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 22:51 UTC, opbld31 commented
Docs Build status updates of commit _[efdf8c1](https://github.com/ajburnle/microsoft-graph-docs/commits/efdf8c12b76e357db89a60e20736bb53970b591c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) | [Details](#user-content-23b22c9c93468277ed6bd990b7036aea-8730295f)
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="23b22c9c93468277ed6bd990b7036aea-8730295f"></a>
### [api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md)
 - **Line 39, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152249009094-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g5Rc%2Fb9OEtTQrPi2tKu63cQImlgxuN%2FMRGou4HfiGi4%3D&st=2021-06-15T22%3A46%3A53Z&se=2021-07-16T22%3A51%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 23:50 UTC, markwahl-msft submitted a review, later dismissed
Also you may wish to consider adding a line for this API to the beta toc YML file, alongside the other access package APIs.

2021-06-15 23:50 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| on | Microsoft.IGAELM.EC.FrontEnd.ExternalModel.accessPackage | |
Microsoft.IGAELM... are internal names not visible to customers.  The type fields in these articles should use the public type names. e.g., accessPackage with a link to ../resource/accesspackage.md.

2021-06-15 23:50 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +None
authorization header should be the same as all the other API articles for EM

2021-06-15 23:50 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +| on | Microsoft.IGAELM.EC.FrontEnd.ExternalModel.accessPackage | |
Howevr, in this case there is no a parameter so this table is not needed.

2021-06-15 23:50 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +The following table shows the return value that can be used to request an assignment for an access package.
these aren't return values.  However see comment below that I don't think this table is needed so then this line isn't needed either, just say no parameters or similar.

2021-06-15 23:50 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackage.md
> +| [getApplicablePolicyRequirements](../api/accesspackage-getapplicablepolicyrequirements.md) | [accessPackageAssignmentRequestRequirements](../resources/accesspackageassignmentrequestrequirements.md)
the description should be 

Retrieve a list of **accessPackageAssignmentRequestRequirement** objects with request requirements.

2021-06-15 23:50 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| questions | [accessPackageQuestion](../resources/accesspackagequestion.md) collection | Questions that are configured on the policy, required or optional; callers can determine if a question is req
Remove the "null if no" isnce this isn't null, it's just absent. absent isn't the same as null.

2021-06-15 23:50 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| schedule | [requestSchedule](../resources/requestschedule.md) | Schedule restrictions that are enforced, if any; `null` if none. |
remove the "null if none'.

2021-06-16 00:20 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +The following table shows the return value that can be used to request an assignment for an access package.
Agreed; Ajane and I talked about this on Friday.

2021-06-16 00:21 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +None
Example: [filterByCurrentUser](https://docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&tabs=http)

2021-06-16 00:25 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +author: "markwahl-msft"
I may be wrong, but should the author be Ajane (well, your account name)?

2021-06-24 00:34 UTC, ajburnle commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +author: "markwahl-msft"
I had my name there first, but Faith told me to make it the PM. I'm not sure if that's a guideline or something

2021-06-24 01:06 UTC, opbld31 commented
Docs Build status updates of commit _[37fc9e3](https://github.com/ajburnle/microsoft-graph-docs/commits/37fc9e37f9464f927bec6ed8e8b5dc76f3b7bba5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7f463776)

<a id="7f463776"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240106201839-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TGZ5PixVQV65jEQFLYVKywUuvhK01jULucxMdZcHO0w%3D&st=2021-06-24T01%3A01%3A41Z&se=2021-07-25T01%3A06%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 01:16 UTC, opbld32 commented
Docs Build status updates of commit _[37fc9e3](https://github.com/ajburnle/microsoft-graph-docs/commits/37fc9e37f9464f927bec6ed8e8b5dc76f3b7bba5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cbb66e89)

<a id="cbb66e89"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240116313241-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EGAnyegtktHv9E3avbRn8wBt5vZ%2Bfdyfne0BDztYTyc%3D&st=2021-06-24T01%3A11%3A50Z&se=2021-07-25T01%3A16%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 01:42 UTC, opbld30 commented
Docs Build status updates of commit _[37fc9e3](https://github.com/ajburnle/microsoft-graph-docs/commits/37fc9e37f9464f927bec6ed8e8b5dc76f3b7bba5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240140421573-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F6k3e8rDBD3gm0yzp8U7rDfgmOW0EJ8q2V0X1x3jjtQ%3D&st=2021-06-24T01%3A37%3A06Z&se=2021-07-25T01%3A42%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 07:17 UTC, FaithOmbongi commented
@ajburnle ; you might want to take a look at the API doctor error. Seems you have a type mismatch.

![image](https://user-images.githubusercontent.com/14026935/123219054-1fb4d780-d4d5-11eb-817a-bc0e96d85d12.png)

Guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103179/API-Doctor-validate-examples

2021-06-24 18:21 UTC, opbld34 commented
Docs Build status updates of commit _[095567b](https://github.com/ajburnle/microsoft-graph-docs/commits/095567bece56ff5e01da761c423aedf807c32bc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241819589438-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aJ3GUo9ID42VanxddT58mHObfVg6CYkKgI%2Bp5QRIAEo%3D&st=2021-06-24T18%3A16%3A33Z&se=2021-07-25T18%3A21%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 18:25 UTC, opbld34 commented
Docs Build status updates of commit _[f8a9e5e](https://github.com/ajburnle/microsoft-graph-docs/commits/f8a9e5e2916b80bc77a5b8e16aac1d76713e8e65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241824191074-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5KPaye7TLQs0Fan3gfHKVslFpwa0pgtBf1OdMz0F89M%3D&st=2021-06-24T18%3A20%3A50Z&se=2021-07-25T18%3A25%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 18:37 UTC, opbld33 commented
Docs Build status updates of commit _[de43a11](https://github.com/ajburnle/microsoft-graph-docs/commits/de43a11af97ba52274f890c94fac012462e548e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241835546390-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8i133R65KnvpHSque7RNgNaW0J6ExVRhOUFjaWJdkHA%3D&st=2021-06-24T18%3A32%3A29Z&se=2021-07-25T18%3A37%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 09:03 UTC, FaithOmbongi requested changes
Checked the prod metadata and there seems to be a few differences in the property names. Just confirm.

2021-06-29 17:04 UTC, opbld33 commented
Docs Build status updates of commit _[c913a87](https://github.com/ajburnle/microsoft-graph-docs/commits/c913a8757a8942f0dc3f61e3c23c58844029bba7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106291703144468-13041%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ljl%2FBvky6Oa2L%2FDuLzCBDo5nr%2B7XUD6m78X0hhLI3k4%3D&st=2021-06-29T16%3A59%3A55Z&se=2021-07-30T17%3A04%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-02 18:45 UTC, FaithOmbongi reviewed
Hi @ajburnle , don't forget to surface this new action in the TOC.

2021-07-08 01:27 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +## Properties
!!!  Good catch, Faith!  This is my bad; I kind of merged two different changes to this object. (sorry meant to send this last week, but got too busy with on-call)

2021-07-15 01:26 UTC, opbld30 commented
Docs Build status updates of commit _[6cccf59](https://github.com/ajburnle/microsoft-graph-docs/commits/6cccf59d168e4571fa528f7eea39cc95849e8b24)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c4d06c94)

<a id="c4d06c94"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150126197761-13041%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A27%3A53Z&ske=2021-07-20T08%3A32%3A53Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A21%3A42Z&se=2021-08-15T01%3A26%3A42Z&sr=b&sp=r&sig=hEdqIivSKPMJ4khGPOL0W4MN8iH2iRWXqv14EmzAQo4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:30 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +# [HTTP]
```suggestion
```

2021-07-15 01:30 UTC, opbld31 commented
Docs Build status updates of commit _[73e5549](https://github.com/ajburnle/microsoft-graph-docs/commits/73e554978b268e9dbc17c33fa334a79dde1a8b81)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-948f8377)

<a id="948f8377"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150130267161-13041%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T12%3A39%3A56Z&ske=2021-07-21T12%3A44%3A56Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A25%3A52Z&se=2021-08-15T01%3A30%3A52Z&sr=b&sp=r&sig=C1APC7kMP7mpxHcg5GmgJ6UCbRA4%2FfJ8oyX6xmY1a50%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:31 UTC, opbld31 commented
Docs Build status updates of commit _[73e5549](https://github.com/ajburnle/microsoft-graph-docs/commits/73e554978b268e9dbc17c33fa334a79dde1a8b81)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cffc7224)

<a id="cffc7224"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150130374793-13041%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T03%3A03%3A12Z&ske=2021-07-21T03%3A08%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A26%3A20Z&se=2021-08-15T01%3A31%3A20Z&sr=b&sp=r&sig=rKr90111yIBJAxftonqDwnmVurD7ZTkhonKAjwttfzU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:36 UTC, opbld30 commented
Docs Build status updates of commit _[c445aad](https://github.com/ajburnle/microsoft-graph-docs/commits/c445aad5d19b7d6ab13aa38ad0136bd36f99052f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150134502891-13041%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A27%3A53Z&ske=2021-07-20T08%3A32%3A53Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A31%3A26Z&se=2021-08-15T01%3A36%3A26Z&sr=b&sp=r&sig=yv%2FBZcvsKUstjux9BdFHfYg3aiN0gmo05PpJ2UVAObY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 17:59 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +  ]
Agreed; 
- accessPackageMultipleChoiceQuestion -> accessPackageQuestion
- accessPackageAnswerString -> accessPackageAnswer

2021-07-21 23:47 UTC, slazo-ms commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +|:---|:---|
is this resolved?

2021-08-03 00:26 UTC, opbld33 commented
Docs Build status updates of commit _[ae0f825](https://github.com/ajburnle/microsoft-graph-docs/commits/ae0f825d2694a3e1f731ce67282f4cef140b8a8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108030023375207-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=0dGsqZdXOhlECAkpt03ac9UFzwznaNtGHvKmiK%2FDHgY%3D&st=2021-08-03T00%3A21%3A23Z&se=2021-09-03T00%3A26%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 18:23 UTC, ajburnle commented
#sign-off

2021-08-10 02:33 UTC, ajburnle commented
#sign-off

2021-08-10 07:39 UTC, FaithOmbongi requested changes
Minor changes requested.

2021-08-10 07:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +      "@odata.type": "microsoft.graph.accessPackageAnswer"
It will return one of the derived types instead of the abstract type.
```suggestion
      "@odata.type": "microsoft.graph.accessPackageAnswerString"
```

2021-08-10 07:39 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| existingAnswers | [accessPackageAnswer](../resources/accesspackageanswer.md) collection  | Answers that have already been provided. |
Let's order these properties alphabetically for easier scanning by our customers.

2021-08-10 07:39 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        },
```suggestion
      "ChangeList": [
        {
          "Id": "62d990bd-ac6b-482a-a161-10ca3c9e92f4",
          "ApiChange": "Method",
          "ChangedApiName": "getApplicablePolicyRequirements",
          "ChangeType": "Addition",
          "Description": "Added the [getApplicablePolicyRequirements](https://docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements.md) method to the [accessPackage](https://docs.microsoft.com/en-us/graph/api/resources/accessPackage?view=graph-rest-beta) resource.",
          "Target": "accessPackage"
        },
```

2021-08-10 07:39 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "CreatedDateTime": "2021-06-08T18:32:06Z",
```suggestion
      "CreatedDateTime": "2021-08-10T18:32:06Z",
```

2021-08-10 07:39 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +            "existingAnswers": []
```suggestion
            "existingAnswers": [],
            "schedule": []
```

2021-08-10 07:39 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +If successful, this method returns a `200 OK` response code and an `accessPackageAssignmentRequestRequirements` collection in the response body, one object for each policy that the user is an `allowe
Can we change this description to remove mention of allowedRequestor? It's not a property of accessPackage nor accessPackageAssignmentRequestRequirements.
```suggestion
If successful, this method returns a `200 OK` response code and an [accessPackageAssignmentRequestRequirements](../resources/accesspackageassignmentrequestrequirements.md) collection in the response body, one object for each policy that the user is an **allowedRequestor**. If there is a policy with no requirements, the **accessPackageAssignmentRequestRequirements** will have `false` and `null` values. If there are no policies where the user is an **allowedRequestor**, an empty collection will be returned instead.
```

2021-08-10 15:06 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +      "@odata.type": "microsoft.graph.accessPackageAnswer"
Yep, good catch.

2021-08-10 15:11 UTC, maaaatthill commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| existingAnswers | [accessPackageAnswer](../resources/accesspackageanswer.md) collection  | Answers that have already been provided. |
Faith, I've been wondering, I think I've seen different approaches -- which is easier for customers?
- Alphabetical
- "importance"/order of use? (e.g. if `isApproval*` are false, `isRequestorJustificationRequired` is not very useful -- and `isCustomAssignmentScheduleAllowed` is very closely related to `schedule` -- and similar for `questions` and `existingAnswers`)

2021-08-10 15:15 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +If successful, this method returns a `200 OK` response code and an `accessPackageAssignmentRequestRequirements` collection in the response body, one object for each policy that the user is an `allowe
No objection to the suggested changes above.

About allowedRequestor, though: allowedRequestors is a property on requestorSettings (on accessPackageAssignmentPolicy): https://docs.microsoft.com/en-us/graph/api/resources/requestorsettings?view=graph-rest-beta#properties.  Perhaps we should add a link to requestorSettings?

2021-08-10 15:15 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +            "existingAnswers": []
Good catch.

2021-08-10 16:35 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| existingAnswers | [accessPackageAnswer](../resources/accesspackageanswer.md) collection  | Answers that have already been provided. |
Hi Matt, we recommend alphabetical order because it allows customers to easily find properties whether on a short list or a growing list like the [User](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) resource. This also helps ensure that the customer can expect a consistent experience throughout the docset unlike if workloads apply different criteria to listing the properties in their resource articles.

2021-08-10 16:52 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +If successful, this method returns a `200 OK` response code and an `accessPackageAssignmentRequestRequirements` collection in the response body, one object for each policy that the user is an `allowe
> Perhaps we should add a link to requestorSettings?

We can mention the requestorSettings property but not without referencing it's parent resource, [accessPackageAssignmentPolicy](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta). Then, the link between the policy and the assignment request requirements should come out clearly-first in accessPackageAssignmentRequestRequirements's description. I believe I raised this question in an [earlier review feedback](https://github.com/microsoftgraph/microsoft-graph-docs/pull/13041#discussion_r650066219).

2021-08-10 17:19 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +If successful, this method returns a `200 OK` response code and an `accessPackageAssignmentRequestRequirements` collection in the response body, one object for each policy that the user is an `allowe
Makes sense (this comment and your earlier review feedback that you mentioned).

2021-08-10 18:46 UTC, opbld33 commented
Docs Build status updates of commit _[48356b1](https://github.com/ajburnle/microsoft-graph-docs/commits/48356b19d7ec1835f9466249ca38c4fd6e0df5f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108101845041645-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=BKGPB2j3xKjHjgfY1WMIeVWpcPe7yqtHdf3O3I2Zqlg%3D&st=2021-08-10T18%3A41%3A39Z&se=2021-09-10T18%3A46%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 18:49 UTC, Lauragra commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +## Optional query parameters
Generally we only include this section for GET operations, this doesn't apply to functions. Please remove.

2021-08-10 19:05 UTC, Lauragra commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +Allow callers to find properties that are required to successfully request an assignment for a specific access package.
Is this description clear enough for users? I'm not sure that this adequately describes the purpose of this API.

2021-08-10 19:11 UTC, opbld31 commented
Docs Build status updates of commit _[0bbcf97](https://github.com/ajburnle/microsoft-graph-docs/commits/0bbcf973e5602a8ae0c4bc5734fb3fcd2ff9cda1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108101908373793-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ft4xmiJwErMoDWzdhcrRJYeHnAEwAXNJl23EiVX6oeE%3D&st=2021-08-10T19%3A06%3A05Z&se=2021-09-10T19%3A11%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 22:32 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +Allow callers to find properties that are required to successfully request an assignment for a specific access package.
@maaaatthill what should we add to the description?

2021-08-10 22:32 UTC, opbld33 commented
Docs Build status updates of commit _[5ea7ad4](https://github.com/ajburnle/microsoft-graph-docs/commits/5ea7ad479e5e0ae3b8ffdbbfdfd651d4e2aa6e15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108102230081185-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=U5bAq%2F59GXyd%2F3RAht93uVX322a%2F6IBkJuAUK0P%2BFXc%3D&st=2021-08-10T22%3A27%3A42Z&se=2021-09-10T22%3A32%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 22:34 UTC, opbld34 commented
Docs Build status updates of commit _[8098411](https://github.com/ajburnle/microsoft-graph-docs/commits/8098411d8839d703d08e7279cbb6b3022440d411)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108102233095971-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=L4UR80TXvHxFbx9anjQsIErdUtxbTDGk28YF4jf7xpw%3D&st=2021-08-10T22%3A29%3A43Z&se=2021-09-10T22%3A34%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 22:36 UTC, opbld31 commented
Docs Build status updates of commit _[79b221d](https://github.com/ajburnle/microsoft-graph-docs/commits/79b221d64af12433501730209e516a2b966bbecf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108102234165427-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Wo2Kdu4QAvI9fO7%2BM8CG1pMFXrN0BeH9ffvFuDydcIM%3D&st=2021-08-10T22%3A31%3A14Z&se=2021-09-10T22%3A36%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 22:07 UTC, ajburnle commented on api-reference/beta/resources/accesspackageassignmentrequestrequirements.md
> +| existingAnswers | [accessPackageAnswer](../resources/accesspackageanswer.md) collection  | Answers that have already been provided. |
properties table alphabetized

2021-08-11 22:08 UTC, opbld33 commented
Docs Build status updates of commit _[231e36a](https://github.com/ajburnle/microsoft-graph-docs/commits/231e36a6e9e4124588952501431c1f9fca730b69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108112206274389-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=MYqKiWSZ0TomlkkBLmesjFT3GagGC1ScpOuNmZfP5e8%3D&st=2021-08-11T22%3A03%3A04Z&se=2021-09-11T22%3A08%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 22:14 UTC, opbld31 commented
Docs Build status updates of commit _[7ac9b22](https://github.com/ajburnle/microsoft-graph-docs/commits/7ac9b2238e055c840f273179036e68736b9116aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108112213096824-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=NlXiuXJ3VBYT8gdA%2Bo%2FfIT7psMxZDr4piCy2dN5gUAE%3D&st=2021-08-11T22%3A09%3A35Z&se=2021-09-11T22%3A14%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 22:53 UTC, ajburnle commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +Allow callers to find properties that are required to successfully request an assignment for a specific access package.
Updated the description to: In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can find properties of an [accessPackageAssignment](../resources/accesspackageassignment.md) object that are required for a user to successfully request an assignment for a specific access package.

2021-08-11 22:54 UTC, opbld31 commented
Docs Build status updates of commit _[6459b3c](https://github.com/ajburnle/microsoft-graph-docs/commits/6459b3cb474954053690ce1fd0e622f3126cf910)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108112252325584-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XLQhiBQnUm3U1rnk9%2Fdz71Pxv08fKrjWP%2BRcyTD9yXs%3D&st=2021-08-11T22%3A49%3A09Z&se=2021-09-11T22%3A54%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 22:55 UTC, opbld32 commented
Docs Build status updates of commit _[dd8fedf](https://github.com/ajburnle/microsoft-graph-docs/commits/dd8fedf3acc41d642128f1774973053f97829f1f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108112252453299-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=TKyAR3EzPwLS2T2TR5%2B4ug39Oao9YcClJk3m0%2B6YNII%3D&st=2021-08-11T22%3A50%3A38Z&se=2021-09-11T22%3A55%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 22:59 UTC, ajburnle commented
@Lauragra @FaithOmbongi Please take a look at the updated docs

2021-08-12 01:11 UTC, maaaatthill commented on api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can find properties of an [accessPackageAssignment](../resources/accesspackageassignment.md) object that are
What do you think of this?

```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), this action retrieves a list of [accessPackageAssignmentRequestRequirements](../resources/accesspackageassignmentrequestrequirements.md) objects that the currently signed-in user can use to create an [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md).  Each requirement object corresponds to an access package assignment policy that the currently signed-in user is allowed to request an assignment for.
```

2021-08-12 01:23 UTC, opbld31 commented
Docs Build status updates of commit _[65a441a](https://github.com/ajburnle/microsoft-graph-docs/commits/65a441a0b49f5a3c77127de72b00ce536135115c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/api/accesspackage-getapplicablepolicyrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequestrequirements.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/resources/accesspackageassignmentrequestrequirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequestrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-getapplicablepolicyrequirements?view=graph-rest-beta&branch=pr-en-us-13041) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-api-aprequestassignment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108120122003711-13041%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=w2M5jH%2FmfavruYQ3Xv1yNNmYMmOJfSp%2Fy9XrfEcTub4%3D&st=2021-08-12T01%3A18%3A16Z&se=2021-09-12T01%3A23%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 03:15 UTC, merged