Identity provider in v1.0
microsoftgraph/microsoft-graph-docs pull request #13082
Opened 2021-06-11 00:52 UTC by namkedia

2021-06-11 00:53 UTC, opbld34 commented
Docs Build status updates of commit _[aa2e6c3](https://github.com/namkedia/microsoft-graph-docs/commits/aa2e6c39663c5fc322265d6a114144341856c8b8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :x:Error | | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-97b0ff7b)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :x:Error | | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-97b0ff7b)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :x:Error | | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-97b0ff7b)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :x:Error | | [Details](#user-content-4a175de425c2e2bb8944e92298130399-97b0ff7b)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :x:Error | | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-97b0ff7b)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :x:Error | | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-97b0ff7b)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :x:Error | | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-97b0ff7b)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :x:Error | | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-97b0ff7b)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :x:Error | | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-97b0ff7b)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-97b0ff7b)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-97b0ff7b)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-97b0ff7b)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :warning:Warning | | [Details](#user-content-60c6062de545134a623d9bba3de4fc43-97b0ff7b)
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :warning:Warning | | [Details](#user-content-6b0889d4ebf6060cea263a904468132a-97b0ff7b)
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :warning:Warning | | [Details](#user-content-d3633d8e3f2047ea491226aceb66bc9c-97b0ff7b)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-97b0ff7b)

<a id="a84f5687169a846fd1db3637d83b0f24-97b0ff7b"></a>
### [api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md)
 - **Line 76, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-identityprovider-1-csharp-snippets.md'.`````
 - **Line 80, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-identityprovider-1-javascript-snippets.md'.`````
 - **Line 84, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-identityprovider-1-objc-snippets.md'.`````
 - **Line 88, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-identityprovider-1-java-snippets.md'.`````
 - **Line 135, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-identityprovider-2-csharp-snippets.md'.`````
 - **Line 139, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-identityprovider-2-javascript-snippets.md'.`````
 - **Line 143, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-identityprovider-2-objc-snippets.md'.`````
 - **Line 147, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-identityprovider-2-java-snippets.md'.`````
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-get.md(2,8), v1.0/api/identityprovider-get.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 54, Column 150**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/openidconnectprovider.md'.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Retrieve the properties and relationships of an identityProvider object.' is duplicated in 'v1.0/api/identityprovider-get.md(3,14)', 'v1.0/api/identityproviderbase-get.md(3,14)'.`````

<a id="b4f61280722f603141db4d23e5eb98bf-97b0ff7b"></a>
### [api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md)
 - **Line 73, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-identityprovider-3-csharp-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-identityprovider-3-javascript-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-identityprovider-3-objc-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-identityprovider-3-java-snippets.md'.`````
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review [...]

2021-06-11 01:05 UTC, opbld32 commented
Docs Build status updates of commit _[623a537](https://github.com/namkedia/microsoft-graph-docs/commits/623a537090f1d27630e0f9cf255d1434cd3ae1fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-64248755)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-64248755)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-64248755)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-64248755)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-64248755)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-64248755)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-64248755)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-64248755)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-64248755)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-64248755)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-64248755)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-64248755)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-60c6062de545134a623d9bba3de4fc43-64248755)
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-6b0889d4ebf6060cea263a904468132a-64248755)
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d3633d8e3f2047ea491226aceb66bc9c-64248755)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-64248755)
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |

<a id="ba90f08d4b9e2c25cf95ad19f863052f-64248755"></a>
### [api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Delete identityProvider - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/identityproviderbase-delete.md(2,8), v1.0/api/identityprovider-delete.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-r [...]

2021-06-11 01:19 UTC, opbld31 commented
Docs Build status updates of commit _[66215e0](https://github.com/namkedia/microsoft-graph-docs/commits/66215e090b3f2f73328fe7a43fe7c2c743e03103)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-faf29ddb)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-faf29ddb)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-faf29ddb)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-faf29ddb)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-faf29ddb)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-faf29ddb)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-faf29ddb)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-faf29ddb)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-faf29ddb)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-faf29ddb)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-faf29ddb)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-faf29ddb)
[api-reference/v1.0/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d82e588669de903bba04c7454e848a1b-faf29ddb)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-60c6062de545134a623d9bba3de4fc43-faf29ddb)
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-3239a0d826065c68413116bea17d657a-faf29ddb)
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-6b0889d4ebf6060cea263a904468132a-faf29ddb)
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d3633d8e3f2047ea491226aceb66bc9c-faf29ddb)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-faf29ddb)

<a id="ba90f08d4b9e2c25cf95ad19f863052f-faf29ddb"></a>
### [api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles] [...]

2021-06-28 22:07 UTC, opbld30 commented
Docs Build status updates of commit _[34bfd52](https://github.com/namkedia/microsoft-graph-docs/commits/34bfd524a2e18c8661f5628b11c0cc49cfbfb93d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-318e8749)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-318e8749)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-318e8749)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-318e8749)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-318e8749)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-318e8749)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-318e8749)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-318e8749)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-318e8749)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-318e8749)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-318e8749)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-318e8749)
[api-reference/v1.0/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d82e588669de903bba04c7454e848a1b-318e8749)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-60c6062de545134a623d9bba3de4fc43-318e8749)
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-3239a0d826065c68413116bea17d657a-318e8749)
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-6b0889d4ebf6060cea263a904468132a-318e8749)
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d3633d8e3f2047ea491226aceb66bc9c-318e8749)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-318e8749)

<a id="ba90f08d4b9e2c25cf95ad19f863052f-318e8749"></a>
### [api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles] [...]

2021-06-29 02:19 UTC, opbld32 commented
Docs Build status updates of commit _[7d3a61b](https://github.com/namkedia/microsoft-graph-docs/commits/7d3a61b61381392eae4eeb2a9df05a5c3bcb8c3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-9e515782)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-9e515782)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-9e515782)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-9e515782)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-9e515782)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-9e515782)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-9e515782)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-9e515782)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-9e515782)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-9e515782)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-9e515782)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-9e515782)
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-3239a0d826065c68413116bea17d657a-9e515782)
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-cae3adaffa367467a5e7ac634c9ce1ce-9e515782)
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-6b0889d4ebf6060cea263a904468132a-9e515782)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9e515782)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |

<a id="ba90f08d4b9e2c25cf95ad19f863052f-9e515782"></a>
### [api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles? [...]

2021-06-29 02:30 UTC, opbld31 commented
Docs Build status updates of commit _[8dd298c](https://github.com/namkedia/microsoft-graph-docs/commits/8dd298c93284a3fd4c8f353daa21a459b54bf49b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-bee0c5fe)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-bee0c5fe)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-bee0c5fe)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-bee0c5fe)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-bee0c5fe)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-bee0c5fe)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-bee0c5fe)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-bee0c5fe)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-bee0c5fe)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-bee0c5fe)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-bee0c5fe)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-bee0c5fe)
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-3239a0d826065c68413116bea17d657a-bee0c5fe)
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-cae3adaffa367467a5e7ac634c9ce1ce-bee0c5fe)
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-6b0889d4ebf6060cea263a904468132a-bee0c5fe)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-bee0c5fe)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |

<a id="ba90f08d4b9e2c25cf95ad19f863052f-bee0c5fe"></a>
### [api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles? [...]

2021-06-29 02:32 UTC, opbld30 commented
Docs Build status updates of commit _[b22e161](https://github.com/namkedia/microsoft-graph-docs/commits/b22e161c18c1276a824640141ebce29fa911618c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-4ef13cf6)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-4ef13cf6)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-4ef13cf6)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-4ef13cf6)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-4ef13cf6)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-4ef13cf6)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-4ef13cf6)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-4ef13cf6)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-4ef13cf6)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-4ef13cf6)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-4ef13cf6)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-4ef13cf6)
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-3239a0d826065c68413116bea17d657a-4ef13cf6)
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-cae3adaffa367467a5e7ac634c9ce1ce-4ef13cf6)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-4ef13cf6)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |

<a id="ba90f08d4b9e2c25cf95ad19f863052f-4ef13cf6"></a>
### [api-reference/v1.0/api [...]

2021-06-29 03:11 UTC, opbld31 commented
Docs Build status updates of commit _[e7b732e](https://github.com/namkedia/microsoft-graph-docs/commits/e7b732e0ba37a6a83ecd929a35c2a39ea8a23976)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-b211a8a0)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-b211a8a0)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-b211a8a0)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-b211a8a0)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-b211a8a0)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-b211a8a0)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-b211a8a0)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-b211a8a0)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-b211a8a0)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-b211a8a0)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-b211a8a0)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-b211a8a0)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-b211a8a0)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |

<a id="ba90f08d4b9e2c25cf95ad19f863052f-b211a8a0"></a>
### [api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api [...]

2021-06-29 07:32 UTC, opbld32 commented
Docs Build status updates of commit _[b425316](https://github.com/namkedia/microsoft-graph-docs/commits/b425316409fb6367698ebc6491eab3fc0161c45e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-9b1ef88d)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-9b1ef88d)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-9b1ef88d)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-9b1ef88d)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-9b1ef88d)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-9b1ef88d)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-9b1ef88d)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-9b1ef88d)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-9b1ef88d)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-9b1ef88d)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-9b1ef88d)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-9b1ef88d)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |

<a id="ba90f08d4b9e2c25cf95ad19f863052f-9b1ef88d"></a>
### [api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md)
 - **Line 2, Column 8**: ** [...]

2021-06-29 07:35 UTC, opbld31 commented
Docs Build status updates of commit _[68d13c5](https://github.com/namkedia/microsoft-graph-docs/commits/68d13c5a71d35301dcc8c143789eec37910575d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-8b6d319e)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-8b6d319e)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-8b6d319e)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-8b6d319e)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-8b6d319e)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-8b6d319e)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-8b6d319e)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-8b6d319e)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-8b6d319e)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-8b6d319e)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-8b6d319e)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-8b6d319e)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-8b6d319e)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api- [...]

2021-06-29 07:44 UTC, opbld31 commented
Docs Build status updates of commit _[6e3097e](https://github.com/namkedia/microsoft-graph-docs/commits/6e3097ebc1723585d5fbe4e30c3ca00ffef1241d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-0f202d8a)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-0f202d8a)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-0f202d8a)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-0f202d8a)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-0f202d8a)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-0f202d8a)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-0f202d8a)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-0f202d8a)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-0f202d8a)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-0f202d8a)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-0f202d8a)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-0f202d8a)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-0f202d8a)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api- [...]

2021-06-29 07:46 UTC, opbld31 commented
Docs Build status updates of commit _[94540ba](https://github.com/namkedia/microsoft-graph-docs/commits/94540ba80a0c0a4528d7511cc6ecdfab70589cf1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-2ffdbfd4)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-2ffdbfd4)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-2ffdbfd4)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-2ffdbfd4)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-2ffdbfd4)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-2ffdbfd4)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-2ffdbfd4)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-2ffdbfd4)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-2ffdbfd4)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-2ffdbfd4)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-2ffdbfd4)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-2ffdbfd4)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-2ffdbfd4)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api- [...]

2021-06-29 07:50 UTC, opbld33 commented
Docs Build status updates of commit _[b112662](https://github.com/namkedia/microsoft-graph-docs/commits/b112662d9027339e5943f393ace3c4ad7c1d0116)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-2ebf54a4)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-2ebf54a4)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-2ebf54a4)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-2ebf54a4)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-2ebf54a4)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-2ebf54a4)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-2ebf54a4)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-2ebf54a4)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-2ebf54a4)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-2ebf54a4)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-2ebf54a4)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-2ebf54a4)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-2ebf54a4)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api- [...]

2021-06-29 08:06 UTC, opbld32 commented
Docs Build status updates of commit _[4bfae30](https://github.com/namkedia/microsoft-graph-docs/commits/4bfae309b14f4910403b74710262996581807898)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-2e82e775)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-2e82e775)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-2e82e775)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-2e82e775)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-2e82e775)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-2e82e775)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-2e82e775)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-2e82e775)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-2e82e775)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-2e82e775)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-2e82e775)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-2e82e775)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-2e82e775)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api- [...]

2021-06-30 10:14 UTC, FaithOmbongi requested changes

2021-06-30 10:14 UTC, FaithOmbongi commented on api-reference/v1.0/resources/openidconnectidentityprovider.md
> +### responseType value
```suggestion
### responseType values
```

2021-06-30 10:14 UTC, FaithOmbongi commented on api-reference/v1.0/resources/openidconnectidentityprovider.md
> +### responseMode value
```suggestion
### responseMode values
```

2021-06-30 10:14 UTC, FaithOmbongi commented on api-reference/v1.0/resources/openidconnectidentityprovider.md
> +|token|An access token is returned back to Azure AD B2C from the custom identity provider. (This value is not supported by Azure AD B2C at the moment)|
These intended/apply to the previous comment? Just align with [Example 2 in the Enumerations guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic).

2021-06-30 10:14 UTC, FaithOmbongi commented on api-reference/v1.0/resources/socialidentityprovider.md
> +|clientId|String|The client identifier for the application obtained when registering the application with the identity provider. Required.|
```suggestion
|clientId|String|The identifier for the client application obtained when registering the application with the identity provider. Required.|
```

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "To support configuring an identity provider in an Azure AD and Azure AD B2C tenant, introduced new resource type [identityProviderBase](https://docs.microsoft.com/en-us/grap
Adding a little info of what the API does sounds good. I recommend the following format

_Added the [identityProviderBase](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0) resource to support configuring an identity provider in an Azure AD and Azure AD B2C tenant._]

Recommendation applies to the other entries

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Id": "224526a5-09a4-4895-9b8b-40e8984a4111",
Previous comment for resources also applies to methods.

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Deprecated the [identityProvider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0) entity to replace it with new [identity provider
- Suggestion applies to other entries
- If all its methods are deprecated, just say "... and related operations and methods" instead and remove the corresponding entries

```suggestion
          "Description": "Deprecated the [identityProvider](https://docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0) resource to replace it with new [identity provider API](https://docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0).",
```

2021-06-30 10:14 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "SubArea": ""
```suggestion
      "CreatedDateTime": "2021-03-30T00:00:00.000Z",
      "WorkloadArea": "Identity and access",
      "SubArea": "Identity and sign-in"
```

2021-07-02 18:32 UTC, FaithOmbongi reviewed
**Deprecation** is now an accepted value for ChangeType.

2021-07-02 18:32 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Change",
```suggestion
          "ChangeType": "Deprecation",
```

2021-07-02 18:32 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Change",
```suggestion
          "ChangeType": "Deprecation",
```

2021-07-02 18:32 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Change",
```suggestion
          "ChangeType": "Deprecation",
```

2021-07-02 18:32 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Change",
```suggestion
          "ChangeType": "Deprecation",
```

2021-07-02 18:32 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Change",
```suggestion
          "ChangeType": "Deprecation",
```

2021-07-02 18:32 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Change",
```suggestion
          "ChangeType": "Deprecation",
```

2021-07-02 18:32 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Change",
```suggestion
          "ChangeType": "Deprecation",
```

2021-07-13 06:05 UTC, opbld32 commented
Docs Build status updates of commit _[51e0ff2](https://github.com/namkedia/microsoft-graph-docs/commits/51e0ff24198680fb515039bcf74f987470dd2169)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-53d83263)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-53d83263)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-53d83263)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-53d83263)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-53d83263)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-53d83263)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-53d83263)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-53d83263)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-53d83263)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-53d83263)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-53d83263)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-53d83263)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-53d83263)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-53d83263)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-grap [...]

2021-07-13 06:07 UTC, opbld31 commented
Docs Build status updates of commit _[b52dbd1](https://github.com/namkedia/microsoft-graph-docs/commits/b52dbd18ae4197d627ec365a0e9b87cac5e4db5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-58833588)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-58833588)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-58833588)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-58833588)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-58833588)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-58833588)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-58833588)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-58833588)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-58833588)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-58833588)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-58833588)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-58833588)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-58833588)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-58833588)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-grap [...]

2021-07-13 06:12 UTC, opbld32 commented
Docs Build status updates of commit _[e689a22](https://github.com/namkedia/microsoft-graph-docs/commits/e689a222b194277a0e21d60da86976ae469c8840)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-6a4a0481)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-6a4a0481)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-6a4a0481)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-6a4a0481)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-6a4a0481)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-6a4a0481)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-6a4a0481)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-6a4a0481)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-6a4a0481)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-6a4a0481)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-6a4a0481)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-6a4a0481)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-6a4a0481)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-6a4a0481)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-grap [...]

2021-07-13 06:13 UTC, opbld32 commented
Docs Build status updates of commit _[5610a70](https://github.com/namkedia/microsoft-graph-docs/commits/5610a70b557c433fbdce19208308d5536331567a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-e9d08784)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-e9d08784)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-e9d08784)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-e9d08784)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-e9d08784)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-e9d08784)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-e9d08784)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-e9d08784)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-e9d08784)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-e9d08784)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-e9d08784)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-e9d08784)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-e9d08784)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-e9d08784)
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/openidconnectidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-grap [...]

2021-07-13 06:45 UTC, namkedia commented on api-reference/v1.0/resources/builtinidentityprovider.md
> +|id|String|The identifier of the identity provider. Inherited from [identityProviderBase](../resources/identityproviderbase.md). Read-only.|
This comes from the identityproviderbase

2021-07-13 06:45 UTC, namkedia commented on api-reference/v1.0/resources/builtinidentityprovider.md
> +    "displayName": "String",
This comes from the identityproviderbase

2021-07-13 06:53 UTC, opbld30 commented
Docs Build status updates of commit _[10db6c5](https://github.com/namkedia/microsoft-graph-docs/commits/10db6c5ff929b817a6a6e448b901d6aab8045cea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-4958d56f)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-4958d56f)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-4958d56f)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-4958d56f)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-4958d56f)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-4958d56f)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-4958d56f)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-4958d56f)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-4958d56f)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-4958d56f)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-4958d56f)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-4958d56f)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-4958d56f)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-4958d56f)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resou [...]

2021-07-14 07:19 UTC, opbld33 commented
Docs Build status updates of commit _[c987f75](https://github.com/namkedia/microsoft-graph-docs/commits/c987f754c3f8ffe00003d501ba644e22414e4bd9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-b72c9037)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-b72c9037)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-b72c9037)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-b72c9037)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-b72c9037)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-b72c9037)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-b72c9037)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-b72c9037)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-b72c9037)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-b72c9037)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-b72c9037)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-b72c9037)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-b72c9037)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-b72c9037)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resou [...]

2021-07-14 07:26 UTC, namkedia commented on api-reference/v1.0/resources/openidconnectidentityprovider.md
> +|responseType|String|The response type describes the type of information sent back in the initial call to the authorization_endpoint of the custom identity provider. Possible values: `code` , `id_tok
remove oidc from v1.0

2021-07-14 07:26 UTC, namkedia commented on api-reference/v1.0/resources/claimsmapping.md
> +title: "claimsMapping resource type"
remove oidc from v1.0 doc

2021-07-14 07:28 UTC, opbld30 commented
Docs Build status updates of commit _[ee23d5f](https://github.com/namkedia/microsoft-graph-docs/commits/ee23d5f65fb055ed4980a0d4dcaff62bb75dad1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-864298e4)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-864298e4)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-864298e4)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-864298e4)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-864298e4)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-864298e4)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-864298e4)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-864298e4)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-864298e4)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-864298e4)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-864298e4)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-864298e4)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-864298e4)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-864298e4)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/so [...]

2021-07-14 07:31 UTC, opbld33 commented
Docs Build status updates of commit _[15c066d](https://github.com/namkedia/microsoft-graph-docs/commits/15c066d164cbaea47c7dd2fcc539b46e84149851)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-610249f2)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-610249f2)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-610249f2)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-610249f2)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-610249f2)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-610249f2)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-610249f2)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-610249f2)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-610249f2)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-610249f2)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-610249f2)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-610249f2)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-610249f2)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-610249f2)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/so [...]

2021-07-15 16:00 UTC, FaithOmbongi requested changes
Proposed minor changes. Just a little clean up.

2021-07-15 16:57 UTC, opbld32 commented
Docs Build status updates of commit _[3067f8a](https://github.com/namkedia/microsoft-graph-docs/commits/3067f8a20a767313bae76aa33682e0afa50058c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-bb3440c9)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-bb3440c9)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-bb3440c9)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-bb3440c9)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-bb3440c9)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-bb3440c9)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-bb3440c9)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-bb3440c9)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-bb3440c9)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-bb3440c9)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-bb3440c9)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-bb3440c9)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-bb3440c9)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-bb3440c9)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/so [...]

2021-07-15 16:58 UTC, opbld33 commented
Docs Build status updates of commit _[ce063a9](https://github.com/namkedia/microsoft-graph-docs/commits/ce063a95ade453d126a19bedca92ce8d5e6f13f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-0c226371)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-0c226371)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-0c226371)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-0c226371)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-0c226371)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-0c226371)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-0c226371)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-0c226371)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-0c226371)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-0c226371)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-0c226371)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-0c226371)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-0c226371)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-0c226371)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/so [...]

2021-07-15 17:00 UTC, opbld31 commented
Docs Build status updates of commit _[0410293](https://github.com/namkedia/microsoft-graph-docs/commits/0410293d579177fb25ee63608c21ac8ca6e32a6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-25230274)
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-25230274)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-25230274)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-25230274)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-25230274)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-25230274)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-25230274)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-25230274)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-25230274)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-25230274)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-25230274)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-25230274)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-25230274)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-25230274)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/so [...]

2021-07-15 17:18 UTC, opbld32 commented
Docs Build status updates of commit _[6ed2c5c](https://github.com/namkedia/microsoft-graph-docs/commits/6ed2c5c2c1705c37fb151ff19e9a78d6a77e321e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-3bbc33a8)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-3bbc33a8)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-3bbc33a8)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-3bbc33a8)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-3bbc33a8)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-3bbc33a8)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-3bbc33a8)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-3bbc33a8)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-3bbc33a8)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-3bbc33a8)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-3bbc33a8)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-3bbc33a8)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-3bbc33a8)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-15 20:59 UTC, opbld33 commented
Docs Build status updates of commit _[1b8a58d](https://github.com/namkedia/microsoft-graph-docs/commits/1b8a58ddc8eb26113df81acf201bcd917ae62763)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-56e44283)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-56e44283)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-56e44283)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-56e44283)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-56e44283)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-56e44283)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-56e44283)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-56e44283)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-56e44283)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-56e44283)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-56e44283)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-56e44283)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-56e44283)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-15 21:01 UTC, opbld31 commented
Docs Build status updates of commit _[1b8a58d](https://github.com/namkedia/microsoft-graph-docs/commits/1b8a58ddc8eb26113df81acf201bcd917ae62763)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-576bdfcb)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-576bdfcb)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-576bdfcb)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-576bdfcb)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-576bdfcb)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-576bdfcb)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-576bdfcb)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-576bdfcb)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-576bdfcb)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-576bdfcb)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-576bdfcb)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-576bdfcb)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-576bdfcb)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-15 21:03 UTC, opbld33 commented
Docs Build status updates of commit _[6606201](https://github.com/namkedia/microsoft-graph-docs/commits/660620145cf4860b731a193216f4d992e687e75c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-60bc3e89)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-60bc3e89)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-60bc3e89)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-60bc3e89)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-60bc3e89)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-60bc3e89)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-60bc3e89)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-60bc3e89)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-60bc3e89)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-60bc3e89)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-60bc3e89)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-60bc3e89)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-60bc3e89)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-15 21:05 UTC, opbld30 commented
Docs Build status updates of commit _[5b5544a](https://github.com/namkedia/microsoft-graph-docs/commits/5b5544afa97d8f6431ab7876d339f74008d1a0eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-dafa3db9)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-dafa3db9)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-dafa3db9)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-dafa3db9)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-dafa3db9)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-dafa3db9)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-dafa3db9)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-dafa3db9)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-dafa3db9)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-dafa3db9)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-dafa3db9)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-dafa3db9)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-dafa3db9)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-15 21:06 UTC, opbld34 commented
Docs Build status updates of commit _[9c78c53](https://github.com/namkedia/microsoft-graph-docs/commits/9c78c5366980d1a7a1bc4fd5a6adea8c1220f4a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-4cca6574)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-4cca6574)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-4cca6574)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-4cca6574)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-4cca6574)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-4cca6574)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-4cca6574)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-4cca6574)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-4cca6574)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-4cca6574)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-4cca6574)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-4cca6574)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-4cca6574)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-15 23:01 UTC, opbld34 commented
Docs Build status updates of commit _[b7a1fe0](https://github.com/namkedia/microsoft-graph-docs/commits/b7a1fe0b5dcf6fb9826a9cf721e69ee942c6c271)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-bb3962fe)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-bb3962fe)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-bb3962fe)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-bb3962fe)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-bb3962fe)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-bb3962fe)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-bb3962fe)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-bb3962fe)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-bb3962fe)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-bb3962fe)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-bb3962fe)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-bb3962fe)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-bb3962fe)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-15 23:03 UTC, opbld31 commented
Docs Build status updates of commit _[edadaec](https://github.com/namkedia/microsoft-graph-docs/commits/edadaecc344298e6db7ad0f0331711d7438bfbab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-604e0f64)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-604e0f64)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-604e0f64)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-604e0f64)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-604e0f64)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-604e0f64)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-604e0f64)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-604e0f64)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-604e0f64)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-604e0f64)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-604e0f64)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-604e0f64)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-604e0f64)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-16 05:55 UTC, opbld33 commented
Docs Build status updates of commit _[bcf1f31](https://github.com/namkedia/microsoft-graph-docs/commits/bcf1f31758259f94ee78e63616a8508ae186adde)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ba90f08d4b9e2c25cf95ad19f863052f-9822c244)
[api-reference/v1.0/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-a84f5687169a846fd1db3637d83b0f24-9822c244)
[api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-53b92e365bc823cf396ec989ecd55cb1-9822c244)
[api-reference/v1.0/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-b4f61280722f603141db4d23e5eb98bf-9822c244)
[api-reference/v1.0/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4eb9545ec97ed0d2dc35ee48d12296dd-9822c244)
[api-reference/v1.0/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityprovider-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-4a175de425c2e2bb8944e92298130399-9822c244)
[api-reference/v1.0/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-238ebdfe5651c522a8c5efad39d95a31-9822c244)
[api-reference/v1.0/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-7b145057a9cf0793deaae89442f9d04c-9822c244)
[api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d9eeb7858b5f81e191122f869e67472c-9822c244)
[api-reference/v1.0/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-d45697b142ed0e8ec4b6c413d8e34db8-9822c244)
[api-reference/v1.0/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-dd986de373deda45a98cc4e8d1135577-9822c244)
[api-reference/v1.0/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-ac63d51321a8d3e821c9bc7515e29f4c-9822c244)
[api-reference/v1.0/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-9822c244)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-13082) (graph-rest-beta) |
[api-reference/v1.0/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/claimsmapping.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/claimsmapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/claimsmapping?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-1.0&branch=pr-en-us-13082) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [...]

2021-07-16 05:56 UTC, FaithOmbongi approved these changes

2021-07-17 01:00 UTC, Lauragra commented on api-reference/v1.0/api/identityproviderbase-delete.md
> +# Delete identityProvider
Should the topic title here be "Delete socialIdentityProvider", and the file name be socialidentityprovider-delete? It seems that the file name, title, and description do not match.

2021-07-17 01:11 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +          - name: Built-in identity provider
The link to this v1.0 resource topic does not appear to be working on the review site; please double check the TOC entries.

2021-07-17 01:15 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +          - name: Built-in identity provider
Can you help me understand the reason for this TOC structure? From the TOC, is it clear to users which of the operations apply to which resources? It seems that different methods apply to the built-in and social identity providers based on the Methods tables, but they are grouped together in the TOC.

2021-07-19 16:28 UTC, namkedia commented on api-reference/v1.0/api/identityproviderbase-delete.md
> +# Delete identityProvider
No, we need to add other identityprovider types in the future. it should be delete identity provider.

2021-07-19 16:30 UTC, namkedia commented on api-reference/v1.0/toc.yml
> +          - name: Built-in identity provider
We have grouped all the identity provider types in the same set called identity provider and not separated it. Two more types will be added to this and our hope is to have them all represented in identity providers.

2021-07-19 18:52 UTC, merged