Teams - Messaging APIs system event messages support
microsoftgraph/microsoft-graph-docs pull request #13085
Opened 2021-06-11 04:07 UTC by harshnat

2021-06-11 04:09 UTC, opbld31 commented
Docs Build status updates of commit _[b9d52bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9d52bf828895a18b770db61f09ddbaf927c6ca1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-f01212ea)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-f01212ea)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-dacf66ca67c127e24f870e78def53c59-f01212ea)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_ [...]

2021-06-11 04:57 UTC, opbld32 commented
Docs Build status updates of commit _[6c14581](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c14581c0a7a6d10006b62b4c446184fb62068be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-064172ea)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-064172ea)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.m [...]

2021-06-11 05:53 UTC, opbld34 commented
Docs Build status updates of commit _[b1f4687](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1f46870800cc45db09a3d17d5d308bb029dd377)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-8a1661b1)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-8a1661b1)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.m [...]

2021-06-11 07:13 UTC, opbld30 commented
Docs Build status updates of commit _[2272cbb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2272cbbc777c5408bd76ad9b4341072a3ee826e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-e5d62b02)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-e5d62b02)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.m [...]

2021-06-11 11:12 UTC, RamjotSingh commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +This message is generated when conversation member user's role is updated.
```suggestion
This message is generated when role of a member in a chat, channel or a team has been updated.
```

2021-06-11 11:12 UTC, RamjotSingh commented on api-reference/beta/resources/eventmessagedetail.md
> +* [callEndedEventMessageDetail](../resources/callStartedEventMessageDetail.md)
Add this in tabular format with 2 columns

1. Link to resource
2. Short description of what it represents

2021-06-11 11:12 UTC, RamjotSingh commented on api-reference/beta/resources/eventmessagedetail.md
> +System messages are messages generated for events such as members added to a channel, channel name updated, channel description updated.
Specify one example (member removed from a chat etc) for chat and one for team.

2021-06-11 11:12 UTC, RamjotSingh commented on changelog/Microsoft.Teams.GraphSvc.json
> +      "SubArea": "Microsoft.Teams.Shifts"
Wrong SubArea.

2021-06-11 11:12 UTC, RamjotSingh commented on changelog/Microsoft.Teams.GraphSvc.json
> +        {
Move all changes to Teams.Core.json

2021-06-14 14:14 UTC, opbld32 commented
Docs Build status updates of commit _[6c590ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c590ac3d13991697eeda021460b526cbc61de8d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-dfa14dbd)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-dfa14dbd)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.m [...]

2021-06-14 14:28 UTC, opbld31 commented
Docs Build status updates of commit _[ccd5616](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccd561676622730ad941ad7ed81629ad50624336)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-6772ff14)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-6772ff14)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.m [...]

2021-06-17 15:47 UTC, anandab-msft commented
@JarbasHorst - can you review this one as well.

2021-06-22 21:53 UTC, JarbasHorst requested changes

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
> +description: "Represents details for channel set as favorite by default event"
Please, add a period at the end of the sentence. Also, consider updating the description since this article is about "...UnsetAsFavorite..."

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +This message is generated when role of a member in a channel or a team has been updated.
Please, add the before role

Articles help readers and translation software identify the nouns and modifiers in a sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/eventmessagedetail.md
> +This is an abstract type for representing system event message details.
Please, rephrase this sentence to avoid gerunds. Suggested revision:

- This abstract type represents system event message details.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/eventmessagedetail.md
> +System messages are messages generated for events such as members added to a channel, members added to a chat, team description updated.
Please, add and after "...members added to a chat,...":

- ...members added to a chat, and team description updated.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/eventmessagedetail.md
> +
Please, add the Properties section to this article.

Properties and JSON representation are required headings in resource articles.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +description: "Represents details for meeting policy updated event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +This message is generated when meeting option **Allow meeting chat** is updated.
Please, add the before meeting 

Articles help readers and translation software identify the nouns and modifiers in a sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +|meetingChatEnabled|Boolean|Represents if the meeting chat is enabled or not.|
Please, replace if with whether

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/membersaddedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/membersaddedeventmessagedetail.md
> +This message is generated when members are added to a chat, a channel or a team.
Please, add a comma after "a channel":

- ...added to a chat, a channel, or a team.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/membersaddedeventmessagedetail.md
> +description: "Represents details for members added event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/membersdeletedeventmessagedetail.md
> +This message is generated when members are removed from a chat, a channel or a team.
Please, add a comma after "a channel":

...removed from a chat, a channel, or a team.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/membersdeletedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/membersjoinedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/memberslefteventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/memberslefteventmessagedetail.md
> +description: "Represents details for members left event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +description: "Represents details for tab updated event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +description: "Represents details for team archived event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +description: "Represents details for team created event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +description: "Represents details for team description updated event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +This message is generated when team's description is updated.
Please, add a before team's 

Articles help readers and translation software identify the nouns and modifiers in a sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +|teamDescription|String|Updated description for the team.|
Please, add The before updated

Articles help readers and translation software identify the nouns and modifiers in a sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamjoiningdisabledeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamjoiningdisabledeventmessagedetail.md
> +description: "Represents details for team joining disabled event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamjoiningenabledeventmessagedetail.md
> +description: "Represents details for team joining enabled event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamjoiningenabledeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +description: "Represents details for team renamed event message"
Please, add a period at the end of the sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +|teamDisplayName|String|Updated name of the team.|
Please, add The before updated

Articles help readers and translation software identify the nouns and modifiers in a sentence.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
> +This message is generated when a teamsApp is removed from a channel, a chat or a team.
Please, add a comma after "a chat":

- ... removed from a channel, a chat, or a team.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamunarchivedeventmessagedetail.md
> +## Example response
Please, remove this section.

The "## Example response" heading doesn't follow our standards for resource templates. Supported H2 sections are: Methods, Properties, Relationships, JSON representation, and See also. Examples are supported in APIs => ## Response heading, and then under Examples, ### Response.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +This message is generated when a teamsApp is installed in a channel, a chat or a team.
Please, add a comma after "a chat":

- ... installed in a channel, a chat, or a team.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +|teamsAppDisplayName|String|Name of the teamApp.|
Sometimes there are also properties called "name". To avoid possible confusion, I recommend you replacing Name with Display Name

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +This message is generated when a teamsApp is upgraded in a channel, a chat or a team.
Please, add a comma after "a chat":

- ... upgraded in a channel, a chat, or a team.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +|teamsAppDisplayName|String|Name of the teamsApp.|
Sometimes there are also properties called "name". To avoid possible confusion, I recommend you replacing Name with Display Name

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/chatmessage.md
> +|messageType|string|The type of chat message. The possible values are: `message`, `systemEventMessage`.|
According to your changes in the enums.md file, possible values for messageType should also include other enum members. Please, update the list of possible values.

2021-06-22 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel or a team e.g. members were added etc.
Please, add a comma after "a channel".
Please, replace e.g. with for example. Also, don't forget to add commas before and after "for example".
For clarity, I recommend you adding "In this case," before "\`messageType\` will be set"

2021-06-24 11:40 UTC, opbld33 commented
Docs Build status updates of commit _[6e7fb9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e7fb9b73e0bf83acc52392481cb5074cb21a2ab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8bca9cb2)

<a id="8bca9cb2"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241139508749-13085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WOQBsN33ZfByLlV92rddEe3yhUxPhCl3gz6%2BTYqjAZQ%3D&st=2021-06-24T11%3A35%3A15Z&se=2021-07-25T11%3A40%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 11:40 UTC, opbld34 commented
Docs Build status updates of commit _[ac4556d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac4556d34dc8aaba3d159bbdacde071ae04983ab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3218001b)

<a id="3218001b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241140330896-13085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kC7CZsS6IevgUPX9iSXeihpTn%2FQhFJH72vEyDgyGJdw%3D&st=2021-06-24T11%3A35%3A53Z&se=2021-07-25T11%3A40%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 11:47 UTC, opbld31 commented
Docs Build status updates of commit _[4ba7a93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ba7a9336ab5fd6b2cd0a080c0c80da715ffbc4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-ff30abf9)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-ff30abf9)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-ff30abf9)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-ff30abf9)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-ff30abf9)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-ff30abf9)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-ff30abf9)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?v [...]

2021-06-24 11:53 UTC, opbld33 commented
Docs Build status updates of commit _[efcfbc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efcfbc954d707390433787af9c459e8e551895c6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-0632ea0d)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-0632ea0d)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-0632ea0d)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-0632ea0d)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-0632ea0d)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-0632ea0d)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-0632ea0d)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?v [...]

2021-06-24 11:54 UTC, harshnat commented on api-reference/beta/resources/callrecordingeventmessagedetail.md
> +description: "Represents details for call recording event message"
Done

2021-06-24 11:55 UTC, harshnat commented on api-reference/beta/resources/calltranscripteventmessagedetail.md
> +description: "Represents details for call transcript event message"
Done

2021-06-24 11:56 UTC, harshnat commented on api-reference/beta/resources/channeladdedeventmessagedetail.md
> +description: "Represents details for a channel added event"
Done

2021-06-24 11:57 UTC, harshnat commented on api-reference/beta/resources/channeladdedeventmessagedetail.md
> +Represents details a channel added event message.
Done

2021-06-24 11:57 UTC, harshnat commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +description: "Represents details for a channel deleted event"
Done

2021-06-24 11:57 UTC, harshnat commented on api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md
> +description: "Represents details for channel description updated event message"
Done

2021-06-24 11:58 UTC, harshnat commented on api-reference/beta/resources/channelrenamedeventmessagedetail.md
> +description: "Represents details for channel renamed event message"
Done

2021-06-24 11:58 UTC, harshnat commented on api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md
> +|channelDescription|String|Updated description of the channel.|
Done

2021-06-24 11:58 UTC, harshnat commented on api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md
> +This message is generated when channel's description is updated.
Done

2021-06-24 11:59 UTC, harshnat commented on api-reference/beta/resources/channelrenamedeventmessagedetail.md
> +|channelDisplayName|String|Updated name of the channel.|
Done

2021-06-24 11:59 UTC, harshnat commented on api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
> +description: "Represents details for channel set as favorite by default event"
Done

2021-06-24 12:00 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|messageType|string|The type of chat message. The possible values are: `message`, `systemEventMessage`.|
Removed the extra values from enum.md file as we don't support those types.

2021-06-24 12:00 UTC, harshnat commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +This message is generated when role of a member in a channel or a team has been updated.
Done

2021-06-24 12:02 UTC, harshnat commented on api-reference/beta/resources/eventmessagedetail.md
> +
Added Properties section.
There are no properties for this type, do we still need this section ?

2021-06-24 12:02 UTC, harshnat commented on api-reference/beta/resources/eventmessagedetail.md
> +This is an abstract type for representing system event message details.
Done

2021-06-24 12:03 UTC, harshnat commented on api-reference/beta/resources/eventmessagedetail.md
> +System messages are messages generated for events such as members added to a channel, members added to a chat, team description updated.
Done

2021-06-24 12:03 UTC, harshnat commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +description: "Represents details for meeting policy updated event message"
Done

2021-06-24 12:04 UTC, harshnat commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +This message is generated when meeting option **Allow meeting chat** is updated.
Done

2021-06-24 12:04 UTC, harshnat commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +|meetingChatEnabled|Boolean|Represents if the meeting chat is enabled or not.|
Done

2021-06-24 12:04 UTC, harshnat commented on api-reference/beta/resources/membersaddedeventmessagedetail.md
> +This message is generated when members are added to a chat, a channel or a team.
Done

2021-06-24 12:05 UTC, harshnat commented on api-reference/beta/resources/membersdeletedeventmessagedetail.md
> +This message is generated when members are removed from a chat, a channel or a team.
Done

2021-06-24 12:05 UTC, harshnat commented on api-reference/beta/resources/memberslefteventmessagedetail.md
> +description: "Represents details for members left event message"
Done

2021-06-24 12:05 UTC, harshnat commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +description: "Represents details for team archived event message"
Done

2021-06-24 12:06 UTC, harshnat commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +description: "Represents details for team created event message"
Done

2021-06-24 12:06 UTC, harshnat commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +This message is generated when team's description is updated.
Done

2021-06-24 12:06 UTC, harshnat commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +description: "Represents details for team description updated event message"
Done

2021-06-24 12:07 UTC, harshnat commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +|teamDescription|String|Updated description for the team.|
Done

2021-06-24 12:07 UTC, harshnat commented on api-reference/beta/resources/teamjoiningdisabledeventmessagedetail.md
> +description: "Represents details for team joining disabled event message"
Done

2021-06-24 12:08 UTC, harshnat commented on api-reference/beta/resources/teamjoiningenabledeventmessagedetail.md
> +description: "Represents details for team joining enabled event message"
Done

2021-06-24 12:09 UTC, harshnat commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +description: "Represents details for team renamed event message"
Done

2021-06-24 12:09 UTC, harshnat commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +|teamDisplayName|String|Updated name of the team.|
Done

2021-06-24 12:09 UTC, harshnat commented on api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
> +This message is generated when a teamsApp is removed from a channel, a chat or a team.
Done

2021-06-24 12:10 UTC, harshnat commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +This message is generated when a teamsApp is installed in a channel, a chat or a team.
Done

2021-06-24 12:10 UTC, harshnat commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +|teamsAppDisplayName|String|Name of the teamApp.|
Done

2021-06-24 12:10 UTC, harshnat commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +This message is generated when a teamsApp is upgraded in a channel, a chat or a team.
Done

2021-06-24 12:10 UTC, harshnat commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +|teamsAppDisplayName|String|Name of the teamsApp.|
Done

2021-06-24 12:11 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel or a team e.g. members were added etc.
Done

2021-06-24 12:15 UTC, harshnat commented on api-reference/beta/resources/membersaddedeventmessagedetail.md
> +description: "Represents details for members added event message"
Done

2021-06-24 12:15 UTC, harshnat commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +description: "Represents details for tab updated event message"
Done

2021-06-24 12:19 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +## Example response
@JarbasHorst @Lauragra there are 28 new types that are being added, it would not be feasible to add examples for all 28 types in the APIs -> Response section.
Is there an alternative here ?

2021-06-24 20:55 UTC, JarbasHorst requested changes

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel, or a team, for example, members were a
Please, add a comma after "In this case":

- In this case, `messageType` will...

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +## Example response
@harshnat, I checked with Laura and yes, you should remove the Example response H2 headings because they aren't supported in resource type articles. You should make sure that the API topics include example responses that reflect the new types.

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/eventmessagedetail.md
> +
In this case, the value here can be None. Suggested revision:

\#\# Properties
None.

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/eventmessagedetail.md
> +description: "Represents base type for event message detail."
Please, add the before base.

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/channeladdedeventmessagedetail.md
> +description: "Represents details for a channel added event."
For consistency with your other articles, please add message after event.

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +description: "Represents details for a channel deleted event."
For consistency with your other articles, please add message after event.

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +Represents details for a channel deleted event.
For consistency with your other articles, please add message after event.

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/membersdeletedeventmessagedetail.md
> +Represents details for members added event message.
Please, replace added with deleted.

2021-06-24 20:55 UTC, JarbasHorst commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +Represents details for team description updated event message.
Please, update this sentence. This article is about team renamed and not team description updated.

2021-06-25 21:03 UTC, angelgolfer-ms commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +---
GLOBAL:
If all these new complex types for event message details are based on the eventMessageDetail type as described in the api.md file, then please make sure:
(a) Document a resource type topic for the base type
(b) For each derived type, in the top section, add a paragraph preceding the "Permissions" section that has a sentence "Inherited from {base type name and link to it}."
(C) In the "JSON representation" section, in the JSON that's presented as an HTML comment. include a line like this:
"baseType": "microsoft.graph.eventmessagedetail"

This is to make sure you let API Doctor verify the JSON in your examples, in case you add properties to the base type in the future. Also this would set consistent expectations for customers; there are other APIs that use base types, and that's how we document them.
More info here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-06-25 21:28 UTC, angelgolfer-ms commented
Hi @harshnat , that's an interesting way your team decided to expose details about events that can happen to a team, channel, chat, or in the context of a meeting.
So that we don't break the template and expectations of customers for what's in a resource topic and API topic (i.e., examples should go to an API topic and not the resource topic), I'd recommend you create a concept topic.

Note that the concept topic is not just to contain these example JSON blocks. I think customers will appreciate if the topic describes the following:
(A) First describe the mechanism - for the scenarios/events (give a couple of examples), customers can use the applicable GET operations to get chatMessage resource(s). If chatMessage has the messageType indicating the message is about an event, then the eventDetail property would provide the details.

(B) Then list the supported events (listed in lines 27-39 of api.md file). It might be helpful to categorize them in some way that's easier to scan and tell whether the event applies to a team, channel, chat, or the context of a meeting. 
- Include the applicable GET operations (lines 19-22).
- Include the name of the applicable event message detail complex type (derived type). Link to the section for the corresponding type in (C).
It would be helpful to make this scannable, so that customers would find this API capability intuitive.

(C) Then finally list each of the derived types, and provide the corresponding JSON example. (Each derived type and example JSON would be in its own sub-section so that you can from (B) to (C).)

2021-06-26 08:07 UTC, angelgolfer-ms commented
Also, after you create the afore-mentioned concept topic, please add a couple of links to that topic from each of the derived complex type topics. In each derived complex type topic, the two links are:
- A link to the section in the concept topics that specifies the corresponding example JSON for that type. 
- A link to the concept topic. Some lead-in sentence like "For more information about other types of events, see {concept topic}."

2021-06-29 15:15 UTC, opbld31 commented
Docs Build status updates of commit _[bcfdac7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bcfdac78bc3c4e9c6af3efa86c429db4c7ac8164)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-4ca9c976)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-4ca9c976)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-4ca9c976)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-4ca9c976)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-4ca9c976)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-4ca9c976)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-4ca9c976)
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/concepts/system-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-13085) | [Details](#user-content-bada6deab2f3bc324c92ee3b61379e4f-4ca9c976)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/re [...]

2021-06-29 15:17 UTC, opbld31 commented
Docs Build status updates of commit _[5a9f16f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a9f16f7cc6c01ec998956bd67174af10becfa88)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-c2e8a151)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-c2e8a151)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-c2e8a151)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-c2e8a151)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-c2e8a151)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-c2e8a151)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-c2e8a151)
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/concepts/system-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-13085) | [Details](#user-content-bada6deab2f3bc324c92ee3b61379e4f-c2e8a151)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/re [...]

2021-06-29 15:33 UTC, opbld32 commented
Docs Build status updates of commit _[7294a9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7294a9ec2c7019aa6382772c8e7bb110d31309d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-1f044f1d)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-1f044f1d)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-1f044f1d)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-1f044f1d)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-1f044f1d)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-1f044f1d)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-1f044f1d)
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/concepts/system-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-13085) | [Details](#user-content-bada6deab2f3bc324c92ee3b61379e4f-1f044f1d)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/re [...]

2021-06-29 15:38 UTC, opbld34 commented
Docs Build status updates of commit _[c306259](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3062596dd0f690106fe6ff4eac5d5da29f7201b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-d5ea7a0e)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-d5ea7a0e)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-d5ea7a0e)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-d5ea7a0e)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-d5ea7a0e)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-d5ea7a0e)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-d5ea7a0e)
[concepts/system-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/concepts/system-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/system-messages?branch=pr-en-us-13085) | [Details](#user-content-bada6deab2f3bc324c92ee3b61379e4f-d5ea7a0e)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/re [...]

2021-06-29 15:42 UTC, harshnat commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +Represents details for team description updated event message.
Done

2021-06-29 15:42 UTC, harshnat commented on api-reference/beta/resources/membersdeletedeventmessagedetail.md
> +Represents details for members added event message.
Done

2021-06-29 15:42 UTC, opbld31 commented
Docs Build status updates of commit _[a549adb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a549adbd958533110ef18fbb4e62ea8bd78cfd7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-3652ce77)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-3652ce77)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-3652ce77)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-3652ce77)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-3652ce77)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-3652ce77)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-3652ce77)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?v [...]

2021-06-29 15:42 UTC, harshnat commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +Represents details for a channel deleted event.
Done

2021-06-29 15:42 UTC, harshnat commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +description: "Represents details for a channel deleted event."
Done

2021-06-29 15:42 UTC, harshnat commented on api-reference/beta/resources/channeladdedeventmessagedetail.md
> +description: "Represents details for a channel added event."
Done

2021-06-29 15:43 UTC, harshnat commented on api-reference/beta/resources/eventmessagedetail.md
> +description: "Represents base type for event message detail."
Done

2021-06-29 15:44 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel, or a team, for example, members were a
Done

2021-06-29 15:46 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +---
(a) and (b) were present.
For (c) added base type in all derived types

2021-06-29 15:48 UTC, harshnat commented on api-reference/beta/resources/eventmessagedetail.md
> +
Updated

2021-06-29 15:48 UTC, opbld34 commented
Docs Build status updates of commit _[691a69e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/691a69e29658e76d1f10a42aef4af99cb5e0e592)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-1984f28f17c8df8965547c0f39bd37a4-8031358e)
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-8031358e)
[api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmemberroleupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-aaada5a4f1a8c3da39ae6c3e65462381-8031358e)
[api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersaddedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-c7d7aa05d4a0dfa0ecf60d8a12f7131d-8031358e)
[api-reference/beta/resources/membersdeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersdeletedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersdeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-0b6e7c60b1b42fa5bc11e02c14842471-8031358e)
[api-reference/beta/resources/membersjoinedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/membersjoinedeventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/membersjoinedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-96d56f62518354dfdcd1b22b652a57ca-8031358e)
[api-reference/beta/resources/memberslefteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/memberslefteventmessagedetail.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/memberslefteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) | [Details](#user-content-01c21000f9237bd7d2f615f77a2a0c96-8031358e)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?v [...]

2021-06-29 15:50 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/callrecordingeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/callstartedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/calltranscripteventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/channeladdedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/channelrenamedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:51 UTC, harshnat commented on api-reference/beta/resources/channelsetasfavoritebydefaulteventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/membersaddedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/membersdeletedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/membersjoinedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:52 UTC, harshnat commented on api-reference/beta/resources/memberslefteventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/teamjoiningdisabledeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/teamjoiningenabledeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:53 UTC, harshnat commented on api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:54 UTC, harshnat commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:54 UTC, harshnat commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:54 UTC, harshnat commented on api-reference/beta/resources/teamunarchivedeventmessagedetail.md
> +## Example response
Removed

2021-06-29 15:57 UTC, harshnat commented
> Also, after you create the afore-mentioned concept topic, please add a couple of links to that topic from each of the derived complex type topics. In each derived complex type topic, the two links are:
> 
> * A link to the section in the concept topics that specifies the corresponding example JSON for that type.
> * A link to the concept topic. Some lead-in sentence like "For more information about other types of events, see {concept topic}."

@angelgolfer-ms added links in all derived types

2021-06-29 16:00 UTC, harshnat commented
> Hi @harshnat , that's an interesting way your team decided to expose details about events that can happen to a team, channel, chat, or in the context of a meeting.
> So that we don't break the template and expectations of customers for what's in a resource topic and API topic (i.e., examples should go to an API topic and not the resource topic), I'd recommend you create a concept topic.
> 
> Note that the concept topic is not just to contain these example JSON blocks. I think customers will appreciate if the topic describes the following:
> (A) First describe the mechanism - for the scenarios/events (give a couple of examples), customers can use the applicable GET operations to get chatMessage resource(s). If chatMessage has the messageType indicating the message is about an event, then the eventDetail property would provide the details.
> 
> (B) Then list the supported events (listed in lines 27-39 of api.md file). It might be helpful to categorize them in some way that's easier to scan and tell whether the event applies to a team, channel, chat, or the context of a meeting.
> 
> * Include the applicable GET operations (lines 19-22).
> * Include the name of the applicable event message detail complex type (derived type). Link to the section for the corresponding type in (C).
>   It would be helpful to format this info in a user-friendly and scannable table rather than paragraphs or long bullet lists like a wall of text, so that customers would find this API capability intuitive.
> 
> (C) Then finally list each of the derived types, and provide the corresponding JSON example. (Each derived type and example JSON would be in its own sub-section so that you can from (B) to (C).)

@angelgolfer-ms Added concept topic under "Use the API" topic, please let me know if that's not the right place.
Requesting you to please review the content for this page.

2021-07-01 09:34 UTC, opbld33 commented
Docs Build status updates of commit _[8130f21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8130f215438363e3b58f30996292e26bb8567cf7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-06 19:59 UTC, JarbasHorst requested changes

2021-07-06 19:59 UTC, JarbasHorst commented on concepts/system-messages.md
> +title: "System messages using Microsoft Graph"
Make sure that the title field matches the H1. In this case, the H1 is more descriptive than the title provided. Hence, I recommend you to replace the title field value with "System messages in Microsoft Teams using Microsoft Graph".

2021-07-06 19:59 UTC, JarbasHorst commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +- For more information about other types of events, see [System Messages](/graph/system-messages)
Please, apply this globally.  For clarity, I recommend you to use the concept title in the hyperlink. Suggested revision:

- For more information about other types of events, see \[System messages in Microsoft Teams using Microsoft Graph\]\(/graph/system-messages\)

2021-07-06 19:59 UTC, JarbasHorst commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +description: "Represents details for call ended event message."
Please, apply this globally. For clarity and readability, please rephrase the description provided in the description field and the corresponding introductory sentence in all articles. Suggested revision for this article:

- Represents the details of an event message about call ended.

2021-07-06 19:59 UTC, JarbasHorst commented on api-reference/beta/resources/callrecordingeventmessagedetail.md
> +|callRecordingStatus|callRecordingStatus|Status of the call recording. Possible values are: `success`, `failure`, `initial`, `chunkFinished`.|
For consistency with your other article "callStartedEventMessageDetail", I suggest you adding unknownFutureValue to the list of possible values.

2021-07-06 19:59 UTC, JarbasHorst commented on api-reference/beta/resources/chatmessage.md
> +|messageType|string|The type of chat message. The possible values are: `message`, `systemEventMessage`.|
For consistency with your other article "callStartedEventMessageDetail", I suggest you adding unknownFutureValue to the list of possible values.

2021-07-07 13:53 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel, or a team, for example, members were a
Done

2021-07-07 13:53 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel, or a team, for example, members were a
Done

2021-07-07 13:53 UTC, opbld34 commented
Docs Build status updates of commit _[817bb96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/817bb96de9c4c99aa3c53ea78db814537237ad8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-07 13:54 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +- For more information about other types of events, see [System Messages](/graph/system-messages)
Done

2021-07-07 13:54 UTC, harshnat commented on api-reference/beta/resources/callrecordingeventmessagedetail.md
> +|callRecordingStatus|callRecordingStatus|Status of the call recording. Possible values are: `success`, `failure`, `initial`, `chunkFinished`.|
Done

2021-07-07 13:55 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +description: "Represents details for call ended event message."
Updated for all.

2021-07-07 13:55 UTC, harshnat commented on concepts/system-messages.md
> +title: "System messages using Microsoft Graph"
Updated

2021-07-07 13:55 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|messageType|string|The type of chat message. The possible values are: `message`, `systemEventMessage`.|
Added

2021-07-07 13:55 UTC, opbld33 commented
Docs Build status updates of commit _[b2e8111](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2e8111b9b12ea2b4af11b43f8220435a8acf3ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-07 22:15 UTC, JarbasHorst requested changes

2021-07-07 22:15 UTC, JarbasHorst commented on concepts/system-messages.md
> +description: "System messages in Microsoft Graph APIs."
The description field should generally be a one-sentence summary of what the article covers, and it shouldn't duplicate the title. This description potentially appears in search results. Suggested revision: "Learn how Microsoft Teams generates system messages for events using Microsoft Graph APIs."

2021-07-08 12:56 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +description: "Represents the details of an event message about call ended ."
Done

2021-07-08 12:56 UTC, harshnat commented on api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
> +Represents the details of an event message about teams app installed.
Updated

2021-07-08 12:56 UTC, harshnat commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +description: "Represents the details of an event message about teams app removed."
Updated

2021-07-08 12:56 UTC, harshnat commented on api-reference/beta/resources/teamsappremovedeventmessagedetail.md
> +Represents the details of an event message about teams app removed.
Updated

2021-07-08 12:57 UTC, harshnat commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +description: "Represents the details of an event message about teams app upgraded."
Updated

2021-07-08 12:57 UTC, opbld32 commented
Docs Build status updates of commit _[f5d5687](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5d56875d9530d37a2cca96ce147aaee3b9770f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-08 12:57 UTC, harshnat commented on api-reference/beta/resources/teamsappupgradedeventmessagedetail.md
> +Represents the details of an event message about teams app upgraded.
Updated

2021-07-08 12:57 UTC, harshnat commented on api-reference/beta/resources/teamsappinstalledeventmessagedetail.md
> +description: "Represents the details of an event message about teams app installed."
Updated

2021-07-08 12:57 UTC, harshnat commented on api-reference/beta/resources/channelsetasfavoritebydefaulteventmessagedetail.md
> +Represents the details of a channel for which 'favorite by default' flag has been set.
Updated

2021-07-08 12:57 UTC, harshnat commented on api-reference/beta/resources/channelsetasfavoritebydefaulteventmessagedetail.md
> +When the flag is set for a specific channel, it will be visible to all team members by default in the channel list under a team.
Updated

2021-07-08 12:57 UTC, harshnat commented on api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
> +When the flag is unset for a specific channel, it will no longer be visible to all team members by default in the channel list under a team.
Updated

2021-07-08 12:57 UTC, harshnat commented on api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
> +Represents the details of a channel for which 'favorite by default' flag has been unset.
Updated

2021-07-08 12:58 UTC, harshnat commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +This message is generated when a group or meeting chat topic has been updated.
Updated

2021-07-08 12:58 UTC, harshnat commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +This message is generated when the role of a member in a channel or a team has been updated.
Updated

2021-07-08 12:58 UTC, opbld31 commented
Docs Build status updates of commit _[db39847](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db3984756febcc07887823621264465c6d025368)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-08 12:58 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +This message is generated when a call has ended.
Updated

2021-07-08 12:58 UTC, harshnat commented on api-reference/beta/resources/callstartedeventmessagedetail.md
> +This message is generated when a call has started.
Updated

2021-07-08 12:59 UTC, harshnat commented on api-reference/beta/resources/callrecordingeventmessagedetail.md
> +This message is generated when a call recording is started.
Updated

2021-07-08 12:59 UTC, harshnat commented on concepts/system-messages.md
> +Microsoft Teams generates system messages for events such as members added to a chat, team name updated, channel description updated which enable the caller to have insights about events that happene
Updated

2021-07-08 12:59 UTC, harshnat commented on concepts/system-messages.md
> +Microsoft Teams generates system messages for events such as members added to a chat, team name updated, channel description updated which enable the caller to have insights about events that happene
Updated

2021-07-08 12:59 UTC, harshnat commented on concepts/system-messages.md
> +System messages are represented as [chatMessage](/graph/api/resources/chatMessage?view=graph-rest-beta&preserve-view=true) resource.
Updated

2021-07-08 12:59 UTC, harshnat commented on concepts/system-messages.md
> +description: "System messages in Microsoft Graph APIs."
Updated

2021-07-08 12:59 UTC, harshnat commented on concepts/system-messages.md
> +Below is the list of supported types with the example JSON response.
Updated

2021-07-08 21:38 UTC, JarbasHorst requested changes

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +description: "Represents the details of an event message about chat renamed."
For readability, I recommend you updating this phrase. Suggested revision:

-  ...event message about a renamed chat.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +Represents the details of an event message about chat renamed.
For readability, I recommend you updating this phrase. Suggested revision:

-  ...event message about a renamed chat.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about conversation member role updated."
For readability and clarity, I recommend you updating this phrase. Suggested revision:

-  ...event message about an updated role of a conversation member in a team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +Represents the details of an event message about conversation member role updated.
For readability and clarity, I recommend you updating this phrase. Suggested revision:

-  ...event message about an updated role of a conversation member in a team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/eventmessagedetail.md
> +This abstract type represents system event message details.
For readability and clarity, I recommend you updating this phrase. Suggested revision:

-  ...represents details of a system event message.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about meeting policy updated."
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an updated meeting policy.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +Represents the details of an event message about meeting policy updated.
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an updated meeting policy.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about tab updated."
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an updated tab.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +Represents the details of an event message about tab updated.
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an updated tab.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +description: "Represents the details of an event message about team archived."
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an archived team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +Represents the details of an event message about team archived.
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an archived team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +description: "Represents the details of an event message about team created."
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about a created team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +Represents the details of an event message about team created.
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about a created team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about team description updated."
For readability and clarity, I recommend you updating this phrase. Suggested revision:

-  ...message about an updated team description.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +Represents the details of an event message about team description updated.
For readability and clarity, I recommend you updating this phrase. Suggested revision:

-  ...message about an updated team description.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +description: "Represents the details of an event message about team renamed."
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about a renamed team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +Represents the details of an event message about team renamed.
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about a renamed team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamunarchivedeventmessagedetail.md
> +description: "Represents the details of an event message about team unarchived."
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an unarchived team.

2021-07-08 21:38 UTC, JarbasHorst commented on api-reference/beta/resources/teamunarchivedeventmessagedetail.md
> +Represents the details of an event message about team unarchived.
For readability, I recommend you updating this phrase. Suggested revision:

-  ...message about an unarchived team.

2021-07-08 21:38 UTC, JarbasHorst commented on concepts/system-messages.md
> +In this case, the `messageType` is set to `systemEventMessage` and the `eventDetail` property provides the event details.
For clarity, I recommend you adding the word property after \`messageType\`

2021-07-08 21:38 UTC, JarbasHorst commented on concepts/system-messages.md
> +### Supported change notification resource types
What do you mean by "change notification resource types"? Maybe it is enough to say: "Supported change notifications"

2021-07-08 21:53 UTC, JarbasHorst requested changes

2021-07-08 21:53 UTC, JarbasHorst commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel, or a team, for example, members were a
Property names should have bold formatting applied.

2021-07-08 21:53 UTC, JarbasHorst commented on concepts/system-messages.md
> +In this case, the `messageType` is set to `systemEventMessage` and the `eventDetail` property provides the event details.
Property names should have bold formatting applied.

2021-07-09 12:59 UTC, harshnat commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **eventDetail** property to [chatMessage](https://docs.microsoft.com/en-us/graph/api/resources/chatMessage?view=graph-rest-beta) resource.",
Updated

2021-07-09 12:59 UTC, harshnat commented on concepts/system-messages.md
> +> **Note:** System messages applicable to a team are posted in General channel.
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +- [Example response](/graph/system-messages/#1-call-ended)
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about channel description updated."
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md
> +Represents the details of an event message about channel description updated.
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +Represents the details of an event message about call ended.
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +description: "Represents the details of an event message about call ended."
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/channeladdedeventmessagedetail.md
> +description: "Represents the details of an event message about a channel added."
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/channeladdedeventmessagedetail.md
> +Represents the details of an event message about a channel added.
Updated

2021-07-09 13:00 UTC, harshnat commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +description: "Represents the details of an event message about a channel deleted."
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/channeldeletedeventmessagedetail.md
> +Represents the details of an event message about a channel deleted.
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/channelrenamedeventmessagedetail.md
> +description: "Represents the details of an event message about channel renamed."
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/channelrenamedeventmessagedetail.md
> +Represents the details of an event message about channel renamed.
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/channelsetasfavoritebydefaulteventmessagedetail.md
> +description: "Represents the details of an event message about channel set as favorite by default."
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/channelunsetasfavoritebydefaulteventmessagedetail.md
> +description: "Represents the details of an event message about channel unset as favorite by default."
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel, or a team, for example, members were a
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +description: "Represents the details of an event message about chat renamed."
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +Represents the details of an event message about chat renamed.
Updated

2021-07-09 13:01 UTC, harshnat commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +Represents the details of an event message about conversation member role updated.
Updated

2021-07-09 13:02 UTC, opbld34 commented
Docs Build status updates of commit _[eda76f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eda76f475ede88e8726ac794b5678ad30eea8110)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-09 13:02 UTC, harshnat commented on api-reference/beta/resources/conversationmemberroleupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about conversation member role updated."
Updated

2021-07-09 13:02 UTC, harshnat commented on api-reference/beta/resources/eventmessagedetail.md
> +This abstract type represents system event message details.
Updated

2021-07-09 13:02 UTC, harshnat commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about meeting policy updated."
Updated

2021-07-09 13:02 UTC, harshnat commented on api-reference/beta/resources/meetingpolicyupdatedeventmessagedetail.md
> +Represents the details of an event message about meeting policy updated.
Updated

2021-07-09 13:02 UTC, harshnat commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +Represents the details of an event message about tab updated.
Updated

2021-07-09 13:02 UTC, harshnat commented on api-reference/beta/resources/tabupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about tab updated."
Updated

2021-07-09 13:02 UTC, harshnat commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +description: "Represents the details of an event message about team archived."
Updated

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +description: "Represents the details of an event message about team created."
Updated

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamarchivedeventmessagedetail.md
> +Represents the details of an event message about team archived.
Updated

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamcreatedeventmessagedetail.md
> +Represents the details of an event message about team created.
Updated

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +Represents the details of an event message about team description updated.
Updated

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +description: "Represents the details of an event message about team renamed."
Updated

2021-07-09 13:03 UTC, opbld31 commented
Docs Build status updates of commit _[fc119b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc119b65a9d687205d4005958e3a818a1b019808)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamunarchivedeventmessagedetail.md
> +description: "Represents the details of an event message about team unarchived."
Updated

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamrenamedeventmessagedetail.md
> +Represents the details of an event message about team renamed.
Updated

2021-07-09 13:03 UTC, harshnat commented on concepts/system-messages.md
> +In this case, the `messageType` is set to `systemEventMessage` and the `eventDetail` property provides the event details.
Updated

2021-07-09 13:03 UTC, harshnat commented on api-reference/beta/resources/teamunarchivedeventmessagedetail.md
> +Represents the details of an event message about team unarchived.
Updated

2021-07-09 13:04 UTC, harshnat commented on concepts/system-messages.md
> +### Supported change notification resource types
Updated

2021-07-09 13:04 UTC, harshnat commented on concepts/system-messages.md
> +In this case, the `messageType` is set to `systemEventMessage` and the `eventDetail` property provides the event details.
Updated

2021-07-09 13:04 UTC, harshnat commented on api-reference/beta/resources/chatmessage.md
> +|eventDetail|[eventMessageDetail](../resources/eventmessagedetail.md)|Read-only.  If present, represents details of an event that happened in a chat, a channel, or a team, for example, members were a
Updated

2021-07-09 13:04 UTC, harshnat commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +description: "Represents the details of an event message about team description updated."
Updated

2021-07-09 20:03 UTC, JarbasHorst requested changes

2021-07-12 12:55 UTC, opbld31 commented
Docs Build status updates of commit _[5460bd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5460bd24dd9c00b6f61b24af048cc1de13a0a965)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-12 12:55 UTC, harshnat commented on api-reference/beta/resources/teamjoiningenabledeventmessagedetail.md
> +- [Example response for an event message about team joining disabled](/graph/system-messages/#23-team-joining-enabled)
Updated

2021-07-12 12:55 UTC, harshnat commented on api-reference/beta/resources/teamdescriptionupdatedeventmessagedetail.md
> +- [Example response for an event message an updated team description](/graph/system-messages/#21-team-description-updated)
Updated

2021-07-12 12:55 UTC, harshnat commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +|chatDisplayName|String|Updated name of the chat.|
Updated

2021-07-12 12:55 UTC, harshnat commented on api-reference/beta/resources/chatrenamedeventmessagedetail.md
> +This message is generated when a group or meeting chat topic is updated.
Updated

2021-07-12 12:56 UTC, opbld31 commented
Docs Build status updates of commit _[e5c1280](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5c12808603c53b3be0d4cb0a4eeb5eb5135e69a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-12 19:49 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-07-13 23:36 UTC, opbld32 commented
Docs Build status updates of commit _[3779647](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3779647352fbd1cd15b3877e4464760865092011)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f6e77d81)

<a id="f6e77d81"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132335058269-13085%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T09%3A54%3A23Z&ske=2021-07-20T09%3A59%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T23%3A31%3A37Z&se=2021-08-13T23%3A36%3A37Z&sr=b&sp=r&sig=ezhSYNYlD7zU1nSXoTge%2B%2BrpU7tIiqCDFL3da77MXHg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 23:39 UTC, Lauragra commented on api-reference/beta/resources/callendedeventmessagedetail.md
> +- For more information about other types of events, see [System messages in Microsoft Teams using Microsoft Graph](/graph/system-messages)
Global: This cross-reference should end with a period since it's a complete sentence. Let's shorten the link text to just say "System messages"; the other keywords are there for SEO but as long as the link text aligns with the title, it can be shorter, for readability.

2021-07-14 00:13 UTC, opbld31 commented
Docs Build status updates of commit _[1e69dca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e69dcafaa38f2be8a4fe1580a7f67f1d53e4d61)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-03383395)

<a id="03383395"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140011464883-13085%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A15Z&ske=2021-07-20T08%3A20%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T00%3A08%3A24Z&se=2021-08-14T00%3A13%3A24Z&sr=b&sp=r&sig=yk6ENYoLUHJ8On%2F7QozjiY3oe9buH%2BHlz25Iakl%2Bkc4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 00:13 UTC, Lauragra commented on concepts/system-messages.md
> +### 1. Call ended
Global: Let's not number these examples because numbering generally implies sequential steps. I realize that if we remove the numbers we also need to update the deep links in the resource topics; however, I think the numbering doesn't add meaning and can potentially confuse readers.

2021-07-14 00:13 UTC, opbld30 commented
Docs Build status updates of commit _[1e69dca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e69dcafaa38f2be8a4fe1580a7f67f1d53e4d61)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6ee09af7)

<a id="6ee09af7"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140011571034-13085%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A58%3A37Z&ske=2021-07-20T08%3A03%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T00%3A08%3A51Z&se=2021-08-14T00%3A13%3A51Z&sr=b&sp=r&sig=bdtmvWwT2TQC0fcZZ2lxM23%2FGzzHRIu8qKI27%2FNSmBk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 00:14 UTC, Lauragra commented on concepts/system-messages.md
> +# System messages in Microsoft Teams using Microsoft Graph
Would a better title for this topic be "Get system messages for Microsoft Teams using Microsoft Graph APIs"?

2021-07-14 00:18 UTC, Lauragra commented on api-reference/beta/toc.yml
> +    - name: System messages in Microsoft Teams
Let's shorten the TOC title here to "System messages". Also, we should be surfacing this concept topic in the concept TOC under Learn/Teamwork, where we surface other Teams-related concept topics. The "Use the API" section is for more general, rather than workload-specific, content.

2021-07-14 00:20 UTC, Lauragra commented on concepts/toc.yml
> +          - name: System messages in Microsoft Teams
Please shorten to "System messages" and move to appear under Learn/Teamwork.

2021-07-14 00:23 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "ComplexType",
Global: ComplexType is not on the list of approved values for ApiChange. Please change this to "Resource".

2021-07-14 12:45 UTC, opbld33 commented
Docs Build status updates of commit _[a39162f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a39162fbdd3edfda73c139b481d0e164faa48725)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3394fbc8)

<a id="3394fbc8"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107141245143482-13085%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A15Z&ske=2021-07-20T08%3A20%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T12%3A40%3A34Z&se=2021-08-14T12%3A45%3A34Z&sr=b&sp=r&sig=tYs627HTVe2ZWGpJ%2Bzcd1sU%2B%2FR%2FFYgcPjZC%2BPzeYjBM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 12:50 UTC, opbld32 commented
Docs Build status updates of commit _[54d502a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54d502af1281ddddf1d03569c1bd4bdf6a089c21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-14 13:10 UTC, harshnat commented on concepts/system-messages.md
> +### 1. Call ended
Removed numbers

2021-07-14 13:10 UTC, harshnat commented on concepts/system-messages.md
> +# System messages in Microsoft Teams using Microsoft Graph
Updated

2021-07-14 13:12 UTC, opbld33 commented
Docs Build status updates of commit _[e49138a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e49138ab7ccb435a80ec528af310d89236a0b920)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-14 13:12 UTC, harshnat commented on api-reference/beta/toc.yml
> +    - name: System messages in Microsoft Teams
Updated title.
Should this be removed from this file and only added in concept TOC ?
If not, which node should this be under, as Learn/Teamwork is not present for this file ?

2021-07-14 13:12 UTC, harshnat commented on concepts/toc.yml
> +          - name: System messages in Microsoft Teams
Updated

2021-07-14 13:12 UTC, harshnat commented on changelog/Microsoft.Teams.Core.json
> +          "ApiChange": "ComplexType",
Updated

2021-07-16 15:07 UTC, opbld30 commented
Docs Build status updates of commit _[f619490](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f619490e5b17449471bb28c5c3f357045afe4108)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-17 01:51 UTC, opbld32 commented
Docs Build status updates of commit _[6bf6e5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bf6e5c35384f0911e8432960f5b51e2060cf324)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-17 01:53 UTC, opbld31 commented
Docs Build status updates of commit _[6bf6e5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bf6e5c35384f0911e8432960f5b51e2060cf324)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/channel-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chat-post-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-list-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post-replies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callendedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callendedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callendedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callparticipantinfo?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callrecordingeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callrecordingeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecordingeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/callstartedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/callstartedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callstartedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/calltranscripteventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/calltranscripteventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calltranscripteventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeladdedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeladdedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeladdedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldeletedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldeletedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldeletedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channeldescriptionupdatedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channeldescriptionupdatedeventmessagedetail?view=graph-rest-beta&branch=pr-en-us-13085) (graph-rest-beta) |
[api-reference/beta/resources/channelrenamedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-05-06-harshna-control-messages/api-reference/beta/resources/channelrenamedeventmessagedetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cha [...]

2021-07-20 00:22 UTC, merged