Add new Microsoft 365 usage report: Microsoft 365 Browse rUsage
microsoftgraph/microsoft-graph-docs pull request #13089
Opened 2021-06-11 10:38 UTC by airicaruss

2021-06-11 10:41 UTC, opbld34 commented
Docs Build status updates of commit _[891bda6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/891bda6e99dde76d3ea2d0605e45764e2b8cfec0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-browserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserDistributionUserCounts.md) | :x:Error | | [Details](#user-content-1c3240bd6a79dd4c5673430e14934118-f22a2b6c)
[api-reference/beta/api/reportroot-browserUsageUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserUsageUserCounts.md) | :x:Error | | [Details](#user-content-c8fb393da2e18a28e854277663081ff0-f22a2b6c)
[api-reference/beta/api/reportroot-browseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browseruserdetail.md) | :x:Error | | [Details](#user-content-6e7535a9fb6197e87a7bb1077f643848-f22a2b6c)
[api-reference/beta/resources/microsoft-365-browser-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-browser-usage-report.md) | :warning:Warning | | [Details](#user-content-801a9a4e6d736bcc37f0f253abfa1ca1-f22a2b6c)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-0817dce4456c16725d5333633847d38f-f22a2b6c)
[api-reference/beta/resources/microsoft-365-apps-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-apps-usage-report.md) | :warning:Warning | | [Details](#user-content-7e2031e9a2ea785cbac2d87c257806d7-f22a2b6c)

<a id="1c3240bd6a79dd4c5673430e14934118-f22a2b6c"></a>
### [api-reference/beta/api/reportroot-browserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserDistributionUserCounts.md)
 - **Line 106, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md'.`````
 - **Line 110, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-browserdistributionuserCounts-csv-javascript-snippets.md'.`````
 - **Line 114, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-browserdistributionusercounts-csv-objc-snippets.md'.`````
 - **Line 118, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md'.`````
 - **Line 172, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md'.`````
 - **Line 176, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-browserdistributionusercounts-json-javascript-snippets.md'.`````
 - **Line 180, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-browserdistributionusercounts-json-objc-snippets.md'.`````
 - **Line 184, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md'.`````

<a id="c8fb393da2e18a28e854277663081ff0-f22a2b6c"></a>
### [api-reference/beta/api/reportroot-browserUsageUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserUsageUserCounts.md)
 - **Line 107, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md'.`````
 - **Line 111, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-browserusageusercounts-csv-javascript-snippets.md'.`````
 - **Line 115, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-browserusageusercounts-csv-objc-snippets.md'.`````
 - **Line 119, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md'.`````
 - **Line 173, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md'.`````
 - **Line 177, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-browserusageusercounts-json-javascript-snippets.md'.`````
 - **Line 181, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-browserusageusercounts-json-objc-snippets.md'.`````
 - **Line 185, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md'.`````

<a id="6e7535a9fb6197e87a7bb1077f643848-f22a2b6c"></a>
### [api-reference/beta/api/reportroot-browseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browseruserdetail.md)
 - **Line 110, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-browseruserdetail-csharp-snippets.md'.`````
 - **Line 114, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-browseruserdetail-javascript-snippets.md'.`````
 - **Line 118, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-browseruserdetail-objc-snippets.md'.`````
 - **Line 122, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-browseruserdetail-java-snippets.md'.`````
 - **Line 177, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/reportroot-browseruserdetail-csharp-snippets.md'.`````
 - **Line 181, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/reportroot-browseruserdetail-javascript-snippets.md'.`````
 - **Line 185, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/reportroot-browseruserdetail-objc-snippets.md'.`````
 - **Line 189, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/reportroot-browseruserdetail-java-snippets.md'.`````

<a id="801a9a4e6d736bcc37f0f253abfa1ca1-f22a2b6c"></a>
### [api-reference/beta/resources/microsoft-365-browser-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-browser-usage-report.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Microsoft 365 Apps usage reports' is duplicated with other articles: 'beta/resources/microsoft-365-apps-usage-report.md(10,1), beta/resources/microsoft-365-browser-usage-report.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0817dce4456c16725d5333633847d38f-f22a2b6c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microso [...]

2021-06-16 06:33 UTC, opbld33 commented
Docs Build status updates of commit _[19a5472](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19a547220c8c3ef3ed5a0c31192f1b12e679b835)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7ad1a353)
[api-reference/beta/api/reportroot-browserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserDistributionUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browserUsageUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserUsageUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercou [...]

2021-06-16 07:27 UTC, opbld33 commented
Docs Build status updates of commit _[3b47ff7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b47ff76dbdf21556314cf48829ff851930541b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-browserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserDistributionUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browserUsageUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserUsageUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-json-javascript-snippets [...]

2021-06-16 07:40 UTC, opbld32 commented
Docs Build status updates of commit _[0e696da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e696da0fb5927b06c1b5dca9041cce1519ff0bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-browserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browserusageusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-json-javascript-snippets [...]

2021-06-16 07:59 UTC, opbld31 commented
Docs Build status updates of commit _[bab14f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bab14f7e3444cb440d2a892fbe01f620caa912bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-browserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browserusageusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browserusageusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-browseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-browseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browserusageusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-browseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browserusageusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserusageusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-browseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-browserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-browserdistributionusercounts-json-javascript-snippets [...]

2021-08-24 04:45 UTC, airicaruss commented
We are still working on the review for graph api with testing effort.

2021-11-04 05:26 UTC, airicaruss commented
We still need this PR.

2021-12-30 07:40 UTC, opbld32 commented
Docs Build status updates of commit _[4b4fd21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b4fd21d6926081bfd04bd143060e091209e3e0b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7602504f)

<a id="7602504f"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112300738305578-13089%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T07%3A40%3A27Z&sr=b&sp=r&sig=nQ5X9nG2wEecTmcH6%2FQOdZEX%2F6IEZ0SO7oDpDZvSLew%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 08:58 UTC, opbld30 commented
Docs Build status updates of commit _[16f5cb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16f5cb53ac4dfb9067848f891d7ed3019f836dfe)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d066b0ae)

<a id="d066b0ae"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112300857579929-13089%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-30T08%3A58%3A28Z&sr=b&sp=r&sig=uqNya5Ea%2BwNqWE%2BgtWxUsCNrP3S5PXvmXfF8EHJIlxQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-30 09:10 UTC, opbld32 commented
Docs Build status updates of commit _[7e3e66f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e3e66faf29307be126c3202cc754481176ff19b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5999393f)
[]() | :warning:Warning | | [Details](#user-content-5999393f)
[api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserDetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets [...]

2021-12-30 09:18 UTC, opbld33 commented
Docs Build status updates of commit _[60fcb11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60fcb1138d814b2fa35a63c35091c0be0844ffaa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-687b58ca)
[api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserDetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2021-12-30 09:21 UTC, opbld30 commented
Docs Build status updates of commit _[c67bf7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c67bf7b8fe6dd2cd329daa9396fc2a55b872692b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-47fc4a49)
[api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserDetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2021-12-30 09:45 UTC, opbld31 commented
Docs Build status updates of commit _[68e566c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68e566ca2d3d5c5549eb981a24835e098f9dcc69)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5a8bbc94)
[api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserDistributionUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserDetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded [...]

2021-12-30 09:47 UTC, opbld34 commented
Docs Build status updates of commit _[82d5a61](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82d5a616af3850b3bb35addbc6f7e0f93eb999a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0aa0a015)
[api-reference/beta/api/reportroot-getBrowserUserCounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserCounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getBrowserUserDetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getBrowserUserDetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [...]

2021-12-30 09:49 UTC, opbld31 commented
Docs Build status updates of commit _[21bf202](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21bf20277940e14682456ae719110f98a754f249)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-5482147a)
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.doc [...]

2021-12-30 10:05 UTC, opbld32 commented
Docs Build status updates of commit _[b81a952](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b81a952ef84bfd331eda52e6ca58ef0e978bc9ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java [...]

2021-12-30 10:15 UTC, opbld33 commented
Docs Build status updates of commit _[ccfa7ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ccfa7ef2d9bc309aa6cd458b2ddbe97c43dacf46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java [...]

2021-12-30 10:21 UTC, opbld30 commented
Docs Build status updates of commit _[1ea5117](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ea5117d7f1ad1cdc07ab82b7e06a9c15a6b27ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java [...]

2022-01-04 07:48 UTC, Zhiliqiao888 commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +description: "Get the number of users by browser over the selected period. The browser types are Edge, Edge Legacy, Internet Explorer."
by browser -> per browser

2022-01-04 07:49 UTC, Zhiliqiao888 commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +Get the number of users by browser over the selected period. The browser types are Edge, Edge Legacy, Internet Explorer.
Same as above

2022-01-04 07:52 UTC, Zhiliqiao888 commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +Report Refresh Date,Report Period,Edge, Edge Legacy, Internet Explorer
whitespace is required after each comma

2022-01-04 07:53 UTC, Zhiliqiao888 commented on api-reference/beta/api/reportroot-getbrowserusercounts.md
> +description: "Get a report that provides the trend in the number of active users for each browser – Edge, Edge Legacy, Internet Explorer - in your organization."
in the number -> with the number

2022-01-04 07:55 UTC, Zhiliqiao888 commented on api-reference/beta/api/reportroot-getbrowserusercounts.md
> +Get a report that provides the trend in the number of active users for each browser – Edge, Edge Legacy, Internet Explorer - in your organization.
same as above

2022-01-04 08:01 UTC, Zhiliqiao888 requested changes
See single comments.

2022-02-25 07:08 UTC, opbld30 commented
Docs Build status updates of commit _[88b98a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88b98a0df4bbe38ca1482b2968efd619d18cc3c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java [...]

2022-02-25 07:21 UTC, opbld34 commented
Docs Build status updates of commit _[ab3b3a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab3b3a06a5c83127de019f89f483673c5fdb6255)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java [...]

2022-02-25 07:27 UTC, opbld30 commented
Docs Build status updates of commit _[9b2ef47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b2ef476e1e3f39006df8a14d347ae3823b144a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java [...]

2022-02-25 07:46 UTC, opbld30 commented
Docs Build status updates of commit _[4c0c6d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c0c6d58cbc1ba13594569120d19fe1174a98250)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserdistributionusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowserusercounts-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-csv-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/csharp/reportroot-getbrowseruserdetail-json-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserdistributionusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowserusercounts-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-csv-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java/reportroot-getbrowseruserdetail-json-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-csv-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/reportroot-getbrowserdistributionusercounts-json-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/includes/snippets/java [...]

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowserusercounts.md
> +description: "Get a report that provides the trend with the number of active users for each browser – Edge, Edge Legacy, Internet Explorer - in your organization."
For clarity and consistency, I recommend you to rephrase this description. Suggested revision for lines 3 and 16:

- Get a report that provides the trend in usage for the number of active users using Microsoft Edge, Microsoft Edge Legacy, and Internet Explorer when used to access the Microsoft 365 services over a selected period.

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +> **Note:** You need to set either `period` in the URL.
This sentence doesn't make sense because it doesn't include a second choice. If a second choice is available, please add it to the table above and update this sentence; otherwise, please remove this sentence.

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +| period    | string | Specifies the length of time over which the report is aggregated. The supported values for {period_value} are: `D7`, `D30`, `D90`, and `D180`. These values follow the format D*
Considering the current circumstances, "period" is a required parameter. In this case, please add "Required." at the end of this sentence => ...the report is aggregated. Required.

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +If successful, this method returns a `200 OK` response code and a [report](../resources/intune-shared-report.md) object in the response body. Report data is contained in the **content** property of t
The information provided in the second sentence is related to the request URL. In this case, I recommend you to remove this second sentence ("Report data is...") and to include the need for the "content" property in the HTTP Request section.

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +GET /reports/getBrowserUserDetail(period='{period_value}')
Currently, this API requires the **content** property to be part of the request URL. In this case, I think that the HTTP request URL should be updated to always include the "content" property.

=> /reports/getBrowserUserDetail(period='{period_value}')/content

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +description: "Get a report that provides the details about which browser users have used."
For clarity and consistency, I recommend you to rephrase this description. Suggested revision for lines 3 and 16:

- Get a report that provides the browsers (Microsoft Edge, Microsoft Edge Legacy, and Internet Explorer) used by users when they access the Microsoft 365 services over a selected period.

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +GET https://graph.microsoft.com/beta/reports/getBrowserUserDetail(period='D7')?$format=text/csv
The **content** property should also be part of this URL.

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +If successful, requesting the **content** property returns a `302 Found` response that redirects to a preauthenticated download URL for the report. That URL can be found in the `Location` header in t
If **content** will be part of the HTTP request URL, you don't need to mention it here explicitly. In this case, I recommend you to replace "requesting the **content** property" with "this method"

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +- User Id
According to line 154 (Report Refresh Date,User Principal Name, Report Period, Edge, Edge Legacy, Internet Explorer) **User Id** isn't part of the response. Also, according to that line, **User Principal Name** and **Report Period** are valid headers. Please, update this list to include the supported headers.

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +If successful, requesting the **content** property returns a `200 OK` response code and a JSON object in response body.
If **content** will be part of the HTTP request URL, you don't need to mention it here explicitly. In this case, I recommend you to replace "requesting the **content** property" with "this method"

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +The following is an example of the request to get the **content** property.
If **content** will be part of the HTTP request URL, you don't need to mention it here explicitly. In this case, I recommend you to replace "the request to get the **content** property." with "a request.".

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +The following is an example of the request to get the **content** property.
If **content** will be part of the HTTP request URL, you don't need to mention it here explicitly. In this case, I recommend you to replace "the request to get the **content** property." with "a request.".

2022-03-01 22:45 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +  "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getBrowserUserDetail(period='D7')?$format=application/json&$skiptoken=D07uj",
Should the response also include "content" as part of the nextLink URL?

2022-03-01 22:48 UTC, JarbasHorst commented
Hello @airicaruss, I reviewed your PR and left some comments. Please, take a look when you will have time. 

Also, please include the Microsoft 365 browser usage to the **Cloud deployments** table [here](https://docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta).

2022-03-02 20:36 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +description: "Use the Microsoft 365 Browser usage reports to get insights into the usage of Browsers in your organization."
For clarity, please add "(Microsoft Edge, Microsoft Edge Legacy, and Internet Explorer)" after "browsers":

- ...into the usage of browsers (Microsoft Edge, Microsoft Edge Legacy, and Internet Explorer) in your...

2022-03-02 20:36 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +Use the Microsoft Browser usage reports to get insights into the Browser usage in your organization.
For consistency, please replace "Browser usage" with "usage of Browsers". Also, please add "365" after "Microsoft". After all modifications, the description should look like:

- Use the Microsoft 365 browser usage reports to get insights into the usage of browsers (Microsoft Edge, Microsoft Edge Legacy, and Internet Explorer) in your organization.

2022-03-02 20:36 UTC, JarbasHorst commented on changelog/Microsoft.O365Reporting.json
> +          "ApiChange": "method",
For consistency, please capitalize "method" => "ApiChange": "Method"

Please, apply this change also to lines 1311 and 1319.

2022-03-17 11:29 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +If successful, return a `200 OK` response code and a JSON object in response body.
There is an example under this section. Should I move the example here?

2022-03-17 11:35 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +GET /reports/getBrowserUserDetail(period='{period_value}')
We won't have content wrapper anymore. Removed the content from the doc.

2022-03-17 11:39 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +If successful, this method returns a `200 OK` response code and a [report](../resources/intune-shared-report.md) object in the response body. Report data is contained in the **content** property of t
We don't have Content wrapper anymore. Removed.

2022-03-17 11:44 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +- User Id
Fixed. The method will return 'User Principal Name' instead of UserId

2022-03-17 11:44 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +If successful, requesting the **content** property returns a `200 OK` response code and a JSON object in response body.
No 'content' wrapper anymore. Removed.

2022-03-17 11:44 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +The following is an example of the request to get the **content** property.
No 'content' wrapper anymore. Removed.

2022-03-17 11:44 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +GET https://graph.microsoft.com/beta/reports/getBrowserUserDetail(period='D7')?$format=text/csv
No 'content' wrapper anymore. Removed.

2022-03-17 11:45 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +The following is an example of the request to get the **content** property.
No 'content' wrapper anymore. Removed.

2022-03-17 11:45 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +  "@odata.nextLink": "https://graph.microsoft.com/beta/reports/getBrowserUserDetail(period='D7')?$format=application/json&$skiptoken=D07uj",
No 'content' wrapper anymore. Removed.

2022-03-17 12:03 UTC, airicaruss commented on changelog/Microsoft.O365Reporting.json
> +          "ApiChange": "method",
Fixed

2022-03-17 12:03 UTC, airicaruss commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +Use the Microsoft Browser usage reports to get insights into the Browser usage in your organization.
Fixed

2022-03-17 12:03 UTC, airicaruss commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +description: "Use the Microsoft 365 Browser usage reports to get insights into the usage of Browsers in your organization."
Fixed

2022-03-17 12:03 UTC, airicaruss commented on api-reference/beta/toc.yml
> +        - name: Microsoft 365 Browser usage
Fixed

2022-03-17 12:04 UTC, airicaruss commented on api-reference/beta/toc.yml
> +          - name: Get user counts distribution
Fixed

2022-03-17 12:04 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +# [HTTP](#tab/http)
Fixed

2022-03-17 12:04 UTC, airicaruss commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +title: "Microsoft 365 Browser usage reports"
Fixed

2022-03-17 12:04 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +description: "Get the number of users per browser over the selected period. The browser types are Edge, Edge Legacy, Internet Explorer."
Fixed

2022-03-17 12:04 UTC, opbld32 commented
Docs Build status updates of commit _[00b6eb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00b6eb6ddbf2323723427c798412363e968550c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/microsoft-365-browser-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-browser-usage-report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[changelog/Microsoft.O365Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203171202159465-13089%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T12%3A04%3A23Z&sr=b&sp=r&sig=3AKqCyQzcLM7Lv%2BLIc%2FXg%2FvrLT1SkSZnKU1wjFHW0jw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 08:37 UTC, Zhiliqiao888 approved these changes
Approved

2022-03-18 21:43 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +> **Note:** For delegated permissions to allow apps to read service usage reports on behalf of a user, the tenant administrator must have assigned the user the appropriate Azure Azure Active Director
Please, remove the second appearance of Azure.

2022-03-18 21:43 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowserusercounts.md
> +> **Note:** For delegated permissions to allow apps to read service usage reports on behalf of a user, the tenant administrator must have assigned the user the appropriate Azure Azure Active Director
Please, remove the second appearance of Azure.

2022-03-18 21:43 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +| [Get browser disctribution counts](../api//reportroot-getbrowserdistributionusercounts.md) | Edm.Stream          | Stream | et the number of users by browser over the selected period. |
Please, replace "et" with "Get".

2022-03-18 21:43 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +| [Get browser detail](../api/reportroot-getbrowseruserdetail.md ) | Stream          | Edm.Stream | Get the detailed browser useage per user.  |
Please, replace "useage" with "usage".

2022-03-18 21:43 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +| [Get browser user counts](../api/reportroot-getbrowserusercounts.md ) | Stream          | Edm.Stream |Get the trend in the number of active users for each browser. |
1) For consistency and clarity, please replace all "Edm.Stream" with "Stream". Please, apply this change to all rows in this table.

2) For consistency, please name the functions according to the names used in the TOC, for example, "Get browser user counts" should be "Get user counts".

3) For consistency, please organize the items in this table in the same order as the entries in the TOC, so first Get user detail, and so on.

2022-03-18 21:43 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +If successful, return a `200 OK` response code and a JSON object in response body.
No need to move the example here. Instead of just using "JSON", I was wondering if you want/can share the specific response object here. For example, https://docs.microsoft.com/en-us/graph/api/resources/office365activeuserdetail?view=graph-rest-beta.

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +
For consistency, please include here the following note:

```
> **Note:** For details about different report views and names, see [Microsoft 365 Reports in the admin center - Microsoft browser usage](/microsoft-365/admin/activity-reports/browser-usage-report).
```

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +title: "Microsoft 365 browser usage reports"
Also, please include the Microsoft 365 browser usage in the **Cloud deployments** table [here](https://docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta). Please, respect the alphabetical order of that table, when adding a new entry.

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +
For consistency, please add the following boilerplate here:

- The following is an example of a request.

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +
GLOBAL: Please, apply this change to all #### Request sections of all API topics.

Please, add back to the request section the HTTP example. For example:

```

<!-- {
  "blockType": "ignored",
  "name": "??????"
}-->

```http
GET https://graph.microsoft.com/beta/reports/...
```

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +> **Note:** For delegated permissions to allow apps to read service usage reports on behalf of a user, the tenant administrator must have assigned the user the appropriate Azure Azure Active Director
Please, remove the second appearance of Azure.

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowserusercounts.md
> +> **Note:** For delegated permissions to allow apps to read service usage reports on behalf of a user, the tenant administrator must have assigned the user the appropriate Azure Azure Active Director
Please, remove the second appearance of Azure.

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +- User Principal Name
Should **Report Period** also be added to this list after "User Principal Name". It is listed in line 117.

2022-03-18 22:28 UTC, JarbasHorst commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +         "userPrincipalName": "admin@contoso.com",
For consistency, please use approved fictitious names (display name, email, and domain): https://microsoft.sharepoint.com/sites/CELAWeb-Copyrights-Trademarks-And-Patents/SitePages/trademarks-fictitious-names.aspx.

2022-03-18 22:30 UTC, JarbasHorst commented
Hi @airicaruss, thanks for addressing my previous comments. I left additional ones. Please, take a look when you will have time.

2022-03-18 22:32 UTC, JarbasHorst commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +| [Get browser user counts](../api/reportroot-getbrowserusercounts.md ) | Stream          | Edm.Stream |Get the trend in the number of active users for each browser. |
1) For consistency and clarity, please replace all "Edm.Stream" with "Stream". Please, apply this change to all rows in this table.

2) For consistency, please name the functions according to the names used in the TOC, for example, "Get browser user counts" should be "Get user counts".

3) For consistency, please organize the items in this table in the same order as the entries in the TOC, so first Get user detail, and so on.

2022-03-30 09:48 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +- User Principal Name
Report Period exists in line 117

2022-03-30 09:54 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +         "userPrincipalName": "admin@contoso.com",
All M365 Usage report using 'userPrincipalName' as property name. For consistency, we should keep this naming convention.

2022-03-30 10:21 UTC, opbld30 commented
Docs Build status updates of commit _[761d74c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/761d74cba9c423df93ee184337b53a55c9378a25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/microsoft-365-browser-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-browser-usage-report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[changelog/Microsoft.O365Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301018134961-13089%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T10%3A21%3A19Z&sr=b&sp=r&sig=RkSkQNee9EFV7plac%2BkCcwQago7H%2FvnzhwRUhc96P9A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 10:29 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md
> +
Fixed

2022-03-30 10:29 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +
Added

2022-03-30 10:29 UTC, airicaruss commented on api-reference/beta/api/reportroot-getbrowseruserdetail.md
> +
Added

2022-03-30 10:29 UTC, airicaruss commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +title: "Microsoft 365 browser usage reports"
Added

2022-03-30 10:29 UTC, airicaruss commented on api-reference/beta/resources/microsoft-365-browser-usage-report.md
> +
Added

2022-03-30 10:31 UTC, opbld30 commented
Docs Build status updates of commit _[037c397](https://github.com/microsoftgraph/microsoft-graph-docs/commits/037c397c3601dc007788af84ecfa16a0e881a8a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/microsoft-365-browser-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-browser-usage-report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[changelog/Microsoft.O365Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203301028187847-13089%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T10%3A31%3A17Z&sr=b&sp=r&sig=4BdfpSXJFvSdIX0N98l9ounZf8eFP%2BuZQy4YhUtvCOw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 20:13 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review. Please, merge PR [16358](https://github.com/microsoftgraph/microsoft-graph-docs/pull/16358) into this branch to include my final edits.

2022-03-30 22:26 UTC, opbld30 commented
Docs Build status updates of commit _[66e5d08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66e5d081368faba676a66cc7dd1fee71bcc85ce5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/microsoft-365-browser-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-browser-usage-report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[changelog/Microsoft.O365Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203302224409083-13089%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T22%3A26%3A38Z&sr=b&sp=r&sig=QuU52vgomVNcC6S33QyiXm%2B3T0Z711vVdjPcsM8NlcE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 23:45 UTC, opbld34 commented
Docs Build status updates of commit _[bba2054](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bba2054ab99ac8247f3d78fb282b89e2acf4a49f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserdistributionusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowserusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowserusercounts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/api/reportroot-getbrowseruserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/api/reportroot-getbrowseruserdetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowseruserdetail?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/microsoft-365-browser-usage-report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/microsoft-365-browser-usage-report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/microsoft-365-browser-usage-report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/resources/report.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/resources/report.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/report?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-getbrowserdistributionusercounts?view=graph-rest-beta&branch=pr-en-us-13089) (graph-rest-beta) |
[changelog/Microsoft.O365Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/haoyli/AddBrowserReport/changelog/Microsoft.O365Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202203302343511253-13089%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T23%3A45%3A38Z&sr=b&sp=r&sig=V09LXqVsoiqhGx7i16KVSoNQ9xKE0FkBm1c%2FYBvFDHE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 03:11 UTC, merged