Added Examples for calling site collection termstore APIs
microsoftgraph/microsoft-graph-docs pull request #13091
Opened 2021-06-11 13:29 UTC by vishriv

2021-06-11 13:31 UTC, opbld30 commented
Docs Build status updates of commit _[1c2a4a9](https://github.com/vishriv/microsoft-graph-docs/commits/1c2a4a90ca2537e19ef7abb243bd76945b85d5f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-b1a6885d)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-b1a6885d)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-b1a6885d)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-b1a6885d)

<a id="22db53ce62c6b3647ef43acec8227bd7-b1a6885d"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="14cef535b8ef611261959c124654ca7a-b1a6885d"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get group - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-get-group.md(2,8), beta/api/termstore-store-get-group.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get group' is duplicated with other articles: 'beta/api/educationclass-get-group.md(10,1), beta/api/termstore-store-get-group.md(10,1)'. First level headings must be unique within a docset.`````

<a id="f18574c455ebb196beb2b39fc50997cb-b1a6885d"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-b1a6885d"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106111329525133-13091%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zc9TV22G8LzkNOBsumzGczV9VhNCBf9%2FXDXQg0kb1n0%3D&st=2021-06-11T13%3A26%3A26Z&se=2021-07-12T13%3A31%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 13:33 UTC, opbld32 commented
Docs Build status updates of commit _[f22c6c5](https://github.com/vishriv/microsoft-graph-docs/commits/f22c6c5816d4f9b8c0900fcee73c5b8764ddf55e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-d8c33770)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-d8c33770)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-d8c33770)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-d8c33770)

<a id="22db53ce62c6b3647ef43acec8227bd7-d8c33770"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 117, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="14cef535b8ef611261959c124654ca7a-d8c33770"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get group - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-get-group.md(2,8), beta/api/termstore-store-get-group.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get group' is duplicated with other articles: 'beta/api/educationclass-get-group.md(10,1), beta/api/termstore-store-get-group.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 170, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="f18574c455ebb196beb2b39fc50997cb-d8c33770"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 107, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-d8c33770"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 118, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151331120847-13091%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Xur5iduZMNeuxOQ77IP7IEgqTtutOGv68BUKtil6%2BBA%3D&st=2021-06-15T13%3A28%3A05Z&se=2021-07-16T13%3A33%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 13:45 UTC, opbld31 commented
Docs Build status updates of commit _[459fc79](https://github.com/vishriv/microsoft-graph-docs/commits/459fc794d9f77666d1cb95137b4a261b2fdb39d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-70421aef)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-70421aef)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-70421aef)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-70421aef)

<a id="22db53ce62c6b3647ef43acec8227bd7-70421aef"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 116, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="14cef535b8ef611261959c124654ca7a-70421aef"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get group - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-get-group.md(2,8), beta/api/termstore-store-get-group.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get group' is duplicated with other articles: 'beta/api/educationclass-get-group.md(10,1), beta/api/termstore-store-get-group.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 169, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="f18574c455ebb196beb2b39fc50997cb-70421aef"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 106, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-70421aef"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 117, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151343568724-13091%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pHICLew8aFY4LIxpjky9W2%2FsQWVvIMamccD47LIrU6g%3D&st=2021-06-15T13%3A40%3A35Z&se=2021-07-16T13%3A45%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 09:14 UTC, opbld31 commented
Docs Build status updates of commit _[ecbd593](https://github.com/vishriv/microsoft-graph-docs/commits/ecbd59397e2498f0f81b6af1a22f7a357a6ac13b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-1b9b2e9b)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-1b9b2e9b)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-1b9b2e9b)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-1b9b2e9b)
[changelog/Microsoft.SharePoint.json](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/changelog/Microsoft.SharePoint.json) | :white_check_mark:Succeeded | |

<a id="22db53ce62c6b3647ef43acec8227bd7-1b9b2e9b"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 116, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="14cef535b8ef611261959c124654ca7a-1b9b2e9b"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get group - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-get-group.md(2,8), beta/api/termstore-store-get-group.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get group' is duplicated with other articles: 'beta/api/educationclass-get-group.md(10,1), beta/api/termstore-store-get-group.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 169, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="f18574c455ebb196beb2b39fc50997cb-1b9b2e9b"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 106, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-1b9b2e9b"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 117, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160911572594-13091%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wUbOtSfK%2F08dmQeVBtrZNoNFuqPhO%2BYIxpVKEhU17hA%3D&st=2021-06-16T09%3A09%3A22Z&se=2021-07-17T09%3A14%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-07 18:08 UTC, opbld34 commented
Docs Build status updates of commit _[8fe7807](https://github.com/vishriv/microsoft-graph-docs/commits/8fe780769074a01b7c164fd8407ddcb8fea3c143)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-6ed39edc)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-6ed39edc)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-6ed39edc)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-6ed39edc)
[changelog/Microsoft.SharePoint.json](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/changelog/Microsoft.SharePoint.json) | :white_check_mark:Succeeded | |

<a id="22db53ce62c6b3647ef43acec8227bd7-6ed39edc"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 116, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="14cef535b8ef611261959c124654ca7a-6ed39edc"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get group - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-get-group.md(2,8), beta/api/termstore-store-get-group.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get group' is duplicated with other articles: 'beta/api/educationclass-get-group.md(10,1), beta/api/termstore-store-get-group.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 169, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="f18574c455ebb196beb2b39fc50997cb-6ed39edc"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 106, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-6ed39edc"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 117, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107071804590481-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A28%3A08Z&ske=2021-07-13T07%3A33%3A08Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T18%3A03%3A41Z&se=2021-08-07T18%3A08%3A41Z&sr=b&sp=r&sig=%2BHCvTpocVzM2wpMKT0bii%2BtZUKuaswj%2FB9oiwV2tXo0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 16:38 UTC, opbld31 commented
Docs Build status updates of commit _[0f555aa](https://github.com/vishriv/microsoft-graph-docs/commits/0f555aa2d78065370b4c9ae34b7da816cc333ff6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-015e94f4)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-015e94f4)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-015e94f4)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-015e94f4)
[changelog/Microsoft.SharePoint.json](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/changelog/Microsoft.SharePoint.json) | :white_check_mark:Succeeded | |

<a id="22db53ce62c6b3647ef43acec8227bd7-015e94f4"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 116, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="14cef535b8ef611261959c124654ca7a-015e94f4"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get group - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-get-group.md(2,8), beta/api/termstore-store-get-group.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get group' is duplicated with other articles: 'beta/api/educationclass-get-group.md(10,1), beta/api/termstore-store-get-group.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 169, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="f18574c455ebb196beb2b39fc50997cb-015e94f4"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 106, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-015e94f4"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 117, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081637332222-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A02%3A24Z&ske=2021-07-13T07%3A07%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T16%3A33%3A47Z&se=2021-08-08T16%3A38%3A47Z&sr=b&sp=r&sig=pNuy9Yy%2FOBIGLp3f9uIskBEnu3XWmbQy2dLuimYFaQ8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 16:46 UTC, isvargasmsft commented on changelog/Microsoft.SharePoint.json
> +      "ChangeList": [
If the objective of this PR is to add examples to the documentation, then a Changelog entry is not required.

Please note, Changelog entries are meant to announce new features, resources, methods or such. Changes in documentation are not usually announced. More details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

Is there a particular reason to add this Changelog entry?

2021-07-08 16:49 UTC, isvargasmsft commented on api-reference/beta/api/termstore-set-get.md
> +# [HTTP](#tab/http)
Line 116: These tabs are autogenerated once a week. If you added the tab manually, please remove it. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets

2021-07-08 17:12 UTC, isvargasmsft commented on api-reference/beta/api/termstore-store-get-group.md
> +# [HTTP](#tab/http)
Similar comment before: please note these tabs are automatically generated. If you added the tab manually, please remove it.

2021-07-08 17:13 UTC, isvargasmsft commented on api-reference/beta/api/termstore-store-get.md
> +# [HTTP](#tab/http)
Please apply previous comments regarding tabs.

2021-07-08 17:13 UTC, isvargasmsft commented on api-reference/beta/api/termstore-term-get.md
> +# [HTTP](#tab/http)
Please apply previous comments regarding tabs here as well.

2021-07-08 17:19 UTC, isvargasmsft requested changes
Hello @vishriv, 

Thank you very much for your work in this PR. Just a few comments:
1. Please double check if a Changelog entry is required. If this PR purpose is just to add examples, then a Changelog entry is not required. 
2. Please note, tabs are automatically generated. If you added tabs in the examples manually (by copying from another example), please remove it for the tool to properly generate the code snippets. 
3. Please fix some warnings by updating the ms.product parameter from Sharepoint to sites. Please confirm with your PM the proper name of the MS product. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103166/Metadata
4. Finally, in the **get group** document: please change the title to Get termstore group in both the title property and the H1 in lune 10. Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=guidelines-and-examples

Please feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2021-07-08 20:32 UTC, isvargasmsft commented on api-reference/beta/api/termstore-set-get.md
> +GET https://graph.microsoft.com/beta/sites/{site-id}/termStore/sets/{setId}
One additional comment; sorry for noticing it late: could you please use real looking IDs in the examples instead of just the placeholder? It is appreciated for unexperienced readers.

2021-07-13 11:48 UTC, opbld30 commented
Docs Build status updates of commit _[7cc9fbc](https://github.com/vishriv/microsoft-graph-docs/commits/7cc9fbcc42e0a67f1d8e7fbf21804b47fd26cccc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-fe78e855)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-fe78e855)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-fe78e855)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-fe78e855)

<a id="22db53ce62c6b3647ef43acec8227bd7-fe78e855"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="14cef535b8ef611261959c124654ca7a-fe78e855"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get group - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-get-group.md(2,8), beta/api/termstore-store-get-group.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get group' is duplicated with other articles: 'beta/api/educationclass-get-group.md(10,1), beta/api/termstore-store-get-group.md(10,1)'. First level headings must be unique within a docset.`````

<a id="f18574c455ebb196beb2b39fc50997cb-fe78e855"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-fe78e855"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131145395818-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A48Z&ske=2021-07-20T08%3A20%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T11%3A43%3A14Z&se=2021-08-13T11%3A48%3A14Z&sr=b&sp=r&sig=pxwbCJgZkDVzM86H0RnPx7r0grqrA14ceAUw%2FvH9UWM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 11:48 UTC, vishriv commented on changelog/Microsoft.SharePoint.json
> +      "ChangeList": [
Oh, got it. Earlier I thought every change should contain changelog. Removed.

2021-07-13 11:54 UTC, opbld34 commented
Docs Build status updates of commit _[f6f1ad2](https://github.com/vishriv/microsoft-graph-docs/commits/f6f1ad21f326b13f907134a044a58b0be38a87c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-22db53ce62c6b3647ef43acec8227bd7-30c07d73)
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-14cef535b8ef611261959c124654ca7a-30c07d73)
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-f18574c455ebb196beb2b39fc50997cb-30c07d73)
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-cc747c947fc48d40b6d4ef394d4dc085-30c07d73)

<a id="22db53ce62c6b3647ef43acec8227bd7-30c07d73"></a>
### [api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="14cef535b8ef611261959c124654ca7a-30c07d73"></a>
### [api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="f18574c455ebb196beb2b39fc50997cb-30c07d73"></a>
### [api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

<a id="cc747c947fc48d40b6d4ef394d4dc085-30c07d73"></a>
### [api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131152497832-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A52%3A39Z&ske=2021-07-20T07%3A57%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T11%3A49%3A18Z&se=2021-08-13T11%3A54%3A18Z&sr=b&sp=r&sig=l2M%2B8TfhEwFLfD3rqdEW1jC6Rmxn8GXYhMPLOo0pZvU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 12:06 UTC, opbld32 commented
Docs Build status updates of commit _[5a41728](https://github.com/vishriv/microsoft-graph-docs/commits/5a417286340eb21e37a2489c9f2e6074f6711df8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131204346346-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A54%3A16Z&ske=2021-07-20T07%3A59%3A16Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T12%3A01%3A01Z&se=2021-08-13T12%3A06%3A01Z&sr=b&sp=r&sig=RGZuZGM0ANhUzv9xACwDHzm4gM5xcIIuRvY99Mo0exI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 21:58 UTC, opbld34 commented
Docs Build status updates of commit _[5b75f38](https://github.com/vishriv/microsoft-graph-docs/commits/5b75f385e1968da371e34415e646a94597ae900a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132157090146-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A52%3A39Z&ske=2021-07-20T07%3A57%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T21%3A53%3A34Z&se=2021-08-13T21%3A58%3A34Z&sr=b&sp=r&sig=Zwx6uIoaq68UOJTafQUndRR%2F05IPt6%2BRIDgl5rj75As%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 06:19 UTC, opbld33 commented
Docs Build status updates of commit _[ea3146c](https://github.com/vishriv/microsoft-graph-docs/commits/ea3146ca0226a5a92e331e6c3e97088aaf0938c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140618102273-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A46%3A13Z&ske=2021-07-20T07%3A51%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T06%3A14%3A41Z&se=2021-08-14T06%3A19%3A41Z&sr=b&sp=r&sig=bEJXOIrpZaJtxSUj%2FImVh28YgcAw4e40NHBCJyd%2FVy8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 15:27 UTC, opbld34 commented
Docs Build status updates of commit _[3ce094e](https://github.com/vishriv/microsoft-graph-docs/commits/3ce094e1c5a4d265eefa8cbd36c5d95576e6dbcc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107141525398126-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T01%3A51%3A21Z&ske=2021-07-21T01%3A56%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T15%3A22%3A12Z&se=2021-08-14T15%3A27%3A12Z&sr=b&sp=r&sig=dembwi5z1lmNSPc6KgAxay9vbfbQwA0mqQ4ZPr%2BCkDM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 16:23 UTC, opbld34 commented
Docs Build status updates of commit _[74de48b](https://github.com/vishriv/microsoft-graph-docs/commits/74de48ba1b3a8d2b569f773ff5b366f63400596c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107141620565804-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T08%3A48%3A38Z&ske=2021-07-21T08%3A53%3A38Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T16%3A18%3A05Z&se=2021-08-14T16%3A23%3A05Z&sr=b&sp=r&sig=vVuT4z9yl4lY0qsSpsA%2BzAlGHNlRbn3SyN7Mw1n95IE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 16:28 UTC, isvargasmsft approved these changes
Thank you for addressing my comments.

2021-07-15 02:58 UTC, Lauragra commented on api-reference/beta/api/termstore-set-get.md
> +GET /sites/{site-id}/termStore/sets/{setId}
Please apply consistent formatting to the placeholders, so, {site-id}, {set-id}.

2021-07-15 02:59 UTC, Lauragra commented on api-reference/beta/api/termstore-set-get.md
> +### Example 1: Get a TermStore Set
Global: We use sentence case for headings, and resource names in Microsoft Graph are lower camel case, so in this case the heading would be "Get a termStore set".

2021-07-15 02:59 UTC, Lauragra commented on api-reference/beta/api/termstore-set-get.md
> +**Note:** The response object shown here might be shortened for readability.
Global: Please format at a note by adding the ">" symbol here.

2021-07-15 03:00 UTC, vishriv commented on api-reference/beta/api/termstore-set-get.md
> +GET /sites/{site-id}/termStore/sets/{setId}
Hi @Lauragra , these are the formats only. I have added the real ids in the examples

2021-07-15 03:05 UTC, Lauragra commented on api-reference/beta/api/termstore-store-get-group.md
> +title: "Get termStore group"
The file name here should just be "termstore-group-get".

2021-07-15 03:06 UTC, Lauragra commented on api-reference/beta/api/termstore-store-get-group.md
> +### Example 1: Get a TermStore Group
Please restore the original casing here -"termStore group"

2021-07-15 03:52 UTC, Lauragra commented on api-reference/beta/api/termstore-set-get.md
> +GET /sites/{site-id}/termStore/sets/{setId}
Yep, I just thought you would want to format the placeholders consistently. Generally they are hyphenated, site-id, set-id.

2021-07-15 03:53 UTC, Lauragra commented on api-reference/beta/api/termstore-store-get-group.md
> +### Example 2: Get a TermStore Group and its parent site ID
Please restore casing and apply sentence casing to headings throughout the PR.

2021-07-15 06:41 UTC, opbld32 commented
Docs Build status updates of commit _[ca38d9e](https://github.com/vishriv/microsoft-graph-docs/commits/ca38d9e547d56603acecfc0ddddcf500d8c6307a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150639228451-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T21%3A54%3A41Z&ske=2021-07-21T21%3A59%3A41Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T06%3A36%3A12Z&se=2021-08-15T06%3A41%3A12Z&sr=b&sp=r&sig=Zfd3wMY0TBZgUAPZr0M7DrUv8Z7aOzyaQEg0H0vJgGo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 07:10 UTC, opbld33 commented
Docs Build status updates of commit _[6c06d60](https://github.com/vishriv/microsoft-graph-docs/commits/6c06d607316da98634e87206655dad3ffc9ad302)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a18dfbfc)
[api-reference/beta/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/resources/termstore-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) | [Details](#user-content-90058fd2958f8b747c97cb587da376db-a18dfbfc)
[api-reference/beta/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

<a id="0817dce4456c16725d5333633847d38f-a18dfbfc"></a>
### [api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/toc.yml)
 - **Line 13538, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/termstore-store-get-group.md'.`````

<a id="90058fd2958f8b747c97cb587da376db-a18dfbfc"></a>
### [api-reference/beta/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/resources/termstore-group.md)
 - **Line 7, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'Sharepoint'.`````
 - **Line 27, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/termstore-store-get-group.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150708520993-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A31%3A12Z&ske=2021-07-20T08%3A36%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T07%3A05%3A29Z&se=2021-08-15T07%3A10%3A29Z&sr=b&sp=r&sig=44BZS7vuhUzrRhxZhIe4Y%2BncpBRULiW4htZH%2FP2fjqI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 07:25 UTC, opbld34 commented
Docs Build status updates of commit _[58944d4](https://github.com/vishriv/microsoft-graph-docs/commits/58944d4796b47ea20f3e9c4125ed2476b93b183a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150723287256-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A31%3A12Z&ske=2021-07-20T08%3A36%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T07%3A20%3A00Z&se=2021-08-15T07%3A25%3A00Z&sr=b&sp=r&sig=8cpr4iwAqaoh%2Fsfmsx2wQG7Q3YIHu%2Bhv2ZeHDl2iTrM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 07:52 UTC, opbld30 commented
Docs Build status updates of commit _[8932ca7](https://github.com/vishriv/microsoft-graph-docs/commits/8932ca70bf89137418869b07628ea6e6de41c574)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/termstore-group-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-group-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-set-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-set-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-set-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-store-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-store-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-store-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/api/termstore-term-get.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/api/termstore-term-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-term-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/resources/termstore-group.md](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/resources/termstore-group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/termstore-group?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/vishriv/microsoft-graph-docs/blob/siteCollectionTermStoreUsage/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/termstore-group-get?view=graph-rest-beta&branch=pr-en-us-13091) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150751125010-13091%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T03%3A03%3A12Z&ske=2021-07-21T03%3A08%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T07%3A47%3A54Z&se=2021-08-15T07%3A52%3A54Z&sr=b&sp=r&sig=pdF0TEcPhUFSrScWXf%2BG5jyP0ka23UkQJ0vIoqQoQRI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 08:11 UTC, vishriv commented on api-reference/beta/api/termstore-set-get.md
> +GET /sites/{site-id}/termStore/sets/{setId}
Got it. I misread it earlier. Resolved.

2021-07-16 03:02 UTC, Lauragra approved these changes

2021-07-16 03:02 UTC, merged