[Teams] Add chat rsc to permissions reference
microsoftgraph/microsoft-graph-docs pull request #13108
Opened 2021-06-12 17:54 UTC by jessiechan27

2021-06-12 17:55 UTC, opbld30 commented
Docs Build status updates of commit _[ca90835](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca90835e9826f61f439ba6a9a7f0eb536b395a26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-rsc-perms/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13108) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106121754292100-13108%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ktWZOFpEBvBGA1llUPln4JXo%2BiYPRD0%2FpU1rODqmIY8%3D&st=2021-06-12T17%3A50%3A52Z&se=2021-07-13T17%3A55%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-12 22:00 UTC, AkJo commented on concepts/permissions-reference.md
> +| TeamsAppInstallation.Read.Chat | Read which apps are installed in this chat.                   | Allows the app read the Teams apps that are installed in this chat along with the permissions grante
app to read

2021-06-12 22:13 UTC, AkJo commented on concepts/permissions-reference.md
> +| OnlineMeeting.ReadBasic.Chat   | Read basic properties of a meeting associated with this chat. | Allows the app to read basic properties of a meeting associated with this chat, without a signed-in
Allows the app to read basic properties, such as name, schedule, organizer and join link, of a meeting associated with this chat, without a signed-in user.

2021-06-12 22:14 UTC, AkJo commented on concepts/permissions-reference.md
> +## Chats resource-specific consent permissions
Thinking of keeping this singular.

Chat resource specific consent permissions

2021-06-12 22:22 UTC, AkJo commented on concepts/permissions-reference.md
> +## Chats resource-specific consent permissions
What are your thoughts?

2021-06-12 22:56 UTC, jessiechan27 commented on concepts/permissions-reference.md
> +## Chats resource-specific consent permissions
I also think it should be singular to keep consistent with the other resources

2021-06-12 22:57 UTC, opbld34 commented
Docs Build status updates of commit _[47f76ef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47f76efd4b3fc629d4912ab18b5a87a967fd3672)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-rsc-perms/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13108) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106122255482097-13108%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2eCO7nfcvdqlhMgFA8M8WHgZd5CeXduOhkxRBK5t424%3D&st=2021-06-12T22%3A52%3A16Z&se=2021-07-13T22%3A57%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 17:54 UTC, AkJo approved these changes

2021-06-15 19:34 UTC, JarbasHorst requested changes

2021-06-15 19:34 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +| ChatMember.Read.Chat           | Read this chat's members.                                     | Allows the app to read the members of this chat, without a signed-in user. |No | No |
For consistency, I recommend you replacing "the members of this chat" with "this chat's members"

2021-06-15 19:34 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +| ChatSettings.Read.Chat         | Read this chat's settings.                                    | Allows the app to read this chat's settings, without a signed-in user. |No | No |
For consistency, I recommend you using italics to emphasize all permissions listed in this table. For example, \_ChatSettings.ReadWrite.Chat\_

2021-06-15 19:34 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +| OnlineMeeting.ReadBasic.Chat   | Read basic properties of a meeting associated with this chat. | Allows the app to read basic properties, such as name, schedule, organizer and join link, of a meeti
For readability, I recommend you using em dash after "... basic properties". Suggested revision:

"Allows the app to read basic properties—such as name, schedule, organizer, and join link—of a meeting associated with this chat, without a signed-in user."

2021-06-15 19:46 UTC, opbld31 commented
Docs Build status updates of commit _[57971e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57971e67b2faef9520860c61e2bd24642bcf44d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-rsc-perms/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13108) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151944522229-13108%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ljCS88AFvp9fw3gnWetSAfKyLLFmY6o0OLkc6zgfGbs%3D&st=2021-06-15T19%3A41%3A24Z&se=2021-07-16T19%3A46%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 20:45 UTC, JarbasHorst requested changes

2021-06-15 20:45 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +| _OnlineMeeting.ReadBasic.Chat_   | Read basic properties of a meeting associated with this chat. | Allows the app to read basic properties —such as name, schedule, organizer and join link— of a mee
Please, remove the empty character before and after the em dashes. For more information, see https://docs.microsoft.com/en-us/style-guide/top-10-tips-style-voice#dont-be-spacey. Additionally, add a comma after organizer. Suggested revision:

Allows the app to read basic properties—such as name, schedule, organizer, and join link—of a meeting associated with this chat, without a signed-in user.

2021-06-15 20:45 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +| _Chat.Manage.Chat_               | Manage this chat.                                             | Allows the app to manage the chat, the chat's members and grant access to the chat's data, without
Please, add a comma after chat's members. Suggested revision:

"Allows the app to manage the chat, the chat's members, and grant access to the chat's data, without a signed-in user."

2021-06-15 21:48 UTC, opbld31 commented
Docs Build status updates of commit _[a7f59c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7f59c463dfab0b5f454b5b7f01617cb4deaa9bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-rsc-perms/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13108) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152146400007-13108%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qHSq1gaLnoAXonyyspCchfoq55ZcRsXr8NVq%2ByjfUbw%3D&st=2021-06-15T21%3A43%3A09Z&se=2021-07-16T21%3A48%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 00:51 UTC, opbld34 commented
Docs Build status updates of commit _[cd5af7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd5af7db34b1567be0631be4188deb3042cf7cc9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-rsc-perms/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/chat-rsc-perms/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13108) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160049559624-13108%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qpi5LW3lPJB0H71EKndjwhjJ%2Fnqh0wlITKbu1RfoGAQ%3D&st=2021-06-16T00%3A46%3A26Z&se=2021-07-17T00%3A51%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 00:58 UTC, Lauragra approved these changes

2021-06-16 00:59 UTC, merged