The set presence APIs
microsoftgraph/microsoft-graph-docs pull request #13119
Opened 2021-06-14 18:46 UTC by elvinyang-msft

2021-06-14 18:47 UTC, opbld34 commented
Docs Build status updates of commit _[5dbd66f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dbd66f56fabeff2e74941e3449b2397e8310139)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-set.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-set?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141846245898-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AKpJjqZNT2LE7qgwR4c7y3186865gLnatpy6wUWX6ok%3D&st=2021-06-14T18%3A42%3A51Z&se=2021-07-15T18%3A47%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 19:17 UTC, opbld31 commented
Docs Build status updates of commit _[9c96355](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c963555b4bbb04d7d7dd92beae592c36b92f7ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-set.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-set?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141915555403-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k%2FsWu1dlQbseLUew11tquW794bJPVTTMFSsP346xy%2Fk%3D&st=2021-06-14T19%3A12%3A27Z&se=2021-07-15T19%3A17%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 19:19 UTC, jsandoval-msft approved these changes

2021-06-14 19:19 UTC, jsandoval-msft commented on api-reference/beta/api/presence-clear.md
> +
Do we need to show the full table that indicates delegated permissions are not currently supported?

2021-06-14 19:20 UTC, opbld31 commented
Docs Build status updates of commit _[a3311fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3311faed63a04631d0e7efd0eb50b8821b91ef5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-set.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-set?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141918509633-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MqE9EvAk3AbeUFgZkJ6WbSxaosbtqm1QHw3Fc7CqqhA%3D&st=2021-06-14T19%3A15%3A19Z&se=2021-07-15T19%3A20%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 19:22 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clear.md
> +
No. We only list what is supported today

2021-06-14 23:21 UTC, zhengni-msft commented on api-reference/beta/api/presence-set.md
> +* Among app-configured: DND > Busy > Available > Away
Seems there is nowhere to mention what DND is. Can we use full name DoNotDistrurb here?

2021-06-14 23:21 UTC, zhengni-msft commented on api-reference/beta/api/presence-set.md
> +Supported combinations of `availability` and `activity` are:
Can we specifically call out the avilability and activity's we don't support in SET but returned in GET here also, as they are mentioned in the GET spec?

2021-06-14 23:55 UTC, elvinyang-msft commented on api-reference/beta/api/presence-set.md
> +Supported combinations of `availability` and `activity` are:
Per discussion we put `currently not supported for set presence` right next to DoNotDisturb

2021-06-14 23:56 UTC, opbld34 commented
Docs Build status updates of commit _[42bb6cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42bb6cdbbbd8a87e0ad2df8bae8f96d0ce68eaf4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-set.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-set.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-set?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clear?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142354367524-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1yzJhLdSsmJ50ZPbeqeHWBjcECMufqsHqmtLW4%2F2Ksk%3D&st=2021-06-14T23%3A51%3A14Z&se=2021-07-15T23%3A56%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 03:09 UTC, Lauragra commented on api-reference/beta/api/presence-clear.md
> +title: "Clear presence"
The file name here should be presence-clearpresence, and the title and H1 should be "presence: clearPresence".

2021-06-15 20:15 UTC, opbld32 commented
Docs Build status updates of commit _[2535701](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2535701d3c62c8637e000da7daac6ae8271bcee8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152013587206-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=S0UKTdfA6agXvrVD6ax%2Bl%2F20nY22nXjFvNScb8CD%2Fi0%3D&st=2021-06-15T20%3A10%3A26Z&se=2021-07-16T20%3A15%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 20:15 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clear.md
> +title: "Clear presence"
@Lauragra updated

2021-06-16 00:52 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clear.md
> +title: "Clear presence"
@Lauragra please disregard this PR for now as our PM wanted us to halt the release for now

2021-06-17 19:06 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clear.md
> +title: "Clear presence"
@Lauragra got a green light from our PM and the doc is good to go

2021-06-21 21:00 UTC, JarbasHorst commented on api-reference/beta/api/presence-setpresence.md
> +# [HTTP](#tab/http)
Please, remove this line. Tabs are automatically generated for docs.

2021-06-21 21:11 UTC, JarbasHorst commented on api-reference/beta/api/presence-clearpresence.md
> +The application can clear its presence session. If a user's only presence session (all sessions from Teams clients and applications adding together) gets cleared, the user's presence will change to `
I recommend updating this sentence for simplicity and to avoid gerunds. Suggested revision:

... If only the presence session (aggregated state of all sessions from Teams clients and applications) of a user gets cleared, user's presence ...

2021-06-21 21:16 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +      "Version": "v1.0",
Please, change the version from v1.0 to beta

2021-06-21 21:21 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the setPresence action.",
From a customer point of view, it is useful to access the corresponding article directly from the description. Please, add the link to the article here. Suggested revision:

Added the \[setPresence\](https://docs.microsoft.com/en-us/graph/api/...?view=graph-rest-beta) action.

2021-06-21 21:21 UTC, JarbasHorst commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the clearPresence action.",
From a customer point of view, it is useful to access the corresponding article directly from the description. Please, add the link to the article here. Suggested revision:

Added the \[clearPresence\](https://docs.microsoft.com/en-us/graph/api/...?view=graph-rest-beta) action.

2021-06-21 22:26 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clearpresence.md
> +Request to clear a presence session:
Removed

2021-06-21 22:26 UTC, elvinyang-msft commented on api-reference/beta/api/presence-setpresence.md
> +# [HTTP](#tab/http)
Removed

2021-06-21 22:27 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clearpresence.md
> +The application can clear its presence session. If a user's only presence session (all sessions from Teams clients and applications adding together) gets cleared, the user's presence will change to `
Simplified the sentence while keeping the original meaning..

2021-06-21 22:27 UTC, elvinyang-msft commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added the clearPresence action.",
Link added

2021-06-21 22:28 UTC, opbld30 commented
Docs Build status updates of commit _[8f39d6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f39d6ddf6a911fe10208b67470f5915180c712f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106212226277590-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zUAvW0bkjHMlB3%2FXArlwfcL3uJeuU%2B84dg7xCWJGqNs%3D&st=2021-06-21T22%3A23%3A20Z&se=2021-07-22T22%3A28%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 17:59 UTC, Lauragra commented on api-reference/beta/api/presence-clearpresence.md
> +title: "Presence: clearPresence"
Note that entity names in Microsoft Graph are lower camel case, so presence in this case should be lower case.

2021-06-22 18:08 UTC, Lauragra commented on api-reference/beta/api/presence-clearpresence.md
> +> For details about the concept of presence sessions, see [Presence: setPresence - concept: presence sessions](presence-setpresence.md#concept-presence-sessions).
I'm not sure why this is formatted as an important. Note that the result here is two Importants stacked next to each other, which reduces the impact. I suggest converting this to a normal text cross-reference. You can move this to a See also H2 section at the end of the topic, or move it to follow the summary statement as a separate line. Please revise as: "For details about presences sessions, see [presence: setPresence]." We actually probably want to update the link destination as well.

2021-06-22 18:10 UTC, Lauragra commented on api-reference/beta/api/presence-setpresence.md
> +### Concept: presence sessions
We generally have minimal conceptual information in API topics, If you can keep this contextual information about presence to approximately 1/3 page, this might go in the presence resource topic. Otherwise, if more explanation is warranted, you'll want to consider creating a separate conceptual topic to describe presence concepts.

2021-06-22 19:11 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clearpresence.md
> +> For details about the concept of presence sessions, see [Presence: setPresence - concept: presence sessions](presence-setpresence.md#concept-presence-sessions).
Moved to follow the summary.

2021-06-22 19:17 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clearpresence.md
> +Below example shows the application with ID `22553876-f5ab-4529-bffb-cfe50aa89f87` updating its presence session for user `fa8bf3dc-eca7-46b7-bad1-db199b62afc3`.
Placing the introductory sentence after `Example` heading, as request + response together make the example..

2021-06-22 19:28 UTC, elvinyang-msft commented on api-reference/beta/api/presence-setpresence.md
> +### Concept: presence sessions
Understood. I believe the concept section is way less than that and since it is so important and fundamental we do want to place it in the API doc..

2021-06-22 19:32 UTC, elvinyang-msft commented on api-reference/beta/api/presence-setpresence.md
> +> * When calling this API, the ID of the application should be supplied as the `sessionId`.
Using the same sentence that's used on the clearPresence doc:

The ID of the application should be provided as the `sessionId`

2021-06-22 19:39 UTC, opbld30 commented
Docs Build status updates of commit _[b0eb0cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0eb0ccb9fcb3ab3613731ba4d454d93d4d239a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106221937576979-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FGn%2BBON3RBsuwhw8Yy%2F2%2FyR20BkbfRvuXNw%2BSbARxPo%3D&st=2021-06-22T19%3A34%3A34Z&se=2021-07-23T19%3A39%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 20:11 UTC, elvinyang-msft commented on api-reference/beta/api/presence-setpresence.md
> +> * When calling this API, the ID of the application should be supplied as the `sessionId`.
Actually after thinking again I do feel your suggestion is better. Will make an update.

2021-06-22 20:16 UTC, opbld33 commented
Docs Build status updates of commit _[aa0ad9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa0ad9fd668e2ea0bed4995b87a45c8c2bc3023f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106222015133253-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KjbEVunivMRdybB5cz6RLuKOnNbSXuGsYe%2FqgJoR%2FjE%3D&st=2021-06-22T20%3A11%3A40Z&se=2021-07-23T20%3A16%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 20:17 UTC, JarbasHorst requested changes

2021-06-22 20:17 UTC, JarbasHorst commented on api-reference/beta/api/presence-setpresence.md
> +## Example
If the API topic has only one example (generated or custom), use H2 Examples (plural) as section title. Please, replace Example with Examples

2021-06-22 20:17 UTC, JarbasHorst commented on api-reference/beta/api/presence-setpresence.md
> +| availability | activity          | Description                                              |
For conformity, please capitalize availability and activity.

2021-06-22 20:17 UTC, JarbasHorst commented on api-reference/beta/api/presence-setpresence.md
> +The following example shows the application with ID `22553876-f5ab-4529-bffb-cfe50aa89f87` that sets its presence session for user `fa8bf3dc-eca7-46b7-bad1-db199b62afc3`.
Since we don't have the Example 1 anymore, I recommend you replacing "The following example..." with "The following request..." for clarity.

2021-06-22 20:17 UTC, JarbasHorst commented on api-reference/beta/api/presence-clearpresence.md
> +The following example shows the application with ID `22553876-f5ab-4529-bffb-cfe50aa89f87` that clears its presence session for user `fa8bf3dc-eca7-46b7-bad1-db199b62afc3`.
Since we don't have the Example 1 anymore, I recommend you replacing "The following example..." with "The following request..." for clarity.

2021-06-22 20:29 UTC, elvinyang-msft commented on api-reference/beta/api/presence-setpresence.md
> +| availability | activity          | Description                                              |
availability and activity are the property names of the presence entity so they should be camel case

2021-06-22 20:33 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clearpresence.md
> +## Example
@Lauragra shall we use singular or plural when there is only one example?

2021-06-22 23:46 UTC, elvinyang-msft commented on api-reference/beta/api/presence-clearpresence.md
> +## Example
@JarbasHorst updated to plural for consistency

2021-06-22 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[fa54cdf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa54cdfa451cfec6247e7d3251ae90063e328bc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106222345564646-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZDAyYSqdy1o0Ixt%2BXp2qt21hQuAwowXHC4oOW%2FXjGSY%3D&st=2021-06-22T23%3A44%3A07Z&se=2021-07-23T23%3A49%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 01:39 UTC, Lauragra commented on api-reference/beta/api/presence-clearpresence.md
> +## Example
It's okay to leave as singular in this case. In general the H2 is plural even if there's one example, but we don't need to change it to plural.

2021-06-23 19:06 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-06-24 01:02 UTC, opbld30 commented
Docs Build status updates of commit _[483bf94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/483bf948d7e79014abcdb12460ab7393143a66ce)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) | [Details](#user-content-e3822718d36caff64688e578b05a508f-00ec6e26)
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="e3822718d36caff64688e578b05a508f-00ec6e26"></a>
### [api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md)
 - **Line 18, Column 43**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#concept-presence-sessions' in 'beta/api/presence-setpresence.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240100404057-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ly105NSFRstC2lHGMfBw6UvapZDHkQ%2FIuiEaPr6BL%2BY%3D&st=2021-06-24T00%3A57%3A09Z&se=2021-07-25T01%3A02%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 01:03 UTC, Lauragra approved these changes

2021-06-24 01:04 UTC, opbld33 commented
Docs Build status updates of commit _[059b163](https://github.com/microsoftgraph/microsoft-graph-docs/commits/059b1638dbd882f81f486a762a1ed4989ce061e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) | [Details](#user-content-e3822718d36caff64688e578b05a508f-0c42ebda)
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="e3822718d36caff64688e578b05a508f-0c42ebda"></a>
### [api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md)
 - **Line 18, Column 43**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#concept-presence-sessions' in 'beta/api/presence-setpresence.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240103052764-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tsttLVJOOGBj06A9%2Fy3gPLsLoaJkoe4ygY%2BF%2BijO8ks%3D&st=2021-06-24T00%3A59%3A34Z&se=2021-07-25T01%3A04%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 01:08 UTC, opbld32 commented
Docs Build status updates of commit _[fce1b53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fce1b534f14cc546d8936f908c90caa3b6123494)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/presence-clearpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-clearpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/api/presence-setpresence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/api/presence-setpresence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-setpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-clearpresence?view=graph-rest-beta&branch=pr-en-us-13119) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/setPresenceNew/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240107201704-13119%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QQlPe%2Bk6TQ%2F2u6BUngfO2zSgZHEII%2FeHrBvRmFAMgOg%3D&st=2021-06-24T01%3A03%3A46Z&se=2021-07-25T01%3A08%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 01:11 UTC, merged