Added List and Create api files and its description in the calendarPe…
microsoftgraph/microsoft-graph-docs pull request #13113
Opened 2021-06-14 11:08 UTC by Swathi-Birlangi

…rmission, also added missing description for the originalStart property in the event file.

2021-06-14 11:09 UTC, opbld32 commented
Docs Build status updates of commit _[ba75ede](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/ba75ede605aff0d9e9cd40f4f50e8754cb7debd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendarpermission-create.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-create?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-list.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-list?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141108129110-13113%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5kbSIgJnYP9UFGRcH7GfY2lYIfN6qSgHHF9AQbuh%2BiA%3D&st=2021-06-14T11%3A04%3A41Z&se=2021-07-15T11%3A09%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 23:40 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +title: "Create calendarPermission"
Please rename the file as calendar-post-calendarpermission.md.
Reasons and more filenaming info: Please see the [file naming](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming) topic.

2021-06-14 23:41 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-list.md
> +title: "Get calendarPermission"
Please rename the file as calendar-list-calendarpermissions.md.
Reasons and more filenaming info: Please see the [file naming](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming) topic.

2021-06-14 23:44 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-list.md
> +# Get calendarPermission
Lines 2 and 10: Please use the topic title "List calendarPermissions".
Note the use of the term "calendarPemissions" is based on the navigation property name calendarPermissions. It's plural solely because that's how the nav property is named.

See the [TOC and topic title](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title) article for more info.

2021-06-15 07:46 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-list.md
> +Get the specified permissions object of a user or group calendar that has been shared.
Line 14:
The description for a list operation should indicate it returns a collection of objects, not a single object.
I can suggest the following description so that it's clearer what one gets out of a calendarPermission object, without requiring a click to the object topic.
Note that I separate the two sentences in two paragraphs. The first paragraph should be a summary description of the operations. Any additional information should be in a subsequent paragraph(s).

"Gets a collection of calendarPermission (provide link to the object topic) objects that describe the identity and roles of users with whom the specified calendar has been shared or delegated.

The calendar can be a user calendar or group calendar."

user with whom the calendar has been shared or delegated in an Outlook client.

2021-06-15 07:48 UTC, angelgolfer-ms commented on api-reference/beta/resources/calendarpermission.md
> +Get, list, create, update, and delete of calendar permissions is supported on behalf of only the calendar owner.
Line 16 and lines 26-28:
Please reorder the operations that reflect the order we use in the TOC: list, create, get, update, delete.

2021-06-15 08:21 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +Create the specified permissions object of a user or group calendar that has been shared.
Line 14:
Have you had a chance to get @JuForan  or @Harini84 to do a tech review on this PR?

I am not sure if the logic of this description is correct. The use of the present perfect tense in the phrase "... calendar that has been shared" makes it sound like first, somewhere (e.g., through the UI in a client?) the calendar owner shares the calendar, then subsequently, use this operation to programmatically create a calendarPermission object?

My guess is, by creating a calendarPermission object for a calendar, you're actually sharing or delegating the calendar, so it's not a two-step procedure.

Please confirm and if I am correct, then I suggest the description:
"Create a calendarPermission resource (link to calendarpermission.md) to specify the identity and role of the user with whom the specified calendar is being shared or delegated.

The calendar can be a user calendar or group calendar."

2021-06-15 08:24 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +If successful, this method returns a `200 OK` response code and the requested [calendarPermission](../resources/calendarpermission.md) object in the response body.
Line 57:
Remove "the requested". "Requested" implies you specified a particular object, and in this case the object didn't even exist, you're using the operation to create one.
"... response code and a [calendarPermission](../resources/calendarpermission.md) object..."

2021-06-15 08:27 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +# [HTTP](#tab/http)
Since this is a new example, do not include lines 65, 92-108. See this topic and section: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets?anchor=enabling-auto-generation-of-code-snippets

2021-06-15 08:34 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +```msgraph-interactive
Line 71:
msgraph-interactive is to support the try-it experience. I think there's a tool to enable the try-it experience, and the tool sets msgraph-interactive.
So here, change line 71 to just http.

2021-06-15 08:39 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +{
Lines 73, 74:
You don't have to separate the request and request body by these two lines of ```.

On the other hand, since this operation requires a request body, you should include this line in line 73.
Content-type: application/json

You need to add a blank line between this line and line 75, the beginning of the request body. So line 74 should be a blank line.

This is documented in this section: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=request-headers-and-body

2021-06-15 08:56 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +    "name": "My Organization",
Line 77:
Perhaps you should seek clarification from @Harini84 or @JuForan whether every calendar by default has a calendarPermission resource created already for "My organization". If so, that would be consistent with the sharing or delegating experience in the Outlook UI.
Meanwhile, I suggest you specify a user email address. If you look at the emailAddress property description in calendarpermission.md, the property is actually null for "My organization". Besides, isRemovable (line 79) would be false for "My organization".

2021-06-15 08:58 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +    "name": "My Organization",
Line 128:
Per the emailAddress property description in calenderpermission.md, this line doesn't seem correct.

Also, in general, please always make sure you have tried out the example in Graph Explorer, before you add it to the docs.

2021-06-15 09:03 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +author: "sochowdh"
Line 5:
Can you confirm with @Harini84 and @JuForan whose Github name should be in the author field, for the sharing API topics?
In general, the person specified in this field would get email notifications of any Github issues or PRs opened by customers, and should respond to, or reassign someone else to respond to the issue or PR. Usually it's the PM owner who doesn't get reassigned to other feature areas periodically.

2021-06-15 09:04 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-create.md
> +author: "sochowdh"
The above comment applies to the new list operation topic in this PR as well.

2021-06-15 09:08 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-list.md
> +
Lines 27-43:
Wouldn't the syntax end with calendarPermissions in each case?
Also, the lead-in sentences (lines 27, 33, 39) are not correct either - in a list operation, you don't specify any particular calendarPermission object in the syntax.
Something like (for line 27) makes more sense:
"Get the permissions of a user's primary calendar:"

2021-06-15 09:13 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-list.md
> +The following is an example of the request.
Please refer to my comments in the create operation topic about how to specify new examples.

Also, a GET operation doesn't take any request body, so lines 79-93 are redundant. As mentioned above in the create operation topic, please always make sure you try out an example in Graph Explorer before adding it to the docs.

Not sure if you have had a chance, if not, please take a look at my comments in Bhupesh's PR 9525.
In particular, for an example to illustrate the list operation, please see this [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/9525/files#r516421220).

2021-06-15 09:15 UTC, angelgolfer-ms commented on api-reference/beta/resources/event.md
> +|originalStart|DateTimeOffset|The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. Only occurrences and exceptions of a series has value for origin
Line 37:
Missing article "a" before "value". Should read:
"... of a series has a value for originalStart..."

2021-06-15 09:25 UTC, angelgolfer-ms requested changes
Hi @Swathi-Birlangi , thank you for the effort in your initial PR! Please take a look at my comments.

Also, you'll need to include changelog updates; see the [Changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog) topic.

If you haven't had a chance, it might be helpful as part of your ramping up to read up on a similar PR [9525](https://github.com/microsoftgraph/microsoft-graph-docs/pull/9525/files). You might find it encouraging to verify what you have done correctly in this PR, or similar issues you have overlooked, and the reasons behind the corresponding appropriate approach.

When you have finished incorporating my feedback, please ping me on Teams so that I can review again. Let me know if you have questions.

2021-06-24 04:09 UTC, opbld32 commented
Docs Build status updates of commit _[842028a](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/842028a724b813f4fe48636ebd111e8cb535d84d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106240407574226-13113%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CSYPus%2FH7DsDrlBNRr4GPvyhIQcvHCFC8nKr5AjlQis%3D&st=2021-06-24T04%3A04%3A29Z&se=2021-07-25T04%3A09%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 10:38 UTC, Swathi-Birlangi reviewed
@angelgolfer-ms 
I have incorporated your feedback comments, please check and approve for merge in case of no errors

2021-06-30 07:55 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +# Get List calendarPermissions
Line 10: please fix title, per [comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/13113#discussion_r651348257) from the last pass.

2021-06-30 08:54 UTC, opbld33 commented
Docs Build status updates of commit _[4f8f500](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/4f8f500d0cbe3364ac36dc2ff251b98cedf23dd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-post-calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) | [Details](#user-content-748f788912a767c4221e01585c7b6100-b625313b)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

<a id="748f788912a767c4221e01585c7b6100-b625313b"></a>
### [api-reference/beta/api/calendar-post-calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermission.md)
 - **Line 71, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '[HTTP]') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106300853117916-13113%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ilGtFHkxl6B1quAxLi5GUY8qLxXZt6jec5UGEt2df3k%3D&st=2021-06-30T08%3A49%3A32Z&se=2021-07-31T08%3A54%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-02 05:42 UTC, Swathi-Birlangi commented
@angelgolfer-ms 
Hi Angela,

I have now double checked and committed the changes, please review and let me know in case of any changes.

Regards,
Swathi.

2021-07-17 06:24 UTC, opbld34 commented
Docs Build status updates of commit _[a4a4167](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/a4a4167ba03e7eb347f8118e29259e24d401d6db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-post-calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) | [Details](#user-content-748f788912a767c4221e01585c7b6100-7d232cb2)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

<a id="748f788912a767c4221e01585c7b6100-7d232cb2"></a>
### [api-reference/beta/api/calendar-post-calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermission.md)
 - **Line 71, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '[HTTP]') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107170623033597-13113%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A48%3A20Z&ske=2021-07-23T08%3A53%3A20Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-17T06%3A19%3A36Z&se=2021-08-17T06%3A24%3A36Z&sr=b&sp=r&sig=MTKXAcNOFdU%2BKvybL%2Fj976B5ZTkNk2PFui14uF6%2BDJ4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-17 07:10 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermission.md
> +  "tocPath": ""
ATTENTION
Beyond line 149:
@Swathi-Birlangi , did you do a copy and paste from some topic to create this topic?
Just to be syntactically complete, you're missing a line to close out the HTML comment that started in line 144. 
And, if you look at other MD files, there should also be a "suppressions" attribute after the "tocPath" attribute.
It should go like this, starting with line 149:

  "tocPath": "",
  "suppressions": [
  ]
}
-->

I'm adding these lines on your behalf because re-reviewing the same PR takes you and I extra cycles and more importantly, the docs for some of these APIs are long overdue.
I labelled this comment with "ATTENTION" to call out that this kind of oversight is extremely rare among our Graph partners and therefore below expectations.

2021-07-17 07:38 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermission.md
> +# [HTTP]
ATTENTION
Did you notice your PR has an API Doctor error and therefore it didn't build properly?
You can look at the first screen shot in this CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103179/API-Doctor-validate-examples

Your PR has a similar error right now. If you followed the steps in the CDK topic, you would see this error: https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=59860&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=25134

For ease of discussion, I am copying the error here:
"Error: /api/calendar-post-calendarpermission.md:
      Exception processing links.
      Link Definition was null. Link text: HTTP (Parameter 'Definition')"

The error refers to line 71:
# [HTTP] 
which is causing an API Doctor error.
This is because, as you should know, in Markdown, the square brackets are reserved for specifying links. And yet the closing square bracket is not followed by a pair of parentheses, and that's why that triggers an API Doctor error.

I think in your case, you didn't mean that line to be anything about links.
Instead, line 71 should be a line like the following so to tell the docs platform to format the example request and request body:

```http

2021-07-17 07:53 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermission.md
> +# [HTTP]
ATTENTION

Let me continue: when you use the tick-tick-tick mark to demarcate code lines, you use that in a pair - where the code starts and where the code ends.
Using this topic as an example, after the closing curly bracket for your example request body, you would add the closing tick-tick-tick mark.

However, did you notice lines 81-92, and lines 94-105 are conflicting and make the request body syntactically incorrect?

This triggered a second API Doctor error: https://dev.azure.com/msrobots/apidoctor/_build/results?buildId=59860&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dac0b392-2308-5704-b9f7-c5b20adf012e&l=25138

Lines 81-92:
  "isRemovable": true,
  "isInsideOrganization": true,
  "role": "write",
  "allowedRoles": [
    "none",
    "freeBusyRead",
    "limitedRead",
    "read",
    "write"
  ],
  "id": "RGVmYXVsdA=="
}

Lines 94-105:
  },
  "isRemovable": true,
  "isInsideOrganization": true,
  "role": "write",
  "allowedRoles": [
    "none",
    "freeBusyRead",
    "limitedRead",
    "read",
    "write"
  ]
}

Was that another copy and paste error?

I have decided not to fix this on your behalf. Can you fix this and ping me on Teams after you have fixed this?

2021-07-17 08:07 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermission.md
> +  "tocPath": ""
Update: after noticing the other API Doctor error involving lines 81-92 and lines 94-105,
I have decided not to fix this error on your behalf.
Can you fix this one please?

2021-07-30 03:53 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +# Get List calendarPermissions
Fixed Line 10

2021-07-30 04:15 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermission.md
> +  "tocPath": ""
Added "suppressions" attribute after the "tocPath" attribute

I will double check from next items

2021-08-02 09:54 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermission.md
> +# [HTTP]
Created a new tenant and tried the example and referred the same in the document.
double checked the syntax too

2021-08-02 09:56 UTC, opbld34 commented
Docs Build status updates of commit _[b338f2c](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/b338f2ccd8aa4a78f6bd3d7b889af0bfd0afa5ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) | [Details](#user-content-5421a860d095705067b1bcf7c879da07-0f045f4f)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

<a id="5421a860d095705067b1bcf7c879da07-0f045f4f"></a>
### [api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md)
 - **Line 27, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calendar-post-calendarpermission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108020954424460-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=WY8iXdDiFA4175y0tvrHJU%2FosG6sWSAjaoZIB2Xb8S0%3D&st=2021-08-02T09%3A51%3A15Z&se=2021-09-02T09%3A56%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 04:16 UTC, opbld32 commented
Docs Build status updates of commit _[468d516](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/468d5166dcfecf6525c9feeae0408ce159e59a0f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) | [Details](#user-content-5421a860d095705067b1bcf7c879da07-f85149e3)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

<a id="5421a860d095705067b1bcf7c879da07-f85149e3"></a>
### [api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md)
 - **Line 27, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calendar-post-calendarpermission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108040415170407-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=M3FmYNW0grStBKeC2bLwCABPP1QVNRmRbJYlcPv2BL8%3D&st=2021-08-04T04%3A11%3A53Z&se=2021-09-04T04%3A16%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 04:45 UTC, opbld33 commented
Docs Build status updates of commit _[5679663](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/5679663813d0fb90dae8028c1941388a5cee457c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) | [Details](#user-content-5421a860d095705067b1bcf7c879da07-4a783f3a)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

<a id="5421a860d095705067b1bcf7c879da07-4a783f3a"></a>
### [api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md)
 - **Line 27, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calendar-post-calendarpermission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108040440054925-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6Gb2Gt3h9B2c1HicYABmQj3efWA4XtlmhjPKo75EyrI%3D&st=2021-08-04T04%3A40%3A21Z&se=2021-09-04T04%3A45%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 11:22 UTC, opbld31 commented
Docs Build status updates of commit _[51d6301](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/51d63019ef5cb2446357f649812d81727a50e032)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) | [Details](#user-content-5421a860d095705067b1bcf7c879da07-deccbcd7)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

<a id="5421a860d095705067b1bcf7c879da07-deccbcd7"></a>
### [api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md)
 - **Line 27, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/calendar-post-calendarpermission.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051120138798-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=uzL7eWBqmBQdO2CiioxfAXHQFFnFxwLXskQo3lvCrOw%3D&st=2021-08-05T11%3A17%3A48Z&se=2021-09-05T11%3A22%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 11:41 UTC, opbld33 commented
Docs Build status updates of commit _[52e362e](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/52e362eb24756b1c89966cca6b45c02d63cf6cb7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) | [Details](#user-content-a38695539fc3e6ad16be8d8e4eaeba12-ddd58982)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

<a id="a38695539fc3e6ad16be8d8e4eaeba12-ddd58982"></a>
### [api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md)
 - **Line 64, Column 93**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/calendarpermissions.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051138402884-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qLpehUGOEyoU%2B0aeUkzLVX5Kn5i%2BB6M83Yl64wykIjw%3D&st=2021-08-05T11%3A36%3A05Z&se=2021-09-05T11%3A41%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 11:52 UTC, opbld32 commented
Docs Build status updates of commit _[32b3ef7](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/32b3ef7232693eaea0f6799eac804de176b60d16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051149474274-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=s%2BWD%2BORPzWvIRZWf5DUDh5zfV%2BsXLBbD6cJIsMkDJDA%3D&st=2021-08-05T11%3A47%3A08Z&se=2021-09-05T11%3A52%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 06:00 UTC, opbld32 commented
Docs Build status updates of commit _[6dc52ec](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/6dc52ec4e7c863e5beb91f05af63247e031cdda2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060558470236-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=jsNDg2Xsfj3zMaZc7JthjsCtuuKf4vPftqNm3nkd4PA%3D&st=2021-08-06T05%3A55%3A19Z&se=2021-09-06T06%3A00%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 07:02 UTC, opbld32 commented
Docs Build status updates of commit _[66b838e](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/66b838e278ff7ea97bc670d759d30f0578579e14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060659504521-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LRtCQhNLLdNq9KjpxyFR7dPzrhlQtyp48izU8ao99cM%3D&st=2021-08-06T06%3A57%3A25Z&se=2021-09-06T07%3A02%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 07:09 UTC, opbld34 commented
Docs Build status updates of commit _[7c7bf99](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/7c7bf99a13a7fd2e97ea581890b65d5e5d1578c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060707122527-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=q6CEvhwz2vyryt%2BLyZvM2AaDLjL3Jn9%2BCH2el6H350w%3D&st=2021-08-06T07%3A04%3A34Z&se=2021-09-06T07%3A09%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 08:41 UTC, opbld31 commented
Docs Build status updates of commit _[f3db62f](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/f3db62faeb05df30f3f6b2c739192de7fd60e0bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060839350208-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=3zB6bwllGpqeQ4ePaL3X2GoYwrDeNdYFceeJ872%2FIMQ%3D&st=2021-08-06T08%3A36%3A06Z&se=2021-09-06T08%3A41%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 08:49 UTC, opbld31 commented
Docs Build status updates of commit _[57cef03](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/57cef039a9132211cd7bd157ea4d39714915d99e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060847062156-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LOYchMWgQmN9lrPBYOjCSTOX%2FAFBCK2HBc6oXdmG6z0%3D&st=2021-08-06T08%3A44%3A31Z&se=2021-09-06T08%3A49%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 08:53 UTC, opbld32 commented
Docs Build status updates of commit _[8d5d0fa](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/8d5d0fa2dc039f110a34978725a4d7754bfebb41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060850419902-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=SaVtHw4Jwi%2FGvlLG2dt5wBro157xbv6OcZ6Us2waC3A%3D&st=2021-08-06T08%3A48%3A09Z&se=2021-09-06T08%3A53%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 09:04 UTC, opbld31 commented
Docs Build status updates of commit _[ffa8378](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/ffa837829c29846422700f49558325100ba71b0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108060901301337-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=QwN4P5yhrtH%2B1ZHnrB4%2FTccFr8gvE5TsWwVjjBkBnTU%3D&st=2021-08-06T08%3A59%3A07Z&se=2021-09-06T09%3A04%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 11:48 UTC, opbld33 commented
Docs Build status updates of commit _[b9154c7](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/b9154c7b4d2b2cfe16f0abd2ae62ca788512b6b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-a16dd0b64f5197b1fa0e15ef70a01e22-9f74e667)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-9f74e667)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="a16dd0b64f5197b1fa0e15ef70a01e22-9f74e667"></a>
### [api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

<a id="861433945d7031875447f7d9797401fb-9f74e667"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108061146424484-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9JOs6rurDv0yhTTODuHKJmQrji9vNbYpiTvKluKurKU%3D&st=2021-08-06T11%3A43%3A11Z&se=2021-09-06T11%3A48%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-07 06:39 UTC, opbld32 commented
Docs Build status updates of commit _[81bd991](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/81bd9919303a21b178ae64eff06561f166d75eb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-a16dd0b64f5197b1fa0e15ef70a01e22-13f6db3d)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-13f6db3d)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="a16dd0b64f5197b1fa0e15ef70a01e22-13f6db3d"></a>
### [api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

<a id="861433945d7031875447f7d9797401fb-13f6db3d"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108070638012208-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=G8c9s1c5OZPR95DWLga%2ByDyyC3C%2BRToNYnIFrlYt80k%3D&st=2021-08-07T06%3A34%3A34Z&se=2021-09-07T06%3A39%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-07 07:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/calendarpermission.md
> +| [List](../api/calendar-list-calendarpermissions.md) | [calendarPermission](calendarpermission.md) | List calendarPermission object. |
Line 26:
In general, it's a good idea to keep the description of a method in the Methods table the same as the description in the corresponding topic.
In this case, other than the description in the Methods table is different from the corresponding list operation topic, this description is actually incorrect. Whenever you do a "list" operation, you are getting a collection, not a single object.
I'm going to fix this to try help us wrap up this marathon review.

2021-08-07 07:23 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +Gets a collection of calendarPermission (../resources/calendarpermission.md) objects that describe the identity and roles of users with whom the specified calendar has been shared or delegated. Here,
Line 14:
This is not the way to format a link in MD: calendarPermission (../resources/calendarpermission.md)
In general, please remember to review your topics on the staging site. You need to do that to catch formatting errors of all types. More importantly, reading it on the staging site without the distractions of MD formatting elements lets you put yourself in the customer's shoes and experience how well the topic is explaining ideas.

I'm going to fix this link on your behalf to try to wrap up the marathon review.

2021-08-07 07:32 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +GET https://graph.microsoft.com/beta/users/{id}/calendar/
Line 76:
This is not an example of the operation you're documenting.
If you compare the syntax in line 76 to each of the 3 syntax lines you listed under the "HTTP request" section, do you find this line matching any of the 3?
I think I commented on this before - you must learn to provide the correct example in Graph Explorer! For this reason, please figure this out and correct the example.

2021-08-07 07:34 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +```
Lines 79-93:
This is a list operation. List operations are "GET" which doesn't take a request body.
I also think I commented on this before. Please fix the example.

2021-08-07 07:42 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +
The next issue is also something I commented on before, and we even talked about it in our 2-hour meeting on 7/20.
Whenever you create a brand new example, DO NOT insert these lines:
Line 69
Lines 96-112

For line 75: 
Do ```http instead.


See the "note" in this section: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets?anchor=enabling-auto-generation-of-code-snippets

2021-08-07 07:44 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +} -->
After line 123, you need to add another line that indicates the response is a collection.
So line 123 and the new line will look like this:

"@odata.type": "microsoft.graph.calendarPermission",
"isCollection": true

2021-08-07 07:54 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +If successful, this method returns a `200 OK` response code and the requested [calendarPermission](../resources/calendarpermission.md) object in the response body.
Line 61:
Saying "...the requested [calendarPermission](../resources/calendarpermission.md) object" is misleading.
Unlike the calendarpermission-get.md which specifies an id value in the request, the "list" operation gets all the calendarPermission objects for a specified calendar.

The correct wording for line 61 is "... and a collection of [calendarPermission](../resources/calendarpermission.md) objects in the response body."

Please make this fix, I hope by doing so, you'll remember this for the future.

2021-08-07 07:58 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +```
Lines 131-143:
We talked about this before in GitHub comments, and in our meeting on 7/20.
This is a "list" operation, the syntax of the response should show a collection, not a single instance, of calendarPermission.
Can you also please make sure you run your examples in Graph Explorer before adding them into the docs?

2021-08-07 07:59 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +ms.prod: "outlook"
Line 5:
Were you going to update the author line to harini84 for all these topics? 
Please do so.

2021-08-07 08:00 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +
Please take a look at the beta topic and apply the similar fixes in this v1 topic.

2021-08-07 08:09 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +Create a calendarPermissions resource (../resources/calendarpermissions.md) to specify the identity and role of the user with whom the specified calendar is being shared or delegated.
Line 14:
Same issue with the link. 
Please make sure you check your topics on the staging site before submitting them for review.
I'll fix this on your behalf this time.

2021-08-07 08:16 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +
Line 60:
Remember - the resource name is "calendarPermission", not "calendarPermissions".
I'll make this fix on your behalf, so that we won't be spending more cycles on careless mistakes like this.

2021-08-07 08:17 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +If successful, this method returns a `200 OK` response code and a calendarPermissions object[calendarPermissions](../resources/calendarpermission.md) object in the response body.
Line 64:
I have to have you fix this sentence.
Like I commented before and we talked about in our 7/20 meeting, please, read your topics carefully.

2021-08-07 08:18 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +
Where is the request body in the example?

2021-08-07 08:23 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +POST https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions
In line 79:
Instead of using the {id} placeholder, can you replace {id} by 458d4c95-124e-49da-ba9d-1dd0387e682e?

Also, after line 74, add the following line:
"sampleKeys": ["458d4c95-124e-49da-ba9d-1dd0387e682e"],

You can find more info about sampleKeys in this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-08-07 08:26 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('458d4c95-124e-49da-ba9d-1dd0387e682e')/calendar/calendarPermissions",
Lines 100-132:
This example response is returning a collection (the square brackets denote a collection).
A "create" operation like this one returns a single instance of a resource, not a collection.

Like I commented before and we talked about in the 7/20 meeting, can you please make sure you run your examples in Graph Explorer before copying them to a topic?

2021-08-07 08:27 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-post-calendarpermissions.md
> +
Please see the beta topic and apply the same fixes.

2021-08-07 08:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/event.md
> +|originalStart|DateTimeOffset|The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. Only occurrences and exceptions of a series has a value for orig
Line 137:
@Swathi-Birlangi , in general, when you add content to existing documentation, you need to pay attention to the flow of the paragraph(s) before and after.
In this case, the original description has two sentence. The second sentence is an example that illustrates the idea in the first sentence. Therefore, you shouldn't have inserted your sentence in between the two.

2021-08-07 09:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/event.md
> +|originalStart|DateTimeOffset|The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. Only occurrences and exceptions of a series has a value for orig
That being said, the original description was insufficient - neither of the original two sentences described what originalStart represents.
I would suggest this description:
"Represents the start time of an event when it is initially created as an occurrence or exception in a recurring series. This property is not returned for events that are single instances. Its date and time information is expressed in ISO 8601 format and is always in UTC. For example, midnight UTC on Jan 1, 2014 is `2014-01-01T00:00:00Z`."

You might want to request @Harini84 to review this before making the change.

2021-08-07 09:22 UTC, opbld32 commented
Docs Build status updates of commit _[438a188](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/438a1885459e4efe8d7642233c663996eed6e558)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-0a76d18a4a58ea11b48e360f54522fcf-10d08455)
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-a16dd0b64f5197b1fa0e15ef70a01e22-10d08455)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-10d08455)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="0a76d18a4a58ea11b48e360f54522fcf-10d08455"></a>
### [api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md)
 - **Line 14, Column 10**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/calendarpermissions.md'.`````

<a id="a16dd0b64f5197b1fa0e15ef70a01e22-10d08455"></a>
### [api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

<a id="861433945d7031875447f7d9797401fb-10d08455"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108070921009518-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2B387MgG [...]

2021-08-07 09:30 UTC, opbld33 commented
Docs Build status updates of commit _[c690909](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/c6909093eb1efe8326e5c153c5008314ee8836f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-a16dd0b64f5197b1fa0e15ef70a01e22-75aebd00)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-75aebd00)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="a16dd0b64f5197b1fa0e15ef70a01e22-75aebd00"></a>
### [api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

<a id="861433945d7031875447f7d9797401fb-75aebd00"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108070929240072-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=VmCpafvn688FOpy403TtqstLWO03fgLxEaYkhrbMHHM%3D&st=2021-08-07T09%3A25%3A53Z&se=2021-09-07T09%3A30%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href [...]

2021-08-07 09:41 UTC, angelgolfer-ms requested changes
@Swathi-Birlangi , thanks for fixing a few items from previous reviews.
To help reduce the time we both spend on iterating these topics, I tried to fix some issues on your behalf. I called out these fixes as comments. Please take a look.
I also added the list and create operations to the TOC in v1 and beta. Please take a look at my commit so that in the future, you can update TOCs as appropriate.
There are however a few remaining issues in the "Response" and "Examples" sections.
Particularly for the remaining issues in the Examples section, I have commented the same ones before in this PR, and we also talked about them in our 7/20 meeting. Please address those issues.

In general, please make sure you read your topics carefully on the staging site before submitting them for content review. There are still mangled sentences and poorly formatted links which you would have noticed if you had reviewed your topics carefully on the staging site.

Same for examples - please make sure you run them in Graph Explorer. You still have examples with irrelevant example request, request body, or response body, which you would have caught if you had looked at the request carefully and tried the example in Graph Explorer.

Please fix the commented issues, look for similar issues **in the other PRs (13204 and 13129)** as well, fix them, review all the topics on the staging site, before requesting another iteration of content review. Meanwhile, let me know if you have questions!

2021-08-10 04:01 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +If successful, this method returns a `200 OK` response code and the requested [calendarPermission](../resources/calendarpermission.md) object in the response body.
Noted and changed the wording as per your suggestion.

2021-08-10 04:09 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +} -->
Added the new line

2021-08-10 04:12 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +
Ok

2021-08-11 05:37 UTC, Swathi-Birlangi commented on api-reference/beta/resources/calendarpermission.md
> +| [List](../api/calendar-list-calendarpermissions.md) | [calendarPermission](calendarpermission.md) | List calendarPermission object. |
Done

2021-08-11 05:37 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +Gets a collection of calendarPermission (../resources/calendarpermission.md) objects that describe the identity and roles of users with whom the specified calendar has been shared or delegated. Here,
Done

2021-08-11 05:37 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +
Removed tab lines

2021-08-11 05:39 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +POST https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions
replaced {id} by 458d4c95-124e-49da-ba9d-1dd0387e682e? and added sampleKeys line

2021-08-11 05:40 UTC, Swathi-Birlangi commented on api-reference/beta/resources/event.md
> +|originalStart|DateTimeOffset|The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. Only occurrences and exceptions of a series has a value for orig
Confirmed with Harini on the description addition and added the same

2021-08-11 07:39 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +GET https://graph.microsoft.com/beta/users/{id}/calendar/
Removed request body - Yes all GET operations will not have a request body

https://graph.microsoft.com/beta/users/{id}/calendar/calendarPermissions

2021-08-11 07:40 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +```
Removed request body for LIST operation

2021-08-11 07:44 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +```
Added more than instance in the response code

2021-08-11 07:44 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +ms.prod: "outlook"
Yes, updated

2021-08-11 07:47 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +Create a calendarPermissions resource (../resources/calendarpermissions.md) to specify the identity and role of the user with whom the specified calendar is being shared or delegated.
Done

2021-08-12 09:47 UTC, opbld30 commented
Docs Build status updates of commit _[2532bae](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/2532bae4000a26533c34f32b07186b2c22a0b276)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-01c5780a)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-01c5780a)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-01c5780a"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-12 09:48 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +If successful, this method returns a `200 OK` response code and a calendarPermissions object[calendarPermissions](../resources/calendarpermission.md) object in the response body.
Fixed

2021-08-12 09:48 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +
Added request body in the example

2021-08-12 09:49 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-post-calendarpermissions.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('458d4c95-124e-49da-ba9d-1dd0387e682e')/calendar/calendarPermissions",
Tried the example and updated request and response code in create calendar

2021-08-12 09:50 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendar-post-calendarpermissions.md
> +
Incorporated same changes in v1.0

2021-08-12 09:58 UTC, opbld31 commented
Docs Build status updates of commit _[4cf78af](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/4cf78afb1e09019b8a0a4a1eab766069fbc70bab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-99102958)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-99102958)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-99102958"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-12 10:51 UTC, opbld33 commented
Docs Build status updates of commit _[2619469](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/2619469e380aecb95529aa7f11833cd42adae2ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-62202cdd)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-62202cdd)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-62202cdd"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-12 15:34 UTC, opbld33 commented
Docs Build status updates of commit _[7e44791](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/7e44791fae00dcd45cec70645b7d90d199ad014e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-88d39ef1)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-88d39ef1)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-88d39ef1"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-12 15:44 UTC, opbld34 commented
Docs Build status updates of commit _[4460209](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/4460209160be8bf9c2de058239db14c354de4f1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-4d14fbd6)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-4d14fbd6)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-4d14fbd6"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-12 15:51 UTC, opbld31 commented
Docs Build status updates of commit _[423cc9a](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/423cc9ab8a009bfd0fabf8ff7f11381e3f1ccd48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-1b5a776f)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-1b5a776f)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-1b5a776f"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 03:54 UTC, opbld32 commented
Docs Build status updates of commit _[5bc8ea2](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/5bc8ea2cd58a04e0d355fde3a0160243a8685617)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-9181d27d)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-9181d27d)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-9181d27d"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 04:15 UTC, opbld33 commented
Docs Build status updates of commit _[491a0e8](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/491a0e8c0434dc75b278c30549d9af8605d80dd8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-34599d90)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-34599d90)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-34599d90"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 04:22 UTC, opbld30 commented
Docs Build status updates of commit _[45e22fe](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/45e22feb971820157e18537d9c7eb3d2cab8d799)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-0389c784)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-0389c784)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-0389c784"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 05:56 UTC, opbld30 commented
Docs Build status updates of commit _[7701452](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/770145244c7135a4c2699544732a74e4fc44b215)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-84fd8b92)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-84fd8b92)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-84fd8b92"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 06:13 UTC, opbld33 commented
Docs Build status updates of commit _[fa94dbf](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/fa94dbf7b06f2b7ca5f4327911103ce8aca32b4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-12b2dd9b)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-12b2dd9b)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-12b2dd9b"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 10:56 UTC, opbld31 commented
Docs Build status updates of commit _[7624275](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/76242753e1bf06f446ef6e265c14703c198ddddc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-218e3f07)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-218e3f07)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-218e3f07"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 13:29 UTC, opbld30 commented
Docs Build status updates of commit _[dfe0f8b](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/dfe0f8bbcb819ea408b539ef10597d16f863c31f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-2adbfabb)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-2adbfabb)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-2adbfabb"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-13 14:01 UTC, millicentachieng commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +  "@odata.type": "microsoft.graph.calendarPermissions",
This should be `microsoft.graph.calendarPermission`

2021-08-16 05:58 UTC, opbld31 commented
Docs Build status updates of commit _[a55d635](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/a55d635a6ed6745107617b94733fd211982a945a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-46005071)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | | [Details](#user-content-861433945d7031875447f7d9797401fb-46005071)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-46005071)

<a id="46005071"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'migrate-azure-ad-graph-overview.md' are still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

<a id="861433945d7031875447f7d9797401fb-46005071"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the properties of calendarpermission object.' is duplicated in 'v1.0/api/calendarpermission-get.md(3,14)', 'v1.0/api/calendarpermission-update.md(3,14)'.`````

<a id="cbaa1bd601de7c633c01b57c8fc6ed3b-46005071"></a>
### [api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Update the properties of calendarpermission object.' is duplicated in 'v1.0/api/calendarpermission-get.md(3,14)', 'v1.0/api/calendarpermission-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108160554573036-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RTmo4OM4eik4O9L5g7KbwSOMzuonIJJkKDecXODRQ5E%3D&st=2021-08-16T05%3A53%3A11Z&se=2021-09-16T05%3A58%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-21 07:39 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/event.md
> +## Properties
@Swathi-Birlangi , can you please restore the order of the H2 sections of this topic? Why were the more important "Properties" and "Methods" sections moved to after the "JSON representation" section?
This is the original order:
"Methods"
"Properties"
"Relationships"
"JSON representation"
"See also"

2021-08-21 07:42 UTC, opbld30 commented
Docs Build status updates of commit _[6007bd9](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/6007bd987cf2185bfefa1af5db825721cfea3485)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-22c65327)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-22c65327)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-22c65327"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-08-21 08:01 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-get.md
>  ---
@Swathi-Birlangi , why did you copy the contents of calendarpermission-update.md to this GET operation topic?
Based on the corresponding user story 105739, is there anything you need to change in the GET operation topic?

(Same questions for the v1.0 version of calendarpermission-get.md as well.)

2021-08-21 08:03 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendarpermission-get.md
>  ---
@Swathi-Birlangi , why did you copy the contents of calendarpermission-update.md to this GET operation topic?
Based on the corresponding user story 105739, is there anything you need to change in the GET operation topic?

(Same questions for the beta version of calendarpermission-get.md as well.)

2021-08-21 08:34 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendarpermission-update.md
> +### Requests
Line 65:
What was the reason to change this to plural? There is only one request per example. Please keep the original, singular.

2021-08-21 08:36 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendarpermission-update.md
> -# [C#](#tab/csharp)
Lines 83-100:
This is a pre-existing topic, you didn't change the examples section. Can you tell me why you deleted these lines?

2021-08-21 08:38 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-update.md
> -# [C#](#tab/csharp)
Lines 84-101:
This is a pre-existing topic, you didn't change the examples section. Can you tell me why you deleted these lines?

2021-08-21 08:40 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +Do not supply a request body for this method.
Line 67:
You don't need this line in an example request section. Please delete.

2021-08-21 08:41 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +If successful, this method returns a `200 OK` response code and a collection of calendarPermission objects in the response body.
Line 61:
Please style calendarPermission as bold.

2021-08-21 08:43 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +GET https://graph.microsoft.com/v1.0/users/{id}/calendar/calendarPermissions
Line 69:
Keep this to just http, remove the msgraph-interactive.
After you eventually get this PR merged, there's a tool that will update this to msgraph-interactive to enable the Try-it experience. Behind the scenes, the tool also needs to first get the Try-it experience ready for this example. So it's not something that authors should just set on their own; they should let the tool do it.

2021-08-21 08:50 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +```http msgraph-interactive
Line 69:
Please fix this line as commented in the v1.0 topic.

2021-08-21 08:53 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +```
Thanks. Just to clarify the previous comment before you made the fix - the response you had before was missing the square brackets which meant the response wasn't even a collection. It's acceptable to have a collection of only 1 resource; having more than 1 resource is better.

2021-08-21 09:22 UTC, angelgolfer-ms commented on api-reference/beta/api/calendarpermission-get.md
> -  "isRemovable": true,
When you restore the appropriate / original contents for calendarpermission-get.md, can you change line 117 "isRemovable": "false"?

As described in the calendarpermission.md topic, isRemovable is always "false" for "My organization" (line 115).

2021-08-21 09:25 UTC, angelgolfer-ms requested changes
Please see my latest comments.
Regarding the API Doctor error about appRoleAssignments, I am not sure where this comes from. Can you fix the other identified issues first? After eliminating those other issues, perhaps it would be clearer where appRoleAssignments is looped in.

2021-08-25 09:10 UTC, Swathi-Birlangi commented on api-reference/v1.0/resources/event.md
> +## Properties
reordered all H2 sections

2021-08-25 09:22 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendarpermission-update.md
> +### Requests
Changed to singular

2021-08-25 09:25 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +Do not supply a request body for this method.
Deleted the above line in both v1.0 and beta

2021-08-25 09:31 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +If successful, this method returns a `200 OK` response code and a collection of calendarPermission objects in the response body.
change the style to bold for calendarPermission in beta and v1.0 version

2021-08-25 09:32 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +GET https://graph.microsoft.com/v1.0/users/{id}/calendar/calendarPermissions
Removed msgraph-interactive for both v1.0 and beta version

2021-08-25 09:33 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-calendarpermissions.md
> +```http msgraph-interactive
msgraph-interactive for both v1.0 and beta version

2021-08-25 09:37 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendarpermission-get.md
> -  "isRemovable": true,
Angela: I have double checked json code for both v1.0 and beta version, I see that I have referred different example, I don't see "My Organization" in json code, please check and correct me if I am wrong

2021-08-25 09:41 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendarpermission-update.md
> -# [C#](#tab/csharp)
I realized now that I shouldn't have remove those tabs for the existing ones, I have added those lines again in both v1.0 and beta version

2021-08-25 09:54 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendarpermission-update.md
> -# [C#](#tab/csharp)
I realized now that I shouldn't have remove those tabs for the existing ones, I have added those lines again in both v1.0 and beta version

2021-08-25 10:07 UTC, opbld33 commented
Docs Build status updates of commit _[2052095](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/2052095de4ba89d985ecd55d7f14c6cfc8984e72)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-f81509a7)
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-cbaa1bd601de7c633c01b57c8fc6ed3b-f81509a7)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="861433945d7031875447f7d9797401fb-f81509a7"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update calendarpermission - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendarpermission-get.md(2,8), v1.0/api/calendarpermission-update.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update calendarPermission' is duplicated with other articles: 'v1.0/api/calendarpermission-get.md(10,1), v1.0/api/calendarpermission-update.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 3, Column 14* [...]

2021-09-08 18:21 UTC, opbld34 commented
Docs Build status updates of commit _[99ac5c7](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/99ac5c70b779bb262fd3a551086e645031c6bde6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9e6a1fd2)

<a id="9e6a1fd2"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109081820375633-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=T5NblfnHeRtFRBJiec%2BIZ3y6v61gpV9G2SZ10b5dOrM%3D&st=2021-09-08T18%3A16%3A00Z&se=2021-10-09T18%3A21%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 18:36 UTC, opbld33 commented
Docs Build status updates of commit _[a8172f9](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/a8172f95e3febc8c75bee50e0bc62341ea0ce986)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-02ec11a0)

<a id="02ec11a0"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109081835343676-13113%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=UFBlU6IwAv4tA4S1lhreahlHuDZ%2BpX0s39HC5quV6Eg%3D&st=2021-09-08T18%3A31%3A23Z&se=2021-10-09T18%3A36%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-08 18:44 UTC, millicentachieng commented
@Swathi-Birlangi As I was investigating the API Doctor error, I noticed that some beta documentation do not have the beta disclaimer.

2021-09-23 07:19 UTC, opbld30 commented
Docs Build status updates of commit _[61647ba](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/61647ba909d6e01c66571e9d3a342baf1fd7f66d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-a16dd0b64f5197b1fa0e15ef70a01e22-c5087e5e)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-c5087e5e)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="a16dd0b64f5197b1fa0e15ef70a01e22-c5087e5e"></a>
### [api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

<a id="861433945d7031875447f7d9797401fb-c5087e5e"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 3, Column 14**: **[Sugges [...]

2021-09-23 07:28 UTC, opbld31 commented
Docs Build status updates of commit _[7470692](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/747069288f222bff4fbe745bf85ae46ea95e43a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-a16dd0b64f5197b1fa0e15ef70a01e22-eef53fe4)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-eef53fe4)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="a16dd0b64f5197b1fa0e15ef70a01e22-eef53fe4"></a>
### [api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

<a id="861433945d7031875447f7d9797401fb-eef53fe4"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 3, Column 14**: **[Sugges [...]

2021-09-23 07:36 UTC, opbld32 commented
Docs Build status updates of commit _[a61eb99](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/a61eb994b2e6b2cd92ec38cb83b735e1c27d9c63)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-a16dd0b64f5197b1fa0e15ef70a01e22-784a5559)
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) | [Details](#user-content-861433945d7031875447f7d9797401fb-784a5559)
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

<a id="a16dd0b64f5197b1fa0e15ef70a01e22-784a5559"></a>
### [api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Get the properties and relationships of calendarpermission object.' is duplicated in 'v1.0/api/calendar-list-calendarpermissions.md(3,14)', 'v1.0/api/calendarpermission-get.md(3,14)'.`````

<a id="861433945d7031875447f7d9797401fb-784a5559"></a>
### [api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md)
 - **Line 3, Column 14**: **[Sugges [...]

2021-09-23 08:20 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-list-calendarpermissions.md
> +If successful, this method returns a `200 OK` response code and a collection of calendarPermission objects in the response body.
Just FYI, even though HTML <b> works in this case, the general guidance from the docs platform team is to avoid using HTML formatting in the MD files and use MD where possible.

2021-09-23 08:31 UTC, opbld33 commented
Docs Build status updates of commit _[2285355](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/22853554b8d83eaf23053512d0448d7a3a8e0bdc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109230830017797-13113%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T08%3A31%3A52Z&sr=b&sp=r&sig=DwHDixsRRj%2BY%2Bgfj%2BpTm354d4N3IPaumm2JJl%2Bog1sY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-23 08:40 UTC, opbld30 commented
Docs Build status updates of commit _[d714f64](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/d714f6444ad46369b263059daf0f789eb45cfb3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-beta&branch=pr-en-us-13113) (graph-rest-beta) |
[api-reference/v1.0/api/calendar-list-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-list-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-post-calendarpermissions.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendar-post-calendarpermissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-delete.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-delete?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-get.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-get?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendarpermission-update.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/api/calendarpermission-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendarpermission-update?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendarpermission.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/calendarpermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/beta/docsupdate/calendarPermission&originalStart/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-calendarpermissions?view=graph-rest-1.0&branch=pr-en-us-13113) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109230838514221-13113%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T08%3A40%3A35Z&sr=b&sp=r&sig=Xzc6y3pPZasHNj07ePsoW%2FIWs1fdtCwXc4pt3uIsWj0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-23 08:54 UTC, merged