[Teams] Update Teams Graph API's with RSC permissions
microsoftgraph/microsoft-graph-docs pull request #13110
Opened 2021-06-12 21:35 UTC by jessiechan27

2021-06-12 21:36 UTC, opbld34 commented
Docs Build status updates of commit _[81d509e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/81d509e263142b2b9d099e66737521320627149a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/profilephoto-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) | [Details](#user-content-61deddea09f79f7372efdf04fd701ab5-7ee8846e)
[api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/v1.0/api/chat-teamsappinstallation-upgrade.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-1.0&branch=pr-en-us-13110) (>= graph-rest-1.0) | [Details](#user-content-81469d54a0115a8112b734d3443a00e3-7ee8846e)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/a [...]

2021-06-12 21:45 UTC, AkJo commented on api-reference/beta/api/profilephoto-update.md
> +PUT /teams/{teamId}/photo/$value
Good job being thorough.

This API is broken at the moment though. Lets skip the documentation for this one, and make a note of it as a work-item to address it in the future.

2021-06-12 21:48 UTC, AkJo commented on api-reference/v1.0/api/chat-get-installedapps.md
> +|Application | TeamsAppInstallation.Read.Chat*, Chat.Manage.Chat*, TeamsAppInstallation.ReadForChat.All, TeamsAppInstallation.ReadWriteSelfForChat.All, TeamsAppInstallation.ReadWriteForChat.All
Skip the RSC documentation for the all the v1 APIs for chat. We are not releasing that yet.

2021-06-12 21:56 UTC, AkJo commented on concepts/permissions-reference.md
> +|File.Read.Group| Read this group's files. | Read this group's files, without a signed-in users. | No | No |
Lets mark this as '(Limited support)'.

2021-06-12 21:56 UTC, AkJo commented on concepts/permissions-reference.md
> +|File.Read.Group| Read this group's files. | Read this group's files, without a signed-in users. | No | No |
Read this team's files.

2021-06-12 21:59 UTC, AkJo commented on concepts/permissions-reference.md
> +|File.Read.Group| Read this group's files. | Read this group's files, without a signed-in users. | No | No |
And for all the above permissions, can you replace "this group's [blah]" to "this team's [blah]"

Skip Member.Read.Group and Owner.Read.Group because those have semantics for the group workload as well. The rest are all only supported by the Teams workload.

2021-06-12 22:32 UTC, opbld31 commented
Docs Build status updates of commit _[828e402](https://github.com/microsoftgraph/microsoft-graph-docs/commits/828e402761cd3b677528d49c7ca69f33bffe3d32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/profilephoto-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) | [Details](#user-content-61deddea09f79f7372efdf04fd701ab5-99f4b0e9)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us- [...]

2021-06-12 22:34 UTC, opbld30 commented
Docs Build status updates of commit _[6217975](https://github.com/microsoftgraph/microsoft-graph-docs/commits/621797583ab3aae59dc0c471c53c497c50139b2c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/profilephoto-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) | [Details](#user-content-61deddea09f79f7372efdf04fd701ab5-b27f8b75)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us- [...]

2021-06-12 22:41 UTC, opbld33 commented
Docs Build status updates of commit _[e7b9503](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7b9503351f0fd909158f57bc77e0bda96693ec4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/profilephoto-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) | [Details](#user-content-61deddea09f79f7372efdf04fd701ab5-b32163ab)
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us- [...]

2021-06-12 22:51 UTC, opbld31 commented
Docs Build status updates of commit _[adab9af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adab9af7208ff6ad0212a9cb462cf030b373dd2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-referenc [...]

2021-06-14 17:56 UTC, AkJo commented on api-reference/beta/api/chat-get-tabs.md
> +|Application | TeamsTab.Read.Chat*, TeamsTab.ReadWriteForChat.All, TeamsTab.Read.All, TeamsTab.ReadWrite.All |
TeamsTab.ReadWrite.Chat*

2021-06-14 18:03 UTC, AkJo commented on api-reference/beta/api/chatmessagehostedcontent-get.md
This does not apply to messages in a channel.

2021-06-14 18:09 UTC, AkJo commented on api-reference/v1.0/api/chat-post-members.md
> +|Application| Chat.ReadWrite.All |
ChatMember.ReadWrite.All as well

2021-06-14 18:27 UTC, AkJo approved these changes

2021-06-14 20:41 UTC, opbld34 commented
Docs Build status updates of commit _[f7d4e20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7d4e2019c9da2602ab616132d6e53206b8e9edd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/ap [...]

2021-06-15 20:34 UTC, JarbasHorst requested changes

2021-06-15 20:34 UTC, JarbasHorst commented on concepts/permissions-reference.md
> +|File.Read.Group| Read this team's files folders. | **Limited support** <br/> (Preview) Read this team's files folders, without a signed-in users. | No | No |
If an Azure AD app with the new permission "File.Read.Group" can read files and folders, I recommend you adding "and" after "files" in both sentences. Suggested revision:

"Read this team's files and folders"

2021-06-15 20:34 UTC, JarbasHorst commented on api-reference/beta/api/chat-get-installedapps.md
> +|Application | TeamsAppInstallation.Read.Chat*, Chat.Manage.Chat*, TeamsAppInstallation.ReadForChat.All, TeamsAppInstallation.ReadWriteSelfForChat.All, TeamsAppInstallation.ReadWriteForChat.All
Please, add | after "TeamsAppInstallation.ReadWriteForChat.All" to avoid markdown issues. Suggested revision:

|Application | TeamsAppInstallation.Read.Chat*, Chat.Manage.Chat*, TeamsAppInstallation.ReadForChat.All, TeamsAppInstallation.ReadWriteSelfForChat.All, TeamsAppInstallation.ReadWriteForChat.All |

2021-06-15 20:34 UTC, JarbasHorst commented on api-reference/beta/api/chat-get-members.md
> +|Application| ChatMember.Read.Chat*, Chat.Manage.Chat*, ChatMember.Read.All, ChatMember.ReadWrite.All, Chat.ReadBasic.All, Chat.Read.All, Chat.ReadWrite.All. |
Please, remove the period after Chat.ReadWrite.All

2021-06-15 20:34 UTC, JarbasHorst commented on api-reference/beta/api/chat-list-members.md
> +|Application| ChatMember.Read.Chat*, Chat.Manage.Chat*, ChatMember.Read.All, ChatMember.ReadWrite.All, Chat.ReadBasic.All, Chat.Read.All, Chat.ReadWrite.All. |
Please, remove the period after Chat.ReadWrite.All

2021-06-15 21:42 UTC, JarbasHorst commented
Hi @jessiechan27, can you please include to your PR the change log entries for all permission changes in the APIs. These changes enable new permissions scenarios which are very relevant for our customers.

2021-06-15 21:54 UTC, jessiechan27 commented
> Hi @jessiechan27, can you please include to your PR the change log entries for all permission changes in the APIs. These changes enable new permissions scenarios which are very relevant for our customers.

Hey Jarbas! Our changelogs are generated using internal tooling which do not usually include permission changes. You can give us a link or instructions on how to generate or write them if this is an issue

2021-06-15 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[f7d4e20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7d4e2019c9da2602ab616132d6e53206b8e9edd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/ap [...]

2021-06-15 21:58 UTC, opbld30 commented
Docs Build status updates of commit _[dee1679](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dee16799b717569daccce0e3c1f3cd47d367c5de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/ap [...]

2021-06-16 01:12 UTC, opbld32 commented
Docs Build status updates of commit _[3f5f5a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f5f5a384435416309ac918f32ee88da350a8577)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-484ad7e7)

<a id="484ad7e7"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160112174281-13110%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PTVsWYTIhbzY045OGzTUTGA3UCozjaWsbgFz5H42qdE%3D&st=2021-06-16T01%3A07%3A40Z&se=2021-07-17T01%3A12%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 01:14 UTC, opbld33 commented
Docs Build status updates of commit _[09aeae7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09aeae7e0c938f10717308e12beabff72333ab36)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c97265e5)

<a id="c97265e5"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160113271118-13110%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uP9kr1PPBpnUjF42CcD1ogda5dxSifFrL039wHYr2Ls%3D&st=2021-06-16T01%3A09%3A01Z&se=2021-07-17T01%3A14%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 01:15 UTC, Lauragra approved these changes

2021-06-16 01:20 UTC, opbld30 commented
Docs Build status updates of commit _[e16c2ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e16c2ee406626b182553f1b30fbc5287354d9a67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/channel-get-filesfolder.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-list-permissiongrants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-list-permissiongrants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-permissiongrants?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jecha/rsc-api-perms/api-reference/beta/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&branch=pr-en-us-13110) (graph-rest-beta) |
[api-reference/beta/ap [...]

2021-06-16 01:21 UTC, merged