Mankadnandan change notification for chat
microsoftgraph/microsoft-graph-docs pull request #13149
Opened 2021-06-16 06:37 UTC by mankadnandan

2021-06-16 06:39 UTC, opbld30 commented
Docs Build status updates of commit _[3d31088](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d31088e7638a6df625a2b1b630381b7eaaed199)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) | [Details](#user-content-72c9e8ea1d233e565e6f94fb6b38acb1-f6512da5)
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) | [Details](#user-content-934b7c1c854f6698c48080ebdae49980-f6512da5)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-f6512da5)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="72c9e8ea1d233e565e6f94fb6b38acb1-f6512da5"></a>
### [concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'nandanmankad' is not a valid GitHub ID.`````

<a id="934b7c1c854f6698c48080ebdae49980-f6512da5"></a>
### [concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'nandanmankad' is not a valid GitHub ID.`````

<a id="5a4bf723696c90353d87e6f17ef663f5-f6512da5"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It [...]

2021-06-16 06:47 UTC, opbld30 commented
Docs Build status updates of commit _[80177c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80177c8f478ae04f852f8a628b79676f4118d3e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-861dc176)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-861dc176"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-16 18:34 UTC, RamjotSingh requested changes

2021-06-16 18:34 UTC, RamjotSingh commented on concepts/teams-changenotifications-chat.md
> +author: "mankadnandan"
use RamjotSingh as the author so I can track issues.

2021-06-16 18:34 UTC, RamjotSingh commented on concepts/teams-changenotifications-chat.md
> +  "chatType": "OneOnOne",
case should be oneOnOne right? Something for u to check.

2021-06-16 18:34 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatMembership.md
> +---
You can combine chat and chat membership into one.

Or comine team channel and chat membership into one.

2021-06-17 06:10 UTC, opbld33 commented
Docs Build status updates of commit _[2c066d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c066d74206967c9ce8f0c7487ad9e3641ff2072)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-744ca09b)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-744ca09b"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-17 06:11 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +author: "mankadnandan"
Done

2021-06-17 06:12 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +  "chatType": "OneOnOne",
I checked and it gives out OneOnOne.

2021-06-17 06:15 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +---
Wouldn't it be better to keep them separate? If required I am planning to merge _teams-changenotifications-chatMembership.md_ and _teams-changenotifications-teamMembership.md_ into a single file and rename the file to be generic for teams and chat membership. Let me know if that is fine.

2021-06-18 04:59 UTC, opbld31 commented
Docs Build status updates of commit _[e05b883](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e05b88306e5cb74530711d058349db5c740eec40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-28132351)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-28132351"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-18 05:10 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +---
As discussed keeping this as it is for now.

2021-06-21 08:57 UTC, opbld34 commented
Docs Build status updates of commit _[4275ad7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4275ad7309647826c151ced9d65e3b5b7177768d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-15cdc1ad)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-15cdc1ad"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-22 06:11 UTC, RamjotSingh requested changes

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-get.md
> +|[conversationMember](../resources/conversationmember.md) (/chats/{id}/members) | ChatMember.Read, Chat.ReadBasic, Chat.Read | Not supported | ChatMember.Read.All, Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-get.md
> +|[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read | Not supported | Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-delete.md
> +|[conversationMember](../resources/conversationmember.md) (/chats/{id}/members) | ChatMember.Read, Chat.ReadBasic, Chat.Read | Not supported | ChatMember.Read.All, Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-delete.md
> +|[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read | Not supported | Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read | Not supported | Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[conversationMember](../resources/conversationmember.md) (/chats/{id}/members) | ChatMember.Read, Chat.ReadBasic, Chat.Read | Not supported | ChatMember.Read.All, Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-update.md
> +|[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read | Not supported | Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on api-reference/beta/api/subscription-update.md
> +|[conversationMember](../resources/conversationmember.md) (/chats/{id}/members) | ChatMember.Read, Chat.ReadBasic, Chat.Read | Not supported | ChatMember.Read.All, Chat.ReadBasic.All, Chat.Read.All |
Mention RSC permissions.

2021-06-22 06:11 UTC, RamjotSingh commented on concepts/teams-changenotifications-chat.md
> +|Delegated (work or school account) | Chat.ReadBasic, Chat.Read, Chat.ReadWrite | Not supported. |
Fix

2021-06-22 06:11 UTC, RamjotSingh commented on concepts/teams-changenotifications-chat.md
> +The payload looks like the following. This payload is for a create chat.
Rewrite this 2 sentences sounds very confusing.

2021-06-22 06:11 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatMembership.md
> +For notifications without resource data, the payload looks like the following. This payload is for a membership add in a chat.
Same here, rewrite.

Following payload describes the information sent in the request for notifications without resource data. This particular payload signifies that a user has been added to a chat.

2021-06-22 06:11 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatMembership.md
> +The **resource** and **@odata.id** properties can be used to make calls to Microsoft Graph to get the payload for the chat member. GET calls will always return the current state of the chat member. I
chat member details

2021-06-22 06:11 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatMembership.md
> +The **resource** and **@odata.id** properties can be used to make calls to Microsoft Graph to get the payload for the chat member. GET calls will always return the current state of the chat member. I
in both places.

2021-06-22 13:33 UTC, opbld31 commented
Docs Build status updates of commit _[0209057](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02090573cd043f6ec30eee37e8e6785ceb89f7e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-a62065f1)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-a62065f1"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-22 14:17 UTC, mankadnandan commented on api-reference/beta/api/subscription-delete.md
> +|[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read | Not supported | Chat.ReadBasic.All, Chat.Read.All |
Updated

2021-06-22 14:17 UTC, mankadnandan commented on api-reference/beta/api/subscription-get.md
> +|[conversationMember](../resources/conversationmember.md) (/chats/{id}/members) | ChatMember.Read, Chat.ReadBasic, Chat.Read | Not supported | ChatMember.Read.All, Chat.ReadBasic.All, Chat.Read.All |
Updated

2021-06-22 14:18 UTC, mankadnandan commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read | Not supported | Chat.ReadBasic.All, Chat.Read.All |
Updated

2021-06-22 14:18 UTC, mankadnandan commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[conversationMember](../resources/conversationmember.md) (/chats/{id}/members) | ChatMember.Read, Chat.ReadBasic, Chat.Read | Not supported | ChatMember.Read.All, Chat.ReadBasic.All, Chat.Read.All |
Updated

2021-06-22 14:18 UTC, mankadnandan commented on api-reference/beta/api/subscription-update.md
> +|[chat](../resources/chat.md) (/chats/{id}) | Chat.ReadBasic, Chat.Read | Not supported | Chat.ReadBasic.All, Chat.Read.All |
Updated

2021-06-22 14:18 UTC, mankadnandan commented on api-reference/beta/api/subscription-update.md
> +|[conversationMember](../resources/conversationmember.md) (/chats/{id}/members) | ChatMember.Read, Chat.ReadBasic, Chat.Read | Not supported | ChatMember.Read.All, Chat.ReadBasic.All, Chat.Read.All |
Updated

2021-06-22 14:19 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +|Delegated (work or school account) | Chat.ReadBasic, Chat.Read, Chat.ReadWrite | Not supported. |
Updated to beta

2021-06-22 14:19 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +The payload looks like the following. This payload is for a create chat.
Updated

2021-06-22 14:20 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +For notifications without resource data, the payload looks like the following. This payload is for a membership add in a chat.
Updated

2021-06-22 14:20 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +The **resource** and **@odata.id** properties can be used to make calls to Microsoft Graph to get the payload for the chat member. GET calls will always return the current state of the chat member. I
Updated

2021-06-22 18:07 UTC, RamjotSingh approved these changes

2021-06-23 07:43 UTC, anandab-msft commented
@JarbasHorst  -can you review this PR as well

2021-06-23 21:35 UTC, JarbasHorst requested changes

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chat.md
> +description: "Get change notifications for change in creation or updation of chats using Microsoft Graph"
I recommend you also rephrasing this sentence to provide the intention of this article. Suggested revision:

- Learn how to get notifications for changes (create and update) for chats using Microsoft Graph APIs.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chat.md
> +Content-Type: application/json
Please, add a new line after Content-Type: application/json

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chat.md
> +Content-Type: application/json
Please, add a new line after Content-Type: application/json

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chat.md
> +Following payload describes the information sent in the request for notifications without resource data. This particular payload signifies that a new chat has been created.
Please, add The before following.

Articles help readers and translation software identify the nouns and modifiers in a sentence.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +
Please, add an introduction to the article.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +### Subscribe to changes in membership of any chat at tenant level
The first heading within an article should be an H2, not an H3.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +#### Permissions
Please, also update "Permissions" to be H3, so the heading order is sequential.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +#### Example
Please, also update "Example" to be H3, so the heading order is sequential.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +#### Permissions
Please, also update "Permissions" to be H3, so the heading order is sequential.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +#### Example
Please, also update "Example" to be H3, so the heading order is sequential.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +### Subscribe to changes in membership of a particular chat
This heading should be H2, so the heading order is sequential.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +# Get change notifications for change in chats membership using Microsoft Graph
Make sure that the title field matches the H1.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +description: "Get change notifications for any change in Chats membership using Microsoft Graph"
Add a description that provides the intent and does not repeat the title. Suggested revision:

- Learn how to get notifications for changes for chat membership using Microsoft Graph APIs.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +title: "Get change notifications for any change in Chats membership using Microsoft Graph"
For consistency with other articles about change notifications, I recommend you rephrasing the title. Suggested revision:

- Get change notifications for chat membership using Microsoft Graph

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +To get change notifications for membership change in a any chat across tenant, subscribe to `/chats/getAllMembers`. This resource supports [including resource data](webhooks-with-resource-data.md) in
Please, replace "membership change" with "membership changes". Additionally, remove a before any.

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +Content-Type: application/json
Please, add a new line after Content-Type: application/json

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +Content-Type: application/json
Please, add a new line after Content-Type: application/json

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +To get change notifications for membership change in a particular chat, subscribe to `/chats/{id}/members`. This resource supports [including resource data](webhooks-with-resource-data.md) in the not
Please, replace "membership change" with "membership changes".

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +For notifications with resource data, the payload looks like the following. This payload is for a membership change in a team.
You say: "This payload is for a membership change in a **team**." Should that be instead "... change in a **chat**."?

2021-06-23 21:35 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +Following payload describes the information sent in the request for notifications without resource data. This particular payload signifies that a user has been added to a chat.
Please, add The before following.

Articles help readers and translation software identify the nouns and modifiers in a sentence.

2021-06-24 07:48 UTC, opbld34 commented
Docs Build status updates of commit _[b061541](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b061541b71229fb1fea1bf14683d309b1ebe6677)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-e92494e9)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-e92494e9"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-24 07:54 UTC, mankadnandan commented on api-reference/beta/resources/webhooks.md
> +| Teams [conversationMember][] | Changes to membership in a specific team:<br>`/teams/{id}/members` <br> Changes to membership in a specific chat:<br>`/chats/{id}/members` <br> Changes to membership
Done

2021-06-24 07:54 UTC, mankadnandan commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[Chat](../resources/chat.md)|`/chats`,`/chats/{id}`|
added

2021-06-24 07:54 UTC, mankadnandan commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[ConversationMember](../resources/conversationmember.md)|`/chats/{id}/members`,`/chats/getAllMembers`,`/teams/{id}/members`|
added

2021-06-24 07:54 UTC, mankadnandan commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/graph/api/resources/subscription) for change notifications to the [chat](https://docs.microsoft.
added

2021-06-24 07:55 UTC, mankadnandan commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added support for the creation of [subscriptions](https://docs.microsoft.com/graph/api/resources/subscription) for change notifications to the [conversationMember](https://d
added

2021-06-24 07:55 UTC, mankadnandan commented on api-reference/beta/resources/webhooks.md
> +| Teams [chat][] | Changes to any chat in the tenant:<br>`/chats` <br>Changes to specific chat:<br>`/chats/{id}` | Yes |
added

2021-06-24 07:55 UTC, mankadnandan commented on concepts/toc.yml
> +                  - name: Change notifications for chat
Done

2021-06-24 07:55 UTC, mankadnandan commented on concepts/toc.yml
> +                  - name: Change notifications for chat membership
Done

2021-06-24 07:56 UTC, mankadnandan commented on concepts/toc.yml
> +                  - name: Change notifications for chat
Done

2021-06-24 07:56 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +
Added

2021-06-24 07:56 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +### Subscribe to changes in any chat at tenant level
Done

2021-06-24 07:56 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +#### Permissions
Done

2021-06-24 07:56 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +#### Example
Done

2021-06-24 07:57 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +### Subscribe to changes in a particular chat
Done

2021-06-24 07:57 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +#### Permissions
Done

2021-06-24 07:57 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +#### Example
Done

2021-06-24 07:57 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +# Get change notifications for chat using Microsoft Graph
Done, please verify

2021-06-24 07:57 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +title: "Get change notifications for creation or updation of chats using Microsoft Graph"
Done

2021-06-24 07:58 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +description: "Get change notifications for change in creation or updation of chats using Microsoft Graph"
Updated

2021-06-24 08:00 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +Content-Type: application/json
Done

2021-06-24 08:00 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +Content-Type: application/json
Done

2021-06-24 08:00 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +Following payload describes the information sent in the request for notifications without resource data. This particular payload signifies that a new chat has been created.
Done

2021-06-24 08:00 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +
Done

2021-06-24 08:01 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +### Subscribe to changes in membership of any chat at tenant level
Done

2021-06-24 08:01 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +#### Permissions
Done

2021-06-24 08:02 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +#### Example
Done

2021-06-24 08:03 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +#### Permissions
Done

2021-06-24 08:03 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +#### Example
Done

2021-06-24 08:03 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +### Subscribe to changes in membership of a particular chat
Done

2021-06-24 08:17 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +Following payload describes the information sent in the request for notifications without resource data. This particular payload signifies that a user has been added to a chat.
Done

2021-06-24 08:17 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +For notifications with resource data, the payload looks like the following. This payload is for a membership change in a team.
Done

2021-06-24 08:17 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +To get change notifications for membership change in a particular chat, subscribe to `/chats/{id}/members`. This resource supports [including resource data](webhooks-with-resource-data.md) in the not
Done

2021-06-24 08:17 UTC, opbld33 commented
Docs Build status updates of commit _[3095be4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3095be402a4778bb5f905bbe03ba8d27f2e0185a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-245de981)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-245de981"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-24 08:18 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +Content-Type: application/json
Done

2021-06-24 08:18 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +Content-Type: application/json
Done

2021-06-24 08:20 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +# Get change notifications for change in chats membership using Microsoft Graph
Done

2021-06-24 08:21 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +description: "Get change notifications for any change in Chats membership using Microsoft Graph"
Done

2021-06-24 08:21 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +title: "Get change notifications for any change in Chats membership using Microsoft Graph"
Done

2021-06-24 08:24 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +To get change notifications for membership change in a any chat across tenant, subscribe to `/chats/getAllMembers`. This resource supports [including resource data](webhooks-with-resource-data.md) in
Done

2021-06-24 21:43 UTC, JarbasHorst requested changes

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chat.md
> +description: "Learn how to get notifications for changes (create and update) for chats using Microsoft Graph APIs"
Please, add a period at the end of the sentence.

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +Change notifications enable you to subscribe to changes (create and delete) in chats membership. You can get notified whenever member is added or removed in a chat. You can also get the resource data
Please, 
- add "a" before "member"
- replace "removed in a chat." with "removed from a chat."

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +description: "Learn how to get notifications for changes for chat membership using Microsoft Graph APIs"
Please, add a period at the end of the sentence.

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +  "resource": "/chats/{id}/members ",
Please, remove the empty space after "...members". Suggested revision:

- "resource": "/chats/{id}/members",

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +  "resource": "/chats/getAllMembers ",
Please, remove the empty space after "...getAllMembers". Suggested revision:

- "resource": "/chats/getAllMembers",

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chat.md
> +To get change notifications for any change in chat's property across tenant or creation of a chat in tenant, subscribe to `/chats`. This resource supports [including resource data](webhooks-with-reso
Please rephrase this sentence for simplicity. Suggested revision:

"To get change notifications for all changes (create and update) related to any chat in a tenant,..."

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chat.md
> +To get change notifications for any change in chats' property of a specific chat, subscribe to `/chats/{id}`. This resource supports [including resource data](webhooks-with-resource-data.md) in the n
Please rephrase this sentence for simplicity. Suggested revision:

"To get change notifications for all changes related to a particular chat,..."

2021-06-24 21:43 UTC, JarbasHorst commented on concepts/teams-changenotifications-chatMembership.md
> +To get change notifications for membership changes in any chat across tenant, subscribe to `/chats/getAllMembers`. This resource supports [including resource data](webhooks-with-resource-data.md) in
Please, add the after across.

2021-06-25 07:40 UTC, opbld32 commented
Docs Build status updates of commit _[acbdf35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acbdf35b0793b1082f39c173112c786d7e63b501)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-c241e60d)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-c241e60d"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +description: "Learn how to get notifications for changes (create and update) for chats using Microsoft Graph APIs"
Added

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +To get change notifications for any change in chat's property across tenant or creation of a chat in tenant, subscribe to `/chats`. This resource supports [including resource data](webhooks-with-reso
Done

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chat.md
> +To get change notifications for any change in chats' property of a specific chat, subscribe to `/chats/{id}`. This resource supports [including resource data](webhooks-with-resource-data.md) in the n
Done

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +description: "Learn how to get notifications for changes for chat membership using Microsoft Graph APIs"
Added

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +Change notifications enable you to subscribe to changes (create and delete) in chats membership. You can get notified whenever member is added or removed in a chat. You can also get the resource data
Done

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +To get change notifications for membership changes in any chat across tenant, subscribe to `/chats/getAllMembers`. This resource supports [including resource data](webhooks-with-resource-data.md) in
Added

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +  "resource": "/chats/getAllMembers ",
Done

2021-06-25 07:53 UTC, mankadnandan commented on concepts/teams-changenotifications-chatMembership.md
> +  "resource": "/chats/{id}/members ",
Done

2021-06-25 18:08 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-06-30 02:57 UTC, mankadnandan commented
@Lauragra Can you please have a look at this one?

2021-06-30 05:07 UTC, opbld34 commented
Docs Build status updates of commit _[ad20460](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad204600c40c1af0497bb9dd709ef532783a7d06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-83d87848)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-83d87848"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-07-07 06:22 UTC, opbld30 commented
Docs Build status updates of commit _[8ef340f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ef340f7a6c522d511e06bf4a8d8cb3a43fb459a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-10601981)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-10601981"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-07-08 03:56 UTC, opbld34 commented
Docs Build status updates of commit _[d5cd4e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5cd4e52f051e549ef651e727013bf53056a595b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-9253b6ab)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-9253b6ab"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-07-08 04:02 UTC, mankadnandan commented
@Lauragra A gentle reminder to prioritize the review for this.

2021-07-08 22:58 UTC, isvargasmsft requested changes
@mankadnandan would you be so kind to fix the warnings in the Build? 

By either adding the preserve-view parameter or removing the view parameter. This will be deeply appreciated.

Thanks!

2021-07-08 23:00 UTC, opbld34 commented
Docs Build status updates of commit _[e119942](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e119942940964fb9aeb366208588dc8db00c77dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-564156eb)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-564156eb"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-07-09 12:17 UTC, mankadnandan commented
@isvargasmsft The attributes which has view=graph-rest-1.0 are older ones and I don't have full context around them. So I would leave them as they are, unless you can guide me on whether to remove the view param or to add preserve-view.

The attribute being added in this PR doesn't have view param anyways, so we are good there.

Let me know your thoughts!

2021-07-09 14:46 UTC, opbld32 commented
Docs Build status updates of commit _[024e78d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/024e78dad68b72cb7c7200664b28283b15470415)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-3f456b9e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-3f456b9e"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 32, Column 48**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 33, Column 53**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/driveitem?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 34, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 35, Column 23**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/conversation?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 36, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 37, Column 11**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 38, Column 20**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 39, Column 12**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If yo [...]

2021-07-09 14:54 UTC, opbld30 commented
Docs Build status updates of commit _[94314ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94314ea5b3f559b61c82089b1ddfd6fcaeea14c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) | [Details](#user-content-5a4bf723696c90353d87e6f17ef663f5-e8fd6cb6)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |

<a id="5a4bf723696c90353d87e6f17ef663f5-e8fd6cb6"></a>
### [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md)
 - **Line 119, Column 202**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-1.0#maximum-length-of-subscription-per-resource-type. Otherwise, remove the view parameter.`````
 - **Line 158, Column 104**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 164, Column 67**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 214, Column 62**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 323, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 324, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/subscription-get?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 325, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 326, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually [...]

2021-07-09 15:01 UTC, opbld33 commented
Docs Build status updates of commit _[63b1dfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63b1dfe54b4dc9320d7285f68ee0386dd66ddd27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091459477034-13149%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A04%3A14Z&ske=2021-07-13T09%3A09%3A14Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T14%3A56%3A16Z&se=2021-08-09T15%3A01%3A16Z&sr=b&sp=r&sig=UZ6MRzzmq5%2BNfATp7k9B8%2BdFCxYewRz5GrEDDyjvv28%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 15:05 UTC, isvargasmsft approved these changes

2021-07-09 18:53 UTC, opbld32 commented
Docs Build status updates of commit _[517bb76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/517bb7681ba47117d48f8ad9f034165b5603e1f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-13149) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/teams-changenotifications-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/teams-changenotifications-chatMembership.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/teams-changenotifications-chatMembership.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmembership?branch=pr-en-us-13149) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chat?branch=pr-en-us-13149) |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mankadnandan-change-notification-for-chat/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-13149) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091851417901-13149%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A37%3A13Z&ske=2021-07-13T07%3A42%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A48%3A04Z&se=2021-08-09T18%3A53%3A04Z&sr=b&sp=r&sig=5QKET3NlUJI%2FJvtZD%2BX5%2FmoEwS9jPKWKnhxlB7Mxjtc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:56 UTC, merged