add incompatible access package and group references to entitlement management accesspackage
microsoftgraph/microsoft-graph-docs pull request #13187
Opened 2021-06-18 16:28 UTC by markwahl-msft

2021-06-18 16:30 UTC, opbld32 commented
Docs Build status updates of commit _[95efeec](https://github.com/markwahl-msft/microsoft-graph-docs/commits/95efeecf0a31a9f8e52c2b9854b9ab720b0206dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181628253518-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JRIm3sHXWqfn1RPWiw47buE5aZ0fnYn%2F1fgwFH9Gw4c%3D&st=2021-06-18T16%3A25%3A13Z&se=2021-07-19T16%3A30%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 16:44 UTC, opbld34 commented
Docs Build status updates of commit _[6ff1b80](https://github.com/markwahl-msft/microsoft-graph-docs/commits/6ff1b805eb591e5076fb4160c59aba4a556ceec3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181639165164-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P%2BHXQBBpmE9K4TEr7ur9%2FAXBIFW3LtzF128lBIyo4N0%3D&st=2021-06-18T16%3A39%3A39Z&se=2021-07-19T16%3A44%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-25 00:14 UTC, opbld33 commented
Docs Build status updates of commit _[b565b1d](https://github.com/markwahl-msft/microsoft-graph-docs/commits/b565b1d4c65e4f48f941aab05ae38348c98e3b99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106250013085081-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iCGgUQx%2B5Wg7aOtBrSDIf0x00N6DjJqJdnOHN%2FDQbyA%3D&st=2021-06-25T00%3A09%3A33Z&se=2021-07-26T00%3A14%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 17:28 UTC, opbld32 commented
Docs Build status updates of commit _[e48f951](https://github.com/markwahl-msft/microsoft-graph-docs/commits/e48f95168147e89e016ea13032b0f7a41d2ef0bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106291727127504-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cZLOxpJgycPs5ysFb%2FBFSdaSYBP2W58Enplm4dWwVlI%3D&st=2021-06-29T17%3A23%3A42Z&se=2021-07-30T17%3A28%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 20:24 UTC, opbld32 commented
Docs Build status updates of commit _[42b5f23](https://github.com/markwahl-msft/microsoft-graph-docs/commits/42b5f23873ed715db7382574db189f68fe0496bf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fcecae82)

<a id="fcecae82"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292023255346-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qP43HNjgAoR1aBIGY%2BqeAIITrd0PIhLbBu6W09X%2BfGQ%3D&st=2021-06-29T20%3A19%3A14Z&se=2021-07-30T20%3A24%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 20:31 UTC, opbld32 commented
Docs Build status updates of commit _[890ab4a](https://github.com/markwahl-msft/microsoft-graph-docs/commits/890ab4a296042e56c929e15b8f50056c67feb899)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c3246fb3)

<a id="c3246fb3"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292031213556-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yb9117SVPakQtfUOGXeB0DREcjya15gZqA52tOdpGow%3D&st=2021-06-29T20%3A26%3A40Z&se=2021-07-30T20%3A31%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 20:41 UTC, opbld32 commented
Docs Build status updates of commit _[cc2f2ea](https://github.com/markwahl-msft/microsoft-graph-docs/commits/cc2f2eacd7008882efc38da3791919e483e4427a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) | [Details](#user-content-233fa7c4f80e8e3e54e49ef2e3aec8e6-2bdf2cb4)
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="233fa7c4f80e8e3e54e49ef2e3aec8e6-2bdf2cb4"></a>
### [api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md)
 - **Line 33, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackage-list-incompatiblegroupss.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292039415149-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BRn6lyRd6nPuTVtXO4%2FDmzXSWoZJh4UmxcGZuVjk25o%3D&st=2021-06-29T20%3A36%3A15Z&se=2021-07-30T20%3A41%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 20:43 UTC, opbld34 commented
Docs Build status updates of commit _[b61d906](https://github.com/markwahl-msft/microsoft-graph-docs/commits/b61d90674ebb8892390d4c1bef7524fd1299c342)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) | [Details](#user-content-233fa7c4f80e8e3e54e49ef2e3aec8e6-72c5e249)
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |

<a id="233fa7c4f80e8e3e54e49ef2e3aec8e6-72c5e249"></a>
### [api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md)
 - **Line 33, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accesspackage-list-incompatiblegroupss.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292040502255-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rzpiiFyqI1BAeSbvrc5T6fb19bwpufGO42PjfOBIE9M%3D&st=2021-06-29T20%3A38%3A00Z&se=2021-07-30T20%3A43%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 21:07 UTC, opbld30 commented
Docs Build status updates of commit _[7e7b81e](https://github.com/markwahl-msft/microsoft-graph-docs/commits/7e7b81ee67c790fc38643fecc2e0dffa60e00e22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292105401704-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9nxGJ8nrQwkN3LQUCUDIIjHK94yyCx9pPS%2FY9Y2XNXg%3D&st=2021-06-29T21%3A02%3A11Z&se=2021-07-30T21%3A07%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 21:57 UTC, opbld30 commented
Docs Build status updates of commit _[6311105](https://github.com/markwahl-msft/microsoft-graph-docs/commits/63111052a76d7192ed8f66a77774f39e1b0a974c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292156030054-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=R1TMvEPDeSjqmAFZ1%2BVGCgqyLaSe6xFODFokubGx5ak%3D&st=2021-06-29T21%3A52%3A45Z&se=2021-07-30T21%3A57%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 23:28 UTC, opbld33 commented
Docs Build status updates of commit _[ba8fce3](https://github.com/markwahl-msft/microsoft-graph-docs/commits/ba8fce363faadc2701de377e6d07bb8b999c8bd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292327228054-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v1u0TVklSqFHbFCcOZQnHjsGV5BpSf5iojwsWgaC1KM%3D&st=2021-06-29T23%3A23%3A50Z&se=2021-07-30T23%3A28%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 23:50 UTC, opbld30 commented
Docs Build status updates of commit _[902b1a0](https://github.com/markwahl-msft/microsoft-graph-docs/commits/902b1a031c631f53917e0839120d0eb5c756ee6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292349204829-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k4pqqVCa%2FkGqkpxGa2FGFe6nGvAw8lL2CuHdcNGoUq0%3D&st=2021-06-29T23%3A45%3A51Z&se=2021-07-30T23%3A50%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 00:04 UTC, opbld34 commented
Docs Build status updates of commit _[483d60c](https://github.com/markwahl-msft/microsoft-graph-docs/commits/483d60caf79ba0468ef175235e5479f8094737f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106300003241943-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s1DueNjONEhTQLS8IiBxFd2GUStqAG64yg82hGXq820%3D&st=2021-06-29T23%3A59%3A44Z&se=2021-07-31T00%3A04%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 23:30 UTC, opbld30 commented
Docs Build status updates of commit _[5ddb129](https://github.com/markwahl-msft/microsoft-graph-docs/commits/5ddb1296352c6ed4398621eb4e006377b41f2eaa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106302328429124-13187%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BhE96jqyf6DC3oidvTpr6KBEdse2kK7FBCP8MUOna70%3D&st=2021-06-30T23%3A25%3A14Z&se=2021-07-31T23%3A30%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-01 14:09 UTC, markwahl-msft commented
CSDL is merged

2021-07-08 08:02 UTC, FaithOmbongi requested changes

2021-07-08 08:02 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Target": "accesspackage"
```suggestion
              "Target": "accessPackage"
```

2021-07-08 08:02 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Target": "accesspackage"
```suggestion
              "Target": "accessPackage"
```

2021-07-08 08:02 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +              "Target": "accesspackage"
```suggestion
              "Target": "accessPackage"
```

2021-07-08 14:57 UTC, opbld30 commented
Docs Build status updates of commit _[dc635d3](https://github.com/markwahl-msft/microsoft-graph-docs/commits/dc635d3bdc9df1e246085fa342141a764ebfec71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081455384345-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-07T21%3A29%3A33Z&ske=2021-07-14T21%3A34%3A33Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T14%3A52%3A14Z&se=2021-08-08T14%3A57%3A14Z&sr=b&sp=r&sig=6Fh40%2FaWHRxWglZoyYwm43t9qwf4%2FhZevPERUCXVdA4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 15:12 UTC, opbld30 commented
Docs Build status updates of commit _[28798dc](https://github.com/markwahl-msft/microsoft-graph-docs/commits/28798dc8a9a648c76a7d6f0c93bc572738dee9a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081510329072-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-07T22%3A59%3A39Z&ske=2021-07-14T23%3A04%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T15%3A07%3A05Z&se=2021-08-08T15%3A12%3A05Z&sr=b&sp=r&sig=ZDpd9p2ZKBmjO51YH7Pnvo6QR7KHqsDlrn022G%2B7pUs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 15:26 UTC, opbld31 commented
Docs Build status updates of commit _[376b2b8](https://github.com/markwahl-msft/microsoft-graph-docs/commits/376b2b83ebfa97d3965080221b30d25c93f54685)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081525096622-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A59%3A36Z&ske=2021-07-13T08%3A04%3A36Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T15%3A21%3A36Z&se=2021-08-08T15%3A26%3A36Z&sr=b&sp=r&sig=JUf%2FYBADgBM8f%2BChrcj7PzR5bon3oD3f0R7enag7sKU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 15:32 UTC, opbld30 commented
Docs Build status updates of commit _[a2cdc24](https://github.com/markwahl-msft/microsoft-graph-docs/commits/a2cdc2430795c75c74c2cc42db9b0d0b18bec0f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081530479450-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A50%3A03Z&ske=2021-07-13T07%3A55%3A03Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T15%3A27%3A06Z&se=2021-08-08T15%3A32%3A06Z&sr=b&sp=r&sig=0y074Gz1DZMlIAJqeCbKx7bI0Ue6iiUa5oJOiHtURVE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 15:33 UTC, opbld32 commented
Docs Build status updates of commit _[e3daf6e](https://github.com/markwahl-msft/microsoft-graph-docs/commits/e3daf6e0d77eb1ff971b175a187b5bd9aad236c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081531166460-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A28%3A08Z&ske=2021-07-13T07%3A33%3A08Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T15%3A28%3A56Z&se=2021-08-08T15%3A33%3A56Z&sr=b&sp=r&sig=JQZMkHzii2HgqerwNnraJQ5b7p%2F9ZHGzR6hKZ70FOM0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 15:35 UTC, opbld31 commented
Docs Build status updates of commit _[e3daf6e](https://github.com/markwahl-msft/microsoft-graph-docs/commits/e3daf6e0d77eb1ff971b175a187b5bd9aad236c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081531060575-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A04%3A14Z&ske=2021-07-13T09%3A09%3A14Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T15%3A30%3A25Z&se=2021-08-08T15%3A35%3A25Z&sr=b&sp=r&sig=Bzhww1V3YFQc945HxkTQ%2FsOpcUMzMSB1ScdbA5aTkPM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 15:36 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Updated, thanks.

2021-07-08 15:36 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackage.md
>  | [Create accessPackageResourceRoleScope](../api/accesspackage-post-accesspackageresourcerolescopes.md) |None | Create a new **accessPackageResourceRoleScope** object for this access package. |
Adding them, thanks.

2021-07-08 15:36 UTC, opbld32 commented
Docs Build status updates of commit _[b76d080](https://github.com/markwahl-msft/microsoft-graph-docs/commits/b76d08039e76ca34a5a5a088a80ece89f9e1f962)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081535186316-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A02%3A24Z&ske=2021-07-13T07%3A07%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T15%3A31%3A57Z&se=2021-08-08T15%3A36%3A57Z&sr=b&sp=r&sig=IwTI7nEqpHPah0VjAbGzGwGWR6x6k41wRuQZP%2FdPJWo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 03:37 UTC, Lauragra commented on api-reference/beta/api/accesspackage-delete-incompatiblegroup.md
> +title: "Remove incompatibleGroup"
The CSDL for this nav property includes ContainsTarget = true, which means that the contained resources specified by this property are also deleted; therefore, this should be "Delete" instead of "Remove". Also, it isn't standard to use a nav property name in a Delete topic; the title should be Delete group. See the guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22

2021-07-09 03:38 UTC, Lauragra commented on api-reference/beta/api/accesspackage-delete-incompatiblegroup.md
> +> **Note:** The response object shown here might be shortened for readability.
Remove this note when there is no response body.

2021-07-09 03:38 UTC, Lauragra commented on api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md
> +> **Note:** The response object shown here might be shortened for readability.
Remove this note.

2021-07-09 03:41 UTC, Lauragra commented on api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md
> +# Remove incompatibleAccessPackage
Per the file naming guidelines this title would be "Remove accessPackage". For delete topics, we use the resource name, not the nav property name.

2021-07-09 03:46 UTC, opbld31 commented
Docs Build status updates of commit _[da23406](https://github.com/markwahl-msft/microsoft-graph-docs/commits/da2340669d4df15f4acee0fe1f35cf0315f835b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107090344319795-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T22%3A53%3A24Z&ske=2021-07-13T22%3A58%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T03%3A41%3A11Z&se=2021-08-09T03%3A46%3A11Z&sr=b&sp=r&sig=q7Qrp2J0HgAk0mSWB%2Bb1CNkyUhO3iTc3bIDh7igVdmo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 03:46 UTC, Lauragra commented on api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md
> +# Add incompatibleAccessPackage
Technically for POST operations we use the resource name in the title, so this would be "Add accessPackage".

2021-07-09 03:49 UTC, opbld33 commented
Docs Build status updates of commit _[39de2ff](https://github.com/markwahl-msft/microsoft-graph-docs/commits/39de2ff1b4d587dd3ba3b178c582041a2479147d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107090347431834-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A37%3A13Z&ske=2021-07-13T07%3A42%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T03%3A44%3A09Z&se=2021-08-09T03%3A49%3A09Z&sr=b&sp=r&sig=Me8giRgxPjietfWftkm8AfE8h1G8F2ZyEYi7Fei1Vhg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 04:00 UTC, Lauragra commented on api-reference/beta/api/accesspackage-post-incompatiblegroup.md
> +# Add incompatibleGroup
Because for this nav prooperty, ContainsTarget = true, the title here should be "Add group". Probably we can further qualify as "Add group to incompatibleGroups".

2021-07-09 04:02 UTC, Lauragra commented on api-reference/beta/resources/accesspackage.md
> +| [List incompatibleAccessPackages](../api/accesspackage-list-incompatibleaccesspackages.md) | [accessPackage](accesspackage.md) collection | Retrieve a list of the incompatible **accesspackage** obj
Make sure when you update the titles that the changes are reflected here as well.

2021-07-09 04:03 UTC, opbld32 commented
Docs Build status updates of commit _[4937f35](https://github.com/markwahl-msft/microsoft-graph-docs/commits/4937f3566150781ad8f9d88f3ce139c26fb9e07c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107090402007084-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-08T02%3A28%3A11Z&ske=2021-07-15T02%3A33%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T03%3A58%3A29Z&se=2021-08-09T04%3A03%3A29Z&sr=b&sp=r&sig=5nCE%2BiFYNUBkpk7wG3UlUimgWtA2fYpxnVGSsbAbFj8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:49 UTC, opbld31 commented
Docs Build status updates of commit _[ea1e7ef](https://github.com/markwahl-msft/microsoft-graph-docs/commits/ea1e7efce1387c340084c07bc1fa7e103aac8b00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091848244887-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-09T02%3A24%3A21Z&ske=2021-07-16T02%3A29%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A44%3A55Z&se=2021-08-09T18%3A49%3A55Z&sr=b&sp=r&sig=uk5UmMK6N3y0KEIr%2F7WJS1JdYtmLEI321N6yZjvH0hk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:51 UTC, opbld34 commented
Docs Build status updates of commit _[1689aed](https://github.com/markwahl-msft/microsoft-graph-docs/commits/1689aedcf45738b0c59a12acb55d6d395fce79d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091848407331-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A57%3A11Z&ske=2021-07-13T08%3A02%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A46%3A35Z&se=2021-08-09T18%3A51%3A35Z&sr=b&sp=r&sig=TrTmf4%2Bf%2B0NVSkLzoKRgRRl3Gf3ENTs2AI9dn%2FpvEGE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[dc02dbb](https://github.com/markwahl-msft/microsoft-graph-docs/commits/dc02dbb8d773e5b8b96b915397b9cbcf013a9a8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091850138663-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-09T02%3A24%3A21Z&ske=2021-07-16T02%3A29%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A48%3A15Z&se=2021-08-09T18%3A53%3A15Z&sr=b&sp=r&sig=oxmT0h96ny%2FZRKJPO12By6FNKBHq4wiLUKqMwZhkSm8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 21:34 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-delete-incompatiblegroup.md
> +title: "Remove incompatibleGroup"
The engineers explained to me that this use of ContainsTarget is a necessary workaround due to an issue in AGS, and that the semantics are "Remove".  Once that issue in AGS is resolved then ContainsTarget will not be used for that property.

2021-07-09 21:38 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md
> +# Remove incompatibleAccessPackage
I was looking at the title of group-delete-owners which is "Remove owner" rather than "Remove directoryObject from owner".  "Remove owner" is also in the example at the end of https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22 .

2021-07-09 21:47 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md
> +# Add incompatibleAccessPackage
I was going by the example group-post-owners which was "add group owner" instead of "add directoryobject to owner".  directoryobject is the type of group members or owners but I didn't see that as a resource name used in Group's API titles, instead it was using the property name?

2021-07-09 21:49 UTC, opbld32 commented
Docs Build status updates of commit _[6ef9a2a](https://github.com/markwahl-msft/microsoft-graph-docs/commits/6ef9a2a0563b3ff7f97063c5c2115555ec0f7068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107092147564613-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A26%3A28Z&ske=2021-07-13T08%3A31%3A28Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T21%3A44%3A29Z&se=2021-08-09T21%3A49%3A29Z&sr=b&sp=r&sig=6l%2BiwXltaDzVq5izEFx3Xw%2FvBZPqp9OyF5nBH4fZ5Ps%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 22:46 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-delete-incompatiblegroup.md
> +> **Note:** The response object shown here might be shortened for readability.
Updated, thanks

2021-07-09 22:46 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md
> +> **Note:** The response object shown here might be shortened for readability.
Updated, thanks

2021-07-09 23:17 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-post-incompatiblegroup.md
> +# Add incompatibleGroup
The ContainsTarget is due to a AGS limitation rather than the use case for this field.

2021-07-09 23:23 UTC, opbld34 commented
Docs Build status updates of commit _[f3d977a](https://github.com/markwahl-msft/microsoft-graph-docs/commits/f3d977ac5c422b5e42e0a035bd3fc8400c2e3909)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107092321421156-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A08%3A42Z&ske=2021-07-13T09%3A13%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T23%3A18%3A15Z&se=2021-08-09T23%3A23%3A15Z&sr=b&sp=r&sig=D50Ur8No2Vb%2FmOMcJ3Ai%2F0CulLPFHa17VTSo2nUcbvs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-10 00:01 UTC, opbld32 commented
Docs Build status updates of commit _[e2bedff](https://github.com/markwahl-msft/microsoft-graph-docs/commits/e2bedff0ea3f2dd5f0429208296c3c32088279d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107092359154288-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A08%3A42Z&ske=2021-07-13T09%3A13%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T23%3A56%3A05Z&se=2021-08-10T00%3A01%3A05Z&sr=b&sp=r&sig=OebOcRjzOW3IXjysY%2FOGfiQAmZW0cxbye2EOvJpF3hk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-10 00:03 UTC, opbld34 commented
Docs Build status updates of commit _[82590c1](https://github.com/markwahl-msft/microsoft-graph-docs/commits/82590c1289d3def5768ea14143b71066c014e39c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-delete-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-delete-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-accesspackagesincompatiblewith.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-accesspackagesincompatiblewith?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatibleaccesspackages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatibleaccesspackages?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-list-incompatiblegroups.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-list-incompatiblegroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-list-incompatiblegroups?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatibleaccesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post-incompatiblegroup.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post-incompatiblegroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-incompatiblegroup?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/api/accesspackage-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/api/accesspackage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete-incompatibleaccesspackage?view=graph-rest-beta&branch=pr-en-us-13187) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-sod/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107100001242906-13187%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T23%3A30%3A18Z&ske=2021-07-13T23%3A35%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T23%3A58%3A14Z&se=2021-08-10T00%3A03%3A14Z&sr=b&sp=r&sig=nWFVQ8QAHGpAX5l%2BRtTCkhrJW7e%2Fzbys%2B0iSmZwZm%2F0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 04:43 UTC, merged