Add Person entity to search API
microsoftgraph/microsoft-graph-docs pull request #13185
Opened 2021-06-18 13:36 UTC by acsehi

2021-06-18 13:38 UTC, opbld31 commented
Docs Build status updates of commit _[29c45c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29c45c85fbb53594a9b8ed6c0c6f16b8717ef3c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) | [Details](#user-content-3039b6fb3ba73fddeb0a62cdf684a7dc-ea8323b6)
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-ea8323b6)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |

<a id="3039b6fb3ba73fddeb0a62cdf684a7dc-ea8323b6"></a>
### [concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ancsehi' is not a valid GitHub ID.`````

<a id="464f6e6261c8b38a41277608d7460584-ea8323b6"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 35, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106181336430166-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c7JAhVFfQk9JOdDHm8N18c%2FPZl6cFSQnrabz8%2FR7UjA%3D&st=2021-06-18T13%3A33%3A17Z&se=2021-07-19T13%3A38%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-28 14:06 UTC, opbld30 commented
Docs Build status updates of commit _[6ce47b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ce47b148b0c4b68153602b8eabf95e89fd513b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-938a169d)
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) | [Details](#user-content-3039b6fb3ba73fddeb0a62cdf684a7dc-938a169d)
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-938a169d)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-13185) (>= graph-rest-1.0) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-13185) |

<a id="a5de560d9c6f4e2a27499d7f0e61a89a-938a169d"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3039b6fb3ba73fddeb0a62cdf684a7dc-938a169d"></a>
### [concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ancsehi' is not a valid GitHub ID.`````

<a id="464f6e6261c8b38a41277608d7460584-938a169d"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 35, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106281404428301-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f9oWcUD1MEhnW6X7knPbixivujVnnlP7MtUX78QNNls%3D&st=2021-06-28T14%3A01%3A31Z&se=2021-07-29T14%3A06%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-28 14:10 UTC, opbld32 commented
Docs Build status updates of commit _[9ce34d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ce34d81616176bd392efa82437b01af50c8de81)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-223f8201)
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) | [Details](#user-content-3039b6fb3ba73fddeb0a62cdf684a7dc-223f8201)
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-223f8201)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-13185) (>= graph-rest-1.0) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-13185) |

<a id="a5de560d9c6f4e2a27499d7f0e61a89a-223f8201"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3039b6fb3ba73fddeb0a62cdf684a7dc-223f8201"></a>
### [concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ancsehi' is not a valid GitHub ID.`````

<a id="464f6e6261c8b38a41277608d7460584-223f8201"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 35, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106281405447198-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y64xm%2BziOSUqrVh8S%2FVwcslea%2FENJVfwYeqvrVyTZ0w%3D&st=2021-06-28T14%3A05%3A30Z&se=2021-07-29T14%3A10%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-28 21:40 UTC, cristianv-ms commented
Please solve the warnings in this files:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/printerstatus.md

https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md

2021-06-29 00:49 UTC, nmoreau commented
@acsehi , I have added cristian who should be the reviewer for anything on Public API.
You can add me as optional only.

2021-06-29 10:30 UTC, opbld33 commented
Docs Build status updates of commit _[21b8c9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21b8c9eca02a48aafe903f1b588e01accca21099)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) | [Details](#user-content-3039b6fb3ba73fddeb0a62cdf684a7dc-f30172b3)
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-f30172b3)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |

<a id="3039b6fb3ba73fddeb0a62cdf684a7dc-f30172b3"></a>
### [concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ancsehi' is not a valid GitHub ID.`````

<a id="464f6e6261c8b38a41277608d7460584-f30172b3"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 35, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106291029133099-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6ORb7KrwuGbwpDgjlc3DFvxNz96Qekc1VmTeuVLnfRo%3D&st=2021-06-29T10%3A25%3A49Z&se=2021-07-30T10%3A30%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 16:25 UTC, cristianv-ms requested changes
Add to entityType property, the new entity type "person" in the description column, in searchrequest.md file.

2021-06-30 14:27 UTC, opbld31 commented
Docs Build status updates of commit _[4158308](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4158308482d7ceca27e1d07969e6ccf1a634bb42)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3cd34195)

<a id="3cd34195"></a>
###
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-ref&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-docs&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106301426409450-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OQC%2B1BjMhmu3UK8hYnabmIYTwinYZVU52%2BTmKno8HAk%3D&st=2021-06-30T14%3A22%3A12Z&se=2021-07-31T14%3A27%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 14:37 UTC, opbld32 commented
Docs Build status updates of commit _[baaff16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/baaff167a8a18607a3081a82403ef24916d57949)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6ee0eba7)

<a id="6ee0eba7"></a>
###
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-ref&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-docs&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106301436452388-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B5o5eVy5zsRkyJfheTqZfRHVNJzkW%2BH%2Bxv00FCgHviw%3D&st=2021-06-30T14%3A32%3A25Z&se=2021-07-31T14%3A37%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 15:01 UTC, opbld31 commented
Docs Build status updates of commit _[4c17d7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c17d7ec479e0b9fe9fb04847067aad6a2dc44fe)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c937956a)

<a id="c937956a"></a>
###
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-ref&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-docs&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106301500588832-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IU8l%2FF9Be0ku1NdXPevhTw3%2F48C3Lovc%2FOWBLN5yHes%3D&st=2021-06-30T14%3A56%3A51Z&se=2021-07-31T15%3A01%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 15:02 UTC, opbld34 commented
Docs Build status updates of commit _[0feecb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0feecb660b5fde4848426ee7e2ddb64af986e482)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-230b6c6d)

<a id="230b6c6d"></a>
###
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-ref&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-docs&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106301501320382-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pwiFjQdtcvgW9ogATFwytRDf9V1t5nBXUvzq33f4TZs%3D&st=2021-06-30T14%3A57%3A27Z&se=2021-07-31T15%3A02%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 16:11 UTC, cristianv-ms approved these changes

2021-06-30 16:24 UTC, opbld32 commented
Docs Build status updates of commit _[0feecb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0feecb660b5fde4848426ee7e2ddb64af986e482)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) | [Details](#user-content-3039b6fb3ba73fddeb0a62cdf684a7dc-64d9e00a)
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-64d9e00a)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="3039b6fb3ba73fddeb0a62cdf684a7dc-64d9e00a"></a>
### [concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ancsehi' is not a valid GitHub ID.`````

<a id="464f6e6261c8b38a41277608d7460584-64d9e00a"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106301622171056-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gMasDigAQVAF25G5EgyQpnTcVr2ChJ6IeWy8m%2BcIf3Y%3D&st=2021-06-30T16%3A19%3A47Z&se=2021-07-31T16%3A24%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 16:27 UTC, opbld34 commented
Docs Build status updates of commit _[0feecb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0feecb660b5fde4848426ee7e2ddb64af986e482)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) | [Details](#user-content-3039b6fb3ba73fddeb0a62cdf684a7dc-9d6832ee)
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-9d6832ee)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |

<a id="3039b6fb3ba73fddeb0a62cdf684a7dc-9d6832ee"></a>
### [concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'ancsehi' is not a valid GitHub ID.`````

<a id="464f6e6261c8b38a41277608d7460584-9d6832ee"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106301624547015-13185%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XU22JxlhlOnqqr9WR4Y3bCtKlSvmkBrYzZQVxmJDACc%3D&st=2021-06-30T16%3A22%3A17Z&se=2021-07-31T16%3A27%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-05 09:50 UTC, opbld30 commented
Docs Build status updates of commit _[3f7a469](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f7a46954d8f3049edf622b3d1af5490cef2dc4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-f9678a85)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) |

<a id="464f6e6261c8b38a41277608d7460584-f9678a85"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107050945012873-13185%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-05T09%3A28%3A15Z&ske=2021-07-12T09%3A33%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-05T09%3A45%3A25Z&se=2021-08-05T09%3A50%3A25Z&sr=b&sp=r&sig=ZO8BNcqDCDato3rynqAyidOOdEM4MA3gMk5398Mz3m8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-07 04:15 UTC, opbld32 commented
Docs Build status updates of commit _[bc12f57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc12f57320b121d8ee372c3c1d863f7ae0c26856)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-d3e61946)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) |

<a id="464f6e6261c8b38a41277608d7460584-d3e61946"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107070413464878-13185%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A50%3A03Z&ske=2021-07-13T07%3A55%3A03Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T04%3A10%3A02Z&se=2021-08-07T04%3A15%3A02Z&sr=b&sp=r&sig=xWgmT%2FxAMtBFRwiIVl1IWNyM%2BtV%2BMk62FI5BbviklNc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-07 04:17 UTC, opbld34 commented
Docs Build status updates of commit _[d7d89a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7d89a116769c9c0daafba25fd61a98912f835db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-5725dc4b)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) |

<a id="464f6e6261c8b38a41277608d7460584-5725dc4b"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107070416040498-13185%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A21%3A19Z&ske=2021-07-13T09%3A26%3A19Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T04%3A12%3A31Z&se=2021-08-07T04%3A17%3A31Z&sr=b&sp=r&sig=137pGImOoBvW97H5YLv6UXyW%2FwlQtHGttyZNFW%2FdYCc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-07 04:19 UTC, opbld30 commented
Docs Build status updates of commit _[65f23fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65f23fdb44af9988b244b9c1b0bf265a45e26525)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-f3d86eec)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) |

<a id="464f6e6261c8b38a41277608d7460584-f3d86eec"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107070418019274-13185%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A23%3A37Z&ske=2021-07-13T08%3A28%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T04%3A14%3A36Z&se=2021-08-07T04%3A19%3A36Z&sr=b&sp=r&sig=3RNULHMpLiB5SV1DD7rMvU2VmaGONkk2TEpGPWsQ618%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-07 04:21 UTC, Lauragra commented on concepts/search-concept-person.md
> +title: "Use the Microsoft Search API in Microsoft Graph to search people (preview)"
Please update the toc.yml file in the /concepts folder to surface this new concept topic in the TOC.

2021-07-07 04:22 UTC, opbld32 commented
Docs Build status updates of commit _[cbc6e93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbc6e93760812a2ae9fc607fa60cd11407bd00be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-b48445a4)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) |

<a id="464f6e6261c8b38a41277608d7460584-b48445a4"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107070420285083-13185%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A57%3A11Z&ske=2021-07-13T08%3A02%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T04%3A17%3A02Z&se=2021-08-07T04%3A22%3A02Z&sr=b&sp=r&sig=mVVcHY2Z82IVQdL3zNQOxaMZiR%2F2wKr9SvMzJ2OUnJQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-07 13:40 UTC, opbld33 commented
Docs Build status updates of commit _[5a1b5a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a1b5a9ba145624a4c0c74ad5327b906495b4ba9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) | [Details](#user-content-464f6e6261c8b38a41277608d7460584-619993b0)
[api-reference/beta/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-13185) (graph-rest-beta) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/search-concept-person.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-person?branch=pr-en-us-13185) |

<a id="464f6e6261c8b38a41277608d7460584-619993b0"></a>
### [api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ancsehi-ms-GraphDocUpdate/api-reference/beta/resources/searchrequest.md)
 - **Line 34, Column 411**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftsearch/configure-connector#step-5-assign-property-labels' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107071338384294-13185%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A19%3A18Z&ske=2021-07-13T07%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T13%3A35%3A05Z&se=2021-08-07T13%3A40%3A05Z&sr=b&sp=r&sig=b3W9BqZ7pT6yfkrE3DNAiY822OhovBpbs0lSVl6WhPM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 04:31 UTC, Lauragra approved these changes

2021-07-08 04:31 UTC, merged