Minor updates to access reviews(v1.0)
microsoftgraph/microsoft-graph-docs pull request #13196
Opened 2021-06-18 21:10 UTC by shubhamguptacal

2021-06-18 21:16 UTC, opbld31 commented
Docs Build status updates of commit _[2c7025b](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/2c7025b1bf231b9f2de66bf6ab9a483d3e0fc2ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-13196) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106182110224717-13196%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P1GQmmfaCCrrmTn1UJJ5gotCdDnMTnS7j8JenJq%2FSVY%3D&st=2021-06-18T21%3A11%3A46Z&se=2021-07-19T21%3A16%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-03 22:00 UTC, isabelleatmsft approved these changes

2021-08-04 07:06 UTC, opbld33 commented
Docs Build status updates of commit _[2c7025b](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/2c7025b1bf231b9f2de66bf6ab9a483d3e0fc2ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-13196) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108040704075647-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=nsCN26807EjoH4%2F2%2FIRimNphUyCoCDu160mA2tVzSa0%3D&st=2021-08-04T07%3A01%3A02Z&se=2021-09-04T07%3A06%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 07:31 UTC, FaithOmbongi requested changes
Let's order the properties in the properties table so it's easily scannable.
All the entries in the ChangeList to have the same Id value.

2021-08-04 07:31 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "SubArea": "Identity governance"
```suggestion
              "SubArea": "Governance"
```

2021-08-04 07:31 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +                      "Id": "71e1d909-8f9b-45de-9b71-882424c7203b",
Same Id value for all entries.

2021-08-04 07:31 UTC, FaithOmbongi commented on api-reference/v1.0/resources/accessreviewinstance.md
> +| reviewers   |[accessReviewReviewerScope](../resources/accessreviewreviewerscope.md) collection| This collection of access review scopes is used to define who are the reviewers. Supports `$select`.
Let's order the properties in this table for scannability

2021-08-09 22:07 UTC, opbld32 commented
Docs Build status updates of commit _[e639a33](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/e639a3364ab2837d1490960a3ea1446ee7c01d34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-13196) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108092205396232-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=gnMxjkZCw2wVbuODHOmMTHRcsFxm0Va6BWnlQ5Ghv7o%3D&st=2021-08-09T22%3A02%3A06Z&se=2021-09-09T22%3A07%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 22:09 UTC, opbld30 commented
Docs Build status updates of commit _[868b7d9](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/868b7d9c0a58cbd85a9ccb1ca24016191ab3b310)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-13196) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108092206585139-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=NKDSViaz3cr06GlRmAM0RSk2%2BhPTyF0TZoawvvR5XRg%3D&st=2021-08-09T22%3A04%3A23Z&se=2021-09-09T22%3A09%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 06:49 UTC, FaithOmbongi reviewed
@isabelleatmsft , let's alphabetically order the properties in the properties tables of accessReviewInstance. This improves scanning by our customers.

2021-08-10 06:49 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +              "Id": "0ae65d30-ac52-461e-92b0-83bc40bc64eb",
```suggestion
              "Id": "d981fc6e-c544-4b73-92ce-b41d0c4cd8bf",
```

2021-08-11 04:49 UTC, opbld34 commented
Docs Build status updates of commit _[64f6883](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/64f68838488e2744196a13f04db6200f705dd630)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-13196) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110448166848-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mnXqr%2FxB1hXthAmlIEn5yytcTpX%2BCrl%2B24ui78AJoVQ%3D&st=2021-08-11T04%3A44%3A53Z&se=2021-09-11T04%3A49%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 04:51 UTC, opbld32 commented
Docs Build status updates of commit _[9c2ac2f](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/9c2ac2fd1152c4989c83fd2f60d01fc2b941624e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-13196) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110449483266-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=iwDAiIzZmzOKeapelcKAWleEIPPNCj9Ga4LQmmLquZM%3D&st=2021-08-11T04%3A46%3A25Z&se=2021-09-11T04%3A51%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 06:24 UTC, opbld30 commented
Docs Build status updates of commit _[d284279](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/d284279d756baf03f666a1df0b21a737287f3d22)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-29e1fe92)

<a id="29e1fe92"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110624076441-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=dWuF%2B02ETWHOcSpFcsc3R7Kuyo4j1yscljLif5QX%2Byg%3D&st=2021-08-11T06%3A19%3A23Z&se=2021-09-11T06%3A24%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 06:27 UTC, opbld32 commented
Docs Build status updates of commit _[d284279](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/d284279d756baf03f666a1df0b21a737287f3d22)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e96e459c)

<a id="e96e459c"></a>
###
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-ref&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-docs&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=main&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110626443460-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=o5O2e36Xr5W0gKn3%2F9xIJpiLMGQjMASbsMKSeJxhnSU%3D&st=2021-08-11T06%3A22%3A35Z&se=2021-09-11T06%3A27%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 06:43 UTC, opbld33 commented
Docs Build status updates of commit _[d284279](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/d284279d756baf03f666a1df0b21a737287f3d22)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-96e0f70f)

<a id="96e0f70f"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108110637270504-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1EuFtvhD3Wi3W%2B%2BQA1Oxwp%2B%2FGf6k6Rgho5bH%2BDBbShI%3D&st=2021-08-11T06%3A38%3A21Z&se=2021-09-11T06%3A43%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-11 06:47 UTC, FaithOmbongi commented
The PR's hitting an OPS build error. Should try to close and reopen later to resolve it.

2021-08-11 11:23 UTC, opbld31 commented
Docs Build status updates of commit _[d284279](https://github.com/shubhamguptacal/microsoft-graph-docs/commits/d284279d756baf03f666a1df0b21a737287f3d22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/accessreviewinstance.md](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/api-reference/v1.0/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-1.0&branch=pr-en-us-13196) (>= graph-rest-1.0) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/shubhamguptacal/microsoft-graph-docs/blob/shugup-accessreview-v1_0/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108111121408140-13196%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=sYGLkQ5vVyFcLYtAYIIXGaIqmGHAVLm3DPE9aNQz%2BV0%3D&st=2021-08-11T11%3A18%3A06Z&se=2021-09-11T11%3A23%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-12 03:15 UTC, merged