Add reupload API to cloudPcDeviceImage
microsoftgraph/microsoft-graph-docs pull request #13220
Opened 2021-06-22 06:42 UTC by RuiHou105

2021-06-22 06:43 UTC, opbld30 commented
Docs Build status updates of commit _[437f836](https://github.com/microsoftgraph/microsoft-graph-docs/commits/437f836ed6a0f0aa5f6f27618cd5747cfcbea2aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) | [Details](#user-content-71bd6c457b5a4e543249017a955662ec-aec515cd)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) | [Details](#user-content-ea68125c0f04f3c3ad01415df54ccd59-aec515cd)
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="71bd6c457b5a4e543249017a955662ec-aec515cd"></a>
### [api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-delete.md(10,1), beta/api/cloudpcdeviceimage-reupload.md(10,1)'. First level headings must be unique within a docset.`````

<a id="ea68125c0f04f3c3ad01415df54ccd59-aec515cd"></a>
### [api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-delete.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete cloudPcDeviceImage' is duplicated with other articles: 'beta/api/cloudpcdeviceimage-delete.md(10,1), beta/api/cloudpcdeviceimage-reupload.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220642037534-13220%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AiFRqClMNRKiOqRa1fXtNRioyzjWErLu7PMDlmdEwMs%3D&st=2021-06-22T06%3A38%3A34Z&se=2021-07-23T06%3A43%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 06:56 UTC, RuiHou105 commented
1.Related api.md file: 
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/8483
https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/8873

2. Related CSDL file:
https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4689135

2021-06-24 23:12 UTC, cohanley approved these changes

2021-07-06 03:03 UTC, RuiHou105 commented
@JarbasHorst As this API is already alive, could you please help me review/approve it? Thanks in advance.

2021-07-06 18:38 UTC, JarbasHorst requested changes

2021-07-06 18:38 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcdeviceimage-reupload.md
> +# Delete cloudPcDeviceImage
Make sure that the title field matches the H1.

2021-07-06 18:38 UTC, JarbasHorst commented on api-reference/beta/api/cloudpcdeviceimage-reupload.md
> +  "name": "delete_deviceimages_from_virtualendpoint"
I recommend you to replace the value of the name property because delete_deviceimages_from_virtualendpoint doesn't describe the request correctly.

2021-07-06 18:38 UTC, JarbasHorst commented on changelog/Microsoft.CloudManagedDesktop.json
> +                    "Description": "Added the [reupload](https://docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta) method to the [cloudPcDeviceImage](https://docs.m
I recommend you to remove `en-us` from the links you've added. Let docs.microsoft.com figure out the correct locale. Suggested revision:

- https://docs.microsoft.com/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta
- https://docs.microsoft.com/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta

2021-07-07 03:29 UTC, RuiHou105 commented on api-reference/beta/api/cloudpcdeviceimage-reupload.md
> +# Delete cloudPcDeviceImage
Sorry for my carelessness. Corrected.

2021-07-07 05:27 UTC, opbld31 commented
Docs Build status updates of commit _[090ca0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/090ca0c2319736c65e9a5dbfc0bfbd2f6673299a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107070525548871-13220%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A19%3A18Z&ske=2021-07-13T07%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T05%3A22%3A22Z&se=2021-08-07T05%3A27%3A22Z&sr=b&sp=r&sig=hjktnjCkf8FCRf6a2fPgCjhCHmEtyeHqDoIkjk3ujSI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-07 05:31 UTC, RuiHou105 commented
@JarbasHorst  Thank you for your review. I've resolved all your comments. Could you please take a second look when you got time?

2021-07-07 19:25 UTC, JarbasHorst commented
Hi @RuiHou105 

I believe we're missing the toc entry for the new *reupload* method. Can you please still do that?

![image](https://user-images.githubusercontent.com/26866873/124816678-11e96280-df69-11eb-8725-b805e72242a9.png)

Thanks,
Jarbas

2021-07-08 03:33 UTC, opbld34 commented
Docs Build status updates of commit _[99a40f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99a40f4488e99b76a0213194ee0d7383f928e151)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080332079643-13220%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A02%3A24Z&ske=2021-07-13T07%3A07%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T03%3A28%3A21Z&se=2021-08-08T03%3A33%3A21Z&sr=b&sp=r&sig=0hcOsqFqwvWcVWfNVkmLdCnmM5qDpgcurq1T%2BErqAMw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 03:37 UTC, opbld32 commented
Docs Build status updates of commit _[5d5ddf5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d5ddf567677abac22a0e59de8b52163b0786e23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080336249176-13220%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A57%3A11Z&ske=2021-07-13T08%3A02%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T03%3A32%3A57Z&se=2021-08-08T03%3A37%3A57Z&sr=b&sp=r&sig=ynzpKiBESuwCbsKIa7lgTCxNrT1vSr2edCZNRXMAbvs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 03:54 UTC, RuiHou105 commented
Hi @JarbasHorst , thanks for reminding. toc file already updated. Please take a second look when you got time. Thanks!

2021-07-08 19:11 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-07-09 19:15 UTC, Lauragra commented on api-reference/beta/api/cloudpcdeviceimage-reupload.md
> +# Reupload cloudPcDeviceImage
The title and H1 here should be "cloudPcDeviceImage: reupload", per the topic title guidelines (binding type: action name).

2021-07-09 19:18 UTC, opbld32 commented
Docs Build status updates of commit _[4a66af1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a66af1ceb31f41e1c4f3ed04f136eadbc93f9fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091916531501-13220%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A08%3A15Z&ske=2021-07-13T08%3A13%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T19%3A13%3A23Z&se=2021-08-09T19%3A18%3A23Z&sr=b&sp=r&sig=O7ckFSmkdD6QOvMZ7qYwbeRworT5lG45S6XKnWUFiVE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 19:19 UTC, opbld34 commented
Docs Build status updates of commit _[0c2c721](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c2c7218cf07fb6c0c52baf0139f90562310fb1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091917155813-13220%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A26%3A28Z&ske=2021-07-13T08%3A31%3A28Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T19%3A14%3A56Z&se=2021-08-09T19%3A19%3A56Z&sr=b&sp=r&sig=UomWUweZX4Aeh7586riUiThXLW0qJRolfRmW69V70pc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 19:23 UTC, Lauragra approved these changes

2021-07-09 19:23 UTC, opbld30 commented
Docs Build status updates of commit _[52b0308](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52b0308ddf97fca2c8bf7d9ba922bc1533647757)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091922183128-13220%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A26%3A28Z&ske=2021-07-13T08%3A31%3A28Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T19%3A18%3A47Z&se=2021-08-09T19%3A23%3A47Z&sr=b&sp=r&sig=aI5X2h3PrfpvOPzXM6jHFCisRTmaxxpgLAzxC8iiIQ8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 19:25 UTC, opbld31 commented
Docs Build status updates of commit _[951cf1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/951cf1e0ec94a6fc7c731f907afe9badc253c6a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-reupload.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/api/cloudpcdeviceimage-reupload.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-reupload?view=graph-rest-beta&branch=pr-en-us-13220) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rui/AddReuploadAPI/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091922577704-13220%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A19%3A18Z&ske=2021-07-13T08%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T19%3A20%3A28Z&se=2021-08-09T19%3A25%3A28Z&sr=b&sp=r&sig=MRk7rvjkhiVa6sVqFTW8SHNV1Cz2UD9MCcZJXFU414U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 21:32 UTC, merged