Updated C# link in code sample
microsoftgraph/microsoft-graph-docs pull request #13245
Opened 2021-06-23 10:12 UTC by v-abirade

2021-06-23 10:14 UTC, opbld34 commented
Docs Build status updates of commit _[e359075](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e35907540caf5fa25c36fccdceb9cc4cd1b72249)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-abirade-patch-2/api-reference/v1.0/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-1.0&branch=pr-en-us-13245) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106231012595396-13245%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VkpQaFPSMQMukNxVp6xrOaGP89%2BmCeBlPMv%2FCPeQto8%3D&st=2021-06-23T10%3A09%3A39Z&se=2021-07-24T10%3A14%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 10:22 UTC, Trinetra-MSFT requested changes

2021-06-23 10:22 UTC, Trinetra-MSFT commented on api-reference/v1.0/api/chat-sendactivitynotification.md
> +|Activity feed notification|Send activity feed notification in scope of a chat|[View](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed/csharp)|Yet to receive
Please remove this yet to receive leave it blank. Copy the description from sample code github repo readMe

2021-06-23 10:35 UTC, opbld30 commented
Docs Build status updates of commit _[db0c312](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db0c312c4d37087fe91ebeb16ebe1dbce8d0ad4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-abirade-patch-2/api-reference/v1.0/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-1.0&branch=pr-en-us-13245) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106231033556644-13245%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hlc5t7ZuhK%2FF9qJv2G3CtcMccztivpk%2FltKtyp%2Bedlc%3D&st=2021-06-23T10%3A30%3A25Z&se=2021-07-24T10%3A35%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 09:51 UTC, Trinetra-MSFT approved these changes

2021-06-24 16:17 UTC, Lauragra commented on api-reference/v1.0/api/chat-sendactivitynotification.md
> +## Code sample
This is a non-standard H2. The reference content is templatized so we shouldn't introduce non-standard headings. Instead, you can use a ## See also heading. We don't need a table for one sample, so just put ## See also followed by the link: [Notify Feed App C# sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed/csharp)). Also, this is the v1.0 version of the topic, you should make the same update to the topic in the /beta folder so they stay in sync.

2021-07-08 04:30 UTC, opbld34 commented
Docs Build status updates of commit _[43b161c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43b161c29f7a76d08198c1b2905651d333ebd222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-abirade-patch-2/api-reference/v1.0/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-1.0&branch=pr-en-us-13245) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080429241266-13245%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A04%3A14Z&ske=2021-07-13T09%3A09%3A14Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T04%3A25%3A56Z&se=2021-08-08T04%3A30%3A56Z&sr=b&sp=r&sig=X0K2U1msszzcXkUN4mDHlfJLaKQUpxrVosSN1IZK%2FqU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 04:32 UTC, merged