Microsoft 365 Lighthouse
microsoftgraph/microsoft-graph-docs pull request #13285
Opened 2021-06-25 18:22 UTC by isaiahwilliams

Through this pull request the documentation for the API used by Microsoft 365 Lighthouse is being added.

2021-06-25 18:24 UTC, opbld30 commented
Docs Build status updates of commit _[cec3deb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cec3debf3499e602029f730bfd8f71dd1756f08b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-391fa6e51415cb7bfa3a3e677326bf19-497ce73e)
[api-reference/beta/api/managedtenants-cloudpcconnection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-edde117d8c646f71a8ccf75cd8a7b439-497ce73e)
[api-reference/beta/api/managedtenants-cloudpcdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-90f3c9a63e1cc46c571383d3004f98ba-497ce73e)
[api-reference/beta/api/managedtenants-cloudpcoverview-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcoverview-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcoverview-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-237c3deacbc611b49af07bad93679342-497ce73e)
[api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-conditionalaccesspolicycoverage-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-fdbe8f3a52ed42664c9fb69dbff627f8-497ce73e)
[api-reference/beta/api/managedtenants-credentialuserregistrationssummary-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-credentialuserregistrationssummary-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-credentialuserregistrationssummary-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-9c525fbc82488367f4db5864625efefc-497ce73e)
[api-reference/beta/api/managedtenants-manageddevicecompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-manageddevicecompliance-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-manageddevicecompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-51a6605f134bbd8147f2bbb644c09b41-497ce73e)
[api-reference/beta/api/managedtenants-managementaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managementaction-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managementaction-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3b7d02bcecc7ce5a320b18aa954a6dd2-497ce73e)
[api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managementactiontenantdeploymentstatus-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-35d23fda09ace150a6aa105b4f991c04-497ce73e)
[api-reference/beta/api/managedtenants-managementintent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managementintent-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managementintent-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-abac4c5560a08c89adfe4ee039741e7e-497ce73e)
[api-reference/beta/api/managedtenants-managementtemplate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managementtemplate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managementtemplate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-93fbadc377d72fe229009a9765489fa9-497ce73e)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-497ce73e)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-497ce73e)
[api-reference/beta/api/managedtenants-tenant-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-tenant-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-tenant-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e6397abf1a4604b1e7bf33d31b7475d-497ce73e)
[api-reference/beta/api/managedtenants-tenantcustomizedinformation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-tenantcustomizedinformation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-tenantcustomizedinformation-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-d69f4f6f50faea8f1804cfdd6ac2bf08-497ce73e)
[api-reference/beta/api/managedtenants-tenantdetailedinformation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-tenantdetailedinformation-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-tenantdetailedinformation-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-576e22dc10cea00ba93f2df6a6255ffb- [...]

2021-06-25 19:46 UTC, opbld33 commented
Docs Build status updates of commit _[4453038](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44530386fb09d0cf8faabffa1789d61ce272a785)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-655f2c5f)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-655f2c5f)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-655f2c5f)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-655f2c5f)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-655f2c5f)
[api-reference/beta/resources/managedtenants-manageddevicecompliancetrend.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-manageddevicecompliancetrend.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-manageddevicecompliancetrend?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-97b90624799d5ea3128e45e4ef4ec855-655f2c5f)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-655f2c5f)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-655f2c5f)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-655f2c5f)
[api-reference/beta/resources/managedtenants-workloadactiondeploymentstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-workloadactiondeploymentstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-workloadactiondeploymentstatus?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f652b9d94465b81a7fd41a7dff358b69-655f2c5f)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-655f2c5f)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-655f2c5f)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-655f2c5f)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-655f2c5f)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-655f2c5f)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-655f2c5f)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/ [...]

2021-06-25 20:14 UTC, opbld34 commented
Docs Build status updates of commit _[21cd6ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21cd6ab4389a0e8cc9a42320644053006338cb31)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-eee7c037)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-eee7c037)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-eee7c037)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-eee7c037)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-eee7c037)
[api-reference/beta/resources/managedtenants-manageddevicecompliancetrend.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-manageddevicecompliancetrend.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-manageddevicecompliancetrend?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-97b90624799d5ea3128e45e4ef4ec855-eee7c037)
[api-reference/beta/resources/managedtenants-managedtenant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-managedtenant.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-managedtenant?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-617005ddd0b7559153cab0fc983cdd81-eee7c037)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-eee7c037)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-eee7c037)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-eee7c037)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-eee7c037)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-eee7c037)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-eee7c037)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-eee7c037)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-eee7c037)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-eee7c037)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-d [...]

2021-06-26 04:20 UTC, opbld32 commented
Docs Build status updates of commit _[7412417](https://github.com/microsoftgraph/microsoft-graph-docs/commits/741241736fb796279ae0263853ff26ea685d87e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-391fa6e51415cb7bfa3a3e677326bf19-b235ab5e)
[api-reference/beta/api/managedtenants-cloudpcconnection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-edde117d8c646f71a8ccf75cd8a7b439-b235ab5e)
[api-reference/beta/api/managedtenants-cloudpcdevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-90f3c9a63e1cc46c571383d3004f98ba-b235ab5e)
[api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-conditionalaccesspolicycoverage-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-fdbe8f3a52ed42664c9fb69dbff627f8-b235ab5e)
[api-reference/beta/api/managedtenants-credentialuserregistrationssummary-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-credentialuserregistrationssummary-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-credentialuserregistrationssummary-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-9c525fbc82488367f4db5864625efefc-b235ab5e)
[api-reference/beta/api/managedtenants-manageddevicecompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-manageddevicecompliance-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-manageddevicecompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-51a6605f134bbd8147f2bbb644c09b41-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-aggregatedpolicycompliances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-aggregatedpolicycompliances.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-aggregatedpolicycompliances?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-854fd7bf179cb3018b54cfc38fea916f-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-cloudpcconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-cloudpcconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-cloudpcconnections?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f8dd0dba17bc3b815c7069046a72f095-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-cloudpcdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-cloudpcdevices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-cloudpcdevices?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-e1af36349215c35b5fd16f3489af4022-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-cloudpcsoverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-cloudpcsoverview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-cloudpcsoverview?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-41f00716cb73b8a5a7363816a34a3f74-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-conditionalaccesspolicycoverages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-conditionalaccesspolicycoverages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-conditionalaccesspolicycoverages?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f7ef13cca3e73bcade1c493ce6f52730-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-credentialuserregistrationssummaries?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-5abefb8e68ff82584a0ed68325a83d8a-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-devicecompliancepolicysettingstatesummaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-devicecompliancepolicysettingstatesummaries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-devicecompliancepolicysettingstatesummaries?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-a8765d76213465a1315c1553b891bdb9-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-manageddevicecompliances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-manageddevicecompliances.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-manageddevicecompliances?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3f3b243f4386304913539c51fb9e9887-b235ab5e)
[api-reference/beta/api/managedtenants-managedtenant-list-manageddevicecompliancetrends.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-manageddevicecompliancetrends.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-manageddevice [...]

2021-06-26 04:52 UTC, opbld34 commented
Docs Build status updates of commit _[6ad77f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ad77f6679cc224ceeac12dda30351aaae7b3f44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-7ba8206f)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-7ba8206f)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-7ba8206f)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-7ba8206f)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-7ba8206f)
[api-reference/beta/resources/managedtenants-manageddevicecompliancetrend.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-manageddevicecompliancetrend.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-manageddevicecompliancetrend?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-97b90624799d5ea3128e45e4ef4ec855-7ba8206f)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-7ba8206f)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-7ba8206f)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-7ba8206f)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-7ba8206f)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-7ba8206f)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-7ba8206f)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-7ba8206f)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-7ba8206f)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-7ba8206f)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-7ba8206f)
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2021-06-26 05:19 UTC, opbld32 commented
Docs Build status updates of commit _[bbfbd5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbfbd5f29575ab5820a36bad099fa2b5e8f27ca7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-9e10cf98)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-9e10cf98)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-9e10cf98)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-9e10cf98)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-9e10cf98)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-9e10cf98)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-9e10cf98)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-9e10cf98)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-9e10cf98)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-9e10cf98)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-9e10cf98)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-9e10cf98)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-9e10cf98)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-9e10cf98)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-9e10cf98)
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-bet [...]

2021-06-28 13:50 UTC, opbld32 commented
Docs Build status updates of commit _[d595034](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d595034424d428b805052402ebf518c4fa7e720a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-55ea997f)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-55ea997f)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-55ea997f)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-55ea997f)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-55ea997f)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-55ea997f)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-55ea997f)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-55ea997f)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-55ea997f)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-55ea997f)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-55ea997f)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-55ea997f)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-55ea997f)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-55ea997f)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-55ea997f)
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-bet [...]

2021-06-28 13:58 UTC, opbld32 commented
Docs Build status updates of commit _[4fc455f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fc455f70c3d10a6ced26c4408a7f1db970d7d6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-45cde18e)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-45cde18e)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-45cde18e)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-45cde18e)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-45cde18e)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-45cde18e)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-45cde18e)
[api-reference/docfx.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/docfx.json) | :warning:Warning | | [Details](#user-content-bcb838118199b175a44ae479e8c43131-45cde18e)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-45cde18e)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-45cde18e)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-45cde18e)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-45cde18e)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-45cde18e)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-45cde18e)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-45cde18e)
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-bet [...]

2021-07-06 20:06 UTC, opbld34 commented
Docs Build status updates of commit _[df5ba33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df5ba33dfdd40f865cdf04286817614756af70cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-cef4207c)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-cef4207c)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-cef4207c)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-cef4207c)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-cef4207c)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-cef4207c)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-cef4207c)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-cef4207c)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-cef4207c)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-cef4207c)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-cef4207c)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-cef4207c)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-cef4207c)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-cef4207c)
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedte [...]

2021-07-07 04:49 UTC, opbld30 commented
Docs Build status updates of commit _[53bb724](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53bb7240b628d9f1a63f54bccdf2e3473e2f30ce)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-0dff4f8a)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-0dff4f8a)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-0dff4f8a)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-0dff4f8a)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-0dff4f8a)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-0dff4f8a)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-0dff4f8a)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-0dff4f8a)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-0dff4f8a)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-0dff4f8a)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-0dff4f8a)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-0dff4f8a)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-0dff4f8a)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-0dff4f8a)
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedte [...]

2021-07-07 06:42 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-aggregatedpolicycompliance.md
> +|Property|Type|Description|
GLOBAL:
It's actually helpful for customers if we can note whether a property is required vs optional, or is read-only. 

I see that for this entity, your api.md file notes this level of info for the properties.
If you can note that, this would be the order - required or optional first, followed by read-only. I'd use the first property as an example:
|compliancePolicyId|String|Identifier for the device compliance policy. Optional. Read-only.|

2021-07-07 06:51 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
GLOBAL:
It's actually helpful to note for customers exactly which OData system query options that an operation supports. 

This operation: I see that the api.md file lists the specific OData system query options that this operation supports. If you can document them, this would be the sentence structure:
"This method supports OData query parameters to help customize the response: 
`$count`, `$filter`, `$orderBy`, `$select`, `$skip`, `$top`.
For general information, see [OData query parameters](/graph/query-parameters)."

2021-07-07 07:09 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md
> +{
GLOBAL:
In general, please provide examples with properties having real-looking values. That would be much more helpful for customers.

Using this operation as an example, instead of providing a JSON definition for each of the properties like tenantId, show what a tenantId can be like - is it a GUID or some string of another format? What value can the compliancePolicyPlatform property take?
Customers do ask such questions!

2021-07-07 07:37 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-conditionalaccesspolicycoverage.md
> +
GLOBAL:
Whenever you're providing a description for a resource, property, action, function, or in some cases enum values, please try to explain the purpose of that API element by using words other than those appearing in the API element name.

Using this entity as an example, line 16:
What is the purpose of conditional access? What if the customer isn't familiar with the concept of "conditional access policy" and therefore its "coverage", the description would not be helpful, right?
You can please correct me where I may get it wrong - as an example, you can say:
"Represents information about any Azure Active Directory policy that defines access rules of a resource for a given managed tenant."

2021-07-07 07:48 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Get cloud PC connection
GLOBAL:
When listing CRUD operations in the table of contents, please follow this order (and skip those operations that aren't supported for an entity): list, create, get, update, delete. More info here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=guidelines-and-examples

Using lines 14038-14041 as an example, please order the 2 operations with "List cloud PC connections" first followed by "Get cloud PC connection".
If there are actions or functions, then those can follow the CRUD operations alphabetically.

2021-07-07 07:56 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md
> +Get a list of the [conditionalAccessPolicyCoverage](../resources/managedtenants-conditionalaccesspolicycoverage.md) objects and their properties.
GLOBAL:
In general, in addition to the generated description for each CRUD operation, if you can provide more info that's specific to the resource in question, then that would be helpful for your customers to learn the specific scenarios that the operation is defined for. The generated description basically teaches what a "list" operation does, for most entities.

Using this operation as an example, as a separate paragraph after line 15, you might want to add:
"Use this operation to list conditional access policy coverage across all the tenants managed by an IT customer."

2021-07-07 08:11 UTC, angelgolfer-ms requested changes
Hi @isaiahwilliams , I have gone through topics for only a couple of entities and their operations. I noted "GLOBAL" in most of my comments, which means those comments generally apply to other entity topics, list operation topics, or method topics, where applicable. Please take a look and make the corresponding updates to other topics in the PR as well. I noted them "GLOBAL" and will not comment about the same issues in other topics.

Please confirm ON TEAMS which api.md files are applicable to this PR. I need to have a fuller context for your API set before I can determine where in the TOC and with which TOC node label to surface your content. We will then also need to add your workload to the [major services](https://docs.microsoft.com/en-us/graph/overview-major-services#device-management) topic.

Please also prepare a service-level conceptual overview to go under the LEARN section in the TOC, and an API overview to go under the Beta reference section TOC. More info for these overview topics here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103154/Conceptual-topics

Please follow up on these items at your earliest convenience within the next couple of days. I will continue to review your PR tomorrow in the early afternoon. Please let me know if you have questions; pinging me on Teams would be good.

2021-07-08 19:10 UTC, opbld32 commented
Docs Build status updates of commit _[5e8cd27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e8cd274d6d0056f5fe83d7dcb9fb202734cf91c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-4982e953)
[api-reference/beta/api/managedtenants-riskyuser-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-7c20b19d1146d1bb930dc73da7f6e62e-4982e953)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-4982e953)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-bc469c2e5a51bed9edcdf23d698a032a-4982e953)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-4982e953)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-4982e953)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-4982e953)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-4982e953)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-4982e953)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-4982e953)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-4982e953)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-4982e953)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-4982e953)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-4982e953)
[api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-aggregatedpolicycompliance-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcconnection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedte [...]

2021-07-09 03:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-cloudpcconnection.md
> +
Line 16:
I'm pointing this out as an example of an earlier GLOBAL comment that in general, we shouldn't just use the same words in the name of a resource (or property or method) in its description. 

Using this resource as an example, what kind of information or data does a "connection" offer?
Also, because of the construction of the sentence ("... for a given managed tenant" instead of "... in a given managed tenant", it was ambiguous/not apparent for someone unfamiliar that typically, a managed tenant would have multiple such cloud PC connections. That ambiguity might pose an issue to localization.

Would it be appropriate to say something like the following (based on the corresponding api.md file):
"Represents Azure resource information for a cloud PC in a given managed tenant. This information can be used to establish on-premises network connectivity for the cloud PC."

Please modify where appropriate.

GLOBAL: Please use a similar approach to make the descriptions for your other resources more helpful.

2021-07-09 03:21 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md
> +{
Reinforcing this point - various members of our docs v-team seconded today that it's pretty common that customers ask questions about our APIs which can be answered if example requests and responses provide real-looking values for IDs and other properties.

2021-07-09 03:52 UTC, angelgolfer-ms commented on api-reference/beta/resources/tenantrelationship.md
> +
Line 14:
When we say "Represent(s) the various type(s)...", we expect the resource to define some property that actually specifies a type, but the resource doesn't specify any "type".

What about:
"Represents the root entity of the relationships of an IT resource manager with its managed tenants."

Is that what this resource is?
Please correct to make the description more helpful.

2021-07-09 04:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/tenantrelationship.md
> +## Properties
GLOBAL:
In a resource topic, if there are no properties, the content of that section should just have one line that says "None."
Can you please update your resource topics?

Using this entity topic as an example - lines 21 and 22 should be replaced by just one line that says "None." (Please make sure to include the period at the end.)

Can you also confirm for me if the empty table (lines 21 and 22) were generated as such?
That would be a bug, if that's the case, and we'd need to report and get that fixed.

2021-07-09 04:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +
GLOBAL:
We start a description with a verb in third-person singular, describing the corresponding resource (or corresponding method in method topics, or a property in a Properties table). Please make the appropriate fixes in your topics in this PR.

Using line 16 as an example, the sentence should start with "Represents...", not "Represent..."

2021-07-09 07:33 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +
Line 16:
You refer to a "multi-tenant management platform" in this topic for a basic entity managedTenant.
Can you please make sure in your conceptual overview topic, you use an example to define what "multi-tenant management platform" does? 
Just so you're aware, even though your API is for IT customers, because your API docs are part of the Microsoft Graph docs that cater to a wide range of customers (including developer and IT customers), we don't assume a high level of familiarity with scenarios and roles.

2021-07-10 06:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-cloudpcoverview.md
> +Represents an overview of cloud PCs for a given managed tenant.
Line 16 and GLOBAL:
This is another example of my GLOBAL comment for this PR - this description is not informative. What kind of information about cloud PCs is exposed in an "overview"?
Does this description work: 
"Represents the statuses and connections of cloud PCs in a tenant of a managed service provider."

In general, please don't just use the same words of the resource name to explain the purpose of a resource. Please review the descriptions of the other resources in this PR and provide more context to make them informative.

2021-07-10 06:30 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcoverview-list.md
> +
Line 15 and GLOBAL:
Wanted to use this description as another example of how the generated description only describes what a list operation does irrespective of the objects it lists. Please try to provide more context for this API. 
Would a description like the following be correct:
"Get a collection of overviews of cloud PC statuses and connections, across each of the multiple tenants of a managed service provider."

In general, please don't just use the generated description to explain the purpose of an operation; it simply describes generically what an operation does irrespective of the object. Please review the descriptions of the other operations in this PR and provide more context to make them informative.

2021-07-10 06:34 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcoverview-get.md
> +Read the properties and relationships of a [cloudPcOverview](../resources/managedtenants-cloudpcoverview.md) object.
Line 15 and GLOBAL:
Wanted to use this description as another example of how the generated description only describes what a get operation does irrespective of the object. Please try to provide more context for this API.
Would a description like the following be correct:
"Get an overview of statuses and connections of cloud PCs in a tenant of a managed service provider."

In general, please don't just use the generated description to explain the purpose of an operation; it simply describes generically what an operation does irrespective of the object. Please review the descriptions of the other operations in this PR and provide more context to make them informative.

2021-07-10 07:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-cloudpcoverview.md
> +|[List cloudPcOverviews](../api/managedtenants-cloudpcoverview-list.md)|[microsoft.graph.managedTenants.cloudPcOverview](../resources/managedtenants-cloudpcoverview.md) collection|Get a list of the [
Line 21:
The first column should read "List cloudPcsOverview". The topic title of a list operation topic uses the name of the navigation property, in this case it's cloudPcsOverview.
For the topic title, we don't make up the topic title by just pluralizing a resource name in the docs (in this case, we don't just add an 's' to the resource name cloudPcOverview).

2021-07-10 07:48 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcoverview-list.md
> +# List cloudPcOverviews
Line 10:
The topic title should be "List cloudPcsOverview". The topic title of a list operation topic uses the name of the navigation property, in this case it's cloudPcsOverview.
See the guidance on reference topic titles: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=guidelines-and-examples

2021-07-10 07:56 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcoverview-list.md
> +---
GLOBAL:

In general, a list operation topic filename in a subnamespace should have a filename that follows this pattern: {subnamespace-name}-{parent-resource-name}-{navigation property-name}.md

In this case, the filename should be managedtenants-managedtenant-cloudpcsoverview.md. 
Please see guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming

Did the stub topic generator generate a topic by this filename managedtenants-cloudpcoverview-list.md?

2021-07-10 08:07 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcdevice-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-{navigation-property-name}.md

In this case, please rename the file as managedtenants-managedtenant-cloudpcdevices.md.

2021-07-10 08:09 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcconnection-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-cloudpcconnections.md and fix links going to the file.

2021-07-10 08:10 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-aggregatedpolicycompliances.md and fix links going to the file.

2021-07-10 08:14 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-conditionalaccesspolicycoverages.md and fix links going to the file.

2021-07-10 08:16 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-credentialuserregistrationssummary-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-credentialuserregistrationssummary.md and fix links going to the file.

2021-07-10 08:18 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-devicecompliancepolicysettingstatesummary-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-devicecompliancepolicysettingstatesummaries.md and fix links going to the file.

2021-07-10 08:19 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-manageddevicecompliance-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-manageddevicecompliances.md and fix links going to the file.

2021-07-10 08:20 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-manageddevicecompliancetrend-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-manageddevicecompliancetrends.md and fix links going to the file.

2021-07-10 08:39 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-managementaction.md
> +
Line 16:
Please provide more context to management actions. For example, the kinds of management actions and their purpose.

Can you pull some info from your api.md file(s), for example:
"Examples of management actions are device encryption and MFA for admins."

2021-07-10 08:42 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementaction-apply.md
> +Applies the management action against the specified managed tenant.
Line 15:
Can you reorganize the sentence so that you can include the resource name managementAction and link to the corresponding topic, so that customers can find out more about management actions?

It would be helpful to provide contexts and examples of management actions that this method supports.

2021-07-10 08:45 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementaction-apply.md
> +
Lines 50 and 51:
Can you rephrase the descriptions, use the resource names tenantGroup and managementTemplate, and link to them?

In general, in API reference, the more we can provide links to API element names (on first reference in the topic), the more helpful it is for customers.

2021-07-10 08:46 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementaction-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-managementactions.md and fix links going to the file.

2021-07-10 08:47 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-changedeploymentstatus.md
> +
Please provide a description for this method.

2021-07-10 08:50 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-changedeploymentstatus.md
> +|status|String|The new status for the management action tenant deployment.|
Lines 47, 49, 50:
In the descriptions, please use the resource names and link to the corresponding topics to provide more context.

2021-07-10 08:53 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-managementactiontenantdeploymentstatuses.md and fix links going to the file.

2021-07-10 08:53 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementintent-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-managementintents.md and fix links going to the file.

2021-07-10 08:54 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-managementtemplate-list.md
> +title: "List managementTemplates"
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-managementtemplates.md and fix links going to the file.

2021-07-10 08:56 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-riskyuser-list.md
> +title: "List riskyUsers"
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-riskyusers.md and fix links going to the file.

2021-07-10 08:56 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenant-list.md
> +title: "List tenants"
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-tenants.md and fix links going to the file.

2021-07-10 09:05 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenant-offboardtenant.md
> +Offboards the specified managed tenant from the multi-tenant management platform.
Line 15:
Can you use another phrase in place of "offboard"? 
What do you think of "Carries out the appropriate procedures to remove a managed tenant from a managed service provider"?
You probably can provide a more insightful description for offboarding tenants.

2021-07-10 09:15 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenant-resettenantonboardingstatus.md
> +Resets the onboarding status for the specified managed tenant.
Line 15:
Can you clarify upon a successful call of this method, exactly which property gets "reset" to what value?

BTW, like I mentioned in another topic with a GLOBAL comment, this method would be a good example to show the importance and effectiveness of an example that includes real-looking property values!

GLOBAL repeat:
Please make sure you provide real examples and do not use the JSON definition of the response type in example response bodies. That is actually very confusing.

2021-07-10 09:16 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenantcustomizedinformation-list.md
> +# List tenantCustomizedInformations
Line 10:
The topic title should use the navigation property name, "List tenantsCustomizedInformation". Please change that.

2021-07-10 09:16 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenantcustomizedinformation-list.md
> +title: "List tenantCustomizedInformations"
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-tenantscustomizedinformation.md and fix links going to the file.

2021-07-10 09:18 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenantdetailedinformation-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-tenantsdetailedinformation.md and fix links going to the file.

2021-07-10 09:18 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenantdetailedinformation-list.md
> +# List tenantDetailedInformations
Line 10:
Please change the topic title to use the nav property name, that is, "List tenantsDetailedInformation".

2021-07-10 09:19 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenantgroup-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-tenantgroups.md and fix links going to the file.

2021-07-10 09:25 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenanttag-assigntag.md
> +    "@odata.type": "#microsoft.graph.managedTenants.tenantTag",
Line 88:
"value"? Doesn't look quite right. At least not when comparing with the example of the api.md file. Can you please double check?

2021-07-10 09:27 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenanttag-create.md
> +title: "Create tenantTag"
In general, a create operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-post-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-post-tenanttags.md and fix links going to the file.

2021-07-10 09:28 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenanttag-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-tenanttags.md and fix links going to the file.

2021-07-10 09:34 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-tenanttag-update.md
> +The following table shows the properties that are required when you update the [tenantTag](../resources/managedtenants-tenanttag.md).
Line 45:
Did the stub topic generator generate this line? I think this is a tracked bug.
Can you customize the sentence to what your PATCH operation actually requires?

For consistency, you can take a look at this topic: https://docs.microsoft.com/en-us/graph/api/printershare-update?view=graph-rest-beta&tabs=http#request-body

2021-07-10 09:35 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-windowsdevicemalwarestates.md and fix links going to the file.

2021-07-10 09:36 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-windowsprotectionstate-list.md
> +---
In general, a list operation filename should follow this pattern: {subnamespace-name}-{parent-resource-name}-list-{navigation-property-name}.md

In this case, please rename the file as  managedtenants-managedtenant-list-windowsprotectionstates.md and fix links going to the file.

2021-07-10 09:45 UTC, angelgolfer-ms requested changes
@isaiahwilliams , I have reviewed more than half of the topics in this PR (all the operation and method topics, and some of the resource topics). As mentioned in an earlier comment, there's feedback (comments) that I called out as "GLOBAL". Please make sure you apply the appropriate change to all the topics in this PR that are applicable; I didn't enter a comment for every instance.

Some major themes:
(a) Please make the descriptions of resources and methods more informative by providing some more context.
(b) Please replace the generated pseudo examples with real-looking examples that have actual property values. Please don't repeat the JSON definition in example request or response bodies. Customers do ask about how the actual property values look like, and so examples are an intuitive place to look for the answers!
(c) Please fix the filenames for the "list" operation topics.

2021-07-11 13:44 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-windowsprotectionstate-list.md
> +---
@angelgolfer-ms thank you for adding this comment, I am working through the appropriate updates right now. Also, with the new round of updates I will see if there is a process issue since these filenames were auto generated. Which means I would have expected these to be correct. None the less, I will be getting them all updated following the guidance that you shared.

2021-07-11 14:11 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-windowsprotectionstate-list.md
> +---
The filename has been updated and the change pushed.

2021-07-11 14:11 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-windowsdevicemalwarestate-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:11 UTC, opbld33 commented
Docs Build status updates of commit _[89c918a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89c918afc7d2e3beee66e66e22c41135751d1c50)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-1319862e)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-1319862e)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-1319862e)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-1319862e)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-1319862e)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-1319862e)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-1319862e)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-1319862e)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-1319862e)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-1319862e)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-1319862e)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-1319862e)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-1319862e)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-1319862e)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-11 14:11 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenanttag-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:12 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenantgroup-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:12 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenantdetailedinformation-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:12 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenantcustomizedinformation-list.md
> +title: "List tenantCustomizedInformations"
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:12 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenant-list.md
> +title: "List tenants"
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:12 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-riskyuser-list.md
> +title: "List riskyUsers"
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:12 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementtemplate-list.md
> +title: "List managementTemplates"
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:13 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementintent-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:13 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:13 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementaction-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:13 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-manageddevicecompliancetrend-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:13 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-manageddevicecompliance-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:13 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-devicecompliancepolicysettingstatesummary-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:13 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-credentialuserregistrationssummary-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:14 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:14 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:14 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-cloudpcconnection-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:14 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-cloudpcdevice-list.md
> +---
Thank you for flagging this, the filename has been updated and the change has been pushed.

2021-07-11 14:17 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-cloudpcoverview-list.md
> +---
@angelgolfer-ms - Yes, the stub topic generator was used to create all the files. Each of the list operations has been updated to reflect the guidance you have provided. As we move forward, I will review our process to see if there was something on our end that caused these files to have the incorrect name. If any issue with the stub generator is discovered, I will be sure to report it. Thank you for taking the time to go through and flag each incorrect filename and providing the appropriate new name.

2021-07-11 14:29 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenanttag-assigntag.md
> +    "@odata.type": "#microsoft.graph.managedTenants.tenantTag",
Thank you for flagging this item, I thought that I had fixed all of these. The stub generator created the examples, and I am not sure why value was added in a handful of places where it does apply. When I pushed the next round of changes this issue will be resolved.

2021-07-11 14:31 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenantdetailedinformation-list.md
> +# List tenantDetailedInformations
Thank you for catching this one. When I push the next round of changes this issue will be resolved.

2021-07-11 14:31 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenantcustomizedinformation-list.md
> +# List tenantCustomizedInformations
Thank you for catching this one. When I push the next round of changes this issue will be resolved.

2021-07-11 14:34 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenanttag-create.md
> +title: "Create tenantTag"
Thank you for flagging this item. When I push the next round of changes this issue will be resolved.

2021-07-11 14:37 UTC, opbld31 commented
Docs Build status updates of commit _[82795b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82795b04c228a9d0dd5a427f152013d6cb998b22)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-d5fb8d85)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-d5fb8d85)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-d5fb8d85)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-d5fb8d85)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-d5fb8d85)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-d5fb8d85)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-d5fb8d85)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-d5fb8d85)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-d5fb8d85)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-d5fb8d85)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-d5fb8d85)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-d5fb8d85)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-d5fb8d85)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-d5fb8d85)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-11 16:17 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md
> +{
With respect to this specific entity, the example has been updated. I am currently working through getting all of the examples updated with real world responses.

2021-07-11 16:18 UTC, opbld31 commented
Docs Build status updates of commit _[e144a82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e144a82b8893ed72f093311298c9fff16eb148a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-a37b0c5d)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-a37b0c5d)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-a37b0c5d)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-a37b0c5d)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-a37b0c5d)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-a37b0c5d)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-a37b0c5d)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-a37b0c5d)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-a37b0c5d)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-a37b0c5d)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-a37b0c5d)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-a37b0c5d)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-a37b0c5d)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-a37b0c5d)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-11 16:48 UTC, opbld32 commented
Docs Build status updates of commit _[b118874](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1188745d4548266b1f7c2fa5b349a53cb78c180)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-6995e73a)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-6995e73a)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-6995e73a)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-6995e73a)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-6995e73a)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-6995e73a)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-6995e73a)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-6995e73a)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-6995e73a)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-6995e73a)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-6995e73a)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-6995e73a)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-6995e73a)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-6995e73a)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-11 18:22 UTC, opbld33 commented
Docs Build status updates of commit _[8ee247b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ee247b3aab9e34e125f205efa950a8127897ff3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-2a5baa72)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-2a5baa72)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-2a5baa72)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-2a5baa72)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-2a5baa72)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-2a5baa72)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-2a5baa72)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-2a5baa72)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-2a5baa72)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-2a5baa72)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-2a5baa72)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-2a5baa72)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-2a5baa72)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-2a5baa72)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-11 19:05 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-changedeploymentstatus.md
> +|status|String|The new status for the management action tenant deployment.|
This is great feedback, thank you for adding this comment. Changes have been made locally and when I commit the next round of updates it will be reflected here.

2021-07-11 19:14 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenant-offboardtenant.md
> +Offboards the specified managed tenant from the multi-tenant management platform.
Yes, and I agree with this feedback. Updates have been made locally and will be committed shortly.

2021-07-11 19:15 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenanttag-update.md
> +The following table shows the properties that are required when you update the [tenantTag](../resources/managedtenants-tenanttag.md).
Yes, this was generated using the stub topic generator. Thank you for providing a reference I have updated the markdown locally. The changes will be committed shortly.

2021-07-11 19:19 UTC, opbld33 commented
Docs Build status updates of commit _[c8ff779](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8ff7790e232595b1011f707b4f71756d2a8ff46)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-a4e5d9b7)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-a4e5d9b7)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-a4e5d9b7)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-a4e5d9b7)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-a4e5d9b7)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-a4e5d9b7)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-a4e5d9b7)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-a4e5d9b7)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-a4e5d9b7)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-a4e5d9b7)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-a4e5d9b7)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-a4e5d9b7)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-a4e5d9b7)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-a4e5d9b7)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-11 20:04 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-tenant-resettenantonboardingstatus.md
> +Resets the onboarding status for the specified managed tenant.
Thank you for adding this feedback, it makes sense, and we want to do everything to avoid adding confusion. Updates have been made locally and will be committed later today.

2021-07-11 20:24 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-aggregatedpolicycompliance-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Thank you for catching this and adding the comment. Updates have been made locally and will be committed shortly.

2021-07-11 21:11 UTC, isaiahwilliams commented on api-reference/beta/resources/managedtenants-aggregatedpolicycompliance.md
> +|Property|Type|Description|
Thank you for flagging this item. An update was just made to incorporate this feedback.

2021-07-11 21:13 UTC, isaiahwilliams commented on api-reference/beta/resources/managedtenants-conditionalaccesspolicycoverage.md
> +
Thank you for the suggestion. I have incorporated it locally and will commit the change later today.

2021-07-11 21:13 UTC, opbld33 commented
Docs Build status updates of commit _[191ddf5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/191ddf5bb90dfab1d6bf4ad9f60a451e6e750a8f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-0c929c48)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-0c929c48)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-0c929c48)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-0c929c48)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-0c929c48)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-0c929c48)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-0c929c48)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-0c929c48)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-0c929c48)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-0c929c48)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-0c929c48)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-0c929c48)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-0c929c48)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-0c929c48)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 02:44 UTC, isaiahwilliams commented on api-reference/beta/toc.yml
> +          - name: Get cloud PC connection
Thank you for sharing the context for this feedback. Changes have been made locally and will be committed shortly.

2021-07-12 02:56 UTC, opbld34 commented
Docs Build status updates of commit _[dfbe1f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfbe1f98c35e433a15c020202542f0ffee80de52)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-f1c95697)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-f1c95697)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-f1c95697)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-f1c95697)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-f1c95697)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-f1c95697)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-f1c95697)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-f1c95697)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-f1c95697)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-f1c95697)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-f1c95697)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-f1c95697)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-f1c95697)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-f1c95697)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 03:10 UTC, opbld32 commented
Docs Build status updates of commit _[667b665](https://github.com/microsoftgraph/microsoft-graph-docs/commits/667b6659f98e06b55b94a3a7f6cf612ae5d7d427)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-a9225278)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-a9225278)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-a9225278)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-a9225278)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-a9225278)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-a9225278)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-a9225278)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-a9225278)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-a9225278)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-a9225278)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-a9225278)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-a9225278)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-a9225278)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-a9225278)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 03:22 UTC, opbld30 commented
Docs Build status updates of commit _[8b25294](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b2529436356831c680346bea34fd78898c71943)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 03:30 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-conditionalaccesspolicycoverage-list.md
> +Get a list of the [conditionalAccessPolicyCoverage](../resources/managedtenants-conditionalaccesspolicycoverage.md) objects and their properties.
This is great feedback! Added the recommended sentence to this operation. With respect to the other operations, I will go through and provide additional information.

2021-07-12 03:30 UTC, opbld32 commented
Docs Build status updates of commit _[6ea53c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ea53c86e4da8a9e3f7fb885085ad7638e2a7e1c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-950aa905)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-950aa905)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-950aa905)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-950aa905)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-950aa905)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-950aa905)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-950aa905)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-950aa905)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-950aa905)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-950aa905)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-950aa905)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-950aa905)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-950aa905)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-950aa905)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 14:34 UTC, opbld30 commented
Docs Build status updates of commit _[468de50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/468de50919089d77ace9033ad086afb9b70ba1ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-eee20b43)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-eee20b43)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-eee20b43)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-eee20b43)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-eee20b43)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-eee20b43)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-eee20b43)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-eee20b43)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-eee20b43)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-eee20b43)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-eee20b43)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-eee20b43)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-eee20b43)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-eee20b43)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 14:35 UTC, opbld34 commented
Docs Build status updates of commit _[a594826](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a59482662f4c427f81e6526a168423f9555c8abb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-0e626e0b)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-0e626e0b)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-0e626e0b)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-0e626e0b)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-0e626e0b)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-0e626e0b)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-0e626e0b)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-0e626e0b)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-0e626e0b)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-0e626e0b)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-0e626e0b)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-0e626e0b)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-0e626e0b)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-0e626e0b)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 15:38 UTC, isaiahwilliams commented on api-reference/beta/resources/managedtenants-managementaction.md
> +
Just realized this was missed. The change has been made locally and will be committed shortly.

2021-07-12 15:39 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementaction-apply.md
> +
This change has been made. When we go back to add the snippets after they are generated, I will make sure we have not missed any other areas.

2021-07-12 15:43 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementaction-apply.md
> +Applies the management action against the specified managed tenant.
Just realized this comment has not been resolved. Changes have been made locally and will be committed shortly.

2021-07-12 15:50 UTC, isaiahwilliams commented on api-reference/beta/api/managedtenants-managementactiontenantdeploymentstatus-changedeploymentstatus.md
> +
Thank you for flagging this item, I did not realize it was not already resolved. Changes have been made locally and will be committed shortly.

2021-07-12 17:13 UTC, isaiahwilliams commented
Closed and re-opened this pull request because one of the validation checks was stuck in pending. This should have requeued each of them.

2021-07-12 19:16 UTC, opbld34 commented
Docs Build status updates of commit _[e61667b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e61667b363cef54272fcb5ef128079e4e72be530)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-a3dbb56c)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-a3dbb56c)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-a3dbb56c)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-a3dbb56c)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-a3dbb56c)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-a3dbb56c)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-a3dbb56c)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-a3dbb56c)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-a3dbb56c)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-a3dbb56c)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-a3dbb56c)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-a3dbb56c)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-a3dbb56c)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-a3dbb56c)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 20:11 UTC, opbld30 commented
Docs Build status updates of commit _[bddf762](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bddf7625c133277c17065c8b3e0692abac3a1b7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-297de4ea)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-297de4ea)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-297de4ea)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-297de4ea)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-297de4ea)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-297de4ea)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-297de4ea)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-297de4ea)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-297de4ea)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-297de4ea)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-297de4ea)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-297de4ea)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-297de4ea)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-297de4ea)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-12 23:29 UTC, opbld34 commented
Docs Build status updates of commit _[48c5878](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48c58781fd31af69e3dda633bb286e094f252e20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-377f9a11)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-377f9a11)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-377f9a11)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-377f9a11)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-377f9a11)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-377f9a11)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-377f9a11)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-377f9a11)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-377f9a11)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-377f9a11)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-377f9a11)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-377f9a11)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-377f9a11)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-377f9a11)
[concepts/managedtenants-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/concepts/managedtenants-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/managedtenants-concept-overview?branch=pr-en-us-13285) | [Details](#user-content-03f19db1b54af825eed2b80e6ecc9f40-377f9a11)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-refere [...]

2021-07-13 02:28 UTC, opbld33 commented
Docs Build status updates of commit _[c9c08d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9c08d0fe8fb0913ba40455c3e2d396228575066)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-01957c76)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-01957c76)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-01957c76)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-01957c76)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-01957c76)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-01957c76)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-01957c76)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-01957c76)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-01957c76)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-01957c76)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-01957c76)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-01957c76)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-01957c76)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-01957c76)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-13 02:30 UTC, opbld34 commented
Docs Build status updates of commit _[8c61823](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c61823ddb87e95b284b2f9b2c8bb3394b8d3939)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyuser?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-52b397398e3d2705c865d3b54bb928f4-868ab3d9)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-868ab3d9)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-868ab3d9)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-868ab3d9)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-868ab3d9)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-868ab3d9)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-868ab3d9)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-868ab3d9)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-868ab3d9)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-868ab3d9)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-868ab3d9)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-868ab3d9)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-868ab3d9)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-868ab3d9)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighth [...]

2021-07-13 02:30 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +The root resource that represents the capabilities available to a Managed Service Provider (MSP) to scale the remote management of its customer tenants.
Line 16:
@isaiahwilliams , for the time being, because this topic is the top level topic in the API reference until you get the API overview, I felt we should make the description a bit more informative. Please see if I got this correct and if I didn't, pleas e update as appropriate.

Line 18: 
This line usually goes to the API overview topic and is redundant in a reference topic because line 12 refers to a similar message. 

After we get the API overview topic, please delete this line 18 (if we remember :-D)!

2021-07-13 02:33 UTC, angelgolfer-ms commented on concepts/managedtenants-concept-overview.md
@isaiahwilliams , please take a look at the updates I made in this topic. I tried to break up the original line 13 a bit to make it more readable, and also to emphasize that the customer is an MSP.

2021-07-13 02:34 UTC, angelgolfer-ms commented on concepts/managedtenants-concept-overview.md
> +- Find out about the [latest new features and updates](/graph/whats-new-overview) for the Lighthouse API.
Line 48:
In a conceptual overview like this one, I would recommend not referring to the changelog topic. The changelog is very deep into the weeds of an API set. The what's new topic would be more viewer friendly.

2021-07-13 02:49 UTC, isaiahwilliams commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +The root resource that represents the capabilities available to a Managed Service Provider (MSP) to scale the remote management of its customer tenants.
This looks great! I will make sure we track the need to remove this once the overview is completed.

2021-07-13 02:50 UTC, isaiahwilliams commented on concepts/managedtenants-concept-overview.md
> +- Find out about the [latest new features and updates](/graph/whats-new-overview) for the Lighthouse API.
Thank you for changing this, it definitely makes more sense to reference the easier to consume article.

2021-07-13 02:53 UTC, opbld34 commented
Docs Build status updates of commit _[656f4ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/656f4eabff8032e568e1d19f80cc6e3dbcde10d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyusers?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1de3ba7bbf09c39ff0b54397c1a8cfd1-83b6387d)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-83b6387d)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-83b6387d)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-83b6387d)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-83b6387d)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-83b6387d)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-83b6387d)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-83b6387d)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-83b6387d)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-83b6387d)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-83b6387d)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-83b6387d)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-83b6387d)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-83b6387d)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lig [...]

2021-07-13 02:54 UTC, isaiahwilliams commented on concepts/managedtenants-concept-overview.md
> +You can use the Lighthouse API to perform the following device tasks:
@angelgolfer-ms do you think that we might confuse partners this change because there is Azure Lighthouse and now Microsoft 365 Lighthouse. While Azure Lighthouse does not have functionality exposed in Microsoft Graph, it might cause some confusion.

2021-07-13 03:31 UTC, opbld31 commented
Docs Build status updates of commit _[01fbade](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01fbadeb5a788a565dfdd57ed94be9dd73b59e6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyusers?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1de3ba7bbf09c39ff0b54397c1a8cfd1-f98c2525)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-f98c2525)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-f98c2525)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-f98c2525)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-f98c2525)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-f98c2525)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-f98c2525)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-f98c2525)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-f98c2525)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-f98c2525)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-f98c2525)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-f98c2525)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-f98c2525)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-f98c2525)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lig [...]

2021-07-13 03:34 UTC, isaiahwilliams commented on concepts/managedtenants-concept-overview.md
Thank you for making these updates they look great and should help provide clear.

2021-07-13 03:36 UTC, isaiahwilliams commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +
This was a great catch! Had not realized that I missed a letter. Since we have changed what has been included in this article, I will mark the comment as resolved.

2021-07-13 03:38 UTC, isaiahwilliams commented on api-reference/beta/resources/managedtenants-managedtenant.md
> +
This feedback makes sense, and I will be sure to keep this in mind as we add more articles. Reference of `multi-tenant management platform` was me trying to avoid using product names. Looking through the documentation I do not believe that is an issue, so we can change the references. Since we are trying to wrap up this initial push, I can add this as an item we will address through another PR that can be opened this week.

2021-07-13 03:39 UTC, isaiahwilliams commented on concepts/managedtenants-concept-overview.md
> +You can use the Lighthouse API to perform the following device tasks:
This has been addressed through an offline conversation. There are no further concerns on this front. So, I will makr this comment as resolved.

2021-07-13 03:41 UTC, angelgolfer-ms commented on concepts/managedtenants-concept-overview.md
> +You can use the Lighthouse API to perform the following device tasks:
Good reminder, thanks, addressed this as discussed on Teams. See if the experience is clearer now?

2021-07-13 03:43 UTC, isaiahwilliams commented on concepts/managedtenants-concept-overview.md
> +You can use the Lighthouse API to perform the following device tasks:
With the recent updates we are in good shape on this front. Thank you for taking the time to help make the appropriate changes.

2021-07-13 06:40 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcconnection-get.md
> +GET https://graph.microsoft.com/beta/tenantRelationships/managedTenants/cloudPcConnections/{cloudPcConnectionId}
After we publish, can you please do the similar for the example requests of other GET, PATCH, and DELETE operations?

2021-07-13 07:08 UTC, angelgolfer-ms commented on api-reference/beta/api/managedtenants-cloudpcconnection-get.md
> +## Optional query parameters
GLOBAL and line 17:
Please include those OData query parameters (OData system query options) that actually applies to a GET operation of a specified resource (instead of getting a collection of resources). Would that be just the $select parameter?

2021-07-13 07:18 UTC, opbld30 commented
Docs Build status updates of commit _[82fad02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82fad0269651145cf1549f64386b295d113609fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyusers?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1de3ba7bbf09c39ff0b54397c1a8cfd1-ae6b4392)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-ae6b4392)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-ae6b4392)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-ae6b4392)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-ae6b4392)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-ae6b4392)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-ae6b4392)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-ae6b4392)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-ae6b4392)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-ae6b4392)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-ae6b4392)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-ae6b4392)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-ae6b4392)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-ae6b4392)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lig [...]

2021-07-13 07:22 UTC, angelgolfer-ms commented on api-reference/beta/resources/managedtenants-managedtenant.md
FYI in line 16, I added "Microsoft 365 Lighthouse API" because otherwise line 18 is kind of odd - nowhere else in the topic content connects this resource with the API name. 
If the customer landed in this topic from a link or from search in general, in a smaller screen where the TOC is not displayed side-by-side with the topic content, not having mentioned "Microsoft 365 Lighthouse API" before line 18 can be disorienting.

2021-07-13 07:25 UTC, angelgolfer-ms commented on concepts/managedtenants-concept-overview.md
> +# Overview for multi-tenant management using the Microsoft 365 Lighthouse API
Line 9: 
FYI I added more words to the topic title to make it relate to the TOC title ("Multi-tenant management") better. Otherwise if a customer clicks the topic in the TOC to display this topic, and notices that the TOC title and topic title don't share any words or phrase, that may make new customers wonder if they got to the wrong topic.

2021-07-13 07:27 UTC, angelgolfer-ms commented on concepts/managedtenants-concept-overview.md
> +Microsoft 365 Lighthouse helps MSPs simplify onboarding of Microsoft 365 Business Premium customer tenants. It offers an MSP the convenience of multi-tenant views across all its customer tenant envir
Line 13 and 20:
Per Microsoft writing style about anything pertaining to security - we only say we _help_ make such and such more secure.

2021-07-13 07:28 UTC, angelgolfer-ms commented on concepts/overview-major-services.md
> +| Multi-tenant management (preview) | Microsoft 365 Lighthouse | Lets Managed Service Providers (MSPs) remotely manage multiple customer tenants for compliance and threats, and help get tenant device
I attempted to fill this in for this debut workload, please feel free to elaborate when you do your pass later in the week.

2021-07-13 07:30 UTC, opbld32 commented
Docs Build status updates of commit _[b3c1e08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3c1e08b1a371f2601203fbdb0faf4925d802fd9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyusers?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1de3ba7bbf09c39ff0b54397c1a8cfd1-52625dec)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-52625dec)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-52625dec)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-52625dec)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-52625dec)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-52625dec)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-52625dec)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-52625dec)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-52625dec)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-52625dec)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-52625dec)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-52625dec)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-52625dec)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-52625dec)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lig [...]

2021-07-13 07:41 UTC, opbld32 commented
Docs Build status updates of commit _[91b6e2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91b6e2b8ee1d92aa940fb9d69e789dea1e4d5cb9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-riskyusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-riskyusers?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1de3ba7bbf09c39ff0b54397c1a8cfd1-5cd01ce5)
[api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-managedtenant-list-windowsdevicemalwarestates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-windowsdevicemalwarestates?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ee24379a2d855b3ad937499a0e9fde87-5cd01ce5)
[api-reference/beta/api/managedtenants-riskyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-riskyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-riskyuser-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-94c3126f3e69feef8008659aa3266ffc-5cd01ce5)
[api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-3e59ee1bee5dc52c2de733e24527e724-5cd01ce5)
[api-reference/beta/api/managedtenants-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-dae1902a11f6a9f235b35b73200aa4d9-5cd01ce5)
[api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-22006ffdb1f0342503ed4997567b563a-5cd01ce5)
[api-reference/beta/resources/managedtenants-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/managedtenants-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/managedtenants-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1ce67f4e8d05e6f77d5228c5dadd166c-5cd01ce5)
[api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsdevicemalwarestate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsdevicemalwarestate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-25a2bbbe4a1cb7ddcc8d19981cbb3e84-5cd01ce5)
[api-reference/beta/api/riskyusers-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-1c6e31188eed04b5c62660fef2c9fc48-5cd01ce5)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ebee6a93df5e3172d0d62df08b19e404-5cd01ce5)
[api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsdevicemalwarestate-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsdevicemalwarestate-list?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ae46524659d2cc76bde7337dfeae99da-5cd01ce5)
[api-reference/beta/api/intune-devices-windowsprotectionstate-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/intune-devices-windowsprotectionstate-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-devices-windowsprotectionstate-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-ab50995c4a99849f9d3d5cf77579aca5-5cd01ce5)
[api-reference/beta/api/riskyusers-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/riskyusers-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/riskyusers-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-4a4e3067946d18d6773b8b61d652cf45-5cd01ce5)
[api-reference/beta/resources/intune-devices-windowsprotectionstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/resources/intune-devices-windowsprotectionstate.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsprotectionstate?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) | [Details](#user-content-f47eeeff674e42bff1ef115f0cfaf0de-5cd01ce5)
[api-reference/beta/api/managedtenants-cloudpcconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcconnection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcconnection-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcdevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lighthouse-docs/api-reference/beta/api/managedtenants-cloudpcdevice-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/managedtenants-cloudpcdevice-get?view=graph-rest-beta&branch=pr-en-us-13285) (graph-rest-beta) |
[api-reference/beta/api/managedtenants-cloudpcoverview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/iswillia/m365-lig [...]

2021-07-13 07:44 UTC, merged