deprecate userflows
microsoftgraph/microsoft-graph-docs pull request #13327
Opened 2021-06-29 19:44 UTC by navdha247

2021-06-29 19:45 UTC, opbld33 commented
Docs Build status updates of commit _[74f6c35](https://github.com/navdha247/microsoft-graph-docs/commits/74f6c351e5d4a5949be4ae8423e4f11e3cad35dc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-989efe19)

<a id="0817dce4456c16725d5333633847d38f-989efe19"></a>
### [api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml)
 - **Line 11336, Column 19**: **[Error-yaml-syntax-error]** `````Block sequence entries are not allowed in this context.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106291944100459-13327%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y7kDoN3ktWkE47FPShQTJc55rg%2BvY6tir2Rj3FjnuAE%3D&st=2021-06-29T19%3A40%3A27Z&se=2021-07-30T19%3A45%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 19:18 UTC, opbld31 commented
Docs Build status updates of commit _[89e4de6](https://github.com/navdha247/microsoft-graph-docs/commits/89e4de64aeec00b519faae4e89788a118d031b37)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-bf0eb9af)

<a id="0817dce4456c16725d5333633847d38f-bf0eb9af"></a>
### [api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml)
 - **Line 11525, Column 19**: **[Error-yaml-syntax-error]** `````Block sequence entries are not allowed in this context.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131915404170-13327%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A34%3A59Z&ske=2021-07-20T08%3A39%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T19%3A13%3A01Z&se=2021-08-13T19%3A18%3A01Z&sr=b&sp=r&sig=%2BNa5OLeYs%2FenZxWtqsPXd%2B%2FwzKwCzTXanwxOKx55Hs4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 19:22 UTC, opbld30 commented
Docs Build status updates of commit _[3ca0670](https://github.com/navdha247/microsoft-graph-docs/commits/3ca067061d851795cf4ba72f68ee2080170ecf86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflow-delete.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-get.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-get?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-list.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-list?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-post-userflows.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-post-userflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflow.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/resources/identityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/includes/identityuserflow-deprecate.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/includes/identityuserflow-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131920572206-13327%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A31%3A12Z&ske=2021-07-20T08%3A36%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T19%3A17%3A28Z&se=2021-08-13T19%3A22%3A28Z&sr=b&sp=r&sig=qziFyClCLcdesICnFBFyrEmotLNRV3CQtcCQQjuaRv8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 22:24 UTC, opbld30 commented
Docs Build status updates of commit _[54a00e9](https://github.com/navdha247/microsoft-graph-docs/commits/54a00e9bed405e589a7b191a81972a707285f353)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7938bfa6)

<a id="7938bfa6"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132222421077-13327%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A02%3A24Z&ske=2021-07-20T08%3A07%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T22%3A19%3A05Z&se=2021-08-13T22%3A24%3A05Z&sr=b&sp=r&sig=zmby70RD5sq8BOzEzY8fxhM%2BfS8h2ID4xbFLE5Dwx7E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 22:36 UTC, opbld33 commented
Docs Build status updates of commit _[8ab18bb](https://github.com/navdha247/microsoft-graph-docs/commits/8ab18bb135591de377003b06aa8f6575365bf38d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflow-delete.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-get.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-get?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-list.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-list?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-post-userflows.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-post-userflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflow.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/resources/identityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/includes/identityuserflow-deprecate.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/includes/identityuserflow-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132234093624-13327%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A34Z&ske=2021-07-20T08%3A20%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T22%3A31%3A08Z&se=2021-08-13T22%3A36%3A08Z&sr=b&sp=r&sig=OPTvvWFpNWWyE7ZL7jDDLZIAl%2BTBDRLAW39oVZER4Is%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 04:13 UTC, Lauragra commented on api-reference/includes/identityuserflow-deprecate.md
> +> This user flow API is deprecated and will stop returning data on January, 2022. Please use the [B2C User Flow APIs](/graph/api/resources/b2cidentityuserflow) or [Self-Service Sign Up User Flow APIs
Do you want to provide a specific date in January? Otherwise, change "on" to "in" to convey that it takes place during the month of January. Also note that the names of the APIs should not be title cased.

2021-07-16 03:04 UTC, Lauragra commented
@FaithOmbongi , can you please review and approve? Thanks!

2021-07-16 06:18 UTC, FaithOmbongi requested changes

2021-07-16 06:18 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
Because the resource + all methods are deprecated, no need to list all the methods. Just summarize them in the description for the deprecated resource. See guidance: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103183/Deprecate-docs
```suggestion
        {
          "Id": "f46a7363-009c-4649-81d4-de52390bb26b",
          "ApiChange": "Method",
          "ChangedApiName": "identityUserFlow",
          "ChangeType": "Deprecation",
          "Description": "Deprecated  the [userFlow API](https://docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta) and related operations and methods. Replaced it with the new [b2cidentityuserflow API](https://docs.microsoft.com/en-us/graph/api/resources/b2cidentityuserflow?view=graph-rest-beta) and [b2xidentityuserflow API](https://docs.microsoft.com/en-us/graph/api/resources/b2xidentityuserflow?view=graph-rest-beta).",
          "Target": "identityUserFlow"
        }
```

2021-07-16 06:18 UTC, FaithOmbongi commented on api-reference/includes/identityuserflow-deprecate.md
> +> This user flow API is deprecated and will stop returning data on January, 2022. Please use the [B2C User Flow APIs](/graph/api/resources/b2cidentityuserflow) or [Self-Service Sign Up User Flow APIs
+1 for Laura's feedback.

2021-07-27 03:29 UTC, CelesteDG commented
@navdha247 Bringing this back up your queue as some changes are being requested. Thank you.

2021-08-13 06:56 UTC, FaithOmbongi requested changes
Feedback pending to be addressed.

2021-09-30 06:49 UTC, opbld31 commented
Docs Build status updates of commit _[0fe7af9](https://github.com/navdha247/microsoft-graph-docs/commits/0fe7af9508ec069e32e801874f743b0d341124c6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0f4ff8a6)

<a id="0f4ff8a6"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109300648036742-13327%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T06%3A49%3A37Z&sr=b&sp=r&sig=kZFeAlnb7ctQ%2BwcintugkCMkV3pZ4SZItwdOsmlx0Oo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-30 07:15 UTC, opbld31 commented
Docs Build status updates of commit _[b81d228](https://github.com/navdha247/microsoft-graph-docs/commits/b81d228228c2e6c682332988870a3b4a51e009ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflow-delete.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-get.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-get?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-list.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-list?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-post-userflows.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-post-userflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflow.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/resources/identityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/includes/identityuserflow-deprecate.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/includes/identityuserflow-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109300712504896-13327%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T07%3A15%3A34Z&sr=b&sp=r&sig=XTyFhqOjOi2Suj91tY9rINxcFb11Ek3QuAMVeMASiLs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 03:29 UTC, opbld30 commented
Docs Build status updates of commit _[eff9803](https://github.com/navdha247/microsoft-graph-docs/commits/eff980304737ddf47185027ef336c2142f427208)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflow-delete.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-get.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-get?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-list.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-list?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-post-userflows.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-post-userflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflow.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/resources/identityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/includes/identityuserflow-deprecate.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/includes/identityuserflow-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010328031000-13327%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T03%3A29%3A50Z&sr=b&sp=r&sig=NMPoSqnniF%2BTEyMIWjKn6CQXrvXOVyKaM7QXAMR0VUI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 03:31 UTC, opbld31 commented
Docs Build status updates of commit _[39fea42](https://github.com/navdha247/microsoft-graph-docs/commits/39fea42c06338fe680b8eb16bdef4ad9f2a8c61d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflow-delete.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-get.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-get?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-list.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-list?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-post-userflows.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-post-userflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflow.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/resources/identityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/includes/identityuserflow-deprecate.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/includes/identityuserflow-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010329039802-13327%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T03%3A31%3A34Z&sr=b&sp=r&sig=S4OY0n9f%2F2NMAzmJ%2B9qBNurlRT6CKO6vLwquOIXEeKg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 03:36 UTC, opbld31 commented
Docs Build status updates of commit _[9f35c9d](https://github.com/navdha247/microsoft-graph-docs/commits/9f35c9d61018864770318153d110691d3be5906a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflow-delete.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-get.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-get?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-list.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-list?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-post-userflows.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-post-userflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflow.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/resources/identityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/includes/identityuserflow-deprecate.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/includes/identityuserflow-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010334235107-13327%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T03%3A36%3A12Z&sr=b&sp=r&sig=Hz7SjBM8%2BI1F%2BsfPQ2PlWT7MHW4sGc%2FhGP%2FYDKTGFnI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 03:38 UTC, opbld33 commented
Docs Build status updates of commit _[f358f31](https://github.com/navdha247/microsoft-graph-docs/commits/f358f31953af052d7fa298bd380590fe0b5c4bb5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityuserflow-delete.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-get.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-get?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-list.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-list?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/api/identityuserflow-post-userflows.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/api/identityuserflow-post-userflows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/resources/identityuserflow.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/resources/identityuserflow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[api-reference/includes/identityuserflow-deprecate.md](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/api-reference/includes/identityuserflow-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityuserflow-delete?view=graph-rest-beta&branch=pr-en-us-13327) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/navdha247/microsoft-graph-docs/blob/nase-tocupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110010335143592-13327%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T03%3A38%3A16Z&sr=b&sp=r&sig=p2M929aOmkUgAN9K9Bbv0o8FLbLbZ7kNpgrNoJGYJhc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 03:48 UTC, merged

2021-10-01 04:54 UTC, navdha247 commented
Hi Laura,

Just checking if there is anything more I need to do at my end.
Or is it all done ?

Thanks,
Navdha

From: Laura Graham ***@***.***>
Sent: Thursday, September 30, 2021 8:49 PM
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Navdha Sethi ***@***.***>; Mention ***@***.***>
Subject: Re: [microsoftgraph/microsoft-graph-docs] deprecate userflows (#13327)


Merged #13327<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F13327&data=04%7C01%7Cnase%40microsoft.com%7Cd6f6b6b78e354cd1a0a008d9848e57d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637686569243102249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ouDLQ4rpnu0T0jnu7G5kH7zJsci7pLwsn0Pq89h6BNM%3D&reserved=0> into main.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F13327%23event-5391610194&data=04%7C01%7Cnase%40microsoft.com%7Cd6f6b6b78e354cd1a0a008d9848e57d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637686569243112248%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=elBGKPtc8GKmNE0eFeM6Qm%2Bl2DTwXTS8Rw8fKo1EKdw%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQJZ6XCM27PU5OIX3CPJVRDUEUVRFANCNFSM47Q4T6SA&data=04%7C01%7Cnase%40microsoft.com%7Cd6f6b6b78e354cd1a0a008d9848e57d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637686569243112248%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M0c3rm8hWBqqbpxG0QGEWIyxfg8JWy4FV4ct7yvMSHQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnase%40microsoft.com%7Cd6f6b6b78e354cd1a0a008d9848e57d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637686569243122245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KOPxtdNo03jhafEdblt6GgKw%2FeW8lBkWswbAY70%2BtXw%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnase%40microsoft.com%7Cd6f6b6b78e354cd1a0a008d9848e57d1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637686569243122245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b47d7tntm5zCz4WfM99c7QJEewJ6qCeCGy6oV3jR7oY%3D&reserved=0>.

2021-10-01 05:02 UTC, Lauragra commented
@navdha247 , you're all set.