adding search admin answers
microsoftgraph/microsoft-graph-docs pull request #13343
Opened 2021-06-30 20:16 UTC by jakeost-msft

Resolved merge conflicts by making a new branch, old PR here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/11920

2021-06-30 20:18 UTC, opbld32 commented
Docs Build status updates of commit _[df0e90d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df0e90d3cc702a9eee21961bef6e321ae37d4c12)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) | [Details](#user-content-e6534d1aa6c0bb8c5544352113edf13a-ff468280)
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) | [Details](#user-content-c4f24a98df82159022614eba2c6b0a57-ff468280)
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |

<a id="e6534d1aa6c0bb8c5544352113edf13a-ff468280"></a>
### [api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="c4f24a98df82159022614eba2c6b0a57-ff468280"></a>
### [api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-create.md'.`````
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-get.md'.`````
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-update.md'.``` [...]

2021-07-06 20:00 UTC, opbld34 commented
Docs Build status updates of commit _[6978801](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6978801631b16a5c165d6b2ddfb9822264efd587)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) | [Details](#user-content-e6534d1aa6c0bb8c5544352113edf13a-5a8cac0b)
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) | [Details](#user-content-c4f24a98df82159022614eba2c6b0a57-5a8cac0b)
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |

<a id="e6534d1aa6c0bb8c5544352113edf13a-5a8cac0b"></a>
### [api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="c4f24a98df82159022614eba2c6b0a57-5a8cac0b"></a>
### [api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-create.md'.`````
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-get.md'.`````
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-update.md'.``` [...]

2021-07-07 21:11 UTC, opbld34 commented
Docs Build status updates of commit _[de5240b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de5240be244dcbaf0458dd4617ae7b38d9010734)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) | [Details](#user-content-c4f24a98df82159022614eba2c6b0a57-65e5f0d7)
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |

<a id="c4f24a98df82159022614eba2c6b0a57-65e5f0d7"></a>
### [api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-list.md'.`````
 - **Line 23, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-create.md'.`````
 - **Line 24, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-get.md'.`````
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-update.md'.`````
 - **Line 26, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/searchanswer-delete.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107072108472657-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-07T06%3A33%3A23Z&ske=2021-07-14T06%3A38%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T21%3A06%3A12Z&se=2021-08-07T2 [...]

2021-07-07 21:12 UTC, opbld33 commented
Docs Build status updates of commit _[59bf8b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59bf8b4c81e6fff0edd9171e3e2fefaf9782360d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107072109396070-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A03%3A42Z&ske=2021-07-13T07%3A08%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T21%3A07%3A49Z&se=2021-08-07T21%3A12%3A49Z&sr=b&sp=r&sig=ZxsffLg57OpQP%2F8bwXbcm0vYaDOgj2EyGvst6AAgHXI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 21:20 UTC, opbld30 commented
Docs Build status updates of commit _[d76167f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d76167f4095cc20cce1f4e5ca7a71a2ef605ab0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122118103399-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A27%3A44Z&ske=2021-07-19T07%3A32%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T21%3A15%3A43Z&se=2021-08-12T21%3A20%3A43Z&sr=b&sp=r&sig=2%2BzuAGvY9CAjumgGEiPeSTxIyXWH8GFVy761J4bDwFQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 23:32 UTC, opbld30 commented
Docs Build status updates of commit _[6fde0bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fde0bccf4724a488340bc27647b93eaf78dfd44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122330052275-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A26%3A07Z&ske=2021-07-19T07%3A31%3A07Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T23%3A27%3A45Z&se=2021-08-12T23%3A32%3A45Z&sr=b&sp=r&sig=YqzyUBhQNr91hVW%2BCRSyWLq4kcPARVRYWiXoA%2F0g3%2Fo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 23:43 UTC, opbld30 commented
Docs Build status updates of commit _[6df361f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6df361fff83d4d170fc64f6f6554cf0ceb6da3d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122342086118-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A20%3A32Z&ske=2021-07-19T07%3A25%3A32Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T23%3A38%3A39Z&se=2021-08-12T23%3A43%3A39Z&sr=b&sp=r&sig=o%2B6A1j2r6XB01XeJYEOOIcjEHH6lhfZonKaWkS6fja4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 23:52 UTC, opbld31 commented
Docs Build status updates of commit _[da6b71e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da6b71e70f9ccd1c83cbc566e29e7189c48f41de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122351338517-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A38%3A44Z&ske=2021-07-19T07%3A43%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T23%3A47%3A54Z&se=2021-08-12T23%3A52%3A54Z&sr=b&sp=r&sig=Rp2Rv8L2xMR%2BOujkmhj5Z%2BVQk8hQvCZ6GX9xOuHYtRQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 00:00 UTC, opbld34 commented
Docs Build status updates of commit _[fc901d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc901d89aa500a9c727e0b596f199b9fc4127a9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122358448913-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A40%3A58Z&ske=2021-07-19T07%3A45%3A58Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T23%3A55%3A19Z&se=2021-08-13T00%3A00%3A19Z&sr=b&sp=r&sig=4q5%2BfQSK%2Fe243z2U8spMcTXzuqXbwsYgBYK%2Fi2ehExI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 19:09 UTC, opbld33 commented
Docs Build status updates of commit _[d242206](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d242206070d31788aeabe5354f9ee6315cbdea83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131907312217-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A45%3A57Z&ske=2021-07-20T07%3A50%3A57Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T19%3A04%3A08Z&se=2021-08-13T19%3A09%3A08Z&sr=b&sp=r&sig=VBhoZ6JIwyQoE4vNBhntRNC8KR44ftq1kb2reSPmvu4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 19:17 UTC, opbld32 commented
Docs Build status updates of commit _[cb8623b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb8623b1f3dd56fc4b312c34a04a49855107457e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131915456304-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A58%3A37Z&ske=2021-07-20T08%3A03%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T19%3A12%3A17Z&se=2021-08-13T19%3A17%3A17Z&sr=b&sp=r&sig=lyQihUJ%2BhdJQT0HMPIVAl5eIJh65k7ce%2FeAB5Vv%2BWB4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 19:22 UTC, opbld31 commented
Docs Build status updates of commit _[3b83867](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b83867c634d91a4a0eb5b61f62f9740eb096b5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/searchanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/searchanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchanswer?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[changelog/Microsoft.Search.Admin.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/changelog/Microsoft.Search.Admin.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131921125053-13343%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A34%3A59Z&ske=2021-07-20T08%3A39%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T19%3A17%3A40Z&se=2021-08-13T19%3A22%3A40Z&sr=b&sp=r&sig=CdDsLRk%2Bn4pcYgVlZEVlp3HQXLRywlWbfGdviKsrZhE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 17:14 UTC, opbld34 commented
Docs Build status updates of commit _[33e34dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33e34dd89f60023e7e177cd521309e8ec5252876)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https: [...]

2021-08-18 17:36 UTC, opbld34 commented
Docs Build status updates of commit _[32acd9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32acd9b2b4ecd42d5f99a13924049db1bf5c3e5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https: [...]

2021-08-18 18:18 UTC, opbld30 commented
Docs Build status updates of commit _[a4497b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4497b06a0bba96f3b6800df5a1d0682489eeb0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https: [...]

2021-08-18 18:25 UTC, opbld30 commented
Docs Build status updates of commit _[bf42b41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf42b416de9cc422412714ed5f0152776e59cadb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https: [...]

2021-09-16 20:27 UTC, JarbasHorst requested changes

2021-09-16 20:27 UTC, JarbasHorst commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +title: "Delete acronym"
GLOBAL: 

Setting **ms.date** to the date that a topic was published or updated is a best practice for SEO as it helps readers verify the currency of the content. Most topics don't currently include ms.date because it must be set manually. We recommend adding this value when you add or update content. In the future, ms.date will be automated via API Doctor. 

Value for ms.date must be a date in format M/D/YYYY, no more than 30 days from today.

2021-09-16 20:27 UTC, JarbasHorst commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +localization_priority: Normal
GLOBAL:

localization_priority isn't a valid property. Please replace localization_priority with ms.localizationpriority. Also, Normal is not on the list of approved values for ms.localizationpriority. Please change this to "medium".

2021-09-16 20:27 UTC, JarbasHorst commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +
GLOBAL:

The beta disclaimer must be added to all beta topics. Please, add \[!INCLUDE \[beta-disclaimer\]\(../../includes/beta-disclaimer.md)\] after the namespace. Suggested revision:

```
Namespace: microsoft.graph.search

[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
```

2021-09-16 20:27 UTC, JarbasHorst commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +|Delegated (work or school account)| Global administrator, search administrator, search editor. |
GLOBAL:

Global administrator, search administrator, and search editor are admin roles in Microsoft 365. For your app to access data in Microsoft Graph, the user or administrator must grant it the correct permissions (for example, _Sites.FullControl.All_) via a consent process. Please, replace the admin roles with the actual permission(s) that your API supports.

2021-09-16 20:27 UTC, JarbasHorst commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +|Permission type|Permissions (from most to least privileged)|
GLOBAL:

The boilerplate text needs to be consistent across the doc set. We shouldn't customize the standard boilerplate in the topics, just like we don't change or customize the H2 structure! In this case, please replace Permissions (from most to least privileged) with:

- Permissions (from least to most privileged)

2021-09-20 21:56 UTC, angelgolfer-ms commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +|Delegated (work or school account)| Global administrator, search administrator, search editor. |
@jakeost-msft , since you're using new permissions SearchConfiguration.Read.All and SearchConfiguration.ReadWrite.All, please add them to permissions-reference.md as well. You can follow the existing structure in that file for new permissions please.

2021-09-21 01:43 UTC, opbld32 commented
Docs Build status updates of commit _[c940c54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c940c54c910a5005f07d7447d23bbc3510d51a75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https: [...]

2021-09-21 02:09 UTC, angelgolfer-ms commented on api-reference/beta/resources/acronym.md
> +---
@jakeost-msft , the filenames for your entities and complex types that are defined in the search subnamespace should also be prefixed by the subnamespace name "search-", like those filenames for the API topics in this PR. Can you fix these entity and complex type filenames please?

2021-09-21 02:55 UTC, opbld31 commented
Docs Build status updates of commit _[6a78c81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a78c81a2902f4a13a00785ad573a0390868ecaa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/qna.md) | :white_check_mark:Succeeded | [View](https: [...]

2021-09-21 03:46 UTC, angelgolfer-ms commented on api-reference/beta/resources/searchanswer.md
> +
Line 14:
@jakeost-msft , it would be helpful if you can mention and link to the other search answer entities.
If you think over time, there will be an abundance of those, then for now, you can say:
"... is a base type for other search answers, such as acronym, bookmark, and QnA resources."
And provide links to those 3 types.

2021-09-21 21:36 UTC, JarbasHorst requested changes

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|webUrl|String|Bookmark url link. When users click this bookmark in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
Please, replace url with URL.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|categories|String collection|Categories commonly used to describe this bookmark. eg. IT, HR, etc.|
Please, avoid non-English words or phrases. In this case, please replace e.g. with for example. Also, for clarity, don't use etc. Instead be specific. Suggested revision:

- ...bookmark. For example, IT and HR.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|availabilityEndDateTime|DateTimeOffset|Date bookmark will stop appearing as a search result. Set as null for always available.|
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "appearing" to "to appear".

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
Should qna be replaced with bookmark?

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
For clarity, I recommend you to replace the acronym OS with operating system.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark. By adding existing PowerApps to a Bookmark, users can complete tasks like entering vacation time or reporting expenses on the search res
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark. By adding existing PowerApps to a Bookmark, users can complete tasks like entering vacation time or reporting expenses on the search res
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; Also, the word Bookmark don't need to be capitalized; in this case, I recommend you to rephrase this sentence. Suggested revision:

- If users add existing PowerApps to a bookmark, they can complete tasks, such as to enter vacation time or to report expenses on the search results page.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|isSuggested|Boolean|True if this bookmark was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
Please, replace Read only with Read-only.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +If successful, this method returns a `201 Created` response code with the id of the bookmark created.
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-qna-post-qnas.md
> +If successful, this method returns a `201 Created` response code with the id of the question and answer created.
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|id|String|Guid id of the qna. Inherited from [entity](../resources/entity.md).|
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/resources/searchanswer.md
> +|id|String|Guid id of the search answer. Inherited from [entity](../resources/entity.md).|
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +The following table shows the properties that are required when you update the [bookmark](../resources/bookmark.md).
For clarity, please change "the" to "a" because we are not talking about a particular one, but any. Suggested review:

-  ...when you update a [bookmark]...

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +The following table shows the properties that are required when you update the [bookmark](../resources/bookmark.md).
For clarity, the following table should list the properties that you can update. I recommend you to rephrase this sentence and list in the following table only the properties that are supported during an update request. For example, lastModifiedBy and lastModifiedDateTime are read-only and cannot be updated.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|webUrl|String|Bookmark url link. When users click this bookmark in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
Please, replace url with URL.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|categories|String collection|Categories commonly used to describe this bookmark. eg. IT, HR, etc.|
Please, avoid non-English words or phrases. In this case, please replace e.g. with for example. Also, for clarity, don't use etc. Instead be specific. Suggested revision:

- ...bookmark. For example, IT and HR.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|availabilityEndDateTime|DateTimeOffset|Date bookmark will stop appearing as a search result. Set as null for always available.|
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "appearing" to "to appear".

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
Should qna be replaced with bookmark?

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
For clarity, I recommend you to replace the acronym OS with operating system.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark. By adding existing PowerApps to a Bookmark, users can complete tasks like entering vacation time or reporting expenses on the search res
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark. By adding existing PowerApps to a Bookmark, users can complete tasks like entering vacation time or reporting expenses on the search res
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; Also, the word Bookmark don't need to be capitalized; in this case, I recommend you to rephrase this sentence. Suggested revision:

- If users add existing PowerApps to a bookmark, they can complete tasks, such as to enter vacation time or to report expenses on the search results page.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|isSuggested|Boolean|True if this bookmark was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
Please, replace Read only with Read-only.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/resources/acronym.md
> +|id|String|Guid id of the acronym. Inherited from [entity](../resources/entity.md).|
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/resources/bookmark.md
> +|id|String|Guid id of the bookmark. Inherited from [entity](../resources/entity.md).|
In regular text, please use ID as the abbreviation for identity.

2021-09-21 21:36 UTC, JarbasHorst commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +DELETE /acronyms/{acronymsId}
GLOBAL:

The HTTP request example should contain the entire path. In this case,

- `DELETE /acronyms/{acronymsId}` should be `DELETE /search/acronyms/{acronymsId}`

2021-09-21 21:55 UTC, opbld33 commented
Docs Build status updates of commit _[b7271c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7271c288c7adca825625959a5f981490e93edfc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/table-post-rows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) | [Details](#user-content-3d4ef16248555d21d47f9f4aef494875-ee967943)
[api-reference/beta/api/search-acronym-delete-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-se [...]

2021-09-21 21:56 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +localization_priority: Normal
#feedback-addressed

2021-09-21 21:56 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +
#feedback-addressed

2021-09-22 21:30 UTC, JarbasHorst requested changes

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/bookmark.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as null for always available.|
For clarity, I recommend you to emphasize null. Suggested revision:

- ...Set as \`null\` for...

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as null for always available.|
For clarity, I recommend you to emphasize null. Suggested revision:

- ...Set as \`null\` for...

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as null for always available.|
For clarity, I recommend you to emphasize null. Suggested revision:

- ...Set as \`null\` for...

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/api/search-qna-post-qnas.md
> +|availabilityStartDateTime|DateTimeOffset|Date qna will start to appear as a search result. Set as null for always available.|
For clarity, I recommend you to emphasize null. Suggested revision:

- ...Set as \`null\` for...

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/api/search-qna-update-qnas.md
> +|availabilityStartDateTime|DateTimeOffset|Date qna will start to appear as a search result. Set as null for always available.|
For clarity, I recommend you to emphasize null. Suggested revision:

- ...Set as \`null\` for...

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|availabilityStartDateTime|DateTimeOffset|Date qna will start to appear as a search result. Set as null for always available.|
For clarity, I recommend you to emphasize null. Suggested revision:

- ...Set as \`null\` for...

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|availabilityEndDateTime|DateTimeOffset|Date qna will stop appearing as a search result. Set as null for always available.|
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "appearing" to "to appear". Also, for clarity, I recommend you to emphasize null. Suggested revision:

- ...Set as \`null\` for...

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|id|String|Guid id of the qna. Inherited from [entity](../resources/entity.md).|
- The unique identifier (GUID) for the qna.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|webUrl|String|Qna url link. When users click this qna in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
Please, replace url with URL.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|lastModifiedBy|[microsoft.graph.identitySet](../resources/identityset.md)|Details of the user that created or last modified the qna. Inherited from [searchAnswer](../resources/searchanswer.md). Read
Please, replace Read only with Read-only.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|lastModifiedDateTime|DateTimeOffset| Timestamp of when the qna is created or edited. Inherited from [searchAnswer](../resources/searchanswer.md). Read only.|
Please, replace Read only with Read-only.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
For clarity, I recommend you to replace the acronym OS with operating systems.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|isSuggested|Boolean| True if this qna was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
Please, replace Read only with Read-only.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/acronym.md
> +description: "acronym"
The description field should generally be a one-sentence summary of what the article covers, and it shouldn't duplicate the title. This description potentially appears in search results. Please, add a description to this article.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +description: "Question and Answer search resource"
Please, add a period at the end of the sentence. Also, for clarity, I recommend you to rephrase this sentence. Suggested revision:

- Represents a question and answer (Q&A) in Microsoft Search.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +Q&As are administrative answer results in the search results page which provide answers for specific search keywords. Q&As allow administrators to answer the user's questions directly in search inste
Line 17, 18, and 19, please remove all backslashes.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/searchanswer.md
> +description: "searchAnswer"
The description field should generally be a one-sentence summary of what the article covers, and it shouldn't duplicate the title. This description potentially appears in search results. Please, add a description to this article.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/searchanswer.md
> +|id|String|Guid id of the search answer. Inherited from [entity](../resources/entity.md).|
- The unique identifier (GUID) for the search answer.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/searchanswer.md
> +|webUrl|String|Search answer url link. When users click this search answer in search results they will go to this url.|
Please, replace url with URL.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/searchanswer.md
> +|lastModifiedBy|[microsoft.graph.identitySet](../resources/identityset.md)|Details of the user that created or last modified the search answer. Read only.|
Please, replace Read only with Read-only.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/searchanswer.md
> +|lastModifiedDateTime|DateTimeOffset|Timestamp of when the search answer is created or edited. Read only.|
Please, replace Read only with Read-only.

2021-09-22 21:30 UTC, JarbasHorst commented on api-reference/beta/resources/searchanswer.md
> +Search answer is a base type for other search answers. Includes properties that apply to other search answer entities.
Articles help readers and translation software identify the nouns and modifiers in a sentence. Please, add A before search answer. Suggested revision:

- The search answer is a...

2021-09-23 20:45 UTC, JarbasHorst requested changes

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/resources/bookmark.md
> +|state|String|State of the bookmark. Possible values are: `published`, `draft`, `excluded`.|
According to the CSDL file, the correct type for state should be microsoft.graph.search.answerState. Please, replace String with microsoft.graph.search.answerState.

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/resources/qna.md
> +|state|String|State of the qna. Possible values are: `published`, `draft`, `excluded`.|
According to the CSDL file, the correct type for state should be microsoft.graph.search.answerState. Please, replace String with microsoft.graph.search.answerState.

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/api/search-qna-post-qnas.md
> +|state|String|State of the qna. Possible values are: `published`, `draft`, `excluded`.|
According to the CSDL file, the correct type for state should be microsoft.graph.search.answerState. Please, replace String with microsoft.graph.search.answerState.

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/api/search-qna-update-qnas.md
> +|state|String|State of the qna. Possible values are: `published`, `draft`, `excluded`.|
According to the CSDL file, the correct type for state should be microsoft.graph.search.answerState. Please, replace String with microsoft.graph.search.answerState.

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|state|String|State of the bookmark. Possible values are: `Published`, `Draft`, `Excluded`.|
According to the CSDL file, the correct type for state should be microsoft.graph.search.answerState. Please, replace String with microsoft.graph.search.answerState.

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|state|String|State of the bookmark. Possible values are: `Published`, `Draft`, `Excluded`.|
According to the CSDL file, the correct type for state should be microsoft.graph.search.answerState. Please, replace String with microsoft.graph.search.answerState.

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/resources/searchentity.md
> +A top level object representing the Microsoft Search API endpoint.
A word ending in –ing can be a verb, a noun, or an adjective. Please, avoid using gerunds where possible; in this case, you can change "representing" to "that represents".

2021-09-23 20:45 UTC, JarbasHorst commented on api-reference/beta/resources/searchentity.md
> +| Relationship | Type |Description|
For clarity, please provide a description to the following relationships.

2021-09-23 20:45 UTC, JarbasHorst commented on changelog/Microsoft.Search.Admin.json
> +                    "Id": "dd9558e5-e354-11eb-88f7-f923b9ff781d",
[devicePlatformType enum type](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-deviceplatformtype?view=graph-rest-beta) already exists. In this case, please remove this entry from the changelog record.

2021-09-23 20:45 UTC, JarbasHorst commented on changelog/Microsoft.Search.Admin.json
> +                    "Id": "dd9093b2-e354-11eb-88f7-f923b9ff781d",
identitySet already exists. In this case, please remove this entry from the changelog record.

2021-09-23 20:45 UTC, JarbasHorst commented on changelog/Microsoft.Search.Admin.json
> +            "Id": "dd7d7fe8-e354-11eb-88f7-f923b9ff781d",
Within a changelog record, all Id properties must have the same value.

2021-09-23 20:45 UTC, JarbasHorst commented on changelog/Microsoft.Search.Admin.json
> +                    "Id": "dd8e30ca-e354-11eb-88f7-f923b9ff781d",
identity already exists. In this case, please remove this entry from the changelog record.

2021-09-23 20:45 UTC, JarbasHorst commented on changelog/Microsoft.Search.Admin.json
> +                    "Description": "Added the [bookmark](https://docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta) resource type.",
For clarity, I recommend you to extend the sentence to contain "supported methods". Suggested revision:

- ... resource type and supported methods.

2021-09-23 20:45 UTC, JarbasHorst commented on changelog/Microsoft.Search.Admin.json
> +                    "Description": "Added the [qna](https://docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta) resource type.",
For clarity, I recommend you to extend the sentence to contain "supported methods". Suggested revision:

- ... resource type and supported methods.

2021-09-23 20:45 UTC, JarbasHorst commented on changelog/Microsoft.Search.Admin.json
> +                    "Description": "Added the [acronym](https://docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta) resource type.",
For clarity, I recommend you to extend the sentence to contain "supported methods". Suggested revision:

- ... resource type and supported methods.

2021-09-24 17:19 UTC, opbld34 commented
Docs Build status updates of commit _[dfdf9ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfdf9adebab543d9cef84709f45c09e76820f65d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-bookmark?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-qna.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-qna.md) | :white_check_mark:Succeeded | [View](https://review.d [...]

2021-09-27 22:39 UTC, opbld33 commented
Docs Build status updates of commit _[44bb8d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44bb8d3d28e8f7f9ca829a18a698efda51260625)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-262bb451)
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :bulb:Suggestion | | [Details](#user-content-6cabbe379866f2aa46daabe2d81e348c-262bb451)

<a id="0817dce4456c16725d5333633847d38f-262bb451"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/toc.yml)
 - **Line 13404, Column 9**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="6cabbe379866f2aa46daabe2d81e348c-262bb451"></a>
### [api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md)
 - **Line 22, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109272237317186-13343%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T22%3A39%3A21Z&sr=b&sp=r&sig=d8hASrR8als5VmxuUDDlJK3ieS08FhYufut%2BPZylRdw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-27 23:11 UTC, opbld32 commented
Docs Build status updates of commit _[06ecbfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06ecbfac0018b27a83a08595d3fd1bed81f9b11d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2021-09-28 17:49 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +---
#feedback-addressed

2021-09-28 19:01 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-list-acronyms.md
> +  "@odata.type": "Collection(microsoft.graph.search.acronym)"
#feedback-addressed

2021-09-28 19:01 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-list-bookmarks.md
> +  "@odata.type": "Collection(microsoft.graph.search.bookmark)"
#feedback-addressed

2021-09-28 19:01 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-list-qnas.md
> +  "@odata.type": "Collection(microsoft.graph.search.qna)"
#feedback-addressed

2021-09-28 19:01 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-post-acronyms.md
> +|Property|Type|Description|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/enums-search.md
> +description: "Microsoft Graph search enumeration values"
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/searchanswer.md
> +Search answer is a base type for other search answers. Includes properties that apply to other search answer entities.
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/searchanswer.md
> +|lastModifiedDateTime|DateTimeOffset|Timestamp of when the search answer is created or edited. Read only.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/searchanswer.md
> +|lastModifiedBy|[microsoft.graph.identitySet](../resources/identityset.md)|Details of the user that created or last modified the search answer. Read only.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/searchanswer.md
> +|webUrl|String|Search answer url link. When users click this search answer in search results they will go to this url.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/searchanswer.md
> +|id|String|Guid id of the search answer. Inherited from [entity](../resources/entity.md).|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/searchanswer.md
> +description: "searchAnswer"
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +Q&As are administrative answer results in the search results page which provide answers for specific search keywords. Q&As allow administrators to answer the user's questions directly in search inste
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +description: "Question and Answer search resource"
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +description: "acronym"
#feedback-addressed

2021-09-28 20:14 UTC, opbld34 commented
Docs Build status updates of commit _[3acdd66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3acdd66ec5520a440c737d01421432dc1a6f6ff6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6e5194e7)

<a id="6e5194e7"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109282013566799-13343%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T20%3A14%3A27Z&sr=b&sp=r&sig=xwwezDKiUbSjE0CaWDxlJ1QX8V4ZDwpN7ynUpIjex9c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|isSuggested|Boolean| True if this qna was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|lastModifiedDateTime|DateTimeOffset| Timestamp of when the qna is created or edited. Inherited from [searchAnswer](../resources/searchanswer.md). Read only.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|lastModifiedBy|[microsoft.graph.identitySet](../resources/identityset.md)|Details of the user that created or last modified the qna. Inherited from [searchAnswer](../resources/searchanswer.md). Read
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|webUrl|String|Qna url link. When users click this qna in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|id|String|Guid id of the qna. Inherited from [entity](../resources/entity.md).|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|availabilityEndDateTime|DateTimeOffset|Date qna will stop appearing as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|availabilityStartDateTime|DateTimeOffset|Date qna will start to appear as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +|availabilityStartDateTime|DateTimeOffset|Date qna will start to appear as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|availabilityStartDateTime|DateTimeOffset|Date qna will start to appear as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:14 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|isSuggested|Boolean|True if this bookmark was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark. By adding existing PowerApps to a Bookmark, users can complete tasks like entering vacation time or reporting expenses on the search res
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|availabilityEndDateTime|DateTimeOffset|Date bookmark will stop appearing as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|categories|String collection|Categories commonly used to describe this bookmark. eg. IT, HR, etc.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|lastModifiedDateTime|DateTimeOffset|Timestamp of when the bookmark is created or edited. Inherited from [searchAnswer](../resources/searchanswer.md). Read only. |
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|lastModifiedBy|[microsoft.graph.identitySet](../resources/identityset.md)|Details of the user that created or last modified the bookmark. Inherited from [searchAnswer](../resources/searchanswer.md).
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|webUrl|String|Bookmark url link. When users click this bookmark in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|id|String|Guid id of the bookmark. Inherited from [entity](../resources/entity.md).|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +\
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +A bookmark is a tenant wide administrative answer in Microsoft search results for common tenant search queries. A bookmark has many properties which allow Admins to make common resources more accessi
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +description: "bookmark"
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answervariant.md
> +|webUrl|String|Answer variation url link. When users click this answer variation in search results they will go to this url.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answervariant.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answervariant.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answervariant.md
> +An answer variant can be used to to change certain fields of a search answer based on country or platform.
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answervariant.md
> +description: "answerVariant"
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answerkeyword.md
> +|matchSimilarKeywords|Boolean|If similar words in the search term to the keywords should trigger the search answer.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answerkeyword.md
> +Answer Keyword is used to configure triggers for a search answer to appear on search.
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/answerkeyword.md
> +description: "answerKeyword"
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +An acronym is a tenant wide administrative answer in Microsoft search results to define common acronyms in a tenant. An acronym has a few properties which define an acronym for an organization.\
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +|id|String|Guid id of the acronym. Inherited from [entity](../resources/entity.md).|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +|lastModifiedBy|[microsoft.graph.identitySet](../resources/identityset.md)|Details of the user that created or last modified the acronym. Inherited from [searchAnswer](../resources/searchanswer.md).
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +|lastModifiedDateTime|DateTimeOffset|Timestamp of when the acronym is created or edited. Inherited from [searchAnswer](../resources/searchanswer.md). Read only.|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +|webUrl|String|The url of the page or website where users can go for more information about the acronym. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +An acronym is a tenant wide administrative answer in Microsoft search results to define common acronyms in a tenant. An acronym has a few properties which define an acronym for an organization.\
#feedback-addressed

2021-09-28 20:15 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +|isSuggested|Boolean|True if this qna was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +|availabilityEndDateTime|DateTimeOffset|Date qna will stop appearing as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +|webUrl|String|Qna url link. When users click this qna in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +The following table shows the properties that are required when you update the [qna](../resources/qna.md).
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +The following table shows the properties that are required when you update the [qna](../resources/qna.md).
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|isSuggested|Boolean|True if this qna was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|availabilityEndDateTime|DateTimeOffset|Date qna will stop appearing as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|webUrl|String|Qna url link. When users click this qna in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|Property|Type|Description|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +The following table shows the properties that are required when you create the [qna](../resources/qna.md).
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +DELETE /acronyms/{acronymsId}
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|isSuggested|Boolean|True if this bookmark was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark. By adding existing PowerApps to a Bookmark, users can complete tasks like entering vacation time or reporting expenses on the search res
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|availabilityEndDateTime|DateTimeOffset|Date bookmark will stop appearing as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|categories|String collection|Categories commonly used to describe this bookmark. eg. IT, HR, etc.|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|webUrl|String|Bookmark url link. When users click this bookmark in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +The following table shows the properties that are required when you update the [bookmark](../resources/bookmark.md).
#feedback-addressed

2021-09-28 20:16 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +The following table shows the properties that are required when you update the [bookmark](../resources/bookmark.md).
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +If successful, this method returns a `201 Created` response code with the id of the question and answer created.
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +If successful, this method returns a `201 Created` response code with the id of the bookmark created.
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|isSuggested|Boolean|True if this bookmark was suggested to the admin by a user or was mined and suggested by Microsoft. Read only.|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark. By adding existing PowerApps to a Bookmark, users can complete tasks like entering vacation time or reporting expenses on the search res
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|availabilityEndDateTime|DateTimeOffset|Date bookmark will stop appearing as a search result. Set as null for always available.|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|categories|String collection|Categories commonly used to describe this bookmark. eg. IT, HR, etc.|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|webUrl|String|Bookmark url link. When users click this bookmark in search results they will go to this url. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|Property|Type|Description|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +The following table shows the properties that are required when you create the [bookmark](../resources/bookmark.md).
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-update-acronyms.md
> +
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-update-acronyms.md
> +|webUrl|String|The url of the page or website where users can go for more information about the acronym. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-update-acronyms.md
> +The following table shows the properties that are required when you update the [acronym](../resources/acronym.md).
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-update-acronyms.md
> +The following table shows the properties that are required when you update the [acronym](../resources/acronym.md).
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +Here is an example of the response. Note: The response object shown here is truncated for brevity. All of the properties will be returned from an actual call.
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +Here is an example of the response. Note: The response object shown here is truncated for brevity. All of the properties will be returned from an actual call.
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-post-acronyms.md
> +Here is an example of the response. Note: The response object shown here is truncated for brevity. All of the properties will be returned from an actual call.
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-post-acronyms.md
> +The following table shows the properties that are required when you create the [acronym](../resources/acronym.md).
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-post-acronyms.md
> +|webUrl|String|The url of the page or website where users can go for more information about the acronym. Inherited from [searchAnswer](../resources/searchanswer.md).|
#feedback-addressed

2021-09-28 20:17 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-post-acronyms.md
> +|Property|Type|Description|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on changelog/Microsoft.Search.Admin.json
> +                    "Description": "Added the [acronym](https://docs.microsoft.com/en-us/graph/api/resources/acronym?view=graph-rest-beta) resource type.",
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on changelog/Microsoft.Search.Admin.json
> +                    "Description": "Added the [qna](https://docs.microsoft.com/en-us/graph/api/resources/qna?view=graph-rest-beta) resource type.",
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on changelog/Microsoft.Search.Admin.json
> +                    "Description": "Added the [bookmark](https://docs.microsoft.com/en-us/graph/api/resources/bookmark?view=graph-rest-beta) resource type.",
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on changelog/Microsoft.Search.Admin.json
> +                    "Id": "dd8e30ca-e354-11eb-88f7-f923b9ff781d",
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on changelog/Microsoft.Search.Admin.json
> +            "Id": "dd7d7fe8-e354-11eb-88f7-f923b9ff781d",
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on changelog/Microsoft.Search.Admin.json
> +                    "Id": "dd9093b2-e354-11eb-88f7-f923b9ff781d",
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on changelog/Microsoft.Search.Admin.json
> +                    "Id": "dd9558e5-e354-11eb-88f7-f923b9ff781d",
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/resources/searchentity.md
> +| Relationship | Type |Description|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/resources/searchentity.md
> +A top level object representing the Microsoft Search API endpoint.
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|state|String|State of the bookmark. Possible values are: `Published`, `Draft`, `Excluded`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|state|String|State of the bookmark. Possible values are: `Published`, `Draft`, `Excluded`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +|state|String|State of the qna. Possible values are: `published`, `draft`, `excluded`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|state|String|State of the qna. Possible values are: `published`, `draft`, `excluded`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|state|String|State of the qna. Possible values are: `published`, `draft`, `excluded`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|state|String|State of the bookmark. Possible values are: `published`, `draft`, `excluded`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update-qnas.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-post-qnas.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 21:49 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-post-bookmarks.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 21:50 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|platforms|microsoft.graph.platform collection|List of devices and OS able to view this qna. Possible values are: `unknown`, `ios`, `android`, `windows`, `windowsMobile`, `macOS`.|
#feedback-addressed

2021-09-28 21:51 UTC, opbld31 commented
Docs Build status updates of commit _[429ed33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/429ed336c99bbdef4b29809d930813d424c981c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2021-09-28 22:14 UTC, jakeost-msft commented on api-reference/beta/resources/searchanswer.md
> +
#feedback-addressed

2021-09-28 22:19 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-get-acronyms.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
#feedback-addressed

2021-09-28 22:19 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-list-acronyms.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
#feedback-addressed

2021-09-28 22:19 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-get-bookmarks.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
#feedback-addressed

2021-09-28 22:19 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-get-qnas.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
#feedback-addressed

2021-09-28 22:19 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-list-qnas.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
#feedback-addressed

2021-09-28 22:28 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +|Delegated (work or school account)| Global administrator, search administrator, search editor. |
#feedback-addressed

2021-09-28 22:28 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +|Permission type|Permissions (from most to least privileged)|
#feedback-addressed

2021-09-28 22:28 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +|Delegated (work or school account)| Global administrator, search administrator, search editor. |
#feedback-addressed

2021-09-28 22:51 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete-acronyms.md
> +|Delegated (work or school account)| Global administrator, search administrator, search editor. |
#feedback-addressed

2021-09-28 22:55 UTC, opbld31 commented
Docs Build status updates of commit _[ede2aa4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ede2aa4d7462f25014dbdc319d85dc46af18f802)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2021-10-01 21:09 UTC, JarbasHorst requested changes

2021-10-01 21:09 UTC, JarbasHorst commented on api-reference/beta/api/search-searchentity-post-qnas.md
> +{
The request example for the QNA POST doesn't give a real example but instead it looks like the JSON representation of the QNA object. This is not correct. Please, update this example to describe a POST request.

2021-10-02 00:27 UTC, opbld33 commented
Docs Build status updates of commit _[6892416](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68924169b7e43f1be0663744fa5a87d0ca239416)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-list-acronyms.md
> +
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-acronyms.md
> +**Note:** The response object shown here is truncated for brevity. All of the properties will be returned from an actual call.
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +**Note:** The response object shown here is truncated for brevity. All of the properties will be returned from an actual call.
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-qnas.md
> +**Note:** The response object shown here is truncated for brevity. All of the properties will be returned from an actual call.
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update.md
> +|categories|String collection|Categories commonly used to describe this bookmark. For example. IT and HR.|
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +|Property|Type|Description|
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update.md
> +**Note:** Updates to collection properties will update the entire collection. Any updates to a collection, such as keywords or categories, will replace the collection entirely.
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update.md
> +In the request body, supply a JSON representation of the [bookmark](../resources/search-bookmark.md) object. Supply the values for relevant fields that should be updated. Existing properties that are
#feedback-addressed

2021-10-04 18:56 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update.md
> +The following table shows the properties that are required when you update a [bookmark](../resources/search-bookmark.md).
#feedback-addressed

2021-10-04 18:57 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-update.md
> +In the request body, supply a JSON representation of the [acronym](../resources/search-acronym.md) object.
#feedback-addressed

2021-10-04 18:57 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update.md
> +In the request body, supply a JSON representation of the [qna](../resources/search-qna.md) object. Supply the values for relevant fields that should be updated. Existing properties that are not inclu
#feedback-addressed

2021-10-04 18:57 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update.md
> +**Note:** Updates to collection properties will update the entire collection. Any updates to a collection, such as keywords or categories, will replace the collection entirely.
#feedback-addressed

2021-10-04 18:57 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-get.md
> +GET /acronyms/{acronymsId}
#feedback-addressed

2021-10-04 18:57 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-qnas.md
> +|Property|Type|Description|
#feedback-addressed

2021-10-04 18:57 UTC, opbld30 commented
Docs Build status updates of commit _[51a0791](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51a079178b77801c9092dac9de98754abb69babf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2021-10-04 18:57 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-qnas.md
> +{
#feedback-addressed

2021-10-04 19:17 UTC, opbld32 commented
Docs Build status updates of commit _[7a5b7a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a5b7a03f8c383624fd57518c237c513b003d4e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2021-10-04 21:19 UTC, JarbasHorst requested changes

2021-10-05 22:35 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +|platforms|microsoft.graph.devicePlatformType collection|List of devices and operating systems able to view this bookmark. Possible values are: `unknown`, `android`, `androidForWork`, `ios`, `macOS`,
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update.md
> +|platforms|microsoft.graph.devicePlatformType collection|List of devices and operating systems able to view this bookmark. Possible values are: `unknown`, `android`, `androidForWork`, `ios`, `macOS`,
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-qnas.md
> +|platforms|microsoft.graph.devicePlatformType collection|List of devices and operating systems able to view this qna. Possible values are: `unknown`, `android`, `androidForWork`, `ios`, `macOS`, `win
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update.md
> +|platforms|microsoft.graph.devicePlatformType collection|List of devices and operating systems able to view this bookmark. Possible values are: `unknown`, `android`, `androidForWork`, `ios`, `macOS`,
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/resources/search-qna.md
> +|platforms|microsoft.graph.devicePlatformType collection|List of devices and operating systems able to view this bookmark. Possible values are: `unknown`, `android`, `androidForWork`, `ios`, `macOS`,
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update.md
> +|webUrl|String|Bookmark URL link. When users click this bookmark in search results they will go to this URL. Inherited from [searchAnswer](../resources/search-searchAnswer.md).|
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update.md
> +|webUrl|String|Qna URL link. When users click this qna in search results they will go to this URL. Inherited from [searchAnswer](../resources/search-searchAnswer.md).|
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +|webUrl|String|Bookmark URL link. When users click this bookmark in search results they will go to this URL. Inherited from [searchAnswer](../resources/search-searchAnswer.md).|
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-qnas.md
> +|webUrl|String|Qna URL link. When users click this qna in search results they will go to this URL. Inherited from [searchAnswer](../resources/search-searchAnswer.md).|
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/resources/search-answervariant.md
> +|webUrl|String|Answer variation URL link. When users click this answer variation in search results they will go to this URL.|
#feedback-addressed

2021-10-05 22:36 UTC, jakeost-msft commented on api-reference/beta/resources/search-bookmark.md
> +|webUrl|String|Bookmark URL link. When users click this bookmark in search results they will go to this URL. Inherited from [searchAnswer](../resources/search-searchAnswer.md).|
#feedback-addressed

2021-10-05 22:37 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +|availabilityEndDateTime|DateTimeOffset|Date bookmark will stop to appear as a search result. Set as `null` for always available.|
#feedback-addressed

2021-10-05 22:37 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-qnas.md
> +|availabilityEndDateTime|DateTimeOffset|Date qna will stop to appear as a search result. Set as `null` for always available.|
#feedback-addressed

2021-10-05 22:37 UTC, jakeost-msft commented on api-reference/beta/resources/search-bookmark.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as `null` for always available.|
#feedback-addressed

2021-10-05 22:37 UTC, jakeost-msft commented on api-reference/beta/resources/search-bookmark.md
> +|availabilityEndDateTime|DateTimeOffset|Date bookmark will stop to appear as a search result. Set as `null` for always available.|
#feedback-addressed

2021-10-05 22:37 UTC, jakeost-msft commented on api-reference/beta/resources/search-qna.md
> +|availabilityEndDateTime|DateTimeOffset|Date qna will stop to appear as a search result. Set as `null` for always available.|
#feedback-addressed

2021-10-05 22:37 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-update.md
> +|availabilityStartDateTime|DateTimeOffset|Date bookmark will start to appear as a search result. Set as `null` for always available.|
#feedback-addressed

2021-10-05 22:38 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update.md
> +|availabilityEndDateTime|DateTimeOffset|Date qna will stop to appear as a search result. Set as `null` for always available.|
#feedback-addressed

2021-10-05 22:38 UTC, jakeost-msft commented on api-reference/beta/resources/search-acronym.md
> +description: "An acronym is a tenant wide administrative answer in search results in Microsoft Search to define common acronyms in a tenant."
#feedback-addressed

2021-10-05 22:38 UTC, jakeost-msft commented on api-reference/beta/resources/search-acronym.md
> +An acronym is a tenant wide administrative answer in search results in Microsoft Search to define common acronyms in a tenant.
#feedback-addressed

2021-10-05 22:38 UTC, jakeost-msft commented on api-reference/beta/resources/search-bookmark.md
> +description: "A bookmark is a tenant wide administrative answer in search results in Microsoft Search for common tenant search queries. A bookmark has many properties which allow administrators to ma
#feedback-addressed

2021-10-05 22:38 UTC, jakeost-msft commented on api-reference/beta/resources/searchentity.md
> +| acronyms | [microsoft.graph.search.acronym](../resources/search-acronym.md) collection | Tenant-wide administrative answer in Microsoft search results to define common acronyms in a tenant.  |
#feedback-addressed

2021-10-05 22:38 UTC, jakeost-msft commented on api-reference/beta/resources/searchentity.md
> +| bookmarks | [microsoft.graph.search.bookmark](../resources/search-bookmark.md) collection | Tenant-wide administrative answer in Microsoft search results for common tenant search queries. |
#feedback-addressed

2021-10-05 22:39 UTC, jakeost-msft commented on api-reference/beta/resources/searchentity.md
> +| qnas | [microsoft.graph.search.qna](../resources/search-qna.md) collection | Tenant-wide administrative answer in Microsoft search results which provide answers for specific search keywords. |
#feedback-addressed

2021-10-05 22:39 UTC, jakeost-msft commented on api-reference/beta/api/search-qna-update.md
> +|platforms|microsoft.graph.devicePlatformType collection|List of devices and operating systems able to view this bookmark. Possible values are: `unknown`, `android`, `androidForWork`, `ios`, `macOS`,
#feedback-addressed

2021-10-05 22:39 UTC, jakeost-msft commented on api-reference/beta/resources/search-qna.md
> +|platforms|microsoft.graph.devicePlatformType collection|List of devices and operating systems able to view this bookmark. Possible values are: `unknown`, `android`, `androidForWork`, `ios`, `macOS`,
#feedback-addressed

2021-10-05 22:44 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-acronyms.md
> +Authorization: Bearer AAD_PFT_TOKEN
#feedback-addressed

2021-10-05 22:44 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +Authorization: Bearer AAD_PFT_TOKEN
#feedback-addressed

2021-10-05 22:44 UTC, jakeost-msft commented on api-reference/beta/resources/search-answervariant.md
> +  "platform": "String"
#feedback-addressed

2021-10-05 22:44 UTC, jakeost-msft commented on api-reference/beta/resources/search-api-answers-overview.md
> +description: "Use Microsoft Graph to manage administrative search answers."
#feedback-addressed

2021-10-05 22:45 UTC, opbld32 commented
Docs Build status updates of commit _[6ce8120](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ce812033661698913ab6ab5c4eeaf40b5d34c75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2021-11-02 23:26 UTC, angelgolfer-ms commented on concepts/permissions-reference.md
> +
@jakeost-msft , FYI 2 comments for this section for the search configuration perms:
(a) To be consistent with other existing sections, the order of the "Application permissions" and "Delegated permissions" should be reversed.
(b) For each of the two tables, the second row is missing a second column.

In general, it's a good practice to view your topics on the staging site for the PR, to let you spot formatting errors like these for a table, and to follow the topic-to-topic experience you're creating for the customer.

For expediency, I can make these fixes on your behalf to meet the updated release date you just informed us.

2021-11-03 04:12 UTC, angelgolfer-ms commented on concepts/search-concept-answers.md
> +# Use the Microsoft Search API in Microsoft Graph to manage administrative search answers (preview)
@jakeost-msft , there are 2 things we can improve on this conceptual topic about the search answers feature. I'll try to take care of them, but would still like to point them out, just in case you have other input, or for your future reference:

- Describe each of these 3 search answers and how they're useful. Even though these terms (acronyms, bookmarks, Q&A ) are common in natural language, the concept of setting them up to make them useful in a search experience may not be intuitive to all our customers. 
- Adjust the topic title to reflect the value of the feature. Right now, this topic and your API overview have virtually the same topic title:
  "Use the Microsoft Search API in Microsoft Graph to manage administrative search answers "

vs

"Use the Microsoft Search API to manage administrative answers"

2021-11-03 04:26 UTC, angelgolfer-ms commented on concepts/search-concept-answers.md
> +You can use the Microsoft Search API to manage administrative search answers in your tenant. These answers are displayed in Microsoft Search results when triggered by a keyword or acronym defined in
Line 13:
In Microsoft Graph, we try to portray a unified API; I have changed the reference of "Microsoft Search API" to "Microsoft Graph API". 
For context, I am adding a paragraph before line 13 to describe what Microsoft  Search allows admins do, so it's not like we're hiding the feature Microsoft Search. Technically, "Microsoft Search" is a branded feature name, but not "Microsoft Search API". On the other hand, the API is "Microsoft Graph API".
The fact that existing docs have been loose in referencing product or service-specific APIs using their names actually weakens the value proposition for the Microsoft Graph API. So we try not to do that where the context is clear. :-)

2021-11-03 04:47 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-acronym.md
> +
GLOBAL:
@jakeost-msft , in the Microsoft Graph docs in general, the Identity team has given the guidance to use "organization" in place of "tenant".
Are there contexts where you or your team have always drawn a distinction between the two?
If so, please let me know.
If not, can you please do a search and replace to make the reference as "organization" consistently?

2021-11-03 05:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-acronym.md
> +|state|microsoft.graph.search.answerState|State of the acronym. Possible values are: `published`, `draft`, or `excluded`.|
Line 39:
@jakeost-msft , FYI, per our guidance for documenting evolvable enums, you should include "unknownFutureValue" in the enumeration of the enum members.
Please take a look at the guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/174164/Evolvable-enumerations

I have fixed this on your behalf, in both this line and in enums-search.md.

2021-11-03 07:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-bookmark.md
> +|languageTags|String collection|List of countries or regions able to view this bookmark.|
Line 42:
@jakeost-msft , the corresponding api.md file for the bookmark resource includes a table of supported language names. Is that list represented somewhere you can link to? If not, how would customers know what to specify?

2021-11-03 08:01 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-qna.md
> +|languageTags|String collection|List of countries or regions able to view this qna.|
Line 41:
@jakeost-msft , the corresponding api.md file for the bookmark resource includes a table of supported language names. Is that list represented somewhere you can link to? If not, how would customers know what to specify?

2021-11-03 08:08 UTC, angelgolfer-ms commented on api-reference/beta/api/search-acronym-update.md
> +<!-- {
Line 79 and GLOBAL:
Can you please delete this line? It's generated by the generator; its purpose is for responses with body. It looks like the 3 PATCH operation sin this PR don't return any response bodies, so this default note is not applicable.

2021-11-03 08:23 UTC, opbld30 commented
Docs Build status updates of commit _[4f4f1e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f4f1e614ec6c1b40ad371e0415e47e77ffde253)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-6aa9f5f7)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-03 08:28 UTC, angelgolfer-ms requested changes
HI @jakeost-msft , I made a review pass of this PR again. I made some updates directly to the PR; I made comments to these ones just to share the reasons for those updates.
There are a few other areas that I had commented we should update.

Can you please follow up a a handful of remaining issues? They mostly pertain to more than a files in your PR.

2021-11-03 16:35 UTC, jakeost-msft commented on api-reference/beta/resources/search-acronym.md
> +
#feedback-addressed

2021-11-03 16:38 UTC, jakeost-msft commented on api-reference/beta/resources/search-acronym.md
> +|state|microsoft.graph.search.answerState|State of the acronym. Possible values are: `published`, `draft`, or `excluded`.|
#feedback-addressed

2021-11-03 22:48 UTC, jakeost-msft commented on api-reference/beta/resources/search-bookmark.md
> +|languageTags|String collection|List of countries or regions able to view this bookmark.|
@angelgolfer-ms good point! After some digging I'm not sure there is a good link for this. Should we include the list of language tags from the api.md somewhere?

2021-11-03 22:53 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-update.md
> +<!-- {
#feedback-addressed

2021-11-03 22:56 UTC, opbld33 commented
Docs Build status updates of commit _[c17e89c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c17e89cb18d450b69bbc9868ffba5beb9918afc9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-e0eaf645)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-03 23:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-bookmark.md
> +|languageTags|String collection|List of countries or regions able to view this bookmark.|
Yes, that would be helpful for customers.
Since at this point, both bookmark and qna use the languageTags property, perhaps adding an H3 section to the API overview topic (search-api-answers-overview.md) is one choice?
If on the other hand you think this would be commonly asked question, then putting that in a separate concept topic  titled appropriate for searching would be another approach. That separate concept topic would go to the "Learn" section, under the "Search" node in the TOC.

2021-11-04 04:21 UTC, opbld33 commented
Docs Build status updates of commit _[b8abcfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8abcfd989cfbe65e206d18dbcd7aa133bbbf530)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-d6a136d5)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-04 05:06 UTC, jakeost-msft commented on api-reference/beta/resources/search-bookmark.md
> +|languageTags|String collection|List of countries or regions able to view this bookmark.|
Added a H2 section to the search-api-answers-overview.md.
#Feedback-addressed

2021-11-04 05:06 UTC, jakeost-msft commented on api-reference/beta/resources/search-qna.md
> +|languageTags|String collection|List of countries or regions able to view this qna.|
Added a H2 section to the search-api-answers-overview.md.
#Feedback-addressed

2021-11-04 05:10 UTC, jakeost-msft commented on concepts/permissions-reference.md
> +
#feedback-addressed

2021-11-04 05:10 UTC, jakeost-msft commented on concepts/search-concept-answers.md
> +# Use the Microsoft Search API in Microsoft Graph to manage administrative search answers (preview)
#feedback-addressed

2021-11-04 05:10 UTC, jakeost-msft commented on concepts/search-concept-answers.md
> +You can use the Microsoft Search API to manage administrative search answers in your tenant. These answers are displayed in Microsoft Search results when triggered by a keyword or acronym defined in
#feedback-addressed

2021-11-04 09:31 UTC, opbld31 commented
Docs Build status updates of commit _[2bf315c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bf315caf06917a56f3b170675ef9aa19ec22882)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-f52b8a8d)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-04 09:35 UTC, angelgolfer-ms reviewed
@jakeost-msft , I see that you added a table to the API overview topic (search-api-answers-overview.md).
FYI I added links to that section from bookmark and qna resource type topics, and modified the descriptions for the languageTags property in each of these resource type topics.
I also added a lead-in paragraph to describe the values in the new table in the the API overview topic.

Can you take a look at my commit from tonight for the above: https://github.com/microsoftgraph/microsoft-graph-docs/pull/13343/commits/2bf315caf06917a56f3b170675ef9aa19ec22882

Please also see my question/comment in search-api-answers-overview.md. Thanks!

2021-11-04 09:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-api-answers-overview.md
> +| ----------- | ----------  |
Lines 35-68:
@jakeost-msft , since the values in the left column ("Value") are in the format {language}-{REGION}, should the description in the right column ("Description") always mention the language and country/region, and not just the country/region in some cases?

For example, line 67 should have the description "English (United States)", and not "United States - English".

2021-11-04 16:31 UTC, jakeost-msft commented on api-reference/beta/resources/search-api-answers-overview.md
> +| ----------- | ----------  |
This is how it is done in the UI today, so for consistency I would argue to keep it the same. Also, the list is sorted by country name, not language, which I believe is what the administrators are expecting.

2021-11-04 16:34 UTC, opbld30 commented
Docs Build status updates of commit _[ba73fcd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba73fcdde2683a0c9df1413ec15239a09f989d6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-70108611)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-04 20:03 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-api-answers-overview.md
> +| ----------- | ----------  |
@jakeost-msft , can you point me to the UI please?

2021-11-04 20:07 UTC, jakeost-msft commented on api-reference/beta/resources/search-api-answers-overview.md
> +| ----------- | ----------  |
Here are some screenshots of the UI interaction:

![image](https://user-images.githubusercontent.com/85905850/140412006-2cfacdfb-e282-4e3a-b536-90c9c1d7216a.png)

![image](https://user-images.githubusercontent.com/85905850/140412088-198cb39c-3072-45cf-97bd-ad889aa527a4.png)

2021-11-05 03:01 UTC, opbld30 commented
Docs Build status updates of commit _[7774d92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7774d92d899d350b3a255bd622c0c8c14d26bd79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-cd4f12ff)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-05 03:15 UTC, opbld33 commented
Docs Build status updates of commit _[92909d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92909d56e4ef1cdbf905915c70fcca421efdbeea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-5af4e602)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-05 04:03 UTC, opbld31 commented
Docs Build status updates of commit _[011910a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/011910a3cf7562fb8bcbc2875ca27ff57d8c9023)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/concepts/permissions-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13343) | [Details](#user-content-eea99bea355d0a4253064eefdbbe7005-216f55ea)
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https:// [...]

2021-11-05 04:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/search-api-answers-overview.md
> +| ----------- | ----------  |
Hi @jakeost-msft , thanks for the clarification this afternoon.
FYI I cleaned up where we refer to the language tags in the 3 topics: search-bookmark.md, search-qna.md, and search-api-answers-overview.md. You can please take a look at my commit here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/13343/commits/7774d92d899d350b3a255bd622c0c8c14d26bd79

2021-11-05 04:13 UTC, angelgolfer-ms reviewed
HI @jakeost-msft , FYI I updated this PR to address language tags and what's supported more clearly. Please take a look at the details in my latest response here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/13343#discussion_r743378011

If I didn't overlook anything with that matter, then I think we're done with the content review! Please confirm and I'll approve and label the PR accordingly. :-)

2021-11-05 17:12 UTC, jakeost-msft commented
@angelgolfer-ms looks good to me! Thank you so much for all of your help!

2021-11-05 19:46 UTC, angelgolfer-ms approved these changes
Thanks for the confirmation that my last updates are good!
After the new permissions are deployed and customers can use these APIs, please label the PR "ready to merge". @Lauragra can publish the PR then.

2022-02-19 04:43 UTC, Lauragra commented on api-reference/beta/api/search-acronym-delete.md
> +One of the following permissions is required to call this api. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
Global: Please change api to API in the boilerplate sentence that introduces the permissions table. Please update in all API topics in the PR.

2022-02-19 04:45 UTC, Lauragra commented on api-reference/beta/api/search-acronym-delete.md
> +ms.date: 09/21/2021
Global: Please remove the ms.date attribute in all topics.

2022-02-19 04:48 UTC, Lauragra commented on api-reference/beta/api/search-bookmark-get.md
> +**Note:** The response object shown here might be shortened for readability.
Global: Where this note occurs, please format it as a note by adding a > symbol at the start of the line.

2022-02-19 04:48 UTC, opbld31 commented
Docs Build status updates of commit _[fa4d271](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa4d271fd236d5e74862a1005c1f1ce2f16400d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2022-02-19 04:50 UTC, opbld34 commented
Docs Build status updates of commit _[0e206fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e206fb4121035acdabcc26ac023773d6bdb9de0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2022-02-19 04:55 UTC, opbld34 commented
Docs Build status updates of commit _[3e343e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e343e9e0bab853a0b783f4d1b42e7cc77c04d05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2022-02-19 05:03 UTC, Lauragra commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +|powerAppIds|String collection|List of PowerApps associated with this bookmark. If users add existing PowerApps to a bookmark, they can complete tasks, such as to enter vacation time or to report exp
Please change PowerApps to Power Apps here.

2022-02-25 04:17 UTC, Lauragra commented
@jakeost-msft , please take a look at the remaining few comments on this PR so we can get it merged. Thanks.

2022-02-28 19:32 UTC, jakeost-msft commented on api-reference/beta/api/search-searchentity-post-bookmarks.md
> +|powerAppIds|String collection|List of PowerApps associated with this bookmark. If users add existing PowerApps to a bookmark, they can complete tasks, such as to enter vacation time or to report exp
#feedback-addressed

2022-02-28 19:32 UTC, jakeost-msft commented on api-reference/beta/api/search-bookmark-get.md
> +**Note:** The response object shown here might be shortened for readability.
#feedback-addressed

2022-02-28 19:33 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete.md
> +ms.date: 09/21/2021
#feedback-addressed

2022-02-28 19:33 UTC, jakeost-msft commented on api-reference/beta/api/search-acronym-delete.md
> +One of the following permissions is required to call this api. To learn more, including how to choose permissions, see [Permissions](/graph/permissions-reference).
#feedback-addressed

2022-02-28 19:34 UTC, jakeost-msft commented
> 

All feedback should be addressed. Thanks!

2022-02-28 19:34 UTC, opbld32 commented
Docs Build status updates of commit _[77694e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77694e4202a4b32813e7c70e73f02aa51164f7bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2022-03-01 03:12 UTC, opbld30 commented
Docs Build status updates of commit _[46284b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46284b6b621ec0fd96dea62c601a0d32a6f8ec7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/search-acronym-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-acronym-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-acronym-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-acronym-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-bookmark-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-bookmark-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-bookmark-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-delete?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-get?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-qna-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-qna-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-qna-update?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-list-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-list-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-list-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-acronyms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-acronyms.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-acronyms?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-bookmarks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-bookmarks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/api/search-searchentity-post-qnas.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/api/search-searchentity-post-qnas.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-searchentity-post-qnas?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/enums-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/enums-search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-search?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-acronym.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-acronym.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-acronym?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answerkeyword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answerkeyword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answerkeyword?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-answervariant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-answervariant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-answervariant?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-api-answers-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&branch=pr-en-us-13343) (graph-rest-beta) |
[api-reference/beta/resources/search-bookmark.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-30-jakeost/SearchAdmin/api-reference/beta/resources/search-bookmark.md) | :white_ [...]

2022-03-01 03:22 UTC, merged