upload resource - concept added
microsoftgraph/microsoft-graph-docs pull request #13359
Opened 2021-07-02 17:19 UTC by sharad-sharma-msft

Assignment service only exposes API for setting up SPO resources folder. However uploading the assignment or submission resource is done using direct API graph calls. This flow needs to be documented to allow graph callers to effectively exercise the flow end to end.

2021-07-02 17:22 UTC, opbld31 commented
Docs Build status updates of commit _[02392da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02392da2d65d8eda267c6bf38c6a3f15c08dd613)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-afeaf509)

<a id="949b1a7a379985a1b5d544757ce6733c-afeaf509"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 12, Column 32**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/educationassignment.md'.`````
 - **Line 12, Column 95**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/educationsubmission.md'.`````
 - **Line 22, Column 41**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/educationassignment.md'.`````
 - **Line 22, Column 102**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationassignment-setupresourcesfolder.md' referenced by link '../api-reference/beta/api/educationassignment-setupresourcesfolder.md' will not be built because it is not included in build scope.`````
 - **Line 22, Column 182**: **[Warning-link-out-of-scope]** `````File '../api-reference/v1.0/api/educationassignment-setupresourcesfolder.md' referenced by link '../api-reference/v1.0/api/educationassignment-setupresourcesfolder.md' will not be built because it is not included in build scope.`````
 - **Line 23, Column 41**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/educationsubmission.md'.`````
 - **Line 23, Column 102**: **[Warning-link-out-of-scope]** `````File '../api-reference/beta/api/educationsubmission-setupresourcesfolder.md' referenced by link '../api-reference/beta/api/educationsubmission-setupresourcesfolder.md' will not be built because it is not included in build scope.`````
 - **Line 23, Column 182**: **[Warning-link-out-of-scope]** `````File '../api-reference/v1.0/api/educationsubmission-setupresourcesfolder.md' referenced by link '../api-reference/v1.0/api/educationsubmission-setupresourcesfolder.md' will not be built because it is not included in build scope.`````
 - **Line 50, Column 52**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 50, Column 52**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 50, Column 52**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107021719270571-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-02T10%3A03%3A12Z&ske=2021-07-09T10%3A08%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-02T17%3A17%3A06Z&se=2021-08-02T17%3A22%3A06Z&sr=b&sp=r&sig=nmNI9nhnHxDoOt%2FZm3mMOg82xcju7%2BT2YVpoNUJ0CAU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 23:37 UTC, opbld33 commented
Docs Build status updates of commit _[4ff0852](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ff085207b495cc59af42b2f55b35938d54c6c09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-580e05d7)

<a id="949b1a7a379985a1b5d544757ce6733c-580e05d7"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 50, Column 52**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/driveitem-createuploadsession?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122335593810-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A58%3A44Z&ske=2021-07-19T08%3A03%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T23%3A32%3A25Z&se=2021-08-12T23%3A37%3A25Z&sr=b&sp=r&sig=jjw7pvKix%2BcxGPQxaVC6dYDT6SciVD%2BLtUjLGxdKZHQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 23:45 UTC, opbld34 commented
Docs Build status updates of commit _[665148c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/665148c5da913836a6a32d1ce0962479d9d559eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122344154375-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A38%3A21Z&ske=2021-07-19T07%3A43%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T23%3A40%3A47Z&se=2021-08-12T23%3A45%3A47Z&sr=b&sp=r&sig=nu56ksVkmGhWi1HhVYlXp%2ByUunphp6fZ3MuXfHVTK84%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 00:22 UTC, opbld31 commented
Docs Build status updates of commit _[b1e06fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1e06fce9d4dbc7c45e2d88cb2b595a5de789879)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107130021118606-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A42%3A44Z&ske=2021-07-19T07%3A47%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T00%3A17%3A46Z&se=2021-08-13T00%3A22%3A46Z&sr=b&sp=r&sig=njrkBO8EF%2FAa5E58JEqlGTVWmHWFDY%2BjMzQfSyvPXuw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 05:16 UTC, opbld30 commented
Docs Build status updates of commit _[1788841](https://github.com/microsoftgraph/microsoft-graph-docs/commits/178884181acdc5dd48baf760c0b6780c8731e44e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107130515234459-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A27%3A16Z&ske=2021-07-19T07%3A32%3A16Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T05%3A11%3A56Z&se=2021-08-13T05%3A16%3A56Z&sr=b&sp=r&sig=927TS1x5qsk5dZdbGatMR0o%2Bgeccx9Qgc0OLG1jPLw4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 05:23 UTC, opbld32 commented
Docs Build status updates of commit _[5db32db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5db32db76cf13ed2a4c79b97f9c2dbc3f0caa208)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107130522162574-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A41%3A25Z&ske=2021-07-19T07%3A46%3A25Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T05%3A18%3A57Z&se=2021-08-13T05%3A23%3A57Z&sr=b&sp=r&sig=kWIfFDg4nDtvzmkQOTv7MFY%2Bs7yWlXf3yf7ELAXXZrw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 05:30 UTC, opbld33 commented
Docs Build status updates of commit _[ee5563a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee5563a23a9d064a250f59caf0d88ff14520c54a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107130528222998-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A33%3A29Z&ske=2021-07-19T07%3A38%3A29Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T05%3A25%3A05Z&se=2021-08-13T05%3A30%3A05Z&sr=b&sp=r&sig=YNE90XvCpgdwtog1AVGTIP%2BwC7M50rODHkHgILADwno%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 16:35 UTC, opbld34 commented
Docs Build status updates of commit _[7986d13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7986d132f2391be63a81ddb1e9db3617d3b3d97c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131633598145-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A50%3A40Z&ske=2021-07-20T07%3A55%3A40Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T16%3A30%3A27Z&se=2021-08-13T16%3A35%3A27Z&sr=b&sp=r&sig=Ik0Gg6XZPOBdFJjka%2F0OvihwDD16GouN%2FfbYtCBXehc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 16:44 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +Resources are integral part of [educationAssignment](/graph/api/resources/educationassignment.md) and [educationSubmission](/graph/api/resources/educationsubmission.md).
are **a** integral....

2021-07-13 16:44 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +This returns a model with one of the property called `resourcesFolderUrl`.
The setup process

2021-07-13 16:46 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +Following steps will allow you to upload a resource/file to the relevant resource folder. For simplicity, we are going to upload an SPO resource to the assignment.
What other options are there other than "SPO resource"? Isn't this the only option?

2021-07-13 16:47 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +e.g. based on sample `resourcesFolderUrl`, the upload url will be:
base on **the** sample

2021-07-13 16:48 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +    "name": "NewFile.png",
This name doesn't match the input name in the request URL. Is that expected?

2021-07-13 16:51 UTC, sharad-sharma-msft commented on concepts/education-upload-resource-overview.md
> +Following steps will allow you to upload a resource/file to the relevant resource folder. For simplicity, we are going to upload an SPO resource to the assignment.
emphasis on assignment (we could show a sample for assignment resource upload or submission resource upload)

2021-07-13 16:52 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +    "webUrl": "https://contososdorg.sharepoint.com/sites/GraphTest/Class%20Files/Assignments/Test%20File%20Distribution/NewFile.png",
Same name comment as above

2021-07-13 16:53 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +            "displayName": "Graph explorer"
Is this accurate?

2021-07-13 16:56 UTC, ssriniva-msft commented on concepts/education-upload-resource-overview.md
> +        "@odata.type": "#microsoft.graph.educationWordResource",
The resource in the previous step was a .png file - this says it is a Word resource

2021-07-13 16:59 UTC, opbld31 commented
Docs Build status updates of commit _[ff92ab0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff92ab01c4728d1999ee6ebc445464a785be168c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107131656261268-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A49%3A27Z&ske=2021-07-20T07%3A54%3A27Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T16%3A54%3A07Z&se=2021-08-13T16%3A59%3A07Z&sr=b&sp=r&sig=K28hlzkzSyeG4wy%2FKQV9DWxdUqrXuViMLBGzj7lZRxw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 22:10 UTC, opbld31 commented
Docs Build status updates of commit _[be06ce1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be06ce19ae566809480806f5614c20478788926a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132209152677-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A58%3A37Z&ske=2021-07-20T08%3A03%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T22%3A05%3A45Z&se=2021-08-13T22%3A10%3A45Z&sr=b&sp=r&sig=mnj8VDonh2YT%2BZC6LPoOt6jgIstMzbtuitWbL8RuSiM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 22:46 UTC, sharad-sharma-msft commented on concepts/education-upload-resource-overview.md
> +            "displayName": "Graph explorer"
omitted

2021-07-13 22:47 UTC, opbld31 commented
Docs Build status updates of commit _[ba7d8ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba7d8abaa866e8c79d5d0f812913fd4fc70abfce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132245570078-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A46%3A13Z&ske=2021-07-20T07%3A51%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T22%3A42%3A34Z&se=2021-08-13T22%3A47%3A34Z&sr=b&sp=r&sig=fvWKbuG7NmZ1ZYebUI09L3E73MYNideS5vM%2BzA88Nno%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 00:39 UTC, opbld34 commented
Docs Build status updates of commit _[cca1667](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cca16672d1d17d80c95a77b78fcea45bfd136aa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107140037239126-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A50%3A00Z&ske=2021-07-20T07%3A55%3A00Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T00%3A34%3A08Z&se=2021-08-14T00%3A39%3A08Z&sr=b&sp=r&sig=P3xWym7DhfcbQsv8yOV1u4499EnBTEC9wH2ZMYp03K8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 19:34 UTC, JarbasHorst commented
Hi @sharad-sharma-msft 

I believe your PR is missing the toc entry for the new concept topic. Can you please add the toc entry to the concept TOC under Learn/Education?

![image](https://user-images.githubusercontent.com/26866873/125682027-1e314e38-d7a6-492f-bbaa-11d887980de0.png)

Thanks,
Jarbas

2021-07-14 22:15 UTC, JarbasHorst requested changes

2021-07-15 20:26 UTC, opbld34 commented
Docs Build status updates of commit _[f5f21a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5f21a270d892d72fa46483f537421ffd46fb62b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-e3465e20)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

<a id="949b1a7a379985a1b5d544757ce6733c-e3465e20"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 27, Column 81**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#Prerequisites' in 'education-upload-resource-overview.md', did you mean '#prerequisites'?`````
 - **Line 173, Column 177**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/educationsubmission-post-resources'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152025005696-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T19%3A27%3A26Z&ske=2021-07-21T19%3A32%3A26Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T20%3A21%3A32Z&se=2021-08-15T20%3A26%3A32Z&sr=b&sp=r&sig=OwCxodJ0S1lmQQHXGVdJzsLCMT8ZbeV%2BU0MFt7flfCk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 20:26 UTC, sharad-sharma-msft commented on concepts/education-upload-resource-overview.md
> +description: "Upload a file to a given educationAssignment or educationSubmission resource."
Hi @JarbasHorst , I have addressed your comments. Please review and help close the comments.

2021-07-15 20:37 UTC, opbld30 commented
Docs Build status updates of commit _[ee22578](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee2257890902e28abbf79bffb3fc6aa7c93dea3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-15a8fe63)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

<a id="949b1a7a379985a1b5d544757ce6733c-15a8fe63"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 27, Column 81**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#Prerequisites' in 'education-upload-resource-overview.md', did you mean '#prerequisites'?`````
 - **Line 175, Column 244**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/educationsubmission-post-resources'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152036034710-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A48Z&ske=2021-07-20T08%3A20%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T20%3A32%3A37Z&se=2021-08-15T20%3A37%3A37Z&sr=b&sp=r&sig=HOZDzizgpXBgKCrMqXg2u7aGuK1kuLPWrRtGtkPgn0k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 20:48 UTC, opbld33 commented
Docs Build status updates of commit _[9890dd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9890dd52e2c5e6fc57cac2f345b41a6748a3e6ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-430b66a2)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

<a id="949b1a7a379985a1b5d544757ce6733c-430b66a2"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 16, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Prerequisites') are not allowed. You can only have one top-level heading.`````
 - **Line 25, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Upload a resource') are not allowed. You can only have one top-level heading.`````
 - **Line 38, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Steps') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152046383606-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A37%3A23Z&ske=2021-07-20T08%3A42%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T20%3A43%3A11Z&se=2021-08-15T20%3A48%3A11Z&sr=b&sp=r&sig=TBhobQ7XEPoMCZt7OBcsaad8kVrWUJLkt8LX%2FijeJBk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 21:34 UTC, JarbasHorst commented
Hello @sharad-sharma-msft,

thanks for applying part of my feedback. Can you please review the comments that are still open?

Thanks,
Jarbas

2021-07-15 21:45 UTC, JarbasHorst commented
Hi @sharad-sharma-msft,

why did you [fix the links](https://github.com/microsoftgraph/microsoft-graph-docs/pull/13359/commits/9890dd52e2c5e6fc57cac2f345b41a6748a3e6ae)? The first heading within an article should be an H2, not an H1. Please revert your changes.

Thanks,
Jarbas

2021-07-15 22:45 UTC, opbld30 commented
Docs Build status updates of commit _[a866bc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a866bc7cb20f765edc782c445d8a6f7a4086b6a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-5c9da03d)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

<a id="949b1a7a379985a1b5d544757ce6733c-5c9da03d"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 27, Column 81**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '##prerequisites' in 'education-upload-resource-overview.md', did you mean '#prerequisites'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152242527438-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A32%3A25Z&ske=2021-07-20T08%3A37%3A25Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T22%3A40%3A50Z&se=2021-08-15T22%3A45%3A50Z&sr=b&sp=r&sig=DwD2Oa7OIG5KNbEEHQo4f%2BX4RckiQVs87YpOH5dwsPM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 22:53 UTC, opbld30 commented
Docs Build status updates of commit _[31d5d8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31d5d8e60690b67c1aacaeb9bff247e7586665bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-14dca9ee)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

<a id="949b1a7a379985a1b5d544757ce6733c-14dca9ee"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152251313336-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-15T08%3A34%3A11Z&ske=2021-07-22T08%3A39%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T22%3A48%3A26Z&se=2021-08-15T22%3A53%3A26Z&sr=b&sp=r&sig=fen2JS7KIZ1TmiGqvPZ2giYu0T8J8HSH1OxG%2FHSKViM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 23:32 UTC, opbld31 commented
Docs Build status updates of commit _[12ea97c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12ea97c1a6098332cc20c7b11116c4826e5a54d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107152330256424-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A50%3A51Z&ske=2021-07-20T07%3A55%3A51Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T23%3A27%3A02Z&se=2021-08-15T23%3A32%3A02Z&sr=b&sp=r&sig=Burho6GcHE%2FzTuBR0GdfbBJzORWCqqpuDGPkv8riCoc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 00:00 UTC, sharad-sharma-msft commented on concepts/education-upload-resource-overview.md
> +PUT https://graph.microsoft.com/v1.0/drives/b!6SQl0y4WHkS2P5MeIsSGpKwfynEIaD1OvPVeH4wbOp_1uyhNwJMSSpseJneB7Z4F/items/01YT2AIJRQLVYT24IWWFAJHMRRNYCB3GE2:/MyPictureFile.png:/content
good idea!

2021-07-16 00:28 UTC, opbld30 commented
Docs Build status updates of commit _[c168fd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c168fd2f9cb3e48c64aa46c40a1636618ae71bbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107160027130153-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A46%3A13Z&ske=2021-07-20T07%3A51%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T00%3A23%3A54Z&se=2021-08-16T00%3A28%3A54Z&sr=b&sp=r&sig=1PTHhlWCrjmUTC%2BCc08c%2BZ7DCkZw0FSTNivOlRBN6EU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 01:23 UTC, opbld33 commented
Docs Build status updates of commit _[0c66a47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c66a4754827b43b70314745475fa6b40099cdf8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107160121295477-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A31%3A59Z&ske=2021-07-20T08%3A36%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T01%3A18%3A00Z&se=2021-08-16T01%3A23%3A00Z&sr=b&sp=r&sig=boVPHFoLgHOzHHPRuzrbHvqLZ2P8ck0Mukm%2FsiaMLTk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:08 UTC, JarbasHorst requested changes

2021-07-16 19:08 UTC, JarbasHorst commented on concepts/education-upload-resource-overview.md
> +Use the `fileUrl` constructed in the previous step in the request body to [POST Assignment Resources](/graph/api/educationassignment-post-resources)
For consistency, replace "POST Assignment Resources" with "Create educationAssignmentResource"

2021-07-16 19:08 UTC, JarbasHorst commented on concepts/education-upload-resource-overview.md
> +```http
For consistency with your previous examples, please add the following HTTP headers to this example response:

```http
HTTP/1.1 201 Created
Content-type: application/json

{
...
}
```

2021-07-16 19:08 UTC, JarbasHorst commented on concepts/education-upload-resource-overview.md
> +Use the `fileUrl` constructed in the previous step in the request body to [POST Assignment Resources](/graph/api/educationassignment-post-resources)
Please, add a period at the end of the sentence.

2021-07-16 23:20 UTC, opbld33 commented
Docs Build status updates of commit _[cb47419](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb47419c4437d4e76c30422dd94ef9fffb22dca7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-7e03467d)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

<a id="949b1a7a379985a1b5d544757ce6733c-7e03467d"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 116, Column 1**: **[Warning-[table-syntax-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107162318241007-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A02%3A50Z&ske=2021-07-23T08%3A07%3A50Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T23%3A15%3A33Z&se=2021-08-16T23%3A20%3A33Z&sr=b&sp=r&sig=A473dJUTeurR1DI8tQnB3PgpJ7xvBrgo43Lnr0gVaV4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 19:36 UTC, cristobal-buenrostro commented
pretty small differences in Response at Step#4, specifically these properties.
```
"assignmentResourceUrl": null,
"distributeForStudentWork": false,
```
response from Graph explorer
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#education/classes('f4a941ff-9da6-4707-ba5b-0eae93cad0b4')/assignments('9018ae7a-9953-4796-a152-4c54e0910922')/resources/$entity",
    "distributeForStudentWork": false,
    "id": "eec7f642-9d9a-406f-bbae-4b3b2c12e273",
    "resource": {
        "@odata.type": "#microsoft.graph.educationFileResource",
        "displayName": "First file uploaded as Education resource by t-cristobalb",
        "createdDateTime": "2021-07-16T23:41:53.9378423Z",
        "lastModifiedDateTime": "2021-07-16T23:41:53.9378423Z",
        "fileUrl": "https://graph.microsoft.com/v1.0/drives/b!DPA6q59Tw0mtgmyXRUmrQRqBZTesG-lMkl1cBmvvMeU6BLWBcGc_R6UgCKyYyTin/items/016XPCQEA5VVDIMU4BSFG3VBI37MPHZ3OE",
        "createdBy": {
            "application": null,
            "device": null,
            "user": {
                "id": "f3a5344e-dbde-48b0-be24-b5b62a243836",
                "displayName": null
            }
        },
        "lastModifiedBy": {
            "application": null,
            "device": null,
            "user": {
                "id": "f3a5344e-dbde-48b0-be24-b5b62a243836",
                "displayName": null
            }
        }
    }
}
```

2021-07-20 00:08 UTC, opbld33 commented
Docs Build status updates of commit _[c4f001e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4f001e3a2cf987eb1583afd640209e553c6b342)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) | [Details](#user-content-949b1a7a379985a1b5d544757ce6733c-77550375)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

<a id="949b1a7a379985a1b5d544757ce6733c-77550375"></a>
### [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md)
 - **Line 116, Column 1**: **[Warning-[table-syntax-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107200006459776-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A33%3A50Z&ske=2021-07-26T02%3A38%3A50Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T00%3A03%3A14Z&se=2021-08-20T00%3A08%3A14Z&sr=b&sp=r&sig=%2Ba8NSzDmvFc2Ja%2Bd3m3NDH36h8iNzdDURy0F0RHa3HI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 00:16 UTC, opbld34 commented
Docs Build status updates of commit _[bc72dc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc72dc26e7fb9224879d12f6ee464f888dc2325a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107200013550949-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A36%3A30Z&ske=2021-07-26T03%3A41%3A30Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T00%3A11%3A23Z&se=2021-08-20T00%3A16%3A23Z&sr=b&sp=r&sig=6llSGIGheFIESvIjtf%2FLLhC%2FiBa%2BvbkHb%2Bi3YNOYXqI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 02:20 UTC, opbld32 commented
Docs Build status updates of commit _[70d8975](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70d8975a018ae2e19736e0fc465e7aee779ca374)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107200219060869-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A27%3A45Z&ske=2021-07-26T03%3A32%3A45Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T02%3A15%3A43Z&se=2021-08-20T02%3A20%3A43Z&sr=b&sp=r&sig=ACAN%2FeN4adkx9ZTJpHV1B3qSGK8Rw0%2F%2BsSQ7kB18368%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 02:22 UTC, opbld33 commented
Docs Build status updates of commit _[fe459f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe459f50b7385e03657f9707fc8c7ea1b9a66d05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107200219450549-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A37%3A59Z&ske=2021-07-26T02%3A42%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T02%3A17%3A24Z&se=2021-08-20T02%3A22%3A24Z&sr=b&sp=r&sig=cLSqr5Z0wM6R%2FIJ6e9WCy2ag4mm7Se1tbGWqNFxm6sw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 03:31 UTC, opbld32 commented
Docs Build status updates of commit _[ef18f30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef18f30b6e52348d782995eb9ea9e6e129aff8e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210330072149-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T04%3A19%3A31Z&ske=2021-07-26T04%3A24%3A31Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T03%3A26%3A44Z&se=2021-08-21T03%3A31%3A44Z&sr=b&sp=r&sig=4Qyf8qOSVD3nDn52RuKANRzFhsBkyMHLsYIlwffskB4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 03:39 UTC, Lauragra approved these changes

2021-07-21 03:41 UTC, opbld32 commented
Docs Build status updates of commit _[6458983](https://github.com/microsoftgraph/microsoft-graph-docs/commits/645898330f8a6f7cd9566bf39a44a44e26a43869)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/education-upload-resource-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sharad-sharma-msft/uploadResourceConcept/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/education-upload-resource-overview?branch=pr-en-us-13359) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210339459189-13359%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A13%3A37Z&ske=2021-07-26T03%3A18%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-21T03%3A36%3A04Z&se=2021-08-21T03%3A41%3A04Z&sr=b&sp=r&sig=e5uZUvJMYnKElvgyHI0n9Q75rF0w5grQhbnSaG1rq38%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 03:45 UTC, merged