Azure AD Reporting quarterly updates Q4 FY2021
microsoftgraph/microsoft-graph-docs pull request #13361
Opened 2021-07-02 20:36 UTC by besiler

Added properties to the signin resource:

authenticationRequirementPolicies
autonomousSystemNumber
crossTenantAccessType
flaggedForReview
homeTenantId
isInteractive
isTenantRestricted
privateLinkDetails
resourceTenantId
alternateSignInName
servicePrincipalCredentialKeyId
servicePrincipalCredentialThumbprint
signInEventTypes

2021-07-02 20:39 UTC, opbld33 commented
Docs Build status updates of commit _[56a3e58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56a3e581be11f754a8449e3e0769bd8808b2def9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) | [Details](#user-content-b4ce98cf195e9f3e8b526ba9744a18e7-34569fa7)
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) | [Details](#user-content-6ddef4501765822a1919c515d4c8f77e-34569fa7)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="b4ce98cf195e9f3e8b526ba9744a18e7-34569fa7"></a>
### [api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md)
 - **Line 16, Column 122**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/private-link/private-link-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 16, Column 122**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/azure/private-link/private-link-overview' will be broken in isolated environments. Replace with a relative link.`````

<a id="6ddef4501765822a1919c515d4c8f77e-34569fa7"></a>
### [api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md)
 - **Line 37, Column 36**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/authenticationrequirementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107022036500992-13361%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-02T10%3A21%3A56Z&ske=2021-07-09T10%3A26%3A56Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-02T20%3A34%3A07Z&se=2021-08-02T20%3A39%3A07Z&sr=b&sp=r&sig=xNQwhy2DiaSZc9AIeMEdMRuHIU4AtNa%2Bw2hWNw7gN0E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-06 07:25 UTC, FaithOmbongi requested changes
- Proposed minor changes.
- Missing Enum declarations for **signInUserType**, **signInIdentifierType**. Also add them to your changelog.

2021-07-06 07:25 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|resourceTenantId|String|The tenant identifier of the resource referenced in the sign in.|
```suggestion
|resourceTenantId|String|The tenant identifier of the resource that the user signed in to.|
```

2021-07-06 07:25 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|servicePrincipalCredentialThumbprint|String|The certificate thumbprint of the certificate used by a service principal to authenticate in the sign-in event.|
```suggestion
|servicePrincipalCredentialKeyId|String|The unique identifier of the key credential used by the service principal to authenticate.|
|servicePrincipalCredentialThumbprint|String|The certificate thumbprint of the certificate used by the service principal to authenticate.|
```

2021-07-06 07:25 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|signInEventTypes|String collection|Indicates the category of sign in the event represents. For user sign ins, the category can be interactiveUser or nonInteractiveUser; the category for a user sign
```suggestion
|signInEventTypes|String collection|Indicates the category of sign in that the event represents. For user sign ins, the category can be `interactiveUser` or `nonInteractiveUser` and corresponds to the value for the **isInteractive** property on the signin resource. For managed identity sign ins, the category is `managedIdentity`. For service principal sign ins, the category is **servicePrincipal**. Possible values are: `interactiveUser`, `nonInteractiveUser`, `servicePrincipal`, `managedIdentity`, `unknownFutureValue`.|
```

2021-07-06 07:25 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|signInIdentifierType|signInIdentifierType|Provides the type of sign-in identifier. Possible values are: `userPrincipalName`, `phoneNumber`, `proxyAddress`, `qrCode`, `onPremisesUserPrincipalName`, `
```suggestion
|signInIdentifier|String|The identification that the user provided to sign in. It may be the userPrincipalName but it's also populated when a user signs in using other identifiers.|
|signInIdentifierType|signInIdentifierType|The type of sign in identifier. Possible values are: `userPrincipalName`, `phoneNumber`, `proxyAddress`, `qrCode`, `onPremisesUserPrincipalName`, `unknownFutureValue`.|
```

2021-07-06 07:25 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|userType|signInUserType|Identifies whether the user is a member or guest in the tenant that performed the sign in. Possible values are: `member`, `guest`, `unknownFutureValue`.|
```suggestion
|userType|signInUserType|Identifies whether the user is a member or guest in the tenant. Possible values are: `member`, `guest`, `unknownFutureValue`.|
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "244631fe-cf8c-11eb-995f-5903f88189f5",
All changelog objects in a single ChangeList should have the same Id value.
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "24489507-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "244af7d7-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "244d59c2-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "244fbe87-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "245233fd-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "2456e2d7-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "24594642-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "245ba66e-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "245e0b51-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +              "Id": "24606f6b-cf8c-11eb-995f-5903f88189f5",
```suggestion
              "Id": "2443cc12-cf8c-11eb-995f-5903f88189f5",
```

2021-07-06 07:25 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +      "WorkloadArea": "Reports and audit",
```suggestion
      "CreatedDateTime": "2021-07-06T16:50:37.572Z",
      "WorkloadArea": "Reports",
```

2021-07-07 15:35 UTC, besiler commented
> * Proposed minor changes.
> * Missing Enum declarations for **signInUserType**, **signInIdentifierType**. Also add them to your changelog.

@FaithOmbongi for the changelog, the docgenerator tool didn't create entries for signInUserType and signInIdentifierType. Can I just generate GUIDs for those changes? So the entry would look something like this?

"Id": "[GUID]",
              "ApiChange": "Property",
              "ChangedApiName": "signinUserType",
              "ChangeType": "Addition",
              "Description": "Added the **signinUserType** property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
              "Target": "signIn"

2021-07-07 15:44 UTC, FaithOmbongi commented
> > * Proposed minor changes.
> > * Missing Enum declarations for **signInUserType**, **signInIdentifierType**. Also add them to your changelog.
> 
> @FaithOmbongi for the changelog, the docgenerator tool didn't create entries for signInUserType and signInIdentifierType. Can I just generate GUIDs for those changes? So the entry would look something like this?
> 
> "Id": "[GUID]",
> "ApiChange": "Property",
> "ChangedApiName": "signinUserType",
> "ChangeType": "Addition",
> "Description": "Added the **signinUserType** property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
> "Target": "signIn"

@besiler , no need to generate GUIDs. Use the same GUID as all other entries of the ChangeList you've added.

ApiChange: Enum type
Description: Added the **signinUserType** enumeration.

2021-07-07 16:05 UTC, besiler commented
> > > * Proposed minor changes.
> > > * Missing Enum declarations for **signInUserType**, **signInIdentifierType**. Also add them to your changelog.
> > 
> > 
> > @FaithOmbongi for the changelog, the docgenerator tool didn't create entries for signInUserType and signInIdentifierType. Can I just generate GUIDs for those changes? So the entry would look something like this?
> > "Id": "[GUID]",
> > "ApiChange": "Property",
> > "ChangedApiName": "signinUserType",
> > "ChangeType": "Addition",
> > "Description": "Added the **signinUserType** property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
> > "Target": "signIn"
> 
> @besiler , no need to generate other GUIDs. Use the same GUID as all other entries of the ChangeList you've added.
> 
> ApiChange: Enum type
> Description: Added the **signInUserType** enumeration.

Thanks for the info! All the GUIDs the docgenerator gave me are slightly different - is that OK or should I manually copy one into all the entries so they're the same? See pic for the different GUIDs I got from the tool. 

![image](https://user-images.githubusercontent.com/69605773/124793039-745b4800-df02-11eb-8e9e-d27e3c6ce0ae.png)

2021-07-07 16:08 UTC, FaithOmbongi commented
> > > > * Proposed minor changes.
> > > > * Missing Enum declarations for **signInUserType**, **signInIdentifierType**. Also add them to your changelog.
> > > 
> > > 
> > > @FaithOmbongi for the changelog, the docgenerator tool didn't create entries for signInUserType and signInIdentifierType. Can I just generate GUIDs for those changes? So the entry would look something like this?
> > > "Id": "[GUID]",
> > > "ApiChange": "Property",
> > > "ChangedApiName": "signinUserType",
> > > "ChangeType": "Addition",
> > > "Description": "Added the **signinUserType** property to the [signIn](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta) resource.",
> > > "Target": "signIn"
> > 
> > 
> > @besiler , no need to generate other GUIDs. Use the same GUID as all other entries of the ChangeList you've added.
> > ApiChange: Enum type
> > Description: Added the **signInUserType** enumeration.
> 
> Thanks for the info! All the GUIDs the docgenerator gave me are slightly different - is that OK or should I manually copy one into all the entries so they're the same? See pic for the different GUIDs I got from the tool.
> 
> ![image](https://user-images.githubusercontent.com/69605773/124793039-745b4800-df02-11eb-8e9e-d27e3c6ce0ae.png)

That must be a bug. I'll raise it with the stub generator team.
Yes, choose one GUID for all entries in the ChangeList.

2021-07-07 18:14 UTC, besiler commented on api-reference/beta/api/signin-get.md
>  {
Ack - will do

2021-07-07 18:17 UTC, besiler commented on api-reference/beta/resources/signin.md
> +|resourceTenantId|String|The tenant identifier of the resource referenced in the sign in.|
Sometimes the sign in can be for a service principal, so referring to a user here is a little over specific.

2021-07-07 18:18 UTC, besiler commented on api-reference/beta/resources/signin.md
> +|resourceTenantId|String|The tenant identifier of the resource referenced in the sign in.|
What if we said "The tenant identifier of the resource that the user or service principal signed in to"

2021-07-07 18:19 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|resourceTenantId|String|The tenant identifier of the resource referenced in the sign in.|
Sounds good.

2021-07-07 18:22 UTC, opbld34 commented
Docs Build status updates of commit _[7311c50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7311c50c1dce4da5dad69307b1d3f9884011ad18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) | [Details](#user-content-6ddef4501765822a1919c515d4c8f77e-00824729)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="6ddef4501765822a1919c515d4c8f77e-00824729"></a>
### [api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md)
 - **Line 37, Column 36**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/authenticationrequirementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107071820344229-13361%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A28%3A08Z&ske=2021-07-13T07%3A33%3A08Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T18%3A17%3A21Z&se=2021-08-07T18%3A22%3A21Z&sr=b&sp=r&sig=tmjqvHFWOi2%2B6a3QVFe8q%2BBzvOOOh4nl1gJLUb21gw8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 03:31 UTC, CelesteDG commented
@FaithOmbongi and @besiler - When you get a chance, can you please review? This got out of date from main but also running into some validation issues with API doctor. I can merge once the API doctor issue has been addressed. Thank you.

2021-07-27 06:18 UTC, opbld31 commented
Docs Build status updates of commit _[7311c50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7311c50c1dce4da5dad69307b1d3f9884011ad18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) | [Details](#user-content-6ddef4501765822a1919c515d4c8f77e-89bc9181)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="6ddef4501765822a1919c515d4c8f77e-89bc9181"></a>
### [api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md)
 - **Line 37, Column 36**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/authenticationrequirementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270616581570-13361%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A35%3A40Z&ske=2021-08-02T02%3A40%3A40Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T06%3A13%3A50Z&se=2021-08-27T06%3A18%3A50Z&sr=b&sp=r&sig=oSBli9LK0Bvgn6QepbVy3xQRpCgphzvyCIp91%2FCCp8o%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 06:38 UTC, FaithOmbongi requested changes
@besiler , some validation errors need your attention + don't forget to add the changelog entry for that new complex type that's required.

2021-07-29 18:06 UTC, besiler commented
@FaithOmbongi the validation error for a missing resource makes me think that we need to add a authenticationrequirementpolicy.md resource, so I'll do that

2021-07-29 20:02 UTC, opbld30 commented
Docs Build status updates of commit _[f1963f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1963f4d059b90d7c8c57fc9453600ba4e63f5ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107292001127073-13361%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A14%3A23Z&ske=2021-08-04T04%3A19%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T19%3A57%3A48Z&se=2021-08-29T20%3A02%3A48Z&sr=b&sp=r&sig=PfzWdQ0jJoxoPLvHCOj2bvMUxlYeTLtWJmdnPE6oic0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 21:08 UTC, besiler commented
@FaithOmbongi all the checks are now succeeding. 

Also, I added the changelog entries manually:

![image](https://user-images.githubusercontent.com/69605773/127566007-81d25f4f-0395-4900-bc47-dea8c66bc3b0.png)

2021-07-29 21:31 UTC, opbld34 commented
Docs Build status updates of commit _[aad4079](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aad407969d17ffdeb84bc4f1b5ff179a376148b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107292130292202-13361%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A20%3A50Z&ske=2021-08-04T04%3A25%3A50Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T21%3A26%3A57Z&se=2021-08-29T21%3A31%3A57Z&sr=b&sp=r&sig=2DCnHtBD52Y6m7SWyaGPrkKoSkqmn9y3aLEyzxL01ns%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-02 09:16 UTC, FaithOmbongi requested changes
- Add 3 missing enum declarations. These will resolve the validation error.
- Changelog entries are incorrect for adding
     - Enumeration. See [Example 4 in the Changelog guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog)
     - Member to an enumeration. See [Example 5 in the Changelog guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog)

- Highlighted a gap that comes to light thanks to the conditionalAccessRule Enum type.
- Plugged you into an email about handling of evolvable enums

2021-08-02 09:16 UTC, FaithOmbongi commented on api-reference/beta/resources/enums.md
Missing requirementProvider, signInUserType, and signInIdentifierType enum declarations. These will resolve the validation error.

2021-08-02 09:16 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          }
1. Are we really deleting the sentinel value? Plugged you into an email where we now have guidance on documenting Enums.

![image](https://user-images.githubusercontent.com/14026935/127836406-1ae7771a-4451-4669-af0b-c1f36e49ab8e.png)


2. This Enumeration (conditionalAccessRule) brings to light a doc gap. conditionalAccessRuleSatisfied complex type is not documented and [appliedConditionalAccessPolicy ](https://docs.microsoft.com/en-us/graph/api/resources/appliedConditionalAccessPolicy?view=graph-rest-beta)complex type does not list all the properties. Let's close this gap. Don't forget to add the complex type to the Changelog.

![image](https://user-images.githubusercontent.com/14026935/127836307-628fa3f5-38d4-477c-818b-5fbd21c3f0a2.png)

2021-08-02 09:16 UTC, FaithOmbongi commented on changelog/Microsoft.AAD.Reporting.json
> +          },
Let's follow the guidance.

2021-08-05 00:36 UTC, opbld33 commented
Docs Build status updates of commit _[ffc6c75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffc6c75f55b66c7def8363720bb5e1d5e0dbccf7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108050033373582-13361%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=IY2lhVDTBEWVcDaxX7f5w4ZSX2ecMy9Y%2BRfN%2BqIiChk%3D&st=2021-08-05T00%3A31%3A10Z&se=2021-09-05T00%3A36%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 00:37 UTC, opbld31 commented
Docs Build status updates of commit _[7369ddf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7369ddf02bc733a2a1d5c7e32ced3228fa3fdb51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108050035396779-13361%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=i8ThXrEh%2Fe74RDoddrHd62KbzdET9F65zGGmgln%2FlGg%3D&st=2021-08-05T00%3A32%3A56Z&se=2021-09-05T00%3A37%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 22:22 UTC, besiler commented on api-reference/beta/resources/enums.md
Not sure why the docsgeneratorclient didn't provide those - maybe I missed it. I'll add them from Abbe's PR: https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/4462802?_a=files&path=%2FWorkloads%2FMicrosoft.AAD.Reporting%2Foverride%2Fschema-PPE-beta.csdl

2021-08-06 23:43 UTC, opbld31 commented
Docs Build status updates of commit _[5f7aae3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f7aae3c8b1fea102f62c06144209b2a2700a504)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2481570e)

<a id="2481570e"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108062342272689-13361%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9TtlmN9TjQBhdtDmEO%2FuhOElW53Ko%2BBuIJWUBca1beA%3D&st=2021-08-06T23%3A38%3A45Z&se=2021-09-06T23%3A43%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 23:45 UTC, opbld31 commented
Docs Build status updates of commit _[77a1237](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77a1237d8e0a65392fc1ac895a26392fe9e00aeb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108062344189356-13361%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eEkRZ%2F0fOULd6X%2F0YpTLbgyuDo11unO979ytFf35q9k%3D&st=2021-08-06T23%3A40%3A40Z&se=2021-09-06T23%3A45%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 23:50 UTC, besiler commented on changelog/Microsoft.AAD.Reporting.json
> +          },
What specifically  needs to change? Since the Graph docs tooling didn't work (the docsGeneratorClient didn't provide the right GUIDs or enough changes in the change log), I'm not sure what needs to be added or removed

2021-08-06 23:55 UTC, besiler commented on changelog/Microsoft.AAD.Reporting.json
> +          }
What do you mean by deleting the sentinel value?

2021-08-18 17:48 UTC, besiler commented
@FaithOmbongi shared this doc with changes needed for this PR: https://microsoft-my.sharepoint.com/:w:/p/ombongifaith/ERr2jlkzN7tFtJCYCS6mGlcBA94QqBgZvpyLLdQs3GaSkw?e=YRdEf0

2021-09-08 18:42 UTC, FaithOmbongi requested changes
Proposed one change.

2021-09-08 18:42 UTC, FaithOmbongi commented on api-reference/beta/resources/signin.md
> +|signInEventTypes|String collection|Indicates the category of sign in that the event represents. For user sign ins, the category can be `interactiveUser` or `nonInteractiveUser` and corresponds to th
```suggestion
|signInEventTypes|String collection|Indicates the category of sign in that the event represents. For user sign ins, the category can be `interactiveUser` or `nonInteractiveUser` and corresponds to the value for the **isInteractive** property on the signin resource. For managed identity sign ins, the category is `managedIdentity`. For service principal sign ins, the category is **servicePrincipal**. Possible values are: `interactiveUser`, `nonInteractiveUser`, `servicePrincipal`, `managedIdentity`, `unknownFutureValue`. Supports `$filter` (`eq` operator only).|
```

2021-10-01 22:22 UTC, opbld34 commented
Docs Build status updates of commit _[2b66f08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b66f08909d8bbb1b0c73b1b2ad1dead6fd12f64)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b43a9bfd)

<a id="b43a9bfd"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202110012222301173-13361%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T22%3A22%3A51Z&sr=b&sp=r&sig=Z2O3IqkfRjY%2B8ltqttR9xrbI1oUSk3T6mjbzIh15bfo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 23:24 UTC, opbld31 commented
Docs Build status updates of commit _[2b66f08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b66f08909d8bbb1b0c73b1b2ad1dead6fd12f64)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-258cf613)

<a id="258cf613"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112172323454095-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T23%3A24%3A08Z&sr=b&sp=r&sig=SL4wUmD0GbV1jaWD67%2Fv1hAyeBPKebg2p1FjO4ECsmc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-17 23:45 UTC, opbld34 commented
Docs Build status updates of commit _[d90c101](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d90c1014be77a32eea253debc334cea8a8482dd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112172342523768-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T23%3A45%3A07Z&sr=b&sp=r&sig=fKn37MWmoB4kBSDo5WSyJbJCO9Ei%2BezZMoGoAqjUxEg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-20 21:19 UTC, opbld34 commented
Docs Build status updates of commit _[cd4ccda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd4ccda332292295fd9a64c173b03bf5e2b8244e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112202117149366-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-20T21%3A19%3A12Z&sr=b&sp=r&sig=t8hfRCVDD0bK7%2FxeJOXtP0SqBUj1jIp0m6qPdKopwV8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 19:56 UTC, opbld33 commented
Docs Build status updates of commit _[73200b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73200b37bbd1fda20fec7e8f3446a1261d35d008)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessRulesSatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalAccessRulesSatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulessatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112211954412070-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T19%3A56%3A29Z&sr=b&sp=r&sig=yl3sTpMp4zRKMP5o0djduXaQ7Dg%2BlToRogMqv71J4N4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 20:08 UTC, opbld30 commented
Docs Build status updates of commit _[8be61ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8be61aba13e0f3184a43a40a8100d57928bc915d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) | [Details](#user-content-28013653079cb095cad51675b28e0de8-eaa3f2af)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessRulesSatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalAccessRulesSatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulessatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="28013653079cb095cad51675b28e0de8-eaa3f2af"></a>
### [api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md)
 - **Line 27, Column 24**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/conditionalAccessRulesSatisified.md'.`````
 - **Line 29, Column 24**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/conditionalAccessRulesSatisified.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112212004432771-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T20%3A08%3A24Z&sr=b&sp=r&sig=5ee828IfC6VmOR5E8ynQkfZsv%2BgXOraHYL9wPvG%2FqLI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 20:15 UTC, opbld31 commented
Docs Build status updates of commit _[4d221ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d221ae5a344b4a638b5dc80a1aba52ff4c1290f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalAccessRulesSatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalAccessRulesSatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulessatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112212013540769-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-21T20%3A15%3A51Z&sr=b&sp=r&sig=M8xU3lvQdChmH%2BvKtzeFjJs75vOrITU3DaKaBmwZWFA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 20:22 UTC, besiler commented
@FaithOmbongi I think this one should now be good to go

2021-12-22 06:26 UTC, FaithOmbongi commented
@besiler Adding this to my re-review queue.

2021-12-28 08:03 UTC, opbld32 commented
Docs Build status updates of commit _[aae4681](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aae46811a14f92e02398ba3c2e682755f962b36c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) | [Details](#user-content-28013653079cb095cad51675b28e0de8-87f6cdcb)
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessrulesatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalaccessrulesatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulesatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="28013653079cb095cad51675b28e0de8-87f6cdcb"></a>
### [api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md)
 - **Line 27, Column 24**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/conditionalAccessRulesSatisfied.md'.`````
 - **Line 29, Column 24**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/conditionalAccessRulesSatisfied.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112280801054026-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T08%3A03%3A35Z&sr=b&sp=r&sig=7R1hpNEmLf%2BEci5MVDD6GIfeogWFJYmfBbRywslc3f8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 09:05 UTC, opbld32 commented
Docs Build status updates of commit _[601c91f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/601c91f8564521cf2775745d5fdac37a58ea453c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessrulesatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalaccessrulesatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulesatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112280902143745-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T09%3A05%3A02Z&sr=b&sp=r&sig=PUSymkqWU0lIMN0VYDydA89LFrla2PJBg8%2FBRRUIosA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 09:10 UTC, opbld33 commented
Docs Build status updates of commit _[e6dd076](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6dd076b4b589318499030245cb996825bdb3166)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessrulesatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalaccessrulesatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulesatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112280907385345-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T09%3A10%3A32Z&sr=b&sp=r&sig=ydyXOvmQNtCWuJhuTvKwsdOsNVDCdAzRdJUHXNOt9KY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 09:20 UTC, opbld30 commented
Docs Build status updates of commit _[e3114a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3114a1a07bdad354460dffd0718e41804a9b630)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessrulesatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalaccessrulesatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulesatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112280916579931-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T09%3A20%3A16Z&sr=b&sp=r&sig=ziDIu7TTUX420yHZUGe%2BLmXj1lNWLxiyT%2BOur%2FUFJXs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 09:28 UTC, FaithOmbongi approved these changes
@besiler. Thank you for addressing the feedback to this PR. I've pushed a few minor changes and set the PR to ready to merge.

2021-12-28 22:08 UTC, isvargasmsft commented
@FaithOmbongi please check the conflicts in this PR and we can merge once resolved :)

2021-12-29 07:08 UTC, opbld30 commented
Docs Build status updates of commit _[01746a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01746a3b49096563fd7760633be1b3ea97646774)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessrulesatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalaccessrulesatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulesatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112290705299070-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-29T07%3A08%3A56Z&sr=b&sp=r&sig=SckV6EvBxRL113pAvgKLNg3gCgxAq49jNgdJb4dd1Xk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-29 08:04 UTC, opbld31 commented
Docs Build status updates of commit _[c605e34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c605e34b60a4c6b1f200d3fe4187e3ab76633d3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/signin-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-get?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/api/signin-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/authenticationrequirementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/authenticationrequirementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationrequirementpolicy?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessrulesatisfied.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/conditionalaccessrulesatisfied.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessrulesatisfied?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/privatelinkdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/privatelinkdetails.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/privatelinkdetails?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-13361) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-06-17-besiler-quarterlyupdatesQ42021/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202112290801512227-13361%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-29T08%3A04%3A02Z&sr=b&sp=r&sig=kIC0ysp3guHrsOXciSoEIoRB%2BN2hE1FF4ZU%2F%2B%2FiRMRs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-29 20:14 UTC, merged