Documentation for v1.0 PSTN and direct routing report
microsoftgraph/microsoft-graph-docs pull request #13376
Opened 2021-07-05 13:26 UTC by SanderSade

2021-07-05 13:32 UTC, opbld30 commented
Docs Build status updates of commit _[7f95b38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f95b38b3ad14bf0910de921e71b35b2633ea852)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-754816fc)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-754816fc)
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

<a id="f306095039a2f930fe6fa0822f23ab80-754816fc"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="36c51a473313ada6c6e27513f12760d7-754816fc"></a>
### [concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md)
 - **Line 13, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 29**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 172**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 260**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 394**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107051326345732-13376%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-05T10%3A37%3A24Z&ske=2021-07-12T10%3A42%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-05T13%3A27%3A19Z&se=2021-08-05T13%3A32%3A19Z&sr=b&sp=r&sig=jVn3epn3QVjRoERStPU%2BTa1Y92CZE%2B7nsgzaZ46Bj0s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77 [...]

2021-07-05 13:46 UTC, opbld33 commented
Docs Build status updates of commit _[cd8db10](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd8db1041f8f772189dcce850388fb9abfad58a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-ff91e913)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-ff91e913)
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

<a id="f306095039a2f930fe6fa0822f23ab80-ff91e913"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="36c51a473313ada6c6e27513f12760d7-ff91e913"></a>
### [concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md)
 - **Line 13, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 29**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 172**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 260**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 394**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107051340596467-13376%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-05T09%3A59%3A31Z&ske=2021-07-12T10%3A04%3A31Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-05T13%3A41%3A23Z&se=2021-08-05T13%3A46%3A23Z&sr=b&sp=r&sig=f9FB7sNUmsSA2%2FK5k10guaxlTpD0W38zYqsYbn3ro8A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e6 [...]

2021-07-06 15:33 UTC, stephenjust approved these changes

2021-07-06 15:33 UTC, stephenjust commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecords.Read.All |
Do we want to document CallRecord-PstnCalls.Read.All?

2021-07-07 11:57 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecords.Read.All |
Probably not, since it seems superfluous - e.g. too fine-grained, no one wants to see just PSTN and direct routing calls.

2021-07-07 15:14 UTC, williamlooney commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecords.Read.All |
If it exists it should be documented, otherwise we risk getting a ticket opened for an undocumented permission.

2021-07-08 07:54 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecords.Read.All |
I added the information to both report pages and overall Graph permissions

2021-07-08 07:55 UTC, opbld32 commented
Docs Build status updates of commit _[c07b0cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c07b0cb23d5bdbcb5d3fe98d06acf6c4036117cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-586a4368)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-586a4368)
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="f306095039a2f930fe6fa0822f23ab80-586a4368"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="36c51a473313ada6c6e27513f12760d7-586a4368"></a>
### [concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md)
 - **Line 13, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 29**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 172**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 260**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 394**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080754027006-13376%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-07T22%3A59%3A39Z&ske=2021-07-14T23%3A04%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T07%3A50%3A35Z&se=2021-08-08T07%3 [...]

2021-07-13 15:06 UTC, williamlooney approved these changes

2021-07-15 13:11 UTC, opbld30 commented
Docs Build status updates of commit _[d120022](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d12002226874ccf68d3ba616970c2b3d39a4fdab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-804c3580)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-804c3580)
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="f306095039a2f930fe6fa0822f23ab80-804c3580"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="36c51a473313ada6c6e27513f12760d7-804c3580"></a>
### [concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md)
 - **Line 13, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 29**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 172**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 260**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 27, Column 394**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107151310223089-13376%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A15%3A34Z&ske=2021-07-20T08%3A20%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T13%3A06%3A53Z&se=2021-08-15T13% [...]

2021-07-15 13:20 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
Could you please add this permission line in the beta topic as well?

2021-07-15 13:23 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +## Examples
Since it is just one example, please use singular here: Example

2021-07-15 13:23 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +  "blockType": "ignored",
Please use the proper blocktype: request.

2021-07-15 13:23 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +  "blockType": "ignored",
Please use the proper blocktype: response.

2021-07-15 13:26 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +* [PSTN call report in Microsoft Graph](callrecords-callrecord-getpstncalls.md)
Please end these sentences with a period.

2021-07-15 13:34 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
Could you please include this permission line in the beta topic as well.

2021-07-15 13:35 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +  "blockType": "ignored",
Please use the proper blocktype: request.

2021-07-15 13:36 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +## Examples
Please use singular in this title.

2021-07-15 13:36 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +  "blockType": "ignored",
Please use the proper blocktype: response.

2021-07-15 13:37 UTC, isvargasmsft commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +* [Direct routing report in Microsoft Graph](callrecords-callrecord-getdirectroutingcalls.md)
Please end these sentences with period.

2021-07-15 14:46 UTC, isvargasmsft commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +  "blockType": "ignored",
Please the proper blocktype: resource. 
Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor

2021-07-15 14:53 UTC, isvargasmsft commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +|userPrincipalName|String|UserPrincipalName (sign-in name) in Azure Active Directory. This is usually the same as user's SIP Address, and can be same as user's e-mail address.|
Please confirm if only these properties will be available in V1. Beta version has more properties listed.

2021-07-15 14:55 UTC, isvargasmsft commented on api-reference/v1.0/resources/callrecords-pstncalllogrow.md
> +  "blockType": "ignored",
Please use the proper blocktype: resource.

2021-07-15 15:02 UTC, isvargasmsft commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "ChangedApiName": "pstnCallDurationSource",
Please do not edit previous Changelog entries. Please add these new changes in a new ChangeList at the top of the changelog. Guidance here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

2021-07-15 15:03 UTC, isvargasmsft commented on concepts/cloud-communications-callrecords.md
> +Organizations that use Microsoft Teams to connect to the public switched telephone network (PSTN) usually want to track this usage to understand the associated costs. The [getPstnCalls](/graph/api/ca
Please remove the view parameter. It will automatically re-direct to the canonical version.

2021-07-15 15:06 UTC, isvargasmsft requested changes
Thank you very much for your work in this PR.
Just a few requests:
1. Please do not edit existing changelog entries. Create a new ChangeList to add new features to v1. 
2. Please remember to use the proper blocktypes for API Doctor. 
3. Please add the new permissions to the beta topics as well. 

Please feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2021-07-21 08:00 UTC, opbld30 commented
Docs Build status updates of commit _[2ac610d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ac610dd71a0d8ba5e88caf80ac36fc103a05d28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-6db5bd5d)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-6db5bd5d)
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="f306095039a2f930fe6fa0822f23ab80-6db5bd5d"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="36c51a473313ada6c6e27513f12760d7-6db5bd5d"></a>
### [concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md)
 - **Line 13, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 29**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210759024021-13376%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A3 [...]

2021-07-21 08:20 UTC, opbld31 commented
Docs Build status updates of commit _[2cc96aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cc96aa65394b0dc494579de9cb52675739dc2e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-9d26e6c6)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-9d26e6c6)
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="f306095039a2f930fe6fa0822f23ab80-9d26e6c6"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

<a id="36c51a473313ada6c6e27513f12760d7-9d26e6c6"></a>
### [concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md)
 - **Line 13, Column 82**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0. Otherwise, remove the view parameter.`````
 - **Line 23, Column 29**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107210819140718-13376%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A2 [...]

2021-07-21 08:24 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
Added

2021-07-21 08:25 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +## Examples
Fixed

2021-07-21 08:25 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +  "blockType": "ignored",
Changed to "request"

2021-07-21 08:25 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +  "blockType": "ignored",
Changed to "response"

2021-07-21 08:25 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +* [PSTN call report in Microsoft Graph](callrecords-callrecord-getpstncalls.md)
Fixed

2021-07-21 08:25 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
Added

2021-07-21 08:26 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +  "blockType": "ignored",
Changed to "request"

2021-07-21 08:26 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +## Examples
Changed

2021-07-21 08:26 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +  "blockType": "ignored",
Changed to "response"

2021-07-21 08:26 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +* [Direct routing report in Microsoft Graph](callrecords-callrecord-getdirectroutingcalls.md)
Fixed

2021-07-21 08:26 UTC, SanderSade commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +  "blockType": "ignored",
Changed to "resource"

2021-07-21 08:27 UTC, SanderSade commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +|userPrincipalName|String|UserPrincipalName (sign-in name) in Azure Active Directory. This is usually the same as user's SIP Address, and can be same as user's e-mail address.|
Both beta and v1.0 have 21 properties - however, per previous PR comment for beta docs for PSTN row, the table is now sorted.

2021-07-21 08:28 UTC, SanderSade commented on api-reference/v1.0/resources/callrecords-pstncalllogrow.md
> +  "blockType": "ignored",
Changed to "resource"

2021-07-21 08:28 UTC, SanderSade commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "ChangedApiName": "pstnCallDurationSource",
Moved the new entry to the top. The old one was not edited beyond whitespace formatting, which was invalid.

2021-07-21 08:28 UTC, SanderSade commented on concepts/cloud-communications-callrecords.md
> +Organizations that use Microsoft Teams to connect to the public switched telephone network (PSTN) usually want to track this usage to understand the associated costs. The [getPstnCalls](/graph/api/ca
Removed

2021-07-30 20:20 UTC, angelgolfer-ms commented on api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
@SanderSade , if CallRecord-PstnCalls.Read.All is a new permission your team is adding, then please also update the permissions reference topic (https://docs.microsoft.com/en-us/graph/permissions-reference#call-records-permissions).

If the same method supports more than one application permission, you should please order them from least to most privileged. Do not add a separate table row like in line 26.

2021-07-30 20:26 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/callrecords-api-overview.md
The following comment applies to the same topic in both the **v1.0** and  **beta** version as well.

Lines 23 and 24:
Please update the "Methods" column to say "List PSTN calls" and not "Get pstnCallLogRow". The latter would return a single row in the log, which is inconsistent with the getPstnCalls method.
Similarly, use "List direct routing calls" as link text, and not "Get directRoutingLogRow".

2021-07-30 21:04 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/callrecords-api-overview.md
The following comment is related to exposing the 2 methods getPstnCalls and getDirectRoutingCalls, in both the **v1.0 and beta** versions.

First, correct the beta version of callrecords-callrecord.md:
In the existing Methods table, the 2nd and 3rd rows have errors:
The second row should use the actual method name "getPstnCalls" and not "Get PSTN calls". In the Graph docs, we use the actual method name if the method is not defined as a CRUD operation. I think this is also where the original confusion could have come in, resulting in this mix of the method name not matching the return type and description.
The "Return Type" column should include "collection" after the type name.
The "Description" column should reflect the same description you use in the corresponding method topic. Right now the description is for getting a single instance of the resource, and so is not correct.

As for the third row, use "getDirectRoutingCalls" instead of "Get direct routing calls".
Do the similar updates for the "Return Type" and "Description" columns, as for the second row.

After correcting the beta version of callrecords-callrecord.md, add the two rows in question to the v1 version of callrecords-callrecord.md as well.

2021-07-30 21:10 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/callrecords-api-overview.md
In addition to exposing the 2 methods getPstnCalls and getDirectRoutingCalls in the Methods table for callrecords-callrecord.md, I would also suggest exposing:
- getPstnCalls in the Methods table for callrecords-pstncalllogrow.md as well.
- getDirectRoutingCalls in the Methods table for callrecords-directroutinglogrow.md as well.

Perhaps your team has reason to bind those 2 methods to the callRecord resource, and that explains why the stub topic generator only included those methods in callrecords-callrecord.md, IMO based on our TOC structure and what these methods actually return, it's helpful if we can expose each method in the resource topic corresponding to the return type.

2021-07-30 21:35 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +}
Lines 57-79:
Please add endDateTime to this JSON definition.

2021-07-30 21:36 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +}
Please also do that for the beta version of callrecords-directroutinglogrow.md.

2021-07-30 21:55 UTC, angelgolfer-ms commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
If this method supports both CallRecord-PstnCalls.Read.All and CallRecords.Read.All, please add them to only one table row and order them from least to most privileged as the column header says.
As commented in the beta topic, please add CallRecords-PstnCalls.Read.All to the permissions reference topic (https://docs.microsoft.com/en-us/graph/permissions-reference#call-records-permissions).

2021-07-30 21:57 UTC, angelgolfer-ms commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecords.Read.All |
Please add CallRecords-PstnCalls.Read.All to the permissions reference topic (https://docs.microsoft.com/en-us/graph/permissions-reference#call-records-permissions).

2021-07-30 22:20 UTC, angelgolfer-ms commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +    "@odata.count": 1000,
Lines 88-115:
Does line 90 mean this response is supposed to have 1000 entries (1000 directRoutingLogRow instances) for the specified date range?

If so, and I understand it's not a good experience for anyone to include that many entries in the response body, then I think for clarify, it's helpful to call that out in an example description.

I suggest to do something like this after line 60:
Add a description:
"The following example shows getting a collection of records for direct routing calls that occurred in the specified date range.  The response includes `"@odata.count": 1000` to enumerate the number of records in this first response, and `@odata.NextLink` to get records beyond the first 1000. For readability, the response shows only a collection of 1 record. Please assume there are more than 1000 calls in that date range."

2021-07-30 22:21 UTC, angelgolfer-ms commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +    "@odata.count": 1000,
If I understood the above correctly, then please also apply the same to the **beta** version of callrecords-callrecord-getdirectroutingcalls.md.

2021-07-30 22:24 UTC, angelgolfer-ms commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
As commented in other topics as well, please combine lines 24 and 25 into one row and order them from least to most privileged, separating them with a comma.

2021-07-30 22:25 UTC, angelgolfer-ms commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +
As commented for callrecords-callrecord-getdirectroutingcalls.md, please make some clarification by adding a description like the following:
"The following example shows getting a collection of records for PSTN calls that occurred in the specified date range. The response includes "@odata.count": 1000 to enumerate the number of records in this first response, and @odata.NextLink to get records beyond the first 1000. For readability, the response shows only a collection of 1 record. Please assume there are more than 1000 calls in that date range."

2021-07-30 22:26 UTC, angelgolfer-ms commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +
And please do the same for the **beta** version of callrecords-callrecord-getpstncalls.md.

2021-07-30 22:34 UTC, angelgolfer-ms commented on concepts/cloud-communications-callrecords.md
> +Organizations that use Microsoft Teams to connect to the public switched telephone network (PSTN) usually want to track this usage to understand the associated costs. The [getPstnCalls](/graph/api/ca
Line 27:
Please remove the extra ')' at the end of the link for "getPstnCalls".

2021-07-30 22:42 UTC, angelgolfer-ms commented on changelog/Microsoft.IC3.DataPlatform.json
>              "ChangeList": [{
I'll comment the similar that I think Isaac also did:
You're not replacing existing changlelist records in this JSON file, are you?
Unless the previous records are invalid and should never have been there, we shouldn't be replacing them. Please add new changelist records instead.
You can see more info here, if you're not using Graph Studio to generate your changelist records and instead adding them manually.

2021-07-30 22:45 UTC, angelgolfer-ms commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "ApiChange": "EnumType",
A general comment for your changelist records:
For the "ApiChange" values, please make sure you choose a value that's supported. For example, instead of "EnumType", please specify "Enum type". The list is here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

If you don't use the same terms, the future filtering feature will miss your changelog entries.

2021-07-30 22:46 UTC, angelgolfer-ms commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "ApiChange": "ComplexType",
Line 12:
Another example for ApiChange: "ComplexType" is not a supported value. Please specify "Resource" instead.
I won't call out every occurrence, please make a check and update the necessary.

2021-07-30 22:50 UTC, angelgolfer-ms commented on changelog/Microsoft.IC3.DataPlatform.json
> +            "SubArea": "Online meeting"
Line 75:
Please keep the SubArea as "Call records". Your API is displayed under the "Call records" node in the TOC.

2021-07-30 22:52 UTC, angelgolfer-ms requested changes
@SanderSade , thanks for incorporating comments by Isaac. I added a few more. Some issues actually got carried over from the beta version of the topics.
Please let me know if you have questions.

2021-07-31 06:23 UTC, SanderSade commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "ApiChange": "ComplexType",
Changed. I believe these values were set by the Graph Studio.

2021-07-31 06:25 UTC, SanderSade commented on changelog/Microsoft.IC3.DataPlatform.json
> +            "SubArea": "Online meeting"
Changed. Again. I believe this was done by Graph Studio.

2021-07-31 06:26 UTC, SanderSade commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "ApiChange": "EnumType",
Changed. I believe these values were set by the Graph Studio.

2021-07-31 06:30 UTC, opbld31 commented
Docs Build status updates of commit _[c293843](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c293843a0380b4df0d0006e31369a72058b99f12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) | [Details](#user-content-6f46fdab805cffbbb601990fd85da2bb-d915dbf6)
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-d915dbf6)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-d915dbf6)
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="6f46fdab805cffbbb601990fd85da2bb-d915dbf6"></a>
### [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md)
 - **Line 42, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="f306095039a2f930fe6fa0822f23ab80-d915dbf6"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.m [...]

2021-07-31 06:40 UTC, SanderSade commented on api-reference/v1.0/resources/callrecords-api-overview.md
Changed

2021-07-31 06:40 UTC, SanderSade commented on api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md
> +| Application                            | CallRecord-PstnCalls.Read.All |
Changed

2021-07-31 06:40 UTC, SanderSade commented on api-reference/v1.0/resources/callrecords-api-overview.md
Changed

2021-07-31 06:40 UTC, SanderSade commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +}
Done

2021-07-31 06:41 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md
> +    "@odata.count": 1000,
Added to all

2021-07-31 06:41 UTC, SanderSade commented on api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md
> +
Added to all

2021-07-31 06:41 UTC, SanderSade commented on concepts/cloud-communications-callrecords.md
> +Organizations that use Microsoft Teams to connect to the public switched telephone network (PSTN) usually want to track this usage to understand the associated costs. The [getPstnCalls](/graph/api/ca
Fixed

2021-07-31 06:42 UTC, SanderSade commented on changelog/Microsoft.IC3.DataPlatform.json
>              "ChangeList": [{
I used the Graph Studio for stubs, but reformatted the existing file due to the bad formatting before.

2021-08-03 15:51 UTC, isvargasmsft commented on api-reference/beta/resources/callrecords-directroutinglogrow.md
> +| [getDirectRoutingCalls](../api/callrecords-callrecord-getdirectroutingcalls.md) | [microsoft.graph.callRecords.directRoutingLogRow collection](callrecords-directroutinglogrow.md)| Read the properti
Please fix the to singular or plural in the description. Since this method returns a collection, please re-phrase to something like:
- List directRoutingLogRow objects for a call log.

Please make the correction in the other documents as well.

2021-08-03 15:54 UTC, isvargasmsft commented on api-reference/beta/resources/callrecords-callrecord.md
> +| [getPstnCalls](../api/callrecords-callrecord-getpstncalls.md) | [microsoft.graph.callRecords.pstnCallLogRow collection](callrecords-pstncalllogrow.md) | Read the properties of a **pstnCallLogRow**
Since this method returns a collection, it behaves more like a list operation than a get operation. In other words, please re-phrase to indicate the actual behavior. Suggestion:
* List all the pstnCallLogRow objects in a call record. 

Please make a similar change for the getDirectRoutingCalls and apply in all other documents where these methods are listed.

2021-08-03 16:32 UTC, isvargasmsft commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +| [getPstnCalls](../api/callrecords-callrecord-getpstncalls.md) | [microsoft.graph.callRecords.pstnCallLogRow collection](callrecords-pstncalllogrow.md) | Read the properties of a **pstnCallLogRow**
Please apply my previous feedback: correct to plural and rephrase to clarify the listing behavior.

2021-08-03 18:55 UTC, williamlooney commented on api-reference/beta/resources/callrecords-directroutinglogrow.md
> +|endDateTime|DateTimeOffset| Only exists for successful (fully established) calls. Time when call ended.|
We need to document the timezone. Are these UTC?

2021-08-03 18:55 UTC, williamlooney commented on api-reference/beta/resources/callrecords-directroutinglogrow.md
> +|inviteDateTime|DateTimeOffset| When the initial invite was sent.|
We need to document the timezone. Are these UTC?

2021-08-03 18:55 UTC, williamlooney commented on api-reference/beta/resources/callrecords-directroutinglogrow.md
> +|startDateTime|DateTimeOffset|Call start time.<br/>For failed and unanswered calls, this can be equal to invite or failure time.|
We need to document the timezone. Are these UTC?

2021-08-03 18:56 UTC, williamlooney commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +|endDateTime|DateTimeOffset| Only exists for successful (fully established) calls. Time when call ended.|
We need to document the timezone. Are these UTC?

2021-08-03 18:56 UTC, williamlooney commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +|failureDateTime|DateTimeOffset| Only exists for failed (not fully established) calls.|
We need to document the timezone. Are these UTC?

2021-08-03 18:56 UTC, williamlooney commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +|inviteDateTime|DateTimeOffset| When the initial invite was sent.|
We need to document the timezone. Are these UTC?

2021-08-03 18:56 UTC, williamlooney commented on api-reference/v1.0/resources/callrecords-directroutinglogrow.md
> +|startDateTime|DateTimeOffset|Call start time.<br/>For failed and unanswered calls, this can be equal to invite or failure time.|
We need to document the timezone. Are these UTC?

2021-08-03 20:43 UTC, isvargasmsft requested changes
Just a couple of additional changes. 

Thank you very much Sander!

2021-08-23 20:53 UTC, opbld34 commented
Docs Build status updates of commit _[85b5612](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85b5612bfe48d9d2fdd315c3a393d1d61bdb345f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) | [Details](#user-content-6f46fdab805cffbbb601990fd85da2bb-5d0e034d)
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-5d0e034d)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-5d0e034d)
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="6f46fdab805cffbbb601990fd85da2bb-5d0e034d"></a>
### [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md)
 - **Line 42, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="f306095039a2f930fe6fa0822f23ab80-5d0e034d"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.m [...]

2021-08-30 13:54 UTC, opbld34 commented
Docs Build status updates of commit _[8a78dd3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a78dd3593cd5e5fd6be7ed0a2e43d3e823ef9aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) | [Details](#user-content-6f46fdab805cffbbb601990fd85da2bb-678f642d)
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-678f642d)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-678f642d)
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="6f46fdab805cffbbb601990fd85da2bb-678f642d"></a>
### [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md)
 - **Line 42, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="f306095039a2f930fe6fa0822f23ab80-678f642d"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.m [...]

2021-08-30 14:11 UTC, opbld31 commented
Docs Build status updates of commit _[711d8e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/711d8e63dc9a65476540b3fbe8eda6312a7c9ed7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) | [Details](#user-content-6f46fdab805cffbbb601990fd85da2bb-79ef9b4e)
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) | [Details](#user-content-f306095039a2f930fe6fa0822f23ab80-79ef9b4e)
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) | [Details](#user-content-36c51a473313ada6c6e27513f12760d7-79ef9b4e)
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

<a id="6f46fdab805cffbbb601990fd85da2bb-79ef9b4e"></a>
### [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md)
 - **Line 42, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="f306095039a2f930fe6fa0822f23ab80-79ef9b4e"></a>
### [api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md)
 - **Line 40, Column 3**: **[Suggestion-[preserve-view-not-set](https://review.docs.m [...]

2021-08-30 14:19 UTC, opbld32 commented
Docs Build status updates of commit _[6135a85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6135a855f06e6c8ef8faa1c6851c0ee00fe66c64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108301417089265-13376%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=JziIcEkrFWiO%2BWZ336OJVlrLSqLrci2r%2BfjCDrpA6hU%3D&st=2021-08-30T14%3A14%3A33Z&se=2021-09-30T14%3A19%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 14:29 UTC, opbld30 commented
Docs Build status updates of commit _[6eacae8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6eacae867c17c6e376c719b27abd2c4e3c5240a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108301426434097-13376%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=NC%2F8Fz770n4Z5eImtiER26v7BBhLTohcVnjqWFtSFkU%3D&st=2021-08-30T14%3A24%3A29Z&se=2021-09-30T14%3A29%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 16:07 UTC, isvargasmsft commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Added the [getDirectRoutingCalls](https://docs.microsoft.com/en-us/graph/api/getDirectRoutingCalls?view=graph-rest-1.0) method to the [getDirectRoutingCalls](https
I think the target is actually callrecord resource type, right? If such, please update the Description and the Target.

2021-08-30 16:08 UTC, isvargasmsft commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Added the [getPstnCalls](https://docs.microsoft.com/en-us/graph/api/getPstnCalls?view=graph-rest-1.0) method to the [getPstnCalls](https://docs.microsoft.com/en-us
Similar observation here: this method belongs to the call record resource type, right?

2021-08-30 16:09 UTC, isvargasmsft requested changes
Please clarify the targets in a couple of changelog entries. 

Kind regards!

2021-08-30 19:46 UTC, angelgolfer-ms commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Added the [getDirectRoutingCalls](https://docs.microsoft.com/en-us/graph/api/getDirectRoutingCalls?view=graph-rest-1.0) method to the [getDirectRoutingCalls](https
@SanderSade , for the changelog JSON for getDirectRoutingCalls and getPstnCalls, please take a look at Example 6 in the [changelog](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog) topic.

There are 2 issues:

- The second part of the Description property is not correct in lines 29 and 36. You're adding the methods to the corresponding parent resource, not to the methods themselves.
- Also, the Target property should be the parent resource, not the method (lines 30 and 37).

After you make these changes, please ping me on Teams and I can approve this PR. Thanks. (I'll be out for a few hours between now and then.)

2021-08-30 19:48 UTC, angelgolfer-ms commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Added the [getDirectRoutingCalls](https://docs.microsoft.com/en-us/graph/api/getDirectRoutingCalls?view=graph-rest-1.0) method to the [getDirectRoutingCalls](https
BTW, @SanderSade , I'm curious - was this JSON generated or did you put it together manually?
If it's generated, then we need to track bugs for the generator.
Please confirm.

2021-08-31 02:15 UTC, opbld33 commented
Docs Build status updates of commit _[79d5356](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79d535601b1c604b6e875d94ce97e1efef33cef6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310213399457-13376%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=lhr9AId2BijpZkKM7p3SuDV87aqjw899AjssIMPqzKU%3D&st=2021-08-31T02%3A10%3A25Z&se=2021-10-01T02%3A15%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 02:24 UTC, opbld34 commented
Docs Build status updates of commit _[0cadfad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0cadfad9be0e6249b434d6f084432cfcb8d3b1a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310221501046-13376%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=kTe5okPCCJqcQbpqCSFCZ7Q%2FeX19I53Zn28dQc2ueWw%3D&st=2021-08-31T02%3A19%3A09Z&se=2021-10-01T02%3A24%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 02:37 UTC, opbld30 commented
Docs Build status updates of commit _[3029b4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3029b4c4fe6bf9cf75a035a0813dd29244d3a8a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310234291820-13376%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=hk%2BFlS9HaId3G%2F3pBPK51LY1sFYOTIPwWSlBwCH%2F270%3D&st=2021-08-31T02%3A31%3A59Z&se=2021-10-01T02%3A36%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 02:39 UTC, opbld31 commented
Docs Build status updates of commit _[ecedbc4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecedbc45d3259e04cc9ff348b016e5b004028699)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-13376) (graph-rest-beta) |
[api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-callrecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-directroutinglogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-directroutinglogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-directroutinglogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&branch=pr-en-us-13376) (>= graph-rest-1.0) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |
[concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/cloud-communications-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/cloud-communications-callrecords?branch=pr-en-us-13376) |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/SanderSade/PSTN-reports-to-GA/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-13376) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108310237443488-13376%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=g0j5YZLHtznEMzrr3esHjuN36WRbADhoyEltH1q7ILQ%3D&st=2021-08-31T02%3A34%3A12Z&se=2021-10-01T02%3A39%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 02:40 UTC, isvargasmsft approved these changes

2021-08-31 03:00 UTC, angelgolfer-ms approved these changes
Hi @SanderSade , we decided to incorporate the few remaining issues in the changelog JSON and publish this PR this evening.
Please take a look at comments from @isvargasmsft and myself from the last day and let us know if you have questions about the changelog JSON.
Also, please confirm if the JSON your provided that has those issues was originally generated by the stub generator, by Graph Studio, or manually put together by you. If it was generated, then we need to track those bugs. Thanks in advance!

2021-08-31 03:01 UTC, merged