added description for Id parameter
microsoftgraph/microsoft-graph-docs pull request #13397
Opened 2021-07-07 05:56 UTC by Swathi-Birlangi

2021-07-07 05:58 UTC, opbld30 commented
Docs Build status updates of commit _[cbb0446](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/cbb044634987ec433c55ad2c7ce36fe55b77f70f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107070556443699-13397%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A21%3A19Z&ske=2021-07-13T09%3A26%3A19Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T05%3A53%3A12Z&se=2021-08-07T05%3A58%3A12Z&sr=b&sp=r&sig=68%2B1AQyZ%2F5T68f68dghgUO2byepRBvYGAua%2F4BuXXHc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 04:59 UTC, opbld34 commented
Docs Build status updates of commit _[5b405a3](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/5b405a3c623310a6ae74dd9c17c51e4160f835bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107160458019817-13397%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A27%3A53Z&ske=2021-07-20T08%3A32%3A53Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T04%3A54%3A45Z&se=2021-08-16T04%3A59%3A45Z&sr=b&sp=r&sig=yEjwVxRePTWeP8faqWlkvRYhnTksKGCJhbl%2BHc4vF2A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 16:53 UTC, opbld32 commented
Docs Build status updates of commit _[0ed817e](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/0ed817e5269d7da0a435a9d7cc28ab737e1f8ff7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) | [Details](#user-content-4b4f8404993636b43c06287309896c96-d57078db)
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-d57078db)
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="4b4f8404993636b43c06287309896c96-d57078db"></a>
### [api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md)
 - **Line 48, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 75, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

<a id="edf733fe343d0503b3147c20963e377f-d57078db"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 45, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 74, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109131651427796-13397%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ithDs7U9JXis%2Bqk%2FBNX7brjWvd%2Ff2lglkDWg5FumvtY%3D&st=2021-09-13T16%3A48%3A27Z&se=2021-10-14T16%3A53%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 17:06 UTC, opbld32 commented
Docs Build status updates of commit _[380f94c](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/380f94ceb78c4dfc86f33e65f1e29b219e443b9c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b6b1b765)
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :warning:Warning | | [Details](#user-content-4b4f8404993636b43c06287309896c96-b6b1b765)
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | | [Details](#user-content-edf733fe343d0503b3147c20963e377f-b6b1b765)

<a id="b6b1b765"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

<a id="4b4f8404993636b43c06287309896c96-b6b1b765"></a>
### [api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md)
 - **Line 48, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 76, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

<a id="edf733fe343d0503b3147c20963e377f-b6b1b765"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 45, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 75, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109131702513543-13397%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=POi%2ByvyIoryFym4i772xLnhA7KCbY2mRrtpL%2F3MIp2c%3D&st=2021-09-13T17%3A01%3A51Z&se=2021-10-14T17%3A06%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-13 17:13 UTC, opbld31 commented
Docs Build status updates of commit _[53fd4ec](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/53fd4ec3c7742a31a31dc6423ff4b79f7c7dd66a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) | [Details](#user-content-4b4f8404993636b43c06287309896c96-78ad9b6e)
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-78ad9b6e)
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="4b4f8404993636b43c06287309896c96-78ad9b6e"></a>
### [api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md)
 - **Line 48, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 75, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

<a id="edf733fe343d0503b3147c20963e377f-78ad9b6e"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 45, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 74, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109131712089646-13397%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XlcowUMUgJmbsUwxoRYMKbSOnoEl%2B%2F5FPdDFWbFD12c%3D&st=2021-09-13T17%3A08%3A43Z&se=2021-10-14T17%3A13%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 11:55 UTC, opbld31 commented
Docs Build status updates of commit _[43d1273](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/43d127341cd1fd271e826238dad8e525829c956e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) | [Details](#user-content-4b4f8404993636b43c06287309896c96-eb58c7c2)
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-eb58c7c2)
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="4b4f8404993636b43c06287309896c96-eb58c7c2"></a>
### [api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md)
 - **Line 48, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 75, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

<a id="edf733fe343d0503b3147c20963e377f-eb58c7c2"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 45, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 74, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109141153290787-13397%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=mbdh%2FzIsiVFXa0bGafiEfsFC473%2B3SZPwzJ2O%2FJaXAA%3D&st=2021-09-14T11%3A50%3A17Z&se=2021-10-15T11%3A55%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 12:56 UTC, opbld30 commented
Docs Build status updates of commit _[dd28742](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/dd287428e41e63f5ebef3a2188335147e513adbe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) | [Details](#user-content-4b4f8404993636b43c06287309896c96-ecd11c66)
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-ecd11c66)
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="4b4f8404993636b43c06287309896c96-ecd11c66"></a>
### [api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md)
 - **Line 48, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 75, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

<a id="edf733fe343d0503b3147c20963e377f-ecd11c66"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 45, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 74, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109141254136439-13397%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6sULdEKD4O0o2Io134ipnwUFhYplG86zvVAvAIkgUV4%3D&st=2021-09-14T12%3A51%3A00Z&se=2021-10-15T12%3A56%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 11:31 UTC, opbld33 commented
Docs Build status updates of commit _[3bd2fff](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/3bd2fffa922dfaba8621fb905faf0de2574f0899)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) | [Details](#user-content-4b4f8404993636b43c06287309896c96-0235e40d)
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-0235e40d)
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="4b4f8404993636b43c06287309896c96-0235e40d"></a>
### [api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md)
 - **Line 48, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 253, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

<a id="edf733fe343d0503b3147c20963e377f-0235e40d"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 45, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 129, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151129090886-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T11%3A31%3A29Z&sr=b&sp=r&sig=JzVJ1vQxW2pwNtUqhdm5zrJojSWjL37bb1OJTWnnz2Q%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 12:21 UTC, opbld32 commented
Docs Build status updates of commit _[0005103](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/000510311bb6d929568826171ee07d6d4bda8689)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) | [Details](#user-content-4b4f8404993636b43c06287309896c96-f62bad3c)
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-f62bad3c)
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="4b4f8404993636b43c06287309896c96-f62bad3c"></a>
### [api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md)
 - **Line 48, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 253, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

<a id="edf733fe343d0503b3147c20963e377f-f62bad3c"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````
 - **Line 45, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````
 - **Line 129, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 'Optional query parameters''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109151217330821-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-16T12%3A21%3A52Z&sr=b&sp=r&sig=l8KiMRrEvNs74GsmpNtNT2j7Bbq78LxZ1h0%2FOWRjCgM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 07:45 UTC, opbld30 commented
Docs Build status updates of commit _[26e0355](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/26e035525d2967dea6be1d8f9895cf9c85c6741e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-d7e35029)
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="edf733fe343d0503b3147c20963e377f-d7e35029"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160743377558-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T07%3A45%3A35Z&sr=b&sp=r&sig=jVYNM%2FqrP86qFQ78Ed2x%2FJhy5pjrASTAVe2ILyzHRoI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-16 08:24 UTC, opbld34 commented
Docs Build status updates of commit _[c351793](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/c3517932300df3c70a9af775435834e3a96eaff6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-43f0c1c0)
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="edf733fe343d0503b3147c20963e377f-43f0c1c0"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109160822562988-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-17T08%3A24%3A52Z&sr=b&sp=r&sig=DlBT6feJmAsvtiaFHvukKC9P%2BYytODpAhxMcFR7beUc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 01:30 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-events.md
> +This method supports some of the OData query parameters to help customize the response. For example, to filter the access packages with subject, include a filter such as `$filter=startsWith(subject,'
Line 161: Delete this paragraph please.

2021-09-24 01:34 UTC, angelgolfer-ms commented on api-reference/beta/api/calendar-list-events.md
> +### Example 2: Filter with subject and emails from a specific address
Line 163: 
Retitle this to say "Example 2: Get events by filtering on the subject property"

Line 165: Delete this line!

Add the sentence "This example gets events in the user's primary calendar by filtering on their subject starting with "All".

Line 167 and 178: Change them to level 4 heading, not level 5.

2021-09-24 01:35 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-list-events.md
> +### Example 2: Filter with subject and emails from a specific address
Example 2: please apply the comments I gave for the beta topic.

2021-09-24 02:12 UTC, angelgolfer-ms requested changes
As I mentioned in our Teams chat (9/23 PST), I suggest the following for this PR:
- Keep this PR 13397 addressing Github issue 12400.
- For Github issue 9685, I don't think adding an example is what the customer is looking for. On the other hand, just to enrich the topic, we can add an example that shows this query URL:

GET https://graph.microsoft.com/beta/me/calendar/events?$filter=startsWith(subject,'All')

Swathi can please incorporate the comments I added to the beta calendar-list-events.md topic. Do the similar to the v1 topic.

Do a separate docs PR to address Github issue 9685, as I suggested in our Teams chat.

2021-09-24 12:42 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-events.md
> +This method supports some of the OData query parameters to help customize the response. For example, to filter the access packages with subject, include a filter such as `$filter=startsWith(subject,'
Deleted this content in beta and v1.0

2021-09-24 12:45 UTC, Swathi-Birlangi commented on api-reference/beta/api/calendar-list-events.md
> +### Example 2: Filter with subject and emails from a specific address
Line 163:  Renamed in both beta and v1.0

Line 165: deleted in both beta and v1.0

Added the sentence in both beta and v1.0

Line 167 and 178: changed the heading to level 4 in both beta and v1.0

2021-09-24 12:45 UTC, Swathi-Birlangi commented on api-reference/v1.0/api/calendar-list-events.md
> +### Example 2: Filter with subject and emails from a specific address
Applied in beta and v1.0

2021-09-24 12:52 UTC, opbld30 commented
Docs Build status updates of commit _[df4c771](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/df4c77165103d2f9c11d0bcd48c806a6390923b7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3035e828)

<a id="3035e828"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241251452557-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T12%3A52%3A12Z&sr=b&sp=r&sig=wWQAghYgzFJFvzYFlEgYl9OOjhUmxfxbcUWKQKwuKgk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 12:57 UTC, opbld32 commented
Docs Build status updates of commit _[c1b6452](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/c1b64521da9310f4e43a9f4c3e9cdc9848767900)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c9a801b8)

<a id="c9a801b8"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241256449945-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T12%3A57%3A33Z&sr=b&sp=r&sig=j5CslEfch%2FiwuJx0Ic4zDwwCRLNXL%2BhToQOYHs8MQ8U%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 13:09 UTC, opbld34 commented
Docs Build status updates of commit _[b068ae6](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/b068ae60a6c4ff252ba540ee22e16f90616c71a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-292f8259)

<a id="292f8259"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241309257174-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T13%3A09%3A51Z&sr=b&sp=r&sig=WhvBByo%2Fz1GH6PIRHspqh%2FWgTcMLnpV1yHUMbhiCTGA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 13:14 UTC, opbld32 commented
Docs Build status updates of commit _[54c53c6](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/54c53c614592b2a30d19ae849984699f2e346ede)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-20bd0958)

<a id="20bd0958"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241314143192-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T13%3A14%3A36Z&sr=b&sp=r&sig=AYTzOqS4Xbodg38E7ck3v0tvwGyJiOC8L4bgdUOwp%2BE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 13:26 UTC, opbld31 commented
Docs Build status updates of commit _[6c5b3d3](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/6c5b3d3c583bac697e40f71ae77126392382fe71)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2f0c5530)

<a id="2f0c5530"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109241326041806-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T13%3A26%3A27Z&sr=b&sp=r&sig=OggnwLEPXm1RwM4%2Bk6lInbbnD2gfJKuuaKXt1%2BvQdg4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 22:32 UTC, opbld31 commented
Docs Build status updates of commit _[357387c](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/357387c4959d3cbb16ff6fa8203f8942aa8d3298)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-4895bc0f)
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="edf733fe343d0503b3147c20963e377f-4895bc0f"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109242230266957-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T22%3A32%3A38Z&sr=b&sp=r&sig=iaOT46z3NSs9UjfM3pud%2B5PcQCTF49nlNbPo%2FJohym8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 22:47 UTC, opbld34 commented
Docs Build status updates of commit _[8233031](https://github.com/Swathi-Birlangi/microsoft-graph-docs/commits/8233031eede9be7126e8e0285c8686559aabdb16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) | [Details](#user-content-edf733fe343d0503b3147c20963e377f-87e8852c)
[api-reference/beta/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/api/calendar-list-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/beta/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/beta/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta&branch=pr-en-us-13397) (graph-rest-beta) |
[api-reference/v1.0/resources/event.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-13397) (>= graph-rest-1.0) |

<a id="edf733fe343d0503b3147c20963e377f-87e8852c"></a>
### [api-reference/v1.0/api/calendar-list-events.md](https://github.com/Swathi-Birlangi/microsoft-graph-docs/blob/origin/v-sbirlangi/v1.0/update-event-id-and-filter-examples/api-reference/v1.0/api/calendar-list-events.md)
 - **Line 2, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List events - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-list-events.md(2,8), v1.0/api/group-list-events.md(2,8), v1.0/api/user-list-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List events' is duplicated with other articles: 'v1.0/api/calendar-list-events.md(10,1), v1.0/api/group-list-events.md(10,1), v1.0/api/user-list-events.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109242245405850-13397%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T22%3A47%3A31Z&sr=b&sp=r&sig=VcfbhKDUNs1ZX5Q4RZrKZXcMsLvT7%2B%2FUbCuStLSxeS8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 23:04 UTC, merged