Add access review error
microsoftgraph/microsoft-graph-docs pull request #13413
Opened 2021-07-07 23:52 UTC by jingyang1114

2021-07-07 23:54 UTC, opbld32 commented
Docs Build status updates of commit _[8dd780b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8dd780b918c226f33b775eb7598c89daf9928a2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewerror?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107072352583237-13413%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-07T04%3A16%3A11Z&ske=2021-07-14T04%3A21%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T23%3A49%3A27Z&se=2021-08-07T23%3A54%3A27Z&sr=b&sp=r&sig=HCOpwiwGjqRIb5j0wXRPX9gptPSGQ6p3HkpdUNPo764%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 08:26 UTC, FaithOmbongi requested changes
Minor changes:
- Let's link to the **genericError** resource from the property descriptions.
- Add a changelog entry for the **accessReviewErrors** resource.

2021-07-09 08:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewerror.md
> +description: "Represents error happened within access review instance lifecycle."
```suggestion
description: "Represents an error that occurred within an access review instance lifecycle."
```

2021-07-09 08:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewerror.md
> +| message |String | Inherit from microsoft.graph.genericError. Error details.|
Let's link to the **genericError** resource.
```suggestion
| code  |String  | Represents the error type. Inherited from genericError. Read-only. |
| message |String | Represents the error details. Inherited from genericError. Read-only.|
```

2021-07-09 08:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewerror.md
> +Represent errors happen in review instance lifecycle. **code** represent error type. **message** contain error details. This resource is read-only.
```suggestion
Represents an error that occurred in an access review instance lifecycle. This resource is read-only.
```

2021-07-09 08:26 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewinstance.md
> +| errors | [accessReviewError](accessreviewerror.md) collection| Collection of errors in access review instance lifecycle Read-only. |
```suggestion
| errors | [accessReviewError](accessreviewerror.md) collection| Collection of errors in an access review instance lifecycle. Read-only. |
```

2021-07-09 08:26 UTC, FaithOmbongi commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +                    "Target": "accessReviewInstance"
Also add an entry for the accessReviewError resource.
```suggestion
                    "Id": "4D251ED7-CD9A-431E-8FB5-BA2DD49E3B35",
                    "ApiChange": "Property",
                    "ChangedApiName": "errors",
                    "ChangeType": "Addition",
                    "Description": "Added the **errors** property to the [accessReviewInstance](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta) resource.",
                    "Target": "accessReviewInstance"
```

2021-07-16 17:22 UTC, opbld30 commented
Docs Build status updates of commit _[f1b2b57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1b2b57e9e2e84cfac83369afbf255f6c2bdc34e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewerror?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161720430233-13413%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A39%3A49Z&ske=2021-07-23T08%3A44%3A49Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A17%3A16Z&se=2021-08-16T17%3A22%3A16Z&sr=b&sp=r&sig=1wfW8H8olXOPlVJC3%2BHCL3sb7v9M4DO5WdkxeTXirvw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 17:31 UTC, opbld33 commented
Docs Build status updates of commit _[84282b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84282b50d1462a989c0671d3b1a815839839b890)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewerror?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161730248932-13413%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A09%3A48Z&ske=2021-07-23T08%3A14%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T17%3A26%3A51Z&se=2021-08-16T17%3A31%3A51Z&sr=b&sp=r&sig=Xww3pIdNqhuh7SXuNtBzf%2FDZeCMi2UTKf5KLEyM0kkg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 17:34 UTC, isabelleatmsft approved these changes
Approving - but please address Faith's open comments! Thanks Jing for getting the docs done. Also Jing, let's establish a plan for getting this change in to v1.0 as well as beta.

2021-07-17 01:19 UTC, Lauragra commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +                {
You also need to state in the changelog that you added the accessReviewError resource type.

2021-07-17 01:21 UTC, Lauragra commented on api-reference/beta/resources/accessreviewerror.md
> +[!INCLUDE [accessreviews-disclaimer-v2](../../includes/accessreviews-disclaimer-v2.md)]
The disclaimer text includes the phrase "in this section", which does not make sense in the context of this topic because it is not part of a section in the TOC. Can you revise the disclaimer text in the include file to be more clear instead of relying on a location to convey which API is not deprecated? Maybe the text should just say "This API". I would change "older" version to "previous" version, and state that it is deprecated, not "will be" deprecated since we've already marked it as deprecated.

2021-07-19 20:24 UTC, jingyang1114 commented on api-reference/beta/resources/accessreviewerror.md
> +[!INCLUDE [accessreviews-disclaimer-v2](../../includes/accessreviews-disclaimer-v2.md)]
@isabelleatmsft  Hi Isabelle, can't fine the file accessreviews-disclaimer-v2.md - was it deprecated ? could you suggest what the change should be here?

2021-07-19 20:30 UTC, jingyang1114 commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +                {
thank you! added

2021-07-19 20:32 UTC, opbld34 commented
Docs Build status updates of commit _[be2e24e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be2e24e59772a371573caa87a330934a57aab01f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewerror?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107192030315663-13413%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A50%3A12Z&ske=2021-07-26T02%3A55%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T20%3A27%3A25Z&se=2021-08-19T20%3A32%3A25Z&sr=b&sp=r&sig=joQRmH8bMQ4P%2FO8RoHv%2BSf8hV%2FtRcZmHcL2PTlg6qfE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 20:57 UTC, isabelleatmsft approved these changes

2021-07-19 20:57 UTC, isabelleatmsft commented on api-reference/beta/resources/accessreviewerror.md
> +[!INCLUDE [accessreviews-disclaimer-v2](../../includes/accessreviews-disclaimer-v2.md)]
@Lauragra i made a PR for those changes: https://github.com/microsoftgraph/microsoft-graph-docs/pull/13569

2021-07-20 00:27 UTC, opbld31 commented
Docs Build status updates of commit _[7895076](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78950764c07de9c1bbcc1f708eb5acc1993746c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewerror?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewinstance.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/api-reference/beta/resources/accessreviewinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewinstance?view=graph-rest-beta&branch=pr-en-us-13413) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessreviewerrors/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107200025482318-13413%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A32%3A49Z&ske=2021-07-26T02%3A37%3A49Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T00%3A22%3A29Z&se=2021-08-20T00%3A27%3A29Z&sr=b&sp=r&sig=6%2FhCc64n1O3p3%2BPHwyynZgR1b2uD9HeteBLsUKNN%2FxM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 00:39 UTC, merged