Application auth method policies
microsoftgraph/microsoft-graph-docs pull request #13418
Opened 2021-07-08 09:20 UTC by madansr7

2021-07-08 09:22 UTC, opbld30 commented
Docs Build status updates of commit _[e964286](https://github.com/madansr7/microsoft-graph-docs/commits/e964286aca4ccab0bfa94296c18c943ebf53cf9e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-e4726b74a650ff21f98cb5c4ea4e7a64-347c21fb)
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-8fb157b90573a7835c79859b30d73ae7-347c21fb)
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-46bc2e6379cf59ea0209078c65882c8d-347c21fb)
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-bf62a84306835bb2b1a7aa56466ff1b4-347c21fb)
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-347c21fb)
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-31c88e41b069137a697d399e6c0ab8ca-347c21fb)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-347c21fb)
[api-reference/beta/api/defaultAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-95ad14a7498de858a8c5c556c6a22df6-347c21fb)
[api-reference/beta/api/defaultAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ff1e96c560f31997708dbef6f733141-347c21fb)
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-9c08d1fda2f84e89ed2c8bb9b818ed6a-347c21fb)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-347c21fb)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-347c21fb)
[api-reference/beta/resources/defaultAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/defaultAppManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-29f04838ccb263c382da55f76c0d6c17-347c21fb)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-347c21fb)
[api-reference/beta/resources/registrationenforcement.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/registrationenforcement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/registrationenforcement?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-fa1441f43d3aa26cc57ce610921684c0-347c21fb)
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |

<a id="e4726b74a650ff21f98cb5c4ea4e7a64-347c21fb"></a>
### [api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md)
 - **Line 5, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'saumadan' is not a valid GitHub ID.`````
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get defaultAppManagementPolicy' is duplicated with other articles: 'beta/api/appManagementPolicy-delete.md(10,1), beta/api/appManagementPolicy-get.md(10,1), beta/api/appManagementPolic [...]

2021-07-09 00:06 UTC, opbld31 commented
Docs Build status updates of commit _[b1a9a48](https://github.com/madansr7/microsoft-graph-docs/commits/b1a9a48b40957b54725055b673eca4fed10aedcc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-e4726b74a650ff21f98cb5c4ea4e7a64-6fb4fd83)
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-8fb157b90573a7835c79859b30d73ae7-6fb4fd83)
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-46bc2e6379cf59ea0209078c65882c8d-6fb4fd83)
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-bf62a84306835bb2b1a7aa56466ff1b4-6fb4fd83)
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-6fb4fd83)
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-31c88e41b069137a697d399e6c0ab8ca-6fb4fd83)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-6fb4fd83)
[api-reference/beta/api/defaultAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-95ad14a7498de858a8c5c556c6a22df6-6fb4fd83)
[api-reference/beta/api/defaultAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ff1e96c560f31997708dbef6f733141-6fb4fd83)
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-9c08d1fda2f84e89ed2c8bb9b818ed6a-6fb4fd83)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-6fb4fd83)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-6fb4fd83)
[api-reference/beta/resources/defaultAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/defaultAppManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-29f04838ccb263c382da55f76c0d6c17-6fb4fd83)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-6fb4fd83)
[api-reference/beta/resources/registrationenforcement.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/registrationenforcement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/registrationenforcement?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-fa1441f43d3aa26cc57ce610921684c0-6fb4fd83)
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |

<a id="e4726b74a650ff21f98cb5c4ea4e7a64-6fb4fd83"></a>
### [api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md)
 - **Line 5, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: 'saumadan' is not a valid GitHub ID.`````
 - **Line 10, Column 1**: [...]

2021-07-09 18:45 UTC, opbld30 commented
Docs Build status updates of commit _[1caef61](https://github.com/madansr7/microsoft-graph-docs/commits/1caef619ad9198cb1b44f1d11ad5ecd2cf4ec328)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ae2ac244)

<a id="ae2ac244"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091845300213-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A19%3A18Z&ske=2021-07-13T08%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A40%3A49Z&se=2021-08-09T18%3A45%3A49Z&sr=b&sp=r&sig=4rd7ceQcbfJ1N%2FXRpHnI9fqEsvF7uf2ISk3taLvcMZY%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 19:17 UTC, opbld32 commented
Docs Build status updates of commit _[bf543d0](https://github.com/madansr7/microsoft-graph-docs/commits/bf543d0a0b47fc709846732058a645fde31ced89)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f24760d1)

<a id="f24760d1"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091916593367-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A01%3A02Z&ske=2021-07-13T07%3A06%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T19%3A12%3A19Z&se=2021-08-09T19%3A17%3A19Z&sr=b&sp=r&sig=zdnAXKvyZJyy3Sd1cEkg%2B4BM5trO1XLUQfySaRVu3qQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 19:55 UTC, opbld33 commented
Docs Build status updates of commit _[2d375a1](https://github.com/madansr7/microsoft-graph-docs/commits/2d375a10bdec4dbaf219e0a7664b9420577f01b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-e4726b74a650ff21f98cb5c4ea4e7a64-c49a42e6)
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-8fb157b90573a7835c79859b30d73ae7-c49a42e6)
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-46bc2e6379cf59ea0209078c65882c8d-c49a42e6)
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-bf62a84306835bb2b1a7aa56466ff1b4-c49a42e6)
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-c49a42e6)
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-31c88e41b069137a697d399e6c0ab8ca-c49a42e6)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-c49a42e6)
[api-reference/beta/api/defaultAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-95ad14a7498de858a8c5c556c6a22df6-c49a42e6)
[api-reference/beta/api/defaultAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ff1e96c560f31997708dbef6f733141-c49a42e6)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-c49a42e6)
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-9c08d1fda2f84e89ed2c8bb9b818ed6a-c49a42e6)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-c49a42e6)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-c49a42e6)
[api-reference/beta/resources/defaultAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/defaultAppManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-29f04838ccb263c382da55f76c0d6c17-c49a42e6)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-c49a42e6)
[api-reference/v1.0/resources/user.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/v1.0/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-13418) (>= graph-rest-1.0) | [Details](#user-content-b6c979e090f802360b5fb2b0e8db6f73-c49a42e6)
[api-reference/beta/resources/registrationenforcement.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/registrationenforcement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/registrationenforcement?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-fa1441f43d3aa26cc57ce610921684c0-c49a42e6)
[api-reference/beta/api/application-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/application-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&branch=pr-en [...]

2021-07-19 17:51 UTC, opbld33 commented
Docs Build status updates of commit _[1943e2d](https://github.com/madansr7/microsoft-graph-docs/commits/1943e2d70957c409e38751ad124258fcfe8c42f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-e4726b74a650ff21f98cb5c4ea4e7a64-f8b0699b)
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-8fb157b90573a7835c79859b30d73ae7-f8b0699b)
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-46bc2e6379cf59ea0209078c65882c8d-f8b0699b)
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-bf62a84306835bb2b1a7aa56466ff1b4-f8b0699b)
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-f8b0699b)
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-31c88e41b069137a697d399e6c0ab8ca-f8b0699b)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-f8b0699b)
[api-reference/beta/api/defaultAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-95ad14a7498de858a8c5c556c6a22df6-f8b0699b)
[api-reference/beta/api/defaultAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ff1e96c560f31997708dbef6f733141-f8b0699b)
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-9c08d1fda2f84e89ed2c8bb9b818ed6a-f8b0699b)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-f8b0699b)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-f8b0699b)
[api-reference/beta/resources/defaultAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/defaultAppManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-29f04838ccb263c382da55f76c0d6c17-f8b0699b)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-f8b0699b)
[api-reference/beta/resources/registrationenforcement.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/registrationenforcement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/registrationenforcement?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-fa1441f43d3aa26cc57ce610921684c0-f8b0699b)
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="e4726b74a650ff21f98cb5c4ea4e7a64-f8b0699b"></a>
### [api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md)
 - **Line 5, Column 9**: **[Warning-[author-not-f [...]

2021-07-19 19:13 UTC, opbld31 commented
Docs Build status updates of commit _[f51a19c](https://github.com/madansr7/microsoft-graph-docs/commits/f51a19c4a43500324d786c2d7e76cdd12b2a21ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-e4726b74a650ff21f98cb5c4ea4e7a64-51f12d7c)
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-8fb157b90573a7835c79859b30d73ae7-51f12d7c)
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-46bc2e6379cf59ea0209078c65882c8d-51f12d7c)
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-bf62a84306835bb2b1a7aa56466ff1b4-51f12d7c)
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-51f12d7c)
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-31c88e41b069137a697d399e6c0ab8ca-51f12d7c)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-51f12d7c)
[api-reference/beta/api/defaultAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-95ad14a7498de858a8c5c556c6a22df6-51f12d7c)
[api-reference/beta/api/defaultAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ff1e96c560f31997708dbef6f733141-51f12d7c)
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-9c08d1fda2f84e89ed2c8bb9b818ed6a-51f12d7c)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-51f12d7c)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-51f12d7c)
[api-reference/beta/resources/defaultAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/defaultAppManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-29f04838ccb263c382da55f76c0d6c17-51f12d7c)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-51f12d7c)
[api-reference/beta/resources/registrationenforcement.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/registrationenforcement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/registrationenforcement?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-fa1441f43d3aa26cc57ce610921684c0-51f12d7c)
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="e4726b74a650ff21f98cb5c4ea4e7a64-51f12d7c"></a>
### [api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md)
 - **Line 5, Column 9**: **[Warning-[author-not-f [...]

2021-07-19 20:11 UTC, FaithOmbongi requested changes
- Metadata author value is your GitHub alias, not MSFT alias. Kindly see the [Metadata guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103166/Metadata).
- Global: The metadata & H1 titles seem off—especially for resource pages. Could you check and use the titles generated by the stub generator tool?
- Global: Check that the opening `# [HTTP](#tab/http)` and closing `---` code snippet tags are not added for new articles. These are auto-included by the snippet generator. See [guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners?pagePath=%2FAPI%2FDocument%2FGuidelines%2FGenerate%20code%20snippets).
- Global: the request name as defined in the HTML comment blocks should be unique for the entire doc set and reflect the method or resource. For example, create_appManagementPolicies is more likely to be found in an appManagementPolicy-post method file than a appManagement-delete method file.
- Seems there should be relationships in application & servicePrincipal resources?

Kindly verify against the output generated by the stub generator tool.

2021-07-19 20:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added navigation properties 'defaultAppManagementPolicy' and 'appManagementPolicies' to policies singleton.",
- Add the public link to policies resources.
- Is it to policies or to policyRoot? Kindly confirm

```suggestion
          "Description": "Added the **defaultAppManagementPolicy** and **appManagementPolicies** navigation properties to the [policies](add public link) singleton.",
```

2021-07-19 20:11 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "Cloud": "prd",
Kindly ensure that all your changes are in a single ChangeList. All your entries will have the same GUID value for Id.

2021-07-19 20:11 UTC, FaithOmbongi commented on api-reference/beta/api/appManagementPolicy-post-applyToResource.md
> +
`200 OK` or `204 No content`? Just confirm.
```suggestion
```http
HTTP/1.1 204 OK

```

2021-07-19 20:49 UTC, opbld30 commented
Docs Build status updates of commit _[0e2d501](https://github.com/madansr7/microsoft-graph-docs/commits/0e2d501e28a25b7f87708a0572e511bfa80fb581)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-9c08d1fda2f84e89ed2c8bb9b818ed6a-034bdd81)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-034bdd81)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-034bdd81)
[api-reference/beta/resources/registrationenforcement.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/registrationenforcement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/registrationenforcement?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-fa1441f43d3aa26cc57ce610921684c0-034bdd81)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/defaultAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/defaultAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/defaultAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/defaultAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="9c08d1fda2f84e89ed2c8bb9b818ed6a-034bdd81"></a>
### [api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'registrationEnforcement resource type' is duplicated with other articles: 'beta/resources/appManagementConfiguration.md(10,1), beta/resources/registrationenforcement.md(10,1)'. First level headings must be unique within a docset.`````

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-034bdd81"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 22, C [...]

2021-07-19 20:52 UTC, madansr7 commented on changelog/Microsoft.DirectoryServices.json
> +      "Cloud": "prd",
I thought that was the guidance on the site. There are two change lists here. Maybe i am misunderstanding something.

2021-07-19 20:52 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +# [HTTP](#tab/http)
fixed. I removed the section.

2021-07-19 20:52 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +  "name": "create_appManagementPolicies"
updated.

2021-07-19 23:13 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post.md
> +title: "Create an application management policy."
Sorry, not sure what you mean.

2021-07-20 16:46 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +If successful, this method returns a `204 OK` response code.
delete is a 204. I updated the no content part.

2021-07-20 16:46 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +
updated.

2021-07-20 16:46 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-get.md
> +Read the properties of a [appManagementPolicy](../resources/appManagementPolicy.md) object.
updated.

2021-07-20 16:46 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list.md
> +Read the properties of a [appManagementPolicy](../resources/appManagementPolicy.md) object.
updated.

2021-07-20 16:46 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post.md
> +# Get defaultAppManagementPolicy
fixed.

2021-07-20 16:47 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-update.md
> +# Get defaultAppManagementPolicy
fixed.

2021-07-20 16:48 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +title: "Delete an app management policy"
yeah, looks like i missed a commit in my merge. Fixed them now.

2021-07-20 16:52 UTC, madansr7 commented on api-reference/beta/resources/appManagementConfiguration.md
> +| passwordCredentials | [graph.passwordCredentialConfiguration](../resources/passwordCredentialConfiguration.md) | Collection of password restrictions settings to be applied to Application or Service
updated. thanks for the suggestion.

2021-07-20 16:56 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +| restrictions | [appManagementConfiguration](../resources/appManagementConfiguration.md) | Restrictions that apply to applications or service principal object.                |
Updated.

2021-07-20 17:00 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +Application auth method tenant app management policy type enforces app management operation restrictions for all applications and service principals.
sorry, not sure what's suggested.

2021-07-20 17:02 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +  "isEnabled": boolean,
That suggestion doesn't seem right. 
If we are documenting the 'type' for each property, then the right value for this should be 'boolean'.
For e.g. refer to the property above, displayName is of type 'string'.

2021-07-20 17:04 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +title: "Application auth method tenant default policy "
you mean the H1 title? It is 'defaultAppManagementPolicy'.

2021-07-20 18:55 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +
updated.

2021-07-20 18:56 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +Tenant wide application auth method policy type enforces app management operation restrictions for all applications and service principals.
updated.

2021-07-20 18:59 UTC, madansr7 commented on api-reference/beta/resources/passwordCredentialConfiguration.md
> +| maxLifeTime                         | Duration                                                                           | Value that can be used as the maximum number for setting password expirati
Updated. Although i updated the text but i feel since we are describing the attributes of the property in the description, saying 'it' would also be fine and less verbose.

2021-07-20 19:05 UTC, madansr7 commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added navigation properties 'defaultAppManagementPolicy' and 'appManagementPolicies' to policies singleton.",
updated.

2021-07-20 19:05 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post-applyToResource.md
> +
It is a 204 no content response.

2021-07-20 19:06 UTC, madansr7 commented on api-reference/beta/resources/passwordCredentialConfiguration.md
> +| restrictionType                     | [graph.appCredentialRestrictionType](../resources/appCredentialRestrictionType.md) | Enum values that define the type of restriction being applied. Possible va
updated.

2021-07-20 19:09 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +| [Get](../api/applicationAuthMethodResourcePolicy-get.md)       | [appManagementPolicy](../resources/applicationAuthMethodResourcePolicy.md) | Gets a single app management policy object.
verified.

2021-07-20 19:14 UTC, opbld30 commented
Docs Build status updates of commit _[642bbdb](https://github.com/madansr7/microsoft-graph-docs/commits/642bbdb452237cfd29ce8ecaa19279ad9b114055)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4134d2f2)

<a id="4134d2f2"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107201914057840-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A19%3A18Z&ske=2021-07-26T02%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T19%3A09%3A25Z&se=2021-08-20T19%3A14%3A25Z&sr=b&sp=r&sig=X98kql%2Fnr3Lkmc13RhuFPe4riAOpcFcqO2JFfO8A4Uk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-21 06:28 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      "Cloud": "prd",
Because all your entries relate to one API & only for beta, one ChangeList is required. This will also ensure the release items are grouped in a single section in the [public changelog](https://developer.microsoft.com/en-us/graph/changelog).

2021-07-21 06:43 UTC, FaithOmbongi commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +title: "Application auth method tenant default policy "
Nope, this metadata title in line 2. The convention is metadata title = H1 title; for both resource and API topics. You can confirm with the [guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title)

So this title would be **defaultAppManagementPolicy resource type**. Kindly also check all other resources and API topic titles (both metadata & H1) in this PR.

2021-07-21 06:47 UTC, FaithOmbongi commented on api-reference/beta/resources/appManagementPolicy.md
> +| [Get](../api/applicationAuthMethodResourcePolicy-get.md)       | [appManagementPolicy](../resources/applicationAuthMethodResourcePolicy.md) | Gets a single app management policy object.
Then _../api/applicationAuthMethodResourcePolicy-get.md_ should be **../api/applicationmethodpolicy-get.md** instead—to align with the file name. This fix will also resolve some of the invalid file link warnings.

2021-07-21 06:50 UTC, FaithOmbongi commented on api-reference/beta/api/appManagementPolicy-post.md
> +title: "Create an application management policy."
Convention is metadata title is the same as the H1 title; for both resource and API reference topics. Kindly see the guidance: [TOC and topic title](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners?pagePath=%2FAPI%2FDocument%2FGuidelines%2FToC%20and%20topic%20title).

2021-07-21 17:56 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +Application auth method tenant app management policy type enforces app management operation restrictions for all applications and service principals.
updated.

2021-07-21 17:56 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +  "isEnabled": boolean,
@FaithOmbongi , can i mark this as resolved?

2021-07-21 20:35 UTC, opbld30 commented
Docs Build status updates of commit _[44876d8](https://github.com/madansr7/microsoft-graph-docs/commits/44876d848dae1143be91c5c5bbfc908dbafa6ee7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-b4ce431f)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-b4ce431f)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/defaultAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/defaultAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/defaultAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/defaultappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/defaultAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/defaultAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/defaultappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-b4ce431f"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 22, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/applicationAuthMethodResourcePolicy-get.md'.`````
 - **Line 22, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/applicationAuthMethodResourcePolicy.md'.`````
 - **Line 23, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/applicationAuthMethodResourcePolicy-get.md'.`````
 - **Line 23, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/applicationAuthMethodResourcePolicy.md'.`````
 - **Line 24, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/applicationAuthMethodResourcePolicy-get.md'. [...]

2021-07-22 11:53 UTC, FaithOmbongi requested changes
- GLOBAL: There seems to be a disconnect in defaultAppManagementPolicy. The CSDL says this is a property of type tenantAppManagementPolicy; the expected resource name is therefore tenantAppManagementPolicy.

> However, the request URL is https://graph.microsoft.com/beta/policies/defaultAppManagementPolicy
instead of policies/tenantAppManagementPolicy

The API.md also doesn't mention tenantAppManagementPolicy

- Is there a method to unassign an appManagementPolicy from an app/SP?
- GLOBAL: The headers in permissions reference tables are incomplete
- Add navigation property in policyRoot
- Add missing relationships

I think this thread shows how using the stub generator really helps.

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +
```suggestion

Application authentication methods such as certificates and password secrets allow apps to acquire tokens to access data in Azure Active Directory (Azure AD). The policies allow IT admins to enforce best practices for how apps in their organizations use these app authentication methods. For example, an admin might configure a policy to block the use or limit the lifetime of password secrets, and use the creation date of the object to enforce the policy.

These policies allow organizations to take advantage of the new app security hardening features. By enforcing restrictions that are based on the application or service principal created date, an organization can review their current app security posture, inventory apps, and enforce controls per their resourcing schedules and needs. This approach using the created date allows the organization to enforce the policy for new applications and also apply it to existing applications.

There are two types of policy controls:

- Tenant default policies that apply to all applications or service principals.
- Resource-specific (application or service principal) policies that allow inclusion or exclusion of individual applications from the tenant default policy.

```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +## Organization default app management policy
```suggestion
## Tenant default app management policy
```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +
```suggestion


A tenant default policy is a single object that always exists and is disabled by default. It's defined by the [defaultAppManagementPolicy](defaultappmanagementpolicy.md) resource and enforces restrictions on application vs service principal objects.

It contains the following two properties:
+ **applicationRestrictions** allows targeting applications owned by the tenant (application objects).
+ **servicePrincipalRestrictions** allows targeting provisioned from another tenant (service principal objects.

These properties allow the organization to either lock down apps that originate within a tenant or raise the quality bar for apps that are provisioned from outside the tenant boundary.

```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +## Application/Service Principal policy
```suggestion
## Resource-specific (application and service principal) policy
```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +> Neither the tenant default policies nor the app/SP specific policies block token issuance for existing applications. So, an application that does not meet the policy requirements will continue to w
```suggestion
Resource-specific policies are defined in the [appManagementPolicy](appmanagementpolicy.md) resource, which contains a collection of policies with varying restrictions or different enforcement dates. An admin can then assign one of these policies to an application or service principal, excluding them from the tenant default policy. 

When both the tenant default policy and resource-specific policy exist, the resource-specific policy takes precedence and the assigned application or service principal doesn't inherit from the tenant policy. Only one policy can be assigned to an application or service principal.

> [!Note]
> Neither the tenant default policies nor the resource-specific policies block token issuance for existing applications. Therefore, an application that doesn't meet the policy requirements will continue to work until it tries to update to add a new secret.
```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +| passwordLifetime | Enforce a max lifetime range for a password secret.   | Restrict all new password secrets to 30 days max on applications created after '01/01/2019'. |
```suggestion
The application authentication methods policy API offers the following restrictions:

| Restriction name | Description                                   | Examples                                                                                               |
|:-----------------|:----------------------------------------------|:-------------------------------------------------------------------------------------------------------|
| passwordAddition | Restrict password secrets on applications.    | Block new passwords on applications created on or after '01/01/2019'.                                  |
| passwordLifetime | Enforce a max lifetime for a password secret. | Restrict all new password secrets to a maximum of 30 days for applications created after '01/01/2019'. |
```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +To restrict multi-tenant apps homed in customer tenant, a policy is applied to the application object where as multi-tenant apps provisioned from another tenant are managed by applying the policy to
```suggestion
### Single vs. Multi-tenant apps

For single tenant apps, apply the policy to the application object. To restrict multi-tenant apps homed in a customer tenant, apply the policy to the application object. To restrict multi-tenant apps provisioned from another tenant, apply the policy to the servicePrincipal object.
```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +### Summary of key difference between Default policy and Resource policies
```suggestion
### Summary of key differences between the tenant default policy and resource-specific policies
```

2021-07-22 11:53 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +- Try the API in the [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer).
```suggestion
| Default policy                                                             | Resource-specific policy                                                                                                                            |
|----------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| Policy always exists.                                                      | Policy objects are created or updated to override the default policy.                                                                               |
| Restrictions are disabled by default for all resources.                    | Allows customization for single-tenant and multi-tenant resources.                                                                                  |
| Allows only single restriction object definition for all resources.        | Allows multiple policy objects to be defined, but only one can be applied to a resource.                                                            |
| Allows distinction of restrictions for app objects vs. service principals. | Policy can be applied to either an application or service principal object.                                                                         |
| Applies all restrictions configured to all apps or service principals.     | Applies only the restrictions configured in the resource policy to the specified app or service principal, and doesn't inherit from default policy. |

## Next steps

- [defaultApManagementPolicy](defaultappmanagementpolicy.md) resource type.
- [appManagementPolicy](appmanagementpolicy.md) resource type.
```

2021-07-26 03:27 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +  "name": "delete_appManagementPolicies"
updated.

2021-07-26 03:28 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +If successful, this method returns a `204 OK` response code.
updated.

2021-07-26 03:33 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +- Try the API in the [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer).
done.

2021-07-26 03:34 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +### Summary of key difference between Default policy and Resource policies
updated.

2021-07-26 03:35 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +To restrict multi-tenant apps homed in customer tenant, a policy is applied to the application object where as multi-tenant apps provisioned from another tenant are managed by applying the policy to
I feel it is important to have them as separate bullets. It's a very important call out.

2021-07-26 03:39 UTC, madansr7 commented on api-reference/beta/resources/passwordCredentialConfiguration.md
> +| maxLifeTime                         | Duration                                                                           | Value that can be used as the maximum number for setting password expirati
The value would be null when not set. For restriction that blocks passwords, it does not make sense to have a maxlifetime for them. So the value would always be null. All restrictions inherit from the common complex type which is why it null sometimes.

2021-07-26 03:41 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +If successful, this method returns 204 No Content response code. It does not return anything in the response body.
not sure why are we deviating from the 204 no content response message?

2021-07-26 03:49 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +> Neither the tenant default policies nor the app/SP specific policies block token issuance for existing applications. So, an application that does not meet the policy requirements will continue to w
updated.

2021-07-26 03:52 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +| passwordLifetime | Enforce a max lifetime range for a password secret.   | Restrict all new password secrets to 30 days max on applications created after '01/01/2019'. |
updated.

2021-07-26 04:35 UTC, opbld31 commented
Docs Build status updates of commit _[4c2109b](https://github.com/madansr7/microsoft-graph-docs/commits/4c2109bdd6ffe746c0383b2b0f5de3174ad08fea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-8b31155e)
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-8b31155e)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-8b31155e"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 22, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/applicationAuthMethodResourcePolicy-get.md'.`````
 - **Line 22, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/applicationAuthMethodResourcePolicy.md'.`````
 - **Line 23, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/applicationAuthMethodResourcePolicy-get.md'.`````
 - **Line 23, Column 68**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/applicationAuthMethodResourcePolicy.md'.`````
 - **Line 24, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/applicationAuthMethodResourcePolicy-get.md'.`````
 -  [...]

2021-07-26 05:48 UTC, opbld34 commented
Docs Build status updates of commit _[dda30a4](https://github.com/madansr7/microsoft-graph-docs/commits/dda30a4f6724bfdebf1a5a05aaf648b2601897f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-5ec1e6611ee32027e0d4405c12ee5975-af9b46bd)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5ec1e6611ee32027e0d4405c12ee5975-af9b46bd"></a>
### [api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md)
 - **Line 22, Column 41**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/appCredentialRestrictionType.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107260547041536-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A42%3A12Z&ske=2021-08-02T03%3A47%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T05%3A43%3A45Z&se=2021-08-26T05%3A48%3A45Z&sr=b&sp=r&sig=1kthFlF1cq4R%2F8roUp%2BUcYcamV5O64Ukm%2Bz%2ByPHnep4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as  [...]

2021-07-26 06:06 UTC, opbld32 commented
Docs Build status updates of commit _[e7ffd38](https://github.com/madansr7/microsoft-graph-docs/commits/e7ffd381ded8958f9b2e7cc13e1cc1c330d779e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107260604447339-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A37%3A26Z&ske=2021-08-02T02%3A42%3A26Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T06%3A01%3A27Z&se=2021-08-26T06%3A06%3A27Z&sr=b&sp=r&sig=i7LMs1AkwDiMClPEhoWOnU0aeLs4DqWWAmWvikLBESo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 14:43 UTC, FaithOmbongi commented on api-reference/beta/api/appManagementPolicy-delete.md
> +If successful, this method returns 204 No Content response code. It does not return anything in the response body.
@madansr7 , not deviating. That placeholder text is for the H2 Response section 
(~Line 49) which is different from this H3 Response section under **Examples**.

2021-07-26 14:51 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +The application authentication methods policy APIs offer the following restrictions:
```suggestion
The application authentication methods policy API offers the following restrictions:
```

2021-07-26 14:51 UTC, FaithOmbongi commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +To restrict multi-tenant apps homed in customer tenant, a policy is applied to the application object where as multi-tenant apps provisioned from another tenant are managed by applying the policy to
Noted. Changed the description.

2021-07-26 16:51 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post.md
> +title: "Create an application management policy."
it matches now.

2021-07-26 16:54 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +| [Get](../api/applicationAuthMethodResourcePolicy-get.md)       | [appManagementPolicy](../resources/applicationAuthMethodResourcePolicy.md) | Gets a single app management policy object.
fixed. the links are updated to point appManagementPolicy-get.md.

2021-07-26 16:54 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +title: "Application auth method tenant default policy "
this is fixed already.

2021-07-26 16:55 UTC, madansr7 commented on changelog/Microsoft.DirectoryServices.json
> +      "Cloud": "prd",
this is updated.

2021-07-26 16:57 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +  "isEnabled": boolean,
yeah, i feel the stub generator needs to update. This seems mismatched from the other properties which are stating types vs this one which is the value for the type. String, Boolean, etc are types and "example", true are values.

2021-07-26 17:01 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-get.md
> +  "name": "get_appManagementPolicies"
fixed.

2021-07-26 17:33 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-get.md
> +The following is an example of the response.
added.

2021-07-26 17:37 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list-appliesTo.md
> +# List appManagementPolicy assignment
updated to **List appManagementPolicy appliesTo**

2021-07-26 17:37 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list-appliesTo.md
> +List resources assigned to an [appManagementPolicy](../resources/appManagementPolicy.md) policy object.
updated.

2021-07-26 17:53 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list-appliesTo.md
> +## HTTP request
updated to a relevant example.

2021-07-26 17:54 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list-appliesTo.md
> +  "name": "get_appManagementPolicyAssignment"
Updated to get_appManagementPolicyAppliesTo

2021-07-26 19:37 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list-appliesTo.md
> +GET https://graph.microsoft.com/beta/policies/appManagementPolicies/{id}/appliesTo?$select=id,appId,displayName,createdDateTime
updated to two examples.

2021-07-26 19:37 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list-appliesTo.md
> +The following is an example of the response.
updated.

2021-07-26 19:37 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list-appliesTo.md
> +  "@odata.context": "https://graph.microsoft.com/beta/$metadata#directoryObjects(id,appId,displayName,createdDateTime)",
updated. this is now in the second example.

2021-07-26 19:38 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-list.md
> +Read the properties of an [appManagementPolicy](../resources/appManagementPolicy.md) object.
updated.

2021-07-26 19:42 UTC, opbld33 commented
Docs Build status updates of commit _[de65c2a](https://github.com/madansr7/microsoft-graph-docs/commits/de65c2a2718215bcdbfce94398d754c7e231c614)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107261940453278-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A34%3A12Z&ske=2021-08-02T02%3A39%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T19%3A37%3A22Z&se=2021-08-26T19%3A42%3A22Z&sr=b&sp=r&sig=uJOt0yhE5N%2B9dNd5ojz4psVsWeQ4E6Uty5l9Try3%2B5o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 19:46 UTC, opbld33 commented
Docs Build status updates of commit _[11798c4](https://github.com/madansr7/microsoft-graph-docs/commits/11798c46f20d1f21619ecd28c6bc353d5327cf32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107261945087736-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-23T07%3A59%3A10Z&ske=2021-07-30T08%3A04%3A10Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T19%3A41%3A43Z&se=2021-08-26T19%3A46%3A43Z&sr=b&sp=r&sig=LaTr2fEzDlS0Pw0Nkh3udUzNQY6HfR9xhgulKV3yE14%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 19:46 UTC, opbld33 commented
Docs Build status updates of commit _[11798c4](https://github.com/madansr7/microsoft-graph-docs/commits/11798c46f20d1f21619ecd28c6bc353d5327cf32)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 19:47 UTC, opbld31 commented
Docs Build status updates of commit _[2e0ec86](https://github.com/madansr7/microsoft-graph-docs/commits/2e0ec8696a17bf4d3b01412c4e2f4b2662d58e52)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 20:00 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +The application authentication methods policy APIs offer the following restrictions:
updated.

2021-07-26 20:02 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post-applyToResource.md
> +title: "Assign appManagementPolicy"
This suggestion doesn't seem to make sense. An app management policy is assigned or applied to an application or SP.

2021-07-26 20:02 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post-applyToResource.md
> +# Assign appManagementPolicy
same as above. assign appliesTo does sound right.

2021-07-26 20:04 UTC, opbld33 commented
Docs Build status updates of commit _[1f108c4](https://github.com/madansr7/microsoft-graph-docs/commits/1f108c474b846d30aacd83eec560afd16c808d6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-45ce9558)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-45ce9558"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262003174739-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A42%3A12Z&ske=2021-08-02T03%3A47%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T19%3A59%3A54Z&se=2021-08-26T20%3A04%3A54Z&sr=b&sp=r&sig=K3N6fHFqtJhl%2BosOlbV8OLpXrFNJ5Xhp0h3M8H15LD0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as a [...]

2021-07-26 20:06 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post-applyToResource.md
> +POST /applications/{id}/appManagementPolicies/$ref
Application and Service Principal operations do not define parameters as 'application-id'. 
`GET /applications/{id}`

2021-07-26 20:08 UTC, opbld34 commented
Docs Build status updates of commit _[0a753b3](https://github.com/madansr7/microsoft-graph-docs/commits/0a753b394011132f05cb8e36ccada87305a03de6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-d6f335cd)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-d6f335cd"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262006549517-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A42%3A12Z&ske=2021-08-02T03%3A47%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A03%3A29Z&se=2021-08-26T20%3A08%3A29Z&sr=b&sp=r&sig=om4F%2FZeg9cyoS9%2B74vvRZn7LBIXSnBBzvdL2aB4GVPQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as [...]

2021-07-26 20:10 UTC, opbld34 commented
Docs Build status updates of commit _[4b2c235](https://github.com/madansr7/microsoft-graph-docs/commits/4b2c2359ea908a1724aede39f5ccbed803a2abca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-2e997858)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-2e997858"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262008069467-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A33%3A16Z&ske=2021-08-02T02%3A38%3A16Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A05%3A14Z&se=2021-08-26T20%3A10%3A14Z&sr=b&sp=r&sig=r2jgU%2BHqk5jKme4IeubqPNjNQjVlb6jMikqyjynBNWo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as a [...]

2021-07-26 20:11 UTC, opbld33 commented
Docs Build status updates of commit _[d88455b](https://github.com/madansr7/microsoft-graph-docs/commits/d88455b6f756ad001c7f449e1d5026c75414f252)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-05d084d5)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-05d084d5"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262009335995-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A26%3A24Z&ske=2021-08-02T02%3A31%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A06%3A57Z&se=2021-08-26T20%3A11%3A57Z&sr=b&sp=r&sig=Q6%2FicTk1YjCi9hwI7a%2BVv4pVUaQiuddDrG8PrwejtIQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as [...]

2021-07-26 20:12 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +| Application                            | Policy.Read.All, Policy.ReadWrite.ApplicationConfiguration |
there is no Policy.ReadWrite.All

2021-07-26 20:14 UTC, opbld34 commented
Docs Build status updates of commit _[7ab502d](https://github.com/madansr7/microsoft-graph-docs/commits/7ab502d514114990b4a96e7a95973fe3d264b9cc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 20:15 UTC, madansr7 commented on api-reference/beta/resources/passwordCredentialConfiguration.md
> +| restrictForAppsCreatedAfterDateTime | DateTimeOffset                                                                     | Enforces the policy for an app created on or after the enforcement date. F
It can be null but we have a follow up item to change it from nullable. This can cause an entire tenant to restrict passwords accidently. That's why i did not include it.

2021-07-26 20:17 UTC, opbld34 commented
Docs Build status updates of commit _[08c643e](https://github.com/madansr7/microsoft-graph-docs/commits/08c643e9b201a4ea5ca416b29d37fb315bee3230)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-53b502a2)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-53b502a2"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262015333571-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A12%3A15Z&ske=2021-08-02T03%3A17%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A12%3A17Z&se=2021-08-26T20%3A17%3A17Z&sr=b&sp=r&sig=6uJI8aNCZs48Ev96dlJEpsuu9f%2B1RBOMAv6co1ysb3k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as a [...]

2021-07-26 20:18 UTC, opbld31 commented
Docs Build status updates of commit _[57e005d](https://github.com/madansr7/microsoft-graph-docs/commits/57e005d15465b42b928a65c40f7200996f4c06ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-a6c72596)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-a6c72596"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262016148995-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T06%3A08%3A17Z&ske=2021-08-02T06%3A13%3A17Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A13%3A55Z&se=2021-08-26T20%3A18%3A55Z&sr=b&sp=r&sig=D0idZ27KI%2BDcVeWmoD46M4HYIwG59nkD9sIufUDzrHc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as a [...]

2021-07-26 20:19 UTC, opbld32 commented
Docs Build status updates of commit _[57e005d](https://github.com/madansr7/microsoft-graph-docs/commits/57e005d15465b42b928a65c40f7200996f4c06ee)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 20:20 UTC, opbld32 commented
Docs Build status updates of commit _[0a16d27](https://github.com/madansr7/microsoft-graph-docs/commits/0a16d2768acc8283e6685de996be8ca2d2ecbef1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-8ae9a1e1)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-8ae9a1e1"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262016382650-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A23%3A25Z&ske=2021-08-02T03%3A28%3A25Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A15%3A49Z&se=2021-08-26T20%3A20%3A49Z&sr=b&sp=r&sig=4aWgfbQH0pd4jd8ysAm9%2FKvlNgnqHLsEguZ9vOA0Hbs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as a [...]

2021-07-26 20:21 UTC, opbld33 commented
Docs Build status updates of commit _[f369e9e](https://github.com/madansr7/microsoft-graph-docs/commits/f369e9e5859db055559772b95bebba5259d67354)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 20:23 UTC, opbld34 commented
Docs Build status updates of commit _[c206cdc](https://github.com/madansr7/microsoft-graph-docs/commits/c206cdceb4b954556c88557f0dcfa17006344cbd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-ef479cb6)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-ef479cb6"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262021413199-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A37%3A26Z&ske=2021-08-02T02%3A42%3A26Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A18%3A31Z&se=2021-08-26T20%3A23%3A31Z&sr=b&sp=r&sig=Os%2FzqN03%2Bdoq8HmbbMEU2IzhW%2BOIqRE7m1nBNe487%2Fo%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links writte [...]

2021-07-26 20:24 UTC, madansr7 commented on api-reference/beta/resources/appManagementConfiguration.md
> +| passwordCredentials | [passwordCredentialConfiguration](passwordCredentialConfiguration.md) | Collection of password restrictions settings to be applied to an application or service principal |
not missing. KeyCredentials is not deployed yet.

2021-07-26 20:25 UTC, opbld32 commented
Docs Build status updates of commit _[7e41e23](https://github.com/madansr7/microsoft-graph-docs/commits/7e41e23945bcc604636c9fea529222c35acaca90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-2ae3976a)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-2ae3976a"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262022206502-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A29%3A52Z&ske=2021-08-02T02%3A34%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A20%3A21Z&se=2021-08-26T20%3A25%3A21Z&sr=b&sp=r&sig=PwwMem8ZGTcDmwJUORISCIcaPkCMUVWxv6u3IjVqMko%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as abs [...]

2021-07-26 20:25 UTC, madansr7 commented on api-reference/beta/resources/appManagementConfiguration.md
> +  }
no, not missing. keyCredentials isn't ready and not deployed yet.

2021-07-26 20:27 UTC, opbld33 commented
Docs Build status updates of commit _[9d6ba16](https://github.com/madansr7/microsoft-graph-docs/commits/9d6ba16eca1e5f6f08dca999f07dc00a1e0a8269)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-95c76ab4)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-95c76ab4"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262023487152-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A29%3A52Z&ske=2021-08-02T02%3A34%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A22%3A05Z&se=2021-08-26T20%3A27%3A05Z&sr=b&sp=r&sig=tEJ1vW055DjRAm7mNUsKwiLa6N0Y0m%2FzjKhmzcGww6g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as a [...]

2021-07-26 20:28 UTC, opbld33 commented
Docs Build status updates of commit _[038646e](https://github.com/madansr7/microsoft-graph-docs/commits/038646ec28014e8edd373cdb67896a6141d6a51d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-f6113aeb)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-f6113aeb"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262024493844-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T04%3A14%3A40Z&ske=2021-08-02T04%3A19%3A40Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A23%3A47Z&se=2021-08-26T20%3A28%3A47Z&sr=b&sp=r&sig=Qm2HY6%2F%2ByA6XWb4bO6Idv5trA8hlxA81gImlwZ59F2E%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as [...]

2021-07-26 20:30 UTC, opbld30 commented
Docs Build status updates of commit _[9d6ba16](https://github.com/madansr7/microsoft-graph-docs/commits/9d6ba16eca1e5f6f08dca999f07dc00a1e0a8269)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-04342893)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-04342893"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262023384616-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A06%3A48Z&ske=2021-08-02T03%3A11%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A25%3A32Z&se=2021-08-26T20%3A30%3A32Z&sr=b&sp=r&sig=sa9zlAqCi11twruok1X3YA9CZhHIslDH34%2B32irah%2Fs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as [...]

2021-07-26 20:38 UTC, opbld34 commented
Docs Build status updates of commit _[e976d3a](https://github.com/madansr7/microsoft-graph-docs/commits/e976d3ad4982970f9462fe452cce59a13653d2f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-43c8cbf2)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-43c8cbf2"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262036480452-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T06%3A14%3A02Z&ske=2021-08-02T06%3A19%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T20%3A33%3A10Z&se=2021-08-26T20%3A38%3A10Z&sr=b&sp=r&sig=6FSzjfGtvaPQVnIn5e%2BrLUq8UbvJRsk3AAsxHK%2BJmT0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as [...]

2021-07-26 22:41 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-get.md
> +Read the properties of a [defaultAppManagementPolicy](../resources/defaultAppManagementPolicy.md) object.
updated.

2021-07-26 23:19 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-get.md
> +}
updated.

2021-07-26 23:21 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-update.md
> +In the request body, supply the values for relevant fields from the [defaultAppManagementPolicy](../resources/defaultAppManagementPolicy.md) that should be updated. Existing properties that are not i
its not the properties of service principal that need to be updated. The update is on default policy and properties of default policy is what's needed here. I believe the link to the object should suffice and we don't need to overload the page.

2021-07-26 23:22 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-update.md
> +If successful, this method returns a 204 No Content response code. It does not return anything in the response body.
updated.

2021-07-26 23:24 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-update.md
> +The following is an example of the request.
updated.

2021-07-26 23:30 UTC, opbld32 commented
Docs Build status updates of commit _[08e1233](https://github.com/madansr7/microsoft-graph-docs/commits/08e1233b87b19f92db5d212530fd4a8dc5c9763c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 23:37 UTC, opbld34 commented
Docs Build status updates of commit _[70a29cb](https://github.com/madansr7/microsoft-graph-docs/commits/70a29cb89ca1d9881442d4def5118ddcaf36db60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-ffb73b2b)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-ffb73b2b"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262335332097-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A15%3A49Z&ske=2021-08-02T03%3A20%3A49Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T23%3A32%3A16Z&se=2021-08-26T23%3A37%3A16Z&sr=b&sp=r&sig=17jA7zKw5tvSNDRVe3tQoxZHumuohB55yP5jCkVM2Jg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as abs [...]

2021-07-26 23:39 UTC, opbld32 commented
Docs Build status updates of commit _[70a29cb](https://github.com/madansr7/microsoft-graph-docs/commits/70a29cb89ca1d9881442d4def5118ddcaf36db60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-ea9cc94f)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-ea9cc94f"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262335441025-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A35%3A40Z&ske=2021-08-02T02%3A40%3A40Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T23%3A34%3A08Z&se=2021-08-26T23%3A39%3A08Z&sr=b&sp=r&sig=OK1k6pxGc0IsyT13NxlWBe%2BPITFiE%2BrIaSVhmD0xv7k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as [...]

2021-07-27 00:27 UTC, opbld34 commented
Docs Build status updates of commit _[7823291](https://github.com/madansr7/microsoft-graph-docs/commits/7823291fc79d7e26b66e585d0297c36b856bf893)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-c03dd3ad)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-c03dd3ad"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270026237554-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A34%3A12Z&ske=2021-08-02T02%3A39%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T00%3A22%3A56Z&se=2021-08-27T00%3A27%3A56Z&sr=b&sp=r&sig=7Gxg4%2FoMuvNklmk%2Fj8yuk53OpDkwri2uolB5V4iqrkI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as [...]

2021-07-27 00:38 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +| Permission type                        | Permissions                                                |
sorry, not sure?

2021-07-27 00:38 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-update.md
> +In the request body, provide a JSON representation of an [appManagementPolicy](../resources/appManagementPolicy.md).
properties are for appManagement object and not the SP. The object is linked in the description.

2021-07-27 00:40 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-post-applyToResource.md
> +| Authorization | Bearer {token}. Required. |
yes, it is requried.

2021-07-27 00:41 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-update.md
> +title: "Update default app management policy"
updated.

2021-07-27 00:43 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-update.md
> +| Application                            | Policy.Read.All, Policy.ReadWrite.ApplicationConfiguration |
updated.

2021-07-27 00:51 UTC, opbld30 commented
Docs Build status updates of commit _[6b5ade4](https://github.com/madansr7/microsoft-graph-docs/commits/6b5ade49e0fb005b2379a94552002f6ea0f5f901)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 00:57 UTC, opbld30 commented
Docs Build status updates of commit _[1c39f59](https://github.com/madansr7/microsoft-graph-docs/commits/1c39f597a3021e4876173d2cbe987065904a1d7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-edd37118)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-edd37118"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270056101090-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A23%3A25Z&ske=2021-08-02T03%3A28%3A25Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T00%3A52%3A43Z&se=2021-08-27T00%3A57%3A43Z&sr=b&sp=r&sig=d7sZKWGrFqcUihz06gQJgfqdn57wXtiPl56DeCsjdgw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as abs [...]

2021-07-27 00:57 UTC, madansr7 commented on api-reference/beta/api/defaultAppManagementPolicy-update.md
> +Read the properties of a [defaultAppManagementPolicy](../resources/defaultAppManagementPolicy.md) object.
resolved.

2021-07-27 00:59 UTC, opbld34 commented
Docs Build status updates of commit _[1c39f59](https://github.com/madansr7/microsoft-graph-docs/commits/1c39f597a3021e4876173d2cbe987065904a1d7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-0991d459)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-0991d459"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270056202774-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A00%3A53Z&ske=2021-08-02T03%3A05%3A53Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T00%3A54%3A32Z&se=2021-08-27T00%3A59%3A32Z&sr=b&sp=r&sig=pXmUfLbMz3C68XYWsweUfYL1DGXIZ6XbjShN6MnyNDw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as abs [...]

2021-07-27 01:00 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +Enforce restrictions on app management operations for specific applications and service principals. If this resource is not configured for an application or service principal, the restrictions defaul
updated.

2021-07-27 01:01 UTC, opbld34 commented
Docs Build status updates of commit _[1c6adef](https://github.com/madansr7/microsoft-graph-docs/commits/1c6adef75c8fb9e2fca5789026ae980a358509f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-6c3df9b1)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6c3df9b1)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-6c3df9b1"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-6c3df9b1"></a>
### [api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml)
 - **Line 10931, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/appManagementPolicy-post-appliesTo.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270058097432-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A23%3A25Z&ske=2021-08-02T03%3A28%3A25Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T00%3A56%3A14Z&se=2021-08-27T01%3A01%3A14Z&sr=b&sp=r&sig=8cZ9tB [...]

2021-07-27 01:07 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +
post does not have appliesTo but get does. I've added the missing link.

2021-07-27 01:10 UTC, opbld30 commented
Docs Build status updates of commit _[0c52b0e](https://github.com/madansr7/microsoft-graph-docs/commits/0c52b0e853964c0db148c0889a592c50528f54bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-834a4d68)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-834a4d68)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-834a4d68"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-834a4d68"></a>
### [api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml)
 - **Line 10931, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/appManagementPolicy-post-appliesTo.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270108235585-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A29%3A52Z&ske=2021-08-02T02%3A34%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T01%3A05%3A10Z&se=2021-08-27T01%3A10%3A10Z&sr=b&sp=r&sig=jRQq3r [...]

2021-07-27 01:11 UTC, madansr7 commented on api-reference/beta/resources/appManagementPolicy.md
> +| restrictions | [appManagementConfiguration](appManagementConfiguration.md) | Restrictions that apply to an application or service principal object. |
updated.

2021-07-27 01:11 UTC, opbld31 commented
Docs Build status updates of commit _[e94da10](https://github.com/madansr7/microsoft-graph-docs/commits/e94da10397d803be944a03d8eb38291f39eb457c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-b143957c)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b143957c)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-b143957c"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-b143957c"></a>
### [api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml)
 - **Line 10931, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/appManagementPolicy-post-appliesTo.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270109375356-13418%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-23T09%3A50%3A20Z&ske=2021-07-30T09%3A55%3A20Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T01%3A06%3A55Z&se=2021-08-27T01%3A11%3A55Z&sr=b&sp=r&sig=nO3sG% [...]

2021-07-27 01:14 UTC, madansr7 commented on api-reference/beta/resources/passwordCredentialConfiguration.md
> +Password credential configuration object that contains properties to configure restrictions such as `passwordAddition`, `passwordLifetime` on password credentials.
updated.

2021-07-27 01:43 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +title: "defaultAppManagementPolicy resource type"
yeah, i already renamed to tenantAppManagementPolicy.

2021-07-27 01:45 UTC, madansr7 commented on api-reference/beta/resources/passwordCredentialConfiguration.md
> +| restrictionType                     | [graph.appCredentialRestrictionType](../resources/appCredentialRestrictionType.md) | Enum values that define the type of restriction being applied. Possible va
updated.

2021-07-27 01:46 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +| description                  | String                                                                   | The description of the default policy.                                |
updated.

2021-07-27 01:48 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +| isEnabled                    | Boolean                                                                  | Denotes if the policy is enabled.                                     |
the default is false because policy is disabled by default. I updated content.

2021-07-27 01:50 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +| servicePrincipalRestrictions | [appManagementConfiguration](../resources/appManagementConfiguration.md) | Restrictions that will apply as default to Service Principal objects. |
updated.

2021-07-27 01:54 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +## Organization default app management policy
updated.

2021-07-27 02:01 UTC, madansr7 commented on api-reference/beta/resources/applicationAuthMethodPolicy.md
> +
updated.

2021-07-27 02:04 UTC, madansr7 commented on api-reference/beta/resources/defaultAppManagementPolicy.md
> +Tenant wide application authentication method policy type enforces app management operation restrictions for all applications and service principals.
updated.

2021-07-27 02:11 UTC, opbld30 commented
Docs Build status updates of commit _[9ea7f45](https://github.com/madansr7/microsoft-graph-docs/commits/9ea7f45eedd2ecea1cb334af629ca3c2611f4226)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-3ab28fad)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-3ab28fad)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3ab28fad)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-3ab28fad"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="56e9593d92b54aaae83e16647d6ae35e-3ab28fad"></a>
### [api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md)
 - **Line 25, Column 111**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-3ab28fad"></ [...]

2021-07-27 02:12 UTC, madansr7 commented on api-reference/beta/api/appManagementPolicy-delete.md
> +| Permission type                        | Permissions                                                |
updated.

2021-07-27 06:50 UTC, opbld31 commented
Docs Build status updates of commit _[88c814d](https://github.com/madansr7/microsoft-graph-docs/commits/88c814ddb6898051f9d49fdc3d673e5229dac886)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-4249e926)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-4249e926)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4249e926)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-4249e926"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="56e9593d92b54aaae83e16647d6ae35e-4249e926"></a>
### [api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md)
 - **Line 25, Column 111**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-4249e926"></ [...]

2021-07-27 06:52 UTC, opbld31 commented
Docs Build status updates of commit _[29d7afe](https://github.com/madansr7/microsoft-graph-docs/commits/29d7afefa4b28e3696308d25c14073a38f4026a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-fc70bc1a)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-fc70bc1a)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-fc70bc1a)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-fc70bc1a"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="56e9593d92b54aaae83e16647d6ae35e-fc70bc1a"></a>
### [api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md)
 - **Line 25, Column 111**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-fc70bc1a"></ [...]

2021-07-27 06:53 UTC, opbld34 commented
Docs Build status updates of commit _[eb50a48](https://github.com/madansr7/microsoft-graph-docs/commits/eb50a4842bdcb80621ea7dd6fdefac1c1a84842d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-241ad786)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-241ad786)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-241ad786)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-241ad786"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="56e9593d92b54aaae83e16647d6ae35e-241ad786"></a>
### [api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md)
 - **Line 25, Column 111**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-241ad786"></ [...]

2021-07-27 07:12 UTC, opbld34 commented
Docs Build status updates of commit _[601f9ea](https://github.com/madansr7/microsoft-graph-docs/commits/601f9eaff07a750f2c668ffea5a7c9595443e7a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-12f8fed5)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-12f8fed5)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-12f8fed5)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-12f8fed5"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="56e9593d92b54aaae83e16647d6ae35e-12f8fed5"></a>
### [api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md)
 - **Line 25, Column 111**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'defaultappmanagementpolicy.md'.`````

<a id="0817dce4456c16725d5333633847d38f-12f8fed5"></ [...]

2021-07-27 07:23 UTC, opbld34 commented
Docs Build status updates of commit _[6336aae](https://github.com/madansr7/microsoft-graph-docs/commits/6336aae9a3244c67a2db35eb07fbd422802a4273)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-8329e05c)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-8329e05c)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-8329e05c)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8329e05c)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-8329e05c"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-8329e05c"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 28, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/appManagementPolicy-post-appliesTo.md'.`````
 [...]

2021-07-27 07:35 UTC, opbld31 commented
Docs Build status updates of commit _[b0fa2be](https://github.com/madansr7/microsoft-graph-docs/commits/b0fa2bec6986322a6841cd37a28b5956c7a85644)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-fbb77deb)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-fbb77deb)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-fbb77deb)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-fbb77deb)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-fbb77deb"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-fbb77deb"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 28, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/appManagementPolicy-post-appliesTo.md'.`````
 [...]

2021-07-27 07:40 UTC, FaithOmbongi requested changes
- Missing additions of appManagementPolicies nav properties on application and servicePrincipal resources.
- File name change:
api-reference/beta/api/appManagementPolicy-post-applyToResource.md => **api-reference/beta/api/appmanagementpolicy-post-appliesto.md**
- **GLOBAL FOR ALL METHODS**: Incomplete Permissions header description. Should be _Permissions (from least to most privileged)_
- Resolve API Doctor errors
- Resolve the invalid file link warnings
- Ensure that when these docs are shipped, the request query is also updated to be https://graph.microsoft.com/beta/policies/tenantAppManagementPolicy. Tested in Graph Explorer and it's still [https://graph.microsoft.com/beta/policies/defaultAppManagementPolicy](https://developer.microsoft.com/en-us/graph/graph-explorer?request=policies%2FdefaultAppManagementPolicy&method=GET&version=beta&GraphUrl=https://graph.microsoft.com)

2021-07-27 07:40 UTC, FaithOmbongi commented on api-reference/beta/api/appManagementPolicy-post-applyToResource.md
> +title: "Assign appManagementPolicy"
For consistency across Graph docs, let's follow [the guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title). The description tells the customer more about what this applies to.

2021-07-27 07:40 UTC, FaithOmbongi commented on api-reference/beta/api/appManagementPolicy-post.md
> +The following is an example of the request.
The placeholder _XX days_ needs to be replaced.

2021-07-27 07:40 UTC, FaithOmbongi commented on api-reference/beta/api/tenantAppManagementPolicy-update.md
> +In the request body, supply the values for relevant fields from the [tenantAppManagementPolicy](../resources/tenantAppManagementPolicy.md) that should be updated. Existing properties that are not inc
You must list these updatable properties. See [Example](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http#request-body).

2021-07-27 07:40 UTC, FaithOmbongi commented on api-reference/beta/resources/appManagementConfiguration.md
> +description: "App management configuration complex type."
```suggestion
description: "App management configuration object that contains properties which can be configured to enable various restrictions for applications and service principals."
```

2021-07-27 07:40 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +          - name: Default app management policy
To align with the name change
```suggestion
          - name: Tenant app management policy
```

2021-07-27 07:40 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +          - name: Application or service principal management policy
```suggestion
          - name: Resource-specific app management policy
```

2021-07-27 15:14 UTC, madansr7 commented on api-reference/beta/toc.yml
> +          - name: Application or service principal management policy
User is also a resource but these policies don't apply to them. I am fine changing it but resource is very generic and doesn't represent the objects to which these policies can apply.

2021-07-27 15:14 UTC, opbld34 commented
Docs Build status updates of commit _[552b040](https://github.com/madansr7/microsoft-graph-docs/commits/552b04078583a42c404d8fd8bbb4075c360baf60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-c78ddfff)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-c78ddfff)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-c78ddfff)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c78ddfff)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-c78ddfff"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-c78ddfff"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 28, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/appManagementPolicy-post-appliesTo.md'.`````
 [...]

2021-07-27 15:16 UTC, opbld31 commented
Docs Build status updates of commit _[fd3c64b](https://github.com/madansr7/microsoft-graph-docs/commits/fd3c64bd3153a6fd99495362a385830e73139bef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-8eb585ac)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-8eb585ac)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-8eb585ac)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8eb585ac)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-8eb585ac"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-8eb585ac"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 28, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/appManagementPolicy-post-appliesTo.md'.`````
 [...]

2021-07-27 15:18 UTC, opbld31 commented
Docs Build status updates of commit _[fd3c64b](https://github.com/madansr7/microsoft-graph-docs/commits/fd3c64bd3153a6fd99495362a385830e73139bef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-a325ac63)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-a325ac63)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-a325ac63)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a325ac63)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-a325ac63"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="f0f085fc8c8d7b9fce74cf2a336f64ad-a325ac63"></a>
### [api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md)
 - **Line 28, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/appManagementPolicy-post-appliesTo.md'.`````
 [...]

2021-07-27 18:29 UTC, madansr7 commented on api-reference/beta/api/tenantAppManagementPolicy-update.md
> +In the request body, supply the values for relevant fields from the [tenantAppManagementPolicy](../resources/tenantAppManagementPolicy.md) that should be updated. Existing properties that are not inc
added.

2021-07-27 18:29 UTC, madansr7 commented on api-reference/beta/toc.yml
> +          - name: Application or service principal management policy
@FaithOmbongi any thoughts on this comment?

2021-07-27 18:33 UTC, opbld32 commented
Docs Build status updates of commit _[09b17bd](https://github.com/madansr7/microsoft-graph-docs/commits/09b17bd619636166f2fb090ac101d643b3a55408)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-9ebdb170)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-9ebdb170)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-9ebdb170)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-9ebdb170)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-9ebdb170)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9ebdb170)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-9ebdb170"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="dd9c236e1ff793d716c5345ecce3941f-9ebdb170"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validat [...]

2021-07-27 18:47 UTC, FaithOmbongi commented on api-reference/beta/toc.yml
> +          - name: Application or service principal management policy
@madansr7 , I understand your PoV. What of **App management policy**? This way, the TOC title aligns with the resource name; plus, an SP is still tied to an application so I think **app management policy** covers everything. 

This means for the instances where we use the word _Resource-specific policy_, we can change that to **App management policy**.

2021-07-27 18:52 UTC, madansr7 commented on api-reference/beta/toc.yml
> +          - name: Application or service principal management policy
That's why i was referring these as policies that apply to specific application or service principal objects. I don't think we want to hold off the release for it.

2021-07-27 18:53 UTC, opbld34 commented
Docs Build status updates of commit _[6647cc4](https://github.com/madansr7/microsoft-graph-docs/commits/6647cc4d04cf972bb52433a6f9a66388afa26354)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-1e72be3b)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-1e72be3b)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-1e72be3b)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-1e72be3b)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-1e72be3b)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1e72be3b)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-1e72be3b"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="dd9c236e1ff793d716c5345ecce3941f-1e72be3b"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validat [...]

2021-07-27 18:55 UTC, opbld30 commented
Docs Build status updates of commit _[6647cc4](https://github.com/madansr7/microsoft-graph-docs/commits/6647cc4d04cf972bb52433a6f9a66388afa26354)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-4e347a49)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-4e347a49)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-4e347a49)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-4e347a49)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-4e347a49)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4e347a49)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-4e347a49"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="dd9c236e1ff793d716c5345ecce3941f-4e347a49"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validat [...]

2021-07-27 19:07 UTC, opbld31 commented
Docs Build status updates of commit _[b6882c9](https://github.com/madansr7/microsoft-graph-docs/commits/b6882c98bb15de8a7949cb06176b252ccb98e3b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-21236a18)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-21236a18)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-21236a18)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-21236a18)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-21236a18)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-21236a18)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-21236a18"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="dd9c236e1ff793d716c5345ecce3941f-21236a18"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validat [...]

2021-07-27 19:19 UTC, opbld34 commented
Docs Build status updates of commit _[a1d0a92](https://github.com/madansr7/microsoft-graph-docs/commits/a1d0a92ec1e6a778583f7b83ad958196c3b547b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-d0a8ad3e)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-d0a8ad3e)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-d0a8ad3e)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-d0a8ad3e)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-d0a8ad3e)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d0a8ad3e)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-d0a8ad3e"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="dd9c236e1ff793d716c5345ecce3941f-d0a8ad3e"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validat [...]

2021-07-27 19:21 UTC, opbld32 commented
Docs Build status updates of commit _[a1d0a92](https://github.com/madansr7/microsoft-graph-docs/commits/a1d0a92ec1e6a778583f7b83ad958196c3b547b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-41f7de018ca8631efc601e44c7735f1f-40820a4a)
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-40820a4a)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-40820a4a)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-40820a4a)
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-56e9593d92b54aaae83e16647d6ae35e-40820a4a)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-40820a4a)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="41f7de018ca8631efc601e44c7735f1f-40820a4a"></a>
### [api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md)
 - **Line 16, Column 208**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/defaultappmanagementpolicy.md'.`````

<a id="dd9c236e1ff793d716c5345ecce3941f-40820a4a"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validat [...]

2021-07-27 19:21 UTC, opbld30 commented
Docs Build status updates of commit _[5288a3c](https://github.com/madansr7/microsoft-graph-docs/commits/5288a3c26022383531d9e3ab7a5de9f0ee43b24a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 19:25 UTC, opbld34 commented
Docs Build status updates of commit _[0874a73](https://github.com/madansr7/microsoft-graph-docs/commits/0874a73712e74d747338534595e1f147a6da242d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-2c1df5c7)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-2c1df5c7)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-2c1df5c7)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2c1df5c7)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="dd9c236e1ff793d716c5345ecce3941f-2c1df5c7"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'policybase.md'.`````
 - **Line 52, Column 126**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'policybase.md'.`````
 - **Line 54, Column 18**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'appManagementConfiguration.md'.`````

<a id="f3b7938aea63f42ce20a784141240068-2c1df5c7"></a>
### [api-reference/beta/api/tenantAppManagementPolicy-update.md [...]

2021-07-27 19:27 UTC, opbld34 commented
Docs Build status updates of commit _[0874a73](https://github.com/madansr7/microsoft-graph-docs/commits/0874a73712e74d747338534595e1f147a6da242d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-e37c0de6)
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f3b7938aea63f42ce20a784141240068-e37c0de6)
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-f0f085fc8c8d7b9fce74cf2a336f64ad-e37c0de6)
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e37c0de6)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-applyToResource.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-applyToResource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-applytoresource?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="dd9c236e1ff793d716c5345ecce3941f-e37c0de6"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 51, Column 127**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'policybase.md'.`````
 - **Line 52, Column 126**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'policybase.md'.`````
 - **Line 54, Column 18**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'appManagementConfiguration.md'.`````

<a id="f3b7938aea63f42ce20a784141240068-e37c0de6"></a>
### [api-reference/beta/api/tenantAppManagementPolicy-update.md [...]

2021-07-28 00:57 UTC, opbld33 commented
Docs Build status updates of commit _[72a1f3b](https://github.com/madansr7/microsoft-graph-docs/commits/72a1f3ba7647d14004e25e307fb2e77dd009fbe4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-dd9c236e1ff793d716c5345ecce3941f-efa05e14)
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-efa05e14)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-efa05e14)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="dd9c236e1ff793d716c5345ecce3941f-efa05e14"></a>
### [api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md)
 - **Line 54, Column 18**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/con [...]

2021-07-28 06:18 UTC, opbld30 commented
Docs Build status updates of commit _[26c3652](https://github.com/madansr7/microsoft-graph-docs/commits/26c36524516c62a6f3a5822859d19a06f1356331)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-cc9b6f2b)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-cc9b6f2b)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-cc9b6f2b"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 06:47 UTC, opbld32 commented
Docs Build status updates of commit _[90d9e97](https://github.com/madansr7/microsoft-graph-docs/commits/90d9e975b13c342f2f2b2f520f36e68d79e9dc39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-1bfb5f71)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-1bfb5f71)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-1bfb5f71"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 14:25 UTC, opbld34 commented
Docs Build status updates of commit _[91d8d07](https://github.com/madansr7/microsoft-graph-docs/commits/91d8d07a91c3045b3295bb83974fa79f711fc5c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-12433d68)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-12433d68)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-12433d68"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 14:27 UTC, opbld31 commented
Docs Build status updates of commit _[91d8d07](https://github.com/madansr7/microsoft-graph-docs/commits/91d8d07a91c3045b3295bb83974fa79f711fc5c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-34444dab)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-34444dab)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-34444dab"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 14:37 UTC, opbld30 commented
Docs Build status updates of commit _[5abc2b6](https://github.com/madansr7/microsoft-graph-docs/commits/5abc2b6da352b9ef991560066c5ed51006e993ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-e2d366cb)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-e2d366cb)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-e2d366cb"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 14:39 UTC, opbld31 commented
Docs Build status updates of commit _[5abc2b6](https://github.com/madansr7/microsoft-graph-docs/commits/5abc2b6da352b9ef991560066c5ed51006e993ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-8110f13d)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-8110f13d)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-8110f13d"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 14:43 UTC, opbld33 commented
Docs Build status updates of commit _[e60d290](https://github.com/madansr7/microsoft-graph-docs/commits/e60d2902f814b2a4a754f6daa94e7f09da64fbec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-3cacb4b8)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-3cacb4b8)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-3cacb4b8"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 14:45 UTC, opbld32 commented
Docs Build status updates of commit _[6f7b5f8](https://github.com/madansr7/microsoft-graph-docs/commits/6f7b5f856387fd48f9ccb1c31f96394f50e1cd09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-49f213ed)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-49f213ed)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-49f213ed"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 14:47 UTC, opbld30 commented
Docs Build status updates of commit _[4f9352d](https://github.com/madansr7/microsoft-graph-docs/commits/4f9352d7aafaeae3787c7777a881942c21fb4b2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-9dbdf494)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-9dbdf494)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-9dbdf494"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 15:08 UTC, opbld32 commented
Docs Build status updates of commit _[c8c8955](https://github.com/madansr7/microsoft-graph-docs/commits/c8c8955ed8f874bdf6fdaf06cc9982b76493b86c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-30bcd3b0)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-30bcd3b0)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-30bcd3b0"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 15:32 UTC, opbld31 commented
Docs Build status updates of commit _[dcadde3](https://github.com/madansr7/microsoft-graph-docs/commits/dcadde36c6043df48864540a86ccf0018648dc0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-a18ac474)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-a18ac474)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-a18ac474"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 15:52 UTC, FaithOmbongi approved these changes

2021-07-28 19:03 UTC, opbld34 commented
Docs Build status updates of commit _[30c624e](https://github.com/madansr7/microsoft-graph-docs/commits/30c624e9679539b89543f852dfc5be049a04d668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-ddb7235fcab3930f5792589d50914b89-077126f9)
[api-reference/beta/resources/serviceprincipal.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) | [Details](#user-content-436c9311274b0a6f54e0ccb92667511d-077126f9)
[api-reference/beta/api/appManagementPolicy-delete.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list-appliesTo.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list-appliesTo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-list.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-list?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post-appliesto.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post-appliesto.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post-appliesto?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-post.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-post?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/appManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/appManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-get.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-get?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/api/tenantAppManagementPolicy-update.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/api/tenantAppManagementPolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tenantappmanagementpolicy-update?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/appManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/appManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/applicationAuthMethodPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/applicationAuthMethodPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/applicationauthmethodpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/passwordCredentialConfiguration.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/passwordCredentialConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/passwordcredentialconfiguration?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/policy-overview.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/policy-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/policy-overview?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/resources/tenantAppManagementPolicy.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/tenantAppManagementPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/tenantappmanagementpolicy?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appmanagementpolicy-delete?view=graph-rest-beta&branch=pr-en-us-13418) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ddb7235fcab3930f5792589d50914b89-077126f9"></a>
### [api-reference/beta/resources/application.md](https://github.com/madansr7/microsoft-graph-docs/blob/app-auth-method-policies/api-reference/beta/resources/application.md)
 - **Line 70, Column 192**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main [...]

2021-07-28 19:14 UTC, CelesteDG commented
Going ahead and merging @madansr7 and @FaithOmbongi

2021-07-28 19:14 UTC, merged