Updating docs, adding and fixing examples for Microsoft Teams
microsoftgraph/microsoft-graph-docs pull request #13416
Opened 2021-07-08 07:11 UTC by RamjotSingh

2021-07-08 07:12 UTC, opbld33 commented
Docs Build status updates of commit _[6a4708e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a4708ef3eb65d3ba3a7752cb1ae6f11facfaee7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-b2ab8b21)
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) | [Details](#user-content-5edd3dffd46b5b5088803794f723a16a-b2ab8b21)
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-send-activityfeednotifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-13416) | [Details](#user-content-3707469317fb509d53f3b50da810ed9e-b2ab8b21)
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[concepts/teams-activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-13416) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |

<a id="2d8cf89182fc122537ab8493d7c325f1-b2ab8b21"></a>
### [api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chatmessage-post.md)
 - **Line 758, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 3).`````
 - **Line 758, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="5edd3dffd46b5b5088803794f723a16a-b2ab8b21"></a>
### [api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chatmessage-post.md)
 - **Line 756, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Duplicate tab id: (http, 2).`````
 - **Line 756, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

<a id="3707469317fb509d53f3b50da810ed9e-b2ab8b21"></a>
### [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-send-activityfeednotifications.md)
 - **Line 417, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'activity-feed-notifications-best-practices.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080711226113-13416%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T06%3A24%3A56Z&ske=2021-07-13T06%3A29%3A56Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T07%3A07%3A55Z&se=2021-08-08T07%3A12%3A55Z&sr=b&sp=r&sig=kOxCsokDNSlLolJ3FVBTxpY3GlefMnFNtQjCViXDBDQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 07:20 UTC, opbld30 commented
Docs Build status updates of commit _[5debec2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5debec2a14ad2c888e9a18daa0129b1837dba32f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[concepts/teams-activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-13416) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-13416) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107080719146853-13416%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-08T06%3A57%3A21Z&ske=2021-07-15T07%3A02%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T07%3A15%3A51Z&se=2021-08-08T07%3A20%3A51Z&sr=b&sp=r&sig=vXjXPdq2qH8fDK1ZFD9f9re8xTMoydzjtjpB3U9cX0I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 19:51 UTC, opbld30 commented
Docs Build status updates of commit _[a715c92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a715c92eb9f544890c1c6d3ab7ab670f83db3184)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[concepts/teams-activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-13416) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-13416) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091949318797-13416%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A19%3A18Z&ske=2021-07-13T08%3A24%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T19%3A46%3A05Z&se=2021-08-09T19%3A51%3A05Z&sr=b&sp=r&sig=YG%2FXE07yeM6%2BV2WLCKxEDnLFE088lX%2BbCQD3wnfG42w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 20:52 UTC, JarbasHorst requested changes

2021-07-09 20:52 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +The following is an example of the request. Refer to [list channels](../api/channel-list.md) for getting list of channels in a team.
For consistency and readability, we introduce the subject before we provide the link. In this case, I recommend: 

- For information about how to get a list of channels in a team, see \[List channels\]\(../api/channel-list.md\).

2021-07-09 20:52 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +The following is an example of the request. Refer to [list tag](../api/teamworktag-list.md) for getting list of tags in a team.
For consistency and readability, we introduce the subject before we provide the link. In this case, I recommend: 

- For information about how to get a list of tags in a team, see \[List teamworkTags\]\(../api/teamworktag-list.md\).

2021-07-09 20:52 UTC, JarbasHorst commented on api-reference/v1.0/api/chatmessage-post.md
> +The following is an example of the request. Refer to [list channels](../api/channel-list.md) for getting list of channels in a team.
For consistency and readability, we introduce the subject before we provide the link. In this case, I recommend: 

- For information about how to get a list of channels in a team, see \[List channels\]\(../api/channel-list.md\).

2021-07-09 20:52 UTC, JarbasHorst commented on api-reference/v1.0/api/chatmessage-post.md
> +> Note: `conversationIdentityType` needs to be set to `channel` to @mention a channel.
Property/Resource names should have bold formatting applied. For readability, consider also replacing "needs to" with "must". Suggested revision:

- \*\*conversationIdentityType\*\* must be set to \`channel\` to @mention a channel.

2021-07-09 20:52 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +> Note: `conversationIdentityType` needs to be set to `channel` to @mention a channel.
Property/Resource names should have bold formatting applied. For readability, consider also replacing "needs to" with "must". Suggested revision:

- \*\*conversationIdentityType\*\* must be set to \`channel\` to @mention a channel.

2021-07-09 20:52 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +> Note: `conversationIdentityType` needs to be set to `team` to @mention a team.
Property/Resource names should have bold formatting applied. For readability, consider also replacing "needs to" with "must". Suggested revision:

- \*\*conversationIdentityType\*\* must be set to \`team\` to @mention a team.

2021-07-09 20:52 UTC, JarbasHorst commented on api-reference/v1.0/api/chatmessage-post.md
> +> Note: `conversationIdentityType` needs to be set to `team` to @mention a team.
Property/Resource names should have bold formatting applied. For readability, consider also replacing "needs to" with "must". Suggested revision:

- \*\*conversationIdentityType\*\* must be set to \`team\` to @mention a team.

2021-07-09 21:01 UTC, opbld30 commented
Docs Build status updates of commit _[09663c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09663c8d8b4d4f40597935403435c7917440be9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[concepts/teams-activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-13416) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-13416) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107092059326729-13416%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T22%3A53%3A24Z&ske=2021-07-13T22%3A58%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T20%3A56%3A12Z&se=2021-08-09T21%3A01%3A12Z&sr=b&sp=r&sig=bgCpcZwl5Z9ScHUmqLyUkh%2BY1W5ylkBs48RnlPJcypw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-12 19:39 UTC, JarbasHorst requested changes

2021-07-12 19:39 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +
For consistency, please, add "The following is an example of the response." after \#\#\#\# Response

2021-07-12 19:39 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +
For consistency, please, add "The following is an example of the response." after \#\#\#\# Response

2021-07-12 19:39 UTC, JarbasHorst commented on api-reference/beta/api/chatmessage-post.md
> +
For consistency, please, add "The following is an example of the response." after \#\#\#\# Response

2021-07-12 19:39 UTC, JarbasHorst commented on api-reference/v1.0/api/chatmessage-post.md
> +
For consistency, please, add "The following is an example of the response." after \#\#\#\# Response

2021-07-12 19:39 UTC, JarbasHorst commented on api-reference/v1.0/api/chatmessage-post.md
> +
For consistency, please, add "The following is an example of the response." after \#\#\#\# Response

2021-07-12 21:53 UTC, opbld30 commented
Docs Build status updates of commit _[fcda5af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcda5af47fa8f2858ac4ebeeb22464d8f4d8c7cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[concepts/teams-activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-13416) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-13416) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107122151429041-13416%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A53%3A48Z&ske=2021-07-19T07%3A58%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T21%3A48%3A08Z&se=2021-08-12T21%3A53%3A08Z&sr=b&sp=r&sig=0ZSf5JndAjDIvo75o%2Bkd%2BdYa1boPZQ8jS%2FbejRmR4rY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 19:34 UTC, JarbasHorst commented
@Lauragra this PR is ready for final review.

2021-07-13 23:16 UTC, opbld34 commented
Docs Build status updates of commit _[2e3d7b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e3d7b5ba8a6a61a6bffa59098c5270f745b70ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/beta/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-13416) (graph-rest-beta) |
[api-reference/v1.0/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/api-reference/v1.0/api/chatmessage-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&branch=pr-en-us-13416) (>= graph-rest-1.0) |
[concepts/teams-activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |
[concepts/teams-change-notification-in-microsoft-teams-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-change-notification-in-microsoft-teams-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-change-notification-in-microsoft-teams-overview?branch=pr-en-us-13416) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-13416) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/main-fixexamples/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-activity-feed-notifications-best-practices?branch=pr-en-us-13416) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107132314357737-13416%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A19%3A00Z&ske=2021-07-20T08%3A24%3A00Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-13T23%3A11%3A03Z&se=2021-08-13T23%3A16%3A03Z&sr=b&sp=r&sig=vqezCUMD%2Bu2kiUicmtF7wTOGrHA1cPD8UROpHtS4MSA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-13 23:20 UTC, Lauragra approved these changes

2021-07-14 01:40 UTC, merged