identity governance: add examples of adding resources and resource roles in entitlement management
microsoftgraph/microsoft-graph-docs pull request #13422
Opened 2021-07-08 17:28 UTC by markwahl-msft

2021-07-08 17:29 UTC, opbld33 commented
Docs Build status updates of commit _[e276ee0](https://github.com/markwahl-msft/microsoft-graph-docs/commits/e276ee04e64a650521a06bb1ca8d1253b21550e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081728080413-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A08%3A15Z&ske=2021-07-13T08%3A13%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T17%3A24%3A37Z&se=2021-08-08T17%3A29%3A37Z&sr=b&sp=r&sig=MJFzvdMwYpJoMieO7M2u5Eu12xWJq6SDs%2BfIwA7gPo0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 17:53 UTC, opbld31 commented
Docs Build status updates of commit _[4ba396d](https://github.com/markwahl-msft/microsoft-graph-docs/commits/4ba396dcf6e8d5bc0b366c0d826b171e078feef8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107081752100530-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-07T23%3A10%3A09Z&ske=2021-07-14T23%3A15%3A09Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T17%3A48%3A47Z&se=2021-08-08T17%3A53%3A47Z&sr=b&sp=r&sig=2U6eBjJCJa1%2FGnu87cKo9EXLLo%2Bkuj3hvI0xg6%2FiyA0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-08 21:39 UTC, opbld34 commented
Docs Build status updates of commit _[6c2e7a8](https://github.com/markwahl-msft/microsoft-graph-docs/commits/6c2e7a8491ce432f92c0c02165bfed2f0fe952b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107082138205201-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A03%3A42Z&ske=2021-07-13T07%3A08%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T21%3A34%3A51Z&se=2021-08-08T21%3A39%3A51Z&sr=b&sp=r&sig=wNqopyxk6mhFzjsUX4EwjmxFubAtkZaoDcF%2FLPdQCM0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 10:17 UTC, FaithOmbongi requested changes

2021-07-09 10:17 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-list.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve the access package of each request, include `$expand=accessPackage` in the query.  To
```suggestion
This method supports the `$expand` and `$filter` OData query parameters to help customize the response. For example, to retrieve the access package of each request, include `$expand=accessPackage` in the query.  To retrieve only requests for a specific access package, include in the query a filter such as `$expand=accessPackage&$filter=accessPackage/id eq '9bbe5f7d-f1e7-4eb1-a586-38cdf6f8b1ea'`.  To retrieve the resulting assignment, include `$expand=accessPackageAssignment` in the query.  To obtain more details on the requestor, include `$expand=requestor` in the query.
```

2021-07-09 10:17 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
> +Retrieve a list of [accessPackageResourceRole](../resources/accesspackageresourcerole.md) objects of an [accessPackageResource](../resources/accesspackageresource.md) in an [accessPackageCatalog](../
```suggestion
Retrieve a list of [accessPackageResourceRole](../resources/accesspackageresourcerole.md) objects of an [accessPackageResource](../resources/accesspackageresource.md) in an [accessPackageCatalog](../resources/accesspackagecatalog.md). The resource should have been added to the catalog by [creating an accessPackageResourceRequest](accesspackageresourcerequest-post.md). This list of roles can then be used by the caller to select a role, which is needed when subsequently [creating an accessPackageResourceRoleScope](accesspackage-post-accesspackageresourcerolescopes.md).
```

2021-07-09 10:17 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
> +### Example 2: Retrieving the roles of a resource for a SharePoint Online site
```suggestion
### Example 2: Retrieve the roles of a resource for a SharePoint Online site
```

2021-07-09 10:17 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
> +The following is an example of the request.
Proposing that you explain this request further. I think it'll help give context to what you described in the description. Example: https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-post?view=graph-rest-beta&tabs=http#example-2-create-an-access-review-on-all-teams-with-inactive-guest-users

Same for the response.

2021-07-09 15:08 UTC, opbld31 commented
Docs Build status updates of commit _[ca76bbd](https://github.com/markwahl-msft/microsoft-graph-docs/commits/ca76bbde951a8762f57ac347ae6a024024da5dc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091506523198-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T22%3A53%3A24Z&ske=2021-07-13T22%3A58%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T15%3A03%3A27Z&se=2021-08-09T15%3A08%3A27Z&sr=b&sp=r&sig=SoTkCAbNCq6LFpmJiyxLUBSP2eaeFK9uatgq%2Bhm%2FZ%2B0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 15:10 UTC, opbld33 commented
Docs Build status updates of commit _[44392e0](https://github.com/markwahl-msft/microsoft-graph-docs/commits/44392e005622ed80eaa46996bbda5ab2297a2ddf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091508310142-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A23%3A37Z&ske=2021-07-13T08%3A28%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T15%3A05%3A01Z&se=2021-08-09T15%3A10%3A01Z&sr=b&sp=r&sig=452ekb%2FxllsEhKacJe1%2BrU4CABb1hDlbkI5RSPSjNvI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 15:11 UTC, opbld30 commented
Docs Build status updates of commit _[30722e0](https://github.com/markwahl-msft/microsoft-graph-docs/commits/30722e075c8a5a5ede6a7a4dd083e2a437a09329)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091509093233-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T10%3A16%3A46Z&ske=2021-07-13T10%3A21%3A46Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T15%3A06%3A49Z&se=2021-08-09T15%3A11%3A49Z&sr=b&sp=r&sig=drEMH%2BiOm1%2FXr%2FVLlCSNVNyhaq8IfDM7nrnEDntfl4Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:28 UTC, opbld33 commented
Docs Build status updates of commit _[d5d770c](https://github.com/markwahl-msft/microsoft-graph-docs/commits/d5d770cab647321cd68ff1a0b1d006b1f2b6cda1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091827244725-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-09T05%3A34%3A07Z&ske=2021-07-16T05%3A39%3A07Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A23%3A57Z&se=2021-08-09T18%3A28%3A57Z&sr=b&sp=r&sig=rMtS9Zk9Nl4xhsKM94ND%2FQsStGCmmpcafTsJ%2FbAmkzE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:30 UTC, opbld33 commented
Docs Build status updates of commit _[c2c0516](https://github.com/markwahl-msft/microsoft-graph-docs/commits/c2c0516bb02cecbb59b3dc165321552d6a0794b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091827434201-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A37%3A13Z&ske=2021-07-13T07%3A42%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A25%3A25Z&se=2021-08-09T18%3A30%3A25Z&sr=b&sp=r&sig=VkQAnSgzsxKkARe%2FglDg6YdZxnJtoHzZV4kW4z%2FpT%2FA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:32 UTC, opbld34 commented
Docs Build status updates of commit _[d9b3b4a](https://github.com/markwahl-msft/microsoft-graph-docs/commits/d9b3b4a96bc5ceec85fcb7db61887b2617a9bd84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091831173518-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T08%3A23%3A37Z&ske=2021-07-13T08%3A28%3A37Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A27%3A47Z&se=2021-08-09T18%3A32%3A47Z&sr=b&sp=r&sig=ykmimfYmvtrXklIgBuLnQ5zR2wTqVq2OC7G7mSTVhO8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:38 UTC, opbld34 commented
Docs Build status updates of commit _[9c5d1c6](https://github.com/markwahl-msft/microsoft-graph-docs/commits/9c5d1c641c7eaa0fca00824c53dcbf223bdd261b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageassignmentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourcerole.md](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-em-addres/api-reference/beta/resources/accesspackageresourcerole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerole?view=graph-rest-beta&branch=pr-en-us-13422) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107091837111068-13422%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T09%3A08%3A42Z&ske=2021-07-13T09%3A13%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A33%3A43Z&se=2021-08-09T18%3A38%3A43Z&sr=b&sp=r&sig=9yoghWlQhO17j6aL3rW9bGHH6vgSVDaRQdEth9biu%2F8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:41 UTC, markwahl-msft commented on api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md
> +The following is an example of the request.
Added more text to this example, thanks.

2021-07-13 00:31 UTC, merged