[Azure AD] [ELM' created reprocess api
microsoftgraph/microsoft-graph-docs pull request #13425
Opened 2021-07-08 21:11 UTC by ajburnle

2021-07-08 21:12 UTC, opbld32 commented
Docs Build status updates of commit _[f21b9d6](https://github.com/ajburnle/microsoft-graph-docs/commits/f21b9d6060d1c490227071f89c25116c803f68c9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2d41abeb)

<a id="2d41abeb"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107082111494233-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-08T00%3A17%3A34Z&ske=2021-07-15T00%3A22%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-08T21%3A07%3A10Z&se=2021-08-08T21%3A12%3A10Z&sr=b&sp=r&sig=88cXcMRdT9BZzm7guQ74YZfgP9En1A9wGwWPzgBdmVk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 01:14 UTC, opbld31 commented
Docs Build status updates of commit _[0cf34f8](https://github.com/ajburnle/microsoft-graph-docs/commits/0cf34f8eb0a5e9038d33d452e491ea0762792338)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107090113135172-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A50%3A03Z&ske=2021-07-13T07%3A55%3A03Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T01%3A09%3A27Z&se=2021-08-09T01%3A14%3A27Z&sr=b&sp=r&sig=hmI3%2BR3Kmvn1kbyM8JllWNb4EP%2FVC7cW9M%2FRn2fkVwc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 01:22 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +| Delegated (work or school account) | EntitlementManagement.ReadWrite.CurrentUser |
are both work or school account?

2021-07-09 01:23 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +| Delegated (work or school account) | EntitlementManagement.ReadWrite.CurrentUser |
are both work or school account?

2021-07-09 01:25 UTC, ajburnle commented on api-reference/beta/resources/accesspackageassignment.md
> +| [Reprocess accessPackageAssignment](../api/accesspackageassignment-reprocess.md) | | Automatically reevaluate and enforce a user’s assignments for a specific access package.|
I need the return type for this methods chart

2021-07-09 01:25 UTC, ajburnle commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +| [Reprocess accessPackageAssignmentRequest](../api/accesspackageassignment-reprocess.md) | | Automatically retry a user’s request for access to an access package.|
I need the return type for this methods chart

2021-07-09 08:18 UTC, wandeg commented on changelog/Microsoft.DirectoryServices.json
> +<<<<<<< HEAD
Looks like a merge conflict wasn't resolved properly.

2021-07-12 06:49 UTC, DebashisChoudhury-MSFT commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +| Delegated (work or school account) | EntitlementManagement.ReadWrite.CurrentUser |
Remove this .CurrentUser permission, this string is not live yet (and changing as well)

2021-07-12 06:50 UTC, DebashisChoudhury-MSFT commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +| Delegated (work or school account) | EntitlementManagement.ReadWrite.CurrentUser |
Remove .Current permission

2021-07-12 18:00 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +POST ttps://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentRequests/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
We're missing the `h` in https here ^ @ajburnle

2021-07-12 18:01 UTC, sponnada approved these changes
I left one comment but everything else looks good to me.

2021-07-14 23:49 UTC, opbld32 commented
Docs Build status updates of commit _[4e34a26](https://github.com/ajburnle/microsoft-graph-docs/commits/4e34a26ca2b1bb157d648c5ca3c7fbb3474a8ea0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2b5bbf1f)

<a id="2b5bbf1f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107142349242350-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A25%3A02Z&ske=2021-07-20T08%3A30%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T23%3A44%3A47Z&se=2021-08-14T23%3A49%3A47Z&sr=b&sp=r&sig=hnpJWtoxD4J%2BKagjvSkM7J%2F3y51Y%2ByvU8R2eQG1PhP0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 23:50 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +| Delegated (work or school account) | EntitlementManagement.ReadWrite.CurrentUser |
I'll have to ask, but I don't think we can publish without permissions

2021-07-14 23:50 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +| Delegated (work or school account) | EntitlementManagement.ReadWrite.CurrentUser |
@FaithOmbongi Can we publish these docs without the permissions section?

2021-07-14 23:51 UTC, opbld34 commented
Docs Build status updates of commit _[c702dd7](https://github.com/ajburnle/microsoft-graph-docs/commits/c702dd7e99ccc446efa78a8c9f4834b682f9f5c4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d56f9dc9)

<a id="d56f9dc9"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107142351328944-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A52%3A39Z&ske=2021-07-20T07%3A57%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T23%3A46%3A55Z&se=2021-08-14T23%3A51%3A55Z&sr=b&sp=r&sig=60RuL1T6FEAthJMfAhQVF3FzxEF%2FMdvSB3U81Sqw44k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 23:52 UTC, opbld32 commented
Docs Build status updates of commit _[c702dd7](https://github.com/ajburnle/microsoft-graph-docs/commits/c702dd7e99ccc446efa78a8c9f4834b682f9f5c4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-69c97a81)

<a id="69c97a81"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107142351430517-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A27%3A53Z&ske=2021-07-20T08%3A32%3A53Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T23%3A47%3A24Z&se=2021-08-14T23%3A52%3A24Z&sr=b&sp=r&sig=KSFITPdcPk%2FOAjMigfQY679Usd7pjkIWU2XMwC3yz8s%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 23:53 UTC, opbld34 commented
Docs Build status updates of commit _[6c39eaa](https://github.com/ajburnle/microsoft-graph-docs/commits/6c39eaa2137a8651f87faf20391d51524854805f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-608c69f7)

<a id="608c69f7"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107142352585258-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A37%3A23Z&ske=2021-07-20T08%3A42%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T23%3A48%3A19Z&se=2021-08-14T23%3A53%3A19Z&sr=b&sp=r&sig=sffSY4X5oV4B%2FdaMxsDyvOlXfIMbz3NYb9bA9lli0vQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-14 23:59 UTC, opbld33 commented
Docs Build status updates of commit _[92671d3](https://github.com/ajburnle/microsoft-graph-docs/commits/92671d38ad6f8596125f103819e32496e950f4ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107142357468569-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A49%3A27Z&ske=2021-07-20T07%3A54%3A27Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T23%3A54%3A36Z&se=2021-08-14T23%3A59%3A36Z&sr=b&sp=r&sig=sGjRlT8WFHOK4vnVa8NrN8gP2Yp3%2BeAOEhNYGdS3PI0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 00:51 UTC, opbld34 commented
Docs Build status updates of commit _[3ba89c6](https://github.com/ajburnle/microsoft-graph-docs/commits/3ba89c6d890bcfb22c3a61cf9e9301c2b6efb0de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150049513134-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A49%3A27Z&ske=2021-07-20T07%3A54%3A27Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T00%3A46%3A36Z&se=2021-08-15T00%3A51%3A36Z&sr=b&sp=r&sig=5mpCnItLARTMlsugjmr4iEC9U6NSQVP341pVCHelOpA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 00:53 UTC, opbld31 commented
Docs Build status updates of commit _[97fc306](https://github.com/ajburnle/microsoft-graph-docs/commits/97fc30694ac79e134464464a2730d7a674a3347c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150052030449-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A25%3A02Z&ske=2021-07-20T08%3A30%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T00%3A48%3A36Z&se=2021-08-15T00%3A53%3A36Z&sr=b&sp=r&sig=A9Nu8u5b3zuYBMKeAQGJSu3MU7JnfgIhUo00derzNs0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:20 UTC, opbld31 commented
Docs Build status updates of commit _[53033fd](https://github.com/ajburnle/microsoft-graph-docs/commits/53033fde8069da72505de5e8cdfc7ef06ff19331)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150118568715-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T21%3A54%3A41Z&ske=2021-07-21T21%3A59%3A41Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A15%3A21Z&se=2021-08-15T01%3A20%3A21Z&sr=b&sp=r&sig=xX%2F0muJzqjZfBJnQjil5TPD30%2BNlceorPzP3hYdm2%2Fc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:29 UTC, opbld33 commented
Docs Build status updates of commit _[76c151b](https://github.com/ajburnle/microsoft-graph-docs/commits/76c151bb134697750d3acba9c10c4fbbff475b6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) | [Details](#user-content-9ad8e0c28c1844f0ad256d90876c361f-b6772aca)
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="9ad8e0c28c1844f0ad256d90876c361f-b6772aca"></a>
### [api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md)
 - **Line 64, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '[HTTP]') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150127480544-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A34%3A59Z&ske=2021-07-20T08%3A39%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A24%3A14Z&se=2021-08-15T01%3A29%3A14Z&sr=b&sp=r&sig=HAWE6fA5%2BIJBs6BTkP%2BvOPTa%2BCzm5t7%2FiYMWeFayvj4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:30 UTC, opbld31 commented
Docs Build status updates of commit _[a1ef18b](https://github.com/ajburnle/microsoft-graph-docs/commits/a1ef18b9a76713feadaddb274d79633fc6c0076e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) | [Details](#user-content-9ad8e0c28c1844f0ad256d90876c361f-a3bfc52a)
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) | [Details](#user-content-e31a9382c403617514165d4295d59dab-a3bfc52a)
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="9ad8e0c28c1844f0ad256d90876c361f-a3bfc52a"></a>
### [api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md)
 - **Line 64, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '[HTTP]') are not allowed. You can only have one top-level heading.`````
 - **Line 64, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 '[HTTP]' is duplicated with other articles: 'beta/api/accesspackageassignment-reprocess.md(64,1), beta/api/accesspackageassignmentrequest-reprocess.md(64,1)'. First level headings must be unique within a docset.`````

<a id="e31a9382c403617514165d4295d59dab-a3bfc52a"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md)
 - **Line 64, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '[HTTP]') are not allowed. You can only have one top-level heading.`````
 - **Line 64, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 '[HTTP]' is duplicated with other articles: 'beta/api/accesspackageassignment-reprocess.md(64,1), beta/api/accesspackageassignmentrequest-reprocess.md(64,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150128493099-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A46%3A13Z&ske=2021-07-20T07%3A51%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A25%3A54Z&se=2021-08-15T01%3A30%3A54Z&sr=b&sp=r&sig=bRzkyb7vSxIK5H0ncks8obe9HhJX5vGOwyinmaNqWJ0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:43 UTC, opbld30 commented
Docs Build status updates of commit _[ebafdba](https://github.com/ajburnle/microsoft-graph-docs/commits/ebafdba501750a55d84f6836259f4152f1098931)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) | [Details](#user-content-e31a9382c403617514165d4295d59dab-3b66580b)
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="e31a9382c403617514165d4295d59dab-3b66580b"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md)
 - **Line 64, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '[HTTP]') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150142049196-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T07%3A50%3A51Z&ske=2021-07-20T07%3A55%3A51Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A38%3A36Z&se=2021-08-15T01%3A43%3A36Z&sr=b&sp=r&sig=SPl4ige0lkjPy0Ju5GtnNDUzD8RdC0NR6conILzdT3s%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:45 UTC, opbld31 commented
Docs Build status updates of commit _[9268594](https://github.com/ajburnle/microsoft-graph-docs/commits/92685941df328a4ee61293b04248504f0773c2f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107150142506701-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A31%3A12Z&ske=2021-07-20T08%3A36%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T01%3A40%3A15Z&se=2021-08-15T01%3A45%3A15Z&sr=b&sp=r&sig=Q91tKpZQnLXzwUOWtTUI3ggfZX2WtUphRW8Z3Yjc5tI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 01:50 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +HTTP/1.1 202 Accepted
error is saying this format is wrong

2021-07-15 01:50 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +HTTP/1.1 202 Accepted
error is saying this format is wrong

2021-07-15 01:50 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentRequests/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
error wants GET instead of POST

2021-07-15 01:50 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignments/d82eb508-acc4-43cc-bcf1-7c1c4a2c073b/reprocess
error wants GET instead of POST

2021-07-16 19:13 UTC, opbld30 commented
Docs Build status updates of commit _[ea41c8f](https://github.com/ajburnle/microsoft-graph-docs/commits/ea41c8f64df96aad02a7fef5828c3645aeb0afa8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161911544668-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A10%3A46Z&ske=2021-07-23T08%3A15%3A46Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T19%3A08%3A34Z&se=2021-08-16T19%3A13%3A34Z&sr=b&sp=r&sig=LpwirDtbH2MaUjZQbC%2BuCyEbdijMU3kBBCXtXLKzZHA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:15 UTC, opbld31 commented
Docs Build status updates of commit _[0e89ab0](https://github.com/ajburnle/microsoft-graph-docs/commits/0e89ab03e804211a16678205a2bfdd738acddf15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161912386769-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A05%3A46Z&ske=2021-07-23T08%3A10%3A46Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T19%3A10%3A16Z&se=2021-08-16T19%3A15%3A16Z&sr=b&sp=r&sig=I3SplXzMbQwbmG7ObScm33zBWFX%2BXLZAm50eOVNCP5E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:21 UTC, opbld33 commented
Docs Build status updates of commit _[9472b57](https://github.com/ajburnle/microsoft-graph-docs/commits/9472b57ec1c40473ea5382875c6db3ad479a7236)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161920258748-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A08%3A34Z&ske=2021-07-23T08%3A13%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T19%3A16%3A58Z&se=2021-08-16T19%3A21%3A58Z&sr=b&sp=r&sig=micAbpWJFYfzNOOfdMXF9IgYQrgwpi%2BvA6TdGiJBrrE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:24 UTC, opbld31 commented
Docs Build status updates of commit _[6579f13](https://github.com/ajburnle/microsoft-graph-docs/commits/6579f13ea5acaf2faeea17c5468057bfd366a424)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161923098172-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A01%3A15Z&ske=2021-07-23T08%3A06%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T19%3A19%3A43Z&se=2021-08-16T19%3A24%3A43Z&sr=b&sp=r&sig=1%2Bvy%2F2xC0knQTj9Vf%2Bi9sxjVnjm%2BiYZQItPan7v%2BAYw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:29 UTC, sponnada approved these changes

2021-07-16 19:29 UTC, opbld33 commented
Docs Build status updates of commit _[6345b75](https://github.com/ajburnle/microsoft-graph-docs/commits/6345b759eab844a5a4fe124712dbfbb2743b4735)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161928201944-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T07%3A57%3A04Z&ske=2021-07-23T08%3A02%3A04Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T19%3A24%3A56Z&se=2021-08-16T19%3A29%3A56Z&sr=b&sp=r&sig=aiAWD8BwkArOsrhFRo2eeEfX52PS4OR4wcT9gN2fpD0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 19:31 UTC, opbld33 commented
Docs Build status updates of commit _[66a5011](https://github.com/ajburnle/microsoft-graph-docs/commits/66a5011a479b3d03bad7e8b0b97b7d8a624d008e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107161928541546-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T09%3A18%3A34Z&ske=2021-07-23T09%3A23%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T19%3A26%3A43Z&se=2021-08-16T19%3A31%3A43Z&sr=b&sp=r&sig=GsE0ACdlc28CtOBeighJzNwIW5F0CMhejaS132iMKNU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 07:41 UTC, FaithOmbongi requested changes

2021-07-19 07:41 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +None
Same comment
```suggestion
```

2021-07-19 07:41 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +If successful, this method returns a `202 Accepted` response code. If the assignment doesn't exist, this method will return `404` or `400` if the ID is not valid.
If successful, this method returns a `202 Accepted` response code. If the assignment doesn't exist, that is, the **id** isn't valid, this method will return `400 Bad request` or a `400 Not found` response code.

2021-07-19 07:41 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +> **Note:** The response object shown here might be shortened for readability.
Same comment
```suggestion
```

2021-07-19 07:41 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +      ],
- For actions and functions, ApiChange is **Method**
- ChangedApiName is the method name as it's referred to in the CSDL. For example, **reprocess**.
- Resource and property names are camelCased except in URLs.
- Description - you are adding the method name, e.g. reprocess, to a resource. i.e. "Added the [reprocess](public link) action to the [accessPackageAssignment](public link) resource. Just confirm your public links. Some are hitting 404s.
- Please see the [Changelog guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog) or other examples in this changelog doc.

2021-07-19 07:45 UTC, FaithOmbongi submitted a review, later dismissed

2021-07-19 07:45 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignment.md
> +| [Reprocess accessPackageAssignment](../api/accesspackageassignment-reprocess.md) | | Automatically reevaluate and enforce a user’s assignments for a specific access package.|
Return type is **None** because your API topics show the action doesn't return a response object.
```suggestion
| [Reprocess accessPackageAssignment](../api/accesspackageassignment-reprocess.md) | None | Automatically reevaluate and enforce a user’s assignments for a specific access package.|
```

2021-07-19 07:45 UTC, FaithOmbongi commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +| [Reprocess accessPackageAssignmentRequest](../api/accesspackageassignment-reprocess.md) | | Automatically retry a user’s request for access to an access package.|
```suggestion
| [Reprocess accessPackageAssignmentRequest](../api/accesspackageassignment-reprocess.md) | None | Automatically retry a user’s request for access to an access package.|
```

2021-07-23 18:01 UTC, opbld32 commented
Docs Build status updates of commit _[1923fb4](https://github.com/ajburnle/microsoft-graph-docs/commits/1923fb4604c872a384531252e09f8b8b692f4c49)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8e40827f)

<a id="8e40827f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231801113498-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-23T06%3A42%3A25Z&ske=2021-07-30T06%3A47%3A25Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T17%3A56%3A33Z&se=2021-08-23T18%3A01%3A33Z&sr=b&sp=r&sig=tGfhGsiqkGMZeyiLABUwqGmjU2yzHKvIajC8XfczAc0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:01 UTC, opbld30 commented
Docs Build status updates of commit _[a594406](https://github.com/ajburnle/microsoft-graph-docs/commits/a594406178f28604c8c799a4afaa5bd86de6e497)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f7ce38f5)

<a id="f7ce38f5"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231801232232-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A32%3A49Z&ske=2021-07-26T02%3A37%3A49Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T17%3A56%3A55Z&se=2021-08-23T18%3A01%3A55Z&sr=b&sp=r&sig=43ruwWyEFGZwJOKhnOcIh6e2B0UNXgFutkLMOPtA%2FQk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:02 UTC, opbld32 commented
Docs Build status updates of commit _[a594406](https://github.com/ajburnle/microsoft-graph-docs/commits/a594406178f28604c8c799a4afaa5bd86de6e497)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-63bbc1ae)

<a id="63bbc1ae"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231801335942-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A25%3A36Z&ske=2021-07-26T03%3A30%3A36Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T17%3A57%3A25Z&se=2021-08-23T18%3A02%3A25Z&sr=b&sp=r&sig=HI7OXXB1sNszTugjpWpGhn9jMZ41wS%2FeIqhWnJBg5c0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:02 UTC, opbld30 commented
Docs Build status updates of commit _[b08959e](https://github.com/ajburnle/microsoft-graph-docs/commits/b08959ec02f10c7b2e09f5f2b72a49aee6411c6c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:03 UTC, opbld33 commented
Docs Build status updates of commit _[369d165](https://github.com/ajburnle/microsoft-graph-docs/commits/369d1659b238f6495901b3e2b9bc12403d5e5baa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5591c310)

<a id="5591c310"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231803067174-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A27%3A45Z&ske=2021-07-26T03%3A32%3A45Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T17%3A58%3A50Z&se=2021-08-23T18%3A03%3A50Z&sr=b&sp=r&sig=C6x9BeHZTfoPRyWp9TzbeWPD2qZCc5hYkWCfA5jCVL0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:04 UTC, opbld31 commented
Docs Build status updates of commit _[8fa490a](https://github.com/ajburnle/microsoft-graph-docs/commits/8fa490adeb2371504fb359a9c62581aa0973ba02)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8b4de805)

<a id="8b4de805"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231803475363-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-23T07%3A59%3A10Z&ske=2021-07-30T08%3A04%3A10Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T17%3A59%3A21Z&se=2021-08-23T18%3A04%3A21Z&sr=b&sp=r&sig=lXo9axYY%2F6pQRAa2UHPZYhoaSJoUJzptWOq0syIokOM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:04 UTC, opbld34 commented
Docs Build status updates of commit _[9e6e5ea](https://github.com/ajburnle/microsoft-graph-docs/commits/9e6e5ea4c68446eaa39320b53d367fed060953d9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ee63cf85)

<a id="ee63cf85"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231804094081-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A39%3A52Z&ske=2021-07-26T02%3A44%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T17%3A59%3A55Z&se=2021-08-23T18%3A04%3A55Z&sr=b&sp=r&sig=JjfCssJ6X960seGZzww8PacSJJPJqq%2Fzm1x%2Bb1xqa7c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:05 UTC, opbld32 commented
Docs Build status updates of commit _[c8831e8](https://github.com/ajburnle/microsoft-graph-docs/commits/c8831e81752ccdd65762744b569db2a3bf62ad36)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-021f83d6)

<a id="021f83d6"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107231803286343-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T03%3A12%3A24Z&ske=2021-07-26T03%3A17%3A24Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T18%3A00%3A42Z&se=2021-08-23T18%3A05%3A42Z&sr=b&sp=r&sig=jzsNvuHn42lBttx9G8L779QRt1Yg8YTCQRE0kUgTPZ4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 22:57 UTC, opbld31 commented
Docs Build status updates of commit _[6c4209e](https://github.com/ajburnle/microsoft-graph-docs/commits/6c4209e90916dff3403c2e88ce4e978969d012c8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bd3114ad)

<a id="bd3114ad"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262256528524-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A11%3A44Z&ske=2021-08-02T02%3A16%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T22%3A52%3A35Z&se=2021-08-26T22%3A57%3A35Z&sr=b&sp=r&sig=%2FTGDFXrTJxLt4M1t7vNWBRrUrszwCbQwUnvog5Bao0A%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 22:58 UTC, opbld30 commented
Docs Build status updates of commit _[be3120c](https://github.com/ajburnle/microsoft-graph-docs/commits/be3120cc20fb16aa329f5ee2faaa0730c81ca5b6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5c4360ae)

<a id="5c4360ae"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262257321641-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A00%3A53Z&ske=2021-08-02T03%3A05%3A53Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T22%3A53%3A06Z&se=2021-08-26T22%3A58%3A06Z&sr=b&sp=r&sig=0jyDqABmnAJfrC2M%2FLzAhZrY4Q27TXVVMJFJhBegYDA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 22:58 UTC, opbld32 commented
Docs Build status updates of commit _[540c111](https://github.com/ajburnle/microsoft-graph-docs/commits/540c111878d2b461325991636b54a5f4feaa6c97)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 22:58 UTC, opbld34 commented
Docs Build status updates of commit _[e258e56](https://github.com/ajburnle/microsoft-graph-docs/commits/e258e56794ef4b1d3f4fa4fc5dd054f6f33ff0aa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b6341cc6)

<a id="b6341cc6"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262257219004-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A12%3A15Z&ske=2021-08-02T03%3A17%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T22%3A53%3A45Z&se=2021-08-26T22%3A58%3A45Z&sr=b&sp=r&sig=y3B9xaH5F6r0kTlNe7FqyNjE9HXsAUJrDmssWh9eBrE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 23:01 UTC, opbld32 commented
Docs Build status updates of commit _[af6aa83](https://github.com/ajburnle/microsoft-graph-docs/commits/af6aa832f8bc0cceff6d1a3606fd749e2eb176a4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-81a1a44b)

<a id="81a1a44b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262300431101-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A34%3A12Z&ske=2021-08-02T02%3A39%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T22%3A56%3A04Z&se=2021-08-26T23%3A01%3A04Z&sr=b&sp=r&sig=3rqloNfoBZHFQu2gDOCDFC39Izsd%2FMuALgyt1NV176Y%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 23:02 UTC, opbld33 commented
Docs Build status updates of commit _[f1d6098](https://github.com/ajburnle/microsoft-graph-docs/commits/f1d60984cb651d0ccc2bea86b55bde84661872a9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bd8b07c1)

<a id="bd8b07c1"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262302014747-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A42%3A12Z&ske=2021-08-02T03%3A47%3A12Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T22%3A57%3A22Z&se=2021-08-26T23%3A02%3A22Z&sr=b&sp=r&sig=%2FPzxOZT7%2FTjUrciTOkQYG2iFTDv%2F0i%2F3yEiqIjSqJZ4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 23:04 UTC, opbld33 commented
Docs Build status updates of commit _[cfd4a04](https://github.com/ajburnle/microsoft-graph-docs/commits/cfd4a04c9fbe04a6813029143c820881b00c2cd0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f41dae8f)

<a id="f41dae8f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262304252304-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A07%3A56Z&ske=2021-08-02T03%3A12%3A56Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T22%3A59%3A48Z&se=2021-08-26T23%3A04%3A48Z&sr=b&sp=r&sig=trz7FeIWTdHcGmKYk%2F9Sg7y1RNxUxQ%2BmvL7PG7DeqoQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 23:28 UTC, opbld34 commented
Docs Build status updates of commit _[eadda37](https://github.com/ajburnle/microsoft-graph-docs/commits/eadda371171cb7952847a162e13ff1f560b44ee0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107262326299379-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-23T07%3A59%3A10Z&ske=2021-07-30T08%3A04%3A10Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T23%3A23%3A04Z&se=2021-08-26T23%3A28%3A04Z&sr=b&sp=r&sig=%2F0OSjGxtzIznAnFjM4ZC3R8C%2BoHNXka0UR4F%2F19gzfk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 03:20 UTC, opbld34 commented
Docs Build status updates of commit _[eadda37](https://github.com/ajburnle/microsoft-graph-docs/commits/eadda371171cb7952847a162e13ff1f560b44ee0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107270318468695-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A12%3A15Z&ske=2021-08-02T03%3A17%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T03%3A15%3A26Z&se=2021-08-27T03%3A20%3A26Z&sr=b&sp=r&sig=r%2B%2FzeoO3vih%2FClSOGOYA9NYYTJryt1NiGqfk7W%2B3PR0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-27 22:39 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce a user’s assignments for a specific access package.
maybe here we could link to the accessPackageAssignment resource type - https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta @ajburnle

2021-07-27 22:40 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +If successful, this method returns a `202 Accepted` response code. If the assignment doesn't exist, that is, the **id** isn't valid, this method will return `400 Bad request` or a `400 Not found` res
link to the access package assignment resource type again - https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta

2021-07-27 22:41 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically retry a user’s request for access to an access package.
link to accessPackageAssignmentRequest resource type - https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta

2021-07-27 22:42 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +If successful, this method returns a  `202 Accepted` response code. If the assignment doesn't exist, that is, the id isn't valid, this method will return a `400 bad request` or a `400 not found`respo
this should say "If the assignment request doesn't exist..."

also, link to the request resource type again - https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta

2021-07-27 22:44 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +If successful, this method returns a `202 Accepted` response code. If the assignment doesn't exist, that is, the **id** isn't valid, this method will return `400 Bad request` or a `400 Not found` res
the method will return 404 Not Found if the assignment was not found and 400 Bad Request if the id isn't valid

2021-07-27 22:46 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +If successful, this method returns a  `202 Accepted` response code. If the assignment doesn't exist, that is, the id isn't valid, this method will return a `400 bad request` or a `400 not found`respo
same as above - it will return 404 Not Found if the accessPackageAssignmentRequest object was not found and 400 Bad Request if the id isn't valid

2021-07-27 22:48 UTC, sponnada reviewed
@ajburnle left some comments - other than those, everything else looks good. feel free to ping me if you have questions; i'll keep an eye out on teams. thank you!

2021-07-28 07:46 UTC, DebashisChoudhury-MSFT commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +| Delegated (work or school account) | EntitlementManagement.ReadWrite.CurrentUser |
Should be just work account. Also we should not have the EntitlementManagement.ReadWrite.CurrentUser permission in that list.

2021-07-28 14:18 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +If successful, this method returns a `202 Accepted` response code. If the assignment doesn't exist, that is, the **id** isn't valid, this method will return `400 Bad request` or a `400 Not found` res
I linked to the resource type at the top

2021-07-28 14:27 UTC, opbld32 commented
Docs Build status updates of commit _[5fc7326](https://github.com/ajburnle/microsoft-graph-docs/commits/5fc7326990e7de169529c84ef8d3bead78ff089d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281425163740-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A44%3A44Z&ske=2021-08-04T03%3A49%3A44Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T14%3A22%3A49Z&se=2021-08-28T14%3A27%3A49Z&sr=b&sp=r&sig=CH1uSh%2FqawsOoqrCtppzPB1upl2NNS2aKSxzjMesIck%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 14:29 UTC, opbld33 commented
Docs Build status updates of commit _[fae8c18](https://github.com/ajburnle/microsoft-graph-docs/commits/fae8c184812f71b36762dd75b658311cd6866461)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281428231932-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A39%3A27Z&ske=2021-08-04T03%3A44%3A27Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T14%3A24%3A53Z&se=2021-08-28T14%3A29%3A53Z&sr=b&sp=r&sig=bs9wzYd1kq2Ef0yYp6D37BbvpxFOOJ9YeOfKfJudOeY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 14:32 UTC, opbld34 commented
Docs Build status updates of commit _[ab220aa](https://github.com/ajburnle/microsoft-graph-docs/commits/ab220aa328de22422ce44bed66fbf1a0ddd21634)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281430498336-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A20%3A50Z&ske=2021-08-04T04%3A25%3A50Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T14%3A27%3A20Z&se=2021-08-28T14%3A32%3A20Z&sr=b&sp=r&sig=nUFK7KFiVgxqDOhL8Vh4NpvxpdIZxDTtH%2BYsC9rv958%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 14:39 UTC, opbld34 commented
Docs Build status updates of commit _[c285274](https://github.com/ajburnle/microsoft-graph-docs/commits/c28527469a7750b60b50876f13a27d00555f2e2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281437079585-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T04%3A14%3A23Z&ske=2021-08-04T04%3A19%3A23Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T14%3A34%3A44Z&se=2021-08-28T14%3A39%3A44Z&sr=b&sp=r&sig=ZajipeVKilnBqrT4yMm11ZAU5kkr8vWbgv1q3gJO3cw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 14:56 UTC, opbld32 commented
Docs Build status updates of commit _[f18dbe3](https://github.com/ajburnle/microsoft-graph-docs/commits/f18dbe36ce7909ffb809acc55699a9afac2ba5b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281454330183-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A27%3A19Z&ske=2021-08-04T03%3A32%3A19Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T14%3A51%3A31Z&se=2021-08-28T14%3A56%3A31Z&sr=b&sp=r&sig=Q44O7QcQ8A5fvJTF90waVLvzqOSe6kUMWpQxsRS%2FrO4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 15:41 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically retry an [accessPackageAssignment](../resources/accesspackageassignment.md) object of a use
let's make this "callers can automatically retry a user's request for access to an access package. It is performed on the [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta) object.

2021-07-28 15:44 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +If successful, this method returns a  `202 Accepted` response code and retries the request of the [accessPackageAssignment](../resources/accesspackageassignment.md) object. If the assignment doesn't
let's make this "...retries the request. If the [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta) object doesn't exist..."

2021-07-28 15:46 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +If successful, this method returns a `202 Accepted` response code and reevaluates and enforces the user's assignments of the [accessPackageAssignment](../resources/accesspackageassignment.md) object.
capitalize Request in Bad Request

2021-07-28 15:46 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +If successful, this method returns a  `202 Accepted` response code and retries the request of the [accessPackageAssignment](../resources/accesspackageassignment.md) object. If the assignment doesn't
capitalize Request in Bad Request

2021-07-28 18:22 UTC, opbld33 commented
Docs Build status updates of commit _[292627b](https://github.com/ajburnle/microsoft-graph-docs/commits/292627b602a88bdf27ea9e5e0a01483fa629760a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281820351618-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A50%3A39Z&ske=2021-08-04T03%3A55%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T18%3A17%3A12Z&se=2021-08-28T18%3A22%3A12Z&sr=b&sp=r&sig=3voJk%2FBYDL%2FbnteyA5PLmH4TcAUsRBRPaNp86rag3Jk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 18:33 UTC, opbld31 commented
Docs Build status updates of commit _[2e5a29b](https://github.com/ajburnle/microsoft-graph-docs/commits/2e5a29bd264afe103d10e8090cdd159022a0dcbb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281831487085-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A33%3A41Z&ske=2021-08-04T03%3A38%3A41Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T18%3A28%3A18Z&se=2021-08-28T18%3A33%3A18Z&sr=b&sp=r&sig=c4GTwRRkB6v9soYrM10SxL7qz9pHnnYpAZHLEygM2eU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 19:54 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +If successful, this method returns a  `202 Accepted` response code and retries the request. If the [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) object doesn't exis
capitalize Request in Bad Request and we're good to go!

2021-07-28 19:54 UTC, sponnada approved these changes

2021-07-28 19:57 UTC, opbld33 commented
Docs Build status updates of commit _[b794092](https://github.com/ajburnle/microsoft-graph-docs/commits/b7940926f2c52e4a7a9095b2f5969d911ce4a358)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107281955373205-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A25%3A00Z&ske=2021-08-04T03%3A30%3A00Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T19%3A52%3A57Z&se=2021-08-28T19%3A57%3A57Z&sr=b&sp=r&sig=Etewqf5CejkD5sC0h1%2FVCNuvnhhrptGBo8W%2BArPNABI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-28 20:05 UTC, ajburnle commented
#sign-off

2021-07-28 20:10 UTC, ajburnle commented
#sign-off

2021-07-30 23:02 UTC, opbld32 commented
Docs Build status updates of commit _[7a7d302](https://github.com/ajburnle/microsoft-graph-docs/commits/7a7d3028384da091949ef911755ac9becce8da0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202107302301030581-13425%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-30T10%3A46%3A18Z&ske=2021-08-06T10%3A51%3A18Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-30T22%3A57%3A33Z&se=2021-08-30T23%3A02%3A33Z&sr=b&sp=r&sig=5wE%2BNRMZgSaVrdRE8t3w61EWuxLaZG%2FAFPkuSNNzXsc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-02 07:10 UTC, FaithOmbongi requested changes
Proposing minor fixes and mostly requesting that we add context to the actions.

2021-08-02 07:10 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +     },
```suggestion
       "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
       "ApiChange": "Method",
       "ChangedApiName": "reprocess",
       "ChangeType": "Addition",
       "Description": "Added the [reprocess](https://docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess.md) action to the [accesspackageassignment](https://docs.microsoft.com/en-us/graph/api/acesspackageassignment.md) resource.",
       "Target": "reprocess"
     },
```

2021-08-02 07:10 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +       "Target": "accessPackageAssignmentRequest"
```suggestion
       "Id": "762ccb17-76e5-41b3-b0e7-e37591f954a1",
       "ApiChange": "Method",
       "ChangedApiName": "reprocess",
       "ChangeType": "Addition",
       "Description": "Added the [reprocess](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageAssignmentRequest-reprocess?view=graph-rest-beta) action to the [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/resources/accessPackageAssignmentRequest?view=graph-rest-beta) resource.",
       "Target": "reprocess"
```

2021-08-02 17:18 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
1. The status needs to be Failed or Partially Delivered.
2. The accessPackageAssignment is retried, so if the action returns a 202, it means the status will be changed to Delivered

@FaithOmbongi

2021-08-02 17:50 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
Thanks @sponnada . Added a few review comments to this effect @ajburnle

2021-08-02 17:52 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +If successful, this method returns a `202 Accepted` response code and reevaluates and enforces the user's assignments of the [accessPackageAssignment](../resources/accesspackageassignment.md) object.
Users can't perform this action. Only admins with Access package assignment manager role (or higher) in ELM can perform this action.

2021-08-02 17:54 UTC, sponnada commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically retry a user's request for access to an access package. It is performed on the [accessPacka
- Users can't perform this action. Only admins with Access package assignment manager role (or higher) in ELM can perform this action.
- This action is most useful when there are failed and partially delivered requests within a 14-day time frame. It reduces friction since the user doesn't need to go to MyAccess and re-request the package. Instead, the admin can just reprocess the user's request in the Azure portal.

2021-08-02 18:02 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
@sponnada , could you confirm these statuses against the allowed values in accessPackageAssignmentRequest/requestState & in accessPackageAssignment/? properties? `PartiallyDelivered` is in accessPackageAssignmentRequest only.

2021-08-02 18:33 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
@FaithOmbongi to reprocess an accessPackageAssignment, it needs to be in the Delivered status. For accessPackageAssignmentRequest objects, they need to be in a Failed or Partially Delivered state.

2021-08-02 18:59 UTC, opbld30 commented
Docs Build status updates of commit _[dd01814](https://github.com/ajburnle/microsoft-graph-docs/commits/dd0181422be5d791c34c13c6c6baf876b4fb2da6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108021857173137-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=uz6gIplXXqLA1mlZxBkXQ2JVpxSrbiSxedxOBS4oXds%3D&st=2021-08-02T18%3A54%3A45Z&se=2021-09-02T18%3A59%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-02 19:02 UTC, opbld32 commented
Docs Build status updates of commit _[8e9aa6c](https://github.com/ajburnle/microsoft-graph-docs/commits/8e9aa6c1f93f6c9255994ae33e43431699b17bd6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108021858282020-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=CQWm1rJkhLFmTKDi%2FXtAATNyBeSmwLdh55FOlVcPrL0%3D&st=2021-08-02T18%3A57%3A28Z&se=2021-09-02T19%3A02%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-02 19:10 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
@sponnada [accessPackageAssignmentRequest](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta) does not list `Failed` as a value of **requestState**...

2021-08-02 20:19 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
@FaithOmbongi just seeing this -- I'm not sure if that object needs to be updated because there is a Failed state displayed on the UI for assignment requests. 

![Screenshot 2021-08-02 142601](https://user-images.githubusercontent.com/9565544/127918726-ac00cfcd-73f4-446a-8d14-11fa74c34c65.png)

2021-08-02 21:41 UTC, ajburnle commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
@FaithOmbongi Do you want this to say "Delivery failed" like the portal?

2021-08-03 10:38 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
@sponnada @ajburnle 

> Do you want this to say "Delivery failed" like the portal?

No. We must only declare values as they are returned by the API.
Sri, is it possible that `DeliveryFailed` (or something similar) is a possible value and should be listed in [the doc](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta)? Gaps like these are common with String types that have allowed values. This info is not available in the CSDL. Could you confirm internally?

2021-08-03 22:29 UTC, opbld33 commented
Docs Build status updates of commit _[1b5ebef](https://github.com/ajburnle/microsoft-graph-docs/commits/1b5ebefb905ded61efc4810d1eba08c3a520582e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108032224155085-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=91FWscZgDf4JNxB3dSuml4PnW9S8ec404q1C%2BNYRwzw%3D&st=2021-08-03T22%3A24%3A35Z&se=2021-09-03T22%3A29%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-04 16:40 UTC, sponnada commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
@FaithOmbongi @ajburnle you’re right - there’s a gap here in the documentation. There is a “DeliveryFailed” status that is returned when the reprocess fails. We’ll need to use that value here and also update the properties table in the [accessPackageAssignmentRequest resource type page](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest) to include that value for requestState

2021-08-04 16:50 UTC, FaithOmbongi reviewed
@ajburnle Could you add `DeliveryFailed` to the list of possible values for the **requestState** property of accessPackageAssignmentRequest? Thank you.

2021-08-04 16:50 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md) object of a user’s assignments for a specific access package. The **assignmentState** of the access package must be `Delivered` for the administrator to reprocess the user's assignment. Only admins with the Access Package Assignment Manager role, or higher, in Azure AD entitlement management can perform this action.
```

2021-08-04 16:50 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignmentrequest-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically retry a user's request for access to an access package. It is performed on the [accessPacka
```suggestion
In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically retry a user's request for access to an access package. It is performed on an [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) object whose **requestState** is in a `DeliveryFailed` or `PartiallyDelivered` state. 
```

2021-08-04 16:51 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageassignment-reprocess.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), callers can automatically reevaluate and enforce an [accessPackageAssignment](../resources/accesspackageassignment.md
Awesome, thanks for confirming @sponnada .

2021-08-05 16:55 UTC, opbld33 commented
Docs Build status updates of commit _[b849f2a](https://github.com/ajburnle/microsoft-graph-docs/commits/b849f2ac3b0f6049982e46720465fbb92d3aacc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051653098759-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=QpH5QqcSC58HtHHVG8CE%2Fee9cpOKU9SRzCM%2BW6nf%2BZc%3D&st=2021-08-05T16%3A50%3A33Z&se=2021-09-05T16%3A55%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 16:57 UTC, opbld34 commented
Docs Build status updates of commit _[3dd6dc7](https://github.com/ajburnle/microsoft-graph-docs/commits/3dd6dc7569822560799447266fab1025839d305a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051653337503-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2FqRhRDr%2BERMyh2%2F43pLByhxRXOMJDIL2VP%2BBtQmFXdA%3D&st=2021-08-05T16%3A52%3A06Z&se=2021-09-05T16%3A57%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 17:49 UTC, opbld30 commented
Docs Build status updates of commit _[02b286f](https://github.com/ajburnle/microsoft-graph-docs/commits/02b286f524096dd007dd3593416d82d4868166f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051748215179-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=PcG3jqlvr9RBLWKaW%2BRteJ34vGcJymYzRw1FUexT%2F5s%3D&st=2021-08-05T17%3A44%3A53Z&se=2021-09-05T17%3A49%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 17:50 UTC, ajburnle commented
> Proposing minor fixes and mostly requesting that we add context to the actions.

2021-08-05 17:51 UTC, ajburnle commented
@FaithOmbongi I have updated the properties table. Can you please close that review item so I can sign off?

2021-08-05 17:52 UTC, opbld30 commented
Docs Build status updates of commit _[02b286f](https://github.com/ajburnle/microsoft-graph-docs/commits/02b286f524096dd007dd3593416d82d4868166f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051750272476-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9%2BIhYPNn877IofFSgzn6Bj3%2FDGAmNvVXDMAen0FsQuY%3D&st=2021-08-05T17%3A47%3A51Z&se=2021-09-05T17%3A52%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 17:57 UTC, FaithOmbongi approved these changes

2021-08-05 17:57 UTC, opbld34 commented
Docs Build status updates of commit _[696a92d](https://github.com/ajburnle/microsoft-graph-docs/commits/696a92db811b82231d8792a8b862feccb39f9464)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051756051938-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=vFctVUk%2BwP%2BlAdggHokYzWQiHCJXjjPe86FHFDK5PME%3D&st=2021-08-05T17%3A52%3A35Z&se=2021-09-05T17%3A57%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 18:00 UTC, opbld31 commented
Docs Build status updates of commit _[25c9149](https://github.com/ajburnle/microsoft-graph-docs/commits/25c914952ff62829a4adc89ba5544598bc0d5bbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108051756478022-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=TNVptv8QHNXkE69Lmq%2BjQwCgxHwm7VRoFrO9GuE0KJc%3D&st=2021-08-05T17%3A55%3A09Z&se=2021-09-05T18%3A00%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 18:12 UTC, ajburnle commented
@CelesteDG Hey Celeste, the content review is complete and I think this is ready to merge. Thanks!

2021-08-10 02:52 UTC, opbld33 commented
Docs Build status updates of commit _[cddc6f5](https://github.com/ajburnle/microsoft-graph-docs/commits/cddc6f5e68f2763e61b18133abc9e56d3406f5b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignment-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-reprocess.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/api/accesspackageassignmentrequest-reprocess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-reprocess?view=graph-rest-beta&branch=pr-en-us-13425) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/ajburnle/microsoft-graph-docs/blob/azuread-elm-reprocessapassignments/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108100251078123-13425%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HNeM3B5aHQa1N%2B4EfYVUssVViL1u3HJ%2Fs9J0aunAUD4%3D&st=2021-08-10T02%3A47%3A35Z&se=2021-09-10T02%3A52%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 02:56 UTC, merged